### ISSUE TITLE
Design a nicer image loader progress indicator

### ISSUE THREAD

**Issue by magsout** [webcompat/webcompat.com#1000]

**Comment by miketaylr** [comment]
(this might actually be #1011, we have one but it's hidden on mobile at least).

(or would this be about tracking upload progress?)

**Comment by miketaylr** [comment]
We can show upload progress to the server easily, btw. Just need a sweet design.

**Comment by magsout** [comment]
Upload progress would awesome, but simple loader is good. The point is to show that something happen

**Comment by miketaylr** [comment]
(oops, used wrong issue in my commit message)

**Comment by miketaylr** [comment]
Changing the title since we already have a loader image... it's just not as awesome as it could be.

**Comment by miketaylr** [comment]
cf. #492

**Comment by miketaylr** [comment]
<img width="228" alt="screen shot 2016-04-22 at 5 30 50 pm" src="https://cloud.githubusercontent.com/assets/67283/14756570/fcbae7fc-08af-11e6-8e40-36a49d7e2cf6.png">

Maybe we could do something like have the bg of the lightbulb fill from light to dark (if that makes sense, sort of like "fill up" animation). But it would have to work no matter where you were scrolled, or what viewport size you have.

**Comment by softvision-sergiulogigan** [comment]
I was about to suggest an improvement on the Loading Spinner, and I found this thread. I definitely think we should do something about that spinner. It doesn't quite match the website's sleek design.

**Comment by zoepage** [comment]
Cross-referencing bug #1433 (so we don't forget) ;)

**Comment by karlcow** [comment]
This one needs to be solved. I don't know if it's the same from elsewhere. But from Japan, if I didn't know better I would abandon the image upload most of the time. It takes around 10+s  without any visual indication that we are waiting for an image upload.

**Comment by karlcow** [comment]
We also need to check what takes so much time.

**Comment by karlcow** [comment]
See https://github.com/webcompat/webcompat-tests/issues/1266

**Comment by miketaylr** [comment]
> But from Japan, if I didn't know better I would abandon the image upload most of the time. It takes around 10+s without any visual indication that we are waiting for an image upload.

We currently show a spinner here:

![d5lut52d7f](https://user-images.githubusercontent.com/67283/31908056-417ed53c-b7fb-11e7-96ab-91d6f03572fb.gif)

But either it's not appearing for you (possible bug), or you didn't know to look there (UX bug). Does it not appear for you @karlcow?

**Comment by miketaylr** [comment]
Thinking about mobile users... that's probably a pretty bad experience.

**Comment by karlcow** [comment]
> But either it's not appearing for you (possible bug), or you didn't know to look there (UX bug). 

@miketaylr Upload an image in a comment :)  https://github.com/webcompat/webcompat-tests/issues/1266 are all comments upload.

**Comment by karlcow** [comment]
To summarize my tests in https://github.com/webcompat/webcompat-tests/issues/1266
in this issue directly.

Uploading a 2.1 Mb image on 1 shot (probably high variation for network speed)

* ~ 13s through webcompat.com
* ~ 8s through github.com
* ~ 0.236ms through local instance (aka in a local folder)

**Comment by zoepage** [comment]
If this issue is caused through the network, the best solution I guess seems to move from our setup to a distributed system. But this will take some time right @miketaylr ?

**Comment by karlcow** [comment]
@zoepage my issue is not so much about the time it takes.  The network is the network and uploads are slow for big images.

As we can see there is not much difference in between GitHub and webcompat so moving would not solve anything, it's about not having an uploader wheel/widget when **uploading an image from a comment**.

I guess I really failed at explaining this one. :D both @miketaylr and @zoepage are not understanding what I'm saying.  Sorry about that.

Tell me if you want me to explain again or do a screencast :)

**Comment by zoepage** [comment]
I find, 5 seconds a massive difference :D But yes, it looks like I misunderstood. 

So, as I understand it correctly there is an issue with uploading images in comments. Could you please explain again / in more detail @karlcow ? Thanks!

**Comment by karlcow** [comment]
@zoepage @miketaylr 
1. Go to https://staging.webcompat.com/issues/1294
2. Add a comment with an image around 3Mb (desktop screenshot for example)
3. Start your chrono ;)

Basically because it takes a long time and there is no visual cue to tell the user that an upload is in the process, you might give up or continue typing text or even restart an upload. 

Sometimes it has happen to me that I posted the text comment without remembering that I started an upload. And the markup for the image shows up in the next comment form. :)

**Comment by miketaylr** [comment]
> I guess I really failed at explaining this one. :D both @miketaylr and @zoepage are not understanding what I'm saying.

Ah. That makes sense, and yep you're right. We probably should have a dedicated bug for the issue of missing progress for comment image upload, rather than pile on this issue of "design a nicer gif".

**Comment by miketaylr** [comment]
I think we can close this. The new design uses an animation, not an image.
