### ISSUE TITLE
[feature-request] Tag certain bugs as NSFW and hide images by default?

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat.com#1001]
Often we get reports related to NSFW websites. They can sometimes contain screenshots that are adult-oriented. I wonder if we could add a `status-nsfw` (or similar, status is probably the wrong prefix), and it would overlay an opaque graphic over any embedded images. You could then click the image to display it, but they would be hidden by default.

(or maybe we have a settings panel somewhere where you opt-in to always see, dunno)

Useful if you're debugging websites and have children around, or are in a public space.

One example is https://github.com/webcompat/web-bugs/issues/2428.

Low priority, but it might be a nice feature to add.

**Comment by hallvors** [comment]
:+1: :)

I don't think this label needs a prefix - it can be simply "nsfw" IMO. Possibly "note-nsfw" but I don't think we will have a group of such labels.

This can be added in a very simple way - so simple we could make it a good-first-patch I think:

1) Add CSS to censor images by default inside body.wc-js-nsfw (or something like that) (where "censor" can be opacity:0.02)
2) Add CSS to show image anyway if it has a "showme" class
3) Add JS to add the wc-js-nsfw classname to BODY if the issue we're loading has a nsfw tag
4) Add JS to add the "showme" class to IMG if it's clicked.

We probably should insert an explanation somewhere saying why the images are hidden.

**Comment by miketaylr** [comment]
Buzzfeed has an implementation of this: https://www.buzzfeed.com/katienotopoulos/play-23-rounds-of-the-deadliest-game-ever?utm_term=.stpjYylBX#.ttvG7j5Ml

(There's a site bug in Firefox, so open this in Chrome to see it in its full glory.)

**Comment by miketaylr** [comment]
> There's a site bug in Firefox

https://bugzilla.mozilla.org/show_bug.cgi?id=1275069

**Comment by miketaylr** [comment]
https://github.com/webcompat/web-bugs/issues/2700 is a good example of where this would be useful (hint: it has a nsfw screenshot in the bug report).

**Comment by karlcow** [comment]
@miketaylr agreed. The choice of colors on this website is disturbing :p

**Comment by miketaylr** [comment]
hehe

**Comment by miketaylr** [comment]
So this is like 90% done, but I'm struggling with how to nicely indicate "click to reveal" (because I suck at UI).

**Comment by miketaylr** [comment]
Let's start with this, then someone with actual skills can improve it:

<img width="895" alt="screen shot 2016-06-10 at 9 09 30 am" src="https://cloud.githubusercontent.com/assets/67283/15967096/b6882b48-2eeb-11e6-8de9-b7dd2945631f.png">

**Comment by hallvors** [comment]
Seems superb to me :)

**Comment by miketaylr** [comment]
Cool, thanks! Just need to write some tests now.

**Comment by karlcow** [comment]
The way the messaging is done on the site The Big Picture is not bad.
For example: http://archive.boston.com/bigpicture/2008/11/congos_crisis_worsens.html

![capture d ecran 2016-06-10 a 20 26 49](https://cloud.githubusercontent.com/assets/505230/15974668/e943eb86-2f49-11e6-8bca-e4051cadb859.png)
