### ISSUE TITLE
Contributor page style differences

### ISSUE THREAD

**Issue by adamopenweb** [webcompat/webcompat.com#1005]
I noticed on the contributors page that the styling is slightly different in Chrome/Safari/Opera compared to Firefox. @magsout is this the expected behavior?

Chrome left, FF right:
<img width="891" alt="chromeff" src="https://cloud.githubusercontent.com/assets/6587558/14476447/c795ca42-00d5-11e6-9701-05911ca7f624.png">

**Comment by magsout** [comment]
oops, nah, it's a bug
