### ISSUE TITLE
After sharing an issue logged  the option remains gray/blank

### ISSUE THREAD

**Issue by ioana-chiorean** [webcompat/webcompat.com#1006]
1) Go to webcompat and log an issue. 
2) At the thanks message after entering the issue - share on TW or FB 
3) Return to page and log at the buttons

Expected: Button should be visible 
Actual: button is gray or blank 

<img src="https://cloud.githubusercontent.com/assets/1391451/14494469/aa920b72-0193-11e6-8ee2-425bd597f33b.jpg" width="300" height="550" />
<img src="https://cloud.githubusercontent.com/assets/1391451/14494467/aa90534a-0193-11e6-890e-4d241cb67ec8.jpg" width="300" height="550" />
![Desktop](https://cloud.githubusercontent.com/assets/1391451/14494468/aa90e7a6-0193-11e6-82a2-47b4c752baae.png)

**Comment by miketaylr** [comment]
@ioana-chiorean WEIRD.

Ideally this maybe goes away with #646, but it's maybe worth figuring out before then.

**Comment by miketaylr** [comment]
Simplified STR:

1) Go to https://webcompat.com/thanks/222
2) Click on Share on Twitter
3) Select the webcompat tab again

Expected: Share on Twitter is gray
Actual: It's all white.

Kind of a weird bug, something to do with focus?

**Comment by magsout** [comment]
Yes focus issue 
![capture d ecran 2016-04-27 a 22 17 31](https://cloud.githubusercontent.com/assets/1997108/14866826/dc7a1e76-0cc5-11e6-8572-9cbeeea19bcd.png)
