### ISSUE TITLE
Some way to enlarge a screenshot that is not readable at column width

### ISSUE THREAD

**Issue by hallvors** [webcompat/webcompat.com#1017]
See devtools screenshot in https://webcompat.com/issues/2483 - it would be nice if it enlarged on hover or click..

**Comment by miketaylr** [comment]
This feels related to #722 -- embed smaller images by default, and then give the ability to see the larger images.

**Comment by karlcow** [comment]
Yup it's the plan and on my todo list. Now that the other one is merged.
And I'm having already the pseudo code for this.

**Comment by karlcow** [comment]
Closing as a duplicate of #722
