### ISSUE TITLE
Animated GIF corruption + size increase

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat.com#1024]
If you upload an animated GIF, it's being corrupted at some level.

Compare the source:

![redbox](https://cloud.githubusercontent.com/assets/67283/14872285/5d7a1ece-0cb0-11e6-9bf9-cac79a66eb26.gif)

And the uploaded file:

![687474703a2f2f73746167696e672e776562636f6d7061742e636f6d2f75706c6f6164732f323031362f342f39346361626634392d333539322d343836312d613936392d3637353635303932363936362e676966](https://cloud.githubusercontent.com/assets/67283/14872288/67fee014-0cb0-11e6-8fdd-c0d6f256e742.gif)

Also the original file-size was 2.7MB, the corrupted version is 5.6MB 😮 

@karlcow something you want to tackle?

**Comment by miketaylr** [comment]
I just looked at a recent PNG I uploaded:

Original size: 1.2MB
Uploaded size: 963kb. 

Very cool.

**Comment by miketaylr** [comment]
Likely a PIL bug and not ours, I think:

https://github.com/webcompat/webcompat.com/blob/master/webcompat/api/uploads.py#L89-L92

**Comment by karlcow** [comment]
The corrupted GIF issues. yes this is known. We discussed about it already.
see https://github.com/webcompat/webcompat.com/issues/710#issuecomment-194709238

And you can see my discussion with Pillow owners
https://github.com/python-pillow/Pillow/issues/1717

**Comment by karlcow** [comment]
We also discussed it here 
https://github.com/karlcow/webcompat.com/commit/3240856d6bd5ed83645d79a1fc12144666dbb5f5

**Comment by karlcow** [comment]
Note that I can try to solve it on Pillow side, but that will take a bit of time, because I think it's quite a complex issue with color encoding compression, etc. 

I wonder if for animated gif, we could convert them to compressed mp4 movies. as we are able to detect them.

**Comment by karlcow** [comment]
@miketaylr Oh! http://zulko.github.io/moviepy/

Let's test something with that.

```

**Comment by karlcow** [comment]
Just to be more explicit. Just the 3 lines of code.

```python
import moviepy.editor as mp
movie_gif = mp.VideoFileClip("/Users/karl/Desktop/animated.gif")
movie_gif.write_videofile("/Users/karl/Desktop/animated.webm")
```

**Comment by miketaylr** [comment]
> We also discussed it here

Yeah, I remember that. I thought the idea was that we weren't going to touch animated GIFs with Pillow, to prevent the corruption. But I misunderstood, because just saving the image (via `Image.save()` ruins it.

(I guess my bad for not catching this at review.)

Another option might be detect if it's animated via Pillow, then save the original file manually via `File.write()`. 

@karlcow for the mp4 approach, do you have a sense of how long it takes to convert? I see you used webm, but Safari can't play those (or Edge currently), so probably not ideal. If it's fast, this seems cool. If it's slow maybe we skip Pillow for animated GIFs like mentioned above.

**Comment by karlcow** [comment]
Yeah good points. Probably slow. 

```python
>>> timeit.timeit('import moviepy.editor as mp; movie_gif = mp.VideoFileClip("/Users/karl/Desktop/animated.gif"); movie_gif.write_videofile("/Users/karl/Desktop/animated.mp4", verbose=False)', number=10)
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 44/44 [00:00<00:00, 1001.18it/s]
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 44/44 [00:00<00:00, 1093.55it/s]
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 44/44 [00:00<00:00, 1105.09it/s]
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 44/44 [00:00<00:00, 966.25it/s]
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 44/44 [00:00<00:00, 1054.83it/s]
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 44/44 [00:00<00:00, 1025.64it/s]
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 44/44 [00:00<00:00, 961.58it/s]
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 44/44 [00:00<00:00, 972.44it/s]
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 44/44 [00:00<00:00, 1020.62it/s]
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 44/44 [00:00<00:00, 1054.83it/s]
1.6520440578460693
```

**Comment by miketaylr** [comment]
Let's not fix this. 💣
