### ISSUE TITLE
Support Drag and Drop for image upload

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat.com#1025]
I could have sworn there was an open issue for this, but I can't find it.

It should be possible to drag and drop an image both into a comment and on the reporting form rather than using the file picker.

When we get to this, https://github.com/webcompat/webcompat.com/blob/master/webcompat/api/uploads.py#L54 will need to be tweaked to accept all valid image types.

**Comment by hallvors** [comment]
We already have this for the reporting form, just needs to be done for the comments too.

**Comment by miketaylr** [comment]
> We already have this for the reporting form, just needs to be done for the comments too.

Sort of. :)

It's not "proper" DnD, it's just that (some?) browsers will let you drop a file on `<label><input type=file></label>` and do the right thing™ (right now our label covers the whole image preview area). I don't know that it makes much of a difference right now, but if we change the design of the form upload, we'll lose our sort-of support.

**Comment by hallvors** [comment]
WOW. I didn't know about this LABEL trick, but it's very cool 8-)

**Comment by miketaylr** [comment]
Ehhh, probably never gonna do this.

**Comment by magsout** [comment]
@miketaylr It already works on the submission form ?

**Comment by miketaylr** [comment]
@magsout yeah, it "fake" works, because dropping an image on a label associated with a form element with serve as a drop target. I think the issue was originally intended to be for dropping an image anywhere on the page, like imgur does. 

FWIW, I think our current solution is good enough. :)
