### ISSUE TITLE
Simplifiy/unify/clean up UA parsing code

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat.com#1035]
See @karlcow's suggestion in https://github.com/webcompat/webcompat.com/pull/1032/files#r61705335.

**Comment by miketaylr** [comment]
The `get_foo` UA parsing methods could share some code, right now it's kind of clunky.

**Comment by karlcow** [comment]
@moraveyo did you make a pull request? You can ask for review/comments on the pull request.

**Comment by karlcow** [comment]
Ah yes there is 
https://github.com/webcompat/webcompat.com/pull/1504

**Comment by moraveyo** [comment]
If UA or OS is "Other",
and suddenly there is some model or version info,
should we make it "Other (Tablet) 7.11" or just "Unknown"?

**Comment by miketaylr** [comment]
> or just "Unknown"?

Unknown seems less confusing, I think.
