### ISSUE TITLE
Labels on issue no longer update when labels are toggled on/off

### ISSUE THREAD

**Issue by hallvors** [webcompat/webcompat.com#1045]
Load an issue, toggle a label on or off

Bug: the labels list does not update.

**Comment by karlcow** [comment]
Same issue here, since the backend for labels has been rewritten.

**Comment by hallvors** [comment]
Possibly a missing piece from that rewrite?

**Comment by hallvors** [comment]
(I'm pretty sure this is more recent though.. Will look into it.)

**Comment by hallvors** [comment]
That rewrite was
https://github.com/webcompat/webcompat.com/commit/92f978f58cc7343886ceff912ddf5ce081887d6c
