### ISSUE TITLE
Disallow non-webby URIs?

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat.com#1054]
For example, https://github.com/webcompat/web-bugs/issues/2591#issuecomment-220498160.

Filing bugs against file://, about:blank, about:config, chrome://settings, etc. -- not very useful? We could show an error saying how they're non-webby URLs.

**Comment by karlcow** [comment]
We should do this properly by indeed explaining why they are not useful. Probably show an explanation as soon as the user starts to enter something which is not starting with `http://` or `https://`  That would also help us give more information on what we consider to be a Web Compat issue.

**Comment by miketaylr** [comment]
👍
