### ISSUE TITLE
Update contributing.md for node installation and virtual environment related issues for Ubuntu

### ISSUE THREAD

**Issue by deepthivenkat** [webcompat/webcompat.com#1059]
1) Node.js is a prerequisite for building webcompat locally.
After installing node, node -v doesn't work.

2) In Ubuntu, even after successful installation of the following commands 

[sudo] virtualenv env
source env/bin/activate

and completing installation of everything in requirements.txt, the user still gets the following error:

Traceback (most recent call last):
  File "run.py", line 38, in <module>
    raise ImportError('{0}\n\n{1}'.format(e, IMPORT_ERROR))
ImportError: No module named flask.ext.github

==============================================
It seems like you don't have all dependencies.
Please re-run : pip install -r requirements.txt
    
==============================================

**Comment by deepthivenkat** [comment]
#1060

**Comment by miketaylr** [comment]
👍
