### ISSUE TITLE
Restructure webcompat organization (to prevent costing a ton of money)

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat.com#1062]
(Not really a webcompat.com bug, but whatever.)

So according to https://github.com/blog/2164-introducing-unlimited-private-repositories orgs can only have 5 members at the $25 a month plan (which is what we currently pay). We don't have any private repos so I don't see any reason to pay the $151.00 a month fee for our current organization structure.

Instead I propose we have a small team of organization members (@webcompat-bot can be our founding member and president!) and convert everyone else to "[outside collaborators](https://help.github.com/articles/adding-outside-collaborators-to-repositories-in-your-organization/)".

You won't get a fancy org sticker, but you will still have the same rights you had before.

I'm not in a rush to do this (it seems GitHub is giving us at least a year), but thought I would start a discussion.

Thoughts? Objections? Alternatives?

cc @webcompat/collaborators @webcompat/core-developers

**Comment by magsout** [comment]
What? You paid yet something @miketaylr ? Organization is free if you have no private repo? Or I don't understand the new price ?

**Comment by karlcow** [comment]
@magsout interesting. 
This https://help.github.com/articles/about-organizations/
seems to contradict https://github.com/pricing

**Comment by magsout** [comment]
@karlcow @miketaylr 

I don"t think is a contradiction, see:

![capture d ecran 2016-05-24 a 07 30 46](https://cloud.githubusercontent.com/assets/1997108/15493043/7c786b4c-2181-11e6-8642-ae43da65eebf.png)

it's about upgrade my organisations.. 


If I try to create new organisation (https://github.com/organizations/new) there is two plan:

![capture d ecran 2016-05-24 a 07 32 13](https://cloud.githubusercontent.com/assets/1997108/15493064/a522964e-2181-11e6-87f6-b1f85768c817.png)

**Comment by karlcow** [comment]
So basically what you are saying is that @miketaylr should "downgrade" to open without private repos. That makes sense.

**Comment by magsout** [comment]
@karlcow yes exactly.

According to @miketaylr message
>We don't have any private repos so

**Comment by miketaylr** [comment]
> What? You paid yet something @miketaylr ?

We pay a $25/month "Bronze" plan to be nice and support GitHub since we rely on them (not because we want or use private repos).

Hmm, I'm not sure about the "unlimited members and public repos for free" option, I think that's the legacy option. But I can email support, because that would be the best.

(The email I got said we have ~12 months to switch to the new billing, so it's possible that's the legacy plan, or it's possible I'm totally wrong!)

**Comment by miketaylr** [comment]
Also maybe we just be lazy and solve this once they force us to in a year. 😴

**Comment by magsout** [comment]
> We pay a $25/month "Bronze" plan to be nice and support GitHub since we rely on them (not because we want or use private repos).

We can add `Get unlimited private repositories.` to @webcompat-bot ton support Github ?

**Comment by zoepage** [comment]
@miketaylr after 11 months this might pop up soon, I guess?

**Comment by denschub** [comment]
Thanks for bringing this up, @zoepage.

Moving everyone in a role as "outside collaborators" would not work, those count as users as well. Whatever we do, I'd **strongly** vote against using a "personal" account like the webcompat bot as a pseudo org for many reasons, which I hope are obvious, but I can elaborate if someone wants me to.

I'd go with downgrading the org to the free plan. Some of us (including me) already have a paid private GitHub account, so that's a bit of support. We could even make the webcompat bot a paid account. Also, we still have @mozilla, and I am pretty sure we also pay for that (disclaimer for everyone else: I actually do not have any facts, but I strongly assume it's that way), so we do not have to feel bad.

**Comment by zoepage** [comment]
I second @denschub. 

The amount of users is more important than private repos (if thats the only criteria). Those could live in our private accounts and the others invited to collaborate. Moved to a public one on webcompat, if necessary. 

Also, +1 on mozilla and the payed plan.

**Comment by miketaylr** [comment]
Thanks for the discussion everyone. For now, the plan is when/if GitHub enforces this new pricing structure they will let us know (according to email from support, anyways). So, we'll burn that bridge when we get to it. 🔥 

And yeah, the smart move will be to move to the no private repos stuff.
