### ISSUE TITLE
label:undefined in issues list

### ISSUE THREAD

**Issue by adamopenweb** [webcompat/webcompat.com#1066]
Accidentally clicked on a random place on the issues list page and think I found a bug.

STR:
1) Navigate to https://webcompat.com/issues?page=1&per_page=50&state=open&stage=all&sort=created&direction=desc
2) Click in the open area just to the left of the Firefox label for any bug listed

Expected results:
Nothing

Actual results:
Filter for the search changes to label:undefined

**Comment by miketaylr** [comment]
lol.
