### ISSUE TITLE
URL tracker cleanup 

### ISSUE THREAD

**Issue by karlcow** [webcompat/webcompat.com#1071]
I'm struggling with this issue. Should we clean up automagically trackers from URIs being reporter. 

Recent example of an URL:

```
http://www.zarpo.com.br/mavsa-resort/resort-de-luxo-interior-sao-paulo-all-inclusive-6378.html?code=Mzg0MjkwOjk2ZDA5M2U2MWI0YzFlOTY4ZmE4Zjc4OWI4OTgyZWQ3&utm_source=seo&utm_medium=magazine&utm_campaign=artigo&utm_content=all_inclusive
```

There are well known trackers which are easy to remove.

**Comment by miketaylr** [comment]
I think so. For this URL I would keep `code` (because I don't know if it somehow affects the page), but remove the `utm_*` garbage.

@karlcow, is there a list of well-known link tracker params that you know of?

**Comment by karlcow** [comment]
Another example:

* https://medium.com/ben-and-dion/the-ideal-web-experience-d3df0178a25d#.u368byrxx
