### ISSUE TITLE
Stealthily remove 'web-bugs/' from URL if we mess up when changing github->webcompat URL patterns

### ISSUE THREAD

**Issue by hallvors** [webcompat/webcompat.com#1072]
We know Github's URLs to webcompat issues are of this form:
``https://github.com/webcompat/web-bugs/issues/1751``
while webcompat.com's are simpler:
https://webcompat.com/issues/1751

I have solid evidence (in the form of an E-mail from @karlcow on Tue, 31 May 2016 09:09:17 +0900 to a non-public mailing list) that I'm not the only person who sometimes copies Github URLs but prefer sending out webcompat.com links and therefore edits the URL directly.

If we get this wrong, we may send somebody a URL looking like 
https://webcompat.com/webcompat/web-bugs/issues/1751
https://webcompat.com/web-bugs/issues/1751
https://webcompat.com/webcompat/issues/1751
and neither of those will work. It is however trivial to change the JavaScript to remove any '/webcompat/' or '/web-bugs/' strings from location.pathname before fetching bug data. I propose we add a small hack to handle these URLs to make the computers slightly more forgiving of us easily distracted humans. :)

**Comment by miketaylr** [comment]
Seems good. We could also do a redirect to the right place, at the nginx proxy or flask application level.

**Comment by miketaylr** [comment]
(flask app seems preferable, since it will be documented and included in the repo)

**Comment by miketaylr** [comment]
We probably don't want to do this, but if someone wants to send a PR, we can reconsider!
