### ISSUE TITLE
Right-clicking on issue label to open in new tab does not have correct URL param state or search term in input box

### ISSUE THREAD

**Issue by deepthivenkat** [webcompat/webcompat.com#1075]
Steps to reproduce : 
1)Go to [issues](https://webcompat.com/issues?page=1&per_page=50&state=open&stage=all&sort=created&direction=desc) page. 

2)Right click on a label for any of the issues -> Open link in a new tab
 Eg : firefox-mobile

Expected Results:

In url:   [https://webcompat.com/issues?page=1&per_page=50&state=open&stage=all&sort=created&direction=desc&q=label%3Abrowser-firefox-mobile](url)
In search box:         _label:browser-firefox-mobile_

Actual Results:

In url:   [https://webcompat.com/issues?page=1&per_page=50&state=open&stage=all&sort=created&direction=desc&labels=browser-firefox-mobile](url)  

**The above URL is not same as expected**

In search box:                    _empty   **[problem]**_

Should I change the final URL parameter from labels=browser-firefox-mobile to q=label:browser-firefox-mobile so as to maintain uniformity for the following two cases:

I) when querying from search box

II) when clicking on a label for an issue in /issues page

**Comment by miketaylr** [comment]
I think part of the fix here will come from your suggested change to the `href` in https://github.com/webcompat/webcompat.com/issues/1074#issuecomment-222753048. The second part will be parsing the `q` param on page load and populating the search input if it finds something like looks like `label: foo` (via the `search:update` event in issue-list.js).
