### ISSUE TITLE
Clicking on invalid label doesn't display issues with invalid label

### ISSUE THREAD

**Issue by deepthivenkat** [webcompat/webcompat.com#1082]
Steps to reproduce: 
1. Go to All-Issues
2. Select "Closed" milestone/Status.
3. Click on the "invalid" label for a bug.

Actual Results:
The search query updates to "label:status-invalid"
Issue list does not display any issues.

Expected Results
The search query updates to "label:status-invalid"
Issue list should display all the issues with "invalid label".

![invalid label click not working](https://cloud.githubusercontent.com/assets/7373087/15807831/e350ada4-2b84-11e6-8a26-e3f7f80d52ec.gif)

**Comment by miketaylr** [comment]
This is by design, for now.
