### ISSUE TITLE
[Desing] SearchBar

### ISSUE THREAD

**Issue by magsout** [webcompat/webcompat.com#1089]
A little enhancement 

Before:
![capture d ecran 2016-06-11 a 14 25 21](https://cloud.githubusercontent.com/assets/1997108/15985026/5afe2da4-2fe0-11e6-8417-a588c404b5a7.png)

After:

![capture d ecran 2016-06-11 a 14 23 53](https://cloud.githubusercontent.com/assets/1997108/15985028/600e3de8-2fe0-11e6-9e6e-cc252e42b3e7.png)

What do you think ?

**Comment by miketaylr** [comment]
Much nicer. 👍
