### ISSUE TITLE
Improved labels

### ISSUE THREAD

**Issue by magsout** [webcompat/webcompat.com#1097]

**Comment by magsout** [comment]
@webcompat/collaborators The list of labels that I think interesting to webcompat 

![capture d ecran 2016-06-17 a 14 32 00](https://cloud.githubusercontent.com/assets/1997108/16152149/465dbb50-3498-11e6-980a-1003511a612d.png)

**Comment by karlcow** [comment]
@magsout thanks.
Some questions/comments.


## Scope
* `scope: features`: When proposing a new feature.
* `scope: design`: This requires design? CSS or prototype?

What about bugs? 


## Status
* `status: accepted` Do you mean for a feature? or for design?
* `status: blocked` 
* `status: discussion` what is the difference in between `needs reviews` and `discussion`
* `status: needs changes` Could you explain again? Usually for code, we comment in the pull request where we explain the changes. 
* `status: needs reviews` The proposed features needs review or the code?
* `status: good first bug`
* `status: WIP`

## Type
* `type: bug`
* `type: documentation`
* `type: enhancement` Which type of issues?
* `type: feature request` what's the difference in between this and scope: features

**Comment by magsout** [comment]
@karlcow 

`Scope` means, this subject of issue is about what ?  features, design.  We can filtering issue about one subject we want..

>status: accepted Do you mean for a feature? or for design?

`status`  is the status of issue, we can talk about a new feature, new design. When we decide what we want with this issue we can accept, We review an issue, then everything is fine, so we add `status: accepted`. A contributor has an idea, but we can't code it right now, so we add `status: blocked` because before we have to, I don't know, for example implement this feature. 

So with this status we can know issues are accepted for example work on them.

>status: discussion

is equal to `needs-feeback`. We have new idea and we want to talk together before working on it for example.


>status: needs changes Could you explain again? Usually for code, we comment in the pull request where we explain the changes. 

It is used specifically for PR. You review a PR, then there is some typo or mistacke, so we add this status for the owner of PR. That means, owner of PR have to to fix errors before the PR can be accepted and merged.

> status: needs reviews The proposed features needs review or the code?

the PR needs review. It is used specifically for PR

> type: enhancement Which type of issues?

All. it's for design, feature..

>type: feature request what's the difference in between this and scope: features

it's similar, but we have to combine both. 

For example:

It's about design and I have an idea
`scope: design` - `type: feature request`

it's about feature but there is a bug:

`scope: features` - `type: bug`

**Comment by karlcow** [comment]
Thanks. understood.
@miketaylr @tagawa @deepthivenkat comments?

**Comment by miketaylr** [comment]
I'm in favor.

**Comment by deepthivenkat** [comment]
@magsout @karlcow 

What is >status:WIP ?

I think instead of >status: discussion we can have >status: needs feedback or >status: needs comments if the latter one is clear.

In favor of the rest of the labels 👍

**Comment by magsout** [comment]
@deepthivenkat 

>What is status:WIP?

Work In Progress

>I think instead of status: discussion we can have status: needs feedback or status: needs comments if the latter is clearer.


yeah, sounds good

**Comment by miketaylr** [comment]
I suppose we can have a "status: add to changelog" label as well.

**Comment by miketaylr** [comment]
I made a pass at converting labels: https://github.com/webcompat/webcompat.com/issues/labels.

I think I goofed by changing "needs-definition" to "scope: features". That should probably be "site-development"? I'm not sure what what "needs-definition" should be (if anything).

Also, we have "in progress" and "ready" -- which I guess Waffle uses? Would "status: accepted" be the new "ready"?

**Comment by magsout** [comment]
>I suppose we can have a "status: add to changelog" label as well.

Yes, sure

**Comment by magsout** [comment]
>I made a pass at converting labels: https://github.com/webcompat/webcompat.com/issues/labels.

Oh coool, awesome. 👍

>I think I goofed by changing "needs-definition" to "scope: features". That should probably be "site-development"? I'm not sure what what "needs-definition" should be (if anything).

Hum, right now I don't know 😮


>Also, we have "in progress" and "ready" -- which I guess Waffle uses? 

Yes.

>Would "status: accepted" be the new "ready"?

Hum, for example. In a PR, when you write r+ = `status : accepted `

**Comment by miketaylr** [comment]
> Hum, for example. In a PR, when you write r+ = status : accepted

OK, I misunderstood. In Waffle there's this "ready" label -- I don't know where it came from or how to configure it differently. It means something is ready to be worked on (is not in progress, or not in backlog). @karlcow did you set up waffle.io, or was that Alexa (maybe?)?

**Comment by karlcow** [comment]
`needs-definition` in my mind is a feature proposal without its architecture or UX defined.

@miketaylr I set up waffle, but didn't change the labels. I just took what was there by default. It is possible to associate tags to some state in waffle in 
https://waffle.io/webcompat/webcompat.com/settings/columns

**Comment by magsout** [comment]
>needs-definition in my mind is a feature proposal without its architecture or UX defined.

ah yes, good definition !

>Also, we have "in progress" and "ready" -- which I guess Waffle uses?

>@miketaylr I set up waffle, but didn't change the labels. I just took what was there by default. It is possible to associate tags to some state in waffle in
https://waffle.io/webcompat/webcompat.com/settings/columns


For in progress: `status : WIP` sounds good.. ?

**Comment by miketaylr** [comment]
Thanks @karlcow, I poked around waffle but couldn't find that.



> For in progress: status : WIP sounds good.. ?

Yep!

**Comment by karlcow** [comment]
@magsout are we done with this one? I guess we basically implemented it.

**Comment by karlcow** [comment]
@magsout ping? ;)

**Comment by magsout** [comment]
@karlcow ah yes ;) we can close
