### ISSUE TITLE
[bug] Rewriting link headers is wrong

### ISSUE THREAD

**Issue by karlcow** [webcompat/webcompat.com#1100]
On Github if we request:

`http --print h GET https://api.github.com/repos/webcompat/webcompat-tests/issues/398/comments 'Accept:application/json' | grep Link`

we get 

```
Link: <https://api.github.com/repositories/17839063/issues/398/comments?page=2>; rel="next", <https://api.github.com/repositories/17839063/issues/398/comments?page=4>; rel="last"
```
Then 

`→ http --print h GET 'https://api.github.com/repos/webcompat/webcompat-tests/issues/398/comments?page=2' 'Accept:application/json' | grep Link`

```
Link: <https://api.github.com/repositories/17839063/issues/398/comments?page=3>; rel="next", <https://api.github.com/repositories/17839063/issues/398/comments?page=4>; rel="last", <https://api.github.com/repositories/17839063/issues/398/comments?page=1>; rel="first", <https://api.github.com/repositories/17839063/issues/398/comments?page=1>; rel="prev"
```

BUT

on webcompat.

we do 

`→ http --print h GET 'http://localhost:5000/api/issues/398/comments' 'Accept:application/json'`

```
link: <comments?page=2>; rel="next", <comments?page=4>; rel="last"
```

Then
`→ http --print h GET 'http://localhost:5000/api/issues/398/comments?page=2' 'Accept:application/json'`

```
link: <comments?page=2>; rel="next", <comments?page=4>; rel="last"
```

**Comment by karlcow** [comment]
Thanks @deepthivenkat for finding the issue

**Comment by karlcow** [comment]
Related to #1101 which illustrates another issue.

**Comment by miketaylr** [comment]
@karlcow is this something you would like to fix?

**Comment by karlcow** [comment]
unittesting++ it helped me a lot in figuring out the right constraints for this one but the previous one.

Also I do not remember why we decided to do `/search/issues` instead of `/issues/search`. Retrospectively it seems like a bad idea.
