### ISSUE TITLE
PSA: Reverting master to last known good state

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat.com#1109]
There's been a number of accidental history mess-ups on master in the past few days, which leaves my confidence in master at below 100%.

I propose to revert master to the v2.6.1 tag state (which is what is currently deployed) by doing the following:

```
git checkout master
git reset --hard v2.6.1
git push --force origin master
```

This won't affect anyone's branches, for people working in branches. But if you happen to be working on some code on master (which is dangerous!), I plan on doing this at some point tonight (it's a holiday, so some point late). This means you need to make a branch of your current work before you pull master. 

(Rebasing your branch against master would probably be a good idea after this happens.)

cc @webcompat/core-developers

**Comment by magsout** [comment]
I agree with you 👍.

I don't know if it's possible but maybe we can disallow the availability to commit on master except for owner ?

**Comment by cch5ng** [comment]
just in case, I've only been working on the browserstack branch. but periodically I've been syncing with the master like:

```
git checkout master
git pull
git checkout browserstack
git merge master
```

my commit comments may look weird like: 'merge master with browserstack' but I have not pushed any changes to master.

I will use `git rebase master` moving forward. I'm good with your planned change.

**Comment by karlcow** [comment]
> I don't know if it's possible but maybe we can disallow the availability to commit on master except for owner ?

or just enforce a fork-only policy with pull requests (aka the way I currently do).

**Comment by karlcow** [comment]
Documented here http://www.otsukare.info/2016/04/14/git-workflow

**Comment by cch5ng** [comment]
> I don't know if it's possible but maybe we can disallow the availability to commit on master except for owner ?

> or just enforce a fork-only policy with pull requests (aka the way I currently do).

for the browserstack testing, I think it needs to be triggered by a branch commit to the main project. when I tried to trigger the tests by committing to a fork (my preference too), the tests would run on travis but not on browserstack.

**Comment by miketaylr** [comment]
Yeah, fork-only development is tricky with Travis and Browserstack -- it means they don't get access to secret stuff.

**Comment by karlcow** [comment]
Some background about security restrictions and tests.
https://docs.travis-ci.com/user/pull-requests#Security-Restrictions-when-testing-Pull-Requests

**Comment by miketaylr** [comment]
💣 Done now.

**Comment by karlcow** [comment]
👾 perfect. Let's play.

**Comment by karlcow** [comment]
ok for people like me who are working from forks.

```
git checkout -b backup master
git fetch upstream
git branch -D master
git checkout -b master upstream/master
```

And you are back in business. `git log --oneline`

```
e5bad88 v2.6.1 changelog update
c32adb6 Merge pull request #1087 from webcompat/issues/1001/1
bb38db5 Issue #1001. Add fixture data for Issue #396.
44eede9 Issue #1001. Add tests for toggling NSFW images.
55dc893 Issue #1001. Toggle between blurry and non-blurry images when clicking on NSFW images.
b4ce0e4 Merge pull request #1105 from tsl143/I1046
ab44b12 Merge pull request #1103 from webcompat/issues/1101/2
```
