### ISSUE TITLE
Proposal: Not merging your own PRs without an explicit r+ or lgtm

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat.com#1110]
Right now the Submission Guidelines mention asking for review explicitly:

https://github.com/webcompat/webcompat.com/blob/master/CONTRIBUTING.md#submission-guidelines

I think we should add a section about not merging your own PR unless the person reviewing has left an explicit "r+" or "lgtm" comment. Possible ways this happens:

1) Reviewee sends PR, asks for r?. Reviewer reviews, leaves r+.
2) Reviewee sends PR, asks for r?. Reviewer reviews, points out issues, asks for changes. Reviewee makes changes, asks again for r?, repeat until r+.

(admins should be able to merge w/o r+ or lgtm, in the case of fixing broken builds, etc.)

We should be able to enforce this w/ a bot: https://github.com/blog/2051-protected-branches-and-required-status-checks, but for now we can just trust each other.

Thoughts? @webcompat/core-developers

**Comment by magsout** [comment]
👍💯
Adding the required lgtm or r+ combined with a bot should be a good thing. We avoid mistakes and the clicks on merge button by accident

**Comment by magsout** [comment]
I can take a look  for adding a bot and update the documentation, If everyone agrees.

**Comment by karlcow** [comment]
@magsout for the bot, maybe that should be its own separate issue. I guess it will take a bit longer. 
I provided a suggestion for the prose. Any edits/comments are welcome in the
