### ISSUE TITLE
Give some breathing room to user avatar and comment box

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat.com#1113]
Our version (on left) feels very "cramped", compared to GitHub.

<img width="710" alt="screen shot 2016-07-05 at 11 55 53 am" src="https://cloud.githubusercontent.com/assets/67283/16590912/865a519c-42a7-11e6-91f4-13e3e7987a60.png">

**Comment by magsout** [comment]
@karlcow and I discussed at London about new Header. No more arrow, Avatar inside Header, and new Background color.

**Comment by miketaylr** [comment]
Ah, OK. Let's close this then!
