### ISSUE TITLE
The functional test "Issue-list - Loading URL with stage param loads issues" passed in my local, failed in Travis.

### ISSUE THREAD

**Issue by deepthivenkat** [webcompat/webcompat.com#1115]
File: /webcompat.com/tests/functional/issue-list-non-auth.js  
Test case: Issue-list - Loading URL with stage param loads issues

Output in my local machine:
![photo593046103980615619](https://cloud.githubusercontent.com/assets/7373087/16598012/78ac79d6-4319-11e6-963a-a0c248a6292e.jpg)

Output in Travis

https://travis-ci.org/webcompat/webcompat.com/builds/141281313#L1458

**Comment by deepthivenkat** [comment]
All the tests passed in my local machine. Whereas most tests failed in Travis.


![photo593046103980615620](https://cloud.githubusercontent.com/assets/7373087/16615484/9fb1eec8-4394-11e6-8591-dd014f1a3939.jpg)

**Comment by miketaylr** [comment]
I think this was fixed by #1150 (especially since Travis is green ATM).
