### ISSUE TITLE
Block specific user agent

### ISSUE THREAD

**Issue by adamopenweb** [webcompat/webcompat.com#1116]
We had some conversations about potentially blocking a specific user agent if it seems to be the source of spam. The one in question currently is:

```
Mozilla/5.0 (Android; Mobile; MyIE; rv:40.7) Gecko/40.7 Firefox/40.7
```

56% of all traffic to Webcompat.com in the last month came from this user agent.

After doing some digging we found the source of this comes from China. There is a modified version of Firefox for Android being distributed in China and users seem to be pressing the "Report Site Issue" button. We were able to download the APK and install on a test device that can be wiped after. The file is available here, use at your own risk.

```
http://m.myie9.com/
```

The default home page of the browser is: 

```
http://sj.myie9.com
```

It's not surprising that over 20% of traffic is going to the landing page:

```
https://webcompat.com/?open=1&url=http://sj.myie9.com/
```

So maybe we don't want to block this user agent after all. There's an opportunity for good bug reports from China, if webcompat.com is localized. Thoughts?

**Comment by karlcow** [comment]
nice findings.

**Comment by karlcow** [comment]
Maybe we could ask the beijing team what they think about this browser.

**Comment by miketaylr** [comment]
Yeah, would be interesting to know if @MDTsai knew anything about this browser (or site).

**Comment by miketaylr** [comment]
Another option: we prevent people from filing bugs on `http://sj.myie9.com/` (the landing site), on the assumption that it's heavily QA'd and likely people just trying out menu items.

**Comment by MDTsai** [comment]
The browser addresses speed, less crashing and customization for China(by addons), that's what I know. I can't understand why people click "Report Site Issue" so frequently? I can contact with the team to know the reason to put the button in there browser.

**Comment by karlcow** [comment]
@MDTsai What is the translation in Chinese for "Report Site Issue"?

**Comment by karlcow** [comment]
I meant on this specific browser. How the button was translated. My understanding is that sj.myie9.com acts as a built-in proxy. And I guess many sites must be failing be because of CSP or delay.

**Comment by MDTsai** [comment]
![screenshot_2016-07-13-14-18-36](https://cloud.githubusercontent.com/assets/5763237/16793634/12437022-4905-11e6-8b56-012bff9d5bd1.png)
On simplified Chinese, it's also "Report Site Issue", no difference. So it may not caused by user, but the browser connects to site fail?

**Comment by karlcow** [comment]
@MDTsai This screenshot is it  Firefox browser or MyIE browser?

**Comment by MDTsai** [comment]
@karlcow It's MyIE browser. My Firefox (and beta) on android doesn't have this button by default.

**Comment by karlcow** [comment]
Ah! so they skin the nightly or Aurora version. Interesting. 
From the past reports we had on webcompat, this is the breakdown of the 20 issues.

* sj.myie9.com: 10 issues Report usually empty
* m.myie9.com: 9 issues
  * 3 Links to http://m.myie9.com/androidaddons/ 
  * Link to http://m.myie9.com/helpanzhuo/#liuyan
  * 4 Links to http://m.myie9.com/badweb/ + something
     * ?http%3A%2F%2Fm1.t77.in%2F
     * ?http%3A%2F%2Fzj.kankan666.org%2Fad.html%3F%23z_15_20150315chuinian.com.cn
     * ?http%3A%2F%2Fm.97bbc.com%2F
     * ?http%3A%2F%2Fwwwvvvwww.ongai.com%2Fwm%2F2.html%3F%3Dwap1.shanghai-expo.com.cn%26rq%3D2015-4-13
* www.myie9.com: 1 issue

**Comment by MDTsai** [comment]
http://m.myie9.com/badweb/ with URL looks like a guide to user to install addon phony to switch to desktop chrome. Click the badweb + URL should redirect to the URL as described, but not work for me.
Does this happened only recently or periodically?

**Comment by adamopenweb** [comment]
@karlcow The big back button is an add-on.

**Comment by miketaylr** [comment]
> I can't understand why people click "Report Site Issue" so frequently? 

It could be that they're just testing out what it means. 

> I can contact with the team to know the reason to put the button in there browser.

Right now, if they're shipping a "Nightly" it will be enabled by default (soon in Aurora). Or it could be that they enabled it on purpose (?).

**Comment by karlcow** [comment]
The latest issue we had for this user agent is https://github.com/webcompat/web-bugs/search?o=desc&q=myie9&s=created&type=Issues&utf8=%E2%9C%93 
March 1, 2017 and before that August 2016.

Problem solved?

@adamopenweb Should we close this?

**Comment by adamopenweb** [comment]
@karlcow yeah let's close it. Unless anyone is worried about the extra traffic to the site, then please open back up. This UA still makes up about 27% of total traffic.

Here's a break down of just Firefox version numbers from the last month:
<img width="450" alt="screen shot 2017-08-30 at 11 15 41 am" src="https://user-images.githubusercontent.com/6587558/29879979-a3a6573c-8d74-11e7-9414-2300001b732b.png">
