### ISSUE TITLE
Automate Changelog

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat.com#1128]
- [x] make sure docs are up to date for conventions
- [ ] enable GitCop for commit messages
- [ ] make a grunt command for something like https://www.npmjs.com/package/conventional-changelog

**Comment by miketaylr** [comment]
Testing GitCop integration here: https://github.com/webcompat/webcompat.com/pull/1136

**Comment by miketaylr** [comment]
@karlcow what do you think about https://github.com/webcompat/webcompat.com/pull/1136#issuecomment-234113766 ? Confusing? Helpful? Harmful?

**Comment by karlcow** [comment]
Hmm… is it possible to decide about the syntax of Gitcop?
For example right now it recommends `Issue #nnnn - blah` where I would prefer `#nnnn - blah`

Another thing which scratches me the wrong way is dependencies on another service, but I can live with that as it's not fundamental for the life of the project. 

Somehow also I think it should be handled on the client side, when people are actually trying to commit messages. I wonder if there are CLI module for git doing that.

**Comment by karlcow** [comment]
` make sure docs are up to date for conventions` Added #1134 for this.

**Comment by karlcow** [comment]
Oh! Pre-commit linter!

https://bugzilla.mozilla.org/show_bug.cgi?id=1108755
https://github.com/mozilla/fjord/commit/a36a2319890cf6309969e2a956524c11635afba9

**Comment by miketaylr** [comment]
> Hmm… is it possible to decide about the syntax of Gitcop?

Yeah, it's configurable. But you can't set certain things as options, which is lame.

> Another thing which scratches me the wrong way is dependencies on another service

We could write our own webhook for this if we wanted. But I think I agree that pre-commit hooks are a nicer approach. The one problem is getting people to set them up -- if they don't, we have to nag them at review time as well.

> For example right now it recommends Issue #nnnn - blah where I would prefer #nnnn - blah

I thought we decided on `Issue #nnnn` in London (https://github.com/webcompat/webcompat.com/blob/master/CONTRIBUTING.md#submission-guidelines), but I'm happy to switch to #nnnn since it leaves more room for commit message headers.

**Comment by karlcow** [comment]
Hmm indeed. I guess we should leave out Issue. That would indeed gives more space for commit messages. :)

> The one problem is getting people to set them up -- if they don't, we have to nag them at review time as well.

I could imagine that 

1. the pre-commit hook script could be part of the project.
2. run.py or the initial configuration script install the hook.

**Comment by miketaylr** [comment]
Seems like a good plan!

**Comment by zoepage** [comment]
related to #740

**Comment by miketaylr** [comment]
Let's close this, #740 is pretty great.
