### ISSUE TITLE
CONTRIBUTION Guidelines: clarify the syntax of commits messages and pull requests

### ISSUE THREAD

**Issue by karlcow** [webcompat/webcompat.com#1134]
I need to clarify the Contribution https://github.com/webcompat/webcompat.com/blob/master/CONTRIBUTING.md#submission-guidelines
- Use imperative styles
- Issue number just need to have `#nnnn`
- Keep the message short so it fits on one line (less than x characters)
- For pull request, start with `Fix #nnnn` or `Fixes #nnnn`

Probably give example of good commit messages

**Comment by miketaylr** [comment]
> Keep the message short so it fits on one line (less than x characters)

Also maybe a note that longer explanations are OK in the commit body (two lines below the commit message header).

**Comment by zoepage** [comment]
Fixed.
