### ISSUE TITLE
Remove Safari Add-on link

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat.com#1140]
Reported @ https://github.com/webcompat/web-bugs/issues/2913

**Comment by miketaylr** [comment]
`72.48.211.134 - - [27/Jul/2016:19:14:25 +0000] "GET /addons/webcompat-reporter.safariextz HTTP/1.1" 404 1697 "https://webcompat.com/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/602.1.41 (KHTML, like Gecko) Version/9.1.2 Safari/601.7.7"`

Hmm, I swear this used to work.

**Comment by miketaylr** [comment]
I think we should just remove it. It can't be updated without paying for a $100/year Apple Dev account, and I don't think that's worth spending money on.

**Comment by miketaylr** [comment]
This whole dir can go, https://github.com/webcompat/webcompat.com/tree/master/addons

As well as the link in the addon-links.html template.

**Comment by magsout** [comment]
@miketaylr   have an iOS dev account. I don't know if  I can update Safari addon. I can Check if you want ?

**Comment by miketaylr** [comment]
Oh, that might be an option!  https://developer.apple.com/library/content/documentation/Tools/Conceptual/SafariExtensionGuide/ExtensionsOverview/ExtensionsOverview.html covers requesting a Safari Extension certificate (which is required for distribution).

**Comment by miketaylr** [comment]
I think we should do the following:

1. Remove the link, right now the experience is bad
2. In SF, look at porting the Safari Addon to send screenshots, then work with @magsout to get it signed.
3. Re-add.
