### ISSUE TITLE
Create method to backup issues.db

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat.com#1145]
This can be a command line argument to `run.py`: https://github.com/webcompat/webcompat.com/blob/master/run.py#L93

Something like `python run.py --backup`. This should:

Copy the existing issues.db to a folder that lives at `$DB_BACKUP_LOCATION` (or similar, somewhere configurable via secrets.py).

**Comment by deepthivenkat** [comment]
@miketaylr  I have a question here. Before moving the issues.db to a backup location that $DB_BACKUP_LOCATION, I need to verify if issues.db exists.

Should I check if issues.db exists in webcompat server / just in the current directory(where ever the code is executed) ?

**Comment by miketaylr** [comment]
> Should I check if issues.db exists in webcompat server / just in the current directory(where ever the code is executed) ?

just in the current directory is fine.

> Should I ssh to a host and check if issues.db exists there and also send the backup folder to the host?

Which host would this be?

**Comment by miketaylr** [comment]
This is merged now!
