### ISSUE TITLE
Images in markdown lists with paragraphs are not converted.

### ISSUE THREAD

**Issue by karlcow** [webcompat/webcompat.com#1148]
See https://github.com/webcompat/web-bugs/issues/1163#issuecomment-236515340
And https://webcompat.com/issues/1163#issuecomment-236515340

Basically in markdown you can have a multi-paragraphs list if you add 4 spaces in front of each items.

```md
1. the first item text

    more text for the first item. You can even have code or images.

    ```html
    <body></body>
    ```

2. The second item text

     Same thing.
```

And this will be rendered as:

1. the first item text

    more text for the first item. You can even have code or images.

    ```html
    <body></body>
   ```

2. The second item text

     Same thing.

**Comment by magsout** [comment]
@karlcow removing padding looks good for you ?

`padding: 0`
![capture d ecran 2016-09-17 a 15 09 19](https://cloud.githubusercontent.com/assets/1997108/18608416/c686da76-7ce8-11e6-9aa0-7d047249bd4b.png)


`default`
![capture d ecran 2016-09-17 a 15 09 24](https://cloud.githubusercontent.com/assets/1997108/18608415/c26c3c6a-7ce8-11e6-9217-5fd169c4cd39.png)

**Comment by magsout** [comment]
ooops, wrong anwser...
