### ISSUE TITLE
Add status, creation and last changed time, domain and reported from to issue db

### ISSUE THREAD

**Issue by deepthivenkat** [webcompat/webcompat.com#1153]
These new fields are necessary if we need use an offline database to display the list of issues.

**Comment by deepthivenkat** [comment]
@miketaylr There are two separate implementations for extracting the domain name from url.

dshgna@ebf615f

form.py

To consolidate which implementation to go ahead with, I am checking the domain extracted from both the implementation for the same sample set of urls.

Input : http://money.cnn.com/2004/01/05/commentary/game_over/column_gaming/ 
Output : 
TldExtract : cnn
UrlParser : money.cnn.com

Input : www.google.co.uk
Output : 
TldExtract : google
UrlParser : www.google.co.uk

Input : https://www.google.co.uk/
Output : 
TldExtract : google
UrlParser : www.google.co.uk

Input : http://www.mx.iucr.org/iucr-top/comm/cpd/QARR/raw/cpd-1a.raw
Output : 
TldExtract : iucr
UrlParser : www.mx.iucr.org

Input : http://sdpd.univ-lemans.fr/course/week-1/sample2.raw
Output : 
TldExtract : univ-lemans
UrlParser : sdpd.univ-lemans.fr

Input : samples/Cu3Au-1.raw
Output : 
TldExtract : samples
UrlParser : samples

Input : mail.google.com
Output : 
TldExtract : mail.google
UrlParser : mail.google.com

Input : https://www.mail.google.com
Output : 
TldExtract : mail.google
UrlParser : www.mail.google.com

Input : deepthivenkat.github.io
Output : 
TldExtract : github
UrlParser : deepthivenkat.github.io

Input : http://www.empassion.com.au
Output : 
TldExtract : empassion
UrlParser : www.empassion.com.au

Input : https://myaccount.shaw.ca/MyBills
Output : 
TldExtract : shaw
UrlParser : myaccount.shaw.ca

Input : https://touch.www.linkedin.com/
Output : 
TldExtract : linkedin
UrlParser : touch.www.linkedin.com

Input : http://www.droid-life.com/
Output : 
TldExtract : droid-life
UrlParser : www.droid-life.com

Input : http://www.nb.no/nbsok/search?mediatype=bøker
Output : 
TldExtract : nb
UrlParser : www.nb.no

Input : http://paramountproperty.my/
Output : 
TldExtract : paramountproperty
UrlParser : paramountproperty.my

Input : http://m.mlb.com/game/2016/07/07/448148/angels-vs-rays
Output : 
TldExtract : mlb
UrlParser : m.mlb.com

Input : http://news.nicovideo.jp/watch/nw2258329?news_ref=sp_list_latest
Output : 
TldExtract : nicovideo
UrlParser : news.nicovideo.jp

Input : http://www.tsn.ca/draft-day-blog-flames-heating-up-1.514591
Output : 
TldExtract : tsn
UrlParser : www.tsn.ca

Input : http://beta.euronews.com/
Output : 
TldExtract : euronews
UrlParser : beta.euronews.com

Input : https://m.reddit.com/r/PersonalFinanceCanada/search
Output : 
TldExtract : reddit
UrlParser : m.reddit.com

Input : https://redsox.m.mlb.tickets.com/seat-select/8158391
Output : 
TldExtract : tickets
UrlParser : redsox.m.mlb.tickets.com

Input : http://mxr.mozilla.org/mozilla-central/source/netwerk/dns/effective_tld_names.dat?raw=1
Output : 
TldExtract : mozilla
UrlParser : mxr.mozilla.org

The url parser is maintaining the subdomain and suffix such as 'co.uk'.
If we are using urlparser, we need to tweak the code to remove 'www.' from the domain names - it is retaining www. currently.

In TLD Extract the subdomain , domain and suffix information is available. It has been coded to retain only the domain names and discard subdomains except for the domains in:

blacklist = ['.google.com', '.live.com', '.yahoo.com', 'go.com', '.js']

For the domains in the above list, subdomain.domain is returned.Now we have 2 options:

1) We may have to edit the blacklist and include more domains for which we need to retain subdomains.
2) Tweak the code to retain subdomain for all domains and suffix as the subdomain and suffix also contains valuable information and help in exact mapping when the user starts typing the subdomain.

TLD extract maintains a cache file containing list of all suffix that is updates regularly. Have attached the file.

test.txt

We need to decide if we have to go ahead with TLD Extract or url parser.

**Comment by miketaylr** [comment]
> We need to decide if we have to go ahead with TLD Extract or url parser.

ok!

Just looking at the results from a few samples:

```
Input : http://beta.euronews.com/
Output :
TldExtract : euronews
UrlParser : beta.euronews.com
```

```
Input : mail.google.com
Output :
TldExtract : mail.google
UrlParser : mail.google.com
```

```
Input : http://www.tsn.ca/draft-day-blog-flames-heating-up-1.514591
Output :
TldExtract : tsn
UrlParser : www.tsn.ca
```

Personally, I would stick with UrlParser. (I'm also not a fan of maintaining a black/whitelist of domains in the project -- too many things to get wrong)

So, I would say we go with the exist UrlParser approach and possibly tweak it so it can return just domain + suffix (without breaking what its currently doing). One disadvantage is to not be able to quickly associate google.com, google.ca, google.co.in, etc.

Is there any reason why we would want to store the subdomain?

Curious about your thoughts here @karlcow.

**Comment by deepthivenkat** [comment]
The main motive to store subdomain would be to provide the most relevant issues when the user starts typing the url.
Say mail.google.com -  if we store just domain name, we will display the issues for all the subdomains under google.com which may not be a possible duplicate of the issue the user wants to report

**Comment by miketaylr** [comment]
Yeah, but on the other hand it _may_ be interesting to know that a bug found on music.apple.com is also on store.apple.com (fake examples here).

One possible strategy is to just weight possible matches differently, and show the higher up ones first.

exact domain + suffix >  domain + diff suffix >  diff sub-domain + domain, etc.

**Comment by miketaylr** [comment]
(still interested in Karl's feedback on this...)

**Comment by deepthivenkat** [comment]
With respect to the [previous comment](https://github.com/webcompat/webcompat.com/issues/1153#issuecomment-237890827) - 

If we are sure that we need to store only domain+suffix, we should go with TLD extract -

Reasons:
1) It provides us subdomain, domain, suffix separately.
2) The tool maintains and updates the list of all public suffix and we don't have to maintain it. 

If we go with url parser, the problem might be:

1) It returns netloc containing subdomain+domain+suffix+port. Though we can easily separate port, it is very difficult to identify domains, suffix with just string pattern.

For example:

UK has subdomains co.uk. Australia has com.au
Italy can have co.it as suffix. But Italy also can have domain+suffix as co.it

In this case, the only better way to separate domain+suffix from url using url parser is by maintaining a lift of suffix file as mentioned in the second answer here:

http://stackoverflow.com/questions/1066933/how-to-extract-top-level-domain-name-tld-from-url

- we discussed that we do not want to do that.

So shall we proceed with tldextract instead?

**Comment by miketaylr** [comment]
ping @karlcow.

**Comment by deepthivenkat** [comment]
Okay!

**Comment by miketaylr** [comment]
(oh sorry, not telling you to ping @karlcow -- I'm trying to summon him myself into this thread for feedback 👍 )

**Comment by karlcow** [comment]
@miketaylr @deepthivenkat sorry for the late reply.

Trying to be clever with domain names is a bit like trying to design a universal name parser or a date parser. It's close to impossible.

So the question ties down, what is the issue we are trying to solve:

* If we try to have a match on an already reported bug, the full domain is fine and indeed urlparser is the way to go.
* If we try to create meta-collection of related URLs (aka `mail.google.com` and `docs.google.com` in the same feed), I would probably encourage we do that in a separate part of the code. This could be controlled by customized JSON filters maintained by hand, but should definitely not be in the core parsing code. 

And it's ok if we have separate bugs for `news.google.br` and `news.google.fr` even if it's the same issue… because it's not the same issue (Remember for example the login on Google Search which is different depending on the country)

**Comment by deepthivenkat** [comment]
I think the purpose of having to display duplicate bugs with same domain is for the user to verify that the bug he is about to report, has not been already reported.

So having a match on an already reported bug would suit this purpose.

What do you think @miketaylr ?

**Comment by miketaylr** [comment]
Yep, sounds good. Agree with @karlcow here.
