### ISSUE TITLE
"one year ago" makes the context a bit hard to understand

### ISSUE THREAD

**Issue by karlcow** [webcompat/webcompat.com#1154]
Currently for old comments, we display a span date:
![capture d ecran 2016-08-04 a 09 50 37](https://cloud.githubusercontent.com/assets/505230/17388096/a9acd1fc-5a34-11e6-9f94-789d5c7059d7.png)

I would instead display the real date such as 25 March 2015

**Comment by miketaylr** [comment]
Yeah, I think just showing the date is good.

To fix this, we need to [remove moment.js](https://github.com/webcompat/webcompat.com/search?utf8=%E2%9C%93&q=moment) and whenever it touches the `createdAt` model property:

https://github.com/webcompat/webcompat.com/blob/master/webcompat/static/js/lib/issues.js#L500
https://github.com/webcompat/webcompat.com/blob/master/webcompat/static/js/lib/models/comment.js#L25

**Comment by miketaylr** [comment]
(removing type: bug label, because this was an intentional design decision)

**Comment by magsout** [comment]
@karlcow @miketaylr 

For all dates , or those more than one year ?

**Comment by karlcow** [comment]
@magsout more than 1 week. Seems a good choice.

**Comment by magsout** [comment]
Ok so,

All dates < 1 week, relative
All dates > 1 week, string
