### ISSUE TITLE
"GitHub view" text rendering problem on issues list page

### ISSUE THREAD

**Issue by jmm** [webcompat/webcompat.com#1155]
On both the [issues list](https://webcompat.com/issues?page=1&per_page=50&state=open&stage=all&sort=created&direction=desc) and [issue](https://webcompat.com/issues/2938) pages there's a paragraph at the bottom:

> takes you to the GitHub view of this page.

On the list page it renders without proper spacing between the words, like:

> takes you to theGitHub viewof this page.

![image](https://cloud.githubusercontent.com/assets/129203/17408144/0e6b5a52-5a38-11e6-806e-6a27e10f7418.png)

That's in Firefox 48 / Chrome 51 Win 7.

It's a result of the `display: flex` styling (looks like that was introduced in #901). One solution would be to apply margin to the GitHub View link. However, perhaps it's better to just remove the `display: flex`? The paragraph at the bottom of the issue template doesn't have it -- it's just the default `display: block`. It seems like the paragraph at the bottom of the issue list template with that and `text-align: right` would be fine, but is there some reason it's important for that to have flex layout?

**Comment by miketaylr** [comment]
Thanks @jmm!

cc @magsout

**Comment by miketaylr** [comment]
(There's some talk of moving that keyboard hint to the side-bar w/ labels: https://github.com/webcompat/webcompat.com/pull/1104#issuecomment-229708929)

**Comment by jmm** [comment]
@miketaylr Thanks!

Oh yeah, I see the discussion about that. Wasn't seeing a mockup with a side-bar in that thread, but tracked down https://github.com/webcompat/webcompat.com/issues/545#issuecomment-144714394 that links to a mockup. It seems like those changes are pretty involved and may take some time to settle, so perhaps it makes sense to fix this in the current layout for now (I'm guessing that's what you have in mind).

**Comment by magsout** [comment]
thanks @jmm 

Hum strange I don't have this issue 
![capture d ecran 2016-08-05 a 07 26 23](https://cloud.githubusercontent.com/assets/1997108/17427054/f8e1d304-5add-11e6-9314-db1a0496729b.png)

I tried with Firefox 48, 49 and Chrome.

>It's a result of the display: flex styling (looks like that was introduced in #901)

There is no `display: flex`  in this `<p>`  , where do you see it ?

**Comment by jmm** [comment]
Thanks @magsout. It only manifests on the issue list page. Since you're not seeing it, and based on the background color of your screenshot, I think perhaps you're looking at the single issue page?

The `<p>` at the bottom of the list list page (I believe [this is its template](https://github.com/webcompat/webcompat.com/blob/e48404c55ff5b2267b180b5f20ecb5e3f95d2e3a/webcompat/templates/list-issue/issue-list.html#L41)) has class `wc-SearchIssue-github` that has `display: flex` set (looks like it comes from [here](https://github.com/webcompat/webcompat.com/blob/e48404c55ff5b2267b180b5f20ecb5e3f95d2e3a/webcompat/static/css/development/components/search-issue.css#L65)).

**Comment by magsout** [comment]
Ah yes, here https://webcompat.com/issues my bad..  So you're right ;)

**Comment by jmm** [comment]
@magsout Cool, we're on the same page :)

**Comment by zoepage** [comment]
@magsout would it be ok for you, if I fix this? :)

**Comment by magsout** [comment]
@zoepage 👍
