### ISSUE TITLE
Make a findVisibleByQSA method that resolves an element

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat.com#1156]
In https://github.com/webcompat/webcompat.com/pull/1151/commits/f6bc3ca3bd419de13ff9275c2f6fa4ae1014f003 I added a modified version of FxA's `visibleByQSA` method so we can wait until things are rendered before operating on them.

In practice this works, but it's too verbose:

```
.then(FunctionalHelpers.visibleByQSA('.wc-IssueList:nth-of-type(1) .wc-Link'))
.findByCssSelector('.wc-IssueList:nth-of-type(1) .wc-Link').getVisibleText()
.then()...
```

Instead I'd like to have something like `FunctionalHelpers.findVisibleByQSA` so we can just do

```
FunctionalHelpers.findVisibleByQSA('.wc-IssueList:nth-of-type(1) .wc-Link').getVisibleText()
.then()...
```

**Comment by brizental** [comment]
Hey @miketaylr, we don't have this method anymore, we do have a visibleByClass method, but it's not used anywhere in the code.

Also, from what I understand, doesn't [findDisplayedByCssSelector](https://theintern.io/leadfoot/module-leadfoot_Element.html#findDisplayedByClassName) do what this method would do?

**Comment by miketaylr** [comment]
Yeah... I think you're right. Either I didn't know about that method (likely...) or I was trying to solve some other problem. And I don't remember, so let's close this.
