### ISSUE TITLE
[RFC] invalid might be felt too strong

### ISSUE THREAD

**Issue by karlcow** [webcompat/webcompat.com#1158]
I wonder if when we close a bug being as invalid, we generate more anger than necessary.

Some ideas:
- Change invalid by notwebcompat 
- automatically add a boilerplate text explaining what is a Web compat issue. 
- automatically add a link to the explanation for invalid/notwebcompat term.

**Comment by miketaylr** [comment]
> Change invalid by notwebcompat 

Not a huge fan of bikeshedding 🚲 🏠, but `notwebcompat` feels a bit terse or confusing itself. 

> automatically add a link to the explanation for invalid/notwebcompat term.

I really like this idea. Some boilerplate with a link to a longer discussion, either on the site or on a wiki where is good. I think maybe `invalid` with a description that explains *why* by default might be better.

Unless someone has a better suggestion for what color to paint the shed.

**Comment by miketaylr** [comment]
Let's close, we should probs be using the notcompat milestone for these types of issues. 

🚲🚲🚲🚲🚲🚲🚲🚲🚲🚲🚲🚲🚲🚲🚲🚲🚲🚲
