### ISSUE TITLE
disallow view-source: prefixed URIs?

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat.com#1159]
It seems like this isn't super useful (and for add-ons, we could disable the reporter button for said URIs).

cf. https://github.com/webcompat/web-bugs/issues/3037

**Comment by miketaylr** [comment]
Any thoughts @adamopenweb @denschub @karlcow @magsout ?

**Comment by karlcow** [comment]
`about:` and `view-source:` let's disable them all.

**Comment by denschub** [comment]
👍

**Comment by magsout** [comment]
Yes 👍

**Comment by adamopenweb** [comment]
Good call 👍

**Comment by miketaylr** [comment]
Closing this in favor of #1054
