### ISSUE TITLE
Create method to execute alter commands on issues.db old schema

### ISSUE THREAD

**Issue by deepthivenkat** [webcompat/webcompat.com#1160]
After taking a backup of existing db [(Issue #1145)](https://github.com/webcompat/webcompat.com/issues/1145) and recreating issues.db that has old schema,

we need to have a file that reads alter commands from a file and executes them sequentially. Once execution is over, we will have updated schema.

**Comment by karlcow** [comment]
I thought we decided together to NOT DO that.
See the discussion in a pull request where [Mike is saying](https://github.com/webcompat/issue_parser/pull/9#issuecomment-235939851):

> I think we should start here. Doing a "back-up" is simple, it's literally copying a file and moving it somewhere. But we also want some mechanism to bootstrap a new database with current GitHub information.
> 
> Right now, the issues.db is 100% unused (and doesn't even contain 100% of issues). If we made any schema changes today, and re-built the DB nothing would break. So I think it's probably too early to add the complexity of alembic, etc when we don't need it yet.

**Comment by miketaylr** [comment]
> I thought we decided together to NOT DO that.

Yeah, we're not ready to take this on right now. But we might want to in the future.

@karlcow do you think closing this now is better, or do we create a label "status: maybe later?"

**Comment by karlcow** [comment]
We have a "status: blocked" not sure it's good, my hunch would say that we should close it because we don't need it in any way for now, aka no schema migration at all in our future projects (for now).

**Comment by karlcow** [comment]
Let's close after discussions on 
https://groups.google.com/forum/#!topic/mozilla.compatibility/f7tJmi9IB40
and IRC

> `[07:28]  <miketaylr> feel free to close`
