### ISSUE TITLE
Main page asks to install add-on when it's already installed

### ISSUE THREAD

**Issue by adamopenweb** [webcompat/webcompat.com#1162]
With the add-on already installed in Firefox, webcompat.com still displays a message recommending I download it.

Not sure if there's a way to detect it? Maybe if we created a content script inside the extension to toggle a flag?

**Comment by miketaylr** [comment]
The idea from https://github.com/webcompat/webcompat.com/issues/1163#issuecomment-244416799 would also solve this -- basically if you click on the add-on and open the page, that message wouldn't be displayed.

Butttt if you just visited the homepage and had the add-on installed, you'd still see it. 

> Maybe if we created a content script inside the extension to toggle a flag?

Seems doable -- it could just add a class to `<html>` or `<body>` and we can hide it based on that.

**Comment by miketaylr** [comment]
Fixed by https://github.com/webcompat/webcompat-reporter-extensions/commit/4790500908a66ea8b32f0f8946c9638e7525ab59 and https://github.com/webcompat/webcompat.com/commit/cd596a2b1dcbdaec59f6bb362b4df9ba4bd67ae4

Oh... I guess I worked on this in a dupe (#1169). Oops.
