### ISSUE TITLE
Main page branding when reporting from add-on

### ISSUE THREAD

**Issue by adamopenweb** [webcompat/webcompat.com#1163]
When the form loads in a new tab, it starts scrolled down the page. There is actually a large header if the user scrolls up. When scrolled down, the webcompat branding is lost, as well as some of the top-level navigation elements (search, all issues, log in).

Maybe we can reduce height of header and start users at the top of the page?

<img width="719" alt="wcdc" src="https://cloud.githubusercontent.com/assets/6587558/18110231/c582d9de-6ee4-11e6-9963-bcf2e8b77356.png">

**Comment by miketaylr** [comment]
> Maybe we can reduce height of header and start users at the top of the page?

I think it gets trickier for mobile. If we start at the top, then the form is totally missing. 

I wonder if a separate landing page for add-on bug reports might be a solution: 
* mini header that says webcompat.com (in place of download our add-on)
* no animation/toggle -- form is just open
* no latest needstriage stuff below
* no "how it works" info

That would make the page smaller and faster, which seems good. Whatcha think @magsout?

**Comment by magsout** [comment]
Good idea @miketaylr.
Maybe totally remove `form` for the homepage and replace the arrow button by a link. I don't know, but I have the feeling that @karlcow had the same idea before, no ?

**Comment by miketaylr** [comment]
> I have the feeling that @karlcow had the same idea before, no ?
Probably. :)

**Comment by karlcow** [comment]
@magsout @miketaylr That's #317
And yes. The form should have it's proper URI and it could be content-negotiated

**Comment by karlcow** [comment]
Also mediaqueries for the win. The height and animation and all of these can be removed.

**Comment by miketaylr** [comment]
> Maybe totally remove form for the homepage and replace the arrow button by a link.

Dunno if we need to go that far, it feels like having the form also be on the homepage is nice. But something we can consider once make more progress.

**Comment by miketaylr** [comment]
I think we should make the `webcompat.com/issues/new` route this simplified page. We can re-use most of the same templates here.

**Comment by miketaylr** [comment]
Let's dupe this again #1193.
