### ISSUE TITLE
Report bug option when reporting from add-on

### ISSUE THREAD

**Issue by adamopenweb** [webcompat/webcompat.com#1164]
When reporting from the add-on the Report Bug title hides/shows the form. The purpose of this page is to show the form, so this is an unnecessary action.

Maybe we can remove the link and collapsible the div for the form?

<img width="718" alt="wcdc2" src="https://cloud.githubusercontent.com/assets/6587558/18110338/4210eee6-6ee5-11e6-9381-5a789e784853.png">

**Comment by miketaylr** [comment]
I think the idea from https://github.com/webcompat/webcompat.com/issues/1163#issuecomment-244416799 would solve this issue.

**Comment by karlcow** [comment]
See #317

**Comment by miketaylr** [comment]
Let's dupe this against #1193.
