### ISSUE TITLE
Add-on reporting page could be distracting to users

### ISSUE THREAD

**Issue by adamopenweb** [webcompat/webcompat.com#1165]
When reporting a bug from the add-on, the user lands on the main webcompat.com page with the report bug div expanded. 

The purpose of this page is for users to fill out the webcompat form and submit it. However, there is a lot of additional information on this page that may distract the user from this purpose. There is a How It Works section, a list of Latest Untriaged Issues and a Join The Team section. This may be of interest the first time a user goes to this page, but only serves as a distraction for future form submissions.

Maybe we could remove extra sections and put them on the Thank You page after submission? The 'How it Works' section could be jazzed up a bit too

<img width="959" alt="howitworks" src="https://cloud.githubusercontent.com/assets/6587558/18110528/8d92b42a-6ee6-11e6-8e11-8db2bc3dfdfb.png">

**Comment by miketaylr** [comment]
Idea to fix this here: https://github.com/webcompat/webcompat.com/issues/1163#issuecomment-244416799

**Comment by miketaylr** [comment]
Let's dupe this against #1193.
