### ISSUE TITLE
Site URL Validation

### ISSUE THREAD

**Issue by adamopenweb** [webcompat/webcompat.com#1166]
Currently we do not check the URL to ensure it is valid. There is an opportunity to prevent some errors for users and bugs that are reported incorrectly. 

<img width="725" alt="site url" src="https://cloud.githubusercontent.com/assets/6587558/18110651/4549a240-6ee7-11e6-88bc-26b0cc4f5c67.png">

**Comment by miketaylr** [comment]
Yeah, I agree validation is probs better UX. And I guess one way to avoid the "about:blah" bugs from coming in as well. 

Some kinda XHR HEAD request with a 2XX or 3XX response should be good here.

**Comment by magsout** [comment]
Maybe starting by add type url ?

`<input type="url" >`

**Comment by miketaylr** [comment]
> Maybe starting by add type url ?

Hm, that might work. But as is, it's way more restrictive than we are: http://www.wufoo.com/html5/types/3-url.html, for example it won't accept `google.com`.

Pros would be having a `:valid` and `:invalid` psuedo-class available for styling. Cons being the native validation UI is ugly....

Am I being to paranoid in thinking that forcing valid URLs for users will reduce the number of reports? Maybe it's not a huge burden to just copy and paste the URL? dunno right now.

**Comment by miketaylr** [comment]
> There is an opportunity to prevent some errors for users and bugs that are reported incorrectly.

We can discuss this in Taipei, but I'm inclined to WONTFIX this bug. Or morph it into something like https://github.com/webcompat/webcompat.com/issues/1054. That's where we've seen "real" invalid URLs. 

We don't see a lot of broken URLs because they were invalid (at least, that's my impression).

**Comment by miketaylr** [comment]
OK, let's WONTFIX but implement #1054.
