### ISSUE TITLE
Green check mark not used on other form fields

### ISSUE THREAD

**Issue by adamopenweb** [webcompat/webcompat.com#1167]
When submitting a report on webcompat.com, there is a green check mark when the Site URL field is populated. The other fields do not have this, users could benefit from this consistency and error prevention.

**Comment by magsout** [comment]
you're right, I need to make a better component for check mark. Mayebe with no SVG but only font icon..

**Comment by karlcow** [comment]
or simply one of ✓ ✅☑︎✔︎

**Comment by miketaylr** [comment]
> The other fields do not have this, users could benefit from this consistency and error prevention.

Right now there's only 2 required field: URL and problem type -- I guess it would be good to have some kind of checkmark for problem type? (The page autofills browser and OS... maybe a check would be good there, but we don't require them so I don't think an X makes sense.)

**Comment by miketaylr** [comment]
(this issue is low priority, IMO. not a blocker)

**Comment by miketaylr** [comment]
Or possibly, we just need to add the checkmark validation to the Browser / Version fields as well. That would make it more consistent and would be useful if people somehow deleted them (but they're not mandatory, so I guess just only care about the success case?).

**Comment by miketaylr** [comment]
Oh look, I said the same thing twice. Yay for consistency. 👀
