### ISSUE TITLE
Missing .eslintrc??

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat.com#1168]
How did this get deleted?

**Comment by miketaylr** [comment]
This is what it looked like... at some point:

https://github.com/webcompat/webcompat.com/blob/ea4f6e33b0865858560fc790b494f8e24c50bdfb/.eslintrc

**Comment by miketaylr** [comment]
https://github.com/webcompat/webcompat.com/blob/b21d1555262876581533477270f1bb318f3f8c1b/.eslintrc a more recent version. Looks the same.

I think we lost this when master got force-pushed to. :(

**Comment by miketaylr** [comment]
Oh wait. I just totally forgot. We moved this into package.json. 🍶

**Comment by magsout** [comment]
😹😹😹
