### ISSUE TITLE
Hide "download add-on" link when user has add-on already installed

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat.com#1169]
cf. https://github.com/webcompat/webcompat-reporter-extensions/issues/34

This issue is about adding CSS to hide the relevant link -- the add-on will add a class to control this.

**Comment by miketaylr** [comment]
(there might be a dupe for this issue... I can't seem to find it)

**Comment by magsout** [comment]
Something like `is-hidden` looks good

**Comment by miketaylr** [comment]
Ah, cool -- that probably makes more sense to just add that directly to what we want to hide.

**Comment by magsout** [comment]
Ah it's the addon  detects and adds the class

**Comment by miketaylr** [comment]
Yeah, but the addon can add the class to the download link directly.
