### ISSUE TITLE
contributing guidelines - npm run init

### ISSUE THREAD

**Issue by luiguild** [webcompat/webcompat.com#1176]
In Working Environment Setup[1] I found the instruction

```
# clone the repo
git clone https://github.com/<username>/webcompat.com.git #replace your github username
# change to directory
cd webcompat.com
# check out submodules
npm run module
# initializing project
[sudo] npm init
```

npm init? The package.json file already exists... Right?
I guess that the correct step is

```
npm install
```

or am I wrong?

😄 

1 - https://github.com/webcompat/webcompat.com/blob/master/CONTRIBUTING.md#working-environment-setup

**Comment by denschub** [comment]
Hm, this probably should be `npm run init` instead of `npm init`. That comment [will set pretty much everything up for you](https://github.com/webcompat/webcompat.com/blob/93662e358169e7443445217fe7d2a5c6151c9b21/package.json#L43).

Do you want to make a pull request for that? :)

**Comment by magsout** [comment]
Hum, maybe I was wrong to write, `npm run init ` it's not a good things to overwrite default recipes

**Comment by miketaylr** [comment]
Maybe we should rename that? `npm run bootstrap` or `npm run setup`??

**Comment by luiguild** [comment]
Personally I prefer ```npm run setup```

**Comment by miketaylr** [comment]
@luiguild did you ever get the development environment working for you?

**Comment by karlcow** [comment]
In #982 @miketaylr  used `npm run init` does it fix this issue?

**Comment by zoepage** [comment]
I ran into the same issue while setup. 
Either way the rename should be a good step to prevent confusion. :)

**Comment by miketaylr** [comment]
@zoepage is handling the rename in #1322, so let's close here!
