### ISSUE TITLE
Explain status meaning in bug reports

### ISSUE THREAD

**Issue by adamopenweb** [webcompat/webcompat.com#1179]
When closing reports, I have been using templates to help explain what is valid and not. Maybe it would be helpful to explain the meaning of the status labels for users who aren't familiar with our process.

An example of where I explained:
https://webcompat.com/issues/3218

It could look something like this:

```
This bug report has been marked as invalid.  Typically this means the reported issue 
does not fit the description of a Web Compatibility issue. For this project we try to 
focus our effort on layouts, features or content that works as expected in one browser 
but not in another.
```

Could include others as well, explaining what sitewait means for instance. 

Thoughts?

**Comment by devjayati** [comment]
Maybe there could a be a link like ['What does this mean?'](www.example.com) for every label and that would take the person to a single webpage where the meanings of all status labels have been explained?

**Comment by miketaylr** [comment]
Action items: @adamopenweb and @karlcow to come up with a set of stuff.

**Comment by karlcow** [comment]
@adamopenweb 

Some status/sentences I have been using. This could probably be more descriptive.

```
Sent an email to the partner mailing-list about this issue.
Moving to sitewait.
```

When closing as incomplete.
```
Thanks for the report. 
This issue has no actionable information to be able to diagnose.
We are closing this issue as incomplete.
```


I also start using templates for some of the technical issues. For example:

Closing as duplicate
```
This is happening only on Firefox Android, not on Desktop. 
Firefox Android will get native input widgets.
This will be fixed by https://bugzilla.mozilla.org/show_bug.cgi?id=1352238
```

**Comment by adamopenweb** [comment]
Thanks @karlcow. A few of mine.

Incomplete.
```
Thanks for the report. Unfortunately without more detail about the issue you
experienced, we cannot help with this bug. Please leave a comment with more
detail, or file a new report and we will gladly investigate this further.
```

Works for me (this one needs improvement):
```
Thanks for the report! I'm unable to reproduce this issue in Firefox 55 for 
Windows 10. It's not clear what issue the reporter experienced here, but 
it doesn't appear to be a web compatibility issue.
```


Not mobile friendly. I usually edit this one for non-compat now, used to be for Invalid.
```
Thanks for the bug report @! It seems the site is not mobile friendly regardless
of the browser that's being used. For this project we try to focus our effort on 
layouts, features or content that works as expected in one browser but not in 
another. I'm going to close this report as invalid but if you would like to reach out 
to the site, that would be helpful for other users.
```

Not really a status, but it's good to put some context behind Tracking Protection duplicates.
```
Thanks for the report! I can reproduce this issue in Firefox __ for ___. This issue 
only seems to happen with Tracking Protection enabled in Firefox.

We don't consider Tracking Protection breakage to be a web compatibility issue, 
because it is a users choice to break some functionality on the web for the benefit 
of not being tracked.

I'm closing as duplicate for now. Referenced this issue on Bugzilla 
https://bugzilla.mozilla.org/show_bug.cgi?id=1101005
```

**Comment by adamopenweb** [comment]
I think it looks really nice @karlcow. But I'm not sure if it's worth putting time into. We could leave it as a good first/second bug maybe?

**Comment by karlcow** [comment]
In accord to the majority opinion ;) Let's close with the flag, backlog.
