### ISSUE TITLE
Make form.get_metadata string concatenation more idiomatic

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat.com#1185]
See @karlcow's comment at https://github.com/webcompat/webcompat.com/issues/355#issuecomment-250619637

To fix this, update the `get_metadata` method as Karl suggests. When that's done, make sure that the tests still pass! (run `nosetests` from the project root).

**Comment by sunakshi96** [comment]
Hey
the function description is 
`
def get_metadata(metadata_keys, form_object):

    '''Return relevant metadata hanging off the form as a single string.'''

    metadata = []

    result = ''

    for key in metadata_keys:

        metadata.append((key, form_object.get(key)))

    # Now, "wrap the metadata" and return them all as a single string

    for md in metadata:

        result += wrap_metadata(md)

    return result

`
We need to change  the line result +-wrap_metadata, in order to update the function?

**Comment by karlcow** [comment]
(edited the comment by @sunakshi96 to make the source code readable).

@sunakshi96 to insert source code in Github comments, see the [code documentation](https://guides.github.com/features/mastering-markdown/#example-code)

The proposal is to do (as said in the link comment):

```python
def get_metadata(metadata_keys, form_object):
    '''Return relevant metadata hanging off the form as a single string.'''
    metadata = []
    result = ''
    for key in metadata_keys:
        metadata.append((key, form_object.get(key)))
    # Now, "wrap the metadata" and return them all as a single string
    ''.join([wrap_metadata(md) for md in metadata])
    return result
```

And as @miketaylr said. Make sure to run nosetests.

**Comment by karlcow** [comment]
Another possible simplification is.

```python
metadata = [(key, form_object.get(key)) for key in metadata_keys]
```

**Comment by karlcow** [comment]
```python
def get_metadata(metadata_keys, form_object):
    '''Return relevant metadata hanging off the form as a single string.'''
    metadata = [(key, form_object.get(key)) for key in metadata_keys]
    # Now, "wrap the metadata" and return them all as a single string
    return ''.join([wrap_metadata(md) for md in metadata])
```

**Comment by karlcow** [comment]
@sunakshi96 To understand what is it about you can read about [list comprehensions in python](http://treyhunner.com/2015/12/python-list-comprehensions-now-in-color/)
