### ISSUE TITLE
Only print expected fixture file path when we can't find it

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat.com#1187]
Currently we output a message "Expected fixture file: ..." every time a fixture file is used when running tests.  It's not very useful when things are working.

<img width="1199" alt="screen shot 2016-10-04 at 4 28 27 pm" src="https://cloud.githubusercontent.com/assets/67283/19093213/d9b57494-8a4f-11e6-8349-bc2afe94efe3.png">

To fix this bug, we should only show that message when a fixture file is _not_ found, so we can have a better idea of what the problem is.

The relevant code is in the `mockable_response` decorator: https://github.com/webcompat/webcompat.com/blob/master/webcompat/helpers.py#L364

**Comment by brizental** [comment]
Yeah... That is annoying. 
I would like to work on this.

**Comment by miketaylr** [comment]
Thanks @brizental!
