### ISSUE TITLE
Update requirements to run tests locally for Firefox 49+ in CONTRIBUTING.md

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat.com#1190]
To get it running, you need v0.10.0 of [geckodriver](https://github.com/mozilla/geckodriver/releases) in your PATH, and the latest 3.0.0 beta build (or whatever is newest, presumably) of Selenium: http://www.seleniumhq.org/download/

To fix this bug, update the relevant docs @ https://github.com/webcompat/webcompat.com/blob/master/CONTRIBUTING.md (and make sure you can run the tests locally!).

**Comment by karlcow** [comment]
Currently it says

>  Note: This version is known to work with Firefox 50.1.0. If things aren't working with the current stable version of Firefox, please file a bug!
https://github.com/webcompat/webcompat.com/blob/master/CONTRIBUTING.md#functional-tests


@miketaylr Something else required?

**Comment by miketaylr** [comment]
Ah no, this looks obsolete.
