### ISSUE TITLE
Fix broken link to CouchDB CONTRIBUTING file in CONTRIBUTING.md

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat.com#1191]
https://github.com/webcompat/webcompat.com/blob/master/CONTRIBUTING.md#acknowledgements

Not sure where it went, so to fix this issue, ideally we could find out where it was moved to. Or, if it's gone forever, remove the link.

**Comment by dacharya64** [comment]
May have been replaced by this (http://docs.couchdb.org/en/latest/contributing.html) or this (https://github.com/apache/couchdb/blob/master/README-DEV.rst) but haven't seen the original, so can't say for sure. Anyone know better?

**Comment by miketaylr** [comment]
@dacharya64 thanks for looking into this!

I think we can probably just remove the link since whatever it turned into wasn't part of the original "inspiration" (whatever that means). Thanks!
