### ISSUE TITLE
Fix CONTRIBUTING.md TOC links

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat.com#1192]
Not all of the TOC links are working, which means we changed headings and forgot to update the TOC links.

"Simple Setup" is an example: https://github.com/webcompat/webcompat.com/blob/master/CONTRIBUTING.md#simple-setup 

To fix this bug, please audit all the links in the TOC and make corrections where needed!

**Comment by devjayati** [comment]
In the TOC, 'Simple Setup' and 'Detailed Setup' are the only ones not working. The code needs a minor change from 
<*a href="#simple-setup">Simple setup<*/a> 
to
<*a href="#simple-setup-mac-os-and-linux">Simple setup<*/a>


for 'Simple Setup' and from
<*a href="#detailed-setup">Detailed setup<*/a>
to
<*a href="#detailed-setup-all-platforms">Detailed setup<*/a>
for 'Detailed Setup'

**Comment by miketaylr** [comment]
Thanks @devjayati!

**Comment by dacharya64** [comment]
Looking at CONTRIBUTING.md now and notice a link to "Good-first-Patch" [here](https://github.com/webcompat/webcompat.com/blob/master/CONTRIBUTING.md#finding-an-issue-to-work-on). Should this be replaced with a link to [good first bug](https://github.com/webcompat/webcompat.com/labels/status:%20good%20first%20bug)?

**Comment by adamopenweb** [comment]
@dacharya64 Good catch thanks! Do you mind adding a new commit to your current pull request for this please? You can call it something like "Update good first bug link".
