### ISSUE TITLE
Wrong user changing labels

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat.com#1203]
When you're logged in and change a label, it shows that @webcompat-bot made the change, not the logged in user.

(reported by @karlcow, to be confirmed)

**Comment by miketaylr** [comment]
Confirmed, just tested on https://github.com/webcompat/webcompat-tests/issues/482

**Comment by miketaylr** [comment]
Wait a second. This is expected behavior. 

Only repo collaborators and owners can change labels. So a random authed person won't be able to do anything -- we use @webcompat-bot as a proxy to work around this limitation.

**Comment by karlcow** [comment]
capice!
