### ISSUE TITLE
labels gear disappears after changing labels

### ISSUE THREAD

**Issue by karlcow** [webcompat/webcompat.com#1204]
1. Write a comment and change the status of the bug.
2. Submit

The gear disappears.
The page needs to be reloaded to make the gear visible again.

**Comment by miketaylr** [comment]
Confirmed. I think I have an idea.

**Comment by miketaylr** [comment]
I don't think comments matter here, just changing a label is sufficient to make the label gear disappear.

**Comment by miketaylr** [comment]
Also, we end up calling the `on('change:labels'` handler inside LabelList model 5 times whenever we change a label. O_o

```
change:labels inside LabelList model label-list.js:35:7 x 2
change:labels inside LabelList model label-list.js:35:7 x 3
```

**Comment by miketaylr** [comment]
> Also, we end up calling the on('change:labels' handler inside LabelList model 5 times whenever we change a label. O_o

If that was true in the past, it's not now. We call it once in the issue model handler, and once in the StateButtonView, which is expected.
