### ISSUE TITLE
auto-expand the bug reporting/comments area

### ISSUE THREAD

**Issue by karlcow** [webcompat/webcompat.com#1211]
Sometimes I feel the form is a bit tiny when editing a long bug or comment. I resize by dragging the corner of the form, but we could also helps users with an auto-expanding feature.

See for example http://codepen.io/vsync/pen/frudD

(not a priority)

**Comment by miketaylr** [comment]
Would be a cool addition. 👍

**Comment by magsout** [comment]
Ah yes I have something

**Comment by nj4710** [comment]
Hi! I would like to work on this.
