### ISSUE TITLE
links to the three part cycles in the about page

### ISSUE THREAD

**Issue by techchic** [webcompat/webcompat.com#1217]
In the About page,I think it will be a good idea to have links to the three part cycles that takes you to what is being talked about.i.e 'Bug reporting' should have a link that take you to ' Report bug' page  . The link can a appear when you hover your cursor.

**Comment by adamopenweb** [comment]
Good idea! I think as we build out the contributor page further, it might make sense to link to the appropriate sections there. As it will have more of an explanation of the process vs. sending someone to do work without any context.

**Comment by zoepage** [comment]
This will be fixed with the changes in #1480
