### ISSUE TITLE
 webcompact twitter account ,on the 'Contact Us' page

### ISSUE THREAD

**Issue by techchic** [webcompat/webcompat.com#1218]
There is no main webcompat accounts.There should be a webcompact twitter account , like the one on the privacy page.

**Comment by adamopenweb** [comment]
Good point, we list off personal accounts but not the main account.
https://webcompat.com/humans.txt

We're also missing @denschub in there.

**Comment by miketaylr** [comment]
Here's the file to make changes to add the @webcompat twitter account: https://github.com/webcompat/webcompat.com/blob/master/webcompat/static/humans.txt

I'd recommend we let @denschub send a PR adding his own name if he's interested -- he might not want to be named! 🙈

**Comment by denschub** [comment]
> he might not want to be named!

Since you now have mentioned me in this issue, I will never be able to hide myself! Thanks for that!  :crying_cat_face:

(just kidding, submitted a PR.)

**Comment by adamopenweb** [comment]
Looks like we can close this. Thanks everyone! 👍
