### ISSUE TITLE
Consistency in the naming process

### ISSUE THREAD

**Issue by techchic** [webcompat/webcompat.com#1219]
The naming of the processes should be the same and maintained throughout. i.e , I notice in cycle two,it's called bug analysis instead of bug diagnosis.

**Comment by adamopenweb** [comment]
Thanks @techchic. For reference this is on the About page: https://webcompat.com/about

We should probably stick with the same terminology. In this case "analysis" refers to the process of triage and diagnosis. It might be simpler as you suggest to just call it diagnosis. Unless someone objects?

**Comment by miketaylr** [comment]
No objections here.
