### ISSUE TITLE
Redundant 'Contribute' Link? 

### ISSUE THREAD

**Issue by devjayati** [webcompat/webcompat.com#1221]
![screenshot](https://cloud.githubusercontent.com/assets/16128743/19808661/792073de-9d43-11e6-8a63-a92f6a1ca70c.png)
 
Navigating to: www.webcompat.com has a contribute link at the bottom of the page(screenshot attached), but there is already a mention of 'three ways to contribute'. Maybe the https://webcompat.com/contributors (contributor link) could be included under 'Join the team'?

**Comment by miketaylr** [comment]
One thing to consider is that footer is global to the site -- so if you somehow missed the front page and landed on an issue, for example, you might not know about the contribute link. I think duplicate links aren't a bad thing here. ^__^

**Comment by devjayati** [comment]
I agree :) Thank you!
