### ISSUE TITLE
When not logged, we can see closed bugs after clicking on a label

### ISSUE THREAD

**Issue by julienw** [webcompat/webcompat.com#1223]
STR:
1. go to https://webcompat.com/
2. make sure you're not logged in
3. scroll down and click on a label (eg: needstriage)

=> On the resulting page we can find closed bugs.

This is not happening if we're logged in.

**Comment by magsout** [comment]
Thanks @julienw

**Comment by miketaylr** [comment]
This should not happen by design anymore -- there shouldn't be any "needstriage" AND "closed" issues. (@karlcow has a script to make sure this stays true, most of the time).
