### ISSUE TITLE
Investigate why issue didn't get "needstriage" label

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat.com#1228]
@adamopenweb noticed the following issue didn't get a "needstriage" label:

https://github.com/webcompat/web-bugs/issues/3646

It was reported w/ `Mozilla/5.0 (Android 4.4.4; Tablet; rv:51.0) Gecko/51.0 Firefox/51.0 ` -- so possibly the UA string parsing for the labeler webhook has some bugs.

**Comment by adamopenweb** [comment]
Hmm this might be a witch hunt. There's been a few bugs in the last week with the same/similar UA, which looks like it was parsed properly. It only looks at [the browser line ](https://github.com/webcompat/webcompat.com/blob/master/webcompat/webhooks/helpers.py#L32)right? The ones I checked all look identical.
```
<!-- @browser: Firefox Mobile (Tablet) 51.0 -->
<!-- @ua_header: Mozilla/5.0 (Android 4.4.4; Tablet; rv:51.0) Gecko/51.0 Firefox/51.0 -->
<!-- @reported_with: web -->
```
https://github.com/webcompat/web-bugs/issues?utf8=%E2%9C%93&q=is%3Aissue%20label%3Abrowser-firefox-mobile-(tablet)%20

**Comment by miketaylr** [comment]
Thanks for checking -- it might have just been a blip or GitHub's API being down for a second. Might be good to double check the tests that we do have and toss in that UA string.

**Comment by adamopenweb** [comment]
@miketaylr Is this the right spot?
https://github.com/webcompat/webcompat.com/blob/master/tests/test_helpers.py#L39

We currently have:
```
FIREFOX_TABLET_UA = 'Mozilla/5.0 (Android 4.4; Tablet; rv:41.0) Gecko/41.0 Firefox/41.0'
```

**Comment by miketaylr** [comment]
@adamopenweb ya, the only thing I see different is the version `4.4` vs `4.4.4`. Without looking at the code I can't say if that's a bug or not!

**Comment by miketaylr** [comment]
@adamopenweb actually, maybe not. the code for parsing a browser name for a label happens here:

https://github.com/webcompat/webcompat.com/blob/master/webcompat/webhooks/helpers.py#L29

**Comment by miketaylr** [comment]
(and it looks like we don't have tests for that, so we should either write some tests, or try to use the same code that is tested)

**Comment by karlcow** [comment]
We have a couple of functions in helpers which are not really well designed. 
https://github.com/webcompat/webcompat.com/blob/master/webcompat/webhooks/helpers.py#L29-L43
The one @miketaylr is pointing out for example `def parse_and_set_label(body, issue_number):`
is taking the issue_number but doesn't do really anything with it. It creates a side effect. The function doesn't return anything either. And it's probably why we do no have test for it. :) It smells bad. 

For the issue at stake. 
```python
>>> import re
>>> match_list = re.search(r'<!--\s@(\w+):\s([^\d]+?)\s[\d\.]+\s-->', body)
>>> match_list
<_sre.SRE_Match object at 0x1031918b0>
>>> match_list.string
'\n<!-- @browser: Firefox Mobile (Tablet) 51.0 -->\n<!-- @ua_header: Mozilla/5.0 (Android 4.4.4; Tablet; rv:51.0) Gecko/51.0 Firefox/51.0 -->\n<!-- @reported_with: web -->\n\n**URL**: https://www.google.com/search?q=Trump+wins&client=firefox-b&source=lnt&tbs=qdr:h&sa=X&ved=0ahUKEwjc9oq5mZvQAhXJDCwKHalQDD8QpwUIFQ&biw=912&bih=467\n**Browser / Version**: Firefox Mobile (Tablet) 51.0\n**Operating System**: Android 4.4.4\n**Problem type**: Layout is messed up\n\n**Steps to Reproduce**\n1) Navigate to: https://www.google.com/search?q=Trump+wins&client=firefox-b&source=lnt&tbs=qdr:h&sa=X&ved=0ahUKEwjc9oq5mZvQAhXJDCwKHalQDD8QpwUIFQ&biw=912&bih=467\n2) \xc3\xa2\xe2\x80\xa6\n\nExpected Behavior:\nClinton wins\nActual Behavior:\nTrump wins\n\n![Screenshot Description](https://webcompat.com/uploads/2016/11/94bc652e-2833-48ed-87f6-91e1a50b0ff4.jpg)\n\n\n\n_From [webcompat.com](https://webcompat.com/) with \xc3\xa2\xe2\x9d\xa4\xc3\xaf\xc2\xb8\xef\xb8\x8f_\n'
>>> match_list.groups(0)[1]
'Firefox Mobile (Tablet)'
>>> browser = match_list.groups(0)[1].lower()
>>> dash_browser = '-'.join(browser.split())
>>> dash_browser
'firefox-mobile-(tablet)'
>>> 'browser-' + dash_browser
'browser-firefox-mobile-(tablet)'
```
So I was wondering if parenthesis where an issue.
But no
https://github.com/webcompat/webcompat-tests/labels/foo-%28bar%29

**Comment by karlcow** [comment]
```
>>> import json
>>> payload = ['browser-' + dash_browser]
>>> payload
['browser-firefox-mobile-(tablet)']
>>> json.dumps(payload)
'["browser-firefox-mobile-(tablet)"]'
```

everything is fine on the computation side. As @miketaylr said earlier last year, probably network glitches.

The initial issue was needstriage not being set. If I look at where it is set on the webhook it is inside [`__init__.py`](https://github.com/webcompat/webcompat.com/blob/master/webcompat/webhooks/__init__.py)


To make things more robust, we need a way to monitor the response from the server. It ties to my earlier comment on functions returning nothing. We should listen on the response with possible two strategies.

* Log it at first failure
* Queue it at failure for a later on retry, then log it if it fails again. (more complex)

Probably the first step would be to log and see if we have that many failures.

**Comment by karlcow** [comment]
Ah ok. Maybe an idea. https://github.com/webcompat/webcompat.com/blob/master/webcompat/webhooks/__init__.py#L46-L56


```python
            if event_type == 'issues':
                if payload.get('action') == 'opened':
                    issue_body = payload.get('issue')['body']
                    issue_title = payload.get('issue')['title']
                    issue_number = payload.get('issue')['number']
                    parse_and_set_label(issue_body, issue_number)
                    # Setting "Needs Triage" label by default
                    # to all the new issues raised
                    set_label('status-needstriage', issue_number)
                    dump_to_db(issue_title, issue_body, issue_number)
                    return ('gracias, amigo.', 200)
```

1. The `parse_and_set_label(issue_body, issue_number)` is calling `set_label`
2. we do not wait for an answer (side_effect mentioned earlier).
3. We call again `set_label` immediately for setting needstriage

I wonder if GitHub is always happy about that two simultaneous requests on the same endpoint milliseconds apart. 

A proposal. we set the labels in one shot. Calling `set_label` once only. The API allows for a list of labels.

**Comment by karlcow** [comment]
searching for set_label

```
webcompat/webhooks/__init__.py
19:from helpers import parse_and_set_label
20:from helpers import set_label
51:                    parse_and_set_label(issue_body, issue_number)
54:                    set_label('status-needstriage', issue_number)

webcompat/webhooks/helpers.py
29:def parse_and_set_label(body, issue_number):
43:        set_label('browser-' + dash_browser, issue_number)
46:def set_label(label, issue_number):
```

oh and…

```
webcompat/api/endpoints.py
217:@api.route('/issues/<int:number>/labels', methods=['POST'])
218:def modify_labels(number):
```

So Basically we are doing the same thing with two different functions. We probably would gain rationalizing a bit. :)

**Comment by karlcow** [comment]
The double labels setting was added here
https://github.com/webcompat/webcompat.com/pull/1114

**Comment by karlcow** [comment]
And probably connected to the issue #1553 where webcompat-bot is adding, removing the labels. I could see that happening in a kind of race condition on HTTP requests.

**Comment by karlcow** [comment]
I will be working on that next week.

**Comment by karlcow** [comment]
Just an update I have been working on this most of the day. 
I'm creating unit tests for it and for each tests I discover failures which I need to fix in the webhooks helpers functions. We are getting there. :) It should be finished tomorrow. Famous last words.

**Comment by karlcow** [comment]
So fixing this has a lot of implications. I have something solid and working. I just need to tighten the corners for testing.

**Comment by karlcow** [comment]
ok let's create a pull request. There will be probably more improvements possible in the future.
But I guess that's already a solid refactoring.

**Comment by softvision-sergiulogigan** [comment]
Happened again for:
https://github.com/webcompat/web-bugs/issues/9143
https://github.com/webcompat/web-bugs/issues/9144
https://github.com/webcompat/web-bugs/issues/9145
and https://staging.webcompat.com/issues/1262

**Comment by karlcow** [comment]
@softvision-sergiulogigan do you have a 100% way to reproduce it?

**Comment by softvision-sergiulogigan** [comment]
@karlcow well, it is reproducing 100% on my side. Tried this morning with https://staging.webcompat.com/issues/1264 and https://staging.webcompat.com/issues/1265


![screenshot_1](https://user-images.githubusercontent.com/16573771/29551500-9e182ab6-871b-11e7-9aff-0a44ffb974dd.png)

**Comment by karlcow** [comment]
@softvision-sergiulogigan This is weird… because it is not happening for most people given that needstriage are being set. ;) So we need to figure out where is the glitch. Configuration, proxy, specific steps creating this situation.

**Comment by karlcow** [comment]
@softvision-sergiulogigan https://github.com/webcompat/web-bugs/issues?utf8=%E2%9C%93&q=is%3Aissue%20author%3Asoftvision-sergiulogigan%20

All of them seem to have status-needstriage set up by webcompat-bot

Now if you are saying that staging doesn't receive the labels for status-needstriage that's true, but this is staging where we test some specific code. 

@miketaylr which version is deployed on staging?

**Comment by softvision-sergiulogigan** [comment]
@karlcow I assigned the missing label myself, when I saw that it was not automatically assigned. As you can see, also the browser-firefox-mobile label appears to be added by the webcompat-bot, when in fact, it too was added manually.

About the Staging environment, I tested there only after the issue reproduced a couple of times in Production, so I would not log mock bugs in Prod.

**Comment by miketaylr** [comment]
> @miketaylr which version is deployed on staging?

I don't recall -- things are deployed there on demand, basically. (Also... we don't have a nice way to know what version is deployed -- other than hoping the CHANGELOG.md is on the server--  perhaps that's something we should think about).

**Comment by karlcow** [comment]
Probably something that could be tackled by the deploy script. Each time the deploy script is used, it checks the commits and records it in a file. This file is then easily readable by local code such as `environment.py`

**Comment by karlcow** [comment]
For the record, a couple of hours after last @softvision-sergiulogigan comment, he tested again and could not reproduce. I explained that labels were unlikely to be visible right away as they are set out of the band. My guess is @softvision-sergiulogigan was taken aback by his ⚡️ speed.
