### ISSUE TITLE
Possible to do weird things with the issue description textarea

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat.com#1230]
I don't know what's the best way to fix this... `max-width`? `z-index`?

![screen shot 2016-11-23 at 11 19 58 am](https://cloud.githubusercontent.com/assets/67283/20571897/da873f92-b16e-11e6-92a9-e4135c5cf44d.png)

**Comment by adamopenweb** [comment]
Github uses resize: vertical. 
http://caniuse.com/#search=resize

IE and Edge can't resize, I guess.
<img width="788" alt="ie" src="https://cloud.githubusercontent.com/assets/6587558/20573958/4e189af8-b180-11e6-92a5-b7156bb5d9c6.png">

**Comment by miketaylr** [comment]
Ah, that's a good solution, I think.

**Comment by karlcow** [comment]
@miketaylr could you describe how you achieve this :)
So that would help to propose a solution.

**Comment by magsout** [comment]
I don't understand the issue ?

**Comment by denschub** [comment]
You can expand the textarea beyond its usual dimensions, allowing you to break the layout in funny ways, as mike screenshotted. The solution is pretty easy, as Adam commented in https://github.com/webcompat/webcompat.com/issues/1230#issuecomment-262594442.

**Comment by miketaylr** [comment]
Sorry everyone for a terrible bug report. 🐛

**Comment by adamopenweb** [comment]
This also appears on the issue page.
<img width="1090" alt="issuepage" src="https://cloud.githubusercontent.com/assets/6587558/21163467/314deeb4-c161-11e6-8aca-ac25283eb8d2.png">
