### ISSUE TITLE
All issues search seems not working

### ISSUE THREAD

**Issue by karlcow** [webcompat/webcompat.com#1231]
https://webcompat.com/issues?page=1&per_page=50&state=all&stage=all&sort=created&direction=desc&q=unicesumar

1. Go to https://webcompat.com/
2. [search "unicesumar" ](https://webcompat.com/issues?page=1&per_page=50&state=open&stage=all&sort=created&direction=desc&q=unicesumar)
3. Currently get 1 open issue result
4. [Select view all issues ](https://webcompat.com/issues?page=1&per_page=50&state=all&stage=all&sort=created&direction=desc&q=unicesumar)
5. Currently get 0 issue.

[Search on GitHub](https://github.com/webcompat/web-bugs/search?q=unicesumar&type=Issues&utf8=%E2%9C%93) (currently 7 issues: 1 open and 6 closed).

**Comment by miketaylr** [comment]
No longer valid since we're removing "view all issues".
