### ISSUE TITLE
[Contributions] Ratio of valid contributions with empty comments.

### ISSUE THREAD

**Issue by karlcow** [webcompat/webcompat.com#1233]
On the full list of valid contributions (open and closed), how many 

* had no description at all.
* had creator == webcompat-bot
* had no description AND creator == webcompat-bot

(Maybe would be good to see the difference in between mobile and desktop)

Depending on the results of this study, we might want to define UX rules for the form depending on the context. For example, if we see that most of the issues (95%+) with no description and creator == webcompat-bot are invalid or not in scope, we may want to require a description for webcompat-bot users (aka anonymous reporting).

 Once we know the stats, let's open (or not) another issue for the specific coding it would require.

**Comment by adamopenweb** [comment]
I did a small study. Out of 204 open issues in this sample, 23 had no description. I went through each one and 7 of them were valid web compatibility issues. We currently see around 18 valid issues per week, this makes up approximately 10% of the monthly total.

We don't know for sure that forcing users to fill out the form will cause them to quit, though I assume some will. It's probably worth doing some tests on this.

http://bornawesome.com/adam/moz/files/2016/validIssues.json

**Comment by miketaylr** [comment]
From the sample, 7/23 ~30% are valid. It's a small sample, but not a 95% invalid smoking gun. Thoughts @karlcow?

**Comment by karlcow** [comment]
I would like to look a bit further on this. 

* On all issues currently closed as invalid, how many of them had a empty description.
* On all issues (open and closed) and valid, how many of them had an empty description. 

I should make a dump of all issues.

but yes 30% valid is too high to force anything.

Maybe there is a different business rule for mobile and desktop users. Enforceable on Desktop but not on Mobile.
Probably also a better messaging on mobile with step by step in forms. More than a singular form.

**Comment by adamopenweb** [comment]
@karlcow here's a dump from today (if it helps):
http://bornawesome.com/adam/moz/files/2016/Issue_dump_12-20-2016.zip

**Comment by karlcow** [comment]
223668 lines of JSON once pretty formatted. Thanks @adamopenweb !
I started to work on it. There's a bit of data normalization involved. 
Also found something strange, we seem to have 86 issues without labels.

3265 2846 2798 2747 2619 2606 2605 2431 2430 2422 2407 2405 2402 2400 2399 2381 2378 2363 2355 2353 2325 2229 2122 1998 1960 1831 1830 1803 1715 1712 1706 1570 1425 1110 1057 774 662 443 299 276 259 239 233 194 193 192 191 157 147 142 125 111 107 106 104 100 99 95 93 92 84 83 77 75 68 67 64 60 58 52 45 43 35 32 21 19 17 16 15 14 13 12 11 10 8 5

Going through some right now…

Oh… some are pull requests… `/pull/INT == /issues/INT` in GitHub world.
* https://github.com/webcompat/web-bugs/pull/3265 Yikes https://webcompat.com/issues/3265
* https://github.com/webcompat/web-bugs/pull/2747

But some are just closed not properly.


* Just added label. https://github.com/webcompat/web-bugs/issues/2846 
* Just added label. https://github.com/webcompat/web-bugs/issues/2798
*

**Comment by karlcow** [comment]
ok I just fixed. 
3265 2846 2798 2747 2619 2606 2605 2431 2430 2422 2407 2405 2402 2400 2399 2381 2378 

You are welcome to the party.

**Comment by miketaylr** [comment]
> webcompat/web-bugs#3265 Yikes https://webcompat.com/issues/3265

That's goofy.

**Comment by karlcow** [comment]
ok. I made a quick program to check this question:
On all issues currently closed as invalid, how many of them had a empty description. 
if I didn't messed up (minor the incomplete issues listed above and based on @adamopenweb dump.)

TOTAL: 1047 (number of issues with label == status-invalid)
new format: 977 (Steps to reproduce, expected behavior, etc.)
old format: 70 (before we didn't have expected behavior, etc.)

So on these **977** issues labeled as invalid,  **588** issues are empty.

(I will test for the valid case too)

**Comment by karlcow** [comment]
Still going through exploration though we have a bit of garbage in our data, we really need to fix this.

Here the list of bugs with more than one status. This probably happens because when one is managing through github the change of status is not mandatory with a unique keyword.

(3859, [u'status-duplicate', u'status-needstriage'])
(3835, [u'status-duplicate', u'status-needsdiagnosis', u'status-needstriage'])
(3574, [u'status-needsinfo', u'status-worksforme'])
(3057, [u'status-fixed', u'status-sitewait'])
(2757, [u'status-invalid', u'status-needsinfo'])
(2162, [u'status-duplicate', u'status-sitewait'])
(1984, [u'status-fixed', u'status-sitewait'])
(1678, [u'status-needscontact', u'status-worksforme'])
(1594, [u'status-invalid', u'status-needsdiagnosis'])
(1587, [u'status-invalid', u'status-worksforme'])
(1562, [u'status-needscontact', u'status-worksforme'])
(1262, [u'status-invalid', u'status-needsdiagnosis'])
(1240, [u'status-needsinfo', u'status-worksforme'])
(1210, [u'status-ie-bugbar', u'status-needsdiagnosis'])
(1207, [u'status-needsdiagnosis', u'status-worksforme'])
(1190, [u'status-needsinfo', u'status-worksforme'])
(1154, [u'status-duplicate', u'status-needscontact'])
(1133, [u'status-needsdiagnosis', u'status-needsinfo'])
(1100, [u'status-needsinfo', u'status-worksforme'])
(1096, [u'status-needsinfo', u'status-worksforme'])
(1068, [u'status-needsdiagnosis', u'status-worksforme'])
(1036, [u'status-invalid', u'status-needsdiagnosis'])
(1035, [u'status-duplicate', u'status-needsinfo'])
(1011, [u'status-needsinfo', u'status-worksforme'])
(929, [u'status-invalid', u'status-needsdiagnosis'])
(906, [u'status-needsdiagnosis', u'status-worksforme'])
(905, [u'status-needsdiagnosis', u'status-worksforme'])
(898, [u'status-contactready', u'status-worksforme'])
(845, [u'status-contactready', u'status-invalid'])
(844, [u'status-contactready', u'status-worksforme'])
(841, [u'status-contactready', u'status-worksforme'])
(817, [u'status-needsdiagnosis', u'status-worksforme'])
(793, [u'status-contactready', u'status-fixed'])
(788, [u'status-needsdiagnosis', u'status-worksforme'])
(785, [u'status-needsinfo', u'status-worksforme'])
(730, [u'status-sitewait', u'status-worksforme'])
(729, [u'status-sitewait', u'status-worksforme'])
(721, [u'status-invalid', u'status-needsinfo'])
(707, [u'status-needscontact', u'status-worksforme'])
(688, [u'status-duplicate', u'status-needsdiagnosis'])
(687, [u'status-contactready', u'status-worksforme'])
(685, [u'status-contactready', u'status-worksforme'])
(670, [u'status-invalid', u'status-needsdiagnosis', u'status-needsinfo'])
(655, [u'status-needsdiagnosis', u'status-worksforme'])
(651, [u'status-needsdiagnosis', u'status-worksforme'])
(644, [u'status-fixed', u'status-worksforme'])
(642, [u'status-needsdiagnosis', u'status-worksforme'])
(637, [u'status-contactready', u'status-sitewait'])
(635, [u'status-needsinfo', u'status-worksforme'])
(629, [u'status-needsinfo', u'status-worksforme'])
(627, [u'status-needsdiagnosis', u'status-needsinfo', u'status-worksforme'])
(610, [u'status-contactready', u'status-duplicate'])
(603, [u'status-needsdiagnosis', u'status-needsinfo'])
(573, [u'status-needsinfo', u'status-worksforme'])
(559, [u'status-contactready', u'status-worksforme'])
(556, [u'status-needsdiagnosis', u'status-worksforme'])
(526, [u'status-needsdiagnosis', u'status-worksforme'])
(511, [u'status-contactready', u'status-invalid'])
(504, [u'status-needsdiagnosis', u'status-worksforme'])
(502, [u'status-contactready', u'status-fixed'])
(494, [u'status-needsdiagnosis', u'status-worksforme'])
(490, [u'status-needsdiagnosis', u'status-worksforme'])
(489, [u'status-needsdiagnosis', u'status-worksforme'])
(486, [u'status-fixed', u'status-invalid'])
(485, [u'status-contactready', u'status-fixed'])
(483, [u'status-invalid', u'status-needsinfo'])
(482, [u'status-needsinfo', u'status-worksforme'])
(474, [u'status-duplicate', u'status-needsdiagnosis'])
(473, [u'status-invalid', u'status-needsdiagnosis', u'status-needsinfo'])
(467, [u'status-needsinfo', u'status-worksforme'])
(456, [u'status-duplicate', u'status-needsdiagnosis'])
(454, [u'status-needsinfo', u'status-worksforme'])
(446, [u'status-contactready', u'status-worksforme'])
(435, [u'status-needsinfo', u'status-worksforme'])
(429, [u'status-contactready', u'status-worksforme'])
(428, [u'status-contactready', u'status-invalid'])
(418, [u'status-contactready', u'status-worksforme'])
(402, [u'status-invalid', u'status-needsdiagnosis'])
(393, [u'status-needsinfo', u'status-worksforme'])
(390, [u'status-needsdiagnosis', u'status-needsinfo', u'status-worksforme'])
(362, [u'status-contactready', u'status-wontfix'])
(361, [u'status-needsinfo', u'status-worksforme'])
(359, [u'status-needscontact', u'status-worksforme'])
(352, [u'status-needsinfo', u'status-worksforme'])
(351, [u'status-fixed', u'status-needsinfo'])
(332, [u'status-needsinfo', u'status-worksforme'])
(320, [u'status-needscontact', u'status-needsinfo'])
(316, [u'status-duplicate', u'status-invalid'])
(309, [u'status-fixed', u'status-sitewait'])
(308, [u'status-contactready', u'status-sitewait', u'status-worksforme'])
(305, [u'status-fixed', u'status-sitewait'])
(304, [u'status-sitewait', u'status-worksforme'])
(303, [u'status-sitewait', u'status-worksforme'])
(301, [u'status-needscontact', u'status-needsdiagnosis', u'status-worksforme'])
(296, [u'status-needsdiagnosis', u'status-worksforme'])
(289, [u'status-needsdiagnosis', u'status-worksforme'])
(283, [u'status-needsdiagnosis', u'status-worksforme'])
(274, [u'status-fixed', u'status-worksforme'])
(266, [u'status-contactready', u'status-needsinfo'])
(265, [u'status-contactready', u'status-needsinfo'])
(264, [u'status-needsinfo', u'status-worksforme'])
(260, [u'status-needscontact', u'status-worksforme'])
(257, [u'status-contactready', u'status-worksforme'])
(250, [u'status-needsinfo', u'status-worksforme'])
(241, [u'status-sitewait', u'status-worksforme'])
(234, [u'status-contactready', u'status-worksforme'])
(227, [u'status-needsinfo', u'status-worksforme'])
(211, [u'status-invalid', u'status-needsinfo'])
(205, [u'status-needsinfo', u'status-worksforme'])
(202, [u'status-contactready', u'status-wontfix'])
(201, [u'status-contactready', u'status-invalid'])
(200, [u'status-fixed', u'status-sitewait'])
(197, [u'status-fixed', u'status-sitewait'])
(190, [u'status-needsinfo', u'status-worksforme'])
(184, [u'status-contactready', u'status-invalid'])
(183, [u'status-contactready', u'status-worksforme'])
(182, [u'status-contactready', u'status-worksforme'])
(181, [u'status-contactready', u'status-worksforme'])
(180, [u'status-needsdiagnosis', u'status-needsinfo'])
(179, [u'status-needscontact', u'status-worksforme'])
(178, [u'status-invalid', u'status-sitewait'])
(174, [u'status-contactready', u'status-worksforme'])
(159, [u'status-contactready', u'status-fixed'])
(151, [u'status-fixed', u'status-needsdiagnosis', u'status-needsinfo'])
(121, [u'status-invalid', u'status-needsinfo'])
(119, [u'status-contactready', u'status-worksforme'])
(117, [u'status-contactready', u'status-invalid'])
(113, [u'status-invalid', u'status-needsinfo'])
(96, [u'status-needsinfo', u'status-worksforme'])
(81, [u'status-invalid', u'status-needsinfo'])
(74, [u'status-contactready', u'status-wontfix'])
(63, [u'status-needsinfo', u'status-worksforme'])
(61, [u'status-needsdiagnosis', u'status-needsinfo'])
(9, [u'status-contactready', u'status-wontfix'])
(6, [u'status-sitewait', u'status-worksforme'])
(2, [u'status-contactready', u'status-needsinfo'])

**Comment by karlcow** [comment]
OK if I didn't screw up and minus the incomplete/bad data we have in web-bugs

```
→ python issues_stats.py 

new format: 3666
old format: 306 # can't conclude anything
---------------------
INVALID: On 1047 > empty: 432
VALID:   On 2925 > empty: 734
```

so 41% of invalid are empty and 25% of valid are empty.

The code is at https://gist.github.com/karlcow/cdc0075a334790aeefada4a6b8f9292e

so we can close it. And forget about constraining the users.

**Comment by karlcow** [comment]
That said we probably need to clean-up data. Maybe another issue to follow-up with.

**Comment by karlcow** [comment]
Oh oh I need to work harder on this script…

Some bugs have 'Expected Behavior' and some 'Expected Behaviour'. Grmbl.

**Comment by karlcow** [comment]
→ grep -i Behaviour issues.json | wc -l
      20
→ grep -i Behavior issues.json | wc -l
    3698

\o/

**Comment by karlcow** [comment]
rha…
```
grep -i --only-matching '\\nExpected Behavio[u]*r[ ]*\:' issues.json | sort | uniq -c | sort -nr
3661 \nExpected Behavior:
   9 \nExpected Behaviour:
   5 \nExpected behavior:
   1 \nExpected behaviour:
   1 \nExpected behaviour :
   1 \nExpected Behaviour :
   1 \nEXPECTED BEHAVIOR:
```

**Comment by karlcow** [comment]
Let's say that the variation are for now statistically insignificant
