### ISSUE TITLE
Remove QR-related code on issue page

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat.com#1239]
We unintentionally didn't include it in the new issue page redesign. Do we re-include it? Or remove it for-reals? Right now we're including the JS on the page but it won't do anything, so we should make a decision one way or the other.

**Comment by miketaylr** [comment]
cc @tagawa @karlcow @magsout

**Comment by miketaylr** [comment]
Disabled in #1236.

**Comment by tagawa** [comment]
As much as I love QR codes, it seems they're not used that much in other countries so perhaps it's not that necessary. One option is to wait and see if there are any "hey, where'd it go?" comments.

**Comment by magsout** [comment]
Agree with @tagawa

**Comment by miketaylr** [comment]
That seems reasonable.

**Comment by miketaylr** [comment]
Let's use this issue to remove, and keep our eyes open for users who want it back.
