### ISSUE TITLE
Put label editor on right side of issues page.

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat.com#1240]
Currently it's down by the comment widget, which is great if you're going to comment. Not so great if you want to see what labels are currently applied.

We'd also like to put a "milestone/status/whatever" widget under (or above?) the labels widget.

cc @magsout

**Comment by miketaylr** [comment]
<img width="981" alt="screen shot 2016-12-13 at 5 18 08 pm" src="https://cloud.githubusercontent.com/assets/67283/21163339/282cf568-c158-11e6-909e-f58b1f5d756f.png">

**Comment by zoepage** [comment]
@miketaylr @karlcow 
How about that?

<img width="1030" alt="screen shot 2017-01-12 at 12 01 41 pm" src="https://cloud.githubusercontent.com/assets/562354/21887205/440c4832-d8bf-11e6-97fe-dc71d2bc673e.png">

**Comment by karlcow** [comment]
@zoepage It's an interesting idea but it doesn't solve some of the constraints.

Let's make a summary of the constraints.

* We change labels when we are taking action (most of the time after a comment).
* Some users (like @miketaylr ) would like to have on desktop viewport the labels on the right side.
* On mobile the labels can't be on the right side
* It is useful to see the labels for knowing which browsers and which status for the issue.
* The current state is temporary and ill-defined because we wanted to deploy the redesign of the issue box (It took too long #545 Life 😄 ). So the position under the issue is not what is/was planned :)

**Comment by miketaylr** [comment]
There were some proposed designs for label editor by @karlcow and @zoepage -- but I can't seem to find them. If either of you remember where, would you mind posting a link? I'd like to start building this, because it blocks the work in #886.

**Comment by miketaylr** [comment]
Ah, nevermind -- should have clicked on the `scope: design` label. Proposed ideas @ https://github.com/webcompat/webcompat.com/issues/1259#issuecomment-270819640 and below. I'll repost the images here for convenience:

![](https://cloud.githubusercontent.com/assets/505230/21706043/5329d710-d407-11e6-99f3-38a6e36b9c2f.png)

<hr>

![](https://cloud.githubusercontent.com/assets/505230/21706044/5329ee26-d407-11e6-8ede-eb3545d7348f.png)

<hr>

![](https://cloud.githubusercontent.com/assets/562354/21844295/53dd3a04-d7ee-11e6-93f3-2b90fa5b3524.png)

**Comment by magsout** [comment]
>The current state is temporary and ill-defined because we wanted to deploy the redesign of the issue box (It took too long #545 Life 😄 ). So the position under the issue is not what is/was planned :) 


I'm a 
![img_2246](https://cloud.githubusercontent.com/assets/1997108/22236566/b03ef554-e206-11e6-9129-5929a63897a6.GIF)

**Comment by magsout** [comment]
![img_2247](https://cloud.githubusercontent.com/assets/1997108/22238841/e88a491a-e213-11e6-97ef-120a05aa7b69.JPG)

**Comment by zoepage** [comment]
How about we put the labels in like in the following screenshot?
From the information architecture site it would be the same as the box for bigger screens. 
Could get too long for scrolling tho...
<img width="1030" alt="screen shot 2017-01-12 at 12 01 41 pm" src="https://cloud.githubusercontent.com/assets/562354/22291210/5ee2c2da-e305-11e6-89e8-fe9fbaff28c4.png">

**Comment by miketaylr** [comment]
@zoepage that's essentially what the last version of labels looked like, with the editor gear/widget to the left of the labels in your mock).

The reason we want to move away from that is if there are more than a few comments, you lose sight of labels, and have to scroll all the way up to add them. The proposed sidebar (like GitHub) gets around that because it should be sticky, staying visible in the viewport even after you scroll.

@magsout a horizontal scrollable list of labels for small screens is interesting... my first reaction is that seems a bit weird, but maybe it would work?

**Comment by magsout** [comment]
@miketaylr It depends on the number of labels we have on average?

I think that in most cases the scrollbar will be useless, since we have on average, I think, 3 labels?

**Comment by miketaylr** [comment]
@magsout yeah good point. It doesn't get much longer than that. 

Another thing to consider, we want 2 boxes. One for "milestone" (status), another for regular labels.

**Comment by magsout** [comment]
@miketaylr  ah, I forgot that

**Comment by miketaylr** [comment]
That said, the "milestone" editor will only show a single milestone, it's not possible for an issue to be in more than one. So it doesn't have the same space constraints.
