### ISSUE TITLE
centered "please login" looks strange

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat.com#1244]
<img width="958" alt="screen shot 2016-12-16 at 3 37 01 pm" src="https://cloud.githubusercontent.com/assets/67283/21279378/8cac3d92-c3a5-11e6-9277-360fb9bc2640.png">

If you're logged out and look at an issues page, the please login message is centered -- and looks strange, IMO. We should maybe left-align it w/ the issue container?

(Another possible option is to move it to the right hand side up top in another column, w/ the G for GitHub thing, I imagine we'd want labels to go there as well.).

**Comment by miketaylr** [comment]
@magsout how hard would it be to create another column to the right for these links + labels?

**Comment by magsout** [comment]
@miketaylr easy ;)

**Comment by zoepage** [comment]
Setting the message left, so we can close the issue and can rethink how to solve the labels issue later on. Are you all ok with it? @magsout @miketaylr

**Comment by miketaylr** [comment]
@zoepage yeah, LGTM. Slightly less weird. :)
