### ISSUE TITLE
Cleaning up incorrect status labels on web-bugs data

### ISSUE THREAD

**Issue by karlcow** [webcompat/webcompat.com#1250]
As the result of studying data in web-bugs #1233, I realized we have a lot of bogus issues with incorrect labels.

1. Fix issues [without status labels](https://github.com/webcompat/webcompat.com/issues/1233#issuecomment-268416182)
2. Fix issues [with multiple status labels](https://github.com/webcompat/webcompat.com/issues/1233#issuecomment-268701048)
3. Fix issues closed [without the appropriate label](https://github.com/webcompat/web-bugs/issues?page=22&q=is%3Aissue+is%3Aclosed+-label%3Astatus-invalid++-label%3Astatus-fixed+-label%3Astatus-duplicate+-label%3Astatus-worksforme+-label%3Astatus-incomplete+-label%3Astatus-wontfix&utf8=%E2%9C%93) Currently 600 issues

The reason is probably when issues are managed through github and we are forgetting to change the labeling appropriately. It's also probably because of the UI of Github where when an issue has a lot of comments, the label widget is up there out of sight in the UI. It's one of the reasons I pushed to have the label widget near the comments section on webcompat.com

**Comment by karlcow** [comment]
To avoid this in the future, I proposed issue #1251 for a janitor script

**Comment by karlcow** [comment]
I started manually to cleanup issues with these two criteria

* closed
* status-needsdiagnosis

most of them are duplicate of something where the person who closed forgot to change the label. (We have a winner for the biggest offender 👮 )

**Comment by miketaylr** [comment]
Thanks for cleaning this up, @karlcow. Let's just pretend the biggest offender isn't me.

**Comment by karlcow** [comment]
* fixed all closed issues without labels.

**Comment by karlcow** [comment]
* fixed all the issues which were closed but had a status-needscontact

**Comment by karlcow** [comment]
* next to do 86 to fix. https://github.com/webcompat/web-bugs/issues?q=is%3Aissue+is%3Aclosed+label%3Astatus-needsdiagnosis

**Comment by miketaylr** [comment]
Thanks for working on this @karlcow.

**Comment by karlcow** [comment]
* fixed all the issues which were closed but had a status-needsdiagnosis
* next 54 for needinfo https://github.com/webcompat/web-bugs/issues?q=is%3Aissue+is%3Aclosed+label%3Astatus-needsinfo
* next 10 for needstriage https://github.com/webcompat/web-bugs/issues?q=is%3Aissue+is%3Aclosed+label%3Astatus-needstriage
* next 57 for sitewait https://github.com/webcompat/web-bugs/issues?q=is%3Aissue+is%3Aclosed+label%3Astatus-sitewait

Anyone is welcome to join the "fun" :p

**Comment by magsout** [comment]
I love fun. Let's go

**Comment by magsout** [comment]
Done: https://github.com/webcompat/web-bugs/issues?q=is%3Aissue+is%3Aclosed+label%3Astatus-needsinfo

**Comment by magsout** [comment]
Done: https://github.com/webcompat/web-bugs/issues?q=is%3Aissue+is%3Aclosed+label%3Astatus-needstriage

**Comment by magsout** [comment]
And done: https://github.com/webcompat/web-bugs/issues?q=is%3Aissue+is%3Aclosed+label%3Astatus-sitewait

**Comment by karlcow** [comment]
wow. Thanks a lot @magsout ❤️

**Comment by karlcow** [comment]
We can mark this as fixed. I checked the different issues from the comment 1 and it seems to be ok. Now I need to work on #1251 so that we do not let it drift. 

Thanks a lot to @magsout for helping on this ungrateful task.
