### ISSUE TITLE
Weekly janitor scripts to flag incorrect status labels on issues

### ISSUE THREAD

**Issue by karlcow** [webcompat/webcompat.com#1251]
Issue #1250 is about cleaning the current bogus data with improper status- labels

To avoid bogus data in the future, we probably need a script 

1. going through all the issues 
2. once a week 
3. send an email to us 
4. with bugs to fix manually

There should not be much.

**Comment by miketaylr** [comment]
Great idea, @karlcow. 👍

**Comment by karlcow** [comment]
Started https://github.com/karlcow/webcompat-janitor

**Comment by karlcow** [comment]
This will become useless soon. Probably next week if we achieve what we want in #886

**Comment by karlcow** [comment]
Useless now that #886 has been created.
