### ISSUE TITLE
Make comments editable

### ISSUE THREAD

**Issue by devjayati** [webcompat/webcompat.com#1256]
Is there a way people who are logged in at webcompat.com can edit their comments (on an issue)? (For example, if I wrote something by mistake, I am unable to change it and need to add an additional comment)

**Comment by miketaylr** [comment]
Not currently, but it shouldn't be too much work!

@devjayati the workaround solution is to press "g" on a webcompat Issue page, which will take you to the corresponding GitHub issue page, which *will* allow you to edit your comments.

**Comment by karlcow** [comment]
Nobody looked at this for the last… 3 years.
Putting it on backlog.
