### ISSUE TITLE
Code for hidding the comments is not working

### ISSUE THREAD

**Issue by karlcow** [webcompat/webcompat.com#1257]
We had a code in webcompat.com for hidding HTML comments. 
This code doesn't work anymore. See the screenshot.

![capture d ecran 2016-12-26 a 09 08 14](https://cloud.githubusercontent.com/assets/505230/21473364/0f88b360-cb4b-11e6-9a9e-a82a54df56c6.png)

**Comment by magsout** [comment]
hum, strange, I have no issue.. 
![capture d ecran 2016-12-31 a 16 49 50](https://cloud.githubusercontent.com/assets/1997108/21578247/2de4ba02-cf79-11e6-8e24-33e313c55da2.png)

On every issue, you have this bug @karlcow  ?

**Comment by karlcow** [comment]
Tested a couple of issues just now. And it's not happening anymore. Let's close it. I will try to be careful about the circumstances if it's happening again.

Thanks.
