### ISSUE TITLE
Labels section should be above the comment box.

### ISSUE THREAD

**Issue by karlcow** [webcompat/webcompat.com#1259]
Currently the labels section is just under the described issue.
We want to have it readily near the comment section, because it is where it is most likely to be used. Probably above.
 
![capture d ecran 2016-12-26 a 10 27 35](https://cloud.githubusercontent.com/assets/505230/21473650/285ba59a-cb56-11e6-956d-69388b4efc7b.png)

**Comment by miketaylr** [comment]
I think I'd prefer to have the label widget to the right, always floating: https://github.com/webcompat/webcompat.com/issues/1240 -- and a milestone widget under/above it.

**Comment by karlcow** [comment]
This would work on desktop but not on mobile. We may be able to manage both.

**Comment by miketaylr** [comment]
Good point!

**Comment by magsout** [comment]
So, on small screen, label editor nears the comment, and big screen: issue on left, and label, milestone, etc... on right like @miketaylr proposed on this issue https://github.com/webcompat/webcompat.com/issues/1240

**Comment by karlcow** [comment]
experimenting with what @miketaylr said and giving it a twist. just for exploration.
![capture d ecran 2017-01-06 a 11 56 10](https://cloud.githubusercontent.com/assets/505230/21706043/5329d710-d407-11e6-99f3-38a6e36b9c2f.png)
![capture d ecran 2017-01-06 a 11 56 27](https://cloud.githubusercontent.com/assets/505230/21706044/5329ee26-d407-11e6-8ede-eb3545d7348f.png)

**Comment by miketaylr** [comment]
iiiiiiinteresting.

**Comment by magsout** [comment]
oh yes 👍

**Comment by denschub** [comment]
I like it. If the right box is sticky, it should probably be closer to the top. The labels look a bit weird, have you tried moving the gear icon to the right end of the box? I guess that would look nicer.

Also, since we have a lot of free space there, it's probably not needed to make the font inside the colored smaller. Maybe it's worth a try using the same font size as used in the rest of that box, maybe removing the bold.

(Also, probably unrelated, it's really driving me nuts that author name + date are underlined in the history but the author is not underlined above the "leave a comment" area. I don't think it's actually needed to underline them - even if they are links, their value is probably low enough to make them non-underlined. Underlining stuff always looks weird to me.)

**Comment by miketaylr** [comment]
> The labels look a bit weird, have you tried moving the gear icon to the right end of the box? I guess that would look nicer.

Also, since we have a lot of vertical space, we could just make them a vertical list, like GitHub.
<img width="266" alt="screen shot 2017-01-11 at 10 56 22 am" src="https://cloud.githubusercontent.com/assets/67283/21843804/9e2eb346-d7ec-11e6-9810-109e87f0e1e5.png">

**Comment by zoepage** [comment]
Was thinking the same with the labels and the icon. Only concern would be, the colours could go wild at some point. But it's probably just me ;)

<img width="1001" alt="screen shot 2017-01-11 at 11 08 09 am" src="https://cloud.githubusercontent.com/assets/562354/21844295/53dd3a04-d7ee-11e6-93f3-2b90fa5b3524.png">

**Comment by karlcow** [comment]
@zoepage The colors for webcompat.com are controlled. or supposed to be controlled. So you would not have these labels which comes from webcompat.com and not web-bugs ;)

I guess it's because @miketaylr started it ;) with the wrong screenshot. He was just illustrating the list not the colors.

Maybe still heavy.

![capture d ecran 2017-01-12 a 10 13 59](https://cloud.githubusercontent.com/assets/505230/21873136/e33cfad8-d8af-11e6-804c-dfdbe0b49e9c.png)


@miketaylr **if** we were going that route with the widget (once we also figured out the mobile version), we should open a separate bug.

I would recommend we do baby steps with this to avoid the giant redesign we had with issues.

**Comment by karlcow** [comment]
@zoepage +1 on being the lighter touch side for widget color code. We need a bit more exploration and tests with all type of labels we can have up there. :)

**Comment by zoepage** [comment]
@karlcow +1 on small steps. I'd love to make a concept at some point and rethink the whole design. So we have a roadmap and can start from there to make it happen step by step.

And +1 on the color code. ;)

**Comment by miketaylr** [comment]
> it's because @miketaylr started it ;)

This is generally the case.

**Comment by miketaylr** [comment]
Also yeah, the bug for that is https://github.com/webcompat/webcompat.com/issues/1240.

**Comment by zoepage** [comment]
@miketaylr @karlcow How about that?

<img width="1030" alt="screen shot 2017-01-12 at 12 01 41 pm" src="https://cloud.githubusercontent.com/assets/562354/21887130/ef393dd8-d8be-11e6-8d51-2bba3fa49d0c.png">

**Comment by karlcow** [comment]
@miketaylr this issue about the 

* #886 Use Milestones for status 
* #1178 New labels for type of issues categorization 
* #1232 Is there something better to do with "out of scope" bugs?
* #863 Create UI for filtering on several labels / search strings

* #1259 label editor near the comment box
* #1240 label editor on the right side on desktop

* #1251 Weekly janitor scripts to flag incorrect status labels on issues 
* #1250 Cleaning up incorrect status labels on web-bugs data 

* #1204  labels gear disappears after changing labels 
* #1258 some labels are not readable because of contrasts issue 

We start to mix friends. I wonder if we need a labels milestones. And small issues for each redesign decision implementation we will take. Plus it will help @zoepage to have a better overview. :) We accumulated of lot of legacy and some discussions.

**Comment by magsout** [comment]
Why removed author for the first comment ? Let comment same for all ?

**Comment by karlcow** [comment]
@magsout What do you mean?

**Comment by zoepage** [comment]
Just so we don't forget for context, #1244.

**Comment by miketaylr** [comment]
> I wonder if we need a labels milestones.

@karlcow if you'd like that create that, it would be useful. I'd like to see this work get done in the near future. Any of the proposed designs here are a massive improvement.

**Comment by miketaylr** [comment]
(setting as good next bug, as this is a bit involved)

**Comment by karlcow** [comment]
Milestones for labels work created
https://github.com/webcompat/webcompat.com/milestone/34

**Comment by magsout** [comment]
I start to work on it this night.

**Comment by zoepage** [comment]
@magsout if you'd like to discuss concept things through or have questions about design aspect, LMK! I'll be around all evening && happy to help :)

**Comment by miketaylr** [comment]
> I start to work on it this night.

awesome!

**Comment by magsout** [comment]
ok, Some test https://cl.ly/2W3r2S1A3z2l

**Comment by magsout** [comment]
second test https://cl.ly/3F3v0u3M0I2Q

Label a-la Github

**Comment by magsout** [comment]
Need to think about small screen

**Comment by zoepage** [comment]
I love the second test. (The background color jumps are probably just a video issue, I guess.) :)

Very excited about the small screen :)

**Comment by miketaylr** [comment]
@magsout do we consider this fixed now?

**Comment by miketaylr** [comment]
oh wait, yeah we do. :)

**Comment by magsout** [comment]
<3
