### ISSUE TITLE
Reporting new issues doesn't redirect to its permanent URI

### ISSUE THREAD

**Issue by karlcow** [webcompat/webcompat.com#1262]
Steps to reproduce.

1. Report a new issue.
2. Get the new flash message on top of the issue
3. Check the URI in the address bar `https://webcompat.com/issues/new` instead of the `https://webcompat.com/issues/[NNNN]`

Note that the flash knows the URI to go 
`https://twitter.com/intent/tweet?text=I%20just%20filed%20a%20bug%20on%20the%20internet%3A&url=https%3A%2F%2Fwebcompat.com%2Fissues%2F4078&via=webcompat`

So it should not be an issue to either redirect to the right place or change window.history

**Comment by miketaylr** [comment]
Whoops.
