### ISSUE TITLE
Add thumbnail tests for two sizes image upload

### ISSUE THREAD

**Issue by karlcow** [webcompat/webcompat.com#1267]
This is a followup on the issue #722 and its pull request #1266 
1. We need to test if when uploading an image we produce the right markup in MarkDown. (js functional test)
2. We probably need to test that the images are created at the right place too. (python unittest)

**Comment by karlcow** [comment]
Was this fixed in #1557?

**Comment by karlcow** [comment]
With https://github.com/webcompat/webcompat.com/blob/dd8102a3d0f89d18bea2a86228afac2fcfeead44/tests/functional/image-uploads-non-auth.js#L144

**Comment by zoepage** [comment]
> Was this fixed in #1557?

@karlcow To who was this question directed to?

**Comment by karlcow** [comment]
Maybe myself

**Comment by karlcow** [comment]
This is fixed. I believe.
