### ISSUE TITLE
Fix failing image upload tests

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat.com#1268]
Busted from merging https://github.com/webcompat/webcompat.com/pull/1266

https://travis-ci.org/webcompat/webcompat.com/builds/189375239

https://github.com/webcompat/webcompat.com/blob/master/tests/functional/image-uploads-non-auth.js (fixing this would effectively fix half of https://github.com/webcompat/webcompat.com/issues/1267.

cc @karlcow

**Comment by karlcow** [comment]
rha my bad. Thanks.
fixing it now.

**Comment by karlcow** [comment]
Handled in https://github.com/webcompat/webcompat.com/pull/1557
