### ISSUE TITLE
Images for Retina displays

### ISSUE THREAD

**Issue by zoepage** [webcompat/webcompat.com#1274]
Images are too low-res for retina displays on the website, e.g. https://webcompat.com/contributors.
Either we need to add `srcset` or fix it in a different way (more sustainable).

Any thoughts?

**Comment by karlcow** [comment]
thanks @zoepage. Ah. And I found #428
What do you see on retina screens?

/me proposes to age the world population so blurry images are not an issue anymore ;)

**Comment by miketaylr** [comment]
Yeah, they are pretty blurry on retina (probably need to click on the image to see it in all its blurriness).

<img width="1100" alt="screen shot 2017-01-10 at 10 51 30 am" src="https://cloud.githubusercontent.com/assets/67283/21801627/c50eaf7c-d722-11e6-88f9-aba2a8765975.png">

I know Mesha is planning on working on a contributors page revamp as part of her Outreachy project, possibly a good opportunity to fix this up as well.

**Comment by zoepage** [comment]
Thanks @miketaylr for the additional information. :)

Yes, I'll have planed a meeting soon with her. So we can go over a few things.

**Comment by zoepage** [comment]
Just cross-linking so it doesn't get lost. https://github.com/webcompat/webcompat.com/issues/1285

**Comment by magsout** [comment]
The resolution must be doubled.

**Comment by zoepage** [comment]
@magsout we need a process to make sure every picture that gets added at some point is added in different resolutions. any ideas?

**Comment by magsout** [comment]
@zoepage 

>every picture that gets added at some point is added in different resolutions. any ideas?

What do you mean ?

**Comment by zoepage** [comment]
@magsout right now the images are just there in one resolution, right?
we'll change that at some point. i'd love to have a process or something, so when we add more pictures to content we don't forget to add more resolutions (well, at least 2)...

**Comment by magsout** [comment]
@zoepage something like that https://developer.mozilla.org/en-US/docs/Learn/HTML/Multimedia_and_embedding/Responsive_images ?

But I don't know if it's necessary, Basically we can double the size of images, If the weight of the image is ok, we can leave the images without adding additional format / resolution.

**Comment by zoepage** [comment]
i'll close this issue. we can re-open, if it pops up again.
