### ISSUE TITLE
[proposal] Add a required "does this work in another browser" question to bug report form

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat.com#1278]
The idea is to communicate the notion that people should be trying other browsers when reporting bugs:

* Does this bug happen in another browser?
* Does the site work in another browser?
* Some other, better worded question
  * yes
  * no
  * (i don't know) <-- unsure if we need this?

I think we should require people to select a radio choice, but probably not prevent bugs from being submitted even if the answer is "i don't know".

Thoughts @webcompat/core-developers?

**Comment by miketaylr** [comment]
No feedback, but https://github.com/webcompat/webcompat.com/issues/1232#issuecomment-273944358 suggests @karlcow is onboard.

**Comment by adamopenweb** [comment]
I really like the idea. Would be good to get this in somewhat quickly to help with our current wave of reports.

Not to sidetrack her, but @lockettm might have some helpful feedback on this.

**Comment by miketaylr** [comment]
> Would be good to get this in somewhat quickly to help with our current wave of reports.

Agreed.

**Comment by lockettm** [comment]
I think it’s a great idea that helps reinforce the site’s mission.

I like "Does this happen in another browser?"

Omitting the "I don’t know" option would likely cause users to drop off, but could result in better submissions.

Thoughts relating to comments made by @zoepage in #1232:

This may be an opportunity to educate users. Suspected non-compat submitters could be shown a tailored thanks message that does one or more of the following:
* Briefly clarifies what web compatibility bugs are
* Explains that web compatibility issues are the priority for this site
* Links to more appropriate bug trackers or information

**Comment by zoepage** [comment]
Great points!
@lockettm 
> Explains that web compatibility issues are the priority for this site

I love that point especially! This should help with setting our expectations and making them clear. Here we could maybe also add pointers to "where to submit a regular site issue"?

**Comment by miketaylr** [comment]
> Omitting the "I don’t know" option would likely cause users to drop off, but could result in better submissions.

In general, my opinion is we should be very liberal in allowing people to submit bug reports to us (see for example, lack of strict URL validation).

I wouldn't want to block a report based on this one section. So I'd agree to skipping the "I don't know" option if we made it a non-required field.

**Comment by denschub** [comment]
I also think we should add this question to our form. Not too sure about "Does this happen in another browser?", I would rather tend towards "Does this issue happen in another browser?" just to eliminate any possible confusion.

In my opinion, we should make the radio buttons required, but add a "Didn't check" option. That way, we maybe could motivate some people to give it a try? Also, of someone selects "Yes", we could add a note stating that this is not the focus of our work, but they are happy to report it anyway so someone can have a look at it. Maybe we could even assign the milestone automatically (while leaving them in the triage queue), which could save some clicks.

**Comment by miketaylr** [comment]
> Maybe we could even assign the milestone automatically (while leaving them in the triage queue), which could save some clicks.

That's a good suggestion.

**Comment by miketaylr** [comment]
We kinda have this now. CLosing.
