### ISSUE TITLE
Add reply templates for closing bugs

### ISSUE THREAD

**Issue by zoepage** [webcompat/webcompat.com#1279]
As @adamopenweb already mentioned, having pre-defined templates as a reply that explain why an invalid bug was closed would be really helpful and we all could use them.

The template(s) should:
- explain why the bug was closed
- be maybe educational, so bug reports get better over time (people learn from their mistakes, right? :) )
- link to more info, if needed.

If you have any suggestions, please post suggestions below. 

You can find here already a good list of "why a bug was closed".
https://github.com/webcompat/webcompat.com/wiki/Invalid-Bugs

**Comment by karlcow** [comment]
This seems to be the same issue (or very close) than #1179
@zoepage @adamopenweb opinions?

**Comment by adamopenweb** [comment]
Oh yeah, looks like it @karlcow.

**Comment by zoepage** [comment]
happy to close it @karlcow
