### ISSUE TITLE
Cursor on div instead of input / label

### ISSUE THREAD

**Issue by adamopenweb** [webcompat/webcompat.com#1280]
This is a very minor issue. You can hover the mouse out in the white space and the cursor switches to pointer, as if you can click a category for "What seems to be the trouble?", but selection isn't possible.

<img width="749" alt="sc" src="https://cloud.githubusercontent.com/assets/6587558/21900507/11c6dfa6-d8c2-11e6-8d86-e2f166e1b50e.png">

The div for these items contains:
```css
.wc-Form-radio {
  cursor: pointer;
}
```

Maybe we should move this to the radio input and label?

**Comment by magsout** [comment]
hum, I think removing this property is best. It is useless., I don't know why I writed this and it's
