### ISSUE TITLE
Replace Twitter text link with icon

### ISSUE THREAD

**Issue by lockettm** [webcompat/webcompat.com#1282]
Would an icon make it easier for users to scan and recognize the Twitter account?
![social](https://cloud.githubusercontent.com/assets/4382193/21940070/68ffa4c8-d977-11e6-99b6-7eb84bcf300e.jpg)

Text blends in, while social media icons are quickly recognized. Also, users are likely to visually scan for icons when they want to find a social media contact.

**Suggestion**
Replace the text link with the platform’s icon. Also, consider linking to GitHub. 
![social-icons](https://cloud.githubusercontent.com/assets/4382193/21940089/7ffe29d8-d977-11e6-8719-cdf4728f0cdf.jpg)

**Comment by miketaylr** [comment]
+1. Any links to usable assets?

**Comment by magsout** [comment]
We can use svg from https://icomoon.io/

**Comment by miketaylr** [comment]
Ah yeah, nice @magsout.

<img width="201" alt="screen shot 2017-01-17 at 3 06 53 pm" src="https://cloud.githubusercontent.com/assets/67283/22040035/1e92d6aa-dcc7-11e6-8bec-3fe9a245c06a.png">

**Comment by lockettm** [comment]
I used icons with a distinct outline, as they’re believed to be easier to scan and recognize. http://uxmovement.com/buttons/why-distinct-icon-outlines-help-users-scan-faster/

Both are on http://fontawesome.io/icons/

If using SVG, Twitter's is on icomoon.io as @magsout mentioned, and GitHub’s is here: https://octicons.github.com/icon/octoface/

**Comment by magsout** [comment]
@lockettm we use https://icomoon.io/ to make icon-font, fontwesome is avalable on https://icomoon.io/.  So we can add icon form fontwesom dircty from icomoon.

https://github.com/webcompat/webcompat.com/tree/master/webcompat/static/font/webcompat

icon are avaiblable here https://github.com/webcompat/design/tree/master/3_Style%20Guide/icon%20from%20icomoon, but honestly I don't remember if it's up to date?

**Comment by miketaylr** [comment]
> Replace the text link with the platform’s icon. Also, consider linking to GitHub.

I like the idea of also linking to GitHub.

**Comment by lockettm** [comment]
A quick update for the record.

While testing mockups of this with a few users, one selected the Twitter link as mentioned in #1373.

No one selected the GitHub icon (maybe more experienced users would?). However, IMHO, I’d still add it.

**Comment by miketaylr** [comment]
Thanks for the update! I agree including the GH icon is still a good idea. Besides, it looks cool. :)

**Comment by zoepage** [comment]
Closing in favor of follow up issue: #1401
