### ISSUE TITLE
Review Join the Team section on homepage

### ISSUE THREAD

**Issue by lockettm** [webcompat/webcompat.com#1283]
I think we can tweak the **Join the Team** section to better serve potential contributors. 

**Three Ways to Contribute** 
Currently _Report bugs_, _Diagnose bugs_, and _Reach out to sites_, link to the report form and open issues. Great for frequent and returning users, but this may confuse new visitors who are looking to learn more about contributing, as it’s under the Join The Team heading. 

![join-the-team](https://cloud.githubusercontent.com/assets/4382193/21941233/9eac65fc-d97c-11e6-87f4-65e4005d24b8.jpg)
A couple of thoughts: 

* The links are actionable and ideal for users who know what they’re doing. So maybe we keep them, but simply add a short explanation under each step to give more context about the specific tasks???

* Or, we can link to a more detailed explanation for each step on the soon to be redesigned Contributors page.

**Learn More**
Also, I’m thinking Learn More should link to /contributors instead of /about, as it seems more helpful to new visitors who are interested in contributing. However, this may be less relevant if we alter the Three Ways to Contribute section. 

Thoughts?

**Comment by lockettm** [comment]
Following up to include more context and suggestions from #1296. 

**Homepage Scenarios**
Scenario 1: Followed a link from an article.
Scenario 2: Google led me here. It’s unclear as to why.
Scenario 3: I simply came to report a bug.

**Content Ideas**
* What is web compat 
* Join the team / 3 ways to contribute (bug team) 
* Link to other ways of contributing (developing webcompat.com and community building)

**Comment by zoepage** [comment]
Referencing new icon ideas:
https://github.com/webcompat/webcompat.com/issues/1374

**Comment by lockettm** [comment]
<img width="770" alt="screen shot 2017-03-06 at 2 37 41 pm" src="https://cloud.githubusercontent.com/assets/4382193/23633452/a67e585e-027a-11e7-939b-aae503b427b7.png">

After testing the above changes with several users, I’d suggest:

* Replacing "Join the Team" with “Help Us Improve the Web.” One user read this while scanning the page and quickly understood the mission.
* Replacing “Learn More” with “Learn more about **how to contribute**.” And linking to the contribute page instead of the About page. One user selected this link to navigate to the Contribute page.
* Adding additional context under “Bug Reporting,” “Bug Diagnosis” and "Site Outreach.” Although one user clicked one of the links without reading the text, three others read it and seemed to have a better understanding of the process.

**Comment by zoepage** [comment]
Fixed.
