### ISSUE TITLE
Design contact page

### ISSUE THREAD

**Issue by lockettm** [webcompat/webcompat.com#1284]
Any thoughts on designing a contact or team page to replace /humans.txt? 

Images would give the project a more personable feel, and social/email links would make it easier for users to contact the team. 

Possible content:
* Picture of each team member--or their GitHub profile pic, if everyone's comfortable.
* Links to each member’s Twitter, GitHub, and/or email.
* A contact form or an email link to a single point of contact.

**Comment by karlcow** [comment]
@lockettm Could you clarify the purpose of the page?

Why I'm asking:

The site webcompat.com is a community Web site, so everyone who has reported a bug, commented, did triage is a contributor of the Web compatibility work.

The humans.txt which follows the guidelines of http://humanstxt.org/ is a really geeky wink about the people who are coding/ux/design the Web site (it is not necessary up to date btw). 

But I guess your message comes partly because of this: The link **Contact** at the bottom to https://webcompat.com/humans.txt indeed doesn't make sense. It was kind of making sense at the beginning… maybe. Let's say it's geeky legacy UI  🤡 

It should really be a contact page, with the different channels to communicate with us. I often wonder if we should move the IRC discussions about webcompat.com to freenode:#webcompat. There is only @denschub and me on this channel.

**Comment by lockettm** [comment]
@karlcow The purpose of a team page would be to display the core members of the community, not necessarily every contributor. Although, additional contributors could be acknowledged by linking to the people page on GitHub https://github.com/orgs/webcompat/people

Social recognition is an important motivation for many contributors. Seeing current members acknowledged could help engage newcomers. I think seeing the people behind the website would make the project more approachable as well—similar to the humans txt initiative—although maybe not as geeky and cool :)

Agreed, the Contact page should link to specific communication channels, unless it’s preferred that visitors contact an individual team member. 

Alternatively, details about core team members could be included on the Contributors page instead of the Contact page.

**Comment by adamopenweb** [comment]
@miketaylr mentioned that the revised contact page could also display details about when and how we meet. Vidyo, IRC, (maybe Slack someday), mailing list and meeting notes.

**Comment by karlcow** [comment]
@lockettm 
>The purpose of a team page would be to display the core members of the community

Understood. The humans.txt is not the core contributors of the webcompat.com community, but the core developers of the code which runs webcompat.com. For example, your work would deserve to be on humans.txt.

It's two days in a row in different venues where I see that we have a bit of a confusion in between these two worlds. And indeed it is confusing. Specifically some of us are active in both worlds. I wonder if we need "pet names" for the two things.

* webcompatDEV aka https://github.com/webcompat/webcompat.com/
* webcompat.com aka https://webcompat.com/ 

humans.txt is really about webcompatDEV and indeed as you said the link at the bottom doesn't make sense. 

Do you think that people **coding the site** (including UX, design, etc) should be on the contact page?

**Comment by lockettm** [comment]
@karlcow  Ahh okay. I tend to overlap the two worlds. I think the pet names would be helpful when there's a need for a clear distinction between the two.

>Do you think that people coding the site (including UX, design, etc) should be on the contact page?
 
No, not on the contact page. I think we agree that the Contact link shouldn’t direct to a page with individuals listed. However, I do think that the people actively coding the site should be acknowledged somewhere on wecompat.com.

**Comment by zoepage** [comment]
I guess, the question here is who is the community? 

For me personally, everyone who is helping the web compat project is part of the community. No matter, if this person is taking care of the bugs, helping with the website or "just" spreading the word. 

I'd love to display. not just the "core developers", but all of us as the friendly, helping and caring community that we are and make the evolving community more visible to everyone.

What are your thoughts on this @lockettm?

**Comment by miketaylr** [comment]
http://hood.ie/community/ is a cool page to look at. It links to a contribute page, has core community/alumni and contributors. How that maps onto the realities of our project, I'm not sure yet -- it's just really well done.

We might consider replacing the "contact" link with something like this -- which I think @lockettm is suggesting! 

(also, as @karlcow mentioned, humans.txt is nerd baggage, it could be nixed in favor of something like this)

**Comment by zoepage** [comment]
@miketaylr this is what I was actually going for with the about page. 

I'd love to split the about page up in community and about the project (the why's of it).

**Comment by lockettm** [comment]
@zoepage I agree with your definition of the community.

Yes, my initial thought was that we'd create a team page similar to Hoodie’s **and** either nix humans.txt or replace it with a contact page.

A few years ago @KarlCow mentioned [creating a map](https://groups.google.com/forum/#!searchin/mozilla.compatibility/map%7Csort:relevance/mozilla.compatibility/Tll2EnRxOLA/E1Pt0cZ7dZIJ) of volunteers. I’m not sure how relevant this still is, but I thought it was a good idea to consider.

**Comment by zoepage** [comment]
@lockettm I guess, we are totally on the same page here 👍 
I'd love to have an additional page for contact. Maybe even mix that up with other entry points like here: https://community.rs/resources/

**Comment by lockettm** [comment]
While doing some user testing, I mocked-up a new contact page to get some user feedback.

<img width="1303" alt="screen shot 2017-03-06 at 3 59 04 pm" src="https://cloud.githubusercontent.com/assets/4382193/23635652/e0ecc66e-0285-11e7-8cdc-2d27bc201e9f.png">

When asked to find a way to ask the community a question, users navigated to the Contact page, but had some trouble. Two of the four were unsure about using IRC, and one felt that Twitter was too public. They also seemed to think of the Public Mailing List as a newsletter.

Can we/should we add a contact form? If not, an email to a single point of contact would be helpful.

**Comment by karlcow** [comment]
@lockettm 
Adding a contact form is indeed possible (in the sense of not difficult to do). If we give this possibility I would like to think about what outcomes it will create. Let me try to explain how I see it.

Maximizing the public channels of communications and reducing private feedback is a strategy, not an oversight. 

Once we allow for private feedback, we create also a difficulty. It's easy to reduce a communication from public to private. It's a lot harder the other way around, aka receiving something private and making it public. Private feedback also reduces the sense of the community and incite to more a customer-service relationship. WebCompat is about trying to foster a community work, not everyone reporting issues and a small paid team answering questions.

All of that said, I understand the valid concerns that users said during the test. And there's certainly work to do around the words and the links for these 3 sections:

## Public Mailing-List
Maybe not the right wording. Where the "Join the mailing list" goes?
Currently the mailing list is archived at https://groups.google.com/forum/#!forum/mozilla.compatibility. For example, I wonder about.

> Email Discussions
> Want to discuss a topic related about Web Compatibility? 
> [Send a message](mailto:compatibility@lists.mozilla.org) to our community ([publicly archived](https://groups.google.com/forum/#!forum/mozilla.compatibility)).

## IRC 
Maybe IRC is not the right term and appeal only to geeks. I would probably change that to "Group Chats". 

> Group Chat
> Need to connect with a core person of the project? 
> Join [our core chat](http://chat.mibbit.com/?channel=%23webcompat&server=irc.mozilla.org).


Some people at Mozilla are praising https://discourse.mozilla-community.org/
I'm not a big fan of Web forums, but that could be a possibility. And I think there is a mailing-list mode too for it. We could eventually create a forum there. Though as I said in a previous, the more sources of input, the more we spread thin in terms of resources.

**Comment by zoepage** [comment]
I'd like to suggest e.g. Slack or other as alternative to IRC and a mailing form.
IRC has a higher entry barrier, as seen in @lockettm's research.

A contact form creates:
1. Overhead for people, who can access the request. 
2. Is "closed up" knowledge. So request will repeat themselves at some point. Not everyone can help to answer the request and it might end up unanswered. 
3. Sending a mail per form can feel like diving into something unknown and held people back from asking questions. With an accessible chat they can join and look around, if they feel comfortable with the tone / people around. Then start asking questions.

**Comment by lockettm** [comment]
@karlcow @zoepage Great points about the contact form. I think changing the wording around the current communication channels is a good option.

> Maybe not the right wording. Where the "Join the mailing list" goes?

I linked it to https://lists.mozilla.org/listinfo/compatibility

> Email Discussions
Want to discuss a topic related to Web Compatibility?
Send a message to our community (publicly archived).

Great phrasing. I think 'Email Discussions' would make more sense to users.

> Group Chat
Need to connect with a core person of the project?
Join our core chat.

I like this revision as well. The change of wording and directly linking to Mibbit should make IRC friendlier to newcomers.

@zoepage
I like the idea of eventually having a Slack channel. Although, I agree with @karlcow that it can be a lot of work to manage. I guess the question is whether or not enough members and resources are available to fully support it--so that it feels lively and active.

**Comment by karlcow** [comment]
@zoepage did you try the mibbit link in Join "our core chat".
http://chat.mibbit.com/?channel=%23webcompat&server=irc.mozilla.org
There is no sign-up process. Just choosing a nickname.

I wonder if there are other services like mibbit **without sign-up** providing a web UI to IRC.

**Comment by karlcow** [comment]
* [nope] Grove. nice UI. https://grove.io/blog/groves-awesome-web-client-is-here.html but sign up required.
*  self hosted IRC web client with a nicer UI https://thelounge.github.io/ but requires maintenance. 
* kiwiirc  has a ok UI https://kiwiirc.com/client 
![capture d ecran 2017-03-08 a 09 27 15](https://cloud.githubusercontent.com/assets/505230/23684324/7994ea66-03e1-11e7-9f62-abb110a105d2.png)
