### ISSUE TITLE
on boarding for new contributors (human side)

### ISSUE THREAD

**Issue by zoepage** [webcompat/webcompat.com#1286]
# On Boarding for new contributors
We need to differentiate between three “projects” and different types of contributors.

## Bugs:
1. reporting
2. triage
3. outreach (to sites / browser vendors etc.

## Webcompat.com
1. bug fixing on website
2. improvements on documentation
3. improvements on design

## The Web Compat Project (promotion)
1. organizing events
2. writing blog posts / communication
3. speaking at meetups, conferences

Those three things combined are our community, we want to take care of. 
We need to define which ones we need to "on board" and how.

## Ideas:
(Probably for Bugs(2. + 3.) and webcompat.com (1., 3.))
- 1:1 call
- create transparency for contributors, about workflow
- todos / responsibilities? (Non-blocking things people can grab)
- pair programming / triage sessions

## Communication
As discussed in team week with @miketaylr and @denschub and me in Berlin last week, we might open up our communication channels and create a slack channel (or similar) to make the entry barrier lower and allow new contributors to join easily. (IIRC might be too complicated to new contributors, especially designers, writers etc., mailing lists can create a lot of noise. Not everyone feels comfortable with it. It also blocks "drive-by" contributions.)  

We also want to start a monthly team meeting. We would open up our weekly meeting once a month to everyone. Therefore we need an additional channel, because it might get tricky to invite everyone to the team channel on Vidyo for confidential reasons.

**Comment by zoepage** [comment]
To add more context to the entry points of different contributors and which skill set those contributors will mostly bring in a following list. It will help us to make smarter decisions on e.g. which tools need to be provided by us for the community.

## Issues

### Reporting bug
- non-experienced, experienced developers
- users with a technical background
- designers with a technical background

### Triage
- non-experienced developers (who will need assurance & us to build up their confidence, answer questions etc)
- experienced developers

### Diagnosis
- most likely experienced developers

### Contact
- people with technical background and very good network
- experienced developers
- other browser vendors


## webcompat.com + @webcompat in general
- non-experienced, experienced developers (great entry point for new people)
- designers (with at least small technical background)
- writers / editors (help with documentation, newsletter, social media news spread)

**Comment by denschub** [comment]
Starting on a side note, we should probably pick better internal names for "Issues", "Bugs" and "Webcompat.com Bugs" since we tend to mix them up and create a whole bunch of confusion. How about using "web bugs" when talking about the bugs reported on "webcompat.com" and "webcompat.com bugs" when talking about site-development related stuff?

I pretty much agree with everything else, though. Just felt like a comment to this is appropriate. 👍

**Comment by zoepage** [comment]
this is tackled with #1933
