### ISSUE TITLE
"Report a bug" should link to /issues/new

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat.com#1290]
To fix this, the link in the following template should point to `/issues/new`:

https://github.com/webcompat/webcompat.com/blob/93662e358169e7443445217fe7d2a5c6151c9b21/webcompat/templates/shared/nav.html#L11-L14

**Comment by karlcow** [comment]
Related to what was proposed on https://github.com/webcompat/webcompat.com/issues/317#issuecomment-139146715

**Comment by miketaylr** [comment]
@zoepage would you like to take this?

**Comment by zoepage** [comment]
Sure @miketaylr :)

**Comment by miketaylr** [comment]
Cool, please let me know if anything comes up -- should be a good bug to get your local dev env set up.

**Comment by karlcow** [comment]
@zoepage you can find the manual for setting up environment
https://github.com/webcompat/webcompat.com/blob/master/CONTRIBUTING.md#working-environment-setup

It's also a good way to test the guide. Open a new issue about the contributing guide, if you have blockers and things which are difficult to understand.

**Comment by miketaylr** [comment]
(removing good-first-bug so another contributor doesn't try to steal this from @zoepage)
