### ISSUE TITLE
Upload image on bugform layout busted

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat.com#1292]
This is on master, but not deployed (just noticed on staging....).

Seems like a regression from https://github.com/webcompat/webcompat.com/pull/1265. @karlcow want to fix?

<img width="1920" alt="screen shot 2017-01-18 at 10 24 05 am" src="https://cloud.githubusercontent.com/assets/67283/22072596/746cb996-dd68-11e6-92b5-1599075858a8.png">

**Comment by miketaylr** [comment]
We either need to revert #1265, or block any releases from master until this is fixed. Depending on the scope of https://github.com/webcompat/webcompat.com/issues/1289, we might back out.

**Comment by miketaylr** [comment]
Also looks broken with image preview:

<img width="533" alt="screen shot 2017-01-18 at 11 29 56 am" src="https://cloud.githubusercontent.com/assets/67283/22075381/71a5ce88-dd71-11e6-82eb-060d44215ccd.png">

**Comment by karlcow** [comment]
I will fix. I think I know what is happening.

**Comment by miketaylr** [comment]
Thanks!

**Comment by miketaylr** [comment]
> Depending on the scope of #1289, we might back out.

For now, neither I nor @adamopenweb can repro that bug, so no need to back out urgently. We'll block release on this bug.

**Comment by karlcow** [comment]
I have created a new pull request fixing the issues, and I tested on both sides. So except if my dose of ☕️ was not enough. It should be ok.

I asked @magsout for review, but if someone else wants to give it a go, it's ok with me.

**Comment by karlcow** [comment]
tested in Safari too. And it's working as expected.
