### ISSUE TITLE
Implement Twitter Cards for webcompat.com issues

### ISSUE THREAD

**Issue by karlcow** [webcompat/webcompat.com#1295]
This morning I was seeing this tweet from a contributor to the project ❤️ 

![capture d ecran 2017-01-20 a 10 18 01](https://cloud.githubusercontent.com/assets/505230/22131884/d610d528-def9-11e6-82af-5b100f787251.png)

And I thought that we should probably take advantage of this twitter feature. It is quite easy to implement.

Explanations are at https://dev.twitter.com/cards/overview

And example from https://dev.twitter.com/cards/types/summary

```html
<meta name="twitter:card" content="summary" />
<meta name="twitter:site" content="@flickr" />
<meta name="twitter:title" content="Small Island Developing States Photo Submission" />
<meta name="twitter:description" content="View the album on Flickr." />
<meta name="twitter:image" content="https://farm6.staticflickr.com/5510/14338202952_93595258ff_z.jpg" />
```

There is a validator for it.
https://cards-dev.twitter.com/validator

**Comment by zoepage** [comment]
@karlcow what would be the purpose of the cards?

**Comment by karlcow** [comment]
The card would be unique to each issue. And have a screenshot when it exists and basic description of the issue.

**Comment by miketaylr** [comment]
I like this idea. Makes tweets w/ links to webcompat issues much more compelling.

**Comment by zoepage** [comment]
@karlcow I don't get the flow of it. Sorry.
So basically every issue would be a tweet or whenever someone tweets an issue at webcompat, we'd get it displayed on our site?

**Comment by miketaylr** [comment]
> @karlcow I don't get the flow of it. Sorry.
> So basically every issue would be a tweet or whenever someone tweets an issue at webcompat, we'd get it displayed on our site?

It just means if someone tweets a tweet w/ a link to a `webcompat.com/issues/NNN` in it, it will have an embedded card w/ an image and some context. Currently it's just a link.

**Comment by zoepage** [comment]
Thank you for making that clear @miketaylr 

👍

**Comment by miketaylr** [comment]
I looked into this, I don't think it's currently possible to do this with client-side rendering since Twitter is fetching the meta tags from the html (and doesn't render JS, from what i've read).

**Comment by zoepage** [comment]
😿 

I've removed the refactor label then. Is it ok, if we close the issue and move it to the backlog?

**Comment by zoepage** [comment]
Let's close as this is for backlog anyway...

**Comment by marimeireles** [comment]
I'm adding to my project so I don't forget about it :)
