### ISSUE TITLE
Content for webcompat.com

### ISSUE THREAD

**Issue by zoepage** [webcompat/webcompat.com#1296]
This is a follow up issue for #1285 and provides suggestions for content (changes, additions) for webcompat.com. This content is up for discussion, so please add suggestions below. 

(especially @lockettm and @adamopenweb <3)

--------------
##### Legend: 
(comment)
-> suggestion for change

## index
- report a bug (+ hidden form)
- how it works (how what works? not sure, if this makes sense here)
- Latest Untriaged Issues
- Join the team / the ways of contribute -> what is web compat?
- how to contribute
- search (not clear on what to search. initial thought is website, but is search for issues) -> needs context or different placement
- all issues
- log in
- download add on

## list of issues
- list of issues
- filters for list
- searchbar for issues

## About (main changes / additions will happen here)
- What is web compat? -> needs work and more focus on why we need compatibility, testimonials of (well-known) devs, why its important to report bugs, what is the benefit for everyone on the internet
- community -> who is behind web compat (pic + short bio) + list of all contributors (active + alumni), benefits of you should contribute

## privacy policy
- legal part about policy (which looks good to me) -> we need to add a Code of Conduct section for all channels that are not provided by mozilla (this can also go somewhere else)

## contribute
- link to contributors page
- how you can contribute + explanations as shown on page right now
- link / embed of screencast on triage

## Contact (this all can be moved around and put also somewhere else)
- human.txt -> add resources like in https://community.rs/resources/ including all links to entry points as listet below
  - Code of Contact (explixit one for community, non-mozilla channels)
  - Github link (most important) repos and what it is in one line.
  - social media channels (twitter, GH(?), mailing list)
  - links to release notes (chrome, firefox, safari, edge)
  - links to how to do triage / diagnosis etc and links to screencasts of diagnosis etc
  - blog (either main one or from all of us), newsletter (archive, newest and how to subscribe)
  - tools (add ons for safari / chrome / firefox), link to contribute of webcompat.com
  - irc, slack (or other), mailing lists, basically a "how to stay in contact with the community"
  - wiki links https://wiki.mozilla.org/Compatibility/Guide 
  - events like monthly open team meeting, talk dates, where to meet the team

**Comment by miketaylr** [comment]
> how it works (how what works? not sure, if this makes sense here)

How the site works (was the original intent anyways). It's probably better turned into "how to participate" or something.

> search (not clear on what to search. initial thought is website, but is search for issues) -> needs context or different placement

Maybe change placeholder text to "Search issues by keyword"?

> About (main changes / additions will happen here)

SGTM.

> Contact (this all can be moved around and put also somewhere else)

All LGTM, with one follow up question:

> links to release notes (chrome, firefox, safari, edge)

What does this mean?

**Comment by zoepage** [comment]
> > links to release notes (chrome, firefox, safari, edge)

@miketaylr 
> What does this mean?

Resources would be an entry point for people to get more information. As our community is very diverse, I would love to have also release notes that people can follow up on. (I am sure, people would love to know more about what changed in a browser, but have no idea where to look.)

So the links would point to e.g. https://chromereleases.googleblog.com/ or http://mzl.la/1BAU2a9

**Comment by lockettm** [comment]
Thanks for putting this together! It’ll be very useful in revising and drafting the existing and new sections. Here's a [list of current and unwritten content](https://docs.google.com/a/mozilla.com/spreadsheets/d/1nRvLQ-5iUOnAtDbLWR63Pkglz4fCnAfkUtnzxVXpNpU/edit?usp=sharing).  I'll add suggestions to the list and drafts, feel free to make any edits or additions.

The only thing I would consider adding would be success stories as [mentioned on the mailing list](https://groups.google.com/forum/#!searchin/mozilla.compatibility/success$20stories%7Csort:relevance/mozilla.compatibility/fQjXtxNo2x8/nCWLGcz9LAAJ), which I think is a great idea. 

I like @miketaylr's suggestion of changing the placeholder text to "Search issues by keyword." We might also consider an "All" and "Issues" dropdown filter if we want to include a sitewide search.

**Comment by miketaylr** [comment]
> Resources would be an entry point for people to get more information. As our community is very diverse, I would love to have also release notes that people can follow up on. (I am sure, people would love to know more about what changed in a browser, but have no idea where to look.)

If there are stable links to browsers status pages (like the examples you gave...), I think this is cool. But I don't imagine we'll want to update this page every few weeks for the N browsers that are of interest.

**Comment by zoepage** [comment]
@miketaylr +1

**Comment by karlcow** [comment]
> I like @miketaylr's suggestion of changing the placeholder text to "Search issues by keyword." We might also consider an "All" and "Issues" dropdown filter if we want to include a sitewide search.

We currently use the github search engine for issues to search. We do not have a site wide search installed and I'm not sure I want to err in these territories for so few content. It is another layer of maintenance and/or pile is already high. We could probably grab the results of duckduckgo with a 
`search_term site:webcompat.com -site:webcompat.com/issues`

https://duckduckgo.com/?q=contributors+site%3Awebcompat.com+-site%3Awebcompat.com%2Fissues&t=ffab&ia=web

**Comment by zoepage** [comment]
@karlcow we don't want a site wide search :)

**Comment by karlcow** [comment]
ah confused 😆 it's because you said. 
> We might also consider an "All" and "Issues" dropdown filter if we want to include a sitewide search.

So good good. No site wide search. Perfect. Just issues.

**Comment by lockettm** [comment]
@zoepage said:

> What do you think about the testimonials?

I like the idea of adding expert social proof. Storj.io does something similar near the bottom of their homepage.

**Comment by lockettm** [comment]
As I mentioned to @adamopenweb on IRC, I’m wondering what the tone of voice should be for the new content.

We could go with Mozilla’s [copy tone guidelines](https://www.mozilla.org/en-US/styleguide/communications/copy-tone/)--familiar and conversational.

Any thoughts? If a different direction, I’ll open a separate issue to discuss.

**Comment by karlcow** [comment]
yup not sure what it means exactly, and I guess it depends on the culture. (For example, the usual friend is not a friend in French.) but I guess yes being not too formal still respectful is a good thing. Maybe it would be easier starting with actual content and it will give us a sense of if we are too cold or too familiar. :)

**Comment by zoepage** [comment]
@lockettm I'd love to represent the tone of voice our team and it's spirit.
So mostly friendly, open and helpful, which would mix with the `familiar and conversational` of Mozilla's copy tone guidelines. 

@karlcow 
> yup not sure what it means exactly, and I guess it depends on the culture. 

Of course it depends on the culture, but as we write things in English, this should be our cultural tone, I guess? The tone we set is defining which people we attract :)

**Comment by karlcow** [comment]
I was just reacting to "familiar and conversational". I don't know what it means. Usually I observe @miketaylr in social gathering to have a clue 🤡 ahah. Or maybe it's why I'm lost 👹

**Comment by miketaylr** [comment]
> So mostly friendly, open and helpful

And positive (at least until you get into a room with us...). 

Ignoring the specific term "familiar and conversational", I think the guidelines themselves are great. https://www.mozilla.org/en-US/styleguide/communications/copy-tone/

Be friendly, be sincere. Don't be too clever (e.g., puns are the worse) or needlessly technical. Be a human. I think that's how we interact with people in bugs, FWIW.

**Comment by zoepage** [comment]
Closing as the main part got covered by https://github.com/webcompat/webcompat.com/tree/refactor
