### ISSUE TITLE
Emoji in markdown for specific patterns should be avoided

### ISSUE THREAD

**Issue by karlcow** [webcompat/webcompat.com#1297]
This is happening in https://webcompat.com/issues/4313
When a user is typing a character in a form which is just after `:` without leaving a space. The converter will interpret it as an emoji. Some strings should be out of parsing because there are part of the system. `Expected behavior:` Should not be parsed for emojis.
 

![capture d ecran 2017-01-23 a 11 22 16](https://cloud.githubusercontent.com/assets/505230/22189207/8eda82c8-e15e-11e6-9d6b-c5fd918da02b.png)

**Comment by miketaylr** [comment]
😛

**Comment by zoepage** [comment]
@karlcow it might be enough to add a space after the `:`?
Could be a good quick fix before we redo the form.

(Disabling emoji rendering is tricky. Parsing the message maybe overhead?)

**Comment by miketaylr** [comment]
> @karlcow it might be enough to add a space after the :?

That might work as a quick hack. 

If we do move to a form with multiple textareas for expected/actual behavior (as has been suggested in a few issues), we can also avoid this problem by adding the expected/actual behavior headings to the user input ourselves, once they're submitted to the back-end.

But I agree we probably want some way to tell the emoji lib, don't look at these strings.

**Comment by zoepage** [comment]
This and #1171 could be probably fixed in one solution?

**Comment by cch5ng** [comment]
hi, I'm starting to look at this bug. after #1547 gets merged, the text area placeholder will no longer contain ":". ie it has changed to:

For example,
1. I've tried to log in.
2. I've filled out the form details.
3. I clicked on the submit button.
4. Nothing happened.

does this mean this issue could be closed or should it still be fixed?

**Comment by karlcow** [comment]
Another instance in https://github.com/webcompat/web-bugs/issues/19090
https://webcompat.com/issues/19090

GitHub has the same bug.
<img width="929" alt="capture d ecran 2018-09-26 a 14 19 38" src="https://user-images.githubusercontent.com/505230/46058749-3e0c0e00-c197-11e8-9051-1f5f3908c549.png">
