### ISSUE TITLE
"unknown" problem type not useful

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat.com#1299]
This feels like a bug, we should make users select a problem type even if it's "Something else". Possibly validation is failing here.

**Comment by miketaylr** [comment]
https://webcompat.com/issues/4387 is an example.

**Comment by zoepage** [comment]
@miketaylr 
Would `something else` and an input work?
Might make a need for an additional label visible.

**Comment by miketaylr** [comment]
@zoepage yeah, that's possibly a good idea, but probably worth its own issue. 

In theory "unknown" should not be possible: https://github.com/webcompat/webcompat.com/blob/master/webcompat/static/js/lib/bugform.js#L176

"unknown" is an escape hatch: https://github.com/webcompat/webcompat.com/blob/master/webcompat/form.py#L86-L87

**Comment by miketaylr** [comment]
I'm pretty sure this is fixed by https://github.com/webcompat/webcompat.com/pull/1614. Before the changeset that created a 400 if a form key was missing, this would just be Unknown.
