### ISSUE TITLE
[discussion] How can we track top issues via labels?

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat.com#1300]
Given https://wiki.mozilla.org/Compatibility/CommonIssues, how do we keep an eye on what counts as a top issue. The size of the team is growing and reported issues will to, so it's not practical to expect any one of us to have insight into all the issues being looked at.

Is it possible to create a type of label, for example `problem type: meta viewport` or `meta: DOM exception`?

Labels are cool because it makes it so we can link to them and see how many have been fixed/closed.

https://github.com/servo/servo/labels for inspiration, probably lots of other issues.

**Comment by magsout** [comment]
Oh, I thought Carl knew this information :1st_place_medal: 


In the short term this seems like a good idea. But in the long term, will it be relevant and maintainable to use labels?

**Comment by magsout** [comment]
The danger is to have lot of label, just for one or two issue ?

**Comment by miketaylr** [comment]
> The danger is to have lot of label, just for one or two issue ?

Yeah, it could get messy. Need to think of ways to either hide it from the webcompat.com UI entirely... or something else. Unsure!

**Comment by adamopenweb** [comment]
As mentioned in the meeting today, I'm open to helping clean up the the labels on a regular basis (monthly maybe?).

**Comment by zoepage** [comment]
@miketaylr 
> The size of the team is growing and reported issues will to, so it's not practical to expect any one of us to have insight into all the issues being looked at.

Those labels could help us to track / measure issues, but also share responsibilities with the community in a better way. So e.g. a contributor could look for CSS issues... they'll find them way faster. Not sure if labels like `layout is broken` are already enough to filter those issues.

+1 on hiding in UI. Maybe just make visible when logged in || part of the project || something something?

**Comment by karlcow** [comment]
We do that now.
