### ISSUE TITLE
WebVR labels

### ISSUE THREAD

**Issue by adamopenweb** [webcompat/webcompat.com#1308]
@cvan mentioned [in a bug](https://github.com/webcompat/web-bugs/issues/4528#issuecomment-276464573), that WebVR compat issues will be reported. His suggestion is that we add some labels for WebVR reports.

Let's have a discussion here about what's required and which labels make sense. (Unless this has happened somewhere else already)

**Comment by karlcow** [comment]
@adamopenweb is WebVR contains WebGL stuff? I'm thinking about
https://github.com/webcompat/web-bugs/issues/4490

This ties I guess to @tsl143  issue about  New labels for type of issues categorization #1178, I could see something like

* type-webvr

along

* type-css
* type-clientsniff
* etc.

**Comment by cvan** [comment]
@karlcow: yes, the [WebVR API](https://w3c.github.io/webvr/) relies upon WebGL.

**Comment by karlcow** [comment]
@cvan understood, I was trying to think in terms of WebGL includes WebVR stuff, but WebGL is not always WebVR? Does https://github.com/webcompat/web-bugs/issues/4490 count as WebGL only or as WebVR?

**Comment by miketaylr** [comment]
> (Unless this has happened somewhere else already)

I don't think it has. @cvan reached out to discuss reporting webVR compat issues on webcompat.com, but we haven't had that meeting yet.

**Comment by miketaylr** [comment]
> This ties I guess to @tsl143 issue about New labels for type of issues categorization #1178, I could see something like
> 
>     type-webvr
> 
> along
> 
>     type-css
>     type-clientsniff
>     etc.

@karlcow I like that. We'll make a bit of clutter now before #886 is done, but any objections (anyone..., not just Karl) to us adding that now so @cvan and team can triage and take care of those issues?

**Comment by cvan** [comment]
> @cvan understood, I was trying to think in terms of WebGL includes WebVR stuff, but WebGL is not always WebVR? Does webcompat/web-bugs#4490 count as WebGL only or as WebVR?

That's true. WebVR may (and likely will) come in other forms that are not only tied to WebGL.

**Comment by miketaylr** [comment]
I created a `type-webvr` label: https://github.com/webcompat/web-bugs/labels/type-webvr

@adamopenweb @karlcow if you triage any WebVR related issues, please add that label!
