### ISSUE TITLE
CLI for local server setup

### ISSUE THREAD

**Issue by zoepage** [webcompat/webcompat.com#1310]
After reviewing the setup for webcompat.com, @denschub and I had the idea of improving the [secrets.py](https://github.com/webcompat/webcompat.com/blob/master/config/secrets.py.example). 

Suggestion by @denschub for refactoring the config: 
https://gist.github.com/denschub/439e19b23cd4cc43670f930de6ca400e

Additional idea would be a small CLI, where you actually would need to go through the setup step by step. We could offer 3 upon building setups.
1. basic setup where you can fix issues in the interface -> just oAuth in secrets.py
2. pull issues from test repo and have fun with content -> add repo, secret and app ID
3. in prod -> add all vars

After e.g. adding information for the 1. setup, you could go back at some point and add information for the 2. step. 

Please let me know, if something is not clear.
I'd love to work on this at some point. :)

**Comment by miketaylr** [comment]
I think this is a great idea, current dev environment setup is full of warts.

**Comment by karlcow** [comment]
very good idea @zoepage a step by step guide for configuration will be nice.

One issue you will meet is that `secrets.py` is just a python file and so will be harder to parse and adjust. One possibility for you to allow both manual and programmatic modifications would be to use a config file using something like [ConfigParser ](https://pymotw.com/2/ConfigParser/).

For the CLI, there are also plenty of small packages to create cli or just using argparse. Another issue you will meet along is to identify where we import `secrets.py` variables. This would have to be changed. See http://flask.pocoo.org/docs/0.12/config/#configuring-from-files

I would probably cut this in multiple issues. For example updating the variables import from a config file and the modification into a config file into its own issue. We can do this part. And then it would be a "smaller task" to create the cli interacting with the config file.

I would also hook it into the `python run.py` so people who just run it, find out that they need to configure something more than the current prints we do on the console.

**Comment by karlcow** [comment]
Oh I forgot. :) We can help at any time. Commit code even imperfect and we will help by explaining how to fix it. It's a cool project.

**Comment by zoepage** [comment]
Perfect, thank you! :)

**Comment by zoepage** [comment]
In addition to creating the CLI tool, we'll need to clean up the CONTRIBUTE.md and remove the info that got obsolete.

**Comment by magsout** [comment]
@zoepage very good idea 👍 

I would love to help if you want

**Comment by zoepage** [comment]
The related repo can be found [here](https://github.com/webcompat/webcompat-cli-tool).
It will be released as a npm package and installed with initial `npm install`.

For implementation reasons, it can be added to a branch in webcompat.com. Depending on what makes it easier to switch from `secret.py` to `secret.json`.

@karlcow what do you prefer?

**Comment by karlcow** [comment]
@zoepage Thanks for starting this. 
* What is the **current CLI** is doing (and not doing)? 
* Could you walk us through what is happening for a user without the project on its computer? 

So I can better understand the loosely joined links we need in between the two. I assume a user has the bash prompt in front of his/her eyes. What is happening? :)

**Comment by karlcow** [comment]
from IRC.

> @zoepage: So, in our `secret.py` config file we have `OAUTH_TOKEN = os.environ.get('OAUTH_TOKEN') or 'addTokenHere'`. Would it make sense to move the env var stuff out of the config or shall it stay?

secret.py was created **for this**. Before we had, only one `config.py` with all the config stuff. :)

**Comment by zoepage** [comment]
> secret.py was created for this.

What is this? (So no miscommunication happens.)

**Comment by karlcow** [comment]
@zoepage 

in the `config/` directory.

* secret.py https://github.com/webcompat/webcompat.com/blob/master/config/secrets.py.example
* environment.py https://github.com/webcompat/webcompat.com/blob/master/config/environment.py

Decision was made in #786

**Comment by miketaylr** [comment]
(fwiw, we need the env variable part for travis)

**Comment by zoepage** [comment]
My initial thought was to remove them from the config, but add them in a different layer as it feels like the config should "just" be the holder of the credentials and mainly for the local setup. 

(Maybe I got @miketaylr wrong on the local setup part.)

**Comment by zoepage** [comment]
Follow up on this one:

Mike and I talked about this in our 1:1 and it seems a second layer that would map the values from the config as well as hold the env vars, would be a good solution. This should be in the init.py as far as I remember correctly. :)

**Comment by zoepage** [comment]
The first version is up: https://github.com/webcompat/webcompat-cli-tool/pull/1

*secret.json*
```
{
	"OAUTH_TOKEN": "1234567890123456789012345678901234567890",
	"ISSUES_REPO_URI": "webcompat/webcompat-tests/issues",
	"GITHUB_CLIENT_ID": "87dsajk8dnajk",
	"GITHUB_CLIENT_SECRET": "nhjdajkln432kldbajkhiofa",
	"GITHUB_CALLBACK_URL": "http://localhost:5000/callback",
	"SECRET_KEY": "SECRETS",
	"HOOK_SECRET_KEY": "~*change me*~",
	"UPLOADS_DEFAULT_DEST": "/Users/olagasidlo/Projekte/webcompat/cli-tool/uploads/",
	"UPLOADS_DEFAULT_URL": "",
	"BACKUP_DEFAULT_DEST": "/Users/olagasidlo/Projekte/webcompat/cli-tool/backups/"
}
```

After @miketaylr's review, the next steps would be:

- [ ] map values from secret.json in init.py
- [ ] enhance values with env var options in init.py
   - GITHUB_CLIENT_ID = os.environ.get('FAKE_ID')
   - GITHUB_CLIENT_SECRET = os.environ.get('FAKE_SECRET')
   - OAUTH_TOKEN = os.environ.get('OAUTH_TOKEN')
   - ISSUES_REPO_URI = os.environ.get('ISSUES_REPO_URI')
- [ ] add tests

**Comment by zoepage** [comment]
Update: The PR is done.

@karlcow wanna take a look? Otherwise Mike / I can take over. Thanks!

**Comment by karlcow** [comment]
@zoepage see my questions in https://github.com/webcompat/webcompat.com/issues/1310#issuecomment-319238631

Plus two more questions.

>@karlcow wanna take a look? Otherwise Mike / I can take over.

I can look at it. What do I have to do to test it? Or did you mean something else? It seems unrelated to take over. 

So if I'm not mistaken the initial purpose is to make it easier for people to start the project configuration. That said there are more people with the current configuration, if we were to use this CLI,how do we plan the transition in between the two?

**Comment by zoepage** [comment]
> What is the current CLI is doing (and not doing)?

The current CLI is giving additional information to the config settings and values, how to generate them and which steps you need to take. It also groups the config in 3 steps, which build upon each other.

1. step is to generate your oAuth token. Right now you get information about where and how to generate the token. The user would create it, copy and paste it to the terminal. 
The planed next step is change this step, so the token gets created automatically after inserting your credentials.

2. step is to add the repo, where the bugs can be found. Either you have forked / set up your own bug repo or you use the webcompat test repo (which is the default). You also need to create your app token. This step gives you information where to find it and how to create one. So, you can paste it in the terminal again and all those things get saved.

3. step is automated. it adds paths to the config for `upload` and `backup`, grabs the `process.cwd`and adds it to the value. 

After you've done one step, the config file gets saves as secret.json, so no need to create / copy one by yourself.


> Could you walk us through what is happening for a user without the project on its computer?

This project will be released as a npm package and integrated in the webcompat.com project. So, it would not be stand alone. (Or did I misread your question?)


> What do I have to do to test it?

Our plan was to switch from secret.py to secret.json, so we need to take steps that are explained here https://github.com/webcompat/webcompat.com/issues/1310#issuecomment-322398618

> That said there are more people with the current configuration, if we were to use this CLI,how do we plan the transition in between the two?

Everyone would need to create a new secret file, so run the CLI tool once. We could also write a script to extract the values out of an existing secret.py and write it to the secret.json. But thinking about how many people would probably be affected by this, it seems like overhead. What do you think?

**Comment by karlcow** [comment]
@zoepage thanks a lot for helping me understand a bit more.

It helped me to test and open issues on the project.

> But thinking about how many people would probably be affected by this, it seems like overhead. What do you think?

Probably the opposite to me. :) Let's see if I can explain my train of thoughts. There are more regular users than one time users who want to contribute see https://github.com/webcompat/webcompat-cli-tool/issues/12 We do sometimes break things for users by changing modules, configurations and it's always a bit of a pain. Specifically when you are in the middle of developing a PR in one version and master has moved to another version. I wonder if we can detect the version or have a tag check which says "Oh shoot! We broke everything. We need you to reconfigure things a bit." :/

I'm also trying to think in advance to the time if/when we switch to python3 (another painful moments probably with bigger consequences).

Most of the first bugs often do not require any credentials. For example, https://github.com/webcompat/webcompat.com/issues/1581

For these issues I don't expect people to run the tests, etc. I expect the reviewers to do it. For people participating onto more complicated issues then indeed they will require more stuff.

**Comment by karlcow** [comment]
Ah that was bothering me, I was sure we discussed something like this in the past. 
I found it again #786

@magsout said:

> I don't know if it's me, but each time config.py is updated (and of course I don't see it) I spend many times to understand the errors in my terminal.

and @miketaylr said:

> I have zero opinions on how we do this, except I have broken production because I haven't added some new config variables from config.py.example to my config.py (so of course the app explodes). So whatever we do, it'll be a good thing.

It happened to me too.

**Comment by karlcow** [comment]
@zoepage To remove a bit of the burden of switching and make it easier for everyone. I created a one off script (not the most elegant code)

https://gist.github.com/karlcow/b3f275e020fbfd5e7fd7ce130fb28c61

→ python convert-config.py config/secrets.py config/environment.py


And it spills out:

```json
{
  "GITHUB_CLIENT_SECRET": "123456789", 
  "ISSUES_REPO_URI": "webcompat/webcompat-tests/issues", 
  "UPLOADS_DEFAULT_DEST": "/uploads/", 
  "BACKUP_DEFAULT_DEST": "/backups/", 
  "GITHUB_CALLBACK_URL": "http://localhost:5000/callback", 
  "OAUTH_TOKEN": {
    "oauthkey": "12334456777888"
  }, 
  "SECRET_KEY": "~*change me*~", 
  "GITHUB_CLIENT_ID": "1223445677888", 
  "UPLOADS_DEFAULT_URL": "http://localhost:5000/uploads/", 
  "HOOK_SECRET_KEY": "SECRETS"
}
```

I hope it helps.

**Comment by zoepage** [comment]
@karlcow this is pretty helpful for the migration part. thanks!

**Comment by karlcow** [comment]
@zoepage Discovered this today http://flask.pocoo.org/docs/0.12/api/#flask.Config.from_json

The conversion in my previous comment is to use only one time if we are going the JSON route.
> I created a one off script

So the strategy would be to  as you said:
> Detecting, if a secret.py is there and running the script, deleting the secret.py after writing the secret.json?

I'm adding this issue to the Architecture Austin because there are a couple of things we need to change around config/deployment and that would be a good opportunity to make a better decision for everything.

**Comment by zoepage** [comment]
I'd like to pick this up again as we might have some space this quarter to implement it :)

**Comment by karlcow** [comment]
We will check here what should we do with the CLI? @magsout will check it.

**Comment by karlcow** [comment]
I was checking the setting of the project indico, which has an [initialization script](https://github.com/indico/indico/blob/67490f2b9ecef583a3603b4a53d024c55486f36b/indico/cli/setup.py) that user can run with the command:

`indico setup wizard --dev`

**Comment by karlcow** [comment]
We will close here to check first the possibility and constraint of a new format for config files.  se  #2722
