### ISSUE TITLE
add Greenkeeper support

### ISSUE THREAD

**Issue by zoepage** [webcompat/webcompat.com#1316]
Add Greenkeeper.io support to automate the upgrade of npm packages. As our project is open source, it's free.

**Comment by magsout** [comment]
Yes, good idea. But first I think we need to do this https://github.com/webcompat/webcompat.com/pull/909

Because we have lot of lib not based/depended of, directly included in our project which is not good IHMO.

**Comment by magsout** [comment]
So I think we could delay this after webpack, @zoepage ?

**Comment by zoepage** [comment]
@magsout +1 :)

**Comment by magsout** [comment]
done
