### ISSUE TITLE
CSS/HTML normalisation for forms - Address review comments from PR #1293

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat.com#1320]
This is a followup bug to https://github.com/webcompat/webcompat.com/pull/1293. We want to merge that so we can ship the new design. This bug is to resolve the issues brought up by @magsout.

It seems like the main issue is the changes don't adhere to project conventions.

(feel free to give this a better title, as well).

**Comment by miketaylr** [comment]
Specific comments here: https://github.com/webcompat/webcompat.com/pull/1293#pullrequestreview-18099802

**Comment by magsout** [comment]
I think there are two things about issue:

- improved Form and button Component.
- Improved Grid (flexbox @karlcow )
- Write something about convention: (no selector with two different component and why)

**Comment by zoepage** [comment]
I feel like this is fixed by http://webcompat.github.io/design/
