### ISSUE TITLE
Add CSP report endpoint

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat.com#1329]
A place that accepts a CSP report and logs the input to disk. Blocks #763

**Comment by denschub** [comment]
If you don't want to build this into the application, I've written a small daemon to collect CSP violation reports and dump them into a SQLite database for a project a while ago. Just pushed the sources to [denschub/csp_violation_reports_collector](https://github.com/denschub/csp_violation_reports_collector), feel free to ping me if you need help! (Or, FWIW, feel free to not use it at all.)

**Comment by miketaylr** [comment]
Thank you @denschub!

**Comment by miketaylr** [comment]
I think I'm gonna do the quick and dirty write-to-a-logfile thing in the current app, mostly because it's simpler than figuring out how to host node apps. 🙈 

I think medium-term @denschub's solution is nicer though!
