### ISSUE TITLE
Python 3 Migration

### ISSUE THREAD

**Issue by karlcow** [webcompat/webcompat.com#1332]
* [x] Install python 3 on server
* [x] Upgrade nginx in a separate instance
* [ ] Give guidance for people to switch/install their computer to python 3 #2905 
* [x] Convert the full project to python 3 #2348
* [x] Deploy on staging. Let it mature.
* [x] Move to production server.

Follow-up on #1181

**Comment by AVGP** [comment]
Any way we can help with this?

**Comment by karlcow** [comment]
@AVGP for now, we need @miketaylr to adjust the server install, the two first items on the list. Then we will be able to move forward.

**Comment by karlcow** [comment]
https://pythonclock.org/ As of now, python 2.7 will not be maintained anymore on Jan 1, 2020. So in one year and 9 months. Sounds like a project to be ready.

**Comment by karlcow** [comment]
I plan to work on this on 2018H2

**Comment by karlcow** [comment]
Status on this There is a successful pull request on https://github.com/webcompat/webcompat.com/pull/2825
nosetests are running locally.

**Comment by miketaylr** [comment]
Given that https://github.com/webcompat/webcompat.com/issues/2905 was closed (the only unchecked item), let's close this!
