### ISSUE TITLE
[ui] My Activity

### ISSUE THREAD

**Issue by magsout** [webcompat/webcompat.com#1337]
What do you think  to add a new section in `activity` ?

```
Issues commented by magsout
```

I don't know if it's possible @miketaylr ?

**Comment by karlcow** [comment]
To clarify a bit, for URL like 
https://webcompat.com/activity/karlcow
a list of the latest comment someone has done.

I guess there is something doable with this 
https://developer.github.com/v3/issues/comments/#list-comments-in-a-repository

It seems an interesting idea to be able to follow the activity. 👍 
That said, @magsout could you say what kind of information you would like to see in this section and why it would help you. Just to be sure to understand we extract the good information. 

(PS: this page deserves a redesign to be a real dashboard)

**Comment by magsout** [comment]
For example last day I commented https://webcompat.com/issues/4630. This morning I received an anwser, then I wanted to add the email as a comment.

I searched my issue. I don't know why I clicked on `My Activity` because I participated to this issue. At this moment it was logic to found this issue here.

 Ideas:

- One list (it's more a design issue maybe, because two list are not clear)
- selectbox: reported by me, mentionned me, commented by me
- selectox filter state: close, open

**Comment by karlcow** [comment]
Yeah I can imagine that, I do that through email filtering but it goes to github and then I have to manually edit the URI to go back to webcompat. It would be cool to draft ideas on how we would like this to work.  But it's a good point you made. 

There are probably other issues related to this one. Yeah, found the main one. #442

**Comment by miketaylr** [comment]
I think it should be possible, @magsout.

**Comment by karlcow** [comment]
I put this on the backlog and I'm closing it. 3 years without someone working on it.
Feel free to propose  a PR.
