### ISSUE TITLE
new version of bulb illustration

### ISSUE THREAD

**Issue by zoepage** [webcompat/webcompat.com#1338]
I've made a new (cleaner) version of our bulb (that could also be used as a logo at some point).
What do you think?

![bulb](https://cloud.githubusercontent.com/assets/562354/22792024/9c772fea-eeeb-11e6-9ba1-03e3765bdbbb.png)

**Comment by denschub** [comment]
Uhm, so. If we really want to talk about a new "logo" (do we?), let's do it:

I honestly dislike the fact the wire penetrates through the first section of the socket. Also, I feel like the "thread bars" should be the same width,

Nitpicking aside, I like it. I love that the bug lost its stinger and thus is more friendly. 😆

**Comment by miketaylr** [comment]
The bug does look more friendly!

I dig the minimal feel to it, but agree the wire intersecting the base is a bit jarring.

**Comment by adamopenweb** [comment]
Looks nice! I prefer the darker, filled in look, but just a personal nit. 
> I love that the bug lost its stinger and thus is more friendly.

I agree.

**Comment by karlcow** [comment]
Beautiful work. We are getting there. How many bugs do we need to change a lightbulb?

![](https://s-media-cache-ak0.pinimg.com/736x/71/44/29/714429ed68c364abd40cce976d7fe2f5.jpg)

[Firefly logos](https://www.google.co.jp/search?q=firefly%2Blightbulb&client=firefox-b-ab&source=lnms&tbm=isch&sa=X&ved=0ahUKEwjDoYS6p4TSAhULTrwKHXSXACsQ_AUICCgB&biw=1077&bih=1074#tbm=isch&q=firefly+%22light+bulb%22+logo)  and [lightbulb logos](https://www.google.co.jp/search?q=firefly%2Blightbulb&client=firefox-b-ab&source=lnms&tbm=isch&sa=X&ved=0ahUKEwjDoYS6p4TSAhULTrwKHXSXACsQ_AUICCgB&biw=1077&bih=1074#tbm=isch&q=%22light+bulb%22+logo)

I like it, things to think about before adopting it:

* Let's make sure that [smaller sizes](https://www.smashingmagazine.com/2016/05/easy-steps-to-better-logo-design/#start-with-simple-geometric-shapes) (icons) work well.
* Was it done in simple SVG? If/When you do, make sure to separate the elements so we can play with them.

**Comment by magsout** [comment]
coool @zoepage 

>I honestly dislike the fact the wire penetrates through the first section of the socket.

Yes, I agree.

>Was it done in simple SVG? If/When you do, make sure to separate the elements so we can play with them.

yes, and maybe we can do this: https://github.com/webcompat/webcompat.com/issues/310

**Comment by zoepage** [comment]
I probably should add more description to that issue (@karlcow you were right. again :D )

So, basically the purpose of the cleanup was to get the logo to the level that it works in different sizes and colours. It's not about a whole redesign of the logo.

In 48x48 - 16x16 I'd basically just use the bulb. 

The sketch file provides separated layers that can be exported to SVG and animated. 


With suggested changes:
![all-seeing-eye](https://cloud.githubusercontent.com/assets/562354/22820685/2a4bd122-ef78-11e6-980f-5e2d9ef899cc.png)

**Comment by karlcow** [comment]
@zoepage Could you post the 16px and 48px versions too.

**Comment by zoepage** [comment]
@karlcow Don't have a lot of time today, so I just post the 48x48 version. Hope, that is ok.
![bulb_logo_48x48](https://cloud.githubusercontent.com/assets/562354/22829029/aafdbc0e-efa0-11e6-9b92-4f6e8bf35cc3.png)

**Comment by karlcow** [comment]
Thanks @zoepage 😁  

I guess we might need different versions at lower res. That's the issue often with big images, they don't work well at smaller sizes. There are articles about that from icon designers. It should not be too hard to do.

**Comment by zoepage** [comment]
If everyone is happy with the illustration, I'd like to switch it on the index as the first step.
We could discuss later on, if we want to animate it and how.

Second thing would be to provide the logo files on a resource page. Either update [here](https://github.com/webcompat/design) or add a non linked site to webcompat (we could link later on, if we need to).

What do y'all think about that?

**Comment by miketaylr** [comment]
Sounds good. We need to remember to make all the various sizes favicons as well:

```
  <link rel="shortcut icon" href="/favicon.ico">
  <link rel="apple-touch-icon" sizes="57x57" href="/favicon/apple-touch-icon-57x57.png">
  <link rel="apple-touch-icon" sizes="114x114" href="/favicon/apple-touch-icon-114x114.png">
  <link rel="apple-touch-icon" sizes="72x72" href="/favicon/apple-touch-icon-72x72.png">
  <link rel="apple-touch-icon" sizes="144x144" href="/favicon/apple-touch-icon-144x144.png">
  <link rel="apple-touch-icon" sizes="60x60" href="/favicon/apple-touch-icon-60x60.png">
  <link rel="apple-touch-icon" sizes="120x120" href="/favicon/apple-touch-icon-120x120.png">
  <link rel="apple-touch-icon" sizes="76x76" href="/favicon/apple-touch-icon-76x76.png">
  <link rel="apple-touch-icon" sizes="152x152" href="/favicon/apple-touch-icon-152x152.png">
  <link rel="icon" type="image/png" href="/favicon/favicon-160x160.png" sizes="160x160">
  <link rel="icon" type="image/png" href="/favicon/favicon-96x96.png" sizes="96x96">
  <link rel="icon" type="image/png" href="/favicon/favicon-16x16.png" sizes="16x16">
  <link rel="icon" type="image/png" href="/favicon/favicon-32x32.png" sizes="32x32">
  <link rel="icon" type="image/png" href="/favicon/favicon-196x196.png" sizes="196x196">
```

And then I guess file a bug to eventually update the icons in our add-ons: https://github.com/webcompat/webcompat-reporter-extensions

**Comment by zoepage** [comment]
@miketaylr +1 on various sizes. Everything above 120x120 or 152x152 could even work with the fly. But for contingency we can also stick to just the bulb and add the fly for stickers / animations etc.

**Comment by magsout** [comment]
@zoepage 
>What do y'all think about that?

sounds good for me.

**Comment by magsout** [comment]
For favicons, wen can use http://realfavicongenerator.net/. And removed old useless size.

**Comment by karlcow** [comment]
So in the previous comment I was asking:

> I guess we might need different versions at lower res. That's the issue often with big images, they don't work well at smaller sizes. There are articles about that from icon designers. It should not be too hard to do.

You didn't provide small icons. The 48x48 version is  not working for example. it needs to be adjusted. 

* As for the idea of a new logo. Id say "why not?" (though came a bit as a surprise because nobody complained about the previous one to my knowledge)
* Go ahead by proposing the smaller icons, but before putting them into the project let's first see what it looks like, aka two phases. 1. Designing 2. Implementing in the code. 

I fear we are jumping too fast to the let's put in the code as-is.

**Comment by zoepage** [comment]
This has been added to http://webcompat.github.io/design/ to "Module: Hero Image"
