### ISSUE TITLE
`site: example.com` doesn't work from homepage search

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat.com#1345]
I think these bugs already existed (and may have dupes, need to check), but they're easier to spot now w/ `site: example.com` feature that landed in #999.

STR)
1) open localhost:5000
2) click on search button, type `site: example.com`

Expected:
Taken to /issues with some example.com issues

Actual:
Taken to /issues with no results and the search input says `site%3A+example.com`, while the search param is `q=site%253A%2Bexample.com`.

So we're doing something funky with URL encoding here.

**Comment by miketaylr** [comment]
@MDTsai would you like to investigate this?

**Comment by miketaylr** [comment]
Let's add some tests for this:

https://github.com/webcompat/webcompat.com/blob/master/tests/functional/search-auth.js
https://github.com/webcompat/webcompat.com/blob/master/tests/functional/search-non-auth.js

**Comment by magsout** [comment]
@MDTsai is that ok, if I take this issue ?

**Comment by MDTsai** [comment]
@magsout  sure, please take that

**Comment by magsout** [comment]
Fixed by https://github.com/webcompat/webcompat.com/pull/1518
