### ISSUE TITLE
eslint: change to double quotes for strings in JS

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat.com#1347]
Single quotes in JS feels gross, I think I chose that for consistency with our Python style, but I don't like it anymore.

Unless somebody objects, I'm going to do submit a PR to do this in the next few days.

**Comment by miketaylr** [comment]
Evidence that this is not normal for JS programmers: https://github.com/webcompat/webcompat.com/commit/bd8877ca6742a26e0f23300c0390e7877ec6f928

😄

**Comment by magsout** [comment]
Thanksssss ❤❤❤❤😍😍😍😍

**Comment by magsout** [comment]
Maybe  remove the semicolons ? 😜😘

**Comment by miketaylr** [comment]
> Maybe remove the semicolons ? 😜😘

Blocked

**Comment by magsout** [comment]
![http://data.photofunky.net/output/image/c/2/8/0/c2800d/photofunky.gif]()

**Comment by zoepage** [comment]
So it's a :+1: @miketaylr && @magsout ?

**Comment by magsout** [comment]
Good for me 👍

**Comment by miketaylr** [comment]
Yeah, let me work on this today.

**Comment by zoepage** [comment]
@miketaylr I could totally do this on the plane

**Comment by miketaylr** [comment]
@zoepage be my guest!

**Comment by zoepage** [comment]
Cool, thx!
