### ISSUE TITLE
Add a GET param to pre-populate extra details inside issue description

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat.com#1358]
(See #1356 for discussion of Media team's needs.)

**Comment by miketaylr** [comment]
I suppose `extra_info` works as well as anything else.

**Comment by miketaylr** [comment]
Or maybe `details` is better. 🚲 🏚

**Comment by miketaylr** [comment]
@squelart can you give me a sample string of the additional info you'd like to send, so I can use it in tests?

**Comment by squelart** [comment]
At the moment, I'm producing something like:
"NS_ERROR_DOM_MEDIA_DEMUXER_ERR (0x806e000c) in `virtual RefPtrMP4Demuxer::InitPromise mozilla::MP4Demuxer::Init()` - Incomplete MP4 metadata in 'file:///Users/gerald/Documents/mozilla/media.mp4'"
(Of course you'll need to escape that as needed.)

Now, if this is going into a text field, I will try to make it look tidier, over multiple lines, e.g.:
"""
Encountered error: NS_ERROR_DOM_MEDIA_DEMUXER_ERR (0x806e000c)
Location: `virtual RefPtrMP4Demuxer::InitPromise mozilla::MP4Demuxer::Init()`
Error information: Incomplete MP4 metadata
Media URL: file:///Users/gerald/Documents/mozilla/media.mp4
"""
(🚲 🏚 welcome!)

Is webcompat.com English only, or should I try to use translated strings where possible?

**Comment by miketaylr** [comment]
Thanks! I think the line breaks make it a bit nicer to read, so if it's not much trouble that would be good. Otherwise we can handle that client side.

> Is webcompat.com English only, or should I try to use translated strings where possible?

For now, it's English only, yeah.

**Comment by miketaylr** [comment]
@squelart if you can send `%0A` to indicate a line break then we should be good i.e.,

`details=Encountered error: NS_ERROR_DOM_MEDIA_DEMUXER_ERR (0x806e000c)%0ALocation: virtual%0ARefPtrMP4Demuxer::InitPromise mozilla::MP4Demuxer::Init()%0AError information:%0AIncomplete MP4 metadata%0AMedia URL: file:///Users/gerald/Documents/mozilla/media.mp4`

**Comment by squelart** [comment]
@miketaylr Just to be 100% sure:
The media code will produce newlines:
    "line 1\nline 2"
and forward that to some JS front-end code, which will build the URL with something like:
    `"webcompat.com/...?details=" + encodeURIComponent(details);`
which will produce:
    "webcompat.com/...?details=line%201%0Aline%202"
I.e., newlines will be encoded (to %0A), but also spaces and other special characters.

Does that look correct?

**Comment by miketaylr** [comment]
> Does that look correct?

Yep, looks good!

**Comment by squelart** [comment]
@miketaylr 
Following https://bugzil.la/1343442#c15 , I've tried to use URLSearchParams to construct the URL (which does seem more appropriate for this job), however one difference with encodeURIComponent is that spaces are encoded as '+' instead of '%20'. E.g.:
Before: https://webcompat.com/issues/new?details=Hello%20World
After: https://webcompat.com/issues/new?details=Hello+World

But these pluses are kept inside the "Give more details" box! Is that normal?

Would you be able to decode them as well, or do you think this is wrong and I should keep spaces as '%20' in the URL?

**Comment by miketaylr** [comment]
> Would you be able to decode them as well, or do you think this is wrong and I should keep spaces as '%20' in the URL?

Hmm, let me take a look. I'm not super intimate with the finer details of URL encoding spaces (who is....)

**Comment by squelart** [comment]
Have a read of this: https://url.spec.whatwg.org/#concept-urlencoded
> The application/x-www-form-urlencoded format is in many ways an aberrant monstrosity ...

:-D

**Comment by miketaylr** [comment]
Heh... I think we're pretty safe to just decode the `+` to space clientside, especially since nobody has used the `details` param before, so there are no legacy constraints. I'll file a bug!
