### ISSUE TITLE
Add a GET param to add a label by default

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat.com#1360]
(See #1356 for discussion of Media team's needs.)

It would be nice to be able to apply a `type-video` label on issue creation. Probably want to make sure this only works for pre-existing labels to reduce abuse.

**Comment by squelart** [comment]
@miketaylr Thank you for opening this.

> `type-video` label

Pedantically, some issues may happen with audio-only media as well.
I'm not sure what this label thing is (will it be user-visible?), but I would suggest allowing for different kinds of media, e.g.: `type-audio`.
Also, at the moment the UI notification code doesn't know what kind of media experienced an error, so it would be good to have a vague label too, e.g.: `type-media` or `type-media-playback`.

**Comment by miketaylr** [comment]
That makes sense, thanks @squelart. Labels are user-visible, but mostly they just allow us to organize types of issues. And they will allow your team to filter only for these kinds of issues. 

I prefer `type-media-playback`, but this should be a generic mechanism where you can control what you pass in via your code (we will want to coordinate beforehand though, to make sure the label exists before trying to apply it).

**Comment by miketaylr** [comment]
Maybe we should consider changing the current "Video doesn't play" problem type to something like "Video or Audio problem": https://github.com/webcompat/webcompat.com/blob/master/webcompat/form.py#L34

Thoughts @karlcow?

**Comment by karlcow** [comment]
@miketaylr We can change the form to say what. Separate issue than this one though. 
We have a big work to do on the form anyway.


For the label, I would suggest to do `type-media` then we can decide to extend this taxonomy with more terms. `type-media-audio`, `type-media-video` etc. But I would start simple. 

The Flickr machine tags created by @thisisaaronland was a good flexible system too. We could  probably steal some of its features/spirit… ten years already.
https://www.flickr.com/groups/51035612836@N01/discuss/72157594497877875/

**Comment by miketaylr** [comment]
`type-media` sounds good. My plan is basically the following:

If the GET param already exists, we add it to the issue. 

If it doesn't, we ignore it. 

In theory this could allow label "abuse", but let's start simple and restrict things later if needed.

**Comment by squelart** [comment]
For clarify, what exactly should I put in the URL? `label=type-media`?

**Comment by miketaylr** [comment]
> For clarify, what exactly should I put in the URL? label=type-media?

Yeah!
