### ISSUE TITLE
add new eslint commands in CONTRIBUTE.md

### ISSUE THREAD

**Issue by zoepage** [webcompat/webcompat.com#1363]
https://github.com/webcompat/webcompat.com/pull/1361#discussion_r103009397

**Comment by karlcow** [comment]
Giving more context.

> Can you file a follow up bug: our grunt eslint task should be checking all .js files and currently doesn't (my bad, probably). It looks like what you use for the fix command is more what we want.
> @zoepage ah, if we document eslint anywhere in CONTRIBUTING.md, it might be good to add these commands as alternatives.

which is about documenting these lines of code.
https://github.com/webcompat/webcompat.com/blob/d89b2c488e67dc70bb1d772ef5c318dd36aeae06/package.json#L42-L53

**Comment by zoepage** [comment]
Merged in https://github.com/webcompat/webcompat.com/pull/1366
