### ISSUE TITLE
Functional Test for URL validation is failing

### ISSUE THREAD

**Issue by karlcow** [webcompat/webcompat.com#1368]
As discovered during [another test review](https://github.com/webcompat/webcompat.com/pull/1362#issuecomment-282918681)

```
→ node_modules/.bin/intern-runner config=tests/intern functionalSuites=tests/functional/reporting-non-auth.js 
```

fails with 

```
× firefox on any platform - Reporting (non-auth) - URL validation
CancelError: Timeout reached on firefox on any platform - Reporting (non-auth) - URL validation
  at Timer.listOnTimeout  <timers.js:92:15>
  at Test.registerSuite.URL validation [as test]  <tests/functional/reporting-non-auth.js:79:10>
  at doNTCallback0  <node.js:417:9>
  at Timer.listOnTimeout  <timers.js:92:15>
```

The sup stays in the form and the message never appears.

In https://github.com/webcompat/webcompat.com/blob/6be0811511c70ae9383850056e4f6c2b63e92857/tests/functional/reporting-non-auth.js#L54-L72

```js
    "URL validation": function() {
      return FunctionalHelpers.openPage(this, url("/issues/new"), ".wc-ReportForm-actions-button")
        .findByCssSelector("#url").click()
        .end()
        .execute(function() {
          var elm = document.querySelector("#url");
          WindowHelpers.sendEvent(elm, "input");
        })
        .sleep(500)
        .findByCssSelector(".wc-Form-helpMessage").getVisibleText()
        .then(function(text) {
          assert.include(text, "A valid URL is required", "URL validation message is shown");
        })
        .end()
        .findByCssSelector("#url").type("sup")
        .end()
        .waitForDeletedByCssSelector(".wc-Form-helpMessage")
        .end();
    },

```

The test seems to assert the the message before anything has been entered in the field. Though if you just select the field on the website, there is no message.  On the current form, the "A valid URL is required" message appears only if you have put in a text and removed it. 

If you put "Blahblah" and submit, it is working.
If you put "Blahblah" and goes to another field it doesn't tell it's an invalid URL.

We should probably fix that. This is not really working and the test is failing consistently blocking the rest.

**Comment by miketaylr** [comment]
Hmm...

```
✓ firefox on any platform - Reporting (non-auth) - Submit buttons are disabled
✓ firefox on any platform - Reporting (non-auth) - Wyciwyg bug workaround
✓ firefox on any platform - Reporting (non-auth) - Report button shows via GitHub
✓ firefox on any platform - Reporting (non-auth) - URL validation
✓ firefox on any platform - Reporting (non-auth) - (optional) browser + os validation
✓ firefox on any platform - Reporting (non-auth) - Problem type validation
✓ firefox on any platform - Reporting (non-auth) - Image extension validation
✓ firefox on any platform - Reporting (non-auth) - Submits are enabled
✓ firefox on any platform - Reporting (non-auth) - problem_type param selects problem type

tests/intern
Tunnel: Starting

Total: [✓✓✓✓✓✓✓✓✓] 9/9
Passed: 9  Failed: 0  Skipped: 0

Fx 51 MAC:  [✓✓✓✓✓✓✓✓✓] 9/9
```

We should investigate why this can fail for some, but not for others.

**Comment by miketaylr** [comment]
(going to mark as good next bug, because timing-related Intern failures can be really tricky)

**Comment by karlcow** [comment]
Confirmed for me with Firefox 51.0.1 (64-bit). Your command is not working for me. I need to separate shell. At a point I thought it was my two screens which was creating an issue. but no.

**Comment by karlcow** [comment]
```
→ echo $SHELL
/bin/bash
→ echo $PATH
…/Applications/FirefoxNightly.app/Contents/MacOS…
```
even with this in my path. it is picking up Firefox Prod and not Nightly. Interesting.

**Comment by miketaylr** [comment]
> Your command is not working for me. I need to separate shell. At a point I thought it was my two screens which was creating an issue. but no.

Ah sorry, you're right. That command needs to be split up.

**Comment by cch5ng** [comment]
I can confirm this test failure. I ran the tests a little differently (while trying to narrow down expected test failures):
`python run.py -t` then separately
`node_modules/.bin/intern-runner config=tests/intern functionalSuites=tests/functional-nonauth`

the same test fails for me
https://github.com/webcompat/webcompat.com/issues/1368#issue-210666943

**Comment by miketaylr** [comment]
Thanks for confirming @cch5ng.

**Comment by miketaylr** [comment]
(@karlcow suggested we sit down together and compare machines and figure out why this fails on his and not on mine)

**Comment by brizental** [comment]
Hey @karlcow , does this still happen for you?

**Comment by zoepage** [comment]
@karlcow is this still happening?

**Comment by karlcow** [comment]
Houla… talk about missing a notification. Sorry about that. Thanks @zoepage for pinging again.

🐄  is reading again the full issue. (… 🕐 …)

so…

1. in a bash window, run. On master.   
  * `grunt` 
   * `python run.py -t`
2. Another bash window.  On master
  `node_modules/.bin/intern-runner config=tests/intern functionalSuites=tests/functional/reporting-non-auth.js`


<img width="486" alt="capture d ecran 2018-01-11 a 09 49 57" src="https://user-images.githubusercontent.com/505230/34803114-d454110e-f6b4-11e7-96e1-a73217327787.png">


So like a real normand answer: "maybe yes, maybe no". According to Chrome no issue, According to Firefox, everything fails 😝 

but I guess this is related to a wider issue and given it is working in Chrome and that everything fails in Firefox, I'm inclined to close this. :) Plus the design has slightly change since that bug.
