### ISSUE TITLE
Add comments describing tests in test_form.py

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat.com#1369]
The following 2 tests need comments:

`test_normalize_url` https://github.com/webcompat/webcompat.com/blob/master/tests/test_form.py#L12
`test_domain_name` https://github.com/webcompat/webcompat.com/blob/master/tests/test_form.py#L37

To verify that this is fixed, you shouldn't see the test method names when running the following command, but instead the short comment:

```
🐓 nosetests -v tests/test_form.py

test_domain_name (tests.test_form.TestForm) ... ok
Make sure wrap_metadata and get_metadata methods work. ... ok
test_normalize_url (tests.test_form.TestForm) ... ok

----------------------------------------------------------------------
Ran 3 tests in 0.001s
```

**Comment by jeanhl** [comment]
I would like to claim this issue to fix. I have the environment up and running already.

**Comment by jeanhl** [comment]
I have added the comments to my version. If this is ok, I can start a pull request once approved. 
![screen shot 2017-03-04 at 12 24 39 pm](https://cloud.githubusercontent.com/assets/20343358/23582019/a8d9844e-00d5-11e7-9856-b8f322ecb3a0.png)

**Comment by karlcow** [comment]
@jeanhl please do.
