### ISSUE TITLE
Add comments describing tests in test_uploads.py

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat.com#1370]
To fix this, the following methods need a docstring:

`testBase64ScreenshotUploads`: https://github.com/webcompat/webcompat.com/blob/master/tests/test_uploads.py#L118
`testRegularUploads`: https://github.com/webcompat/webcompat.com/blob/master/tests/test_uploads.py#L82

To know that this is fixed, the output from the following command won't show the test method names, but the docstring:

```
🐓 nosetests -v tests/test_uploads.py
testBase64ScreenshotUploads (tests.test_uploads.TestUploads) ... ok
Test that /upload/ doesn't let you GET. ... ok
testRegularUploads (tests.test_uploads.TestUploads) ... ok

----------------------------------------------------------------------
Ran 3 tests in 0.125s
```

**Comment by sergiorojasa** [comment]
I would like to work on this

**Comment by karlcow** [comment]
@sergiorojasa Thanks. That's cool!

Follow the instructions about the project on [CONTRIBUTING](https://github.com/webcompat/webcompat.com/blob/master/CONTRIBUTING.md)
When your environment is setup, create a pull request with the right syntax and ask for a review for python, you can ask me as a reviewer. 

if you have issue you can drop in the IRC channel. irc.mozilla.org #webcompat channel.
