### ISSUE TITLE
Change Icons for more friendly / professional look on Index page

### ISSUE THREAD

**Issue by zoepage** [webcompat/webcompat.com#1374]
I'd like to change the icons (mainly on the index) to achieve a cleaner look and feel for the user as the "filled" ones feel heavy.

To give a little bit more of context: https://mlockettux.wordpress.com/2017/02/27/documenting-the-initial-iteration/ + https://github.com/webcompat/webcompat.com/issues/1338

Now:
<img width="1162" alt="ways of how to contribute" src="https://cloud.githubusercontent.com/assets/562354/23437574/e05cfe38-fe0e-11e6-86d1-ed903260f4f5.png">

[Report a bug](https://thenounproject.com/search/?q=report&i=883147)
[Diagnose bugs icon](http://thenounproject.com/term/hackathon/6324/) 
[Reach out to sites icon](http://thenounproject.com/term/sport-fan/8283/) 

Idea:
<img width="85" alt="report a bug" src="https://cloud.githubusercontent.com/assets/562354/23437672/320659aa-fe0f-11e6-8393-dca81f0b952d.png">
[Report a bug](https://thenounproject.com/search/?q=report&i=883147)

<img width="70" alt="diagnose a bug" src="https://cloud.githubusercontent.com/assets/562354/23437713/65de8428-fe0f-11e6-9927-33f4fa192c17.png">
 
[Diagnose bugs icon](https://thenounproject.com/search/?q=diagnose&i=518092) 

<img width="70" alt="reach out" src="https://cloud.githubusercontent.com/assets/562354/23437759/962e7a48-fe0f-11e6-8b40-9f775adfabc3.png">

[Reach out to sites icon](https://thenounproject.com/search/?similar=518092&i=518087) 

@lockettm Do you think this could improve to help newcomers quickly find what they need?

**Comment by lockettm** [comment]
@zoepage These look great! I think the suggested "Report a Bug" icon is especially clearer and better represents the task. I like it.

**Comment by karlcow** [comment]
agreed with @lockettm specifically the 1st one.
Diagnose not sure.

**Comment by magsout** [comment]
Interesting.

**Comment by magsout** [comment]
as @lockettm and @karlcow I like the first one.

The third is cool. Love the spirit about share the love.

The second is less clear at first sight. Perhaps the drawing is less clean. We can not see the details. Even if it looks closer, it does the job perfectly

**Comment by zoepage** [comment]
<img src="https://mlockettux.files.wordpress.com/2017/02/roles-test.jpg?w=451&h=308" />

For **community builder** could following be nice:
<img width="80" alt="screen shot 2017-03-01 at 3 54 16 pm" src="https://cloud.githubusercontent.com/assets/562354/23465328/36876b48-fe98-11e6-9c7a-28e10a42f61b.png">
[community builder icon](https://thenounproject.com/search/?similar=518092&i=557872)

**Comment by zoepage** [comment]
@karlcow && @magsout 
Alternatives for the 2nd one:

<img width="86" alt="screen shot 2017-03-01 at 4 01 08 pm" src="https://cloud.githubusercontent.com/assets/562354/23465413/7c80f7ae-fe98-11e6-8f4a-acb1b4d27fc0.png"> 

[Diagnose bug icon](https://thenounproject.com/search/?similar=518092&i=518014)

or 

<img width="75" alt="screen shot 2017-03-01 at 4 11 43 pm" src="https://cloud.githubusercontent.com/assets/562354/23465926/f512dd8a-fe99-11e6-9814-1fa1ab9a17c8.png">

[Diagnose bug icon](https://thenounproject.com/search/?q=diagnose&i=241273)

**Comment by magsout** [comment]
@zoepage 

For me:

Report a bug
<img width="85" alt="report a bug" src="https://cloud.githubusercontent.com/assets/562354/23437672/320659aa-fe0f-11e6-8393-dca81f0b952d.png">

Diagnose bug 
<img width="85" alt="report a bug" src="https://cloud.githubusercontent.com/assets/562354/23466278/eb6a6720-fe9a-11e6-9b3e-d5c311cc3d01.png">

Reach out to sites
<img width="85" alt="report a bug" src="https://cloud.githubusercontent.com/assets/562354/23437759/962e7a48-fe0f-11e6-8b40-9f775adfabc3.png">

**Comment by zoepage** [comment]
It might sound weird, but having two icons with a bug and one without might create an imbalance.
After thinking about it, I'd go with

Report a bug
<img width="85" alt="report a bug" src="https://cloud.githubusercontent.com/assets/562354/23437672/320659aa-fe0f-11e6-8393-dca81f0b952d.png">

Diagnose bug 
<img width="75" alt="screen shot 2017-03-01 at 4 11 43 pm" src="https://cloud.githubusercontent.com/assets/562354/23465926/f512dd8a-fe99-11e6-9814-1fa1ab9a17c8.png">

Reach out to sites
<img width="85" alt="report a bug" src="https://cloud.githubusercontent.com/assets/562354/23437759/962e7a48-fe0f-11e6-8b40-9f775adfabc3.png">

**Comment by lockettm** [comment]
> It might sound weird, but having two icons with a bug and one without might create an imbalance.

That makes sense, I also associate the magnifying glass with search or find.

**Comment by zoepage** [comment]
So, let's make a decision. We could turn that issue into a great "first bug".
If anyone is ok with it, I'd create a new issue and close this one.

**Comment by miketaylr** [comment]
> So, let's make a decision.

Let's discuss in our team meeting on Tuesday, then follow up here. 👍

**Comment by zoepage** [comment]
As discussed in out web compat meeting today, we'll go with following:

`Report a bug`
<img width="85" alt="report a bug" src="https://cloud.githubusercontent.com/assets/562354/23437672/320659aa-fe0f-11e6-8393-dca81f0b952d.png">

and 

`Reach out to sites`
<img width="85" alt="report a bug" src="https://cloud.githubusercontent.com/assets/562354/23437759/962e7a48-fe0f-11e6-8b40-9f775adfabc3.png">

(We can change things still later on, if we realize things don't work as expected.)

We need to decide on an icon for `Diagnose bug`, we'll add a poll below. Please vote for one of the icons with a reaction... e.g. 👍  or ❤️  or 💃  (whatever works for you)

**Comment by zoepage** [comment]
Option 1 for diagnose bug:

<img width="86" alt="screen shot 2017-03-01 at 4 01 08 pm" src="https://cloud.githubusercontent.com/assets/562354/23465413/7c80f7ae-fe98-11e6-8f4a-acb1b4d27fc0.png">

**Comment by zoepage** [comment]
Option 2 for `diagnose bug`:

<img width="75" alt="screen shot 2017-03-01 at 4 11 43 pm" src="https://cloud.githubusercontent.com/assets/562354/23465926/f512dd8a-fe99-11e6-9814-1fa1ab9a17c8.png">

**Comment by zoepage** [comment]
Option 3 for `diagnose bug`:

<img width="100" alt="screen shot 2017-03-01 at 4 18 16 pm" src="https://cloud.githubusercontent.com/assets/562354/23466278/eb6a6720-fe9a-11e6-9b3e-d5c311cc3d01.png">

**Comment by zoepage** [comment]
AAAAND we have a winner!!! 
https://github.com/webcompat/webcompat.com/issues/1374#issuecomment-284751519

**Comment by zoepage** [comment]
Closed due to follow up issue in https://github.com/webcompat/webcompat.com/issues/1402
