### ISSUE TITLE
Misleading icon for Github view

### ISSUE THREAD

**Issue by ioana-chiorean** [webcompat/webcompat.com#1375]
Steps:
1. Go to the bottom1 of an issues' page on webcompat. (ex: https://webcompat.com/issues/4877) 
2. Tap the G icon from "G takes you to the Github view of the page. "

Expected results:
- I would expected to be taken to the github view - as taping the link behind the text github view

Actual results:
- the G doesn't do anything. Only the link behind the Github View text forwards you to that. 

![photo_2017-03-02_12-14-21](https://cloud.githubusercontent.com/assets/1391451/23502952/60df7e30-ff42-11e6-8a43-5c5df0c9892a.jpg)

**Comment by magsout** [comment]
There is no link around the G icon. 

Why do you consider that you can tap on G?

The icon is just there to symbolize the keyboard key.

**Comment by miketaylr** [comment]
We could easily just making the G a link as well though (with or without an underline).

**Comment by ioana-chiorean** [comment]
> Why do you consider that you can tap on G?
Because it looks like a button? At least for me. 

> The icon is just there to symbolize the keyboard key.
Well, on mobile ( as in mindset and workaround) there is not keyboard key there. Sorry, I honestly did not consider that at all. 

> We could easily just make the G a link as well though (with or without an underline).
Indeed. I can do this if this will be the final decision.

I do not have a strong feeling about this. I missed the keyboard thing (which works on desktop btw) so It might just be me and my weird ux.

**Comment by magsout** [comment]
@ioana-chiorean sorry, my question was maybe a little direct? 

I just went to know why.

 Your point of view is interesting.

I don't see/understand the behavior of the Button because I added it. 

So, thank you for your feedback. It's a good idea to add a link around the Icon. IMHO

**Comment by ioana-chiorean** [comment]
> @ioana-chiorean sorry, my question was maybe a little direct?
> I just went to know why.

No worries, but I honestly though it is a button :| I work a lot from mobile nowdays so I am definitely bias there. 

>So, thank you for your feedback. It's a good idea to add a link around the Icon. IMHO

I will patch it later a bit.

**Comment by karlcow** [comment]
Great feedback @ioana-chiorean 

* On Mobile indeed this doesn't make sense. It says "G" (this) takes you (action) to the Github View (there). But there is no keyboard on mobile. so the G is indeed doing nothing.
* On desktop, it's not completely clear either. :) It is clear for us because we know it, but I'm pretty sure a website newbie will not get it in addition to the duplication of the link in `[Github View]`. And if you are not a newbie you know the key. Even with non-newbie like @ioana-chiorean 

What would be the metaphor which would work for both. Ultimately the "G" keys is an asset which should not be explained. We added the sentence for discovery, which is usually a sign of bad UI/UX aka explain what the site needs to do. 

Just an idea. ping @lockettm 

`[Github View]` being a link and when someone does a hover on the link, there is a message which says: "You can use the `g` key as a shortcut". That way on mobile no confusion and on desktop people can discover the shortcut. 

Or any better idea… 🤡

**Comment by heatherbooker** [comment]
Throwing in my unsolicited two cents as an outsider - when I read ioana-chiorean's first message, I thought 
> "How silly, a button that doesn't have a link! Also, why isn't it an octocat?"

So I definitely agree it is confusing for newbies >< But an awesome feature once I know about it! As a sidenote, I was also confused by it being a capital 'G' - I tried using shift + g to use the shortcut, but it turned out I needed to just press g.

I agree with karlcow's suggestion of having a tooltip - I'd be happy to do a fix with any/all of the following (I know @ioana-chiorean offered but as an official contributor I am guessing there might be bigger fish to fry ;) ), otherwise just throwing them in as (a summary of) ideas:

1. Use media queries to have completely different views
--> ex. mobile: simple github icon button + "View on github" linked text
2. Make the G a link
3. Make the G lowercase
4. Change the wording to something like "Press (the) G (key (on your keyboard)) to be taken to the Github view of this page" (keeping the G being a key icon)
5. Add tooltips on hover of G and [Github View] link explaining use of G key shortcut

**Comment by zoepage** [comment]
@heatherbooker 
> < But an awesome feature once I know about it! As a sidenote, I was also confused by it being a capital 'G' - I tried using shift + g to use the shortcut, but it turned out I needed to just press g.

Happened to me too.


@karlcow 
> [Github View] being a link and when someone does a hover on the link, there is a message which says: "You can use the g key as a shortcut". That way on mobile no confusion and on desktop people can discover the shortcut.

I feel like, this would add even more confusion. I'd learn the behavior is to click the button, so the `press G` feature would get obsolete at some point.


@heatherbooker 
> 1. Use media queries to have completely different views
--> ex. mobile: simple github icon button + "View on github" linked text
> 2. Make the G a link

Had the same idea to create two different views for this feature. I love to change the `G`into octocat plus link the button. And on mobile to hide the text next to it.

**Comment by karlcow** [comment]
@zoepage 

> I feel like, this would add even more confusion. I'd learn the behavior is to click the button, so the press G feature would get obsolete at some point.

to make extra-sure that I was understood. I'm talking about just having github view as a sentence.

![capture d ecran 2017-03-03 a 19 52 47](https://cloud.githubusercontent.com/assets/505230/23548477/0b56d620-004b-11e7-8c3b-77d0c2e8b890.png)

**Comment by zoepage** [comment]
@karlcow 
Behavior wise, you have to hover for +1.2 sec over a button to get a tooltip. Mostly too long for people to see the info and the knowledge about the feature "gets lost". 
This is why I am not a big fan of tooltips.

+1 on "github view" label like button.

**Comment by karlcow** [comment]
You mean 1.2s when using the "title" attribute? It doesn't have to be a title attribute.  I just mocked it up quickly for making clear what I'm talking about. The goal is that once people learned that there is a g shortcut, they will not ever use the button anymore. Plus with a button github view we do not have to put it down there hanging nowhere. Ultimately it should  be on the top.

For the octocat icon, I like the idea, but I fear it speaks to only geeks. Maybe it's ok. I don't know. Given that anyway the github view is not the one I would recommend to anyone. :)

**Comment by zoepage** [comment]
@karlcow 
> The goal is that once people learned that there is a g shortcut, they will not ever use the button anymore. 

Agree, but I fear they won't be able to learn it, because its harder to get the info.

> For the octocat icon, I like the idea, but I fear it speaks to only geeks. 

I actually feel the other way around. Seems to add a human side to it. But that's probably just me.

**Comment by miketaylr** [comment]
I feel like we're totally overthinking this. This is a "good first bug", so let's keep it simple. If someone wants to get fancier, let's fix the simple bug then file a follow up.

@heatherbooker I think your suggestions in 
https://github.com/webcompat/webcompat.com/issues/1375#issuecomment-283883226 are good. Want to work on this?

(@ioana-chiorean, is that OK with you?)

**Comment by heatherbooker** [comment]
I can do that later today yup!

**Comment by ioana-chiorean** [comment]
> @ioana-chiorean, is that OK with you?

Si senor. 

> to make extra-sure that I was understood. I'm talking about just having github view as a sentence.

@karlcow - i liked your proposal too . 
@heatherbooker  - go for it! 

Thank you all!

**Comment by heatherbooker** [comment]
Proposed changes:

Desktop (width > 40em):

![screenshot](https://puu.sh/uxTCO/0884727351.png)

Mobile (max-width: 40em):

![screenshot](https://puu.sh/uxTPB/dfe059bd25.png)

The octocat, "View on Github", and 'g' are all clickable links. What do y'all think? (_note_: I don't want to tag & therefore spam everyone about this...should I tag everyone involved in a conversation like this?)

**Comment by zoepage** [comment]
> I don't want to tag & therefore spam everyone about this...should I tag everyone involved in a conversation like this?

No, no worries :) Everyone involved in this conversation will be notified anyway. So, the best thing is to just mention someone, if you need their direct attention. :)

+1 on Github Icon. 
Not sure about the g (link + background). Still feels like a button. But probably just me. :)

**Comment by heatherbooker** [comment]
Rad, thanks. 

I definitely agree it still feels like a button. I mean, it _is_ a button, but that's only to mitigate the confusion from it looking like a button...hah. I like what I assume was the original idea of making the g look like a key, and I'm not sure how to implement it without making it look also like a button. Maybe just ditch that idea and do something like `Shortcut: Press 'g' on your keyboard to be taken to the Github view of this page.` ?

**Comment by zoepage** [comment]
> Maybe just ditch that idea and do something like Shortcut: Press 'g' on your keyboard to be taken to the Github view of this page. ?

+1 :)

**Comment by heatherbooker** [comment]
Sure @zoepage !

I've got two PRs for this issue, one with an octocat that changes color #1408 and one that doesnt #1407 .

**Comment by zoepage** [comment]
wow, @heatherbooker! you're killing it!  Thank you :)

If I had to choose, I'd go with #1407. The contrast of the hover color on the grey background feels tricky. Also in both the link is not really readable anymore on hover. :/ 

Maybe adding another class like `wc-GithubLink` to https://github.com/heatherbooker/webcompat.com/blob/githubLink/webcompat/templates/issue.html#L19 `wc-Link` and remove the hover color?

Also, could you please remove the span from the `g` https://github.com/heatherbooker/webcompat.com/blob/githubLink/webcompat/templates/issue.html#L19? And just make it bold?

Thank you <3

**Comment by heatherbooker** [comment]
@zoepage gotcha, you're very right it becomes hard to see. I removed the change color on hover and the span from the g (and accompanying keyhint class).
