### ISSUE TITLE
Missing description in package.json

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat.com#1376]
If you do `npm install`, you will see the following:

`npm WARN webcompat@ No description`

To fix this, we need to add something short and sweet to package.json:

https://github.com/webcompat/webcompat.com/blob/master/package.json

See also https://docs.npmjs.com/files/package.json#description-1

**Comment by magsout** [comment]
@miketaylr something like ?

```
Webcompat.com is a gathering place for the web compatibility community. 
````

**Comment by zoepage** [comment]
As this is a description `as it's listed in npm search`, how about
`WebCompat.com is a tool to gather web compatibility bugs, inform the community and help to fix the web.` ?

**Comment by miketaylr** [comment]
LGTM.

**Comment by nj4710** [comment]
I'd like to work on this.

**Comment by zoepage** [comment]
@nj4710 Enjoy!

If you have any questions, let us know! :)

**Comment by zoepage** [comment]
@nj4710 That was quick! Thank you :)

Could you change `WebCompat.com is a tool to gather web compatibility bugs, inform the community and help to fix the web` to `The webcompat.com is a tool to gather web compatibility bugs, inform the community and help to fix the web.`?

(Sorry, didn't check the spelling before. My fault.)

If you are done, could you send a PR against master please? 
Thank you!

**Comment by nj4710** [comment]
@zoepage I have changed the message and sent a PR
