### ISSUE TITLE
Document running grunt (or npm run build) before running functional tests for the first time

### ISSUE THREAD

**Issue by jeanhl** [webcompat/webcompat.com#1377]
**Issue:**
I've been getting familiar with the webcompat codebase and noticed that the css would not appear when I'm running localhost. Mike told me to run grunt to get it to appear. 

**Fix:**
Basic: Documentation needs to be amended to reflect that "grunt" has to be executed in the root directory of webcompat.com
Detailed: Install gruntjs by running "sudo npm install -g grunt-cli" (on Mac) before running grunt. Reference: https://gruntjs.com/using-the-cli

**Comment by miketaylr** [comment]
Thanks @jeanhl!

For context, this came up after @jeanhl was running Intern tests:

https://github.com/webcompat/webcompat.com/blob/master/CONTRIBUTING.md#running-tests

We cover this in https://github.com/webcompat/webcompat.com/blob/master/CONTRIBUTING.md#working-environment-setup (at some point), but if you jump straight to the tests you'll miss that.

We could add a link back or a sentence saying, make sure you've set up your dev environment and run the build process so CSS is built.
