### ISSUE TITLE
Failing functional test (nonauth): "History navigation - Back button works from issues page"

### ISSUE THREAD

**Issue by cch5ng** [webcompat/webcompat.com#1383]
Ran nonauth functional tests locally
`python run.py -t`
`node_modules/.bin/intern-runner config=tests/intern functionalSuites=tests/functional-nonauth`

This was one of the resulting test failures:
```
× firefox on any platform - History navigation - Back button works from issues page
AssertionError: expected 'http://localhost:5000/issues?page=1&per_page=50&state=open&stage=all&sort=created&direction=desc' to not include '/issues'
  at Command.<anonymous>  <tests/functional/history-navigation-non-auth.js:38:18>
  at Test.Back button works from issues page [as test]  <tests/functional/history-navigation-non-auth.js:37:10>
```

**Comment by cch5ng** [comment]
hi, @miketaylr this seemed it could be a timing issue. I restarted my router and re ran the test (there may have been a new app on my computer also causing performance slow down). it is passing. sorry about that!

**Comment by zoepage** [comment]
> could be a timing issue
Interesting. That would explain a few things. Thanks @cch5ng for that pointer :)

**Comment by miketaylr** [comment]
> this seemed it could be a timing issue.

Yeah, I suspect this is the case -- thanks for opening the bug though! Hopefully we can make the tests less flaky depending on hardware/distance-from-GitHub servers, etc.
