### ISSUE TITLE
Unable to log issues from the webcompat website, on Samsung Galaxy S6 device

### ISSUE THREAD

**Issue by softvision-sergiulogigan** [webcompat/webcompat.com#1390]
*Environment*:
Samsung Galaxy S6 (Android 6.0.1)
Application version: Firefox 51.0.3

*Prerequisites*:
1. Fresh install the Firefox app.
2. Install the Webcompat add-on, from www.webcompat.com.

*Steps to reproduce*:
1. Launch the Firefox app.
2. Open any website.
3. Tap the More-Report Site Issue button.
4. Select any options from the "What seems to be the trouble?" section.
5. Tap the "Attach a screenshot image" placeholder.
6. Select a photo.
7. Tap the "Report via GitHub" button.
8. Tap the Back button.
9. Tap the "Report via GitHub" button.
10. Tap the Back button.

*Expected results*:
For Step 7&9: The GitHub page is displayed. The issue is logged.
For Step 10: The www.webcompat.com page is displayed, and the details of the issue can be edited.

*Actual results*:
For Step 7&9: A webpage is displayed, with the message: "Access to the file was denied".
For Step 10: The www.webcompat.com page is displayed, but the details of the issue can not be edited.

*Notes*:
1. Reproducible: 5/5.
2. Screenshot attached (https://goo.gl/zvIfKk).
3. After Step 10, long-tapping on the screen, resets the view to the top.
4. The issue is NOT reproducible under the following environment: Samsung Note 4 (Android 5.0.1), Nexus 5 (Android 6.0.1), Honor 8 (Android 6.0), LG G4 (Android 5.1)

**Comment by miketaylr** [comment]
Interesting, thanks @softvision-sergiulogigan. I imagine this has to do with how Samsung's OS hands off images from their photo app back to JS. 

@softvision-sergiulogigan note: if you want to file test reports, you can use our staging server: https://s:s@staging.webcompat.com (that way they don't end up in the main repo).

**Comment by miketaylr** [comment]
> Screenshot attached (https://goo.gl/zvIfKk).

Once you select an image, you shouldn't see a cloud icon anymore -- it should show a local preview. So this is the first area to investigate. I've got a Samsung Galaxy S6 I can check in the next day or so.

**Comment by softvision-sergiulogigan** [comment]
Hi Mike,
Sorry for the poor quality video, but I tried to keep the size under 10 MB.

**Comment by miketaylr** [comment]
karl suggests looking into file size. also, there was a connection broken error message from flask when images were too big.

**Comment by softvision-sergiulogigan** [comment]
When I first discovered the issue, I tried uploading a screenshot of a web page, taken with the Samsung Galaxy S6 itself.

**Comment by karlcow** [comment]
@softvision-sergiulogigan do you still have the issue? with current version of Firefox and webcompat.com

**Comment by softvision-oana-arbuzov** [comment]
I've tested the issue and below are my results:
- manually attaching a screenshots is not working (tested on Samsung S6, Huawei P10);
- automatically attaching a screenshot is not working on Samsung S6 but it's working on Huawei P10 (using the Webcompat addon);
- after being signed into Github and reporting the issue using "Report as <Github user>" button, the issue is not logged (tested on Samsung S6, Huawei P10, on staging server);
- reporting the issue using "Report Anonymously" button, the issue is logged (tested on Samsung S6, Huawei P10, on staging server);
- performing the described scenario, I did not received "Access to the file was denied" error and still manage to edit the details of the issue.

**Tested with:**
Browser / Version: Firefox Mobile Nightly 57.0a1 (2017-08-30)
Operating System: 
Samsung Galaxy S6 (Android 7.0) - Resolution 1440 x 2560 pixels (~577 ppi pixel density)
Huawei P10 (Android 7.0) - Resolution 1080 x 1920 pixels (~432 ppi pixel density)

**Comment by karlcow** [comment]
@softvision-oana-arbuzov When you say

> manually attaching a screenshots is not working

Do you mean that the image is not in the final report or that the image is not being seen as a thumbnail once chosen?

**Comment by softvision-oana-arbuzov** [comment]
@karlcow  It means that I tap the "Upload screenshot" button and choose an image from the mobile device/desktop.

**Comment by miketaylr** [comment]
@softvision-sergiulogigan do you still have access to a Samsung Galaxy phone to test if this still reproduces?

**Comment by softvision-sergiulogigan** [comment]
@softvision-oana-arbuzov has the device.

However, I did test it on a Samsung Galaxy S8 (Android 9) - 1440 x 2960 pixels, 18.5:9 ratio (~570 ppi density) but could not reproduce the issue.

Let's wait and see if Oana can reproduce it or not, using the new version of webcompat.com

**Comment by softvision-oana-arbuzov** [comment]
@miketaylr I still reproduce the issue on Samsung Galaxy S6 Edge (Android 7.0) - 1440 x 2560 pixels (~577 ppi pixel density). The screenshot is not uploaded if Firefox Preview Nightly cache/data is cleared first.
![FirstTryBroken](https://user-images.githubusercontent.com/12184325/78995085-442fc880-7b4a-11ea-96e1-2187b8133bb9.gif)

Note: Trying again to upload a screenshot does not work, but dismissing the bug report and trying again upload works.

**Tested with:**
Browser / Version: Firefox Preview Nightly 200405 (🦎 76.0a1-20200403063228)

**Comment by miketaylr** [comment]
So weird, thanks for testing again.

**Comment by softvision-sergiulogigan** [comment]
Since neither Oana or me can reproduce this one, I'm closing it as Invalid (due to the layout change)
