### ISSUE TITLE
redirect for /activity page

### ISSUE THREAD

**Issue by zoepage** [webcompat/webcompat.com#1391]
When you are logged in, you can see your activity e.g. https://webcompat.com/activity/zoepage

https://webcompat.com/activity/ is a 404. It should point to either https://webcompat.com/activity/USERNAME when logged in or https://webcompat.com/ when logged out.

**Comment by karlcow** [comment]
Let's hold on the discussion on this. Why? In short: URIs are identifier toward a meaning. 
And so I'm in favor of closing this without implementing it. But I want to explain further in a longer prose.

**Comment by zoepage** [comment]
For me, this is a bug. This is why I'd like to keep this open.
But yeah, let's discuss it then.

**Comment by miketaylr** [comment]
> But yeah, let's discuss it then.

Let's chat more in Berlin over Club Mate.

**Comment by karlcow** [comment]
`/activity` A proposal made during the meeting was to use it for webcompat stats/progress. aka the activity of the site. Hopefully I can better communicate my love for HTTP in Berlin. My elevator pitch often relates to HTTP is a tool for managing UX. 

* [HTTP — an Application-Level Protocol](https://dev.opera.com/articles/http-basic-introduction/)
* [HTTP: Let’s GET It On!](https://dev.opera.com/articles/http-lets-get-it-on/)
* [HTTP: Response Codes](https://dev.opera.com/articles/http-response-codes/)
* [WebArch](https://www.w3.org/TR/webarch/)
* [Design Issues](https://www.w3.org/DesignIssues/)

**Comment by karlcow** [comment]
Thanks.
