### ISSUE TITLE
Twitter account link should include replies

### ISSUE THREAD

**Issue by karlcow** [webcompat/webcompat.com#1398]
This is a followup issue on "change twitter link in footer" #1372

In  her blog post @lockettm mentioned the comment of a UX test participant:

> “Last post was 6:35 am Jan 30—so no, I would say they would not respond quickly. And then I’d have to take my chances with email—I would probably not even try to ask them on Twitter.”

We fixed it with #1372 That's cool it was an improvement. I guess we can improve this a bit more, by using https://twitter.com/webcompat/with_replies

Here the screenshots. Left with replies, and right without replies (aka the current one)

![capture d ecran 2017-03-07 a 08 17 34](https://cloud.githubusercontent.com/assets/505230/23634733/38be0fa4-030f-11e7-8ca8-1d5c01ead6cb.png)

**Comment by karlcow** [comment]
@lockettm feel free to chime in.

**Comment by lockettm** [comment]
That's interesting. I agree, linking to /with_replies would make the account seem even more active.

**Comment by magsout** [comment]
@karlcow oh yes, its relevant
