### ISSUE TITLE
 Replace Twitter text link with icon + add GH icon

### ISSUE THREAD

**Issue by zoepage** [webcompat/webcompat.com#1401]
We'd like to change the twitter link into the twitter logo icon and add a github logo icon link to the footer.

You can find a more detailed explanation here as well as the discussion: https://github.com/webcompat/webcompat.com/issues/1282#issue-200693908.

Template: https://github.com/webcompat/webcompat.com/blob/master/webcompat/templates/shared/footer.html

- [ ] add twitter icon SVG to footer http://www.flaticon.com/free-icon/twitter-logo-silhouette_8800
- [ ] link twitter icon to https://twitter.com/webcompat/with_replies
- [ ] add github icon SVG to footer https://octicons.github.com/icon/octoface/
- [ ] link github icon to https://github.com/webcompat/webcompat.com/

If you have any questions, please let us know! <3

**Comment by nj4710** [comment]
I would like to work on this issue

**Comment by zoepage** [comment]
@nj4710 enjoy :)

LMK, if you have any questions!

**Comment by nj4710** [comment]
![icons](https://cloud.githubusercontent.com/assets/13145287/23716576/b9227de0-0456-11e7-98df-eeb10ee5a4ca.jpg)

Hey! How does this look? @zoepage . Should I add text with the icons too? and also should we change the opacity or color on hover?

**Comment by zoepage** [comment]
@nj4710 Looks great! :)
Could you add more spacing between the icons, so no one clicks on the other one by accident?

Otherwise, I guess we're good! :+1: 
(We can always improve it later, when we see it doesn't work as we expect it to)

**Comment by karlcow** [comment]
@nj4710 +1 for @zoepage spacing. Would be good to test on small screens (mobile), because I suspect it will be near the screen edge and big fingers need to be able to touch without issues.

**Comment by zoepage** [comment]
@karlcow thank you for mentioning that. wanted to mention it, but forgot while writing. (should probably go to 🛌 )

**Comment by nj4710** [comment]
Hi, This is how the icons look in small screens( I used max-width:28em)
![small](https://cloud.githubusercontent.com/assets/13145287/23746657/b76886ca-04e2-11e7-99f4-6c79fc650de3.jpg)

and this is how they look in normal screens
![big](https://cloud.githubusercontent.com/assets/13145287/23746686/cfd7ffec-04e2-11e7-8387-c88b1ee401e8.jpg)
Does this look alright??

**Comment by zoepage** [comment]
Not really. Could you please send a PR, so we can discuss it in there? 
Thank you.

**Comment by nj4710** [comment]
Sent PR :)
