### ISSUE TITLE
add event page to "join us" in about

### ISSUE THREAD

**Issue by zoepage** [webcompat/webcompat.com#1403]
<img src ="https://cloud.githubusercontent.com/assets/4382193/23636977/b9222cac-028d-11e7-9465-7aee2090c733.png" /> Our about section on webcompat.com will be updated soon. 
(more context: https://github.com/webcompat/webcompat.com/issues/1149#issuecomment-284589695)

As many of us speak at conferences, travel and go to events / meetups / user groups etc, it would feel great to have an event section added as under-topic of "join us".

We could start of with a static page as a start, but hook it to a open calendar or excel sheet (how hoodie did it), to keep it updated. 

So the community would get the opportunity to meet up and get to know each other, exchange knowledge / contacts or even organize events by themselves. 

What do you think?
<3

**Comment by karlcow** [comment]
@zoepage This looks like a good idea.

Maybe as a start, we should probably list the events we attended/spoke to in 2016 to better understand the "[shape of our content](http://www.hup.harvard.edu/catalog.php?isbn=9780674805705&content=reviews)" 

Then we can see if it's worth doing and if we were doing that how we should maintain it in an easy way without relying too much on third party services (breakage, maintenance, owning your content, etc.). 

Now travel to the memory lane. @miketaylr @ioana-chiorean @haseebgit @zoepage are people who spoke at events in 2016 from the top of my head? I'll make a separate comment that anyone can edit for the list of talk.

**Comment by karlcow** [comment]
Edit this comment with your talk or leave a comment and I'll add it here.

* 2016-10-16 Jakarta, Indonesia, Tech-in-Asia, [A tale of two Webs](http://www.otsukare.info/2016/11/23/webcompat-techinasia)
* 2016-10-17 Jakarta, Indonesia, Moz Community Space. The Rusty Web. (but not related to webcompat so probably out of scope.)

**Comment by karlcow** [comment]
as a source of information we also have [planet.webcompat.com](https://planet.webcompat.com/)

**Comment by zoepage** [comment]
@karlcow to add past events is a pretty good idea. 
I spoke a lot last year, but mainly about offline first. So probably also out of scope. ;)

So, its a +1 from you on the event page and to include it as sub topic of 'join us', if I am getting this right? :)

We already have dates for 2017 set up and should add them too, I guess?

**Comment by karlcow** [comment]
misunderstanding: I did not suggest to add past events. I said to be able to understand the proposal we need to better understand the data. And so I'm asking people to share where they speak so we can see what we should do or not.

**Comment by karlcow** [comment]
> So, its a +1 from you on the event page and to include it as sub topic of 'join us', if I am getting this right? :)

no. Not yet. :) (to make extra clear)

**Comment by zoepage** [comment]
@karlcow ah! ok. :)

my talks 2017/2016/2015 (I am sure, I forgot 1 or 2)
- FrontTrends , Warschau (2017)
- WeAreDevelopers, Vienna (2017)
- Codemotion Amsterdam, Amsterdam (2017)
- Voxxeddays, Zurich (2017)
- GOTOBerlin, Berlin (2016)
- PWA Meetup , Rotterdam (2016)
- ViewSource , Berlin (2016)
- ScotlandJS , Edinburgh (2016)
- RenderConf , Oxford (2016)
- GOTOBerlin , Berlin (2015)
- Up.Front UG , Berlin (2015)
- WWNRW , Düsseldorf (2015)
- FH Dortmund , Dortmund (2015)
- JSUnconf , Hamburg (2015)
- Concat , Salzburg (2015)
- CouchDBDay , Hamburg (2015)
- OpenTechSchool , Dortmund (2015)

**Comment by karlcow** [comment]
All of this was for webcompat?

**Comment by zoepage** [comment]
no, but starting with 
- FrontTrends , Warschau (2017)
- WeAreDevelopers, Vienna (2017)
- Codemotion Amsterdam, Amsterdam (2017)
it will be. (plus probably Roadshow).

I posted that list to show the type of events and frequency of me speaking in the future about webcompat.

**Comment by karlcow** [comment]
So far, from the top of my head, it has been mainly @miketaylr going to conferences to talk about webcompat. This year has been light for me for family reasons. And will be probably light this year too. Though I might be asked by devrel like last year. We will see. @ioana-chiorean did a lot too. 

What I'm trying to guess is how useful it will be for people to have this page. Or how do we make it useful? And maintenance is key. This [event calendar](https://wiki.mozilla.org/Compatibility/Calendar) has not been maintained in the past. No blame. Just reality 101. 

There are different techniques to maintain such thing:
* There is an owner who has the burden to collect and shake the tree asking people for information.
* Automatic aggregation of people sources through a script. [mike's page](https://miketaylr.com/pres/). [Mine](http://la-grange.net/karl/talks/) (not maintained since 2011 lol. It speaks volume.)

**Comment by haseebgit** [comment]
@karlcow I spoke at one conference in 2016

"Introduction to webcompat.com" - FOSS Asia, Singapore(2016)

**Comment by ioana-chiorean** [comment]
2015 
* [FOSDEM](https://archive.fosdem.org/2013/schedule/speaker/ioana_chiorean/) - Brussels, February 3rd

2016
* [DevTalks](https://www.youtube.com/watch?v=UwXpAldCg28) - Cluj-Napoca, May 11th
* [CodeCamp ](http://codecamp.ro/archive/Codecamp19nov2016/index.html) - Cluj-Napoca, November 19th 

2017
* [FOSDEM](https://medium.com/@ioana_cis/about-fosdem-2017-db432c7c048b) - Brussels, Feb 4th
* [The Rolling Scopes](https://medium.com/@ioana_cis/about-rolling-scopes-conf-83311099e4b0#.oorjobltd) - Minsk, Feb 18th

This were my WebCompat talks till now (I might have miss 1 or 2 too, I need a better tracking)

**Comment by zoepage** [comment]
@miketaylr Just a friendly reminder as you mentioned, you'd like to add some feedback here. It's appreciated. :)

**Comment by miketaylr** [comment]
OK! Giving feedback 3 weeks later (right on time...)

So, in general I'm not opposed to such a page, but I have concerns that it might end up as a ghost town if not curated by an owner. Personally, such a page isn't useful to me, but it might be encouraging for other people to see their work and talks recognized.

For record keeping, last year I think I have 6 or so talks on web compatibility, but the year before was probably 0. This year looks like it will be about 6 talks again.

**Comment by zoepage** [comment]
Let's delay the discussion until we feel like we need such a section and close the issue for now.
