### ISSUE TITLE
Toggle add on link description with icon on small screensize in top navigation

### ISSUE THREAD

**Issue by zoepage** [webcompat/webcompat.com#1405]
### Todo 
- [x] hide `download our` when on small screensize
- [x] toggle with icon https://thenounproject.com/search/?q=donwload&i=620997

---

### Context
<img src="https://cloud.githubusercontent.com/assets/4382193/22042177/e5a4e9d0-dcbe-11e6-817e-951c5bbc218a.png" />

https://github.com/webcompat/webcompat.com/issues/1281#issuecomment-273320729

HTML: 
https://github.com/webcompat/webcompat.com/blob/master/webcompat/templates/addon-links.html

CSS: 
https://github.com/webcompat/webcompat.com/blob/master/webcompat/static/css/development/components/navbar.css#L41

**Comment by heatherbooker** [comment]
@zoepage So you want it to look like that screenshot on small screens? It seems to already do that!

**Comment by zoepage** [comment]
@heatherbooker yeah, but with the contribute icon ^^ 
(when you use the label, it should work yes)
