### ISSUE TITLE
Issue title page has no information

### ISSUE THREAD

**Issue by karlcow** [webcompat/webcompat.com#1412]
Currently, our issues individual pages have no information about the issue.

```html
<head>
  <title>webcompat.com</title>
…
</head>
```

This is due to the way we are handling the site. With empty templates fetching the information through JavaScript. It creates a couple of issues

* Bookmarking is useless
* Search engines indexing is useless https://duckduckgo.com/?q=google+site%3Awebcompat.com&t=ffab&ia=web
* Multiple tabs users have no way to disambiguate their tabs. See screenshot

![capture d ecran 2017-03-08 a 11 56 09](https://cloud.githubusercontent.com/assets/505230/23688300/12110238-03f7-11e7-9b4f-88edb93a0047.png)

## Suggestions

* [x] grab the issue number from the template. It's in there already
* [ ] change the way we build the template by pre-fetching the issue JSON file then prepopulating it. (my favorite choice)

Or we could modify the title through JS (but meh…) aka something along…

```js
document.title = IssueNumber + document.body.getElementsByTagName('h1')[0].textContent + SiteTitle
```

**Comment by sergiorojasa** [comment]
I would like to work on this

**Comment by karlcow** [comment]
@heatherbooker Ah excellent . Indeed your commit fixes the issue number. This is the low hanging fruit. Excellent. This is my first bullet point. 

The second bullet point is to have the title with the domain name.
https://webcompat.com/issues/4999

```html
<title>Issue #4999 - www.skylinewebcams.com - video doesn't play -webcompat.com</title>
```

To choose on how to do that. There is probably a need of evaluating the performance impact of prefetching the JSON on the server side before generating the HTML. But that's a bigger project. Maybe.

**Comment by karlcow** [comment]
It would be good to add a couple of unit tests for testing we received the right title.

**Comment by heatherbooker** [comment]
@karlcow Great point about testing it! I added a test.

Ok I see what you're saying about also having the issue title in the page title. Yeah, that does seem like a larger concern - I've never used flask, jinja, or backbone before but I've been sifting through their docs and webcompat code to try and figure out how one would go about getting that data pre-page load.

If you want to leave that as a bigger project (esp. if concerned about performance impact), I consider this PR ready for review; if you'd like me to continue looking into it, LMK! :)

**Comment by karlcow** [comment]
OK let's make this a first step. Thanks a lot. I added myself as a reviewer. I'm boarding a plane soon. I will review it when I reach the other side.
