### ISSUE TITLE
Flask-Limiter deprecated usage

### ISSUE THREAD

**Issue by brizental** [webcompat/webcompat.com#1420]
Everytime I run `python run.py` or `python run.py -t` I get this warning:

>UserWarning: Use of the default `get_ipaddr` function is discouraged. Please refer to https://flask-limiter.readthedocs.org/#rate-limit-domain for the recommended configuration

This is simple enough, just some changes to the `__init__.py` file and it's good to go. Just want to know if there is some reason this hasn't been done yet or if I can just go for it.

**Comment by karlcow** [comment]
Yes the warning could be avoided :) Last time I checked I don't think we were using get_ipaddr but before removing the warning, I wanted to check if get_ipaddr is called in some ways. And if yes, how do we change it.

@brizental feel free to investigate. :)

**Comment by brizental** [comment]
So, we don't use ip_addr on our code. It's just legacy code from Flask-Limiter.
We just have to add a parameter to the constructor for it not to use get_ipaddr anymore.
I'll send a PR shortly :)
