### ISSUE TITLE
New Footer Navigation concept for mobile

### ISSUE THREAD

**Issue by zoepage** [webcompat/webcompat.com#1422]
As we are improving our design, I'd like to suggest a new idea for the footer navigation on mobile.
Please note, this is "just" a concept and no finished designs. :)

**Old**

![footer_nav](https://cloud.githubusercontent.com/assets/562354/23792823/dbc8e82e-0588-11e7-9972-6c9f1ee18abd.png)

**New - closed / no subtopics**
![footer_nav_old](https://cloud.githubusercontent.com/assets/562354/23792888/1df0336a-0589-11e7-8a3e-42b69939ba29.png)

**New - closed / open subtopics** 
![footer_nav_new](https://cloud.githubusercontent.com/assets/562354/23792899/2795eba8-0589-11e7-8e1b-4f30a79e3264.png)

So, what do you think?

**Comment by nj4710** [comment]
I would like to go with the second one. Nice and Clean :)

**Comment by zoepage** [comment]
@adamopenweb @lockettm @karlcow @denschub @MDTsai @wisniewskit

**Comment by adamopenweb** [comment]
I dig it. I'm wondering if the Twitter and Github icons could use a little more space on top though?

**Comment by zoepage** [comment]
@adamopenweb yes, they should get more space. Will add, when make the design :)

**Comment by lockettm** [comment]
Looks good. It does a great job of visually separating the different links, they'll also be easier to tap.

**Comment by karlcow** [comment]
Personally, I would not do an open/close state and makes it just a list of links (the 3rd screenshot only). This kind of choice if we had infinite time and a big enough crowd could be tackled with A/B testing. We are not there yet.

**Comment by denschub** [comment]
As a follow-up thought on @karlcow, I wonder if it's necessary to implement the open/close thingy at all. There is not much content after that links after all...

But yes, I like it!

**Comment by zoepage** [comment]
The solution right now is a bit hard to use on mobile, so enhancing it feels like the right thing to do.

@karlcow 
> Personally, I would not do an open/close state...

It's not an "active" open/closed state, which means the subtopics will be open, when you are on the maintopic.

@denschub 
> There is not much content after that links after all...

I think, with the great changes @lockettm suggested, we'll add up more content soon.

**Comment by adamopenweb** [comment]
> The solution right now is a bit hard to use on mobile, so enhancing it feels like the right thing to do.
I agree. IMO we should move forward with this.

**Comment by zoepage** [comment]
Cool. I'll mock up few things and create an issue for it. 

Thanks everyone <3

**Comment by zoepage** [comment]
Added to mockups in [Living Style Guide](https://github.com/webcompat/design), but will not be implemented yet as we will just refactor the old content in the first step. Also feedback was already added to mockups. So, closing for now.
