### ISSUE TITLE
[Graphics]  SVG icons need to be improved

### ISSUE THREAD

**Issue by karlcow** [webcompat/webcompat.com#1425]
So following discussions in #1421 PR.

As we can see for the three SVG icons, the one on the left, the report bug, is a bit thinner and smaller. 
![Icons for three steps](https://cloud.githubusercontent.com/assets/505230/23858535/078735f4-0801-11e7-8cec-ed63a54826d7.png)

* [ ] SVG icons need to be re-centered and  in their own view box
* [ ] Report bug icon needs to be thicker for matching the two others
* [x] The included text inside the SVG can be cleaned up too

It might be possible to just improve the tracing. Or just remake them. It's not really complicated but long and a fun project. It requires a bit of expertise with SVG too.

**Comment by zoepage** [comment]
I know, @bastianalbers is working on this and will send a PR soon.

**Comment by zoepage** [comment]
The placement of SVG's was improved and the message was taken out. The other two todo's are still open, if anyone wants to tackle them.

**Comment by zoepage** [comment]
In the new design, there won't be icons as you can see here http://webcompat.github.io/design/ "Module: Hero Tiles". So this issue can be closed.
