### ISSUE TITLE
CONTRIBUTING.md needs to be adjusted for the new stricter GitHub format

### ISSUE THREAD

**Issue by brizental** [webcompat/webcompat.com#1427]
So, the layout in CONTRIBUTING.md is broken for me. There are two broken parts.

 The first is a small one:
![screenshot from 2017-03-16 22-36-37](https://cloud.githubusercontent.com/assets/25176023/24025468/5022fbfa-0a99-11e7-8a2a-df148cf21c29.png)
The starter and the closing  backticks and "bash" shouldn't appear. I have looked at the code and this is happening because there is an extra space on line 268.

The second one is a bigger one:
![screenshot from 2017-03-16 22-36-56](https://cloud.githubusercontent.com/assets/25176023/24025680/a7687254-0a9a-11e7-9bb6-25c8d5adf90b.png)
All the layout after "We use cssnext as a tool for compiling css" is messed up. This is happening because of an extra backtick on line 200.

I don't know why this was not happening before. Since the last changes made to these lines were a while ago...

**Comment by karlcow** [comment]
It's probably happening because of Github creating [a formal spec for GitHub Flavored Markdown](https://githubengineering.com/a-formal-spec-for-github-markdown/). They say: 

> The Markdown documents stored in Git repositories, however, cannot be touched at all, as their contents are hashed as part of Git’s storage model.
> 
> Fortunately, we discovered that the vast majority of user content that was using complex Markdown features were user comments (particularly Issue bodies and Pull Request bodies), while the documents stored in Git repositories were rendering properly with both the old and the new renderer in the overwhelming majority of cases.

We are part of the unlucky ones. :) so to fix.

**Comment by brizental** [comment]
I tried to look for an automatic way to do the adjustments from the old  to the new syntax, but couldn't find any. I'll send a PR shortly that fixes the mistakes that I found, ok?

**Comment by karlcow** [comment]
@brizental thanks a lot. That sounds like a good plan.
