### ISSUE TITLE
Add test for `/activity/user`

### ISSUE THREAD

**Issue by heatherbooker** [webcompat/webcompat.com#1428]
To finish up #1419 (fixes #1412 ), there needs to be one more title added to the array being tested in `test_rendering.py` - the title for `/activity/user`. This will require mocking the circumstances of the /activity template. More info [here](https://github.com/webcompat/webcompat.com/pull/1419#issuecomment-286418716).

**Comment by karlcow** [comment]
Tests in test_rendering are working and correctly check /activity/username template… BUT to be able to make it work correctly I had to modified a bit `views.py`
which in return broke almost all tests in test_urls.py 😂 

I changed a bit the way we do test_urls.py and went from all to two tests breaking. 1 ERROR and 1 FAILURE. I have hope. :)

Mostly related to the fact that these tests are calling… GitHub when a username is given. So I need to find a better way of managing side effects. And probably at the same time, if I find an elegant solution that would make #1384 a lot easier to implement.

Suggestions are welcome. I wonder if @vladikoff has one idea or two. Or if I'm doing it really wrong.
