### ISSUE TITLE
When attaching a screenshot with Drag and Drop, the image is opened

### ISSUE THREAD

**Issue by softvision-sergiulogigan** [webcompat/webcompat.com#1433]
**Browser / Version**
Chrome 56.0.2924.87 (Desktop)
Firefox 52.0.1 Release (Desktop)

**Operating System**
Windows 10

**Give more details**
1. Launch the Chrome browser.
2. Navigate to: https://webcompat.com/issues/new
3. Drag and Drop an image into the "Attach a screenshot image" placeholder.

Expected Behavior:
The image is attached.

Actual Behavior:
The image is opened.

Notes:
1. The issue is reproducible 5/5 attempts on Chrome.
2. Workaround: Click the "Attach a screenshot image" link, and then close the file selection window. Follow step 3.
3. The issue is also reproducible on Firefox, on first attempt.

sv;

**Comment by softvision-oana-arbuzov** [comment]
I've observed when inspecting the "Screenshot" area that only the left half side of it allows to drag and drop an image and attach it (check screenshot). When drag and dropping an image anywhere else, it is being opened.
![uploadonlyarea](https://cloud.githubusercontent.com/assets/12184325/24649410/a043a6b2-192f-11e7-8bd6-726eca98d8e4.png)

**Comment by magsout** [comment]
@softvision-oana-arbuzov @softvision-sergiulogigan In this PR https://github.com/webcompat/webcompat.com/pull/1492 I fixed some CSS Bug, and I think I fixed this bug, could you test to see if you get to reproduce the bug? 

Thanks

**Comment by softvision-sergiulogigan** [comment]
Hi, @magsout , I have tested both in Chrome and Firefox, and I was unable to reproduce the issue. It seems it has been fixed, so it can be closed now.

**Comment by magsout** [comment]
Cool, thanks @softvision-sergiulogigan
