### ISSUE TITLE
Add prettier instead of eslint 

### ISSUE THREAD

**Issue by magsout** [webcompat/webcompat.com#1434]
I like the idea behind prettier. 

you can write your code however you like and instantly prettier format it correctly.

http://jlongster.com/A-Prettier-Formatter

We can add a script in the file package.json to automate prettier to start before a commit

**Comment by karlcow** [comment]
Just my 2 cents. 

One of the valuable things about style rules when editing code is that you ensure that the code is readable for everyone now and the future (aka consistency in a team). I usually like packages which helps developers put the code in the right form. But I don't really like packages which are silently changing the code. 

So for a better understanding:
1. Does prettier fix the code when you edit it (before commit)? (pep8 style in python)
2. OR Does prettier fix the code once compiled (after commit)?

I would prefer 1.

Supported in Atom, SublimeText, Emacs, Vim, … according to https://github.com/prettier/prettier

**Comment by karlcow** [comment]
> to automate prettier to start before a commit

/me needs to better read!

**Comment by miketaylr** [comment]
I've heard good things about prettier, I'm +1.

**Comment by zoepage** [comment]
@magsout Seems like people are on board!
Do you wanna work on this? :)

**Comment by magsout** [comment]
@zoepage 👍 <3

**Comment by magsout** [comment]
@karlcow I heard your comment, So I added Prettier insinde eslint.. https://github.com/webcompat/webcompat.com/pull/1468

 The package  are not silently changing the code.
