### ISSUE TITLE
/rate-limit shows webcompat-bot when non authentified

### ISSUE THREAD

**Issue by karlcow** [webcompat/webcompat.com#1437]
Currently, we are displaying the rate limit when requesting https://webcompat.com/rate_limit and being logged out.

```
Current user: webcompat-bot

Core resources rate limit: 4998 / 5000 requests.
Reset in 45 minutes.

Search rate limit: 30 / 30 requests.
Reset in 1 minute.
```

I don't have the feeling it is useful for anyone but us. Maybe we should just return a 403, with a simple text message saying that rate limit is available only to authenticated users. 

It also removes the need for 
https://github.com/webcompat/webcompat.com/blob/db4e879a167604debfa04d3e208be68cb4f64c6d/webcompat/views.py#L253-L256

webcompat-bot is a person like us.

**Comment by miketaylr** [comment]
That was an intentional decision back when I wrote that, just to be able to debug situations where the bot was hitting the rate limit. But it's arguably not useful to anyone (bot, or authed user).

**Comment by adamopenweb** [comment]
I forgot about this.
 
> But it's arguably not useful to anyone (bot, or authed user).

Yeah, if it's not needed anymore, why not remove altogether?

**Comment by karlcow** [comment]
ok! Let's do this. Thanks everyone.
