### ISSUE TITLE
add browserstack logo/blurb to site/readme

### ISSUE THREAD

**Issue by cch5ng** [webcompat/webcompat.com#1438]
hi, the free browserstack account is coming up on expiration. a support contact made the request that in order to extend the free account, some credits should be visible on the site and/or readme.

I can work on this (target next couple of days).

**Comment by miketaylr** [comment]
Seems like a fair trade. :D

**Comment by cch5ng** [comment]
what was done

- [ ] README: added text blurb and link to browserstack 
- [ ] homepage: added logo and text blurb (link to browserstack)
