### ISSUE TITLE
Add description about Virtualenv in Contributing.md

### ISSUE THREAD

**Issue by nj4710** [webcompat/webcompat.com#1441]
I think that the section of virtualenv in Contributing.md could use some more description about Virtual environments or a link to a page describing virtual environment. That will be very helpful for newcomers.
**Installing virtualenv**
`[sudo] pip install virtualenv`

Also, in some lines like

> We use cssnext as a tool for compiling css

a full stop is missing. 
So, what do you think?

**Comment by zoepage** [comment]
+1 on additional info to virtualenv. Do you have anything specific in mind, like a link that provides the information you'd like to see @nj4710 ?

+1 on full stop.

**Comment by nj4710** [comment]
I would like to have a description like `Virtual Environment is a tool to create isolated environments for different projects so as to prevent conflicts.`

or a link to the docs [https://virtualenv.pypa.io/en/stable/](url)

**Comment by sunakshi96** [comment]
@nj4710 
We can keep both the Description(with an example of where the conflict might occur and if it occurs how can it be solved) as well as the link.

**Comment by zoepage** [comment]
Also +1 on both :)
@nj4710 wanna send a PR? :)

**Comment by nj4710** [comment]
sent:)

**Comment by zoepage** [comment]
Merged ;)

**Comment by nj4710** [comment]
Thanks @zoepage :hand:
