### ISSUE TITLE
The Search text field is not clearly defined

### ISSUE THREAD

**Issue by softvision-sergiulogigan** [webcompat/webcompat.com#1442]
Browser / Version: Chrome 57.0.2987, Firefox 52.0
Operating System: Windows 10

Steps to Reproduce
1. Navigate to: https://webcompat.com/issues?page=1&per_page=50&state=open&stage=all&sort=created&direction=desc
2. Observe the Search textbox.

Expected Behavior:
The Search text field is clearly defined and intuitive to use.

Actual Behavior:
The Search text field is not clearly defined.

sv;
![screenshot](https://cloud.githubusercontent.com/assets/16573771/24344941/74272ab8-12d6-11e7-8f2a-9d4ea8cd84ea.jpg)

**Comment by zoepage** [comment]
@softvision-sergiulogigan Thanks for the hint! 
Do you think of this as mainly a design / concept issue?

**Comment by softvision-sergiulogigan** [comment]
Yes, I think it is only design issue. I think that making the textbox white, would solve the ambiguity.
Or maybe just shorten the textbox. Or both.
IMO, the hint text and the icon are too far apart.

**Comment by zoepage** [comment]
As I understood it correctly, the main issue is contrast / visibility and the relation between hint text and the icon, correct? :)

(Just wanted to rephrase, so I've understood the issue)

**Comment by softvision-sergiulogigan** [comment]
Yes, that's correct.

**Comment by zoepage** [comment]
Thanks for clarify this :)
Yeah, I can totally see this. Changing the background to white of the input should already group those items and make the relation clear. 

Additional idea would be to put the magnifying glass in front of the hint text as shown on the index page. Would also add more contingency. 

<img width="1255" alt="screen shot 2017-03-27 at 2 09 35 pm" src="https://cloud.githubusercontent.com/assets/562354/24355740/5bc2d56e-12f7-11e7-89d9-f5606a711f06.png">

What do you think @softvision-sergiulogigan, but also @adamopenweb  @magsout and @lockettm?

**Comment by adamopenweb** [comment]
Making the input background white should help, IMO.

**Comment by sunakshi96** [comment]
@zoepage the search text field, with magnifying class icon looks perfect.
We can make the magnifying icon as a button , to the right of search field?

**Comment by karlcow** [comment]
Just to visualize in context.

![capture d ecran 2017-03-28 a 08 11 59](https://cloud.githubusercontent.com/assets/505230/24381963/4cb7df46-138e-11e7-8db1-13e892d9b84c.png)

**Comment by karlcow** [comment]
Also https://dribbble.com/search?q=search+form

**Comment by zoepage** [comment]
@karlcow did you just mock that up? <3

**Comment by zoepage** [comment]
@magsout It's also a button on the index page...
<img width="623" alt="screen shot 2017-03-28 at 12 54 02 pm" src="https://cloud.githubusercontent.com/assets/562354/24401743/e2bd4a90-13b5-11e7-981c-aee18a68ef4b.png">

So, which ever decision we make, it should be done on both sides :)

**Comment by karlcow** [comment]
@zoepage 
> @karlcow did you just mock that up? <3

what are devtools for if not sculpting Web pages on the spot?

**Comment by magsout** [comment]
@zoepage oh oups, <3

My bad ;)

**Comment by zoepage** [comment]
DECISION:
To go with following https://github.com/webcompat/webcompat.com/issues/1442#issuecomment-289613640

**Comment by zoepage** [comment]
This will be solved in the big refactor soon. Mocks can be seen in the [design repository](https://github.com/webcompat/design).
