### ISSUE TITLE
add npm build to npm start

### ISSUE THREAD

**Issue by zoepage** [webcompat/webcompat.com#1448]
As a lot of new contributors forget the `npm run build` step and file issues or ping on the channel, because the CSS files are missing.

To help and make the setup steps simpler, it seems like a good idea to put `npm run build` in one of the steps. As running the build before starting the server makes sense, I'd suggest to put it [here](https://github.com/webcompat/webcompat.com/blob/master/package.json#L51).

What do you think?

**Comment by miketaylr** [comment]
Sounds good!

**Comment by magsout** [comment]
@zoepage yes 👍

**Comment by zoepage** [comment]
As npm scripts don't like `()`, it seems like 
`"start": "grunt && source env/bin/activate || grunt && . env/bin/activate && python run.py",` would be the only thing that makes sense right?

(@denschub)
