### ISSUE TITLE
Move GA code to external (async) script file

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat.com#1449]
This is something that came up investigating CSP #763.

**Comment by miketaylr** [comment]
To fix this:

the script code here: https://github.com/webcompat/webcompat.com/blob/master/webcompat/templates/layout.html#L42-L49

Should end up in its own ga.js file, probably is static/js/vendor and the it script tag should use the `async` attribute:

`<script src=path/to/file async></script>`

**Comment by miketaylr** [comment]
Hm, possibly we want to move to the "alternative async tracking snippet" first: https://developers.google.com/analytics/devguides/collection/analyticsjs/. As is, they try to load a JS data URI and that seems not great.

**Comment by karlcow** [comment]
Do we **really use** GA? Probably @adamopenweb can answer. I know we had intents, but do we really do it. If not, why keeping it around?

**Comment by miketaylr** [comment]
> Do we really use GA?

Infrequently, but @adamopenweb and other people at Mozilla have been interested in the data, especially when doing stuff with dev-marketing.

**Comment by adamopenweb** [comment]
@karlcow We don't have a specific use case for it. But it's good to know, for example, that 40% of our traffic is coming from China (most likely QA from that fennec fork). 

Is it worth having our users tracked by Google? Probably not IMO, but I'm also a fan of tracking protection. 😄

**Comment by karlcow** [comment]
"so you are saying that Chinese users don't use tracking protections". 🤡 (kidding)

**Comment by nj4710** [comment]
I want to work on this issue:)
