### ISSUE TITLE
More CSP tweakings - Round 2

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat.com#1450]
We've learned a few things, need to update the policy. See https://github.com/webcompat/webcompat.com/issues/763#issuecomment-289847715.

**Comment by karlcow** [comment]
grmbl. From the comments, I guess paraphrasing @miketaylr's prose.

* [ ] GA adds a data URI JS snippet. we need to allow this now and look to remove it later.
* [ ] We use data image URIs for upload previews. We should allow this.
* [ ] We need to whitelist the GitHub search API for non-logged in search.

**Comment by miketaylr** [comment]
> grmbl

>_>
