### ISSUE TITLE
add code language labels

### ISSUE THREAD

**Issue by zoepage** [webcompat/webcompat.com#1452]
In our weekly meeting today, there was the idea of having labels of required language skill indicator for specific bugs.

Minutes can be seen here:
(Now) https://public.etherpad-mozilla.org/p/webcompat
(Soon) https://wiki.mozilla.org/Compatibility/Meetings

- What would be the criteria to add such a label? Just for starter bugs or for all? 
- Should we have different levels for the languages to indicate the required skill set?
- What would be the format of the label? 

Suggestion: 
`lang: JS`
`lang: CSS`
`lang: Pyton`
...

What do y'all think?

(Esp. @karlcow && @wisniewskit as you two came up with the idea.)

**Comment by karlcow** [comment]
[28 March 2017 Minutes](https://wiki.mozilla.org/Compatibility/Meetings/2017-03-28#Outreachy_PR.27s_.2F_issues_.28ola.29) with the discussion that @zoepage is mentioning.

@zoepage Good suggestions. 183 issues to fix/review ;)

**Comment by karlcow** [comment]
>    What would be the criteria to add such a label? Just for starter bugs or for all?

all bugs :) It will be practical for the community as large and projects like https://www.whatcanidoformozilla.org/#!/progornoprog/advocate/webcompat

>    Should we have different levels for the languages to indicate the required skill set?

I guess if the bug is targeted as good-first bug. The requirements on the language are low.

>    What would be the format of the label?

The format you suggested seems good and regular with others.

**Comment by magsout** [comment]
@zoepage @karlcow very good idea.

**Comment by zoepage** [comment]
@karlcow 
> all bugs :) It will be practical for the community as large and projects like https://www.whatcanidoformozilla.org/#!/progornoprog/advocate/webcompat

+1 for community project.
So, we would need to write down a todo issues, with a small concept for the criteria, right?

> I guess if the bug is targeted as good-first bug. The requirements on the language are low.

So context related? +1 on that!

What do you think @miketaylr @denschub @MDTsai @wisniewskit @adamopenweb ? :)

**Comment by miketaylr** [comment]
+1

**Comment by denschub** [comment]
👍

**Comment by zoepage** [comment]
I'll create the labels and add an issue for it.

**Comment by magsout** [comment]
@zoepage looks good 👍 

Just one more question, what about tools ? Like grunt, webpack etc.. ?

**Comment by magsout** [comment]
Thinking of my previous question, I think it's stupid.

lang = JS.

**Comment by zoepage** [comment]
@magsout It's a valuable thing to think about builds and maybe also devOps at some point?

**Comment by zoepage** [comment]
Shall we add frameworks too? Like jQuery or Backbone?

**Comment by zoepage** [comment]
FYI: 
Labels set on `status: good first bug` and `status: good next bug`.

**Comment by karlcow** [comment]
For frameworks, I would say no. We want a minimal set of things.
@zoepage thanks for creating the labels.

**Comment by magsout** [comment]
@zoepage I agree with @karlcow for frameworks. `lang` labels is enought IMO.

for devops, or api, or tools, I don't know how many issues are about these subject ? I guess not a lot.

**Comment by zoepage** [comment]
I understand the issue of having way too many labels. 

Sometimes you have issues that need specific skill needs, e.g. JS does not mean you are experienced with e.g. Backbone. We also have e.g. quite a few GitHub API issues.

Would it make sense to add this information in the first issue comment in a specific format, so it would make it easier to filter issues (just not as intuitive).

**Comment by karlcow** [comment]
Let's fix things when there is a need. 
We could add these if there are necessary in the future. It's not the case for now.

**Comment by zoepage** [comment]
@karlcow i feel like there is a need as we have a lot of (old) issues that are hard to go through. Let's put it on the `discuss in Berlin list`.
