### ISSUE TITLE
Create a note in the documentation for not overcommitting

### ISSUE THREAD

**Issue by karlcow** [webcompat/webcompat.com#1454]
In [CONTRIBUTING.md](https://github.com/webcompat/webcompat.com/blob/master/CONTRIBUTING.md) we need to add a note for reminding people to not over-commit themselves. Aka if they currently work on an PR. They should not take another one, except if the PR is in the process of being reviewed. 

1. It helps people to focus on what they have to do.
2. It unblocks other issues for other contributors. 

Cf [discussions on team meeting March 28, 2017](https://wiki.mozilla.org/Compatibility/Meetings/2017-03-28#Outreachy_PR.27s_.2F_issues_.28ola.29)

(It's yet more content. And I know that @zoepage voiced concerns about the length of the documentation and its structure. There's an issue for this. If @zoepage wants to take it over, feel free #264 )

**Comment by zoepage** [comment]
@karlcow 
> They should not take another one, except if the PR is in the process of being reviewed.

I like the idea to add that note to the contributing.md, but it this mostly applies to new / less-experienced contributors. For experienced contributors, having 3-5 PRs open plus contributions in different issues / discussions might not be an issue.

So, I guess its mostly about wording?

@karlcow 
> And I know that @zoepage voiced concerns about the length of the documentation and its structure.

True. The documentation is great and has all the information you'd need, but might feel a little bit overwhelming... especially when you are looking for something specific. So a refactor could improve the contributors experience (especially for first timers). 

Maybe writing an outline and asking the community for help with the refactor here would be a good way to go? Happy to help with a draft. :)

**Comment by miketaylr** [comment]
Maybe something like working on no more than 2 good first bugs at a time.
