### ISSUE TITLE
Click "e" on webcompat.com comment area opens label menu

### ISSUE THREAD

**Issue by MDTsai** [webcompat/webcompat.com#1455]
Expect behavior: nothing happen
Actual behavior: click "e" always open label menu, which interrupt comment.

**Comment by karlcow** [comment]
Indeed. weird. But in fact quite handy when you are at the bottom of a long comments chain

1. Go to https://webcompat.com/issues/1061
2. Scroll to the bottom
3. Type e.
4. 🏅 labels in focus.

**Comment by karlcow** [comment]
This is a bug. I wonder if it should become a feature. Though "e" -> "l"

**Comment by karlcow** [comment]
Ah not a bug. Intentional.
https://github.com/webcompat/webcompat.com/blob/28ac4928f56dec681349fa977d619da3d2888eac/webcompat/static/js/lib/labels.js#L26-L28

**Comment by MDTsai** [comment]
I guess we can exclude this event if input area is focused.

**Comment by karlcow** [comment]
Yes just understood your issue. OK there is a regression introduced by a recent merge. I guess. Because indeed now typing e in a textarea open the label editor, which makes it unusable.  @MDTsai  Sorry for not understanding the first time

**Comment by zoepage** [comment]
As this bug makes the comment area unusable, I'll take care of it today. 
Shall we change `e` to `l` in that step? Plus add an info in the "g for github" box.

**Comment by MDTsai** [comment]
@zoepage: I found e (or l) open label menu is fixed but g open github view is still existing.

**Comment by karlcow** [comment]
@MDTsai yup https://github.com/webcompat/webcompat.com/pull/1459#issuecomment-290278908

**Comment by zoepage** [comment]
Seeing it. But I don't understand why it broke now.
I tested a few times manually yesterday and it all worked as it should have. 

(I understand why it's not working in the expected way, but not why it worked in a different before...)

So I guess, we **really** need the automated tests here.
