### ISSUE TITLE
Add functional regression test for preventing shortcut to open label editor when typing comment

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat.com#1462]
Fix was landed in https://github.com/webcompat/webcompat.com/pull/1459, but we should write an Intern test for this.

**Comment by miketaylr** [comment]
(I'm happy to mentor anyone who wants to work on this!)

**Comment by miketaylr** [comment]
See #1455 as well, this should cover all shortcuts.

**Comment by brizental** [comment]
Hey Mike! I would like to work on this. Can you give me some pointers?

**Comment by miketaylr** [comment]
Sure thing!

Basically, we need to add a couple of tests for these scenarios:

1. user is typing in an issue comment and pressed `l` (lower-case letter l, as in lizard)
2. user is typing an an issue comment and pressed `g`

In both of these instances, nothing should happen. That is, the associated l and g shortcuts should not fire. So, the "label editor" shouldn't be visible, and we shouldn't end up on GitHub.

We have a similar test here for the search stuff:

https://github.com/webcompat/webcompat.com/blob/master/tests/functional/search-non-auth.js#L22-L35

https://github.com/webcompat/webcompat.com/blob/master/tests/functional/comments-non-auth.js is a good file for these tests to live.

Ping me if any of that needs clarification!

**Comment by brizental** [comment]
Ok, think I got it. I'll give this a try now :)

**Comment by zoepage** [comment]
There is also the case for `INPUT` as we have the search filed. Not sure, if this is already covered somewhere or if we should add it here. More a FYI, so we do not forget to test it at some point.

**Comment by brizental** [comment]
@zoepage the tests for that are already on the `issues-non-auth.js` and `issue-list-non-auth.js` files :)
