### ISSUE TITLE
Rename `labelWarp` method

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat.com#1465]
The name `labelWarp` could be improved.

To fix this, `labelWarp` should be given a more descriptive name like `openLabelEditor` or `editLabels` or something, in these two places:

* [ ] https://github.com/webcompat/webcompat.com/blob/37fa4d28bbf533d536995cb443c3c6856dd386a7/webcompat/static/js/lib/labels.js#L27
* [ ] https://github.com/webcompat/webcompat.com/blob/37fa4d28bbf533d536995cb443c3c6856dd386a7/webcompat/static/js/lib/labels.js#L29

**Comment by moraveyo** [comment]
Can I work on it?

**Comment by zoepage** [comment]
@moraveyo Enjoy :) If you have questions, please let us know :)
