### ISSUE TITLE
Handle decoding + as a space for `details` param values

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat.com#1469]
(https://github.com/webcompat/webcompat.com/issues/1358#issuecomment-290627963)

The value of the `details` param will be constructed using `URLSearchParams` rather than `encodeURIComponent`, and it treats spaces differently (+ vs %20).

Something hacky like `decodeURIComponent(str.replace(/\+/g, '%20'));` would probably do the trick.

**Comment by miketaylr** [comment]
Ping @karlcow for maybe some advice (feel free to ask more questions... not a ton of context).

**Comment by karlcow** [comment]
@miketaylr 

Does [that help](https://docs.python.org/2/library/urllib.html#urllib.unquote_plus)?

```python
>>> import urllib
>>> urllib.unquote_plus('http://example.com/foo?q=a+well+thought+module')
'http://example.com/foo?q=a well thought module'
```

**Comment by karlcow** [comment]
and just for the record on your proposal above mixing inadequately two things 👹 

```python
>>> s = 'http://example.com/foo?q=a+well+thought+module'
>>> # SIMPLE
>>> s.replace('+', '%20')
'http://example.com/foo?q=a%20well%20thought%20module'
>>> # OR REGEX
>>> import re
>>> regex = r"\+"
>>> new = "%20"
>>> re.sub(regex, new, s, 0)
'http://example.com/foo?q=a%20well%20thought%20module'
```

**Comment by miketaylr** [comment]
@karlcow `unquote_plus` is cool, didn't know about that. I need to handle this on the client before we submit to the server. AFAICT, just replacing `+` with `%20` should be safe, then we can decode as normal.

`URLSearchParams` serializes input as [x-www-form-urlencoded](https://url.spec.whatwg.org/#application/x-www-form-urlencoded), which encodes SPACE as `+`:

```
0x20 (SP)
    Append U+002B (+) to output.
```

Looking at the serialization steps, it seems like only `+` is different, otherwise things are left as is or percent encoded: https://url.spec.whatwg.org/#urlencoded-serializing

So as long as we don't replace the `+` after decoding, but before (since we might be replacing an actual `+` PLUS character with a space...which came from `%2B`), `decodeURIComponent(str.replace(/\+/g, '%20'))` should be OK.

I'll be sure to only do this decoding hack for the details param content, so we don't break legacy content.

**Comment by karlcow** [comment]
I don't know why I was thinking we were in python world. All my comments above don't make sense at all. Sorry about that.
