### ISSUE TITLE
Newest dropdown can be improved

### ISSUE THREAD

**Issue by nj4710** [webcompat/webcompat.com#1471]
Hi!
I feel that the text in the drop-down merges with the text in the background. This may hamper user experience. This can be improved maybe by changing the opacity or background colour  of the dropdown. 
![dropdown](https://cloud.githubusercontent.com/assets/13145287/24604260/b89e9a7c-1881-11e7-8d17-30d39597a033.png)
What do you think?

**Comment by zoepage** [comment]
Good catch @nj4710 

Changing opacity to 0.95 is already helping (plus a thin border in light gray).
<img width="553" alt="screen shot 2017-04-03 at 1 00 56 pm" src="https://cloud.githubusercontent.com/assets/562354/24606565/f2d303cc-186d-11e7-913b-6bbc169ffefe.png">
<img width="448" alt="screen shot 2017-04-03 at 1 01 31 pm" src="https://cloud.githubusercontent.com/assets/562354/24606566/f2d49228-186d-11e7-9971-afd60ca48f70.png">

**Comment by nj4710** [comment]
A light border and opacity of 0.95 could also be helpful in the drop-down of view all.

![view-all](https://cloud.githubusercontent.com/assets/13145287/24615629/6bd88240-18ac-11e7-9937-7c79b67d6526.png)

**Comment by zoepage** [comment]
@nj4710 Sorry, should have mentioned that I meant both of the drop downs as they should have a consistent style. :)

So, setting both to `opacity: 0.97` and the `border: 1px solid #F0F0F0` should fix this. :)
(The color here is one of our per-defined colors, we want to reuse as seen here http://webcompat.github.io/webcompat.com/.)

**Comment by lewiscowper** [comment]
I'd be happy to work on this one! 👍

**Comment by zoepage** [comment]
@lewiscowper <3

**Comment by zoepage** [comment]
As this will be fixed in the refactor (https://github.com/webcompat/design/blob/master/website_modules/filter-options-issues/Desktop%20HD%20Copy%204.png), I'd say we close this as we don't need a fix in the old design for it.
