### ISSUE TITLE
Document recommended eslint/prettier workflow

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat.com#1474]
Support for prettier landed in #1468.

We should determine a simple workflow, and document it so we're all on the same page.

Strawman proposal:

 1.  write some code
 2.   run npm run lint
 3.   run npm run fix (if there were simple style errors...)
 4.   commit, make PR, etc.

**Comment by magsout** [comment]
@miketaylr looks good 👍 it's I think the best way.

**Comment by zoepage** [comment]
+1

Do we want to add a hook to lint automatically before committing? 
https://github.com/prettier/prettier#pre-commit-hook-for-changed-files

**Comment by magsout** [comment]
@zoepage 

>Do we want to add a hook to lint automatically before committing?

It was my first thought and I made it in my initial PR. But after I did not know if it was good or practical to do that especially after the comment of @karlcow  https://github.com/webcompat/webcompat.com/issues/1434#issuecomment-288255993

**Comment by zoepage** [comment]
@magsout Just to clarify, I was just talking about linting. Not fixing :)

Not a fan of automated fixing either, so I agree with @karlcow. Linting is something people like to forget (as same as running the build and wondering, why the styles are missing... Me. Always. :grin:)

**Comment by miketaylr** [comment]
Decision: we'd like to figure out a pre-commit style workflow. But possibly good to document manual way as well?

**Comment by magsout** [comment]
@zoepage 
>@magsout Just to clarify, I was just talking about linting. Not fixing :)

ah yes, you meant `npm run lint` ? not `npm run fix`  ?

**Comment by magsout** [comment]
So something like:

```js
"scripts": {
    "precommit": "lint-staged",
 },
"lint-staged": {
    "{webcompat/static/js/lib,tests}__}/**/*.js": [
      "npm run lint"
    ]
  },
```

**Comment by miketaylr** [comment]
So with a pre-commit lint, I guess once you try to commit w/ style errors, it will fail and then it's up to you to run `npm run fix`? @zoepage is that what you would expect?

**Comment by zoepage** [comment]
@miketaylr 
The pre-commit should lint after adding the files through `git add, but before the commit itself. 
Then you could run `npm run fix` or fix manually. This is what I would expect. :)

**Comment by miketaylr** [comment]
Cool, thanks! I can live with that. :)

@magsout want to implement what you wrote in https://github.com/webcompat/webcompat.com/issues/1474#issuecomment-291502599?

**Comment by miketaylr** [comment]
This should go here: 

https://github.com/webcompat/webcompat.com/blob/master/CONTRIBUTING.md#javascript

**Comment by magsout** [comment]
@miketaylr certainly
