### ISSUE TITLE
“Attach Screenshot” area becomes cropped when using keyboard “Tab” button twice

### ISSUE THREAD

**Issue by softvision-oana-arbuzov** [webcompat/webcompat.com#1475]
**Browser / Version:** Firefox Mobile Release 52.0.2, Chrome 56.0.2924
**Operating System:** Windows 10 Pro

**Steps to Reproduce**
1.	Navigate to: https://webcompat.com.
2.	Click “Report a bug” button. 
3.	Click the “Give more details” area.
4.	Use keyboard “Tab” button twice.
5.	Observe behavior.

**Expected Behavior:**
[TBD] “Report Anonymously” is selected (highlighted), considering that “Screenshot” area is skipped.	

Actual Behavior:
“Attach Screenshot” area becomes cropped.

**Notes:**
1. As a consequence of this issue “Remove image upload” button also becomes available.
2. Screenshot can still be attached and “Remove image upload” button has no functionality until a screenshot is available.
3. Screenshot attached.

sv; 

![croppedscreenshotarea_2xtab](https://cloud.githubusercontent.com/assets/12184325/24646282/0c2f885c-1924-11e7-91b1-818707f89c62.png)

**Comment by miketaylr** [comment]
Oops. @magsout is this something you might be able to look at?

**Comment by magsout** [comment]
@miketaylr 👍
