### ISSUE TITLE
Autoexpand does not work in chrome for bug-reporting form

### ISSUE THREAD

**Issue by nj4710** [webcompat/webcompat.com#1477]
Issue landed from here [#1476](https://github.com/webcompat/webcompat.com/pull/1476)
We have added the auto-expanding feature to Give more details of bug-reporting area and comments in issues. The auto-expanding works well in Firefox for both the areas. In chrome, it does not work for bug-reporting form

**Comment by zoepage** [comment]
@nj4710 could you please provide more information here? I tried to reproduce, but its try without context. Thanks :)

**Comment by magsout** [comment]
@zoepage related to https://github.com/webcompat/webcompat.com/pull/1440#issuecomment-291522149

But it seems to work https://github.com/webcompat/webcompat.com/pull/1440#issuecomment-291524792

I don"t know if @miketaylr deploys to the production site

**Comment by miketaylr** [comment]
Will do a deploy this afternoon!

**Comment by zoepage** [comment]
Is this still an issue @nj4710 ?

**Comment by nj4710** [comment]
I tested this again on chrome. It works fine for me. Probably @miketaylr had some problems.

**Comment by zoepage** [comment]
Thanks. Closing. :)

**Comment by miketaylr** [comment]
> Probably @miketaylr had some problems.

This is usually true.

**Comment by miketaylr** [comment]
(also, thanks for testing again!)
