### ISSUE TITLE
[package.json] `npm run backend-install` missing

### ISSUE THREAD

**Issue by zoepage** [webcompat/webcompat.com#1485]
In https://github.com/webcompat/webcompat.com/blob/master/package.json#L60 we're trying to call a script called `backend-install`, but after checking the history, I saw it was never defined.

What was the purpose and do we need it?

**Comment by karlcow** [comment]
@magsout Probably for the answer.

Looking at the blame, it was introduced by #965 by @magsout 
https://github.com/webcompat/webcompat.com/blame/master/package.json#L60

**Comment by magsout** [comment]
@zoepage good catch.

Hum honestly, I don't remember why I writed this line. But, I guess, we don't need it.

**Comment by zoepage** [comment]
Cool, I'll send a PR.
