### ISSUE TITLE
The Contribute button remains highlighted after tapping it

### ISSUE THREAD

**Issue by softvision-sergiulogigan** [webcompat/webcompat.com#1490]
**Environment:**
Browser / Version: Firefox 52.0 Release (Mobile), Firefox Mobile Nightly 55.0a1 (2017-04-07) (Mobile), Chrome (Mobile) 56.0.2924.87.
Operating System: Android

**Steps to Reproduce:**
1. Navigate to: https://webcompat.com
2. Tap the Contribute button.
3. Scroll back to the top of the page. Observe the Contribute button.

**Expected Behavior:**
The Contribute button is not highlighted.

**Actual Behavior:**
The Contribute button is highlighted.

**Notes:**
1. Screenshot attached.
![screenshot_2017-04-07-11-35-02](https://cloud.githubusercontent.com/assets/16573771/24792622/7954fcfe-1b87-11e7-9224-783f1e9ce877.png)

sv;

**Comment by miketaylr** [comment]
Interesting, thanks for the report @softvision-sergiulogigan. 

@magsout something you can take a look at?

**Comment by magsout** [comment]
@miketaylr sure

**Comment by zoepage** [comment]
This will be fixed by http://webcompat.github.io/design/ and is already implemented.
