### ISSUE TITLE
The page can be scrolled left/right

### ISSUE THREAD

**Issue by softvision-sergiulogigan** [webcompat/webcompat.com#1491]
**Environment:**
Browser / Version: Firefox 52.0 Release (Mobile), Firefox Mobile Nightly 55.0a1 (2017-04-07) (Mobile), Chrome (Mobile) 56.0.2924.87.
Operating System: Android

**Steps to Reproduce:**
1. Navigate to: https://webcompat.com
2. Swipe right and left.

**Expected Behavior:**
Nothing happens.

**Actual Behavior:**
The page can be scrolled.

**Notes:**
1. Screenshot attached.

sv;
![screenshot_2017-04-07-11-49-06](https://cloud.githubusercontent.com/assets/16573771/24792884/7f5a0b98-1b88-11e7-8e68-50bde949d14a.png)

**Comment by miketaylr** [comment]
@magsout something you can take a look at?

**Comment by magsout** [comment]
@miketaylr sure

**Comment by magsout** [comment]
The bug is due to the overflow of SVG. I made a small fixed and pushed a PR

**Comment by magsout** [comment]
it would be a good idea if we can remove background SVG and icon font and replace all by inline SVG https://github.com/webcompat/webcompat.com/issues/899
