### ISSUE TITLE
[BUG] labels - layout is mixed up

### ISSUE THREAD

**Issue by zoepage** [webcompat/webcompat.com#1493]
After the refactor of the labels, the layout seems messed up when the label box merges into the main box and I scroll. Can be seen better below.

FF 52.0.2, OSX 10.12.2 (but also in Chrome  57.0.2987). 

![scroll_bug](https://cloud.githubusercontent.com/assets/562354/24828469/00d00508-1c5e-11e7-81a8-48314a863326.gif)

@magsout If you have time and worked on this, would you like to take care of it? Thanks!

**Comment by magsout** [comment]
@zoepage good catch 👍 sending a PR, thanks.
