### ISSUE TITLE
Incorrect position of “Share on Facebook/Twitter” buttons after reporting an issue

### ISSUE THREAD

**Issue by softvision-oana-arbuzov** [webcompat/webcompat.com#1499]
Browser / Version: Chrome 56.0.2924, Firefox 52.0.2 
Operating System: Windows 10 Pro

**Prerequisites:**
A new issue was found/encountered.

**Steps to Reproduce:**
1. Navigate to: https://webcompat.com.
2. Tap “Report a bug” and type in the required information.
3.  Report the issue and observe “Share on Facebook/Twitter” buttons displayed.

**Expected Behavior:**
“Thanks for reporting an issues!” section is larger.

**Actual Behavior:**
The buttons are not fully contained in the “Thanks for reporting an issues!” section.

**Notes:**
1. Reproducible also on Release 52.0.2 and Chrome 56.0.2924.
2. Screenshot attached.

**Watchers:**
@softvision-sergiulogigan
@softvision-oana-arbuzov

sv; 

![shareonfb_twitter](https://cloud.githubusercontent.com/assets/12184325/24855914/abf794ee-1deb-11e7-8028-335853dda6e0.png)

**Comment by magsout** [comment]
thanks @softvision-oana-arbuzov .

The box at right isn't necessary. We need to remove it.

**Comment by magsout** [comment]
There is two box because of this target https://github.com/webcompat/webcompat.com/blob/master/webcompat/static/js/lib/flash-message.js#L60

There is two element with this className in the DOM
