### ISSUE TITLE
New sidebar is broken on mobile

### ISSUE THREAD

**Issue by denschub** [webcompat/webcompat.com#1501]
The new sidebar is `position: sticky` on mobile as well, thus overlaying all contents:

![screenshot_20170410-222013](https://cloud.githubusercontent.com/assets/344777/24880816/13840ab6-1e3c-11e7-9877-5cd946fa7ec9.png)

It probably should just scroll away on mobile.

/cc @magsout

**Comment by magsout** [comment]
thanks @denschub . It fixed by https://github.com/webcompat/webcompat.com/pull/1495

I'll ask @miketaylr if he can deploy on production

**Comment by miketaylr** [comment]
Ah yeah, let's deploy right now.

**Comment by magsout** [comment]
thanks @miketaylr <3

**Comment by denschub** [comment]
Oh, I didn't know there was an issue open already and I wasn't able to find it. 🙈

Sorry. :)

**Comment by magsout** [comment]
@denschub ❤️
