### ISSUE TITLE
[layout] text without space is not broken.

### ISSUE THREAD

**Issue by karlcow** [webcompat/webcompat.com#1502]
Go to https://webcompat.com/issues/5572

```html
<ol>
<li>Error page is displayed javascript:%20{%20var%20vid%20=%20document.getElementById('video_1943544786');%20if%20(firstTime)%20{vid.load();%20firstTime%20=%20false;}%20if%20(vid.paused)%20vid.play();%20else%20vid.pause();%20}</li>
<li>Not reproducible on the Firefox 52.0 Release and Chrome (Mobile) 57.0.2987.132.</li>
<li>Screenshot attached.</li>
</ol>
```

![capture d ecran 2017-04-11 a 10 59 17](https://cloud.githubusercontent.com/assets/505230/24889671/4021ac58-1ea6-11e7-80ce-630f20409378.png)

Probably something along `word-wrap` to add.

```css
.wc-Markdown li {
	margin-bottom: 1em;
	word-wrap: break-word;
}
```

After this.

![capture d ecran 2017-04-11 a 11 03 34](https://cloud.githubusercontent.com/assets/505230/24889712/8caaed1e-1ea6-11e7-846a-6773e6af5867.png)

**Comment by karlcow** [comment]
Added info after hitting return to early.

**Comment by apoorvasingh17** [comment]
Hi. Can I take this up?

**Comment by underscoredotspace** [comment]
Hi @karlcow. Is there any reason not to add the `word-wrap: break-word` rule to the `.wc-Markdown *` selector as opposed to just covering the LI element?

**Comment by zoepage** [comment]
Sorry, we should close this big as there is a big refactor going on right now which already solved this issue.

But feel free to grab another starter issue with the label scope: refactor @underscoredotspace

**Comment by underscoredotspace** [comment]
Ah, that's fine @zoepage. I only checked this out as I've just made a similar fix elsewhere that wasn't quite as straight-forward. 

Looks like there's plenty more to work on 🙂
