### ISSUE TITLE
Remove query-params.js file

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat.com#1505]
This code has never been actually used. So lets remove it.

(FTR, it has some great ideas in it, possibly something we want to revisit during a refactor).

https://github.com/webcompat/webcompat.com/blob/master/webcompat/static/js/lib/models/query-params.js

**Comment by cch5ng** [comment]
starting work on this by:

- [ ] moving the file contents to a wiki page with JS refactor tasks
https://github.com/webcompat/webcompat.com/wiki/Z-Intern-Refactor-Tasks-(Sum-2017)
- [ ] removing the file from the code
