### ISSUE TITLE
Upgrade Prettier to 1.0

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat.com#1506]
1.0 was just released: http://jlongster.com/prettier-1.0

**Comment by miketaylr** [comment]
(1.1.0 is the latest, that was fast...)

**Comment by magsout** [comment]
👍

**Comment by magsout** [comment]
hum under the wood, there is a awesome option calls `--no-semi (#1129)`

**Comment by miketaylr** [comment]
> hum under the wood, there is a awesome option calls --no-semi (#1129)

Are you in favor of having no semicolons? I think that might be a tough sell 😆

**Comment by magsout** [comment]
>Are you in favor of having no semicolons?

yuip ;)

**Comment by karlcow** [comment]
I'm no JS developers. But from a beginner perspective, I find it easier to read when semi-colons are here. It helps me understand where are the limits of a block. The voice of the newbie ;)
