### ISSUE TITLE
Use whitelist for `isReportableURL` (rather than blacklist)

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat.com#1508]
Rather than check that we're not on some schemes, we should check that we're either looking at a URI that is either `http` or `https`. 

See https://github.com/webcompat/webcompat.com/blob/master/webcompat/static/js/lib/bugform.js#L227-L236 for where this code lives.

http://searchfox.org/mozilla-central/source/browser/extensions/webcompat-reporter/content/TabListener.jsm#47-49 might serve as some inspiration for what to do here (but we won't be able to use the ES6 stuff by default).

**Comment by MynahMarie** [comment]
@miketaylr I’d like to work on this for my outreachy contribution!

If it's ok for me to work on this, can you please give me a bit more clarification on this issue? If I understand correctly, this would be about modifying the function located at: https://github.com/webcompat/webcompat.com/blob/master/webcompat/static/js/lib/bugform.js#L270 and include an http/https check (the link provided for inspiration leads to a 404...) ?

**Comment by miketaylr** [comment]
@MynahMarie Yep! Sounds good. Also yeah, I guess that code did disappear... :)

https://searchfox.org/mozilla-central/source/browser/extensions/webcompat-reporter/content/WebCompatReporter.jsm#55 should give an idea of what we want.

**Comment by miketaylr** [comment]
This got fixed!
