### ISSUE TITLE
Double "thanks" flash message?

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat.com#1510]
Haven't dug into this yet, but it looks goofy. :clown_face: 

STR: 
1. report new bug (locally, at least)

<img width="1681" alt="screen shot 2017-04-14 at 3 00 57 pm" src="https://cloud.githubusercontent.com/assets/67283/25054577/8e1357fc-2123-11e7-8638-6b19255bdb10.png">

I think it might be here, if we use that class in more than one place:

https://github.com/webcompat/webcompat.com/blob/master/webcompat/static/js/lib/flash-message.js#L60

@magsout maybe there's a better class we can use to "anchor" the flash message?

**Comment by magsout** [comment]
@miketaylr yes, you're right.

@softvision-oana-arbuzov already opened a bug here https://github.com/webcompat/webcompat.com/issues/1499

**Comment by miketaylr** [comment]
whooops 🙈

**Comment by magsout** [comment]
@miketaylr ❤️
