### ISSUE TITLE
Reported type incorrect for some media error reports

### ISSUE THREAD

**Issue by adamopenweb** [webcompat/webcompat.com#1516]
There are some issues being tagged as "reported_with: web" when they are coming from media decode errors. 

[This one](https://github.com/webcompat/web-bugs/issues/5765) is anonymous:
```
<!-- @reported_with: web -->
```
but also contains in the description:
```
Technical Information:
Error Code: NS_ERROR_DOM_MEDIA_FATAL_ERR (0x806e0005)
{{snip}}
```

[Another example](https://github.com/webcompat/web-bugs/issues/5879) where the account is signed in.

**Comment by adamopenweb** [comment]
@squelart what URLs are you sending for the media errors?

**Comment by squelart** [comment]
@adamopenweb Currently the URL is something like:
https://webcompat.com/issues/new?url=URL&problem_type=video_bug&src=media-decode-error&details=TECH
(I will be adding 'label=type-media' in the next few days)

IIRC the "reported_with" tag comes from 'src' in the URL, right? It's hard-coded to be "media-decode-error" when the user clicks on "Report site issue" from the decode-error notification bar [1], so I'm not sure how it could be different.

Would you be able to access the web server logs, and see the full URL for the page that was used to report the issue?

If you want to try it yourself, launch a recent Firefox Nightly (or a local build), navigate to [2] and click on 'Download the attachment'. After attempting to play that file, a drop-down notification should appear; click on "Report Site Issue".
Good luck!

[1] http://searchfox.org/mozilla-central/source/browser/base/content/browser-media.js#350
[2] https://bugzilla.mozilla.org/attachment.cgi?id=8630560&action=edit

**Comment by adamopenweb** [comment]
Thanks!

@miketaylr: I looked up the request on GA for the bug that didn't assign properly (5765):
```
/issues/new?url=https://www.amazon.com/gp/video/detail/B06WWLT84P?ref_=aiv_dp_season_select&problem_type=video_bug&src=media-decode-error&details=Technical+Information: Error+Code:+NS_ERROR_DOM_MEDIA_FATAL_ERR+(0x806e0005) Details:+class+mozilla::ipc::IPCResult+__cdecl+mozilla::gmp::ChromiumCDMParent::RecvDecodeFailed(const+unsigned+int+&):+ChromiumCDMParent::RecvDecodeFailed Resource:+blob:https://www.amazon.com/26ebc0fa-0c1b-436a-ab0e-8edc715c0405=
```

And here's one that worked (5781):
```
/issues/new?url=http://www.mtv.fi/sport/f1/uutinen/artikkeli/pilasi-aika-ajoni-verstappen-manasi-massaa/6392386&problem_type=video_bug&src=media-decode-error&details=Technical+Information: Error+Code:+NS_ERROR_DOM_MEDIA_FATAL_ERR+(0x806e0005) Details:+class+mozilla::ipc::IPCResult+__cdecl+mozilla::gmp::ChromiumCDMParent::RecvDecodeFailed(const+unsigned+int+&):+ChromiumCDMParent::RecvDecodeFailed Resource:+blob:http://www.mtv.fi/10c784af-11c9-4b0f-becd-6fc005a40ccf=
```

Both have "&src=media-decode-error". 

I noticed both example bugs I listed in description of this report have URLs with query strings. Maybe that's borking it?

**Comment by miketaylr** [comment]
> I noticed both example bugs I listed in description of this report have URLs with query strings. Maybe that's borking it?

ooh, that's entirely possible. 🐛 🐞

**Comment by miketaylr** [comment]
Hmm, logging out `request.param` and it looks a bit... weird.

```
ImmutableMultiDict([
('url', u'https://www.amazon.com/gp/video/detail/B06WWLT84P?ref_=aiv_dp_season_select'), 
('src', u'media-decode-error'), 
('): ChromiumCDMParent::RecvDecodeFailed Resource: blob:https://www.amazon.com/26ebc0fa-0c1b-436a-ab0e-8edc715c0405', u''), 
('details', u'Technical Information: Error Code: NS_ERROR_DOM_MEDIA_FATAL_ERR (0x806e0005) Details: class mozilla::ipc::IPCResult __cdecl mozilla::gmp::ChromiumCDMParent::RecvDecodeFailed(const unsigned int '), 
('problem_type', u'video_bug')])
```

**Comment by miketaylr** [comment]
Ah, I see. It's choking in the details stack.

That said, `request.param.get('src')` is what I expect it to be, and we parse the `details` param client-side in JS, so maybe not where the bug lives.

**Comment by squelart** [comment]
That RecvDecodeFailed function takes a `const uint32_t&`, so I'm guessing the '&' is causing trouble in your example above! URLSearchParams encodes '&' as "%26".

Though trying https://webcompat.com/issues/new?url=URL&problem_type=video_bug&src=media-decode-error&details=const+unsigned+int+%26%29%3A+blah%0AResource%3A+foo seems to work fine. :-S

**Comment by miketaylr** [comment]
Yeah, I'm not convinced that's where the bug is just yet. Will keep poking at it.

**Comment by karlcow** [comment]
@miketaylr 
this indeed not good. What did you use to generate this one?

```
ImmutableMultiDict([
('url', u'https://www.amazon.com/gp/video/detail/B06WWLT84P?ref_=aiv_dp_season_select'), 
('src', u'media-decode-error'), 
('): ChromiumCDMParent::RecvDecodeFailed Resource: blob:https://www.amazon.com/26ebc0fa-0c1b-436a-ab0e-8edc715c0405', u''), 
('details', u'Technical Information: Error Code: NS_ERROR_DOM_MEDIA_FATAL_ERR (0x806e0005) Details: class mozilla::ipc::IPCResult __cdecl mozilla::gmp::ChromiumCDMParent::RecvDecodeFailed(const unsigned int '), 
('problem_type', u'video_bug')])
```
The part which is not good is this line:

```
(
    '): ChromiumCDMParent::RecvDecodeFailed Resource: blob:https://www.amazon.com/26ebc0fa-0c1b-436a-ab0e-8edc715c0405', 
    u''
), 
```

There are a couple of things I don't like with this.

**Comment by karlcow** [comment]
@miketaylr do we still have this kind of reports? From the top of my head I think we stopped these.

**Comment by miketaylr** [comment]
> From the top of my head I think we stopped these.

Yes, we don't get these anymore.
