### ISSUE TITLE
The label selection list should open from under the clicked button

### ISSUE THREAD

**Issue by softvision-sergiulogigan** [webcompat/webcompat.com#1517]
**Environment:**
Browser / Version: Chrome 57.0.2987.133 (Desktop), Firefox 52.0.1 Release (Desktop)
Operating System: Windows 10

**Steps to Reproduce:**
1. Navigate to: https://webcompat.com/issues/5899 (for example).
2. Click the gear icon next to "Labels".

**Expected Behavior:**
The label selection list is opened from under the "Labels" string.

**Actual Behavior:**
The label selection list should open from under the clicked button.

**Notes:**
1. Screenshot attached.

sv;
![screenshot_1](https://cloud.githubusercontent.com/assets/16573771/25129179/8cbce344-2445-11e7-8383-dbc36e10bdbf.png)

**Comment by magsout** [comment]
@softvision-sergiulogigan thanks, you're right

**Comment by zoepage** [comment]
I don't feel like this is a bug as it is popping up under the "label" label, which sums up the list?
But I see, improvements can be made towards UX.

How about we take away the triangle from the list, so it points nowhere?

**Comment by zoepage** [comment]
this is fixed in refactor
