### ISSUE TITLE
The label selection button is no longer displayed after setting a label

### ISSUE THREAD

**Issue by softvision-sergiulogigan** [webcompat/webcompat.com#1520]
**Environment:**
Browser / Version: Chrome 57.0.2987.133 (Desktop), Firefox 52.0.1 Release (Desktop)
Operating System: Windows 10

**Steps to Reproduce:**
1. Navigate to: https://webcompat.com/issues/5899 (for example).
2. Click the gear icon next to "Labels".
3. Select a label.
4. Click the "Save & Close" button. Observe the behavior.

**Expected Behavior:**
The label is set, and the label selection button is still displayed.

**Actual Behavior:**
The label is set, but the label selection button is no longer displayed.

**Notes:**
1. Workaround: Refresh the page.

sv;

**Comment by miketaylr** [comment]
Ah yeah, nice reminder to fix this. Dupe of #1204.
