### ISSUE TITLE
The label selection popup should be redesigned

### ISSUE THREAD

**Issue by softvision-sergiulogigan** [webcompat/webcompat.com#1522]
**Environment:**
Browser / Version: Chrome 57.0.2987.133 (Desktop), Firefox 52.0.1 Release (Desktop)
Operating System: Windows 10

**Steps to Reproduce:**
1. Navigate to: https://webcompat.com/issues/5899 (for example).
2. Click the gear icon next to "Labels".

**Expected Behavior:**
The checkbox does not overlap the label color.

**Actual Behavior:**
The checkbox overlaps the label color.

**Notes:**
1. Screenshot attached.

sv;
![screenshot_1](https://cloud.githubusercontent.com/assets/16573771/25338586/6c0b0d16-2908-11e7-9177-9474ca260666.png)

**Comment by miketaylr** [comment]
This is what I see on Mac -- @magsout do you have a way to test in Windows to verify?

<img width="262" alt="screen shot 2017-04-24 at 5 18 12 pm" src="https://cloud.githubusercontent.com/assets/67283/25344309/08c0c80e-2912-11e7-9af4-1869472d9f90.png">

**Comment by karlcow** [comment]
Tested on Firefox 53 (aka latest release production)
![capture d ecran 2017-04-25 a 08 28 30](https://cloud.githubusercontent.com/assets/505230/25371464/3a25bc86-2991-11e7-87bb-7d190e618724.png)

no issue.

**Comment by karlcow** [comment]
In Safari Tech Preview. Release 28 (Safari 10.2, WebKit 12604.1.17)

![capture d ecran 2017-04-25 a 08 31 10](https://cloud.githubusercontent.com/assets/505230/25371534/94850164-2991-11e7-989d-2be95a546346.png)

In Opera Blink. 45.0.2552.225 
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.41 Safari/537.36 OPR/45.0.2552.225 (Edition beta)


![capture d ecran 2017-04-25 a 08 33 53](https://cloud.githubusercontent.com/assets/505230/25371629/f3c3708e-2991-11e7-9b27-5c79f21d6090.png)

**Comment by magsout** [comment]
@miketaylr 

In 
Mozilla/5.0 (Windows NT 10.0; WOW64; rv:53.0) Gecko/20100101 Firefox/53.0
Windows 10
![capture d ecran 2017-04-25 a 21 25 08](https://cloud.githubusercontent.com/assets/1997108/25403787/d683d0d8-29fd-11e7-9b7f-7d8e59c079b7.png)

**Comment by zoepage** [comment]
@softvision-sergiulogigan is this what you'd suggest?

![lables](https://cloud.githubusercontent.com/assets/562354/25420081/a200ac56-2a56-11e7-939b-4923ce713d39.png)

**Comment by softvision-sergiulogigan** [comment]
Either this, or maybe the current version with the checkboxes on the right side.

**Comment by zoepage** [comment]
@softvision-sergiulogigan 
> maybe the current version with the checkboxes on the right side.

Not sure what you mean by this. Could you explain this a bit more? Thanks!

**Comment by softvision-sergiulogigan** [comment]
Sure, but sorry for my bad Paint skills :P
![screenshot_1](https://cloud.githubusercontent.com/assets/16573771/25424863/90fd5582-2a72-11e7-8e3b-0d189d9418b8.png)

**Comment by zoepage** [comment]
I'll remove the `type:bug` label as this seems more like a design suggestion then a bug.

**Comment by zoepage** [comment]
closing in favor of https://github.com/webcompat/design/pull/81
