### ISSUE TITLE
Switching main font from 'Helvetica Neue' to 'Open Sans'

### ISSUE THREAD

**Issue by zoepage** [webcompat/webcompat.com#1530]
As "Helvetica Neue" is just a system font for OSX, I'd like to suggest to switch to ["Nunito Sans"](https://fonts.google.com/specimen/Nunito+Sans).
(Let's not talk about font performance or other things, as this is something we can discuss later, because those are issues we can definitely solve 🐱).

I also feel it would improve the readability of the site + make it feel more "round".

Here are some examples:
<img width="1341" alt="screen shot 2017-04-25 at 3 40 48 pm" src="https://cloud.githubusercontent.com/assets/562354/25388396/1fb13a96-29ce-11e7-8244-3d9126af0a15.png">
<img width="1240" alt="screen shot 2017-04-25 at 3 40 57 pm" src="https://cloud.githubusercontent.com/assets/562354/25388394/1f903030-29ce-11e7-8a44-9a974ba64282.png">
<img width="1270" alt="screen shot 2017-04-25 at 3 41 14 pm" src="https://cloud.githubusercontent.com/assets/562354/25388395/1f980c9c-29ce-11e7-8f17-2e591e914721.png">

What do you think?

**Comment by miketaylr** [comment]
@zoepage maybe if you send in a PR we can deploy it to staging to get a better feel. It's hard for me to judge based on screenshots (I might just be tired?).

**Comment by zoepage** [comment]
@miketaylr Sure, it will take a bit as the height of the font is different and that might change/break some layouts, I want to check first.

**Comment by karlcow** [comment]
One of the reasons I like a system font is that it removes a dependency on an external 3rd party service (and eventually yet another tracker). Personally it doesn't affect me, because I'm blocking `fonts.google.com` (no issue with speed and tracking from Japan once it is blocked), but I'm not sure we gain things for the project.

**Comment by zoepage** [comment]
@karlcow there are a lot of ways to solve performance issues and ways to implement. So, let's not talk about that right now. :)

Helvetica is no general system font, Arial is. Arial was not created for modern browsers / mobile devices and has a few pitfalls when it comes down to readability and small screensizes.

**Comment by magsout** [comment]
@zoepage good idea 👍 

@karlcow @zoepage what about https://css-tricks.com/snippets/css/system-font-stack/ ? I just mention it because @zoepage you talk about general system font. I would really like to see what your font do.

**Comment by zoepage** [comment]
@magsout the only one we could use from your list them would be http://font.ubuntu.com/ :)

**Comment by zoepage** [comment]
As the font will probably be a different one, I'll close this issue.

**Comment by zoepage** [comment]
![grid_poc](https://user-images.githubusercontent.com/562354/27057160-36ced792-4fcb-11e7-835c-3376d9d064b7.gif)

**Comment by zoepage** [comment]
After checking the mockups, we decided to go with it. This can be seen in the [Living Style Guide](https://github.com/webcompat/design)
