### ISSUE TITLE
add pagination in "all issues" list at bottom of list

### ISSUE THREAD

**Issue by zoepage** [webcompat/webcompat.com#1535]
http://localhost:5000/issues?page=1&per_page=50&state=open&stage=all&sort=created&direction=desc 

Pagination `prev` && `next` is above the list.
<img width="1289" alt="screen shot 2017-04-26 at 11 50 25 am" src="https://cloud.githubusercontent.com/assets/562354/25428729/eb822cc2-2a76-11e7-8da9-84c5d9790017.png">

We should also add it below the list, so you do not have to scroll up when you want to see the next 50 issues.
<img width="1259" alt="screen shot 2017-04-26 at 11 50 35 am" src="https://cloud.githubusercontent.com/assets/562354/25428730/eb8266ce-2a76-11e7-934c-5351b5f442ff.png">

**Comment by zoepage** [comment]
@magsout Is this something you'd like to work on? :)

**Comment by magsout** [comment]
@zoepage sure 👍
