### ISSUE TITLE
No results were found with a q param and state at all

### ISSUE THREAD

**Issue by magsout** [webcompat/webcompat.com#1536]
STR:

  Goto: https://webcompat.com/issues?page=1&per_page=50&state=all&stage=all&sort=created&direction=desc
 click on a label like: `firefox-mobile`

Expected Results:
Display related bugs

Actual Results:
Sorry, no results were found.

**Comment by magsout** [comment]
Related to https://github.com/webcompat/webcompat.com/issues/1023

When you 're login you have 0 result, when you are not log in, you have an error as mentioned inhttps://github.com/webcompat/webcompat.com/issues/1023

**Comment by magsout** [comment]
I don"t see anything related to JS, so maybe the bug is caused by something wrong with /api python ?

**Comment by miketaylr** [comment]
Hmm, seems like we broke something. :(

**Comment by karlcow** [comment]
## Loggedin Scenario

1. https://webcompat.com/issues?page=1&per_page=50&state=all&stage=all&sort=created&direction=desc
2. click on `firefox-mobile` https://webcompat.com/issues?q=label:browser-firefox-mobile
3. This is converted into https://webcompat.com/api/issues/search?page=1&per_page=50&state=all&stage=all&sort=created&direction=desc&q=label%3Abrowser-firefox-mobile
4. it returns

```json
{
  "total_count": 0,
  "incomplete_results": false,
  "items": [

  ]
}
```

Note that the same issue is happening if you just type `amazon` in the search area on this page.
https://webcompat.com/api/issues/search?page=1&per_page=50&state=all&stage=all&sort=created&direction=desc&q=amazon


I will check locally what is happening.
(Removing the non interesting stuff)

``` 
127.0.0.1 - - [27/Apr/2017 13:52:13] "GET /issues?page=1&per_page=50&state=all&stage=all&sort=created&direction=desc HTTP/1.1" 200 -
…
127.0.0.1 - - [27/Apr/2017 13:52:16] "GET /api/issues?page=1&per_page=50&state=all&stage=all&sort=created&direction=desc HTTP/1.1" 200 -
…
127.0.0.1 - - [27/Apr/2017 13:52:41] "GET /api/issues/search?page=1&per_page=50&state=all&stage=all&sort=created&direction=desc&q=label%3Abrowser-firefox HTTP/1.1" 200 -
```

OK. I thought it was a parameter badly encoded aka `label%3Abrowser-firefox`

```
→ http GET "https://webcompat.com/api/issues/search?page=1&per_page=50&state=all&stage=all&sort=created&direction=desc&q=label%3Abrowser-firefox"
```
which gives

```http
HTTP/1.1 200 OK
Connection: keep-alive
Content-Encoding: gzip
Content-Security-Policy-Report-Only: default-src 'none'; connect-src 'self'; font-src 'self'; img-src 'self' https://www.google-analytics.com https://*.githubusercontent.com data:; manifest-src 'self'; script-src 'self' 'unsafe-eval' 'unsafe-inline' https://www.google-analytics.com https://api.github.com; style-src 'self' 'unsafe-inline'; report-uri /csp-report
Content-Type: application/json
Date: Thu, 27 Apr 2017 11:56:17 GMT
Server: nginx/1.1.19
Strict-Transport-Security: max-age=31536000; includeSubDomains;
Transfer-Encoding: chunked
Vary: Accept-Encoding
X-Content-Type-Options: nosniff
X-Frame-Options: DENY
X-XSS-Protection: 1; mode=block
cache-control: no-cache
etag: None

{
    "incomplete_results": false, 
    "items": [], 
    "total_count": 0
}
```

but when we fix it manually:

```
→ http GET "https://webcompat.com/api/issues/search?page=1&per_page=50&state=all&stage=all&sort=created&direction=desc&q=label:browser-firefox"
```

it doesn't solve the issue

```http
HTTP/1.1 200 OK
Connection: keep-alive
Content-Encoding: gzip
Content-Security-Policy-Report-Only: default-src 'none'; connect-src 'self'; font-src 'self'; img-src 'self' https://www.google-analytics.com https://*.githubusercontent.com data:; manifest-src 'self'; script-src 'self' 'unsafe-eval' 'unsafe-inline' https://www.google-analytics.com https://api.github.com; style-src 'self' 'unsafe-inline'; report-uri /csp-report
Content-Type: application/json
Date: Thu, 27 Apr 2017 11:56:26 GMT
Server: nginx/1.1.19
Strict-Transport-Security: max-age=31536000; includeSubDomains;
Transfer-Encoding: chunked
Vary: Accept-Encoding
X-Content-Type-Options: nosniff
X-Frame-Options: DENY
X-XSS-Protection: 1; mode=block
cache-control: no-cache
etag: None

{
    "incomplete_results": false, 
    "items": [], 
    "total_count": 0
}
```

Let's see what is happening on the server side.  Basically how this query is translated before requesting Github.

https://github.com/webcompat/webcompat.com/blob/24ee62f09ce8e3b8f49781b459c964d0fd0df22e/webcompat/api/endpoints.py#L165

Everything so far seems ok.
```
MultiDict([('sort', u'created'), ('order', u'desc'), ('q', u'label:browser-firefox repo:webcompat/webcompat-tests state:all'), ('per_page', u'50'), ('page', u'1'), ('stage', u'all')])
```

**Comment by miketaylr** [comment]
@magsout this bug goes away when we land #1531, right? (We decided to kill the main "View all foo" dropdown).

**Comment by karlcow** [comment]
Following @miketaylr idea
Going to https://webcompat.com/issues and then clicking on a label it works.

On the all issues page this query is working
```
https://webcompat.com/issues?q=label:browser-chrome
```

On the page that @magsout mentions this is not working.
```
https://webcompat.com/issues?q=label:browser-firefox-mobile
```

AND if I directly enter the URI into the address bar
```
https://webcompat.com/issues?q=label:browser-firefox-mobile
```

is working. and

```
MultiDict([('sort', u'created'), ('order', u'desc'), ('q', u'label:browser-firefox-mobile repo:webcompat/webcompat-tests state:open'), ('per_page', u'50'), ('page', u'1'), ('stage', u'all')])
```

 So there is definitely something funky in terms of context.

**Comment by magsout** [comment]
>@magsout this bug goes away when we land #1531, right? (We decided to kill the main "View all foo" dropdown).

@miketaylr yes, it is.. I did't see this PR.

**Comment by magsout** [comment]
thanks @karlcow for your time and for all the tests you have done
