### ISSUE TITLE
New Content Structure for webcompat.com

### ISSUE THREAD

**Issue by zoepage** [webcompat/webcompat.com#1539]
After the work & research of the past few months, this is a proposal for a new content structure for webcompat.com. Please add your feedback or questions below. Happy to provide as much context as possible. (also the label [scope: content](https://github.com/webcompat/webcompat.com/labels/scope%3A%20content) could give a bit more context / ideas.)

After the structure is set, we will start a doc with all the content. The link will be posted below, so everyone is able to participate. <3

General related issues:
https://github.com/webcompat/webcompat.com/issues/1296
(Explicit related issues are next to the relevant topics.)

Home
- Intro
- Bug Form
- All Issues
- Intro to project

Dashboard (https://github.com/webcompat/webcompat.com/issues/1537 + https://github.com/webcompat/webcompat.com/issues/1418 + https://github.com/webcompat/webcompat.com/issues/1337)
- my activity
- (stats about open / closed bugs, types of bugs etc)

List of Issues

Issue detail

Contact (https://github.com/webcompat/webcompat.com/issues/1284)
- IRC
- Mailing list
- Twitter
- Blog
- Gitter / Slack (or other)

Screencasts ()
- Joy of Diagnose
- How to videos (https://github.com/webcompat/webcompat.com/issues/1149#issuecomment-284589695)

Contribute (https://github.com/webcompat/webcompat.com/issues/1149#issuecomment-240519586)
- Web Bugs
  - report
  - diagnose
  - outreach
- webcompat tools
    - Design / UX (http://webcompat.github.io/webcompat.com/)
    - webcompat.com (http://webcompat.com)
    - GoFast addon
    - automated testing
    - "report site issue" in Nightly
    - https://webcompat.com/tools/cssfixme
- community builder
  - writing (blog, NL, documentation)
  - speaking at events
  - organizing events
  - taking care of the community

About the project (https://github.com/webcompat/webcompat.com/issues/1149#issuecomment-284589695)
- What + Why of the project
- join the project 
- contributors (pics + bios)
- testimonials (https://github.com/webcompat/webcompat.com/issues/1309)
- success stories
- getting started (link to contribute or screencasts / https://github.com/webcompat/webcompat.com/issues/1149#issuecomment-284589695)
(- events)

(FAQ)

Resources
https://github.com/webcompat/webcompat.com/issues/1381

Private Policy
https://webcompat.com/privacy

CoC
https://www.mozilla.org/en-US/about/governance/policies/participation/

Metrics

**Comment by adamopenweb** [comment]
@zoepage This looks great!
It might be cool to have something on the main page that mentions people are regularly using webcompat.com. Something like "someone reported a bug 10 minutes ago" or maybe "130 people reported bugs this week", with a link to Metrics.

**Comment by zoepage** [comment]
@adamopenweb I'd love that. We should include that in the mockups.

**Comment by zoepage** [comment]
@miketaylr @karlcow @denschub @wisniewskit @lockettm 
What are your thoughts?

**Comment by miketaylr** [comment]
> webcompat tools

I think some of these are a bit too Firefox-centric to fit with the project (thinking of GoFaster, report site issue). We could remove those and add https://github.com/webcompat/webcompat-reporter-extensions. Or, we could just link to other related projects from other browsers as well?

**Comment by karlcow** [comment]
1. What is metrics?
2. Should the FAQ be in the about the project?
3. +1 to mike's comments about tools.
4. cssfixme doesn't show up in there https://webcompat.com/tools/cssfixme
5. in "writing (blog, NL, documentation)" what is NL?
6. what's the difference between "writing (**blog**, NL, documentation)" and "contact / blog"?
7. What's the difference between "Intro" and "Intro to the project" on Home.
8. The GoFastly landing page (Firefox) is cool but probably not on webcompat.com (all browsers)

How do we encourage other browser vendors to review this page? @TheWebJustWorks (Microsoft), Google, Apple, Opera, and others.

**Comment by zoepage** [comment]
@miketaylr 
> I think some of these are a bit too Firefox-centric to fit with the project (thinking of GoFaster, report site issue). We could remove those and add https://github.com/webcompat/webcompat-reporter-extensions. Or, we could just link to other related projects from other browsers as well?

I'd be happy to add more general tools as e.g. the webcompat-linter or others, also from other related projects. If you have anything specific in mind, please feel free to post / add links in here. :)

@karlcow 
> What is metrics?

https://github.com/webcompat/webcompat.com/issues/1539#issuecomment-297704386

> Should the FAQ be in the about the project?

The main purpose of a FAQ is to answer questions in a quick way, right? So, I feel like we should make it as accessible as possible for contributors. Adding it to "about the project" would add at least one click, which would make it less present. (That is my main reason why it's separate. Happy to combine it with "Resources" and prompt both in the link like "FAQ / Resources").

> cssfixme doesn't show up in there https://webcompat.com/tools/cssfixme

Added.

> in "writing (blog, NL, documentation)" what is NL?

NL = Newsletter

> what's the difference between "writing (blog, NL, documentation)" and "contact / blog"?

When you take a look above the line, you see the context:
"community builder > writing (blog, NL, documentation)" One describes a role a contributor can have. The other describe the content for "contact" or "blog".

>What's the difference between "Intro" and "Intro to the project" on Home.

"Intro" on the index is a very short 3 line intro about the project. "Intro to the project" is a proper introduction about the why's and how's of the project in the "about" page.

> The GoFastly landing page (Firefox) is cool but probably not on webcompat.com (all browsers)

I like to mention the GoFastly addon in "tools" to make people aware it exists and maybe others will either follow the approach or understand the bigger issue and help to fix things.

About the landing page, I feel like it should be on the site, but not linked in the navigation. People would "find" it by following the URL from the console prompt (see https://github.com/webcompat/webcompat.com/issues/1534 for more info).

**Comment by miketaylr** [comment]
(just a note here that we also have the Report Issue endpoint (/issues/new) which is separate from the bugform on the homepage, although it shares the same template partials and bugform.js code -- not sure if it actually matters for this issue tho!)

**Comment by karlcow** [comment]
@zoepage 

>> The GoFastly landing page (Firefox) is cool but probably not on webcompat.com (all browsers)
> I like to mention the GoFastly addon in "tools" to make people aware it exists and maybe others will either follow the approach or understand the bigger issue and help to fix things.

Who is "others"? if others are browser vendors, they are well aware of the techniques. In fact GoFastly is partly a copy of the Opera BrowserJS model. Microsoft has Compatibility View predating this too for a long time. 😁  This is similar to the #1534

Talking about the tools/strategies that different browser vendors have put in place is ok.
Having an official landing page is **not ok** and should be done on MDN or somewhere on mozilla.org.

**Comment by lockettm** [comment]
Looks great. I like Mike's idea of including resources from other browsers. For example, listing [docs](https://developer.chrome.com/devtools) or [tutorials](https://www.codeschool.com/courses/discover-devtools) for both Chrome and Firefox dev tools.

**Comment by zoepage** [comment]
> (just a note here that we also have the Report Issue endpoint (/issues/new) which is separate from the bugform on the homepage, although it shares the same template partials and bugform.js code -- not sure if it actually matters for this issue tho!)

I agree. When we wrap up the structure for content (what this issue is about), we'll create a sitemap with the links and add it there. Thanks for pointing it out @miketaylr .

> Having an official landing page is not ok and should be done on MDN or somewhere on mozilla.org.

We've agreed in the discussion in #1534 to not add the AddOn, So I'll edit the first comment and take it out.

**Comment by magsout** [comment]
looks good 👍

**Comment by zoepage** [comment]
As the main structure is set, I've created a concept for the index page.
Following a mock-up, I'd love to share with you.

The context can be found here: https://docs.google.com/document/d/1uCBbUx7TAZh_nIYn7U18Npceo1xQl_6j36BV-cmy1_g/edit?usp=sharing
Please note, this document is a `work in progress`.

![img_20170516_201429](https://cloud.githubusercontent.com/assets/562354/26122844/2906bf06-3a79-11e7-972d-56172a7b8e4e.jpg)

**Comment by zoepage** [comment]
Preview for 1x1 text module. Headline gets icons to appear more friendly and styled.
Font changed to Open Sans.

![desktop hd](https://cloud.githubusercontent.com/assets/562354/26678219/c19bbd22-46cf-11e7-8a34-dad1f7929499.png)
![mobile portrait](https://cloud.githubusercontent.com/assets/562354/26678220/c1a4afa4-46cf-11e7-8da6-080c4a6b3039.png)
![tablet portrait](https://cloud.githubusercontent.com/assets/562354/26678221/c1a9930c-46cf-11e7-9445-c808d8e4317e.png)

**Comment by karlcow** [comment]
* not a fan of the branches (visual annoyance to my eyes)
* The rest is fine, but would need to see in context.

**Comment by zoepage** [comment]
@karlcow The branches will have a different visual weight, when they are in the context as they will appear smaller plus there will be more content distracting from them. So, maybe we'll check then again?
