### ISSUE TITLE
Request/Proxy Model Graph

### ISSUE THREAD

**Issue by karlcow** [webcompat/webcompat.com#1540]
Having a request/proxy model graph can be useful for contributors to understand how everything is working.

When I click 

https://webcompat.com/issues/1

What's happening?

**Comment by karlcow** [comment]
See https://github.com/webcompat/webcompat.com/issues/1336#issuecomment-290021432
for a partial textual explanation.

**Comment by karlcow** [comment]
See Also https://github.com/webcompat/webcompat.com/wiki/Architecture

**Comment by zoepage** [comment]
Is this in progress or done @karlcow ? :)

**Comment by karlcow** [comment]
Probably missing a couple of things.

**Comment by zoepage** [comment]
Shall we add a deadline or something?

**Comment by karlcow** [comment]
by the end of Q4 2017.

**Comment by karlcow** [comment]
> by the end of Q4 2017.

arf…

* https://github.com/webcompat/webcompat.com/wiki/Architecture
* https://github.com/webcompat/webcompat.com/issues/2525#issuecomment-403676858

Done. https://github.com/webcompat/webcompat.com/wiki/Architecture/_compare/d5e768e0c70a8d45b458a096815b167092a4a774...af5b8e8417bd61310b7729b3f015d9a5d0f6c77c
