### ISSUE TITLE
401 on changing labels

### ISSUE THREAD

**Issue by zoepage** [webcompat/webcompat.com#1543]
When I try to set a label on the issue page, I get `There was an error setting labels.` on every branch. It looks like this just happens to me as @magsout and @denschub tried it and it works.

I am logged in, am able to comment on an issue. It happens on various issues, with no label / labels already set... My config did not change, recreated a new app key. Still not working.

@karlcow @miketaylr Do you have any idea about what it could be? Any hints are appreciated.

**Comment by karlcow** [comment]
The message comes from https://github.com/webcompat/webcompat.com/blob/2e9f2444a789d39873e42d2292f150fc87b98845/webcompat/static/js/lib/models/issue.js#L128-L139

when labels are saved.
I can't reproduce myself. It is working for me. Was it in a specific version of Firefox? with addons? Or maybe just bad luck at the moment?

**Comment by zoepage** [comment]
The POST fails and the params are passed through correctly. 

Chrome + Firefox are failing (for local setup). No specific addons. It looks like an auth issue with Github. 

Did anyone of you change anything?

**Comment by karlcow** [comment]
not that I know. Did you reach your API limit?

**Comment by karlcow** [comment]
At least we didn't change anything that would break a key for you and not for the others.

```
(webcompatcom) 17:33:16 ~/code/webcompat.com
→ git checkout master
Switched to branch 'master'
Your branch is up-to-date with 'webcompat/master'.
(webcompatcom) 17:33:21 ~/code/webcompat.com
→ git fetch webcompat
(webcompatcom) 17:33:29 ~/code/webcompat.com
→ git merge webcompat/master
Already up-to-date.
(webcompatcom) 17:33:40 ~/code/webcompat.com
→ git log --oneline | head -5
eefc096 Merge pull request #1531 from webcompat/issues/1527/1
de711fc Merge pull request #1511 from webcompat/issues/1491
add3d7d Merge pull request #1532 from webcompat/issues/1526/1
a572e80 Issue #1491 - added more space on small screen between these icons
4717f89 Issue #1626. Split up CONTRIBUTING.md to multiple files.
(webcompatcom) 17:33:59 ~/code/webcompat.com
→ python run.py
('secrets', '/Users/karl/code/webcompat.com')
 * Running on http://localhost:5000/ (Press CTRL+C to quit)
 * Restarting with stat
('secrets', '/Users/karl/code/webcompat.com')
```

I could publish
* a bug report
* add labels
* and leave  a comment

http://localhost:5000/issues/586
https://github.com/webcompat/webcompat-tests/issues/586


@zoepage your issue is from 13 hours ago and you say: 

> I am logged in, am able to comment on an issue. 

But the latest comments from you are 3 days old.
https://github.com/webcompat/webcompat-tests/issues?utf8=%E2%9C%93&q=is%3Aissue%20sort%3Aupdated-desc%20commenter%3Azoepage

Or do you test on another repo? Or is the issue 3 days old :) Trying to narrow the context.

**Comment by zoepage** [comment]
@karlcow I played around with the comments and also deleted a few of them.
Also set labels in the GH interface as well (worked) as well as in our interface (didn't work).

Rate limit seems ok.
```
X-RateLimit-Limit: 60
X-RateLimit-Remaining: 52
X-RateLimit-Reset: 1493639518
```

**Comment by miketaylr** [comment]
@zoepage I just revoked all user tokens from the local testing oauth app -- can you try to re-auth and see if the problem still exists?

**Comment by miketaylr** [comment]
(i kicked staging as well, for no real reason)

**Comment by zoepage** [comment]
@miketaylr thanks! Still failing :/

**Comment by miketaylr** [comment]
@zoepage what does https://github.com/webcompat/webcompat.com/blob/master/config/secrets.py.example#L40 say for you in secrets.py? PM me if you'd like it to remain a secret :P

**Comment by zoepage** [comment]
Interesting... I am also not able to close the issue.

**Comment by karlcow** [comment]
so everything which requires admin credentials basically and does not go through webcompat-bot.

**Comment by karlcow** [comment]
Your repo in `secrets.py` is:

```
# Production GiHub Issues repo URI. Can be ignored for local testing.
if PRODUCTION:
    ISSUES_REPO_URI = ''
# Staging and Local instances use the same test repo
else:
    ISSUES_REPO_URI = os.environ.get('ISSUES_REPO_URI') or 'webcompat/webcompat-tests/issues'
```

**Comment by zoepage** [comment]
@karlcow yes.

**Comment by zoepage** [comment]
sometimes you just need `rm -rf webcompat.com` in your life... (and new credentials)
