### ISSUE TITLE
Pin the prettier version to specific version

### ISSUE THREAD

**Issue by magsout** [webcompat/webcompat.com#1548]
I think it would be necessary to block the prettier version in package.json to avoid errors like here https://github.com/webcompat/webcompat.com/pull/1538#issuecomment-298885812

The error is caused by a different version in the package.json. So every time we install prettier, or update all nodes module, we can cause an new error if there is a new update.

**Comment by miketaylr** [comment]
@magsout what do you mean by block?

https://github.com/webcompat/webcompat.com/blob/master/package.json#L43 has `^1.1.0` -- do you mean we pin to exactly a single version, so just `1.1.0`?

**Comment by magsout** [comment]
@miketaylr yes exactly.

**Comment by miketaylr** [comment]
Cool, +1.

**Comment by zoepage** [comment]
Fixed in https://github.com/webcompat/webcompat.com/commit/182e77ac0c4182f58661196624cf3d3b131b599f
