### ISSUE TITLE
[feature] type-media bugs - handling duplicates automagically

### ISSUE THREAD

**Issue by karlcow** [webcompat/webcompat.com#1551]
For certain domains, such as vk.com or yandex.ru in the category `type-media` we have a series of duplicates. A couple of them every day. It would make it easier for us to deal with them if we could triage them automagically.

This is just an idea on how we could maybe handle this.

1. An issue is reported with `type-media` label (we know when it's coming from the media reporting system)
2. It contains a specific Error Code and a specific domain name.
3. Check if the tuple (`domain_name`, `media_error_code`) is in the `type-media` duplicate cache list: `media_bugs_cache_list.txt`.
4. If yes
    - Remove `status-needstriage`
    - Add `status-duplicate`
    - Add comment with "closing as duplicate of `first_bug_number`"
    - option: Add comment on  `first_bug_number` with "`current_bug_number` is a duplicate"
    - Close the issue 
5. If No
    - Add a new line to `media_bugs_cache_list.txt` with the following information `domain_name`, `media_error_code`, `first_bug_number`
    - Remove `status-needstriage`
    - Add `status-needsdiagnosis`

This should remove some of our daily burden.

To be discussed: @adamopenweb @MDTsai some thoughts?

Unknown:
* Issues where type-media is added after the fact.
* Old issues do we create a batch processing script doing the above for old bugs we already received.

**Comment by MDTsai** [comment]
One concern is media file in different CDN server, but seems not happened till now. So I think this works.

**Comment by karlcow** [comment]
@MDTsai Thanks! Indeed that might influence the result. For example, for social networks, where external links are authorized.  That could be an additional check. 

I should download all the current data we have and see if we can have a better idea of the variability.

**Comment by karlcow** [comment]
@miketaylr Currently for the webhook, we are using the `/labeler` route which is adding two new labels: browser and needstriage.

(thinking out loud)

There are maybe three options:

* reusing `/labeler` route.  
 Probably modifying the name to be more generic and improving a bit more the logic in the code to be more versatile. The `if` cascade bothers me a bit. 
* <del>OR create a new route for the purpose of triaging type-media issues.  </del>
  How would that work? Can we assign more than one URL per webhook. Heading to the docs. Ah… so a Webhook is only targeting one specific URL. And we already receive all issues events onto labeler. Creating a new route is then not possible without creating a new webhook. Let's strike this option.
* <del>OR create another webhook on the project. </del>  
   We could definitely do that but no specific benefits, because we would still need to listen on issues events, which are already doing with `/labeler`. We would generate twice the traffic for no additional benefits. Let's strike this.


  https://github.com/webcompat/web-bugs/settings/hooks

We will still be using the issue event https://developer.github.com/v3/activity/events/types/#issuesevent but this time monitoring for `action: labeled`. One cool thing maybe is that assigning the label manually should also trigger the webhook.

```
        if event_type == 'issues':
```

(Removing some parts), this is what it looks like:

```json
{
  "action": "labeled",
  "issue": {
    "url": "https://api.github.com/repos/webcompat/web-bugs/issues/7109",
// cut
    "id": 232410003,
    "number": 7109,
    "title": "plex.tv - text is not visible",
    "user": {
      "login": "webcompat-bot",
// cut
    },
    "labels": [
      {
        "id": 242578402,
        "url": "https://api.github.com/repos/webcompat/web-bugs/labels/browser-firefox-mobile",
        "name": "browser-firefox-mobile",
        "color": "fbca04",
        "default": false
      },
      {
        "id": 468843070,
        "url": "https://api.github.com/repos/webcompat/web-bugs/labels/status-incomplete",
        "name": "status-incomplete",
        "color": "d93f0b",
        "default": false
      }
    ],
    "state": "closed",
    "locked": false,
    "assignee": null,
    "assignees": [

    ],
    "milestone": null,
    "comments": 1,
    "created_at": "2017-05-30T23:20:50Z",
    "updated_at": "2017-06-01T03:20:13Z",
    "closed_at": "2017-06-01T03:20:08Z",
    "body": "<!-- @browser: Firefox Mobile 55.0 -->\n<!-- @ua_header: Mozilla/5.0 (Android 7.1.2; Mobile; rv:55.0) Gecko/55.0 Firefox/55.0 -->\n<!-- @reported_with: mobile-reporter -->\n\n**URL**: https://plex.tv/\n**Browser / Version**: Firefox Mobile 55.0\n**Operating System**: Android 7.1.2\n**Problem type**: Text is not visible\n\n**Steps to Reproduce**\n1. Navigate to: https://plex.tv/\r\n2. …\r\n\r\nExpected Behavior:\r\n\r\nActual Behavior:\r\n\r\n\r\n[![Screenshot Description](https://webcompat.com/uploads/2017/5/daa9a4ad-7ad5-43d7-af3d-b2b098a5b7c3-thumb.jpg)](https://webcompat.com/uploads/2017/5/daa9a4ad-7ad5-43d7-af3d-b2b098a5b7c3.jpg)\n\n\n\n_From [webcompat.com](https://webcompat.com/) with ❤️_"
  },
  "label": {
    "id": 468843070,
    "url": "https://api.github.com/repos/webcompat/web-bugs/labels/status-incomplete",
    "name": "status-incomplete",
    "color": "d93f0b",
    "default": false
  },
  "repository": {
// cut
  },
  "organization": {
//cut
  },
  "sender": {
//cut
  }
}
```

so the thing to watch out is 

* payload.action = labeled
* payload.label.name = type-media

To note. Every label changed, even if it was done as bulk post `['label1', 'label2']` will generate a HTTP POST to `/labeler` for each individual labels. so 2 labels added in a bulk POST == 2 HTTP POST to `labeler`. If a label has been changed (aka one added, another one remove), same story, There will be a `payload.action = unlabeled`  and a `payload.action = labeled`.

**Comment by karlcow** [comment]
Started to commit code for 

1. Better webhook (a bit more refactoring, follow-up on #1228 )
2. Handling the label `type-media`

This is in progress.

**Comment by karlcow** [comment]
This is interesting. https://docs.python.org/2/library/unittest.html#unittest.skipIf

```python
@unittest.skipIf('blah', "run test only if blah")
    def test_format(self):
        # Tests that work only if blah is met.
        pass
```

For my latest commit 
https://github.com/karlcow/webcompat.com/commit/7f74e032603a63ef8bee3f516208b205cd6095e6
I have used `with webcompat.app.test_client() as client:` which is cool to create a request context accessible for the test. It helps me to specifically test the request headers, like if it was coming from GitHub without actually doing anything with GitHub. I put it here to keep it in mind for other tests.

**Comment by karlcow** [comment]
I tested different options this Sunday… and was surprised when profiling. 
I tested first with regex, then with slicing and I didn't find a lot of differences. 
https://gist.github.com/karlcow/8737fb709b49f481917896fa356c89da

But in the profiler I have seen that a lot of calls were made to urlparse. So I decided to just remove it from my code, just to see what is happening and wow. Not only it increases speed by 6 folds on the regex solution, but it's not measurable in the slicing one. 

So I guess the CPU hoarder there is urlparse to extract the domain. I need to find out a bit more on this.

**Comment by karlcow** [comment]
```
# Python 3.6
→ python3 -m timeit -n 1000000 "import urllib.parse;domain=urllib.parse.urlparse('http://www.chia-anime.tv/player.php?id=78454').netloc;"
1000000 loops, best of 3: 4.14 usec per loop

# Python 2.7
→ python -m timeit -n 1000000 "import urlparse;domain=urlparse.urlparse('http://www.chia-anime.tv/player.php?id=78454').netloc;"
1000000 loops, best of 3: 2.55 usec per loop

# python 3.6
→ python3 -m timeit -n 1000000 "'http://www.chia-anime.tv/player.php?id=78454'.split('/')[2]"
1000000 loops, best of 3: 0.43 usec per loop

# python 2.7
→ python -m timeit -n 1000000 "'http://www.chia-anime.tv/player.php?id=78454'.split('/')[2]"
1000000 loops, best of 3: 0.431 usec per loop
```

A lot faster… but the issue is to have correctly formatted URIs.

```python
>>> 'http://www.chia-anime.tv/player.php?id=78454'.split('/')[2]
'www.chia-anime.tv'
>>> 'http:/www.chia-anime.tv/player.php?id=78454'.split('/')[2]
'player.php?id=78454'
>>> 'http:www.chia-anime.tv/player.php?id=78454'.split('/')[2]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
IndexError: list index out of range
```

**Comment by karlcow** [comment]
Ah we probably should be using urlsplit instead of urlparse when extracting the domain name.

```
→ python -m timeit -n 1000000 "import urlparse;domain=urlparse.urlparse('http://www.chia-anime.tv/player.php?id=78454').netloc;"
1000000 loops, best of 3: 2.37 usec per loop

→ python -m timeit -n 1000000 "import urlparse;domain=urlparse.urlsplit('http://www.chia-anime.tv/player.php?id=78454').netloc;"
1000000 loops, best of 3: 1.41 usec per loop
```

**Comment by karlcow** [comment]
```
→ git rg urlparse
webcompat/form.py
11:import urlparse
129:    parsed = urlparse.urlparse(url)
155:        domain = urlparse.urlparse(url).netloc

webcompat/helpers.py
16:import urlparse
224:        host = urlparse.urlparse(request.referrer).hostname
240:        host = urlparse.urlparse(request.referrer).hostname
289:        uri_tuple = urlparse.urlsplit(uri)
299:        data['link'] = urlparse.urlunsplit(('', '', api_path, query, ''))
319:    uri_group = urlparse.urlparse(uri)
325:    return urlparse.urlunparse(clean_uri)

webcompat/static/js/vendor/markdown-it.js
7105:function urlParse(url, slashesDenoteHost) {
7310:module.exports = urlParse;

webcompat/webhooks/helpers.py
11:import urlparse
67:        domain = urlparse.urlparse(url).netloc
```

**Comment by karlcow** [comment]
Still thinking out loud and documenting this process.

Scenarios:

1. the issue is already in the list with the same issue number.  
    it might happen when changing labels. Removing it, adding it again.
    Should we take care of the unlabeling cases. 
2. the issue is in the list with same error code and domain, but different issue number. (duplicate)
3. the issue is not in the list. This is a new issue to add to the list.

**Comment by karlcow** [comment]
Option to test. We probably don't need to extract the domain name through regex as it comes for free in the issue title.

That would simplify a lot the code and make it more robust. And probably we could avoid regex altogether and use slicing instead (faster).

https://github.com/karlcow/webcompat.com/commit/dc9cabd552a6a5a68a955a71f9ef8e30f35bebc0#diff-53c7dc964488671110b629cf6885fb3eR67

**Comment by karlcow** [comment]
Should we have an entry in the list for each type of error code. aka

```
1076 error_code_1  example.org
2048 error_code_2  example.org
3095  error_code_2 example.com 
```

or should we just have 

```
1076  example.org error_code_1 error_code_2
3095  example.com error_code_2
```

Until now for manual triage, I have been mostly doing the second case, but I think @MDTsai makes a distinction in between the type of issues.

**Comment by MDTsai** [comment]
Automatically close duplicate issues can save our time doing triage, but the rest issues (or the list) should not block media team does diagnosis. For me I think the first list keeps complete information. Maybe @alfredoyang can give us clue about this?

**Comment by karlcow** [comment]
@MDTsai understood. That would mean reshuffling the current issue which have been closed. I'll see what I can do, discover for doing that.

**Comment by karlcow** [comment]
* to [create a comment](https://developer.github.com/v3/issues/comments/#create-a-comment)
```
POST /repos/:owner/:repo/issues/:number/comments

  {
  "body": "Me too"
}
```
* to [close an issue](https://developer.github.com/v3/issues/#edit-an-issue)

```http
PATCH /repos/webcompat/webcompat-tests/issues/735 HTTP/1.1
Accept: application/vnd.github.v3+json
Accept-Encoding: gzip, deflate
Authorization: token OAUTH-TOKEN
Connection: keep-alive
Content-Length: 54
Content-Type: application/json
Host: api.github.com
User-Agent: HTTPie/0.9.9

{
    "labels": [
        "duplicate", 
        "foobar"
    ], 
    "state": "closed"
}
```
Tested on the cli and working.

**Comment by karlcow** [comment]
We need to make sure we have all labels of the issue before sending back an edit. If we don't we will loose labels. It means an additional request and so idle time for the Webhooks. :/
grmph

Same thing will happen for @MDTsai future webhooks. I need to find a good strategy 
1. to not loose data
2. to not create race conditions
3. to not lock the webhook with waiting http requests responses. 

Challenge accepted. 👅

**Comment by karlcow** [comment]
So the patch above will remove the old label. 
The only way this will not happen is if we do a POST. This works.

```http
POST /repos/webcompat/webcompat-tests/issues/735/labels HTTP/1.1
Accept: application/json, */*
Accept-Encoding: gzip, deflate
Authorization: token OAUTH-TOKEN
Connection: keep-alive
Content-Length: 18
Content-Type: application/json
Host: api.github.com
User-Agent: HTTPie/0.9.9

[
    "apple", 
    "pies"
]
```

but in return it means we might have surprise in the case where we want to remove the `status-needstriage` which might have been set already or not… possible race conditions.
So we need to make sure we have a failsafe scenario.

Or to wait for milestones in SF by @miketaylr because that means we need to rewrite the code for switching from labels to milestones. :D

**Comment by karlcow** [comment]
Per discussion in San Francisco, we decided to stop the `type-media` firehose. https://wiki.mozilla.org/Compatibility/Meetings/2017-06-29#Type-media_future_.28karl.29

There's a followup issue to benefit of the code improvements done with this work. see #1677
