### ISSUE TITLE
“Report” button becomes active after adding a screenshot and no other details are typed/set for the issue

### ISSUE THREAD

**Issue by softvision-oana-arbuzov** [webcompat/webcompat.com#1552]
**URL:** www.webcompat.com  
**Browser / Version:** Firefox 52.0.2, Chrome 56.0.2924 
**Operating System:** Windows 10 Pro

**Steps to Reproduce:**
1. Navigate to: www.webcompat.com.   
2. Tap “Report bug” button.
3. Without typing any details or selecting an option, attach a screenshot.
4. Observe behavior.

**Expected Behavior:**
Error messages are displayed (“Problem type required”, “A valid URL is required”, “Need more Details”) and “Report” button becomes active only after the mandatory fields/options are set.

**Actual Behavior:**
No error messages are displayed and “Report” button becomes active.

**Notes:**
1. Issues is logged if tapping the “Report” button.
2. Check example #[6596](https://github.com/webcompat/web-bugs/issues/6596).
3. Screenshot attached.

**Watchers:**
@softvision-sergiulogigan
@softvision-oana-arbuzov

sv; 

![reportissue_nodetails](https://cloud.githubusercontent.com/assets/12184325/25891276/1db3d88c-3579-11e7-90f5-a1e6d59e54a0.png)

**Comment by zoepage** [comment]
We should tackle this one in #1547.

**Comment by cch5ng** [comment]
This seems like a relatively small fix, removing this line:
https://github.com/webcompat/webcompat.com/blob/master/webcompat/static/js/lib/bugform.js#L457

I am just wondering if there was a reason why it was included originally. This change will be made in #1547

**Comment by cch5ng** [comment]
![screen shot 2017-06-02 at 6 29 58 pm](https://cloud.githubusercontent.com/assets/4755432/26749517/bf063dec-47c1-11e7-92d4-e3c97fab3481.png)

there is a pointer to issue #1049 in the blame for line 415 but I still don't understand why that line was needed

**Comment by karlcow** [comment]
@miketaylr see question above. I don't remember either.

**Comment by miketaylr** [comment]
> I am just wondering if there was a reason why it was included originally.

Hm, it's possible I meant to call `checkForm` there... but I don't remember. If removing it doesn't fail tests, that sounds like a good fix. :)

**Comment by cch5ng** [comment]
revisiting this because @zoepage found a bug with my pr for it

in the current code, I think these 2 calls are being paired (this.disableSubmits() and this.enableSubmits()) in the context of making the post request for image uploads. I guess disableSubmits() is done before to avoid some conflict between issue saving and image uploading.

https://github.com/webcompat/webcompat.com/blob/master/webcompat/static/js/lib/bugform.js#L443

https://github.com/webcompat/webcompat.com/blob/master/webcompat/static/js/lib/bugform.js#L457

to fix the reported issue, #1552, if I remove the this.enable() call, a different bug like this would occur:

https://github.com/webcompat/webcompat.com/pull/1578#issuecomment-306905330

**Comment by cch5ng** [comment]
@softvision-oana-arbuzov hi, if I understand correctly, these are the expected changes

- [ ] if the user drags/drops an image onto an empty issue form, then all fields validation should occur (displaying errors for required fields)
- [ ] if the user drags/drops an image onto an empty issue form, then the submit buttons should remain inactive

**Comment by softvision-sergiulogigan** [comment]
Now we get a 400 error when submitting the form without selecting a general issue radio button.

![efdxlaitseuq5lzax6z6aw](https://user-images.githubusercontent.com/16573771/26930804-38b3978a-4c67-11e7-92bb-ced5aac65628.png)

**Comment by cch5ng** [comment]
@zoepage re your question about why this issue is dependent on #1547, I had to make updates to this function:

https://github.com/webcompat/webcompat.com/blob/master/webcompat/static/js/lib/bugform.js#L442

like
```
  this.getUploadURL = function(dataURI) {
    this.disableSubmits();
    this.uploadLoader.addClass("is-active");
    var formdata = new FormData();
    formdata.append("image", dataURI);

    $.ajax({
      contentType: false,
      processData: false,
      data: formdata,
      method: "POST",
      url: "/upload/",
      success: _.bind(function(response) {
        this.addImageURL(response);
        this.uploadLoader.removeClass("is-active");
        // checks for any empty required fields to display warnings
        this.checkURLValidity();
        this.checkImageTypeValidity();
        this.checkProblemTypeValidity();
        // after #1547 gets merged, one line needs to be added to call checkDescriptionValidity() or verify that the new Description input text (required field) is not empty
        // only enable submit buttons if there are no errors
        if (!$('.wc-Form-helpMessage').length && !$('.wc-Form-helpMessage--imageUpload').length) {
          this.enableSubmits();
        }
      }, this),
```

**Comment by miketaylr** [comment]
See also #1613 -- I forgot this issue already existed and fixed it there.

**Comment by miketaylr** [comment]
> I am just wondering if there was a reason why it was included originally.

Just to add some context, the submits are disabled before the upload here:

https://github.com/webcompat/webcompat.com/blob/master/webcompat/static/js/lib/bugform.js#L443

The original idea was to check validity once the upload succeeded, but instead I just enabled them blindly, which was a bug. :)

**Comment by miketaylr** [comment]
This is fixed now in production, can you verify @softvision-oana-arbuzov and close?

@cch5ng unless I misunderstand something from your proposed solution, shouldn't `checkForm` be updated to include `checkDescriptionValidity`? Possibly something that should land in #1547, if it's not already included.

**Comment by cch5ng** [comment]
@miketaylr 
> unless I misunderstand something from your proposed solution, shouldn't checkForm be updated to include checkDescriptionValidity? Possibly something that should land in #1547, if it's not already included.

yes, that is correct. some time before this comment (below), I was asked to separate #1552 from #1547. your comment above is the reason why #1552 is now being held until #1547 gets merged.

https://github.com/webcompat/webcompat.com/issues/1552#issuecomment-308474276

I think I just need to get an agreement from you and @zoepage whether to include #1552 in #1547 or not.

**Comment by cch5ng** [comment]
@miketaylr 
> unless I misunderstand something from your proposed solution, shouldn't checkForm be updated to include checkDescriptionValidity? Possibly something that should land in #1547, if it's not already included.

for me when reading through the checkForm() function, I thought it would just validate the required fields and display errors if relevant. but I didn't see where it would re-enable the submit buttons if appropriate (ie case where all required fields were filled out before the file upload).

but I tested your fix on master and it seems like the submit buttons get re-enabled somewhere in the process.

**Comment by softvision-oana-arbuzov** [comment]
I've retested the issue and it is no longer reproducible. 
Verified cases:
- not logged in;
- logged in;
- different browsers;
- trying to submit the issue without selecting a problem type option/without typing the site URL.

Note that when removing all the text from "Give more details", but selecting a problem type and site URL, "Report" button becomes active. I consider that for this case, "Report" button should also be inactive until users adds some details.

**Tested with:**
Browser / Version: Firefox 54.0, Chrome 58.0.3029.110.
Operating System: Windows 10 Pro

**Comment by miketaylr** [comment]
> I've retested the issue and it is no longer reproducible.

Thanks!

> I consider that for this case, "Report" button should also be inactive until users adds some details.

If there isn't another bug open for this, can you open one?

**Comment by softvision-oana-arbuzov** [comment]
The issue is no longer reproducible.

**Tested with:**
Browser / Version: Firefox 54.0.1, Chrome 59.0.3071.115.
Operating System: Windows 10 Pro

Related to "I consider that for this case, "Report" button should also be inactive until user adds some details.", I've opened an issue [#1659](https://github.com/webcompat/webcompat.com/issues/1659)

**Comment by miketaylr** [comment]
Thanks!
