### ISSUE TITLE
Rename status-needsdiagnosis-important as important

### ISSUE THREAD

**Issue by karlcow** [webcompat/webcompat.com#1554]
Currently when we set a **status-needsdiagnosis-important** instead of **status-needsdiagnosis** the bug disappears from the lists.

Steps to reproduce:

1. Go to https://webcompat.com/issues?page=1&per_page=50&state=open&stage=needsdiagnosis&sort=created&direction=desc
2. needsdiagnosis-important are not visible.

Proposal:  The UI should show the aggregated lists of needsdiagnosis and needsdiagnosis-important. 

Benefit. Avoid to have to setup two status-* tags.

Maybe the issue is moot if we consider that the `important` is not tied to the status. Aka it is important for contact, etc.

**Comment by karlcow** [comment]
The diagnosis is urgent… but then probably the needscontact/contactready too. 
should the important label be orthogonal to the status? We can even imagine at a point where we have semi-automatic labeling for triage, aka this domain is mail.google.com, assign important, because it needs triage priority.

**Comment by miketaylr** [comment]
> should the important label be orthogonal to the status?

That seems to make sense.

**Comment by karlcow** [comment]
Proposal: Rename the `status-needsdiagnosis-important` to `important`.

* Avoid conflict with future milestones
* Avoid current conflict when selecting needsdiagnosis in the current UI.
* Help contactready/needscontact to have the priority too.

**Comment by karlcow** [comment]
I moved today all the issues which had `status-needsdiagnosis-important` to `status-needsdiagnosis` + `priority-critical` to be compatible with @MDTsai work and to make it possible to carry on the priority after diagnosis.
