### ISSUE TITLE
[design] List of content modules

### ISSUE THREAD

**Issue by zoepage** [webcompat/webcompat.com#1558]
To get a better overview of what we have and need, I've created a short list of modules we use right now on the site. Here modules refer to a specific purpose created through content on the site.

```
Search
"dashboard"
Top Navigation
Footer navigation
Hero-box (index)
1x3 grid teaser boxes
1x1 grid text box / image / text-image combo
Issues list
Issue detail
Label box
Bug form
Comment form
1x3 image / 2x3 text grid box
4x4 || 5x5 grid box
```

@magsout Is there anything I forgot so far?

**Comment by magsout** [comment]
@zoepage hum, seems good.
