### ISSUE TITLE
Cannot close or reopen issues

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat.com#1560]
Fallout from #1559.

STR
1. go to any open issue
2. try to close issue

expected: 200 PATCH to edit endpoint
actual: 403

I have a quick fix I'll push then ask @karlcow to review after (and probably improve).

**Comment by zoepage** [comment]
@miketaylr as the push seemed to fix the issue and you pushed to master, shall we close the issue?

**Comment by miketaylr** [comment]
Ah yeah, this should have been closed. Thanks!

**Comment by zoepage** [comment]
Thanks!
