### ISSUE TITLE
Code overflow in issue description

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat.com#1562]
See https://webcompat.com/issues/6656

Seems related to #748.

@magsout any ideas?

![screen shot 2017-05-15 at 1 47 45 pm](https://cloud.githubusercontent.com/assets/67283/26073671/1dac39ce-3975-11e7-94e6-e1f2bcc5f444.png)

**Comment by magsout** [comment]
not yet, but i try to figure out why
