### ISSUE TITLE
When the browser name contains (), remove them

### ISSUE THREAD

**Issue by karlcow** [webcompat/webcompat.com#1567]
This is a followup on #1228 
Currently if the browser name is "Firefox (tablet)" we end up as a tag with `browser-firefox-(tablet)` instead of `browser-firefox-tablet` 

I'm happy to mentor this.
The code to modify is here
https://github.com/karlcow/webcompat.com/blob/0fea5ebe3cfd46efaf6568c35a358e86525f6a41/webcompat/webhooks/helpers.py#L28-L30

And probably an additional test to add to 
https://github.com/karlcow/webcompat.com/blob/0fea5ebe3cfd46efaf6568c35a358e86525f6a41/tests/test_webhook.py#L117

**Comment by kritisingh1** [comment]
Hello @karlcow I would like to take up this issue if it is still open. May I ?

**Comment by zoepage** [comment]
@kritisingh1 For `good first bugs` we decided to go with "grab one at a time". 

I've assigned you to #1688, but if you'd rather work on this one, please let me know :)

**Comment by aryanshar** [comment]
Hi ! i would love to work on this issue. Please assign me this issue. Thanks.
