### ISSUE TITLE
[bug] broken code layout with text fully wrapped

### ISSUE THREAD

**Issue by karlcow** [webcompat/webcompat.com#1570]
1. Go to https://webcompat.com/issues/2009#issuecomment-304553096
2. See how the code is wrapped.

![capture d ecran 2017-05-29 a 10 16 25](https://cloud.githubusercontent.com/assets/505230/26533781/afaf48aa-4458-11e7-9dec-8f767bec8366.png)

Compare with github.
https://github.com/webcompat/web-bugs/issues/2009#issuecomment-304553096

**Comment by karlcow** [comment]
@magsout @zoepage this one is "urgent" :)
And I confirmed with @adamopenweb that I was not the only one.

**Comment by magsout** [comment]
@karlcow it's on top on my todolist this morning

**Comment by karlcow** [comment]
With big 😍
