### ISSUE TITLE
Please write your bio - deadline 6/7

### ISSUE THREAD

**Issue by zoepage** [webcompat/webcompat.com#1576]
Please write a short 3 line bio, we can include in the contributor section.
You can find examples here: [http://hood.ie/community/](http://hood.ie/community/)

Please add following under your handle:
- Full name
- Twitter or other you'd like to link
- A short bio

Below you will find a list of people suggested, to send a bio in. If you feel like someone is missing, please add them in a comment, so they will get a notification. Thanks!

**DEADLINE is 7th of June.**

@magsout 
Guillaume Demesy
Front-end developer, enjoys coding and being a dad.
http://magsout.github.io/

@lockettm

@miketaylr 
Mike Taylor - USA
https://miketaylr.com
Looking at broken web pages like it's 1999. Lives in sunny Austin, TX.

@denschub
Dennis Schubert - Germany
https://schub.io
Breaking and fixing the web in various ways, usually by creating open source software.

@karlcow 
Karl Dubost - Japan
http://www.la-grange.net/karl/
Walking toward every nowhere.

@adamopenweb 
Adam Stevenson - Canada
twitter.com/AdamOpenWeb
Works on webcompat bugs and does outreach to sites / developers. Enjoys music, biking, travel and sometimes photos. 

@MDTsai 
Eric MD Tsai - Taiwan
https://medium.com/@md.tsai
Webcompat engineer works on compatibility issue some other helper features.

@cch5ng 
Carol Chung - USA
http://www.carolchung.com
Front-end developer. Enjoys JavaScript, volleyball and museums.

@brizental 
Beatriz Rizental - Brazil
https://github.com/brizental
Design student who really just wants to code.

@wisniewskit  
Thomas Wisniewski - Canada
Full-stack web developer with an affection for the open web and open source. Diagnoses webcompat bugs, helps out with web standards and browser regressions, and loves good food, good drink and good company.

@ioana-chiorean 

@softvision-oana-arbuzov 
Arbuzov Oana - Romania
I'm a QC Engineer. I enjoy testing on mobile (Android & iOS) and web.
My hobbies are mountain biking, hiking, swimming, traveling and playing online rpg games.

@softvision-sergiulogigan
Sergiu Logigan
QC Engineer @Softvision (Romania).
Helps making the WWW a better place, when he's not biking, hiking or traveling.

@zoepage 
Ola Gasidlo - Germany
twitter.com/misprintedtype
JS developer & daughter-driven development advocate. Conference speaker and organizer.
Loves riding her bike, cares deeply about community and open source.

**Comment by karlcow** [comment]
tongue in cheek: "short 3 line bio" How many characters in each line? 😉

**Comment by wisniewskit** [comment]
I can't seem to edit your comment, so here's a quick bio for me:
Thomas Wisniewski
Full-stack web developer with an affection for the open web and open source. Diagnoses webcompat bugs, helps out with web standards and browser regressions, and loves good food, good drink and good company.

**Comment by MDTsai** [comment]
Short bio for me:
Eric MD Tsai
https://medium.com/@md.tsai
Webcompat engineer works on compatibility issue some other helper features.

**Comment by miketaylr** [comment]
Mike Taylor
https://miketaylr.com
Looking at broken web pages like it's 1999. Lives in sunny Austin, TX.

**Comment by zoepage** [comment]
@karlcow 
> tongue in cheek: "short 3 line bio" How many characters in each line? 😉

:D It should describe yourself a bit more, so you get out of the black vault and seem more approachable? :)

**Comment by karlcow** [comment]
@zoepage I understand that.

**Comment by magsout** [comment]
Guillaume Demesy
Front-end developer, enjoys coding and being a dad. 
http://magsout.github.io/

**Comment by softvision-oana-arbuzov** [comment]
Arbuzov Oana - Romania
I'm a QC Engineer. I enjoy testing on mobile (Android & iOS) and web. 
My hobbies are mountain biking, hiking, swimming, traveling and playing online rpg games.

**Comment by softvision-sergiulogigan** [comment]
Sergiu Logigan
QC Engineer @Softvision (Romania).
Helps making the WWW a better place, when he's not biking, hiking or traveling.

**Comment by zoepage** [comment]
Last call as the deadline is tomorrow for @cch5ng @brizental @ioana-chiorean @lockettm. 
Thanks!

**Comment by zoepage** [comment]
Sneak peak for the community bio section. 
Please note, that this is still a WIP and details are not set yet. 

Thanks!

## Desktop 
![desktop hd 1 1 1 img txt txt](https://cloud.githubusercontent.com/assets/562354/26826446/7b132b5e-4ab9-11e7-9ba0-50eb16471fd2.png)

## Tablet
![tablet portrait 1 2 img txt](https://cloud.githubusercontent.com/assets/562354/26826448/7b1a4f7e-4ab9-11e7-82f2-4029107cb756.png)


## Mobile
![mobile portrait 1 2 img txt](https://cloud.githubusercontent.com/assets/562354/26826447/7b17e9be-4ab9-11e7-8512-aea208add7bf.png)

**Comment by cch5ng** [comment]
my bio:

Carol Chung - USA
http://www.carolchung.com
Front-end developer. Enjoys JavaScript, volleyball and museums.

**Comment by brizental** [comment]
(I'll put my github for now, but I'll publish my blog later this week. When I do, I edit this.)

Beatriz Rizental - Brazil
https://github.com/brizental
Design student who really just wants to code.

**Comment by zoepage** [comment]
Closing as bios have been moved to content document.

**Comment by ioana-chiorean** [comment]
@ioana-chiorean

Ioana Chiorean - Romania
https://twitter.com/ioana_cis 

Works in mobile testing, and contributes to open source projects while hacking a coffee or a good wine. Bike lover, community supporter and explorer through running.
