### ISSUE TITLE
[optimization] change urlparse to urlsplit

### ISSUE THREAD

**Issue by karlcow** [webcompat/webcompat.com#1581]
In [form.py ](https://github.com/webcompat/webcompat.com/blob/master/webcompat/form.py), there is the function `domain_name` which extracts the domain name. It uses `urlparse.urlparse()` which is less performant than `urlparse.urlsplit()`.

```python
def domain_name(url):
    '''Extract the domain name of a sanitized version of the submitted URL.'''
    # Removing leading spaces
    url = url.lstrip()
    # testing if it's an http URL
    if url.startswith(SCHEMES):
        domain = urlparse.urlparse(url).netloc
    else:
        domain = None
    return domain
```

**Comment by zoepage** [comment]
Removing the label `scope: refactor` as this one is mainly for the front end refactor purpose.

**Comment by rheaparekh** [comment]
Can I make the changes if this is not yet worked upon?

**Comment by karlcow** [comment]
@rheaparekh yes
Be sure to read https://github.com/webcompat/webcompat.com/blob/master/CONTRIBUTING.md
