### ISSUE TITLE
Mock Github login for testing

### ISSUE THREAD

**Issue by brizental** [webcompat/webcompat.com#1582]
I have been working on #980 and Github requests have been really slowing the process down. Not only because it's a request to a remote server, but also because Github requires re-authorization from time to time.

We have a work around (https://github.com/webcompat/webcompat.com/blob/master/tests/functional/lib/helpers.js#L88) for when Github asks the user for re-authorization, but that does not seem to be working :/

**Comment by karlcow** [comment]
@brizental the goal partly would be to have the tests working when you switch off any internet connections. So basically to have everything working in local without making any requests to GitHub.

**Comment by brizental** [comment]
@karlcow Yes! I opened the issue mainly because this is really slowing me down, but that is also one of the goals.

**Comment by karlcow** [comment]
If you crack this one, It will be wonderful all over here. It's a very important and useful work.
This is ruby but might give you inspiration
https://github.com/Ada-Developers-Academy/textbook-curriculum/blob/master/09-intermediate-rails/testing-auth.md

**Comment by brizental** [comment]
@karlcow Thanks for the ref!

I don't know yet if it's best for us to use a package to help on the mock requests or not, do you have any suggestions?

Also, I was taking a look at the login function that we have now and it occurred to me: wouldn't it be best for us just to login through the GitHub API? The way we do it now (https://github.com/webcompat/webcompat.com/blob/master/tests/functional/lib/helpers.js#L74), it seems like we are testing the GitHub interface, I don't know...

Finally, I thought we could leave in the real login even after we make the mock one and the interaction would be something like this: when testing, the `user` and `pw` parameters would be optional. If you put them, you get the normal login and if not you get the mock login.

**Comment by karlcow** [comment]
There are two sets of tests (python unit tests and JavaScript functional tests). We should try to separate as much as possible things which really requires any network connections. Also we do not need to test that GitHub is working. :) 

Our goal is to test that webcompat is working, so everything which relies on GitHub should be mocked in some ways.

Yup having a switch if we really want to test online could also be a useful option.

**Comment by karlcow** [comment]
About https://github.com/webcompat/webcompat.com/blob/master/tests/functional/lib/helpers.js#L65-L119

yes this is the case where we exactly do not want to rely on the network and where mocking github would be better. We don't want  test GitHub UI. :) Here we are just doing this because we are dependent on this.

**Comment by zoepage** [comment]
looping @cch5ng in that discussion as she had the same question.

**Comment by karlcow** [comment]
Another piece of information which could be useful. The module we use for GitHub-Flask has tests (mocking GitHub oauth).
https://github.com/cenkalti/github-flask/blob/master/test_flask_github.py

**Comment by miketaylr** [comment]
> Another piece of information which could be useful. The module we use for GitHub-Flask has tests (mocking GitHub oauth).

This is good to keep in mind. We have a current super hack in place, but if it turns out to be too fragile, let's come back to this. 👍
