### ISSUE TITLE
[bug] Content Security Policy and localhost

### ISSUE THREAD

**Issue by karlcow** [webcompat/webcompat.com#1585]
Steps to reproduce
1. Starts python run.py
2. load an issue page with images.

Actual: images are not loaded
Expected images are loaded.

```
14:03:11.792 Content Security Policy: The page’s settings blocked the loading of a resource at https://webcompat.com/uploads/2017/5/c026afea-510c-48a2-890b-257b9f107747-thumb.jpg (“img-src http://localhost:5000 https://www.google-analytics.com https://*.githubusercontent.com data:”). 
14:03:11.793 Content Security Policy: The page’s settings blocked the loading of a resource at https://webcompat.com/uploads/2017/5/6142b925-f591-43a9-b026-533e392ed936.jpg (“img-src http://localhost:5000 https://www.google-analytics.com https://*.githubusercontent.com data:”).
```

**Comment by miketaylr** [comment]
Ah indeed. We only allow uploads from 'self', google analytics, github and data URIs. Adding webcompat.com for localhost seems fine.

**Comment by miketaylr** [comment]
@karlcow just to understand, was this an image you uploaded from localhost? Or did you manually link to an image uploaded from webcompat.com?

The current policy is:

`"img-src 'self' https://www.google-analytics.com https://*.githubusercontent.com data:; " +  # nopep8
`

IIRC, if you upload an image from localhost, it will be served from localhost, so `'self'` here is correct.

**Comment by karlcow** [comment]
/me is trying to remember which page. incomplete report 🏸 (badminton racket because there is no `:bad:` emoji)

I think it was http://localhost:5000/issues/667
and indeed it's an image on github
https://github.com/webcompat/webcompat-tests/issues/667#issuecomment-306397496

**Comment by karlcow** [comment]
and forgotten the handle @miketaylr 6am chat.

**Comment by miketaylr** [comment]
Thanks! I think we can special-case localhost to include webcompat.com, seems harmless.
