### ISSUE TITLE
[proposal] Adds a data/ directory under .gitignore

### ISSUE THREAD

**Issue by karlcow** [webcompat/webcompat.com#1586]
Should we have a `data/` directory where we stash things like

* `issues.db`
* `sessions.db`
* Any other data useful for running webcompat.com but not part of the commits. (I'm thinking about the cache type-media list).

(Updated on August 17, 2017)

* [x] Create a `data/` directory
* [x] Add a `DATA_PATH` in the config file
* [x] Check in the code where we rely on `session.db` and `topsites*.db` adjust the paths  (@MDTsai)
* [x] Add `data/` to `.gitignore`
* [ ] Move `topsites*.db` and `session.db` (erase probably)

**Comment by miketaylr** [comment]
Sounds good to me @karlcow. I also think we should just remove isuses.db entirely since it's dead code. But +1 to having a .gitignore'd data directory.

**Comment by karlcow** [comment]
* The issues.db code #1719 is being removed by #1720 PR.
* Adding information in the first comment of that issue for the `data/`

**Comment by karlcow** [comment]
I will also need this `data/` for domain names feeds in #132

**Comment by karlcow** [comment]
For example:

```diff
diff --git a/config/environment.py b/config/environment.py
index 1359c64..275f4b3 100644
--- a/config/environment.py
+++ b/config/environment.py
@@ -8,6 +8,8 @@ import os
 
 # Define the application base directory
 BASE_DIR = os.path.abspath(os.path.join(os.path.dirname(__file__), os.pardir))
+DATA_PATH = os.path.join(BASE_DIR, 'data')
+FEED_PATH = os.path.join(DATA_PATH, 'feed')
 
 # the PRODUCTION and DEVELOPMENT environment variables are set in uwsgi.conf
 # on the webcompat server. If they're not set, they will default to None
```

**Comment by miketaylr** [comment]
decision: let's do it!

**Comment by karlcow** [comment]
Reminder: people will need to clean up their project root.
