### ISSUE TITLE
https://github.com/mozilla/geckodriver/issues/308 fixed

### ISSUE THREAD

**Issue by zoepage** [webcompat/webcompat.com#1590]
@miketaylr https://github.com/mozilla/geckodriver/issues/308 has been fixed. 

Related to:
https://github.com/webcompat/webcompat.com/blob/master/tests/functional/lib/helpers.js#L62

Possible this is related to the failing build? 
https://travis-ci.org/webcompat/webcompat.com#L579

**Comment by brizental** [comment]
Closing this because the code for it was removed in #1743
