### ISSUE TITLE
Create 3 labels for issue priority from alexa ranking

### ISSUE THREAD

**Issue by MDTsai** [webcompat/webcompat.com#1592]
This is the a part of #1533, we need to map the result from #1579 to a label. Label name should follow the bug label naming style. Some ideas:
Prefixes: priority, alexa, ranking, etc.
Suffixes: (critical, important, normal), (1, 2, 3), etc. 
Maybe we need a vote function on github to decide the name?

- [ ] Whitelist priority-* in label-list.js
- [ ] Add labels in web-bugs repository

**Comment by zoepage** [comment]
@MDTsai ok, let's vote! 😁 

Please click on a reaction emoji for your vote @denschub @wisniewskit @miketaylr @karlcow @adamopenweb  

Prefix: 
- priority 👍
- alexa 👎
- ranking 😀 

Suffixes:
- critical, important, normal 🎉 
-  1, 2, 3 ❤️

Other:
Please add comment below!

**Comment by karlcow** [comment]
So I have voted for `priority-(critical|important|normal)` 👍-🎉

**Comment by wisniewskit** [comment]
I second Karl's vote: 👍-🎉

**Comment by denschub** [comment]
emoji votes! interesting! 👍-🎉

**Comment by MDTsai** [comment]
Cool, so we use priority-(critical|important|normal).
@zoepage could you give them beautiful color?
@miketaylr should I do something to make the label visible on webcompat.com?

**Comment by zoepage** [comment]
@MDTsai How about

priority
- critical #D05

<img width="280" alt="screen shot 2017-06-15 at 11 56 27 am" src="https://user-images.githubusercontent.com/562354/27176264-23083cdc-51c2-11e7-8210-0a34611da390.png">
<img width="281" alt="screen shot 2017-06-15 at 11 56 38 am" src="https://user-images.githubusercontent.com/562354/27176265-23083bce-51c2-11e7-83f0-1a498a68631c.png">

- important #FB1

<img width="282" alt="screen shot 2017-06-15 at 11 55 58 am" src="https://user-images.githubusercontent.com/562354/27176263-2307b8c0-51c2-11e7-8d92-4c653c0d2771.png">


- normal #5A7
<img width="283" alt="screen shot 2017-06-15 at 11 54 26 am" src="https://user-images.githubusercontent.com/562354/27176266-23094942-51c2-11e7-8894-ce5007a948a7.png">

**Comment by miketaylr** [comment]
> @miketaylr should I do something to make the label visible on webcompat.com?

Yeah, we'll have to "whitelist" the `priority-` prefix:

https://github.com/webcompat/webcompat.com/blob/58f47fdd8f003444b3d4502de33fdb9c72ab574f/webcompat/static/js/lib/models/label-list.js#L27

I think that should be enough....

(this seems unused?? https://github.com/webcompat/webcompat.com/blob/2e9f2444a789d39873e42d2292f150fc87b98845/webcompat/static/js/lib/models/issue.js#L23)

**Comment by MDTsai** [comment]
Hmm, I should modify label-list.js first then add label to prevent people see the label with prefix. 

> (this seems unused?? https://github.com/webcompat/webcompat.com/blob/2e9f2444a789d39873e42d2292f150fc87b98845/webcompat/static/js/lib/models/issue.js#L23)

I think it's not used for now.

**Comment by MDTsai** [comment]
One more thing, if critical is checked, important and normal should not be checked.
