### ISSUE TITLE
Implement alexa webhook for priority labels

### ISSUE THREAD

**Issue by MDTsai** [webcompat/webcompat.com#1594]
This is the final part of #1533. Use the result db from #1591 and put the label from #1592 to created issue.

**Comment by karlcow** [comment]
So for this one, I recommend to hold on I have finished with the `type-media` webhook in #1551 because it will modify the code a bit.

**Comment by karlcow** [comment]
@MDTsai could you clarify how you intend the webhook to work? So I make it easier for you in my current changes. I guess you want something along:

1. new issue is created
2. issue creation event is emitted 
3. webhook checks the DB
4. if match sends a HTTP POST for creating a label

**Comment by MDTsai** [comment]
Too late to reply this issue. Here are thing I need to do:
1. Add Site class and DB access in db/__init__.py
2. Add priority_label in webhooks/__init__.py, this may looks like extract browser label
3. Add lookup_priority_label in webhooks/helpers.py, lookup priority in DB
