### ISSUE TITLE
Travis test failure on master

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat.com#1595]
After merging in https://github.com/webcompat/webcompat.com/pull/1588, we have the following failure on master:

```
.............

======================================================================

FAIL: Test that the /login route 302s to GitHub.

----------------------------------------------------------------------

Traceback (most recent call last):

  File "/home/travis/build/webcompat/webcompat.com/tests/test_urls.py", line 55, in test_login

    self.assertIn('github.com/login/oauth/', rv.headers['Location'])

AssertionError: 'github.com/login/oauth/' not found in 'http://localhost/'

----------------------------------------------------------------------
```

(my bad from not checking `nosetests` output before merging... 👻)

@brizental can you check this out? We won't deploy until this can get fixed -- thanks!

**Comment by miketaylr** [comment]
I guess we wanna add an exception to https://github.com/webcompat/webcompat.com/blob/master/tests/test_urls.py#L51 (for test mode?)

**Comment by brizental** [comment]
@miketaylr sorry, should have run these tests too...
Anyways, should we even leave this function in? In the setup for the nosetests we set the app in test mode, so there's no point in adding an exception for test mode, since we will always be in test mode... is there?

**Comment by miketaylr** [comment]
Oh, I think you're right. Hm... I guess we can just delete the test then. :)
