### ISSUE TITLE
bug description placeholder cut off at small viewports

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat.com#1617]
See:

![screen shot 2017-06-27 at 1 50 02 pm](https://user-images.githubusercontent.com/67283/27609482-c3797470-5b3f-11e7-8270-5c362fe0744e.png)

Maybe we can think of some shorter example text?

**Comment by cch5ng** [comment]
@miketaylr perhaps the placeholder could just be an abbreviation of the current:
The video should have started

also I'm not sure what is the process to complete this fix. who all needs to give feedback? thx

**Comment by miketaylr** [comment]
> The video should have started

Yep, that works! Or, "The video doesn't play" or... something like that. :)

> also I'm not sure what is the process to complete this fix. who all needs to give feedback? thx

I would submit a PR modifying the `placeholder` and probably ping @zoepage for review.
