### ISSUE TITLE
4 unit tests are network dependent.

### ISSUE THREAD

**Issue by karlcow** [webcompat/webcompat.com#1618]
When working with @brizental for an issue she had with tests, we also found out that 4 unit tests are failing if the network is off.

```
ERROR: API access to comments greater than 30 returns pagination in Link
Traceback (most recent call last):
  File "/Users/karl/code/webcompat.com/tests/test_api_urls.py", line 81, in test_api_comments_link_header_auth
    query_string=query_string, environ_base=headers)

ERROR: API issue for a non existent number returns JSON 404.
Traceback (most recent call last):
  File "/Users/karl/code/webcompat.com/tests/test_api_urls.py", line 45, in test_api_issues_out_of_range
    rv = self.app.get('/api/issues/1000000', environ_base=headers)

ERROR: API access to labels without auth returns JSON 200.
Traceback (most recent call last):
  File "/Users/karl/code/webcompat.com/tests/test_api_urls.py", line 69, in test_api_labels_without_auth
    rv = self.app.get('/api/issues/labels', environ_base=headers)

ERROR: Checks 500 is not accepted for /issues/new POST.
Traceback (most recent call last):
  File "/Users/karl/code/webcompat.com/tests/test_urls.py", line 129, in test_new_issue_should_not_crash
    rv = self.app.post('/issues/new', data=data)
```

These need to work even if the network is off.

**Comment by wisniewskit** [comment]
I am just commenting upon request, please ignore this comment!

**Comment by brizental** [comment]
@karlcow I was looking at this issue and the reason why some tests from `test_api_urls.py` fail is that we don't start the server is test mode for this suite. We have a comment saying that we don't want fixture data for this suite in particular (https://github.com/webcompat/webcompat.com/blob/master/tests/test_api_urls.py#L28-L29), why is that? If I can't change this I don't know how I can get this tests to work without connection.

**Comment by karlcow** [comment]
That's one possibility. Another one is to mock the data (if we can). I tried a couple of times, was close to manage it, but there was still a small things missing. Mocking is less complicated than I thought at the beginning. 
see https://github.com/webcompat/webcompat.com/blob/cc7aed70713a48f8c04082fcc2ac42c218967d77/tests/test_topsites.py#L35-L40

**Comment by karlcow** [comment]
Oh and this PR is probably one of the nails into finishing #396
