### ISSUE TITLE
bug form element alignment

### ISSUE THREAD

**Issue by cch5ng** [webcompat/webcompat.com#1619]
css styles should be revisited for small desktop size (~806px)

the alignment of text area bottom with submit buttons is a little off

https://github.com/webcompat/webcompat.com/pull/1578#issuecomment-311504694

should probably clean up the margin-bottom tweak made for verified input fields (another class was updated at the last minute for 1547)

**Comment by zoepage** [comment]
Will be fixed by http://webcompat.github.io/design/ as this will be handled by flexbox automatically.
