### ISSUE TITLE
Comment box issues with long comments

### ISSUE THREAD

**Issue by karlcow** [webcompat/webcompat.com#1622]
Step to reproduce

1. Go to an issue 
2. Start typing a comment so you reach the bottom of the allocated space
3. insert an image

Issues List
1. Actual: Note how the image is added under the visible part of the textarea.  Expected: the textarea should be positioned so we can see the code we just added.
2. Actual: You can't scroll in the textarea to view the code. Expected. Scroll down. The only way is to use the arrow key.
3. Once the textarea is bigger than the viewport and your page is scrolled to the bottom (aka end of textarea above the end of the viewport) and you type. Actual: The textarea bottom jumps to the bottom of the page. Expected: The textarea should be in place.
4. Bonus issue: When the cursor is somewhere in the comment. It should be the insertion point of the image. The image is always added at the end of the comment. 

I can open separate issues for each of them.

**Comment by karlcow** [comment]
Some issues are possibly related to what we decided in #1211 
Sorry… @zoepage 😿 👹

**Comment by zoepage** [comment]
After a conversation with @karlcow, we've decided to remove the feature as we it feels more like a bug and not a feature.

**Comment by apoorvasingh17** [comment]
Hello....I'm a beginner and would like to work on this issue. How should I get started?

**Comment by denschub** [comment]
@apoorvasingh17 Check my comment [over here](https://github.com/webcompat/webcompat.com/issues/1650)!

**Comment by miketaylr** [comment]
> After a conversation with @karlcow, we've decided to remove the feature as we it feels more like a bug and not a feature.

@zoepage does this mean we should close the issue? Or do we need to write patches to remove...something?

**Comment by karlcow** [comment]
@miketaylr confirmed. Remove the autoexpand. It is not working as it is right now.

**Comment by zoepage** [comment]
As this was fixed in #1636, closing,
