### ISSUE TITLE
Adds coco.fr to the abuse list

### ISSUE THREAD

**Issue by karlcow** [webcompat/webcompat.com#1627]
We currently had a series of report for coco.fr which looks like spam. 
Let's block them in the meantime.

**Comment by karlcow** [comment]
https://github.com/webcompat/web-bugs/issues?page=1&q=is%3Aissue+coco+in%3Atitle&utf8=%E2%9C%93

**Comment by karlcow** [comment]
The storm has passed. Let's close the pull request for now.
https://github.com/webcompat/webcompat.com/pull/1628

**Comment by miketaylr** [comment]
It's back. Like 17 in the past few hours.
