### ISSUE TITLE
[tests] Starting "python run.py -t" from the functional tests

### ISSUE THREAD

**Issue by karlcow** [webcompat/webcompat.com#1631]
So we have a pattern. 

Very often in the team, we forget (or at least I do) to start `python run.py -t` for running the functional tests. And indeed we have quite a lot of things to do before starting the tests. Having the right version of java, starting the server, the long command for launching the tests.

I wonder if this should not be handled with a script.

**Comment by zoepage** [comment]
Things got tiny bit easier when #1656 landed, but I agree. 

We could add a second start command to the npm scripts like `npm run start:test` and alias that, so it's easier to remember?

My initial thought was a combo of `python run.py -t` && `npm test`, but the issue here is, we'd need to start a second process for the tests and this is tricky from the package.json as it would need to "hook into the terminal" and it's sandboxed. (I'd be happy, if I'm wrong).

**Comment by zoepage** [comment]
We talked about this last week in the european-friendly webcompat.com meeting.
A way to go would be to write a small bash script to take care of that issue (firing up two processes, depending on each other and exit, if necessary.) But this also might be total over-engineering. (It probably is).

Maybe we could also solve the issue with improving the docs or adding another npm script to like `npm run start:test` ?

**Comment by brizental** [comment]
Another solution for this would be to add a warning in case the person is running the tests, but is not running the server in test mode. 

Something like "Hey, you are not running the server in test mode you might get a lot of false negatives!" plus some guidance about how to run the server in test mode.

We could even abort tests in case the person is not in test mode, I guess.

**Comment by zoepage** [comment]
How about we do both? So the npm script as well as the warning (including cancel the test if not in test mode)? Might sound as over engineering, but the pro's would be...

1. script (`npm start:test`) makes it easier to remember what to type as the words are "more human".
2. An error message to let you know, why tests fail would have saved me many hours (at least thinking about it, not to mention investigating.) We could build more trust in the tests for the person who develops and show a solution how to fix it right away.
3. Aborting the test would save time as the tests would not need to run through and fail before the person who runs them notices.

**Comment by brizental** [comment]
@zoepage That's great, I agree! I'll claim this issue then :)
