### ISSUE TITLE
Remove autoExpand feature for textareas

### ISSUE THREAD

**Issue by softvision-oana-arbuzov** [webcompat/webcompat.com#1636]
URL: www.webcompat.com  
Browser / Version: Firefox 54.0.1, Chrome 59.0.3071.115. 
Operating System: Windows 10 Pro

**Steps to Reproduce:**
1. Navigate to: www.webcompat.com.   
2. Type in a lot of info in “Give more details” text area.
3. Observe “Attachment” area.

**Expected Behavior:**
“Attachment” area remains on top of the page.

**Actual Behavior:**
“Attachment” area keeps moving to the bottom of the page.

**Notes:**
1. “Attachment” area becomes hidden if large data is added to “Give more details” text area. 
2. Screenshot attached.

**Watchers:**
@softvision-sergiulogigan
@softvision-oana-arbuzov

sv; 

![attachmentareadbellow](https://user-images.githubusercontent.com/12184325/27864221-543eaab4-6196-11e7-8755-328ee1dd4e9e.png)

**Comment by zoepage** [comment]
@karlcow and I discussed the feature of the growing textarea at the all hands and decided to remove it as it creates more issues that solving right now.

**Comment by apoorvasingh17** [comment]
Hello....I'm a beginner and would like to work on this issue. How should I get started?

**Comment by denschub** [comment]
@apoorvasingh17 Check my comment [over here](https://github.com/webcompat/webcompat.com/issues/1650)!

**Comment by miketaylr** [comment]
> @miketaylr The autoExpand function is used also in other spots. So we just need to touch the bugform.js, right or am I missing anything?

If we want to keep autoexpand for regular comments (which maybe we don't?... https://github.com/webcompat/webcompat.com/issues/1622#issuecomment-314046834), then we would leave in issues.js:

https://github.com/webcompat/webcompat.com/search?utf8=%E2%9C%93&q=autoExpand&type=

But it sounds like we want to remove it from anywhere.

@apoorvasingh17 if you want to work on this feature, we want to remove references to `autoExpand` in issues.js and bugform.js.

**Comment by apoorvasingh17** [comment]
@miketaylr yes, I would like to work on this issue.

**Comment by zoepage** [comment]
@apoorvasingh17 Do you want to work on this one or https://github.com/webcompat/webcompat.com/issues/1688#issuecomment-322539068 as you claimed both? Please choose one :)

**Comment by apoorvasingh17** [comment]
@zoepage I would work on this one.
