### ISSUE TITLE
refactor views.py and endpoints.py

### ISSUE THREAD

**Issue by cch5ng** [webcompat/webcompat.com#1637]
while looking at code for fixing issues, noted some items might be cleaned up

endpoints.py (from manual testing of search functionality couldn't see these endpoints getting called in the network panel)
* first verify logic in https://github.com/webcompat/webcompat.com/blob/master/webcompat/static/js/lib/issue-list.js; maybe some endpoints get used under special conditions like (with category filter and/or logged in status)
~~* https://github.com/webcompat/webcompat.com/blob/master/webcompat/api/endpoints.py#L148~~
(l148 appears to get used when logged in)
* https://github.com/webcompat/webcompat.com/blob/master/webcompat/api/endpoints.py#L181
  * verified even when logged in, a different endpoint, /api/issues/category/<category> appears to get used

views.py
~~* https://github.com/webcompat/webcompat.com/blob/master/webcompat/views.py#L179 (think set() replaced by frozenset() but could verify)~~
* https://github.com/webcompat/webcompat.com/blob/master/webcompat/views.py#L179 (could clean up comment)

**Comment by karlcow** [comment]
Some answers to your questions might be in #1640

**Comment by karlcow** [comment]
Are there things actionable in that issue? I will close it and if we missed things, anyone can propose an issue with a refactoring proposal. Good opportunity for first bugs.
