### ISSUE TITLE
[tutorial] Explanation of code in webcompat.com

### ISSUE THREAD

**Issue by karlcow** [webcompat/webcompat.com#1640]
@cch5ng started to ask question about the code. I will use this space to reply to the questions which might be useful for others.

Extract from https://github.com/webcompat/webcompat.com/pull/1628#issuecomment-312970048
> @karlcow this is the start to my questions about views.py (for /issues/new route) but eventually I'll cover the entire views.py. I might include some questions I had when trying to address a different issue later.
> 
> for https://github.com/webcompat/webcompat.com/blob/master/webcompat/views.py#L179
> should set() be updated to frozenset()? I had to look up issubset() and saw a deprecation notice in the docs. https://docs.python.org/2/library/sets.html ... but am not totally clear about it
> 
> https://github.com/webcompat/webcompat.com/blob/master/config/__init__.py#L49
> (this is something I looked at for a different issue) why do you use a namedtuple here? is it just to be more descriptive?
> 
> for the homepage view (/), I'm trying to understand the flow for how the triage issues list gets generated. in the source it seems to be coming from a backbone model but I'm not clear where in the code the request to the github api gets made. could I get a pointer to which source files I should be looking at?
> 
> in the future is it OK for me to include both you and MikeT as JS reviewers? I know both of you are very busy but your review concerns are a bit different and I think I learn from both forms.

**Comment by karlcow** [comment]
## sets vs set/frozenset in views.py

Usually better to use a reference with a commit view so it doesn't get lost in the future.
https://github.com/webcompat/webcompat.com/blob/eb8b2ac6377f4d2ffe96eae3e2fa6c5de3f6950b/webcompat/views.py#L179
https://docs.python.org/2/library/sets.html

> for https://github.com/webcompat/webcompat.com/blob/master/webcompat/views.py#L179
should set() be updated to frozenset()? I had to look up issubset() and saw a deprecation notice in the docs. https://docs.python.org/2/library/sets.html ... but am not totally clear about it

The module [`sets`](https://docs.python.org/2/library/sets.html) which has `Set()` is deprecated indeed, but we are not using that. We are using the built-in [set()](https://docs.python.org/2/library/stdtypes.html#set). It became a standard type. So we are good for this.

**Comment by karlcow** [comment]
## namedtuple in config for labels

https://github.com/webcompat/webcompat.com/blob/c613a7849f6e573c5c5cf186dea1bcf51e2f9b27/config/__init__.py#L46-L62

> https://github.com/webcompat/webcompat.com/blob/master/config/__init__.py#L49
(this is something I looked at for a different issue) why do you use a namedtuple here? is it just to be more descriptive?

Yes just to be more descriptive and easier to manipulate. We use them in templates. I did that initially to help the passing of arguments to @magsout This code will change soon when we switch to milestones (Issue #886 )

On GitHub, Blame is a good tool to find out the reason behind a change.

![capture d ecran 2017-07-06 a 09 24 42](https://user-images.githubusercontent.com/505230/27890339-0b4f1d56-622d-11e7-93c4-de2c435c91d0.png)

Though in this specific case it doesn't help that much because we moved the config to a new file and it destroyed the history. I wish there was a way to link history across file moves (but that's another topic.)

![capture d ecran 2017-07-06 a 09 26 34](https://user-images.githubusercontent.com/505230/27890401-6974e26c-622d-11e7-8253-7f0b58f08ce8.png)
 
So Let's see, we can probably search in the commits and issues. We had a discussion about this in the past
https://github.com/webcompat/webcompat.com/pull/801#discussion-diff-43366774

@miketaylr was not very fond of it. He found it confusing. We could switch to something else. As I said this code will change anyway very soon. I'm happy to kill them with fire if it confuses more people. 🔥

**Comment by karlcow** [comment]
## Homepage list of issues

> for the homepage view (/), I'm trying to understand the flow for how the triage issues list gets generated. in the source it seems to be coming from a backbone model but I'm not clear where in the code the request to the github api gets made. could I get a pointer to which source files I should be looking at?

The issues are populated into the section `js-lastIssue` and this is the code sent by the server.

```html
    <div id="js-lastIssue">
      <script type="text/template" id="needstriage-tmpl">
        <% if (issues.length) { %>
          <% _.each(issues, function(issue) { %>
            <article class="wc-IssueList wc-IssueList--<%= issue.stateClass %> wc-IssueList--large js-IssueList">
  <div class="wc-IssueList-section">
    <header class="wc-IssueList-header">
      <a class="wc-Link" href="/issues/<%= issue.number %>">
        <span class="wc-IssueList-count">Issue <%= issue.number %></span>: <%- issue.title %>
      </a>
    </header>
    <p>
      <span class="wc-IssueList-metadata">Opened: <time><%= issue.createdAt %></time></span>
      <span class="wc-IssueList-metadata">Comments: <%= issue.commentNumber %></span>
    </p>
  </div>
  <div class="wc-IssueList-section">
    <span class="wc-IssueList-label js-Issue-label">
    <% _.each(issue.labels, function(label) { %>
      <a href="/issues?q=label:<%= label.remoteName %>"
         class="wc-Labels" data-remotename="<%= label.remoteName %>"
         title="Labels : <%= label.name %>"><%= label.name %></a>
    <% }); %></span>
  </div>
</article>
          <% }); %>
        <% } else { %>
        <p>Nothing here currently, cool!</p>
      <% } %>
      </script>
      </div>
```

The HTTP request is made by the JavaScript as an XHR request asking for:
http://webcompat.com/api/issues/category/needstriage
This returns a JSON file. 

Which means we hit this route in the code: `@api.route('/issues/category/<issue_category>')`
https://github.com/webcompat/webcompat.com/blob/eb8b2ac6377f4d2ffe96eae3e2fa6c5de3f6950b/webcompat/api/endpoints.py#L107-L145

which ends up doing:
https://github.com/webcompat/webcompat.com/blob/eb8b2ac6377f4d2ffe96eae3e2fa6c5de3f6950b/webcompat/api/endpoints.py#L132

```python
 return api_request('get', issues_path, params=params)
```
aka https://github.com/webcompat/webcompat.com/blob/eb8b2ac6377f4d2ffe96eae3e2fa6c5de3f6950b/webcompat/helpers.py#L450-L471

Two cases at this moment, depending if you are logged in or not. 

---
Little tip here. If you do not remember what are the methods you can call on a function, you can use print(dir(function_name)) it will display all the method associated to a specific name.
---

so for example if you do that on [`resource`](https://github.com/webcompat/webcompat.com/blob/eb8b2ac6377f4d2ffe96eae3e2fa6c5de3f6950b/webcompat/helpers.py#L465)
aka `print(dir(resource))` you get in the terminal when loading the home page. 

```
['__attrs__', '__bool__', '__class__', '__delattr__', '__dict__', '__doc__', '__format__',
 '__getattribute__', '__getstate__', '__hash__', '__init__', '__iter__', '__module__',
 '__new__', '__nonzero__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', 
'__setstate__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_content', 
'_content_consumed', 'apparent_encoding', 'close', 'connection', 'content',
 'cookies', 'elapsed', 'encoding', 'headers', 'history', 'is_permanent_redirect', 
'is_redirect', 'iter_content', 'iter_lines', 'json', 'links', 'ok', 'raise_for_status', 
'raw', 'reason', 'request', 'status_code', 'text', 'url']
127.0.0.1 - - [06/Jul/2017 09:50:18] "GET /api/issues/category/needstriage HTTP/1.1" 304 -
```

So let's print `resource.url` in helpers.py in the api_request function. and I get:

```
https://api.github.com/repos/webcompat/webcompat-tests/issues?labels=status-needstriage
127.0.0.1 - - [06/Jul/2017 09:54:11] "GET /api/issues/category/needstriage HTTP/1.1" 304 -
```

So this is the URL request that is sent to GitHub. GitHub will reply to webcompat.com which in return will send it back to the user. Basically webcompat.com proxy all requests to GitHub.

**Comment by karlcow** [comment]
## About reviews

>in the future is it OK for me to include both you and MikeT as JS reviewers? I know both of you are very busy but your review concerns are a bit different and I think I learn from both forms.

Yes. Perfectly fine. :)

**Comment by cch5ng** [comment]
@karlcow thanks for your time and answers. the app flow is particularly helpful.

> Basically webcompat.com proxy all requests to GitHub.

is that the same as meaning the FE makes a request (like issues) to the BE api which makes a corresponding request to Github's api?

**Comment by karlcow** [comment]
@cch5ng what are FE and BE?

**Comment by zoepage** [comment]
@karlcow FE = Front end, BE = Back end

**Comment by karlcow** [comment]
> is that the same as meaning the FE makes a request (like issues) to the BE api which makes a corresponding request to Github's api?

ok let me try to make a graph of what is happening? So it becomes clearer. The separation is not totally Front-end / Back-end. Or more exactly it's usually better to talk in terms of Request/Response because when you proxy a server is at the same time front-end and back end.

**Comment by karlcow** [comment]
@cch5ng 

It is something which looks  [a bit like this][1]:

![http-diagram](https://user-images.githubusercontent.com/505230/27949280-12091564-6338-11e7-9183-28e72969c79a.png)



[1]: http://www.plantuml.com/plantuml/uml/VP2n3e9044Hxlc939OMXjp1e8reHf30n580RWN1tUBj8-7k14BWOiPytRtOzuaHp8ohhg5LBg66xXnRJJ8awuHtuKHH0YAy6YU6UTd2vWfAGLGLAZgqvEM1JmmnHhIGXR78MbPiHkIMvXKYUI8vfivUIGt2s9_pcXt-yNynOSohORrApm-I3ZdCbUzA8hTkNyIKfwVpohLqx0ePocDtdtgXZoqFvw7_z0G00

```
@startuml
Browser -> webcompat: HTTP Request [by JS on client]
webcompat -> Browser: HTTP Response (html/css/js/images)
Browser -> "webcompat API": HTTP XHR Request [by JS on client]
"webcompat API" -> "GitHub API": HTTP Request [by Python]
"GitHub API" -> "webcompat API": HTTP Response (json)
"webcompat API" -> Browser: HTTP Response (json) [by Python on server]
@enduml
```

**Comment by zoepage** [comment]
Would it be possible to move that to / reference that in our wiki as issues are not ment for documentation purpose? That would be great. Thanks!

**Comment by karlcow** [comment]
@zoepage [Done](https://github.com/webcompat/webcompat.com/wiki/Webcompat.com-Technical-Architecture)
