### ISSUE TITLE
Missing colon and newline in reported bug

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat.com#1643]
![screen shot 2017-07-07 at 11 30 58 am](https://user-images.githubusercontent.com/67283/27967226-d5d5330a-6307-11e7-9a36-cb031a57bee8.png)

We need a colon after `Steps to reproduce`, and a new line would be good too

**Comment by cch5ng** [comment]
@miketaylr I'm not sure I understand the context for your change request.

for #1547, I was working off this doc:
https://docs.google.com/document/d/1uCBbUx7TAZh_nIYn7U18Npceo1xQl_6j36BV-cmy1_g/edit
(see pg 6; also this comment https://github.com/webcompat/webcompat.com/issues/1547#issuecomment-301849726)

for your code review, I made an update to the placeholder to look like this (screenshot of deployed webcompat.com)

![screen shot 2017-07-10 at 10 28 01 am](https://user-images.githubusercontent.com/4755432/28031033-ddcba882-655a-11e7-84f3-1911ca0ae394.png)

are you asking me to change the current label: "How did you get there?" to "Steps to Reproduce:"
also are you asking me to change the current label: "Please describe what was wrong" to "Description:"
and then are you asking me to change the Description field placeholder to be blank (currently "e.g. The video should have started after 3 sec. but this text has been modified in #1617)

**Comment by miketaylr** [comment]
> are you asking me to change the current label

Nah, nothing that complicated. There's just a missing colon after "Steps to Reproduce":

https://github.com/webcompat/webcompat.com/blob/master/webcompat/form.py#L237-L239

(note how Description and Browser / Version have a colon. Just a minor cosmetic thing. And it would look a bit more organized if the "For example," part started on the next line (especially if the user deletes that For example and puts in a long sentence or URL. 

Ideally the end result would be:

```
Steps to Reproduce:
For example,
(the rest here)
```
