### ISSUE TITLE
How did you get there example text could be improved

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat.com#1646]
Instead of populating the textarea, maybe we can use `@placeholder` text? Possibly with some validation for empty text? (Or not, there's a good argument that if an issue has an image, it's still useful)...

```
For example,

    I've tried to log in.
    I've filled out the form details.
    I clicked on the submit button.
    Nothing happened.
```

**Comment by miketaylr** [comment]
cc @cch5ng

**Comment by cch5ng** [comment]
@miketaylr 
> Possibly with some validation for empty text? (Or not, there's a good argument that if an issue has an image, it's still useful)...
I think there was some recent discussion to postpone required content validation for this field: https://github.com/webcompat/webcompat.com/issues/613#issuecomment-311542095

otherwise I'll look at the @placeholder suggestion

**Comment by miketaylr** [comment]
Yeah, I think placeholder is probably what we want, at least to start with. Thanks!

**Comment by miketaylr** [comment]
(relevant comment https://github.com/webcompat/web-bugs/issues/8135#issuecomment-314209963)

**Comment by miketaylr** [comment]
(whoops...)

**Comment by denschub** [comment]
Probably a rude question (😸), but @cch5ng, is this on your list of priorities? Our bug reports get a bit messy with quite a few of them having the dummy text submitted. :)

Also, it's worth noting that placeholder attributes [cannot contain line breaks](http://w3c.github.io/html/sec-forms.html#the-placeholder-attribute), sadly.

**Comment by cch5ng** [comment]
@denschub I don't have an issue with working on this since a couple reprioritized tasks are on hold. actually shortening the placeholder would fix a visual usability issue I was seeing on https://github.com/webcompat/webcompat.com/issues/1662#issuecomment-316862852

how about placeholder text like: "Steps to reproduce this issue"?

in the past it appeared there were lengthy discussions about text changes so I do not know who needs to approve the change (?)

**Comment by cch5ng** [comment]
updating as the requirements of this issue have changed:
* the old default value (list of steps) for the bug form text area was retained but new logic was added

* case 1: (default) the text area has default value only
* case 2: the text area  has default value + prepopulated additional string (ex servo/stylo pref from Nightly or Dev builds)

in both cases,  
 * if the user clicks the text area, the default value (list of steps) should be removed (but prepopulated strings  for bug reporting should remain)
 * if the user submits the form w/o editing the text area, the default value (list of steps) should be removed (but prepopulated strings for bug reporting should remain)

---
probably a couple of functional tests should be added
- [ ] case 1: when user clicks text area...
- [ ] case 2: when user clicks text area... (don't think this can be tested from here, should it be added to Nightly at a future time)

**Comment by miketaylr** [comment]
Closing this, will open a new follow up.
