### ISSUE TITLE
Some icons have disappeared

### ISSUE THREAD

**Issue by magsout** [webcompat/webcompat.com#1647]
Some icons have disappeared: for example, Home, log in (header)

**Comment by magsout** [comment]
![img_3297](https://user-images.githubusercontent.com/1997108/27997979-dd275518-6503-11e7-8870-98b4b594a202.PNG)

**Comment by zoepage** [comment]
@magsout Could you please give more info, like OS or browser as I can't reproduce? Thanks!

**Comment by zoepage** [comment]
Closing as I can't reproduce. We can re-open, when it re-appears. :)

**Comment by miketaylr** [comment]
> Could you please give more info, like OS or browser as I can't reproduce?

That's Firefox for iOS, in his screenshot.

**Comment by miketaylr** [comment]
Also, this reproduces on an iPod. Still a bug.

**Comment by miketaylr** [comment]
@magsout what's the state of remote debugging in Firefox for iOS? Possible? Does this repro in Safari Mobile?

**Comment by zoepage** [comment]
I just ran into the issue with Safari 10.1.1 and a resolution < 600px.

<img width="505" alt="screen shot 2017-07-20 at 4 33 53 pm" src="https://user-images.githubusercontent.com/562354/28423127-7f3ba7aa-6d6a-11e7-8acf-92dda6b95c05.png">

**Comment by miketaylr** [comment]
OK, so def a bug. Can you investigate @zoepage?

**Comment by zoepage** [comment]
I can tonight, yes @miketaylr

**Comment by zoepage** [comment]
After a quick first look the icon fonts are not displayed in a correct way, the contribute icon is a SVG (which works).

**Comment by zoepage** [comment]
Looks like this bug also appears in FF Nightly 56, private mode from time to time (maybe just the first load). 

Safari shows "Unrecognized Content-Security-Policy directive 'manifest-src'", so it's probably a CSP bug related to the manifest. (I feel like this could be related to app cache manifest, not webmanifest. But I also might be totally wrong. :grin: )

**Comment by miketaylr** [comment]
> afari shows "Unrecognized Content-Security-Policy directive 'manifest-src'", so it's probably a CSP bug related to the manifest.

If you want to test that theory you can modify the `add_csp` method here: https://github.com/webcompat/webcompat.com/blob/master/webcompat/helpers.py#L486

**Comment by zoepage** [comment]
Webkit has issues with `manifest-src` and jumps to the fallback, which is `default-src 'none';`.

A work around would be to send a different policy for webkit, like 
```
      "default-src 'self'; " +
        "object-src 'none'; " +
```

But this does not solve the issue here. Investigating further.

**Comment by zoepage** [comment]
Thanks to @denschub and a great debug session, we found it. 
So, Safari 10.1.1 runs CSS2, which has issues with the short notation for font. I'll send in a PR tomorrow latest.

**Comment by miketaylr** [comment]
> Webkit has issues with manifest-src and jumps to the fallback, which is default-src 'none';.

Yeah, seems like they just don't support that yet. Changing default-src to self for everything seems OK. I don't think we have any need for object-src.

**Comment by zoepage** [comment]
Without the object-src we give access to modules, which might add a security issue. 
(At least this is what Freddy Braun from our security team said)

**Comment by miketaylr** [comment]
> Without the object-src we give access to modules, which might add a security issue.
> (At least this is what Freddy Braun from our security team said)

I'm not sure I understand this... can you open a new issue for `manifest-src` and discuss there?

**Comment by mozfreddyb** [comment]
> Without the object-src we give access to modules, which might add a security issue.
> (At least this is what Freddy Braun from our security team said)

To clarify: 
if you do not set object-src to 'none' (explicitly or implicitly via default-src), you'll allow plugins like Flash, Silverlight, ActiveX which can be a similar XSS risk like inline scripts.
