### ISSUE TITLE
“Browser version/Operating System/Tested another version” section should be displayed under “Site URL”

### ISSUE THREAD

**Issue by softvision-oana-arbuzov** [webcompat/webcompat.com#1648]
**URL:** www.webcompat.com  
**Browser / Version:** Firefox 54.0.1, Chrome 59.0.3071.115. 
**Operating System:** Windows 10 Pro

**Steps to Reproduce:**
1. Navigate to: www.webcompat.com.   
2. Tap “Report bug” button.
3. Type in all the info for reporting a bug, set the relevant options and upload a screenshot.
4. Tap “Report” button.
5. After bug is reported observe “Browser version/Operating System/Tested another version” section placement.

**Expected Behavior:**
“Browser version/Operating System/Tested another version” section are displayed under “Site URL”.

**Actual Behavior:**
“Browser version/Operating System/Tested another version” section are displayed under all the details of the bug and screenshot.

**Notes:**
1. It is more relevant to have this info at the beginning of the issue, not at the end, in order to be aware on what Browser/OS was the issue reported. 
2. Screenshots attached.

![buglayoutbefore_new](https://user-images.githubusercontent.com/12184325/28008252-6d5644e0-655f-11e7-8672-f77762e8b720.png)

![layoutsuggestion](https://user-images.githubusercontent.com/12184325/28008257-71605b5c-655f-11e7-845c-a92b67e51390.png)

**Watchers:**
@softvision-sergiulogigan
@softvision-oana-arbuzov

sv;

**Comment by zoepage** [comment]
I can't find the comment, but there was a discussion going on about the placement of the additional info. The decision was made to add it below the other information, but it can be changed easily, if needed.

@adamopenweb @denschub @miketaylr @MDTsai @wisniewskit What do you think?

**Comment by adamopenweb** [comment]
It takes a bit of getting used to the new layout of information. I'm fine with it either way, feels more natural with it all at the top IMO.

**Comment by miketaylr** [comment]
Yeah, I agree with @softvision-oana-arbuzov here, let's stick it up top.

**Comment by zoepage** [comment]
Please note, there is an inconsistency after we change the format (as the report was saved in an old format). We could run a clean up script if it's necessary.
