### ISSUE TITLE
Add detection for Firefox Focus

### ISSUE THREAD

**Issue by karlcow** [webcompat/webcompat.com#1685]
> Btw, this webcompat site doesn't detect Focus, it says the client is Chrome Mobile. I had to manually change it to "Focus".

from https://github.com/webcompat/web-bugs/issues/8470

**Comment by gloomy-ghost** [comment]
UA: `Mozilla/5.0 (Linux; Android 7.1.2) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Focus/1.1 Chrome/59.0.3071.125 Mobile`

**Comment by miketaylr** [comment]
We'll need to get the upstream ua-parser fixed first: https://github.com/webcompat/webcompat.com/blob/master/config/requirements.txt#L13

@karlcow can you file a bug over there and/or send a PR?

**Comment by miketaylr** [comment]
We currently add a label for GeckoView-based Focus. I don't know the future of WebView Focus, but I suspect it won't exist long term. Let's close here.
