### ISSUE TITLE
https://webcompat.com/#contribute link doesn't work as expected

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat.com#1688]
When you visit https://webcompat.com/#contribute, you should see the "Help us improve the web" header -- not issues.

We could fix this with some code similar to this, which would probably live in homepage.js:

https://github.com/webcompat/webcompat.com/blob/8fadbd6463464c5120586583bef8651980e2350e/webcompat/static/js/lib/contributors.js#L20-L29

**Comment by zoepage** [comment]
If this a follow up for #1682 or an issue on live?

**Comment by miketaylr** [comment]
This reproduces on webcompat.com right now, in production.

**Comment by zoepage** [comment]
Hm, weird. Because I can't. So, it is probably related to the loading time of the issues, right? 🤔

**Comment by miketaylr** [comment]
Here's a gif of what I see in DevEdition/55

![hash-contribute](https://user-images.githubusercontent.com/67283/28836552-fa521328-76ae-11e7-9e5f-e7aa57712c03.gif)

**Comment by apoorvasingh17** [comment]
Hello, can I work on this? I'm a beginner....how should I proceed?

**Comment by karlcow** [comment]
@apoorvasingh17 You are welcome to work on any issues. Though we recommend you try to work on one issue at a time. You asked on three issues https://github.com/webcompat/webcompat.com/search?utf8=%E2%9C%93&q=apoorvasingh17+&type=Issues

1. Get the environment ready following instructions in CONTRIBUTING.md See @denschub comment on other issues.
2. Tackle one issue
3. When it's finished work on another one.

**Comment by karlcow** [comment]
@apoorvasingh17 I also see that you have unfinished code on other activities. Maybe better to focus on those before tackling another project.
https://github.com/apoorvasingh17?tab=overview&from=2017-07-26

**Comment by apoorvasingh17** [comment]
@karlcow I was waiting for a response on my PR, it got merged today.
Now I would work on this one.

**Comment by zoepage** [comment]
This one is btw still up for grabs as @apoorvasingh17 is working on another bug.

**Comment by kritisingh1** [comment]
Hi @zoepage I would like to take up this issue. Please assign this to me

**Comment by zoepage** [comment]
cool @kritisingh1! enjoy :)

**Comment by kritisingh1** [comment]
Hi @Ola Gasidlo
I am stuck in the setup process as I don't have any client id and client
secret issued by your organization. What should I do now?

**Comment by zoepage** [comment]
@kritisingh1 
Open the link below in the browser of your choice and fill out the form.
👉  https://github.com/settings/applications/new 👈. 

The homepage URL is http://localhost:5000/
The Authorization callback URL http://localhost:5000/callback

**Comment by Obtin** [comment]
@miketaylr @zoepage is anybody still working on this? If not, I would like to work on it. Thank you.

**Comment by zoepage** [comment]
@Obtin feel free to grab that issue :)

**Comment by Obtin** [comment]
@zoepage I would like to work on this issue first. Thank you.

**Comment by miketaylr** [comment]
We should probably retire this bug, since it will be obsolete when the refactor lands.
