### ISSUE TITLE
upgrade npm lodash to 4.0.0

### ISSUE THREAD

**Issue by karlcow** [webcompat/webcompat.com#1699]
From #1679 

>The blocker is using lodash templates. I have a plan to do pre-compiled template functions, which should let us maybe even reduce the size of our lodash build we send over the wire (since we won't need template parsing).

This morning I had to install a new module. Doing that, npm warned me about lodash 2.4.2 not being maintained anymore.

```
→ grunt
>> Local Npm module "grunt-contrib-jst" not found. Is it installed?
Warning: Task "jst" not found. Use --force to continue.

Aborted due to warnings.

(webcompatcom) 08:48:43 ~/code/webcompat.com
→ npm install
npm WARN deprecated lodash@2.4.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0

```

**Comment by miketaylr** [comment]
We use lodash 3.10.1 in the app: https://github.com/webcompat/webcompat.com/blob/master/webcompat/static/js/vendor/lodash.custom.min.js

I *think* that npm error is complaining that `grunt-contrib-jst` has an older lodash dependency:

https://github.com/gruntjs/grunt-contrib-jst/blob/master/package.json#L20

**Comment by karlcow** [comment]
Thanks @miketaylr 

When doing `npm run setup` on a fresh clone  of webcompat.com 

```
npm WARN deprecated postcss-cssnext@2.11.0: 'postcss-cssnext' has been deprecated in favor of 'postcss-preset-env'. Read more at https://moox.io/blog/deprecating-cssnext/
npm WARN deprecated gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
npm WARN deprecated @dojo/interfaces@0.2.1: @dojo/interfaces is deprecated
npm WARN deprecated lodash@2.4.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0
npm WARN prefer global coffeescript@1.10.0 should be installed with -g

```

**Comment by miketaylr** [comment]
I don't think this is actionable.
