### ISSUE TITLE
webcomat issue with CSP LVL3 in webkit

### ISSUE THREAD

**Issue by zoepage** [webcompat/webcompat.com#1701]
Follow up for https://github.com/webcompat/webcompat.com/issues/1647#issuecomment-319665648

@miketaylr 
In https://github.com/webcompat/webcompat.com/blob/master/webcompat/helpers.py#L496
`manifest-src` is not supported in webkit as it has a partial implementation of CSP LVL3: https://webkit.org/status/#?search=csp

The `manifest-src` is not supported and jumps to `default-src`, which is set to `none`. 
https://w3c.github.io/webappsec-csp/#directive-manifest-src

When we change the `default-src` to `self` anything else without an explicit directive is set on self too. So this is why we set `object-src`to none to prevent that issue. This also seems like a "best practice" thing. 

In addition, because it's a handy tool && for documentation purpose: https://csp-evaluator.withgoogle.com/

**Comment by miketaylr** [comment]
> When we change the default-src to self anything else without an explicit directive is set on self too. So this is why we set object-srcto none to prevent that issue.

Got it, thanks!

**Comment by zoepage** [comment]
This was fixed, but I put in `fixes` not `fix` or `fixed`, so it was not closed automatically :D
