### ISSUE TITLE
Highlight search bar on clicking icon

### ISSUE THREAD

**Issue by ayushi-jain97** [webcompat/webcompat.com#1705]
![webcompat](https://user-images.githubusercontent.com/19989931/29004883-b6c5d986-7aec-11e7-9877-1bf6df2ca206.jpg)

On clicking the search icon (red), the search box (blue) should be highlighted. Also, the cursor should jump to the text area.

**Comment by zoepage** [comment]
Thanks for the report. This is already on our roadmap for the refactor of the site. :)

**Comment by karlcow** [comment]
Thanks @ayushi-jain97 
@zoepage do you mean #1296 ?

**Comment by zoepage** [comment]
@karlcow no, but I can't find the issue (looked for 30 minutes).

But it's planed out in the [mocks](https://github.com/webcompat/design/blob/master/website_modules/) and belongs to our [list of accessibility features](http://a11yproject.com/checklist.html), we want to implement.

**Comment by ankitbug94** [comment]
> On clicking the search icon (red), the search box (blue) should be highlighted. Also, the cursor should jump to the text area.

Hi all!
This is my first post in this category. Basically, this is a request to [focus](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/focus) the input [element](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Input). This is implemented in various ways all over the internet. Though, the suggested way is good that focus the element if the text is empty but there can be something like stackoverflow.com too that searches the empty string. Currently, webcompat is just neglecting if the input is empty which is also fine and not an issue IMHO.

**Comment by zoepage** [comment]
Related to https://github.com/webcompat/webcompat.com/issues/1488

**Comment by magsout** [comment]
This issue is about the old design. So we can close ?

**Comment by magsout** [comment]
ah, the behavior is the same on the new design..

**Comment by karlcow** [comment]
We can close it. Because the new design is kind of working. There are not anymore UX issues related to this in the new design.
