### ISSUE TITLE
"How did you get there" text should be removed (for now)

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat.com#1707]
It should get cleared out, rather than submitted to the server.

Note: We can't use `@placeholder` because linebreaks aren't allowed (which is lame).

See also #1646.

**Comment by karlcow** [comment]
I was just curious. so I did this.
http://imgur.com/a/OhEGT
Firefox, Safari and Chrome. Only Chrome seems to interpret a bit of special characters in placeholder.

Then maybe we are abusing the placeholder in our case: https://html.spec.whatwg.org/multipage/input.html#attr-input-placeholder

> The placeholder attribute represents a short hint (a word or short phrase) intended to aid the user with data entry when the control has no value. A hint could be a sample value or a brief description of the expected format. The attribute, if specified, must have a value that contains no U+000A LINE FEED (LF) or U+000D CARRIAGE RETURN (CR) characters.
> 
> The placeholder attribute should not be used as an alternative to a label. For a longer hint or other advisory text, the title attribute is more appropriate.

**Comment by karlcow** [comment]
https://www.nngroup.com/articles/form-design-placeholders/

**Comment by miketaylr** [comment]
@karlcow do you think we should just have no placeholder and an empty textarea? It's certainly easier to implement. :)

**Comment by karlcow** [comment]
My growing impression yes. And gives the instructions on the side or before/after.

**Comment by miketaylr** [comment]
I don't really want to do another redesign of the form (since we plan to do that at some future point), so I propose we remove all placeholder text now and see how it goes.

**Comment by karlcow** [comment]
Post Rationale. We get a lot of bug reports with the boilerplate as-is and not remove, which is confusing for people reviewing the issue report. Better to remove it until we find a better way to do this.

**Comment by zoepage** [comment]
Just got a weird, but maybe fun idea.

How about we add the placeholder text as a background image, that disappears when `focus`or the value is `>0`? It would at least be a work around?
