### ISSUE TITLE
generate test coverage report

### ISSUE THREAD

**Issue by zoepage** [webcompat/webcompat.com#1714]
As intern has a build in way to create a test coverage report, I feel like this is something we should have. I started yesterday to play around with it and got it running partially.

I've added following to the config obj in https://github.com/webcompat/webcompat.com/blob/master/tests/intern.js
```
coverage: [
        "/webcompat/static/js/*.js",
        "/webcompat/static/js/**/*.js",
        "/webcompat/static/js/**/**/*.js"
    ],

    filterErrorStack: true,
    reporters: ["Pretty", "LcovHtml"], // LcovHtml generates a html site for the report
```

The report is empty.
<img width="1427" alt="screen shot 2017-08-15 at 9 56 36 am" src="https://user-images.githubusercontent.com/562354/29307092-b657956a-81a0-11e7-916d-f946396a6a8e.png">

What am I missing? 0_o

@brizental any idea?

**Comment by brizental** [comment]
@zoepage Yeah, I saw that, but haven't tried it yet. I agree that we should have it.

I'll have a look at it today and get back here. Don't know why it's not generating anything.

**Comment by brizental** [comment]
Hey @zoepage , it took me a while but I think I understand what is going on here. I'm not really sure, but maybe you can help me out.

There's this information on the Intern.js documentation (https://theintern.github.io/intern/#reporter-lcov):

> Generally speaking, code coverage reporters will never work directly from the browser client because they require code to be instrumented in order to collect coverage data.

I guess this means that code coverage will only work when using the Node.js client for the tests, and since our tests run in a remote browser it can't generate  any reports.

**Comment by zoepage** [comment]
Good catch @brizental! We could use https://www.npmjs.com/package/istanbul as it supports it.
What do you think?

**Comment by karlcow** [comment]
> I feel like this is something we should have. 

@zoepage Could you share a bit more or explain why we should have them.

**Comment by zoepage** [comment]
@karlcow 

Code coverage indicates how much of the code is tested. The reports shows exactly which functions are tested and which not, which makes it easier to see which tests are still missing. 
(This is very handy, as we had issues in the past where code was failing and we realized after that tests were missing.) 

A solid code coverage is also a good indicator for new contributors for how well maintained the code is in this project and build trust, they will not break things when contributing. They just need to run the tests.

**Comment by karlcow** [comment]
* Code coverage (quality tool)
* Coverage report (console, html)

I'm familiar with coverage. It exists [in python](https://coverage.readthedocs.io/). I used it a long time ago on some projects. My worries are about the distraction it creates, aka people focus on 100% coverage tests and start fixing the project for achieving this goal, instead of focusing on developing user-facing features (**with tests** ideally in a test driven way).  It will mean also time to review the contributed code on improving the code. 

And maybe also because we are not really developing a product (aka something which we want to see bloom with many instances.) webcompat.com code is a tool for a mean. It's not like developing a library used by many people in their own projects.

To note that I'm not against it. I understand the appeal but I doubt about the value when we have so many other things. (The same way **I want** to switch to python 3 #1332, but I'm not pushing too hard on it, because well the project is currently working and the value, the burden of migration makes it a lower priority.)

**Comment by zoepage** [comment]
@karlcow 
> start fixing the project for achieving this goal, instead of focusing on developing user-facing features

I get your point here, but I've realized that in the past few months missing tests were the main issue for a lot of bugs we've experienced and had to fix, which was the main reason for us not having much time to work on new features or focus on other important things. I don't think, we need a 100% coverage, but we should at least be aware of how much we have, which parts of the code we test exactly and have the possibility to make the conscious decision which tests are necessary and which are not. 

I used to contribute to projects with 100% coverage, where I wrote a lot of the tests by myself. I see a huge advantage in a good coverage, especially in open source projects. You do not to be aware of all the code before you contribute, as the tests will tell you, if something went really wrong. It also cuts down the review time for PR's when you can rely on tests (I like to take my time when review to make sure nothing broke).

**Comment by zoepage** [comment]
@miketaylr I got this working, but it fails to generate a report as the tests are failing for me 🙈
Maybe you'd like to test it?

```
$ git checkout issues/1714
$ npm i
$ npm run start:test
$ npm test
```

**Comment by miketaylr** [comment]
@zoepage I'm not familiar with istanbul. Rather than learn it, I think we should table it for a post-refactor task so we can fix the remaining P0 and P1 bugs.

**Comment by zoepage** [comment]
@miketaylr istanbul is just a task runner and it was a 5 minute fix. 
but we can postpone it.

**Comment by miketaylr** [comment]
> @miketaylr istanbul is just a task runner and it was a 5 minute fix.
> but we can postpone it.

(my comment was n reply to why you get that error... i'm not sure, sorry)

**Comment by zoepage** [comment]
> (my comment was in reply to why you get that error... i'm not sure, sorry)

ah, i see. the issue is that my tests are failing. this is why there is no report generated. I thought, you might want to test it on your machine as yours passed the last time.

**Comment by miketaylr** [comment]
This might help us: https://github.com/theintern/digdug/issues/60#issuecomment-373849751

**Comment by miketaylr** [comment]
I'm gonna see if I can get this working, there's a related failure on master in #2285.

**Comment by miketaylr** [comment]
> I'm gonna see if I can get this working, there's a related failure on master in #2285.

<img width="1792" alt="screen shot 2018-03-22 at 3 54 25 pm" src="https://user-images.githubusercontent.com/67283/37798619-482677da-2deb-11e8-988e-32fbf089c113.png">


I can get the coverage report generated, but it's showing 0% test coverage. Not something I care to mess with any longer, if someone wants to pick it up, here's what I did:

```
commit a677d38d3b56809f6b2aeb883104de2855e7a019
Author: Mike Taylor <miketaylr@gmail.com>
Date:   Thu Mar 22 16:05:41 2018 -0500

    Experiment with adding coverage.

diff --git a/.gitignore b/.gitignore
index 33340f35..393cda43 100644
--- a/.gitignore
+++ b/.gitignore
@@ -6,8 +6,7 @@ config.py
 fabfile.py
 *.pyc
 *.db
-docs/build/
-screenshots/
+coverage/
 uploads/
 .idea/
 .vscode/
diff --git a/tests/functional/_intern.js b/tests/functional/_intern.js
index 8215ffb5..a0717133 100644
--- a/tests/functional/_intern.js
+++ b/tests/functional/_intern.js
@@ -53,10 +53,21 @@ intern.configure({
     drivers: ["firefox", "chrome"]
   },
 
+  coverage: [
+    "!webcompat/static/js/*.js",
+    "!webcompat/static/js/vendor/*.js",
+    "webcompat/static/js/templates.js",
+    "webcompat/static/js/lib/**/*.js",
+    "webcompat/static/test-files/functional/lib/window-helpers.js"
+  ],
+
+  functionalCoverage: true,
+
   environments: environments,
 
   filterErrorStack: true,
   reporters: [args.reporters ? args.reporters : "pretty"],
+  "reporters+": "htmlcoverage",
 
   functionalSuites: ["./tests/functional/*.js"]
 });
```

Some links that will be helpful:

https://github.com/theintern/intern-tutorial#step-5-code-coverage

intern by default uses istanbul under the hood:

https://istanbul.js.org/docs/tutorials/intern/

**Comment by zoepage** [comment]
thanks @miketaylr for giving it a try :)

**Comment by Regaddi** [comment]
I think it's currently hard to solve, because the JavaScript source files are processed "manually" in multiple steps (concat and uglify) and we're not generating source maps in both steps. Possibly it could work with source maps.

**Comment by karlcow** [comment]
Should this be put in backlog mode?

**Comment by miketaylr** [comment]
> Should this be put in backlog mode?

I think so. I don't see a lot of immediate value from working on this now.

**Comment by karlcow** [comment]
Let's close it for now. We can reopen if the opportunity comes around.
