### ISSUE TITLE
Fix for alexa topsite deployment

### ISSUE THREAD

**Issue by MDTsai** [webcompat/webcompat.com#1726]
- Fix to use HTTPS instead of HTTP
- Adjust the parameter sequence, origin move AWSAccessKeyId to first

@miketaylr ,do we need to read the key from config or keep using in argument?

**Comment by miketaylr** [comment]
If we're running as cronjob, using as an argument seems fine (and reduces risk of leaking key). We could also store the key as an environment variable on the server and have the config read from that.

What do you think is better?

**Comment by MDTsai** [comment]
Agree with cronjob with key in arguments. There is no more change need, I will send PR.
