### ISSUE TITLE
Update new issue webhooks

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat.com#1751]
Currently it adds a `status-needstriage` label. We want to add the correct milestone on issue creation.

#886.

**Comment by MDTsai** [comment]
Looks like we can just remove the needstriage label while creation in 
https://github.com/webcompat/webcompat.com/blob/d2ba4dd1667801e09d4bd192b553fac50d485b59/webcompat/webhooks/helpers.py#L111
