### ISSUE TITLE
Update /issues/new form endpoint to add needstriage milestone

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat.com#1752]
We can automatically assign a milestone upon issue creation.
https://developer.github.com/v3/issues/#create-an-issue (see `milestone` param)

#1751 #886.

**Comment by MDTsai** [comment]
I guess it could be done to insert something near here:
https://github.com/webcompat/webcompat.com/blob/d2ba4dd1667801e09d4bd192b553fac50d485b59/webcompat/views.py#L201
and depends on the result of #1761

**Comment by karlcow** [comment]
Closed by #1774
