### ISSUE TITLE
Wire up milestone editor with milestone backend

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat.com#1753]
So when you change a milestone, it communicates that change with GitHub and syncs the UI.

#886. 

Depends on #1745, related to #1748.

**Comment by miketaylr** [comment]
(essentially #1766)

**Comment by miketaylr** [comment]
Need to send a dict with milestone integer and state to the /issues/N/edit endpoint:

`{'milestone': 2, 'state': 'open'}`

**Comment by miketaylr** [comment]
Depends on #1782.

**Comment by karlcow** [comment]
Fixed by #1787
