### ISSUE TITLE
Handle color schemes for milestones

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat.com#1754]
We currently get the values from GitHub via the label, but this doesn't exist for milestones. So we need a serverside/config solution.

#886.

**Comment by miketaylr** [comment]
This will come from the config. #1761. Right now it's empty.

environment.py will have the colors eventually.

**Comment by MDTsai** [comment]
@magsout @zoepage we may need your input to move to next step. We can refer 2 sources, 1st is currentissue label's color. 2nd is in [style-variable.css](https://github.com/webcompat/webcompat.com/blob/master/webcompat/static/css/development/components/style-variable.css#L16-L23) for .wc-Issue-information-header (I guess).

2nd list is not a complete list for all milestones, so I prefer to manually copy from the 1st list to the dict.

**Comment by MDTsai** [comment]
Now I use the first list and use type-flash/nsfw for non-compat.

**Comment by karlcow** [comment]
Fixed by #1786
