### ISSUE TITLE
Update label-list.js to know about milestones

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat.com#1758]
Possibly we just need to unteach it about `status-`?

https://github.com/webcompat/webcompat.com/blob/master/webcompat/static/js/lib/models/label-list.js#L27

#886.

**Comment by miketaylr** [comment]
Yeah, just remove status stuff once we delete those labels. Doesn't need to know about milestones.

**Comment by karlcow** [comment]
This line 

https://github.com/webcompat/webcompat.com/blob/0ea702ebba61fd2e887a24768c4f79e4b0613875/webcompat/static/js/lib/models/label-list.js#L27

is only filtering out the namespace when displaying the labels. Even if we moved the `status-*` to milestones, we still have one `status-` which is `needinfo`. So I guess this is still useful.
