### ISSUE TITLE
Remove the close/reopen button

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat.com#1760]
These are the closed milestones:

wontfix, incomplete, invalid, fixed, duplicate, worksforme, non-compat

(we can update issue status when changing milestone)

#886. #1305.

**Comment by miketaylr** [comment]
This might be JS... or Python, I don't remember. :P

**Comment by MDTsai** [comment]
Also enforce reopen to have a milestone.

**Comment by MDTsai** [comment]
Begin here:
https://github.com/webcompat/webcompat.com/blob/03b0da41a8615f160a90529fef51dea64352d0c6/webcompat/templates/issue/issue-comment-submit.html#L19

Maybe I can share #1745 and use part of it?

**Comment by MDTsai** [comment]
After discussion, if the close/reopen button can change the status milestone as the milestone editor in #1745, that might be complex and confused.
The milestone editor widget will be able to change the milestone and reopen/close issue if necessary. Then we don't need a close/reopen button now. @zoepage 
I would move the issue to remove the close/reopen button as an UI issue.

**Comment by MDTsai** [comment]
List TODOs:
- [ ] Remove close/reopen button in https://github.com/webcompat/webcompat.com/blob/master/webcompat/templates/issue/issue-comment-submit.html#L19-L21
- [ ] Remove https://github.com/webcompat/webcompat.com/blob/master/webcompat/templates/issue/state-button.jst
- [ ] Remove functional test in https://github.com/webcompat/webcompat.com/blob/master/tests/functional/comments-auth.js#L39-L78
- [ ] Remove functional test in https://github.com/webcompat/webcompat.com/blob/master/tests/functional/issues-auth.js#L30-L57
- [ ] Remove View in https://github.com/webcompat/webcompat.com/blob/master/webcompat/static/js/lib/issues.js#L310-L381
