### ISSUE TITLE
Create mapping for milestones to API integers

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat.com#1761]
So it's less annoying to deal with them.

#886.

**Comment by karlcow** [comment]
@miketaylr @MDTsai Some thoughts.

To request the list of issues associated we need the milestone number:

For example here a request getting all the needstriage issue (milestone=2).

https://api.github.com/repos/webcompat/webcompat-tests/issues?sort=created&direction=desc&milestone=2&state=open&per_page=50&page=1

The milestone number will change in between the repos. So it needs to be dynamically generated. But at the same it seems dumb to request it every time, when they usually never change or just when a project has been modified or the repo has been changed.

One possibility for run.py to requests the list of milestones and to store in the project memory a variable with the dictionary of `{"milestones name": milestone number, }`

To get the list of milestones we just need to do
https://api.github.com/repos/webcompat/webcompat-tests/milestones

This is related to #1749 and

**Comment by karlcow** [comment]
To make it less likely to break let's say we do this:

1. `python run.py`
2. Make a request to the Github api to list milestones
3. With the HTTP response:
  - if `200`, use this data stored in memory **AND** make a local dump in `data/`
  - if `4*`, use the cached copy in `data/` and load it in memory.
  - if something else, just don't start the project.

Like this @miketaylr would feel more comfortable. 😉

**Comment by karlcow** [comment]
@miketaylr Currently on webcompat-tests

```python
app.config['MILESTONES'] == {
    u'worksforme': 11, 
    u'non-compat': 12, 
    u'needscontact': 3, 
    u'invalid': 8, 
    u'needstriage': 1, 
    u'duplicate': 10, 
    u'needsdiagnosis': 2, 
    u'sitewait': 5, 
    u'wontfix': 6, 
    u'fixed': 9, 
    u'incomplete': 7, 
    u'contactready': 4}
```

**Comment by miketaylr** [comment]
It would be cool if we could have a data format like so, to help control the ordering, and to split between closed and open milestones:

```
{
  'needsdiagnosis': {id: 2, state: 'open', order: 2},
  'needshamburgers': {id: 3, state: 'open', order: 1},
...
}
```

**Comment by karlcow** [comment]
@miketaylr 

```
>>> MILESTONES = { 'worksforme': {'id': 1, 'order': 10, 'state': 'closed'}, 'sitewait': {'id': 2, 'order': 5, 'state': 'open'} }
>>> import json
>>> json.dumps(MILESTONES)
'{"worksforme": {"state": "closed", "id": 1, "order": 10}, "sitewait": {"state": "open", "id": 2, "order": 5}}'

```

**Comment by miketaylr** [comment]
Merged into milestones branch, so let's close.
