### ISSUE TITLE
Add template watching to Grunt watch task

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat.com#1763]
something like this would do it:

```
    templates: {
      files: "<%= tmplPath %>/**/*.jst",
      tasks: ["jst"]
    }
```

Bonus points for fixing the script task, it throws an error due to a missing `jshint` var (which we don't use anymore).

**Comment by miketaylr** [comment]
The change should be made here:

https://github.com/webcompat/webcompat.com/blob/master/grunt-tasks/watch.js

**Comment by miketaylr** [comment]
(and to test that it works, run `npm run watch`, make a change to any `.jst` file and watch the console output)

**Comment by amitsin6h** [comment]
want to work on this assign me

**Comment by miketaylr** [comment]
Sorry about missing this @amitsin6h (I get notifications that mention my name faster...). Are you still interested in making a contribution here?

**Comment by miketaylr** [comment]
(You can go ahead and send in a PR without it being assigned, btw!)

**Comment by amitsin6h** [comment]
@miketaylr ok

**Comment by karlcow** [comment]
@amitsin6h Did you see/read https://github.com/webcompat/webcompat.com/blob/master/CONTRIBUTING.md ?

**Comment by Obtin** [comment]
@karlcow @miketaylr  If nobody is working on it, I would like to work on this issue.
Thank you.

**Comment by zoepage** [comment]
@Obtin Please check https://github.com/webcompat/webcompat.com/blob/master/CONTRIBUTING.md as we have a `one issue at the time` policy for first timers. 

Just choose between the two you asked to work on and post a comment, you are working on it. :)

**Comment by Obtin** [comment]
@zoepage I would like to work on this first. 
Thank you.

**Comment by Obtin** [comment]
@zoepage I made the following changes in grunt-tasks/watch.js file . I guess this fixed the "jshint" warning yet the output is not appropriate.
![webcompat](https://user-images.githubusercontent.com/25207205/34460860-48dc89a6-ee41-11e7-898f-a41aa340a308.png)

**Comment by zoepage** [comment]
@Obtin Could you please send a PR? It makes it easier to discuss and test the changes.
After sending it, please add `r? @zoepage` or / and `r? @miketaylr` to your comment. thanks!

**Comment by Obtin** [comment]
@zoepage done.Please see to it. Thank you.
