### ISSUE TITLE
" The data body sent to GitHup API." test in test_form.py failure in milestones branch

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat.com#1779]
(also note the typo :P)

```
1.24s$ nosetests

.........F......................................................

======================================================================

FAIL: The data body sent to GitHup API.

----------------------------------------------------------------------

Traceback (most recent call last):

  File "/home/travis/build/webcompat/webcompat.com/tests/test_form.py", line 121, in test_build_formdata

    self.assertEqual(actual, expected)

AssertionError: {'body': u'<!-- @browser: None -->\n<!-- @ua_header: None -->\n<!-- @reported_wi [truncated]... != {'body': u'<!-- @browser: None -->\n<!-- @ua_header: None -->\n<!-- @reported_wi [truncated]...

  {'body': u'<!-- @browser: None -->\n<!-- @ua_header: None -->\n<!-- @reported_with: None -->\n\n**URL**: None\n\n**Browser / Version**: None\n**Operating System**: None\n**Tested Another Browser**: Unknown\n\n**Problem type**: Unknown\n**Description**: None\n**Steps to Reproduce**:\nNone\n\n\n\n_From [webcompat.com](https://webcompat.com/) with \u2764\ufe0f_',

-  'milestone': 0,

   'title': 'None - unknown'}

----------------------------------------------------------------------

Ran 64 tests in 0.927s

FAILED (failures=1)
```

**Comment by miketaylr** [comment]
See here: https://travis-ci.org/webcompat/webcompat.com/builds/272417023#L674

**Comment by MDTsai** [comment]
TODO: 

- [ ] Mock the **app.config['STATUSES']['needstriage']['id']** with specific value. M
- [ ] Add milestone: ID to **expected** dict.

**Comment by karlcow** [comment]
My bad for not spotting it.

@MDTsai It's an easy fix. You just need to add the missing value in the expected variable.

https://github.com/webcompat/webcompat.com/blob/0ea702ebba61fd2e887a24768c4f79e4b0613875/tests/test_form.py#L112-L121

And indeed it could be fixed in #1774 pull request directly.

**Comment by karlcow** [comment]
just a missing `'milestone': 0,`. The exact value for now maybe doesn't matter that much. Given this test is just here to check that we are sending the right parameters. All the information is fake in that body.

**Comment by karlcow** [comment]
Closed by https://github.com/webcompat/webcompat.com/pull/1774/commits/a6d217d5ddfda2796d0242e5f9b4955b6077f299
