### ISSUE TITLE
Make it so you can only check a single milestone in the milestone editor

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat.com#1780]
So selecting a new one will unselect the current one.

We have similar code here:

https://github.com/webcompat/webcompat.com/blob/0ea702ebba61fd2e887a24768c4f79e4b0613875/webcompat/static/js/lib/labels.js#L146-L162

**Comment by MDTsai** [comment]
basically it's here https://github.com/webcompat/webcompat.com/blob/milestones/webcompat/static/js/lib/milestones.js#L73
also get checked one then uncheck all the others.

**Comment by karlcow** [comment]
Why don't we use `type="radio"`

**Comment by miketaylr** [comment]
> Why don't we use type="radio"

Let's re-visit once we have a working version as-is.
