### ISSUE TITLE
Milestones label information in issues list view

### ISSUE THREAD

**Issue by karlcow** [webcompat/webcompat.com#1806]
Currently the issues list view look like this

<img width="475" alt="capture d ecran 2017-09-08 a 12 03 47" src="https://user-images.githubusercontent.com/505230/30195740-0a33d234-948e-11e7-959a-38da74b12f94.png">

The markup is 

```html
<span class="wc-IssueList-status js-Issue-status">
     <a href="/issues?q=milestone:sitewait" 
       class="wc-Labels" 
       data-remotename="sitewait" 
       title="Status : sitewait">sitewait</a>
</span>
```

This might need to be slightly redesigned.

**Comment by zoepage** [comment]
@karlcow 
> This might need to be slightly redesigned.

This will be redesigned with https://github.com/webcompat/design/blob/master/website_modules/issues_list/Desktop%20HD.png

**Comment by karlcow** [comment]
<img width="1220" alt="screen shot 2017-10-30 at 12 56 55 pm" src="https://user-images.githubusercontent.com/505230/32203391-5cdeea20-be26-11e7-8cbe-426cee537e73.png">


```css
.wc-IssueList-status.js-Issue-status {
	text-align: right;
}
```

<img width="1004" alt="capture d ecran 2017-10-31 a 10 26 45" src="https://user-images.githubusercontent.com/505230/32203355-220d0d0a-be26-11e7-908d-04a534b57b77.png">

**Comment by karlcow** [comment]
This should probably fixes the major issue before the new design.

**Comment by miketaylr** [comment]
Yeah, we should deploy an easy fix like this ASAP, especially since it's a one line CSS fix.

**Comment by karlcow** [comment]
ok done. Let's make a PR.

<img width="2564" alt="capture d ecran 2017-11-01 a 09 19 50" src="https://user-images.githubusercontent.com/505230/32254703-dc4d2820-bee5-11e7-9996-e7171aeb2dae.png">

**Comment by karlcow** [comment]
PR done. https://github.com/webcompat/webcompat.com/pull/1855
