### ISSUE TITLE
Add class to js-CategoryEditor to know specific editor

### ISSUE THREAD

**Issue by MDTsai** [webcompat/webcompat.com#1807]
#1804 fix the click outside but not good. We can add class to editors to know if the other one is exactly opened then close it.

**Comment by miketaylr** [comment]
Yeah, we shouldn't try to close it if it's not open.

**Comment by miketaylr** [comment]
I think this is also the cause of another bug...

If you set a label (by closing the label editor), it will call closeEditor on the milestones editor -- then try to update milestone status and throw.

```
TypeError: statusObject is undefined
milestones.js:47:9
updateMilestone
http://localhost:5000/js/lib/models/milestones.js:47:9
closeEditor
http://localhost:5000/js/lib/milestones.js:88:7
closeEditor
http://localhost:5000/js/lib/milestones.js:26:5
closeCategoryEditor
http://localhost:5000/js/lib/issues.js:354:9
r
http://localhost:5000/js/vendor/lodash.custom.min.js:26:149
dispatch
http://localhost:5000/js/vendor/jquery-1.11.2.min.js:3:8497
add/r.handle
http://localhost:5000/js/vendor/jquery-1.11.2.min.js:3:5235
```

**Comment by karlcow** [comment]
@MDTsai @miketaylr What do we need to do to fix this one?

**Comment by karlcow** [comment]
We are very close to the finish line.

**Comment by miketaylr** [comment]
I can work on this tomorrow. Hoping to make as much progress by EOW...

**Comment by miketaylr** [comment]
I'm gonna close this as a dupe of #1820 (this came first, but @karlcow has some better analysis in that one, I think it's the same bug).
