### ISSUE TITLE
Priority Labeling Criteria

### ISSUE THREAD

**Issue by softvision-oana-arbuzov** [webcompat/webcompat.com#1824]
According to the weekly meeting discussion:
"Mike: Also, new bugs should have a priority label assigned now, since Eric landed his stuff.
Oana: What's the source for deciding which priority label gets assigned?
Mike: Currently it's the Top X list from Alexa. We might develop a smarter solution in the future, but for now, Top 100(?) websites will get assigned the critical label and so on.
Oana: It was a bit weird seing a "cropped text" issue with "critical" priority
Mike: Yes, it might be good to file an issue for that to get the discussion started."

Currently, after reporting an issue:
"Priority" criteria is automatically  set according to Top X list from Alexa, with 3 states (#1533):
- priority-critical
- priority-normal
- priority-low

Sometimes, this is no sufficient when investigating/prioritizing/fixing an issue. 
What other approaches could be useful?

**Comment by softvision-oana-arbuzov** [comment]
I would suggest adding a "Severity" drop-down menu in the webcompat.com reporting web form with 3 states:
- severity-critical
- severity-normal
- severity-low

The Severity should be set by users according to the impact the issue has on him or automatically according to the "Type of bug".
e.g 
- Severity-critical: Layout fully messed up/Site not usable/Desktop site instead of mobile site/Video or - audio doesn't play
- Severity-normal: Design is broken (cropped text/distorted buttons/misaligned items/overlapped items)
- Severity-low: Something else (page flicker/different design/color/background/text style/transition/choppy scrolling/navigation).

**Comment by miketaylr** [comment]
cc @MDTsai

**Comment by MDTsai** [comment]
#1533 is set priority according to the site importance. Definitely we can still adjust manually if severity is low. As a daily contributor doing triage with @karlcow  @adamopenweb , two labels seems too complex for me.
I'm thinking if we can map the priority into different rating, like site importance, severity, anonymous reporter, clear STR. High priority means we can easily push this issue to next step.

**Comment by karlcow** [comment]
The priority is indeed a rating based on the ranking of the issue more than the quality of the issue.
It means that if two sites have similar problems on foobar.example.com and wellknown.example.org, the wellknown.example.org gets priority in processing treatment.

**Comment by karlcow** [comment]
And forgotten to add. There are issues for known Web sites, that I put on "one day queue" because the issue is minor, and it's better to focus on things which are really broken.

**Comment by zoepage** [comment]
This issue seems to be solved?

**Comment by karlcow** [comment]
This has been fixed by #1594
