### ISSUE TITLE
Use Description for the title instead of the radio button text when it has been filled

### ISSUE THREAD

**Issue by karlcow** [webcompat/webcompat.com#1828]
See for example https://webcompat.com/issues/9602
It would probably be better to feed the title with the Description field than the current title after the domain name.

**Comment by karlcow** [comment]
To modify 
https://github.com/webcompat/webcompat.com/blob/016f0ee80157dc6dd2430fad1d245c589a52b9a3/webcompat/form.py#L105-L113

using https://github.com/webcompat/webcompat.com/blob/016f0ee80157dc6dd2430fad1d245c589a52b9a3/webcompat/form.py#L221

**Comment by karlcow** [comment]
1. if description is not empty - use it
2. fall back on the current code.

**Comment by karlcow** [comment]
It would also avoid @webcompat/collaborators to not have to reedit the title by hand.

**Comment by zoepage** [comment]
@karlcow Would there be a max of characters or would we use the whole description text?

**Comment by karlcow** [comment]
@zoepage I don't know. We need to look at the data.

TODO: Check the current length of descriptions.

**Comment by karlcow** [comment]
to give context to @Obtin and the discussion in #1992 

This is what I'm proposing when I say description should go in the title and issue summary.

![proposal-description](https://user-images.githubusercontent.com/505230/34556570-24c7f60e-f17a-11e7-95e9-c43d31b468d4.jpg)

**Comment by miketaylr** [comment]
> This is what I'm proposing when I say description should go in the title and issue summary.

(I think this would be a big improvement)

**Comment by Obtin** [comment]
@karlcow I totally got your point. :-)

**Comment by zoepage** [comment]
>> This is what I'm proposing when I say description should go in the title and issue summary.

> (I think this would be a big improvement)

I agree. The only reason we didn't tackle this yet was:

@karlcow 
> TODO: Check the current length of descriptions.

**Comment by karlcow** [comment]
@zoepage yes. And Probably #1992 is a kind of duplicate of this one. We should probably close #1992

**Comment by karlcow** [comment]
That gives up a potential of 1519 titles to fix, but 9600 would still be directly usable which is not bad. 
I want to check how many people are not using "steps by steps" because they have "description" 

* steps shorter than description:  768
* steps longer than description:  8564
* steps are empty: 1884
