### ISSUE TITLE
status not updated visually (without refresh) when... changing status

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat.com#1832]
Issue found by @karlcow here: https://github.com/webcompat/webcompat.com/pull/1831#issuecomment-333414014

**Comment by miketaylr** [comment]
Hm, either I don't understand the issue, or it doesn't reproduce for me:
![status](https://user-images.githubusercontent.com/67283/31100852-b0781c12-a790-11e7-8244-0d5775aca334.gif)



```
Changing the status to needs diagnosis

    top category of infobox is changed. OK!
    The status visual world is not updated. BUG.
    The Labels box didn't change. OK!
```

@karlcow would you mind re-testing when you get a moment? It's possible I'm not understanding the issue. Thanks.

**Comment by karlcow** [comment]
ok my bad. Just checked this morning. And I had forgotten to do the magical `grunt`. Sorry about that. It works accordingly to the… spec 👅
