### ISSUE TITLE
TypeError: milestoneColors[milestone] is undefined [Learn More]

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat.com#1833]
1. https://staging.webcompat.com/issues/1288
2. the page refuses to load
3. in the console, `TypeError: milestoneColors[milestone] is undefined [Learn More]`

**Comment by miketaylr** [comment]
in issue-milestones.jst

```html
    <span class="wc-Label wc-Label--badge js-Milestone"
          style="background-color:<%= milestoneColors[milestone].color %>">
```

in issue.js model:

```js
parse: function(response) {
    var milestoneColors = $("main").data("statuses");
    var milestone = response.milestone ? response.milestone.title : "";
    var labelList = new issues.LabelList({ labels: response.labels });
    var labels = labelList.get("labels");
    this.set({
      body: md.render(response.body),
      commentNumber: response.comments,
      createdAt: response.created_at.slice(0, 10),
      issueState: this.getState(response.state, milestone),
      labels: labels,
      milestone: milestone,
      milestoneColors: milestoneColors,
      number: response.number,
      reporter: response.user.login,
      reporterAvatar: response.user.avatar_url,
      state: response.state,
      title: response.title
    });
```

On the server, `<main data-statuses="">`, not sure why yet. 

Question: is a fallback color useful? Or when this fails, will it fail no matter what? (or in other ways)

**Comment by karlcow** [comment]
where does staging get its bug from? webcompat-test?

**Comment by miketaylr** [comment]
milestones.json is in the right place on the staging server (in $FOO/data/milestones.json)

https://gist.github.com/miketaylr/c861d7c15c276e3502a817e25a956fc7

**Comment by karlcow** [comment]
@miketaylr could you restart once. :) just an intuition

**Comment by karlcow** [comment]
Wondering… https://github.com/webcompat/webcompat.com/blob/236c970c101b2a78c20732df43d63eec2e17d343/run.py#L108
 
I'll check tomorrow morning in the train.

**Comment by miketaylr** [comment]
Cool, thanks @karlcow. I'm messing around with some logging on the server, but I suspect you could figure it out quicker than me. :)

**Comment by miketaylr** [comment]
> where does staging get its bug from? webcompat-test?

Yeah.

**Comment by miketaylr** [comment]
Interesting. I added some dumb code to log the JSON_STATUSES config object, which works locally:

views.py:

```py
@app.route('/issues/<int:number>')
@cache_policy(private=True, uri_max_age=0, must_revalidate=True)
def show_issue(number):
    """Route to display a single issue."""
    app.logger.info('json statuses:')
    app.logger.info(app.config['JSON_STATUSES'])
    if g.user:
        get_user_info()
    if session.get('show_thanks'):
        flash(number, 'thanks')
        session.pop('show_thanks')
    return render_template('issue.html', number=number)
```

(in my console with localhost running)

```
INFO in views [/Users/mitaylor/dev/webcompat.com/webcompat/views.py:230]:
json statuses:
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
INFO in views [/Users/mitaylor/dev/webcompat.com/webcompat/views.py:231]:
{"sitewait": {"color": "#006b75", "state": "open", "id": 5, "order": 5}, "worksforme": {"color": "#d4c5f9", "state": "closed", "id": 11, "order": 7}, "non-compat": {"color": "#b60205", "state": "closed", "id": 12, "order": 5}, "needsdiagnosis": {"color": "#ff8364", "state": "open", "id": 2, "order": 2}, "contactready": {"color": "#a1ebbf", "state": "open", "id": 4, "order": 4}, "wontfix": {"color": "#000000", "state": "closed", "id": 6, "order": 6}, "needscontact": {"color": "#e11d21", "state": "open", "id": 3, "order": 3}, "invalid": {"color": "#e6e6e6", "state": "closed", "id": 8, "order": 4}, "needstriage": {"color": "#ff9900", "state": "open", "id": 1, "order": 1}, "duplicate": {"color": "#cccccc", "state": "closed", "id": 10, "order": 1}, "fixed": {"color": "#009800", "state": "closed", "id": 9, "order": 2}, "incomplete": {"color": "#d93f0b", "state": "closed", "id": 7, "order": 3}}
--------------------------------------------------------------------------------
127.0.0.1 - - [03/Oct/2017 10:07:02] "GET /issues/1000 HTTP/1.1" 304 -

```

I deployed that to staging and get an nginx 500.

staging-nginx.log:

`2017/10/03 15:09:32 [error] 856#0: *380129 upstream prematurely closed connection while reading response header from upstream, client: 66.90.217.104, server: staging.webcompat.com, request: "GET /issues/1237 HTTP/1.1", upstream: "uwsgi://unix:///tmp/uwsgi-staging.sock:", host: "staging.webcompat.com"
`

Not very helpful.

In staging-uwsgi.log:

```
webcompat@webcompat:~/logs$ tail -f staging-uwsgi.log 
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "./webcompat/helpers.py", line 517, in policy
    response = make_response(view(*args, **kwargs))
  File "./webcompat/views.py", line 231, in show_issue
    app.logger.info(app.config['JSON_STATUSES'])
KeyError: 'JSON_STATUSES'
[pid: 23633|app: 0|req: 4/4] 66.90.217.104 () {46 vars in 969 bytes} [Tue Oct  3 15:09:32 2017] GET /issues/1237 => generated 0 bytes in 7 msecs (HTTP/1.1 500) 0 headers in 0 bytes (1 switches on core 0)
```

**Comment by miketaylr** [comment]
So it seems like that's failing somehow?

**Comment by miketaylr** [comment]
One thing to note, doesn't seem like the bug though:

https://github.com/webcompat/webcompat.com/blob/milestones/run.py#L160
https://github.com/webcompat/webcompat.com/blob/236c970c101b2a78c20732df43d63eec2e17d343/run.py#L108

That `statuses` argument is never used.

**Comment by miketaylr** [comment]
/me steps away to let Karl poke at it.

**Comment by karlcow** [comment]
small intuition, because of `KeyError: 'JSON_STATUSES'`
Could you put in config/environment.py as a test, `JSON_STATUSES = {}`
 

For 

> That statuses argument is never used.

that's a bug. :p

**Comment by karlcow** [comment]
I tried different failures mode on localhost, without being able to reproduce the issue. So there is something which is really tied to the fact to be on staging. Still investigating. (🚂 arriving in Tokyo soon)

**Comment by karlcow** [comment]
On creating a bug on staging
I ended up having a redirection to https://staging.webcompat.com/file with a 502 bad gateway.
Not good. :)
The bug was created. https://staging.webcompat.com/issues/1289

**Comment by karlcow** [comment]
The second. Still 502 Gateway. Redirection to https://staging.webcompat.com/issues/new
The bug was not created.

**Comment by miketaylr** [comment]
I'm not sure staging is in a good state. Let me re-deploy the milestones branch.

**Comment by miketaylr** [comment]
OK, something is up... strange. I left a comment of the stack in #1836. Will spend time investigating today.

**Comment by miketaylr** [comment]
Let's close this in favor of https://github.com/webcompat/webcompat.com/issues/1836, since that has all the good diagnosis comments.
