### ISSUE TITLE
Move all "built" scripts into a build folder

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat.com#1834]
Basically everything that's not in `js/lib` or `js/vendor` should go into a `js/build` directory, and be git ignore'd. We should never edit those files, and it would be easier to hide them from editor search results as well.

**Comment by zoepage** [comment]
This was already discussed in #1352, but I second that! Shall we do this now then (with grunt)?

**Comment by miketaylr** [comment]
Yeah, why not. If and when webpack happens, it would mean less work to modify templates, etc.

**Comment by zoepage** [comment]
@Regaddi is this something you'd be interested in? :)

**Comment by Regaddi** [comment]
`js/build` is already in use and contains `ga.js`.
How about `js/dist` so we're consistent with `css/dist`?

**Comment by miketaylr** [comment]
> Isn’t this done and can be closed? 🤔

Looks like it!
