### ISSUE TITLE
NotFound send_from_directory

### ISSUE THREAD

**Issue by karlcow** [webcompat/webcompat.com#1835]
It seems quite frequent in the logs. I don't know why, and I need to understand to be able to ignore or to fix it. 

```
2017-10-04 06:54:59,977 tracking Exception thrown:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/flask/helpers.py", line 922, in send_static_file
    cache_timeout=cache_timeout)
  File "/usr/local/lib/python2.7/dist-packages/flask/helpers.py", line 668, in send_from_directory
    raise NotFound()
NotFound: 404: Not Found
```

a couple of times every hour. On webcompat we use it only twice but in a LOCALHOST context.

```
webcompat/views.py
16:from flask import send_from_directory
294:        return send_from_directory(
301:        return send_from_directory(path, filename)
```

So it's probable that it comes from something else such as serving a static resource.

**Comment by miketaylr** [comment]
I wonder if we can monkey patch `send_from_directory` to log the filename/path when there's an error? Or something?

One theory I had was bots trying to index an issue page that has had an image deleted. But we've only "hard"-deleted 2 or 3 images to my knowledge (at the request of the reporter, or in the case of illegal content).

**Comment by miketaylr** [comment]
> On webcompat we use it only twice but in a LOCALHOST context.

Hm.

**Comment by karlcow** [comment]
🤔 indeed.

**Comment by miketaylr** [comment]
I wonder if that `send_from_directory` is indeed coming from flask lib code, and not our app.

`NotFound` error sounds like a 404: https://github.com/webcompat/webcompat.com/blob/6f47e598ed2dd39f24154d9b17d935e4a25ce0bf/webcompat/error_handlers/__init__.py#L52

It could be a missing file, or we could be `abort(404)`ing elsewhere?

https://github.com/pallets/werkzeug/blob/c53d13cd1d4a19421a2c6fb9e73a10f8ffc50b1e/werkzeug/exceptions.py#L690-L707

Using `abort` throws an Exception, and our exception handling code indeed logs that. 

https://github.com/webcompat/webcompat.com/blob/6f47e598ed2dd39f24154d9b17d935e4a25ce0bf/webcompat/error_handlers/__init__.py#L59

**Comment by miketaylr** [comment]
The places we `abort(404)`: https://github.com/webcompat/webcompat.com/search?utf8=%E2%9C%93&q=abort%28404%29&type=

**Comment by miketaylr** [comment]
Or, maybe it's literally some 404 static asset:

https://github.com/pallets/flask/blob/7e4e6eced3b0d3e48261f85e365108b82ee77610/flask/helpers.py#L948

Tricky. Looking into `HTTPException` from werkzeug, there isn't path info we can get. Just description, code and name.

**Comment by karlcow** [comment]
> I wonder if that send_from_directory is indeed coming from flask lib code, and not our app.

possible. The good news is that `send_from_directory` is only used and defined in `lib/python2.7/site-packages/flask/helpers.py` 

* `send_static_file` is using it.

```python
    def send_static_file(self, filename):
        """Function used internally to send static files from the static
        folder to the browser.

        .. versionadded:: 0.5
        """
        if not self.has_static_folder:
            raise RuntimeError('No static folder for this object')
        # Ensure get_send_file_max_age is called in all cases.
        # Here, we ensure get_send_file_max_age is called for Blueprints.
        cache_timeout = self.get_send_file_max_age(filename)
        return send_from_directory(self.static_folder, filename,
                                   cache_timeout=cache_timeout)
```

```
→ find env/lib/python2.7/site-packages -type f -name '*.py' | xargs egrep -i send_static_file
env/lib/python2.7/site-packages/flask/testsuite/blueprints.py:                rv = blueprint.send_static_file('index.html')
env/lib/python2.7/site-packages/flask/testsuite/helpers.py:            rv = app.send_static_file('index.html')
env/lib/python2.7/site-packages/flask/testsuite/helpers.py:            rv = app.send_static_file('index.html')
env/lib/python2.7/site-packages/flask/testsuite/helpers.py:            rv = app.send_static_file('index.html')
env/lib/python2.7/site-packages/flask/blueprints.py:                               view_func=self.send_static_file,
env/lib/python2.7/site-packages/flask/app.py:                              view_func=self.send_static_file)
env/lib/python2.7/site-packages/flask/helpers.py:    def send_static_file(self, filename):
env/lib/python2.7/site-packages/flask_limiter/extension.py:            or view_func == current_app.send_static_file
```

**Comment by miketaylr** [comment]
`webcompat@webcompat:~/logs$ tail -n 2000 nginx-error.log | grep "No such file"`

https://gist.github.com/miketaylr/b22c75473ca30fa006fa526945ab2747

**Comment by karlcow** [comment]
which logs did I extract this error message?
hmm uwsgi.log

grep send_from_directory uwsgi.log |wc -l
23084

grep send_from_directory staging-uwsgi.log |wc -l
3

**Comment by karlcow** [comment]
ahah we are searching at the same places. :)

**Comment by karlcow** [comment]
Ah you nailed it!
Non existent `.well-known` resources, browsers or bots.

**Comment by miketaylr** [comment]
> Non existent .well-known resources, browsers or bots.

So I guess we ignore them... Shame it creates noise in the logs to discover important issues. Such is life.

**Comment by karlcow** [comment]
iOS 9.3+ introduced it

https://developer.apple.com/library/content/documentation/UserExperience/Conceptual/Handoff/AdoptingHandoff/AdoptingHandoff.html#//apple_ref/doc/uid/TP40014338-CH2-SW10

and it seems Google-bot is trying to index it
https://stackoverflow.com/questions/34812135/requests-to-well-known-apple-app-site-association/36185061#36185061

https://developer.apple.com/library/content/documentation/General/Conceptual/AppSearch/UniversalLinks.html

>  When you support universal links, iOS users can tap a link to your website and get seamlessly redirected to your installed app without going through Safari. If your app isn’t installed, tapping a link to your website opens your website in Safari. 

The other one is `assetlinks.json`
https://developers.google.com/digital-asset-links/v1/getting-started

> The Digital Asset Links protocol and API enable an app or website to make public, verifiable statements about other apps or websites. For example, a website can declare that it is associated with a specific Android app, or it can declare that it wants to share user credentials with another website.


So let's see something

<img width="967" alt="capture d ecran 2017-11-08 a 09 50 51" src="https://user-images.githubusercontent.com/505230/32525966-59b0ec5a-c46a-11e7-9db9-d85f77ac2307.png">

And 

<img width="967" alt="capture d ecran 2017-11-08 a 09 51 42" src="https://user-images.githubusercontent.com/505230/32525990-7558b6ae-c46a-11e7-84a7-4f230688ae2d.png">

At least it's not heavy. The surprise is that it is hitting webcompat.com
We could make a light txt '404' minimal headers heavily cached 404 for this two urls. and send that instead.

**Comment by karlcow** [comment]
https://github.com/pallets/flask/blob/470112dd6e708a18eb4ec1daa10c4ea276620dbf/flask/helpers.py#L661-L678

`X-SendFile` maybe

**Comment by miketaylr** [comment]
> We could make a light txt '404' minimal headers heavily cached 404 for this two urls. and send that instead.

I like this idea.
