### ISSUE TITLE
Fix Milestones initialization for non-local servers

### ISSUE THREAD

**Issue by softvision-oana-arbuzov** [webcompat/webcompat.com#1836]
**URL:** www.staging.webcompat.com  
**Browser / Version:** Firefox Release 56.0 (Desktop), Chrome 61.0.3163.100 (Desktop), Firefox Nightly 58.0a1 (2017-10-04) (Mobile), Chrome 61.0.3163.98 (Mobile).   
**Operating System:** Windows 10 Pro, Google Pixel (Android 8.0.0) - 1080 x 1920 pixels (~441 ppi pixel density)

**Prerequisites**
1. Logged in with valid credentials.

**Steps to Reproduce:**
1. Navigate to www.staging.webcompat.com.
2. Tap “Report bug” button.
3. Type in all the required info and upload a screenshot.
4. Tap the “Report” button and observe behavior.

**Expected Behavior:**
Issue is reported, no error is displayed.

**Actual Behavior:**
“502 Bad Gateway” error is displayed, issue is not reported.

**Note**
1. Not reproducible on production (www.webcompat.com).
 
**Watchers:**
@softvision-sergiulogigan
@softvision-oana-arbuzov

sv; 

![errorbadgateway](https://user-images.githubusercontent.com/12184325/31275448-e3f8f270-aa9f-11e7-8e25-3b8535537c8f.jpg)

**Comment by softvision-oana-arbuzov** [comment]
This might be related to #1833 .

**Comment by miketaylr** [comment]
```
INFO in views [./webcompat/views.py:206]:
72.48.250.154 wwww
--------------------------------------------------------------------------------
/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/util/ssl_.py:132: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecurePlatformWarning
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1994, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "./webcompat/views.py", line 220, in create_issue
    return redirect(url_for('show_issue', number=response.get('number')))
  File "/usr/local/lib/python2.7/dist-packages/flask/helpers.py", line 333, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1805, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/helpers.py", line 323, in url_for
    force_external=external)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/routing.py", line 1620, in build
    raise BuildError(endpoint, values, method)
werkzeug.routing.BuildError: ('show_issue', {}, None)
```

**Comment by miketaylr** [comment]
Aha...

```
2017-10-10 21:19:09,685 tracking Exception thrown:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/flask/helpers.py", line 922, in send_static_file
    cache_timeout=cache_timeout)
  File "/usr/local/lib/python2.7/dist-packages/flask/helpers.py", line 668, in send_from_directory
    raise NotFound()
NotFound: 404: Not Found
2017-10-10 21:22:18,268 tracking 72.48.250.154 testing.com
2017-10-10 21:22:18,382 tracking {u'documentation_url': u'https://developer.github.com/v3/issues/#create-an-issue', u'message': u'Validation Failed', u'errors': [{u'field': u'milestone', u'code': u'invalid', u'resource': u'Issue', u'value': 0}]}
```

**Comment by miketaylr** [comment]
So GitHub is saying we failed issue creation, because we're sending an invalid milestone?

**Comment by miketaylr** [comment]
https://developer.github.com/v3/#client-errors

**Comment by miketaylr** [comment]
I suppose this is somehow consistent with my theory in #1833 that somehow something is wrong with milestones.json.

But it's on the server:

`-rw-r--r--  1 webcompat webcompat 16677 Oct 10 21:16 milestones.json`

**Comment by miketaylr** [comment]
I might experiment with https://flask-debugtoolbar.readthedocs.io/en/latest/ later on. Not sure what's up at the moment. 😖

**Comment by karlcow** [comment]
> So GitHub is saying we failed issue creation, because we're sending an invalid milestone?

If the milestones are empty in the templates… then indeed we are sending something wrong in the template, because we do not have access to milestones. 

The easiest way to check that theory would be to hardcode the file in the template. 

Now the real question is why the template doesn't receive the file. :0) to explore. We know this is working locally. And working very well. I wonder if there is a permission issue into reading the file which is on the disk OR the failure mode which is not complete in run.py.

**Comment by miketaylr** [comment]
Doing the following from the index route logs what I would expect:

```python
milestones_file = os.path.join(app.config['DATA_PATH'], 'milestones.json')
app.logger.info(milestones_file)
with open(milestones_file, 'r') as f:
    milestones_content = f.read()
    app.logger.info(milestones_content)
```
(also we're not getting `IOError` which would suggest a permission issue)

I wonder if we're getting into some kind of race condition or something when setting `JSON_STATUSES`.

**Comment by karlcow** [comment]
> I wonder if we're getting into some kind of race condition or something when setting JSON_STATUSES.

Yes my thought and I think I know where to change that and It's my mistake.

**Comment by karlcow** [comment]
This commit is not a solution to our problem but something to avoid starting with our problem.
https://github.com/karlcow/webcompat.com/commit/d93e3fb3f2a7c56566f4f9620681a02d7a7645e0

I renamed a couple of variables to make it clearer and added a condition to bail out if milestones are not properly initialized. This should at least help to not have the server starts without milestones.

**Comment by miketaylr** [comment]
https://stackoverflow.com/a/39457189 might be relevant here. But... it seems like we're trying to add `STATUSES` and `JSON_STATUSES` before starting `app.run()`. 

Maybe that's too late? I need to read some flask library code.

One idea: populate `JSON_STATUSES` / `STATUSES` from environment.py by reading a file that is assumed to be on the server. We could put that there via cron daily or so (using your existing milestone fetching code), or at some point after the app has started handling requests.... maybe that would work. Not sure.

**Comment by miketaylr** [comment]
@karlcow OK, on the theory that we're modifying `app.config` too late, I hacked this crappy diff patch together:

https://gist.github.com/miketaylr/0e2d8ad8eca3806f7c77e8799d9e1c63#file-hax-patch

<img width="1742" alt="screen shot 2017-10-11 at 10 19 24 pm" src="https://user-images.githubusercontent.com/67283/31477964-fb06c0dc-aed2-11e7-9bad-4dd578599097.png">

It's ugly, but the `JSON_STATUSES` is where it needs to be, and you can see filing a bug works and displaying it as well.

Do you want to run with that idea and send in a PR? Bed time for me. 😴 🛌

**Comment by karlcow** [comment]
>  it seems like we're trying to add STATUSES and JSON_STATUSES before starting app.run().
> Maybe that's too late? I need to read some flask library code.

Are there   things touching `app.config` before `app.run`?
Let's see.         

`config_validator()` is calling `app.config['OAUTH_TOKEN']` and it's working, but it just checks the reading and not writing.

AAAAAH no… understood. And easy to test :) doh! 
Try to write a log from `run.py`

It will not happen in production, nor staging. In fact our current run.py is not used at all except for LOCALHOST, which probably means we don't do dependency check, etc on staging and prod.

`uwsgi` starts the app from  `module = webcompat` and `callable = app`. It's why your "hax" is working :) because `__init__.py` is in `webcompat/`.

ok this becomes a lot simpler and will need a bit of re-architecture. 👍 but this is for the best. A bit of straightening the fabfile too. 

Cool.

**Comment by karlcow** [comment]
Basically we can populate the milestones from the fabfile when deploying (aka setting up the system). In the meantime I suggest a small script that is independent indeed. 

We should probably get rid of python run.py and kind of using the same strategy locally and remotely with a fabfile. So we would deploy to local, staging or prod. That would make everything much cleaner. It would clearly separate what is about running the app, and what is about configuring the app.

**Comment by karlcow** [comment]
The why it is/was confusing is that the `app.run()` is not run.py but http://flask.pocoo.org/docs/0.12/api/#flask.Flask.run

**Comment by karlcow** [comment]
Oh… and if @miketaylr you tell me "but but karl… milestones.json has been created in data/ so run.py is being read". I answer: "Nope." :) It's because you ran python run.py locally :)

````
 > history | grep run.py
 1614  python run.py 
 1654  python run.py 
 1663  python run.py u
 1664  python run.py 
 1686  python run.py 
 1727  python run.py 
 1732  python run.py 
 1934  python run.py 
 1950  python run.py 
 1975  python run.py 
 2000  history | grep run.py
```

**Comment by karlcow** [comment]
To remember
After reading this http://flask.pocoo.org/docs/0.12/cli/

This is working and illustrates our issue with milestones. :)

```
export FLASK_APP=/Users/karl/code/webcompat.com/webcompat/__init__.py
flask run
```

**Comment by karlcow** [comment]
@miketaylr I will fix the mess tomorrow (Friday) ^_^ stay tuned.

**Comment by miketaylr** [comment]
Awesome, thanks @karlcow.

**Comment by miketaylr** [comment]
Just so I understand, that part of the code wasn't running because of `if __name__ == '__main__':`, right? That block will only run when running run.py as a program from the commandline, uwsgi doesn't care about it when it runs the app.

**Comment by miketaylr** [comment]
(closing #1833 since we have better comments in here)

**Comment by karlcow** [comment]
> Just so I understand, that part of the code wasn't running because of if __name__ == '__main__':, right? That block will only run when running run.py as a program from the commandline, uwsgi doesn't care about it when it runs the app.

The full `run.py` is never used in prod/staging because we start the app with uwsgi  `service uwsgi restart` which is concerned only with what is inside `webcompat/` directory (aka the module) starting the callable `app()` inside it effectively in the `__init__.py` with `app = Flask(__name__, static_url_path='')` :)

**Comment by miketaylr** [comment]
(yeah, you said it more elegantly, but that's what I was awkwardly stating.... -- thanks!)

**Comment by karlcow** [comment]
So there's an issue in our current situation. It's cool to read an existing file for creating a config. But that's not cool to create the HTTP GET part from network. This should be in the fabfile. I will try to come up with a solution which is trying to solve our current issue but will have to be modified in Austin.

**Comment by karlcow** [comment]
Pull request done. 
https://github.com/webcompat/webcompat.com/pull/1840

**Comment by miketaylr** [comment]
This is fixed now, just tested on staging. Thanks again @karlcow.
