### ISSUE TITLE
Type of bug options are almost invisible in Firefox for Android version 57

### ISSUE THREAD

**Issue by swarnava** [webcompat/webcompat.com#1837]
![image](https://user-images.githubusercontent.com/1162991/31459482-f119cb88-aee0-11e7-9701-7807e830f01d.png)

**Comment by zoepage** [comment]
![screenshot_20171011-210013](https://user-images.githubusercontent.com/562354/31460694-85c55f82-aec7-11e7-990a-c5914628c1d1.png)
![screenshot_20171011-210008](https://user-images.githubusercontent.com/562354/31460701-88cf3cf2-aec7-11e7-85a9-8692f64f27b6.png)


Android 7.1.1.
Nightly 58
Firefox 56

Confirmed. Will investigate.

**Comment by zoepage** [comment]
![screenshot_20171011-212219](https://user-images.githubusercontent.com/562354/31461631-68cbdda4-aeca-11e7-845e-99ab02a88298.png)
![screenshot_20171011-212239](https://user-images.githubusercontent.com/562354/31461637-6b9e0ed0-aeca-11e7-8a3b-1f3155e4af13.png)

**Comment by zoepage** [comment]
This is a general issue and gladly already reported https://bugzilla.mozilla.org/show_bug.cgi?id=1406808

Thanks @swarnava :)

**Comment by karlcow** [comment]
this has been fixed.
https://bugzilla.mozilla.org/show_bug.cgi?id=1406808
