### ISSUE TITLE
Images uploaded through GitHub are being hidden?

### ISSUE THREAD

**Issue by karlcow** [webcompat/webcompat.com#1844]
1. Go to https://webcompat.com/issues/12147#issuecomment-337414177
2. Go to https://github.com/webcompat/web-bugs/issues/12147#issuecomment-337414177

Same issue we can't see the images.

![capture d ecran 2017-10-18 a 08 58 52](https://user-images.githubusercontent.com/505230/31695029-d5948888-b3e2-11e7-9d8f-bf16815c38b0.png)

on webcompat.com

```html
<img src="https://user-images.githubusercontent.com/505230/31694721-c66b6054-b3e0-11e7-8c72-880b539e01b8.png" 
   alt="capture d ecran 2017-10-18 a 08 45 49" 
   style="display: none !important;" hidden="">
```

on github.com

```html
<img src="https://user-images.githubusercontent.com/505230/31694721-c66b6054-b3e0-11e7-8c72-880b539e01b8.png" 
   alt="capture d ecran 2017-10-18 a 08 45 49" 
   style="max-width:100%;">
```

**Comment by karlcow** [comment]
@magsout do you know why?

**Comment by magsout** [comment]
@karlcow do you edited your comment ? Because all images are visible..

**Comment by karlcow** [comment]
I didn't, but it is working. So let's close! Thanks for checking @magsout
