### ISSUE TITLE
Missing automatic Priority Labeling 

### ISSUE THREAD

**Issue by softvision-oana-arbuzov** [webcompat/webcompat.com#1848]
URL: www.webcompat.com
Browser / Version: Firefox Mobile Nightly 58.0a1 (2017-10-22), Firefox Release 56.0.1
Operating System: Windows 10 Pro

**Steps to Reproduce**
1. Navigate www.webcompat.com.
2. Type in all required info and report the issue.
3. Observe added labels.

**Expected Behavior:**
Corresponding Priority label is automatically added.

**Actual Behavior:**
Priority label is not automatically added.

**Note**
1. Also reproducible on staging (www.staging.webcompat.com).
2. Workaround: Manually setting the Priority labels is performed.

**Watchers:**
@softvision-sergiulogigan
@softvision-oana-arbuzov

sv; 

![missingprioritylabels](https://user-images.githubusercontent.com/12184325/31953114-0457989c-b8eb-11e7-884f-f9a772a65153.png)

**Comment by miketaylr** [comment]
Thanks for reporting @softvision-oana-arbuzov.

Yesterday I deployed https://github.com/webcompat/webcompat.com/pull/1815. @MDTsai?

**Comment by MDTsai** [comment]
Yes, I found that and manually restore the DB. But I don't think #1815 break that, it's not running. So I guess the deploy process did something I don't know, maybe?

**Comment by MDTsai** [comment]
DB is still there after I manually restore, but the priority label is not working, check this today.

**Comment by miketaylr** [comment]
This is fixed now.

**Comment by softvision-sergiulogigan** [comment]
Happened again for https://github.com/webcompat/web-bugs/issues/13436
I did like 4-5 refresh actions and waited about a minute, but still no label were displayed.
Added the browser-firefox-mobile priority-normal labels manually.

![image](https://user-images.githubusercontent.com/16573771/32727997-5a7d44be-c887-11e7-90d7-8065b032960c.png)

**Comment by miketaylr** [comment]
cc @MDTsai 

Uh I hope I didn't break this again? In theory https://github.com/webcompat/webcompat.com/commit/c427c32064666005df6056f96442e3c71c3193a8 would have prevented that.

**Comment by MDTsai** [comment]
I don't think it's broken, the domain is not in topsites.db. Priority tag function works as far as on issue 13453.
I try to search the URL https://www.alexa.com/siteinfo/indoxxi.com, the global ranking is 10753 for me, so it's not in priority-normal (1000 to 10000).

**Comment by karlcow** [comment]
So priority was not set, but the browser was not set too.

**Comment by karlcow** [comment]
@softvision-sergiulogigan I guessed you changed the browser by hand ;)

> Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.89 Safari/537.36

so you are saying that just the priority label was not set, but as @MDTsai said, there is no priority label in this case.

**Comment by softvision-sergiulogigan** [comment]
> I guessed you changed the browser by hand ;)

yup... as usual!

**Comment by karlcow** [comment]
So we can close again :)
