### ISSUE TITLE
"layout.css.servo.enabled: true" Should probably not be in the form.

### ISSUE THREAD

**Issue by karlcow** [webcompat/webcompat.com#1850]
Currently when opening a new issue the form has 
<img width="537" alt="capture d ecran 2017-10-26 a 16 03 35" src="https://user-images.githubusercontent.com/505230/32038971-405584ee-ba67-11e7-9814-919118b4cc40.png">

"layout.css.servo.enabled: true"

This should probably not be editable by the user. Just be a label (maybe it's already is).
Or added to the report after the user puts the description and submit the issue.

**Comment by miketaylr** [comment]
This is probably not worth improving, as I have plans to remove this entirely once stylo ships in 57.

**Comment by miketaylr** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1399980

**Comment by karlcow** [comment]
understood 👍

**Comment by miketaylr** [comment]
Let me reopen this bug to remove the webcompat client bits related to this.
