### ISSUE TITLE
Filed issue details not displayed (because logged-in non-collaborator users cannot set milestones)

### ISSUE THREAD

**Issue by pavangudiwada** [webcompat/webcompat.com#1851]
Went to webcompact and reported a bug the reported page is blank. I should have found the sharing option and other details.
![screenshare](https://user-images.githubusercontent.com/25551553/32227380-41ab1b48-be71-11e7-8369-4470f3413467.png)

**Comment by miketaylr** [comment]
@pavangudiwada thanks for the report! That seems bad.

https://github.com/webcompat/web-bugs/issues/12961 is the bug you filed, but for some reason the milestone wasn't set?

**Comment by miketaylr** [comment]
But I see there are issues reported after that that succeeded:

https://webcompat.com/issues/12969, for example. I wonder why this failed. I'll try to look in logs.

**Comment by miketaylr** [comment]
https://github.com/webcompat/web-bugs/issues/12970 is another instance where milestone wasn't set.

💣

**Comment by miketaylr** [comment]
I don't see anything weird in logs.

I do see webcompat/web-bugs#12970 in `webcompat.log`:

`2017-10-31 13:51:25,709 tracking XXX.XXX.XX.XXX http://www.dragonframe.com/`

But that's just logging we got a bug report for that domain. Time to check webhooks logs.

**Comment by miketaylr** [comment]
The webhook payload for 12970 creation worked: 954426c0-be42-11e7-8d18-0954797c7279

https://github.com/webcompat/web-bugs/settings/hooks/7890332

(it also had a browser-firefox label set correctly, so that seems normal)

**Comment by miketaylr** [comment]
@karlcow any ideas? Maybe we should add some logging somewhere to see if setting the milestone ID fails during issue creation?

Or hard-code the "needstriage" ID as a fallback?

https://github.com/webcompat/webcompat.com/blob/master/webcompat/form.py#L248

**Comment by miketaylr** [comment]
That seems to be the issue here.

When it works, and we get an issue creation webhook payload, `milestones` looks like this:

```
"milestone": {
      "url": "https://api.github.com/repos/webcompat/web-bugs/milestones/2",
      "html_url": "https://github.com/webcompat/web-bugs/milestone/2",
      "labels_url": "https://api.github.com/repos/webcompat/web-bugs/milestones/2/labels",
      "id": 2845621,
      "number": 2,
      "title": "needstriage",
      "description": "Issues in needs for triage. Next step is diagnosis.",
      "creator": {
        "login": "karlcow",
        "id": 505230,
        "avatar_url": "https://avatars0.githubusercontent.com/u/505230?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/karlcow",
        "html_url": "https://github.com/karlcow",
        "followers_url": "https://api.github.com/users/karlcow/followers",
        "following_url": "https://api.github.com/users/karlcow/following{/other_user}",
        "gists_url": "https://api.github.com/users/karlcow/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/karlcow/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/karlcow/subscriptions",
        "organizations_url": "https://api.github.com/users/karlcow/orgs",
        "repos_url": "https://api.github.com/users/karlcow/repos",
        "events_url": "https://api.github.com/users/karlcow/events{/privacy}",
        "received_events_url": "https://api.github.com/users/karlcow/received_events",
        "type": "User",
        "site_admin": false
      },
      "open_issues": 26,
      "closed_issues": 1,
      "state": "open",
      "created_at": "2017-10-18T01:25:36Z",
      "updated_at": "2017-10-31T14:41:05Z",
      "due_on": null,
      "closed_at": null
    },
```

When it fails (twice we know about so far), `milestone` is `null` (see payload 550f26b0-bdeb-11e7-80d1-5bb335ce0a33 )

```
    "milestone": null,
```

**Comment by miketaylr** [comment]
https://github.com/webcompat/web-bugs/issues/12975 is another one that just failed. :(

**Comment by miketaylr** [comment]
Hm, crazy theory -- are these only failing for github authed users? A quick search of webhook payloads suggests that might be true.

**Comment by miketaylr** [comment]
> Hm, crazy theory -- are these only failing for github authed users? A quick search of webhook payloads suggests that might be true.

Oh wait. This should fail for any non-collaborator, because the milestone is being set as the logged in user. We missed this because we were testing as ourselves, and we're collaborators. 🙈 

We have to set the milestone as `webcompat-bot`, in a webhook (labeler, or create a new one) for this to work.

**Comment by karlcow** [comment]
Ah excellent find. <3

**Comment by miketaylr** [comment]
Thanks again for reporing @pavangudiwada!
