### ISSUE TITLE
Triage dashboard query information

### ISSUE THREAD

**Issue by karlcow** [webcompat/webcompat.com#1859]
Context: #1857 
Previous issue: #1858 

We need two things: 

1. Total count of needstriage issues https://github.com/webcompat/web-bugs/milestones
2. Total count of needstriage issues older than 48 hours. (`is:issue milestone:needstriage created:<2017-10-30` on `2017-11-01`) **AND** without a `status-needinfo` label.
3. The list of issues in needstriage and/or only the ones which are older than 48 hours 

* [x] Create tests for the number being queried on GitHub
* [x] Create tests for checking the list of issues being returned by GitHub as a JSON
* [x] Create test to make sure needinfo is not part of the more than 48hours issues.
* [x] Create function for querying the two numbers we need
* [x] Create function for getting the list of these older issues (Maybe it's already in the previous request.)

**Comment by karlcow** [comment]
@magsout 

Tomorrow (Thursday evening), this part will be done. After that you can have fun with design and JS improvements for filtering, reorganizing the data, making the dates human readable. The cool thing is all the data you need will already be in the page itself. So it will be about manipulating the DOM. 

People who wants to do a raw CLI request will have the data too. :)
Currently it takes only 1s and I get a  page with all the data in the HTML (aka not pulled through JS).

<img width="1184" alt="capture d ecran 2017-11-08 a 14 57 20" src="https://user-images.githubusercontent.com/505230/32533685-2a7e820a-c495-11e7-9d21-f5cd91e0d455.png">


Teasing. I need to straighten my tests and see some work hypothesis (specifically when needstriage gets a bit too big)

<img width="1208" alt="capture d ecran 2017-11-08 a 14 51 04" src="https://user-images.githubusercontent.com/505230/32533491-5f11cd7a-c494-11e7-83a6-3877f3a08723.png">

I also propose we keep the needinfo issues but we make them hidden by default through css in the page with possibility to show them ( ping @miketaylr )

**Comment by karlcow** [comment]
Here thinking if I should filter out the data 48h+ on the server side and if we should do it on the client side. Both are doable with no cost. Getting better.

<img width="1160" alt="capture d ecran 2017-11-08 a 15 30 29" src="https://user-images.githubusercontent.com/505230/32534703-0830c21c-c49a-11e7-96af-4eac588ed5d3.png">

**Comment by magsout** [comment]
@karlcow good work.

**Comment by miketaylr** [comment]
> I also propose we keep the needinfo issues but we make them hidden by default through css in the page with possibility to show them ( ping @miketaylr )

+1, good idea.

**Comment by karlcow** [comment]
Pull request #1865 for this issue against the dashboard branch. But basically this is mergeable already in master.
![capture d ecran 2017-11-09 a 15 19 44](https://user-images.githubusercontent.com/505230/32591191-7c4c4618-c561-11e7-873a-f5388b447dbf.png)

**Comment by karlcow** [comment]
The next step is in the hand of @magsout with #1861

**Comment by karlcow** [comment]
This was merged.
