### ISSUE TITLE
Family of colors by labels type

### ISSUE THREAD

**Issue by karlcow** [webcompat/webcompat.com#1871]
In [San Francisco All Hands](https://wiki.mozilla.org/Compatibility/Meetings/2017-06-28#LABELs_discussion_.28ola.29), we discussed about giving a family color for each type, and decline the colors for each of these family.

```
LABELs discussion (ola)

Karl and Ola met about labels. We discussed about the labels and their categories.

    karl: documents about the current labels. https://docs.google.com/document/d/1uCBbUx7TAZh_nIYn7U18Npceo1xQl_6j36BV-cmy1_g/edit?usp=sharing
    karl: There are currently 70 labels on https://github.com/webcompat/web-bugs/labels
    RESOLUTION: we would probably gain in simplicity by adoption a simple color BY meta keyword. So one color for all type-* one color for all browser-* etc.
    ola: we also need to clean up and add consistency for the context labels, which will be easy when they are categorized.
    karl: We still need to ask others if people would agree with this choice. 
```

**Comment by zoepage** [comment]
Following a list with labels (from july) with web safe colors.
<details> Default: #ED
Browser-android #2AB
Browser-chrome: #E65
Browser-edge: #EC8
Browser-Firefox-mobile #FC0 (Status-needs-info)
Browser-Firefox #F40
Browser-Iceweasel #05C
Browser-IE #0BE
Browser-opera #A00
Browser-safari #29F
Browser-ucweb #FCC 
Ios #0D2
Mobile #090 (same as status-fixed)
NSFW #C00
Status-contactready #BEB
Status-duplicate #333
Status-fixed #090 (same as mobile)
Status-ie-bugbar #BDD (same as Type-webvr)
Status-incomplete #D30
Status-invalid #E6
Status-needscontact #E12
Status-needsdiagnosis-important #F86 (same as Status-needsdiagnosis)
Status-needsdiagnosis #F86 (same as Status-needsdiagnosis-important)
Status-needs-info #FC0 (same as Browser-Firefox-mobile)
Status-needs-triage #F90
Status-sitewait #077
Status-wontfix #000
Status-worksforme #DCF
Type-cssrule #51E
Type-flash #B00
Type-media #FDC
Type-webp #E99
Type-webrender #33
Type-webvr #BDD (same as Status-ie-bugbar)
Browser-all
Browser-blackberry-browser
Browser-blackberry
Browser-chrome-mobile-ios
Browser-chrome-mobile
Browser-chromium
Browser-edge-mobile
Browser-fennec
Browser-firefox-aurora-mobile
Browser-firefox-esr
Browser-firefox-focus
Browser-firefox-for-android
Browser-firefox-for-ios
Browser-firefox-ios
browser-firefox-mobile-(tablet)
Browser-firefox-mobile-nightly
Browser-hsafari
Browser-ie-mobile
Browser-ie11
Browser-lynx
Browser-midori
Browser-mobile-safari
browser-myie-mobile-(tablet)
Browser-myie-mobile
Browser-myie
Browser-nightly
Browser-opera-desktop
Browser-opera-mini-v
Browser-opera-mini
Browser-puffin-browser-android
Browser-seamonkey
Browser-uc-browser
Browser-vivaldi
Browser-webkit-nightly
Browser-yandex-browser
Os-android
Windows
</details>

**Comment by karlcow** [comment]
Big categories to define colors for:

* type-
* browser-
* priority-

Special labels:

* status-needinfo
* nsfw

**Comment by zoepage** [comment]
Adding IRC discussion for context:

```
<ola>: karlcow: what about - os and we also had the difference between mobile and desktop 
09:58 
<karlcow> mobile and desktop are currently in the browser-
09:59 os we never really used it
```

The idea behind categorizing the labels was to create a way of combining them.
So, e.g. right now we have `browser-firefox` and `browser-firefox-mobile`.
This way we'd have 2 labels like e.g. `browser-firefox` and `device-mobile` (or something like that). Other upside could be to make the filtering more simple.

**Comment by karlcow** [comment]
yeah was just describing the way it currently is. :)
We could modify the bots, the labeling, etc. and PATCH all the 13000+ issues
but that's a separate work. 

We can imagine that we have a new category for device type and attribute a color :) +1 even if we don't use it right away.

**Comment by zoepage** [comment]
Cool, so as a first step we could group by color.
Second step would be the clean up of the labels itself. 

Maybe we can take a look at that this week @denschub ?

**Comment by zoepage** [comment]
Will be added in design/issues/14.
