### ISSUE TITLE
Commit package-lock.json?

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat.com#1873]
When you setup the repo, after npm build runs you get the following:

`npm notice created a lockfile as package-lock.json. You should commit this file.`

Reading up at https://docs.npmjs.com/files/package-lock.json, it seems like a good idea?

I'll defer to @zoepage though.

**Comment by miketaylr** [comment]
Then again... maybe people hate this: https://twitter.com/brianleroux/status/930516598846144512

**Comment by zoepage** [comment]
I'm also not a big fan, but it might be helpful. 

@miketaylr where do you see the advantages to have it?

**Comment by KevinTCoughlin** [comment]
https://twitter.com/d3viant0ne/status/930519213554458629

Interesting discussion. Can always .gitignore and save exact via `.npmrc` for most of the same benefit w/o the headache I believe... not an expert.

**Comment by miketaylr** [comment]
Yeah, I think what we're doing is fine (just .gitignore'ing it). Thanks all!
