### ISSUE TITLE
refactor template: footer.html

### ISSUE THREAD

**Issue by zoepage** [webcompat/webcompat.com#1883]
Refactor following:
https://github.com/webcompat/webcompat.com/blob/master/webcompat/templates/shared/footer.html

with:
https://github.com/webcompat/design/blob/master/docs/index.html#L1370
(if line changed, search for id="footer")

Please be aware to add the placeholders for links as they are in the old templates.
Please keep the GitHub and Twitter link.

**Comment by denschub** [comment]
Fixed by #1901.

**Comment by zoepage** [comment]
We are missing links in the footer...
- [ ] issues list
- [ ] new bug
- [ ] index

**Comment by zoepage** [comment]
fixed with 3544085e13c3099241ee5171690a7969794dfb07
