### ISSUE TITLE
refactor template: reported-by-user.html

### ISSUE THREAD

**Issue by zoepage** [webcompat/webcompat.com#1885]
To see this, you need to log in... https://webcompat.com/activity/<username>

Refactor following: 
https://github.com/webcompat/webcompat.com/blob/master/webcompat/templates/user-activity/reported-by-user.html

with: 

(if the line is wrong, look for id="issues-list")

Please be aware to add the placeholders for links as they are in the old templates.

**Comment by karlcow** [comment]
* Activity doesn't exist `https://webcompat.com/activity/` it's a 404 on purpose.
* The page which exists for user is `https://webcompat.com/activity/[username]`

**Comment by zoepage** [comment]
https://github.com/webcompat/webcompat.com/pull/1963

**Comment by zoepage** [comment]
https://github.com/webcompat/webcompat.com/pull/1963
