### ISSUE TITLE
refactor template: user-mentions.html

### ISSUE THREAD

**Issue by zoepage** [webcompat/webcompat.com#1887]
To see this, you need to log in... https://webcompat.com/activity/

Refactor following:
https://github.com/webcompat/webcompat.com/blob/master/webcompat/templates/user-activity/user-mentions.html

with:

(if the line is wrong, look for id="issues-list")

Please be aware to add the placeholders for links as they are in the old templates.

**Comment by karlcow** [comment]
see the answer in https://github.com/webcompat/webcompat.com/issues/1885#issuecomment-345077794

**Comment by zoepage** [comment]
https://github.com/webcompat/webcompat.com/pull/1963

**Comment by zoepage** [comment]
fixed by https://github.com/webcompat/webcompat.com/pull/1963
