### ISSUE TITLE
refactor template: layout.html

### ISSUE THREAD

**Issue by zoepage** [webcompat/webcompat.com#1894]
Refactor following:
https://github.com/webcompat/webcompat.com/blob/master/webcompat/templates/layout.html

Please be aware to add the placeholders for links as they are in the old templates. Especially for the JS.

- [x] add new css link
- [x] add google fonts
- [x] add new favicons (https://github.com/webcompat/design/issues/62)
- [x] add svg sprite to the header

**Comment by chaosmonster** [comment]
I added the the svg-icons to shared/svg-icons.html and included it in layout.html on branch issue/1892
