### ISSUE TITLE
Refactor: form related

### ISSUE THREAD

**Issue by zoepage** [webcompat/webcompat.com#1898]
This is a list of issues per unit or page.

Relates to 
- [x] #1897 - new-issue.html
- [x] #1891 - form.html

**Comment by zoepage** [comment]
Remove `js-ReportForm` class from form.

**Comment by miketaylr** [comment]
> Remove js-ReportForm class from form.

context: https://github.com/webcompat/webcompat.com/pull/1948#discussion_r154227867

**Comment by zoepage** [comment]
this was done in #1932  and merged.
