### ISSUE TITLE
refactor template: topbar.html

### ISSUE THREAD

**Issue by zoepage** [webcompat/webcompat.com#1902]
Related to https://github.com/webcompat/webcompat.com/issues/1881

Refactor following:
https://github.com/webcompat/webcompat.com/blob/master/webcompat/templates/topbar.html

with:
https://github.com/webcompat/design/blob/master/docs/index.html#L192
(if line changed, search for id="Nav")

Please be aware to add the placeholders for links as they are in the old templates.

**Comment by chaosmonster** [comment]
Waiting for @stefanjudis to finish https://github.com/webcompat/design/issues/31, bc I will reuse his approach for the search bar

**Comment by zoepage** [comment]
fixed https://github.com/webcompat/webcompat.com/pull/1918#issuecomment-347463951
