### ISSUE TITLE
refactor template: about.html

### ISSUE THREAD

**Issue by zoepage** [webcompat/webcompat.com#1906]
Refactor following:
https://github.com/webcompat/webcompat.com/blob/master/webcompat/templates/about.html

with:
.grid > .grid-row > .grid-cell.x3

Please be aware to add the placeholders for links as they are in the old templates. 
Especially for the JS.

**Comment by chaosmonster** [comment]
The current [about page](https://webcompat.com/about) has three boxes to illustrate the steps of a issues life cycle. 
We don't have anything like those boxes in the current design styleguide. 
Do you have any ideas @zoepage @kotzendekrabbe

**Comment by zoepage** [comment]
just dismiss those as we'll get the content today.

**Comment by zoepage** [comment]
done by https://github.com/webcompat/webcompat.com/commit/ceb2fbd3663c9d1931288706f1135ad3ace80b8a
