### ISSUE TITLE
make animation of bug in hero section run just once

### ISSUE THREAD

**Issue by zoepage** [webcompat/webcompat.com#1924]
Follow up for https://github.com/webcompat/design/pull/79

The animation should appear just on the very first load. We can set a status in the localStorage and make sure, if gets checked before the animation starts.

Edit:
We also need a fix for the bug falling out of the scene. Right now it falls all the way down... it should stay in the hero section box and disappear there.

**Comment by miketaylr** [comment]
> The animation should appear just on the very first load. We can set a status in the localStorage and make sure, if gets checked before the animation starts.

Having played around with this locally, I would recommend we only make it animate after some kind of interaction -- I think it's a bit too distracting, even for the first load.

**Comment by zoepage** [comment]
Was thinking about this too recently. How about a hover and just one time, so it has an easter egg feel to it?

**Comment by miketaylr** [comment]
> Was thinking about this too recently. How about a hover and just one time, so it has an easter egg feel to it?

I like this. 👍

**Comment by zoepage** [comment]
Maybe @mpaarating might be interested in working on this after #2061 ? :)

**Comment by deeptibaghel** [comment]
@miketaylr I’d like to work on this for my outreachy contribution!

**Comment by zoepage** [comment]
@deeptibaghel Feel free! Please make sure to branch from the `refactor`  branch. Let me know, if you have questions :)

**Comment by deeptibaghel** [comment]
@zoepage i tried to work branch refactor but got errors as below :
<img width="1450" alt="screen shot 2018-03-06 at 7 34 13 pm" src="https://user-images.githubusercontent.com/448609/37036379-84f8a016-2175-11e8-8369-46e2590a903b.png">

**Comment by deeptibaghel** [comment]
Also i can see the animation in https://staging.webcompat.com/ but not on https://webcompat.com.
Can i get any hint on which js files would be having the animation related code.

**Comment by deeptibaghel** [comment]
@miketaylr , sorry yeah i missed building it. Also i sensed it is coming from svg, but then "lang: js" tag in issue made me think that way.
The animation seems to be running only once to me on page load, without any interaction, so we need to change it to happen on hover ?

**Comment by zoepage** [comment]
Sorry for the confusion with the `lang: JS` tag. The initial idea was to just run it once and store the status in the local Storage. This is why we added the JS tag. It's all CSS now. :)

The animation should just run on hover of the bug. :)

**Comment by zoepage** [comment]
merged #2219
