### ISSUE TITLE
type-stylo label added, then removed

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat.com#1938]
I plan on removing the `type-stylo` label stuff this week, but I'd like to understand what's going on and fix it (because we want to be able to add labels via GET params in the future).

For example, in https://github.com/webcompat/web-bugs/issues/13877:

1. `type-stylo` label is added
2. bug is added to needstriage milestone
3. priority label and browser label are added (which removes `type-stylo`).

**Comment by miketaylr** [comment]
This blocks https://bugzilla.mozilla.org/show_bug.cgi?id=1420102.

**Comment by miketaylr** [comment]
I possibly broke this in https://github.com/webcompat/webcompat.com/commit/1429b85a32f9f117d70d17ab86c4f062c937426e.

**Comment by miketaylr** [comment]
I think the simplest solution is to see if there are existing labels, rather than create a new empty list each time:

https://github.com/webcompat/webcompat.com/blob/54e0d5d5a9f2bcfe143fa652894b4703591678c1/webcompat/webhooks/helpers.py#L139

**Comment by karlcow** [comment]
if I remember what  @makotokato told me. Stylo is not deployed in Android yet.

**Comment by karlcow** [comment]
```python
if not labels:
    labels = []

**Comment by karlcow** [comment]
hmm no…  that would break. 

https://github.com/webcompat/webcompat.com/blob/54e0d5d5a9f2bcfe143fa652894b4703591678c1/webcompat/webhooks/helpers.py#L139-L147

```
browser_label = extract_browser_label(issue_body)
priority_label = extract_priority_label(issue_body)
```

return None when empty.
it's always a unique string which is returned for both functions.

**Comment by karlcow** [comment]
If I understood what you want.

```python
def new_opened_issue(payload):
    '''When a new issue is opened, we set a couple of things.
    - Browser label
    - Priority label
    - Issue milestone
    '''
    issue_body = payload.get('issue')['body']
    issue_number = payload.get('issue')['number']
    browser_label = extract_browser_label(issue_body)
    priority_label = extract_priority_label(issue_body)
    labels = [label for label in (browser_label, priority_label)
              if label is not None]
    milestone = app.config['STATUSES']['needstriage']['id']
    if labels:
        meta = {'labels': labels, 'milestone': milestone}
    else:
        meta = {'milestone': milestone}
    return update_issue(meta, issue_number)
```

**Comment by miketaylr** [comment]
> if I remember what @makotokato told me. Stylo is not deployed in Android yet.

It looks like 59 cycle it will ship (which is current nightly cycle):

https://groups.google.com/forum/#!topic/mozilla.dev.platform/SUfu_2hPH8o

**Comment by miketaylr** [comment]
```
labels = [label for label in (browser_label, priority_label)
              if label is not None]
```

This will have the same problem -- if the `payload` has a non-empty list for `issue.labels`, we're still replacing it. I tried yesterday to do something like:

```
labels = payload.get('issue')['labels']
if labels:
        labels = [l.get('name', '') for l in labels]
```

But it failed... it seems like the payload doesn't have the `type-stylo` label on issue creation at the webhook level, but sends a `labeled` webhook immediately after a `new issue` webhook. So I might need to re-think this.

**Comment by miketaylr** [comment]
One option would be to re-use our `<!-- @browser: foo -->` hack, and set the EXTRA_LABEL at the same time as miletone and browser label...

**Comment by miketaylr** [comment]
Testing here, with that code deployed:

1. filed https://github.com/webcompat/webcompat-tests/issues/1305
2. get webhook  `action:opened`, with empty labels:
```
"labels": [

    ],
```
3. get webhook d67c52e0-d47a-11e7-8530-9184f88e7c88 , `action:milestoned`, labels has type-stylo:

```
"labels": [
      {
        "id": 650809601,
        "url": "https://api.github.com/repos/webcompat/webcompat-tests/labels/type-stylo",
        "name": "type-stylo",
        "color": "ededed",
        "default": false
      }
    ],
```
4. get webhook  d6802370-d47a-11e7-89db-1f25dda4a176 , `action:unlabeled`, with new browser and priority labels:

```
"labels": [
      {
        "id": 182807004,
        "url": "https://api.github.com/repos/webcompat/webcompat-tests/labels/browser-firefox",
        "name": "browser-firefox",
        "color": "d4c5f9",
        "default": false
      },
      {
        "id": 762722919,
        "url": "https://api.github.com/repos/webcompat/webcompat-tests/labels/priority-critical",
        "name": "priority-critical",
        "color": "ededed",
        "default": false
      }
    ],
```

5. get webhook `action:labeled`, still with browser and priority labels:

```
"labels": [
      {
        "id": 182807004,
        "url": "https://api.github.com/repos/webcompat/webcompat-tests/labels/browser-firefox",
        "name": "browser-firefox",
        "color": "d4c5f9",
        "default": false
      },
      {
        "id": 762722919,
        "url": "https://api.github.com/repos/webcompat/webcompat-tests/labels/priority-critical",
        "name": "priority-critical",
        "color": "ededed",
        "default": false
      }
    ],
```

**Comment by miketaylr** [comment]
Step 2 is suprising to me. I would expect the label to exist when the issue is open, since we're sending it to the new issue endpoint.... but if we're just reacting to the new open issue webhook, this approach won't work. So I think I'm gonna do the comment hack to be simpler and not have to deal with timing of webhooks and github events.

**Comment by karlcow** [comment]
My hunch for the step 2 issue which should contain

```
"labels": ["type-stylo"],
```

Github server strategy of handling the server load. Probably when the HTTP POST for the webhook is sent the labels have not been written in the labels tables of their DB. That would be a good question for them. I even wonder if they even a similar internal notifications systems for queuing actions that they partially expose for webhooks.

**Comment by karlcow** [comment]
hmm though…
https://developer.github.com/v3/activity/events/types/#webhook-payload-example-10
They give an example with labels.

**Comment by karlcow** [comment]
it we could to craft a manual request to webcompat-test and check if the label is being set in opened. Maybe they have a bug. If it happens when done manually, then we might have a bug.
