### ISSUE TITLE
Error opening file for reading: Permission denied (milestones?)

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat.com#1943]
Just noticed this in the staging uwsgi logs:

```
Statuses Initialization…
Fetching milestones from Github…
[snip]
Milestones saved in data/
Milestones in memory
Error opening file for reading: Permission denied
```

Might be related to not running as root. Something to investigate.

**Comment by karlcow** [comment]
Maybe it doesn't exist anymore! :) Let's close it. If it resurfaces, we will something about it. It seems to be devops stuff.
