### ISSUE TITLE
Triage Dashboard - if untriaged issues > 50, mark the number as red for alert

### ISSUE THREAD

**Issue by MDTsai** [webcompat/webcompat.com#1950]
Easily to know if there is issue flood from sprint?

**Comment by karlcow** [comment]
@magsout What do you think? Should we send something from the server side, `alert: True` if it's becoming more than 50. Or should we just handled the color on the server through JS. aka if the number is 50, `background-color: red`

**Comment by magsout** [comment]
@karlcow I think that solution number 2 is good
