### ISSUE TITLE
[triage dashboard] After filtering, there are some missing issues.

### ISSUE THREAD

**Issue by karlcow** [webcompat/webcompat.com#1951]
<img width="993" alt="capture d ecran 2017-12-04 a 10 29 13" src="https://user-images.githubusercontent.com/505230/33532578-21efd9ce-d8de-11e7-8bf2-bd4034fa5256.png">
Obviously this is not working as it should.

**Comment by karlcow** [comment]
In this case the list has been filtered on Firefox.

**Comment by karlcow** [comment]
I guess in the list we are missing all the mobile stuff, etc. I need to normalize the list I send for the `browser-*` It was part of our discussions with @magsout 

* browser-firefox
* browser-chrome
* browser-edge
* browser-safari
* browser-others

**Comment by magsout** [comment]
@karlcow or maybe I can add a regexp in my search ?

**Comment by karlcow** [comment]
@magsout Indeed. It is probably a better idea. This way we do not loose information, if we want to rearrange another way.

Let's do that. Changing the flag from Python to JavaScript.
