### ISSUE TITLE
Add webrender labels to EXTRA_LABELS whitelist

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat.com#1960]
We'd like to track if people have webrender prefs enabled.

See https://bugzilla.mozilla.org/show_bug.cgi?id=1422985

**Comment by miketaylr** [comment]
Per https://bugzilla.mozilla.org/show_bug.cgi?id=1422985#c3, I think I'd like to create a `type-webrender-enabled` label instead of `type-webrender`. Just because webrender prefs are enabled, that doesn't mean it's the root cause of the reported issue.

**Comment by karlcow** [comment]
@miketaylr What do we do with the 6 current issues in type-webrender? Do we transfer them or leave them as-is?

**Comment by miketaylr** [comment]
> @miketaylr What do we do with the 6 current issues in type-webrender? Do we transfer them or leave them as-is?

I'll take a look, possibly transfer them.

**Comment by miketaylr** [comment]
> I'll take a look, possibly transfer them.

Moved some of them, removed it from some other ones that had the label incorrectly.
