### ISSUE TITLE
Add optional "browsers" argument for functional tests

### ISSUE THREAD

**Issue by brizental** [webcompat/webcompat.com#1977]
I had already done that while trying to get tests to run in Safari, but didn't merge it in since those tests failed. I think this is helpful, specially when working with the tests, troubleshooting, etc.

My idea is to add the `browsers` argument and if the user doesn't specify anything, just run all the available ones.

It would look like this: `npm run test:js browsers=safari,chrome,firefox`

**Comment by miketaylr** [comment]
> It would look like this: npm run test:js browsers=safari,chrome,firefox

SGTM.
