### ISSUE TITLE
Functional tests failing in Chrome

### ISSUE THREAD

**Issue by brizental** [webcompat/webcompat.com#1981]
Still need to do some investigating, but this is the situation right now:

> Chr 63 MAC: [✓✓✓✓✓✓✓✓×××✓✓✓✓✓✓✓✓××××××××××××××××××      ] 74/81, 38 fail

The `comments-auth.js` tests all fail and after the first `Pressing g goes to github issues` test all the others fail and the suite isn't event able to finish. 

The comments fails don't seem to be linked to the second one.

Is this only happening for me?

**Comment by miketaylr** [comment]
@brizental master is green (so at least travis can get them to pass), i wonder if it's conf wifi network related?

<img width="894" alt="screen shot 2017-12-13 at 4 32 25 pm" src="https://user-images.githubusercontent.com/67283/33966049-be680b86-e023-11e7-93a9-f6c8ae394c16.png">

**Comment by brizental** [comment]
@miketaylr maybe, but then ola's tests should have passed

**Comment by miketaylr** [comment]
> @miketaylr maybe, but then ola's tests should have passed

(i think you figured this out already, but her merge is broken because that branch broke uglify stuff (probably due to es6 template strings)

**Comment by zoepage** [comment]
> her merge is broken because that branch broke uglify stuff

I checked the tests on master, so this shouldn't have anything to do with the ES6 stuff.

**Comment by brizental** [comment]
Closed by 30cd7fb
