### ISSUE TITLE
Report anonymous email addresses to private repo

### ISSUE THREAD

**Issue by adamopenweb** [webcompat/webcompat.com#1984]
Related to #1015 and #1822. 
Want to discuss this topic without sidetracking other bugs, if this is not found to be valuable, we can close this report.

When a user reports a bug anonymously, we could provide an option to record their email address for follow up. 

The email address would be logged in a private repo issue and create a link to it in the main web-bugs report. The issue numbers won't match, but it shouldn't matter.

I'm curious if this can help with our security concerns regarding keeping email addresses.

Thoughts?

**Comment by miketaylr** [comment]
> The issue numbers won't match, but it shouldn't matter.

Yeah, and the simplest db table can match issue -> privateIssue.

> I'm curious if this can help with our security concerns regarding keeping email addresses.

I like it. We would need to define a strict policy of who gets added to the "private emails" team, with access to the repo as well. Some criteria: 2FA enabled, privileged triager (not just any volunteer triager), level 4 wizard (at minimum).

**Comment by adamopenweb** [comment]
I don't know that we need to leave this open. Just one possible solution to the anonymous report problem. Closing for now.
