### ISSUE TITLE
Make local build doc more obvious from README.md

### ISSUE THREAD

**Issue by Obtin** [webcompat/webcompat.com#1991]
For new contributors there are no instructions or additional link present , neither on github page nor on the web page that may direct him/her and help in setting up environment on local machine.
Even the Wiki of this project does provide any information regarding this.

**Comment by Obtin** [comment]
Thank you very much.I was unable to find it. :-)

**Comment by zoepage** [comment]
@Obtin that is a good hint. Thanks! :)

**Comment by miketaylr** [comment]
> Thank you very much.I was unable to find it. :-)

Maybe it would be good to update our README which currently reads:

> Please check out CONTRIBUTING.md for more instructions.

To something like:

> Please check out CONTRIBUTING.md for more instructions, including how to set up a local build environment. 

(and have local build environment be a link to the `dev-env-setup.md` file).

**Comment by Obtin** [comment]
I would like to work on this r ? @zoepage @miketaylr

**Comment by miketaylr** [comment]
> r ? @zoepage @miketaylr

(no need to request review from an issue comment -- in the PR is fine, thanks!)
