### ISSUE TITLE
Site URL does not check for appropriate URL

### ISSUE THREAD

**Issue by Obtin** [webcompat/webcompat.com#1993]
Observed : 
- When I entered a random URL, no warning was given and it accepted the wrong URL.
![webcompatissue](https://user-images.githubusercontent.com/25207205/34463086-f5bff500-ee77-11e7-8d1f-e544cacd62c2.png)
 Expected : 
- A check for URL that does not allow to submit an issue with an inappropriate URL.

**Comment by karlcow** [comment]
@Obtin when testing these types of issues, it's better to do it on https://staging.webcompat.com/ 
Thanks.

This is a duplicate of #1742
We have been relaxed about URL validation because there are cases where things which don't seem valid are still useful things.
