### ISSUE TITLE
Update Contributing.md 

### ISSUE THREAD

**Issue by zoepage** [webcompat/webcompat.com#1996]
This is about updating the Contributing.md with the suggested new process for labels and feature requests.

**Comment by karlcow** [comment]
@zoepage Could you give more details? or links to the discussions/proposals? Thanks. (for the paper trail 😉 )

**Comment by zoepage** [comment]
https://groups.google.com/forum/#!topic/mozilla.compatibility/Y9fceIecTME
https://groups.google.com/forum/#!topic/mozilla.compatibility/_kCr_EUZDoA
