### ISSUE TITLE
Get functional tests running in Safari

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat.com#2023]
https://github.com/webcompat/webcompat.com/pull/1987#issuecomment-357441787

> ...I will look at Safari issues after this is done. Even though we have much less errors, we are still getting a bunch of intermittents.

**Comment by brizental** [comment]
Hm, we have an issue for that already, hahaha, #1704 !

**Comment by miketaylr** [comment]
Oops. OK, let's close this one. :)
