### ISSUE TITLE
Use HTTP POST instead of URL parameters for populating the new issue form from site report button

### ISSUE THREAD

**Issue by karlcow** [webcompat/webcompat.com#2024]
I was looking at https://reviewboard.mozilla.org/r/212166/diff/2#index_header
for https://bugzilla.mozilla.org/show_bug.cgi?id=1422985

And I was wondering if there could be a better way of sending the browser data to the form
https://webcompat.com/issues/new

And I thought about [HTTP PATCH](https://tools.ietf.org/html/rfc5789)
PUT overwrite a resource, but in this case we just want to add data to the `/issues/new` resource.

```
   The PATCH method requests that a set of changes described in the
   request entity be applied to the resource identified by the Request-
   URI.  The set of changes is represented in a format called a "patch
   document" identified by a media type.  If the Request-URI does not
   point to an existing resource, the server MAY create a new resource,
   depending on the patch document type (whether it can logically modify
   a null resource) and permissions, etc.

[…]

  With PATCH, however, the enclosed entity contains a set
   of instructions describing how a resource currently residing on the
   origin server should be modified to produce a new version.
```
https://tools.ietf.org/html/rfc5789#section-2

So we could do something like this 

```http
   PATCH /issues/new HTTP/1.1
   Host: webcompat.com
   Content-Type: application/json
   If-Match: "blah"
   Content-Length: 109

{
  "details": [
    "something"
  ],
  "user-agent": "blahblah",
  "prefs": [
    "webrender", "stylo"
  ]
}
```

and so on the receiving hand in webcompat/Flask we read the body and adjust the form with prefiled data. That would avoid a lot of parsing-URL foo and probably a more reliable validation.

* [ ] Modifying the browser "Report Site Issue to send a PATCH with a JSON"
* [ ] Modify the backend to monitor PATCH on /issues/new
* [ ] Modify the unittest tests for URLs
* [ ] Modify the unittest tests for data validation
* [ ] (Option) Modify the add-ons to use the same mechanism if possible.

Possible review for this idea: @miketaylr 
Possible Resources for development: @miketaylr @karlcow @MDTsai

**Comment by miketaylr** [comment]
+1, I like this idea a lot @karlcow. 

For https://reviewboard.mozilla.org/r/212166/diff/2#index_header, I think my approach will change a bit (which might require some simples changes to our current backend parsing). But I think medium-term this is a nicer architectural change.

I'd recommend we try to land the `type-webrender-enabled` stuff before we block on this approach, even if it means re-doing work.

**Comment by karlcow** [comment]
* +1 on not blocking the current effort. (I think we have a couple of other things on our plate right now.)
* We can take a bit of time later for this.

**Comment by karlcow** [comment]
Let me rewind a bit. After diving a bit more in the specs, it was probably a good bad idea.

1. The PATCH is here to modify a resource with a specific media type. The PATCH for `application/json` has not been defined which suggested [this errata](https://www.rfc-editor.org/errata/eid3169)
2. In my proposal we are not modifying parts of a resource like GitHub does with its PATCH semantics.  So that would subvert PATCH.
3. There is still something we can do probably by using HTTP POST
I need to create a test for this and see if it would be working.

```
POST /issues/preform HTTP/1.1
Content-Type: application/json
Authorization: some_key

{ "foo" : "bar", "name" : "John" }
```

and sending a redirect to the right form `/issues/new`.

**Comment by miketaylr** [comment]
This blocks https://bugzilla.mozilla.org/show_bug.cgi?id=1453493.

**Comment by miketaylr** [comment]
@karlcow @wisniewskit wants to work on this (because it blocks the console error stuff), but we're going to hold off until https://github.com/webcompat/webcompat.com/pull/2528 is merged.

**Comment by miketaylr** [comment]
A few things to note: 

In [`BugForm.checkParams`](https://github.com/webcompat/webcompat.com/blob/master/webcompat/static/js/lib/bugform.js#L208), we rely on 2 GET params for the UI:

`url`: autofills the URL input
`problem_type`: will select the option, if present

We also populate a hidden input with `details`, but this could be sent as POST data.

There's some other GET params that could be sent as POST data, since they're consumed by the backend:

`src`: https://dxr.mozilla.org/mozilla-central/source/browser/extensions/webcompat-reporter/content/WebCompatReporter.jsm#115
`label`:  https://dxr.mozilla.org/mozilla-central/source/browser/extensions/webcompat-reporter/content/WebCompatReporter.jsm#119

**Comment by karlcow** [comment]
@miketaylr could you show me an example of console.log data as sent by the browser. Or should I assume that this is just a UTF-8 stream of data.

**Comment by karlcow** [comment]
This seems to be manageable on the server side instead of the client side. 
https://github.com/webcompat/webcompat.com/blob/master/webcompat/static/js/lib/bugform.js#L207-L244

**Comment by karlcow** [comment]
So there will be  I guess a compat story to handle here. 

When switching to HTTP POST with data  instead of parameters, we still need to maintain the url one because some of the things will be using this. Or we mint a new URI for the new form style.

**Comment by karlcow** [comment]
Trying to model things a bit more. 
https://webcompat-meet.herokuapp.com/oWU0yjHPT9mYl_sM7iZ0XQ#

<img width="771" alt="capture d ecran 2018-08-14 a 15 43 33" src="https://user-images.githubusercontent.com/505230/44075750-dcb91772-9fd8-11e8-97c0-478de9627b64.png">

**Comment by miketaylr** [comment]
> Or should I assume that this is just a UTF-8 stream of data.

I believe it will just be included as part of the `details` POST data. So, nothing different than we currently accept to get pref values, just over POST. Probably coming in as JSON (as current `details` data does).

> When switching to HTTP POST with data instead of parameters, we still need to maintain the url one because some of the things will be using this. Or we mint a new URI for the new form style.

Current compat requirements:

* Firefox for Android: https://dxr.mozilla.org/mozilla-central/source/mobile/android/chrome/content/WebcompatReporter.js#122: `src` and `url` params.
* Firefox Desktop reporter: https://dxr.mozilla.org/mozilla-central/source/browser/extensions/webcompat-reporter/content/WebCompatReporter.jsm#114: `src`, `url`, `details` params.
* Decoder Doctor: https://searchfox.org/mozilla-central/source/browser/base/content/browser-media.js#344: `label`, `problem_type`, `url`, `src` params
* Focus/Klar: https://github.com/mozilla-mobile/focus-android/blob/5b5c3869080c64c5354bf21ec2c88cf1a9f61a5a/app/src/main/java/org/mozilla/focus/utils/SupportUtils.java#L31 `url` and `label` params
* Browser addons: https://github.com/webcompat/webcompat-reporter-extensions/blob/master/shared/base.js#L7 & https://github.com/webcompat/webcompat-reporter-extensions/blob/master/shared/base.js#L31 `url` and `src` params

**Comment by karlcow** [comment]
@miketaylr 
> included as part of the details POST data

It is currently sent as parameters, not multipart data. :)
https://dxr.mozilla.org/mozilla-central/source/browser/extensions/webcompat-reporter/content/WebCompatReporter.jsm#113-116

* Should we modify all of these to be sent as multipart data?
* Supporting the two methods for a little while, and deprecating one for the other after a while?

**Comment by karlcow** [comment]
Taking @miketaylr list and annotating (second level of bullet points) also putting permalink into the fray.

* Firefox for Android: https://dxr.mozilla.org/mozilla-central/rev/4e56a2f51ad739ca52046723448f3129a58f1666/mobile/android/chrome/content/WebcompatReporter.js#122 : `src` and `url` params.
  * This opens a new tab at the URL and does a `HTTP GET` and not `HTTP POST`
* Firefox Desktop reporter: https://dxr.mozilla.org/mozilla-central/rev/4e56a2f51ad739ca52046723448f3129a58f1666/browser/extensions/webcompat-reporter/content/WebCompatReporter.jsm#105-125 : `src`, `url`, `details` params.
  * This opens a new tab at the URL and does a `HTTP GET` and not `HTTP POST`
* Decoder Doctor: https://dxr.mozilla.org/mozilla-central/rev/4e56a2f51ad739ca52046723448f3129a58f1666/browser/base/content/browser-media.js#341-350 : `label`, `problem_type`, `url`, `src` params
  * This opens a new tab at the URL and does a `HTTP GET` and not `HTTP POST`
* Focus/Klar: https://github.com/mozilla-mobile/focus-android/blob/5b5c3869080c64c5354bf21ec2c88cf1a9f61a5a/app/src/main/java/org/mozilla/focus/utils/SupportUtils.java#L31 `url` and `label` params
  * This creates a [GET](https://github.com/mozilla-mobile/focus-android/blob/2f7a7a5e8af0f81ed1e644f12284e2c12532e906/app/src/main/java/org/mozilla/focus/fragment/BrowserFragment.java#L1243-L1248)
* Firefox Reality: https://github.com/MozillaReality/FirefoxReality/commit/284bf800372704c8576563f0738a660c0890336d `src`, `label`, `url`
  * This creates a [GET](https://github.com/MozillaReality/FirefoxReality/blob/c814e4beef33e45a2b4dabf1383af15d5b3e7b92/app/src/common/shared/org/mozilla/vrbrowser/ui/SettingsWidget.java#L235-L255) but on `https://mixedreality.mozilla.org/fxr/report?src=browser-fxr&amp;label=browser-firefox-reality&amp;url=%1$s` which itself creates a GET with the same parameters to `https://webcompat.com/issues/new` I'm not sure why they decided to do this indirection. The page is literally a script doing a redirection. Maybe @cvan knows why
* Browser addons: https://github.com/webcompat/webcompat-reporter-extensions/blob/d9d5c04808a3a375ab41a86e15cabad3c4287abf/shared/base.js#L25-L39 & https://github.com/webcompat/webcompat-reporter-extensions/blob/d9d5c04808a3a375ab41a86e15cabad3c4287abf/shared/base.js#L7 `url` and `src` params

So all the clients so far are creating a GET on the backend to `issues/new`, which are partly grabbed by the backend and partly grabbed by the `bugform.js` to generate a prepopulated Form, which will be then sent by user as a POST on the backend.

The GET story doesn't work when we want to send more information. So we need to listen to POST to prepopulate the form and probably needs to rewrite all these clients (PATCHES welcome).

## IMPORTANT

* **Note 1**: The backend needs to preserve the GET way of doing things for backward compatibility with pre-existing client. We could probably monitor the new clients and when we have 100% usage for the new clients we can safely obsolete the GET way.
* **Note 2**: All these clients could directly do a POST with JSON in the body. There's nothing in the HTTP spec which says that a POST has to be url-encoded or multipart data. We can have an endpoint for clients `/api/issues/new` accepting POST with a JSON payload, processing  the JSON payload and redirecting the client to a prepopulated /issues/new with the right parameters.

**Comment by karlcow** [comment]
Testing (evil?) things…

```python
@app.route('/foo', methods=['GET'])
def testing_form():
    """TODO REMOVE THIS"""
    return (request.data, 200, {'content-type': 'text/plain; charset=utf-8'})
```

Then sending the HTTP Request

```http
GET /foo HTTP/1.1
Accept: application/json, */*
Accept-Encoding: gzip, deflate
Connection: keep-alive
Content-Length: 12
Content-Type: application/json
Host: localhost:5000
User-Agent: HTTPie/0.9.9

LOOK A BODY
```

And then looking at the response…

ahah!

```http
HTTP/1.0 200 OK
Content-Length: 12
Content-Security-Policy: default-src 'self'; object-src 'none'; connect-src 'self' https://api.github.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' https://webcompat.com https://www.google-analytics.com https://*.githubusercontent.com data:; manifest-src 'self'; script-src 'self' https://www.google-analytics.com https://api.github.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; base-uri 'self'; frame-ancestors 'self'; report-uri /csp-report
Date: Thu, 16 Aug 2018 05:04:19 GMT
Server: Werkzeug/0.14.1 Python/2.7.10
X-Content-Type-Options: nosniff
X-Frame-Options: DENY
X-XSS-Protection: 1; mode=block
content-type: text/plain; charset=utf-8

LOOK A BODY
```

This is working. To note that [RFC 7231](https://tools.ietf.org/html/rfc7231#section-4.3.1
) says about GET:

```
  A payload within a GET request message has no defined semantics;
  sending a payload body on a GET request might cause some existing
  implementations to reject the request.
```

not forbidden… just… undefined. Tempting.

**Comment by karlcow** [comment]
But GET body not usable in the browser context. :)

```js
const url2 = 'http://localhost:5000/foo';
fetch(url2, {method: "GET", body: "this is a body"}).then(response => response.text()).then(html => console.log(html))
```

```
Promise { <state>: "pending" }
TypeError: HEAD or GET Request cannot have a body.
```

**Comment by karlcow** [comment]
@miketaylr Question of priorities.

Let's imagine the following scenario with contradictory data for creating the form.

```http
POST /new/issues?url=http://example.com/
Content-Type: application/json

{"url": "http://foobar.example.org/"}
```

Currently, I'm leaning to make the JSON data overwriting the URL arguments into the form, if not empty. So in this example above the prefilled form will have the value `http://foobar.example.org/`

**Comment by karlcow** [comment]
@miketaylr Another question :)

I have a hunch that this is useless

**Comment by miketaylr** [comment]
> Currently, I'm leaning to make the JSON data overwriting the URL arguments into the form, if not empty. So in this example above the prefilled form will have the value http://foobar.example.org/

+1 to this recommendation. Let's trust POST data over anything else.

**Comment by miketaylr** [comment]
> Just tested. This was dead code. :)

nice. :)

**Comment by karlcow** [comment]
this is what a pull request would look like.
https://github.com/webcompat/webcompat.com/compare/master...karlcow:2024/1

I want to double check something today.

Then the next step would be to deploy on staging and wild test it. Specifically for things which are supposed to keep working as-is
