### ISSUE TITLE
Normalization of naming in app.config['CATEGORIES']

### ISSUE THREAD

**Issue by zoepage** [webcompat/webcompat.com#2025]
https://github.com/webcompat/webcompat.com/blob/master/config/__init__.py#L125-L130

The `cat_labels` have a different naming convention here for the names, which we use as class identifiers. That is causing issues with the CSS. 

Are there any other dependencies that speak against changing e.g. `needsDiagnosis` to `needsdiagnosis` e.g. or `needstriage` to `needsTriage`?

@miketaylr @karlcow

**Comment by miketaylr** [comment]
> That is causing issues with the CSS.

@zoepage can you explain a little more? What kind of issues?

> Are there any other dependencies that speak against changing e.g. needsDiagnosis to needsdiagnosis e.g. or needstriage to needsTriage?

In theory we have a test suite which would help to answer this question, if you're asking about something beyond grepping the codebase.)

(re: the label, is this really a bug? -- i think i don't understand the issue)

**Comment by miketaylr** [comment]
ah. OK, so if you change that everywhere (CSS, Python, JS), there shouldn't be any issues.

**Comment by zoepage** [comment]
Should have mentioned, its relevant for the refactor. Changed in py + js. CSS can be dismissed here. 
(PR is going against refactor branch)

**Comment by karlcow** [comment]
@zoepage I always check the blame to be sure about my memory. I have the feeling it was introduced to have an object like structure so @magsout could easily use that in templates and I proposed it, but let's double check with the blame. 

* Heading to https://github.com/webcompat/webcompat.com/blob/master/config/__init__.py
* Clicking on blame.
* So it appears in #786, but it seems to predate this when we had the config.py

Funny: by @miketaylr 
> In the future we can add labels.py and whatever else we want in the config/ folder, and import them from __init__.py

* So it was done in #749 and it probably started with this comment.
https://github.com/webcompat/webcompat.com/commit/7e0305e93c4dc3710b356f70f8f554fbf390c5d3#r13708121 and the discussion here about namedtuples in Python. https://github.com/webcompat/webcompat.com/commit/7e0305e93c4dc3710b356f70f8f554fbf390c5d3#commitcomment-13709820

It was made to create indeed an easy structure to call in the templates.

So yes it was made for the templates and it can be renamed, extended, scrapped, depending on how people use them or need them. The important is that we keep the tests consistent.

**Comment by karlcow** [comment]
@zoepage ah! but the naming mixed up happened here.
https://github.com/webcompat/webcompat.com/pull/1114/files
When solving #975 where we replace the `new` keyword by `needstriage`.

**Comment by karlcow** [comment]
Just seen https://github.com/webcompat/webcompat.com/pull/2026/commits/895bc60458bc34f7997d807c91729c3feae0a6b7

Thanks @zoepage for normalizing.
