### ISSUE TITLE
Update stylelint to v8

### ISSUE THREAD

**Issue by zoepage** [webcompat/webcompat.com#2031]
The --fix option for the CSS linter is broken in v7, so we'd like to update to v8.
http://npmjs.com/stylelint

Please note, there were changes to the config https://github.com/stylelint/stylelint/releases/tag/8.0.0 we need to take care of too.

Updating stylelint-config-standard from v16 to v18 probably wouldn't also hurt.

**Comment by zoepage** [comment]
@magsout would this be something you'd like to work on?

**Comment by magsout** [comment]
@zoepage sure ;)

**Comment by zoepage** [comment]
Please remember to create a branch from `refactor`. :)
