### ISSUE TITLE
[triage dashboard][feedback] Cards vs lists

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat.com#2033]
Not a bug, just a personal perference.

Right now the design is using cards that require quite a bit of scrolling to interact with. I would prefer a flat list. The most important info to me is:

`Bug Number | <a href='link to bug'>Bug title`

Dunno if it's worth adding view options, or we should move to a simpler design?

Thoughts @karlcow @magsout?

**Comment by karlcow** [comment]
Thanks a lot @miketaylr

**Comment by magsout** [comment]
@miketaylr like a simple Table View ?

**Comment by karlcow** [comment]
So we currently return for needstriage.

* total nb of issues
* nb of issues > 48h
* issues list
  * issue['number'],
  * issue['title'],
  * issue['created_at'],
  * issue['updated_at'],
  * browsers (labels)
  * has_needinfo (label)
  * priority (label)

**Comment by karlcow** [comment]
@miketaylr Something along this idea or even more compact?

![capture d ecran 2018-01-25 a 14 47 41](https://user-images.githubusercontent.com/505230/35372724-c793e234-01de-11e8-923d-30e988787902.png)

**Comment by miketaylr** [comment]
@karlcow that looks perfect.

**Comment by karlcow** [comment]
@magsout here a wireframe proposal to work with. (not a real design).
![capture d ecran 2018-02-01 a 12 49 27](https://user-images.githubusercontent.com/505230/35660269-6d511ac4-074e-11e8-8d45-3f396bb52dd2.png)

**Comment by karlcow** [comment]
![capture d ecran 2018-02-01 a 13 11 15](https://user-images.githubusercontent.com/505230/35660781-7c869af2-0751-11e8-88eb-bd76ea6d22c8.png)

**Comment by magsout** [comment]
@karlcow oups did't see your message.
So You added an Header and two new icons ?
One for priority and another for need information ?
