### ISSUE TITLE
Handle details as JSON

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat.com#2040]
Needed for changes related to https://bugzilla.mozilla.org/show_bug.cgi?id=1422985. We'll send:

`details=JSONSTRING`, and consume it in bugform.js.

**Comment by miketaylr** [comment]
Oddly enough, the test from https://github.com/webcompat/webcompat.com/commit/440bad707f8dedde1256d66297d1741ed5e4bd10#diff-db9f827f59656441c082dbc15f76426b is no longer on master... possibly swallowed by the Intern 4 merge. :|

But, I was going to delete it anyways.

**Comment by karlcow** [comment]
@miketaylr we close this?
