### ISSUE TITLE
Put `details` contents in a hidden input

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat.com#2042]
Rather than populate the textarea (which can be ugly/confusing), @karlcow suggested we put it in a hidden input. We will display the content the same once the issue is created.

See https://github.com/webcompat/webcompat.com/pull/2041#discussion_r164319434

**Comment by miketaylr** [comment]
Another thing that might be good is once the issue is created, to put this pref inside a `<details>` element so it can be hidden by default. It's not always interesting to stare at.

e.g. https://gist.github.com/ericclemmons/b146fe5da72ca1f706b2ef72a20ac39d

**Comment by zoepage** [comment]
@miketaylr happy to tackle the `detail` issue with #2011

**Comment by miketaylr** [comment]
> @miketaylr happy to tackle the detail issue with #2011

Cool. Let's wait until we've fixed this bug first, before deciding how to do that. Thanks!

**Comment by miketaylr** [comment]
(and that random idea should be its own issue at some point -- this one is about hidden inputs).
