### ISSUE TITLE
Add buildID and update channel for Firefox browsers

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat.com#2047]
ref. https://github.com/webcompat/webcompat-reporter-extensions/issues/71

https://github.com/webcompat/webcompat-reporter-extensions/issues/71#issuecomment-318533516

We can just populate this data from `navigator.buildID` for browsers that support it (Firefox).

We could either do hidden metadata, or toss it in the description textarea with pref values. Thoughts @karlcow?

**Comment by karlcow** [comment]
I would choose hidden metadata in the textarea. For the reason that it is easier to manipulate and is less prone to destruction. We can still expose them through the UI elsewhere than the textarea too.

Design for this can come in a subsequent issue.

**Comment by miketaylr** [comment]
Sounds good to me. Thanks.

**Comment by adamopenweb** [comment]
Can we add `Update Channel` as well please?

It would make it easier to know the channel in our reports. Rather than taking the version and having to figure out what channel it was at a given point in time. `Update Channel` just tells us. 

It's useful to know if some channels are providing higher volume of bugs and higher % of valid bugs.

**Comment by miketaylr** [comment]
> Update Channel

@adamopenweb what's the best way to consume this for you? A label? A string somewhere in the issue body?

**Comment by adamopenweb** [comment]
Same way as `<!-- @reported_with: desktop-reporter -->` is fine. As long as it's consistent, it's somewhat easy to pull out.

**Comment by miketaylr** [comment]
> Can we add Update Channel as well please?

Yeah, we do this at the same time, at least for in-browser reports.

**Comment by miketaylr** [comment]
@karlcow I've got 3 ideas on how I could implement this, curious on your thoughts:

1. send this info from the browser as additional get params `buildID=20180404171943` (and `channel=nightly`), pass those into `get_metadata` (form.py)
2. add the information to the [`details` json object](https://dxr.mozilla.org/mozilla-central/source/browser/extensions/webcompat-reporter/content/WebCompatReporter.jsm#94). probably need to pull out those new keys and toss them into `get_metadata` or similar so they end up as hidden metadata comments.
3. add the information to the `details` hidden input (#2042) on the client, just before form submission. If we want it to be a "metadata" comment, this will require some manipulation of the hidden input value, and special casing for `get_metadata`. Maybe a little messy.


I would prefer 2, I think, but 1 seems simpler. Thoughts?

**Comment by miketaylr** [comment]
Note: option 3 won't work for `AppConstants.MOZ_UPDATE_CHANNEL`, it's too late at that point.

**Comment by miketaylr** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1399985 to track on the Bugzilla side.

**Comment by karlcow** [comment]
(I'll take time for this today) Just to let you know it's on my todo list.

**Comment by karlcow** [comment]
@miketaylr 
I have a tendency to prefer things sent through the `details` JSON when it's about the browser. It's more difficult to tamper the data. And we are talking about the "Report Site Issue" button, so things that people really report about the current experience in this browser. 

```
navigator.buildID
"20180412172954"
```

It's slightly different for the `/issues/new` form where we can report things which are not related to the current browser used to report.

So yeah Solution 2. seems fine.

**Comment by miketaylr** [comment]
Thanks @karlcow.

**Comment by miketaylr** [comment]
> probably need to pull out those new keys and toss them into get_metadata or similar so they end up as hidden metadata comments.

I'm sort of thinking these don't really need to be hidden. We'll see what it looks like.

**Comment by karlcow** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1399985 has been resolved as fixed.
#2042 has been fixed.

@miketaylr what is the next step?

**Comment by miketaylr** [comment]
> @miketaylr what is the next step?

Ah, this is fixed by both bugs you linked. As an example: https://github.com/webcompat/web-bugs/issues/17159. Sorry for not closing earlier.

**Comment by miketaylr** [comment]
(we should consider if it would be useful to have channel / version as a label at a future point, to find all issues reported for the nightly-62 cycle, for example)
