### ISSUE TITLE
Remove type-stylo from EXTRA_LABELS

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat.com#2051]
We no longer need to send it from Firefox:

https://reviewboard.mozilla.org/r/205210/diff/2#index_header

**Comment by miketaylr** [comment]
To fix this bug, remove the following line and send a PR!
* [ ] https://github.com/webcompat/webcompat.com/blob/master/config/__init__.py#L141

**Comment by miketaylr** [comment]
> To fix this bug, remove the following line and send a PR!

Also, we need to fix some tests after changing that: 

https://github.com/webcompat/webcompat.com/pull/2052#issuecomment-363646688

**Comment by suhailsinghbains** [comment]
Hi @miketaylr I have read the PRs made and your comments on it, I know specifically what to do now. This would be my first bug in Python, can I please be assigned this issue.
Thanks.

**Comment by suhailsinghbains** [comment]
No worries, I'll try to solve ASAP.
