### ISSUE TITLE
Don't hide parts of the screenshot

### ISSUE THREAD

**Issue by digitarald** [webcompat/webcompat.com#2055]
I wanted to report a layout issue on GA. The part I want to report on is hidden by the enormous yellow `remove image` button.

**Comment by karlcow** [comment]
@digitarald 

So you are saying we give this: 

<img width="620" alt="capture d ecran 2018-02-08 a 07 40 42" src="https://user-images.githubusercontent.com/505230/35945390-6862e8a8-0ca3-11e8-89a3-f5f903d702fb.png">

And you would prefer this?

<img width="614" alt="capture d ecran 2018-02-08 a 07 45 57" src="https://user-images.githubusercontent.com/505230/35945601-23e88c68-0ca4-11e8-898f-7c41b3ced63c.png">

if yes. This can be done as I just did… by

1. Putting the background-image (aka the screenshot) on `div.wc-UploadForm-wrapper`
2. and adding `padding: 52px` (or probably the equivalent value required) on the `label`

**Comment by karlcow** [comment]
@zoepage is working on redesign currently. And I'm not sure she is touching this part or not.

**Comment by zoepage** [comment]
We did a full redesign of that module. I hope, it will be more clear then :)

**Comment by zoepage** [comment]
Closing as this will be changed in the refactor
