### ISSUE TITLE
SVG in hero animation - bug + bulb

### ISSUE THREAD

**Issue by zoepage** [webcompat/webcompat.com#2061]
During the process, we mixed up the naming of 2 SVG's. 

This is why we need to change [`svg-bulb_nobug.svg`](https://github.com/webcompat/webcompat.com/blob/refactor/webcompat/static/img/svg/icons/svg-bulb_nobug.svg) and [`svg-bulb.svg`](https://github.com/webcompat/webcompat.com/blob/refactor/webcompat/static/img/svg/icons/svg-bulb.svg).

- [x] change `svg-bulb_nobug.svg` to `svg-bulb.svg`
- [x] change `svg-bulb.svg` to `svg-bug-animated.svg`
- [x] run `npm run build:svg` in your terminal
- [x] copy [sprite](https://github.com/webcompat/webcompat.com/blob/refactor/webcompat/static/img/svg/sprite.svg) in [html include](https://github.com/webcompat/webcompat.com/blob/refactor/webcompat/templates/shared/svg-icons.html) (Make sure, you keep the `is-hidden` class)
- [x] change SVG names / IDs in CSS files (search & replace for `svg-bulb_nobug.svg` and `svg-bulb.svg`)
- [x] test animation in index page

**Comment by mpaarating** [comment]
I got this one. Just to clarify task 4, the generated sprite should replace the svg-icons.html (keeping the `is-hidden` class though)

**Comment by zoepage** [comment]
@mpaarating yes. That sounds about right :)

**Comment by zoepage** [comment]
fixed by #2183
