### ISSUE TITLE
fix 404 page layout

### ISSUE THREAD

**Issue by zoepage** [webcompat/webcompat.com#2067]
The `grid` class is missing at the 404 page.

This is why it "falls out of the grid".
<img width="1405" alt="screen shot 2018-02-14 at 2 07 56 pm" src="https://user-images.githubusercontent.com/562354/36205859-88203924-1190-11e8-994b-0fc42642950e.png">

**Comment by mpaarating** [comment]
Is this still an issue? I'm not able to reproduce the behavior in chrome or firefox.

**Comment by softvision-sergiulogigan** [comment]
@mpaarating try https://staging.webcompat.com/issues/138d in Chrome or Nightly.

![image](https://user-images.githubusercontent.com/16573771/36429969-b181e51c-165c-11e8-8c24-17a5732430d1.png)

**Comment by mpaarating** [comment]
I see it now. I was just using the wrong url :D I'll go ahead and snag this if its cool.

**Comment by zoepage** [comment]
Feel free @mpaarating :)

**Comment by mpaarating** [comment]
Will do! Thanks!

**Comment by miketaylr** [comment]
> Edit: @zoepage Maybe I'm crazy, but staging and prod look very different. My local branch off master looks like prod (no 404 bug), what branch is staging based off?

Not crazy! Staging is based on the `refactor` branch, while production is the `master` branch.

**Comment by mpaarating** [comment]
@miketaylr Good to know! Thanks!
