### ISSUE TITLE
Issues list pagination missing cursor: pointer on previous and next

### ISSUE THREAD

**Issue by adamopenweb** [webcompat/webcompat.com#2069]
The previous and next buttons don't show a pointer when hovering with mouse.

<img width="546" alt="screen shot 2018-02-15 at 12 21 12 pm" src="https://user-images.githubusercontent.com/6587558/36270825-c26152c0-124a-11e8-95f8-1f82b50a4193.png">

**Comment by zoepage** [comment]
fixed by #2129
