### ISSUE TITLE
Meet the Wompats on home page links to wrong page

### ISSUE THREAD

**Issue by adamopenweb** [webcompat/webcompat.com#2070]
I think this is a bug?

**Find out and meet the Wompats** links to:
https://webcompat.com/about

I thought it would go to:
https://webcompat.com/contributors

<img width="300" alt="screen shot 2018-02-15 at 12 41 29 pm" src="https://user-images.githubusercontent.com/6587558/36271819-c0d9d834-124d-11e8-9af7-b9b321c94dc1.png">

**Comment by zoepage** [comment]
Thanks Adam, you are 100% right!

This link can be changed here: https://github.com/webcompat/webcompat.com/blob/refactor/webcompat/templates/home-page/how-it-works.html#L24

**Comment by zoepage** [comment]
merged #2223
