### ISSUE TITLE
"Upload screenshot" label is off-center

### ISSUE THREAD

**Issue by denschub** [webcompat/webcompat.com#2071]
<img width="439" alt="screen shot 2018-02-15 at 19 40 18" src="https://user-images.githubusercontent.com/344777/36274466-1b9c3642-1288-11e8-8ce8-c578bc6db46a.png">

Marking this as a bug, because it bugs me. 🐛 🤡

**Comment by miketaylr** [comment]
Oddly, the screenshot in my dupe report shows it aligned to the right? 

https://github.com/webcompat/webcompat.com/issues/2072#issue-297563691

**Comment by miketaylr** [comment]
<img width="481" alt="screen shot 2018-02-15 at 1 13 36 pm" src="https://user-images.githubusercontent.com/67283/36276005-25da0944-1252-11e8-93ea-d6633ef7f3c5.png">

**Comment by denschub** [comment]
It actually depends on the browser width! `.form-upload .label-icon` is styled absolute, but the `<div class="form-upload js-image-upload js-Form-group">` doesn't reset the context with a `position: relative;`.

**Comment by softvision-oana-arbuzov** [comment]
Also reproducible on Mobile.
![screenshot-1519031717237](https://user-images.githubusercontent.com/12184325/36370032-27e278b8-1566-11e8-9e0f-7d05b0c217b6.jpg)

Affected area:
```html
<div class="label-icon label-upload js-label-upload">
	<svg class="icon icon-big" role="presentation" title="Upload Screenshot">
		<use class="icon-upload" href="#svg-plus">Upload Screenshot</use>
	</svg>
	<small class="label-icon-message">Upload screenshot</small>
</div>
```

**Tested with:**
Browser / Version: Firefox Nightly 60.0a1 (2018-02-18) (Mobile), Chrome 64.0.3282.137 (Mobile).
Operating System: Google Pixel (Android 8.0.0) - 1080 x 1920 pixels (~441 ppi pixel density)

**Comment by zoepage** [comment]
Tested in various widths. Feel free to test again.

**Comment by denschub** [comment]
Looking great, thank you!
