### ISSUE TITLE
Jumping validation requirements

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat.com#2074]
STR:

1. go to staging.webcompat.com/issues/new
2. hit tab to cycle thru the form (or just click in and out of the URL and description inputs

Actual:
I get shown a "A valid URL is required.", etc. which causes the layout to jump down. 

Expected:
Can we figure out how to do this without shifting layout?

Also, when you put something in, those messages don't disappear. Not sure if that is intended behavior.

**Comment by zoepage** [comment]
> Also, when you put something in, those messages don't disappear. Not sure if that is intended behavior.

This is definitely a bug that needs to be fixed.

> Can we figure out how to do this without shifting layout?

Definitely. Do you feel this has a high prio or could be split the two issues?

**Comment by zoepage** [comment]
> Also, when you put something in, those messages don't disappear. Not sure if that is intended behavior.

This is related to #2149 and will be fixed with that issue.

**Comment by miketaylr** [comment]
> Definitely. Do you feel this has a high prio or could be split the two issues?

Splitting seems fine!

**Comment by zoepage** [comment]
FYI #2149 is fixed. We just need to fix the jumping issue now.

**Comment by zoepage** [comment]
merged #2197
