### ISSUE TITLE
Label /widget editor icon moves when opening

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat.com#2076]
STR:

1. go to https://staging.webcompat.com/issues/1368
2. login
3. click on the label or milestone editor to open it
4. click in the same spot to close it

depending on where you were for 3, 4 is not possible because it shifts location. We should make sure that doesn't happen.

![jumping-button](https://user-images.githubusercontent.com/67283/36276724-6cab45f2-1254-11e8-842a-909072478034.gif)

**Comment by zoepage** [comment]
So, this is 100% about position of the dropdown, correct? :)

**Comment by zoepage** [comment]
merged #2133
