### ISSUE TITLE
User dropdown misaligned

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat.com#2079]
STR

1. go to staging.webcompat.com
2. log in
3. click on your avatar to open the menu

expected:
it opens below my username

actual:

<img width="765" alt="screen shot 2018-02-15 at 1 37 25 pm" src="https://user-images.githubusercontent.com/67283/36277079-76a6968c-1255-11e8-9436-d2e6bc1dcec2.png">

**Comment by zoepage** [comment]
fixed my #2131
