### ISSUE TITLE
[design] bug milestones feel misaligned on all issues page

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat.com#2080]
If you go to staging.webcompat.com, observe the following:

<img width="843" alt="screen shot 2018-02-15 at 1 42 34 pm" src="https://user-images.githubusercontent.com/67283/36277297-1c2a9612-1256-11e8-9c14-86a6f5d2cec9.png">

It's hard for me to scan from the top left down because things aren't aligned. Can we improve this somehow?

(the same is true for the right as well):

<img width="259" alt="screen shot 2018-02-15 at 1 43 18 pm" src="https://user-images.githubusercontent.com/67283/36277370-4dec1c70-1256-11e8-8465-48083f8e8736.png">

**Comment by miketaylr** [comment]
(Note: I don't think we should block on this particular issue, this is something that could be incrementally improved, if it turns out to be a huge PITA)

**Comment by karlcow** [comment]
@miketaylr Do you mean you would prefer something like
![capture d ecran 2018-02-16 a 13 31 41](https://user-images.githubusercontent.com/505230/36293539-d787e05a-131d-11e8-8077-7b4b5fed6162.png)

**Comment by karlcow** [comment]
Previous screenshot done with flexbox.

**Comment by miketaylr** [comment]
@karlcow yep, much nicer.

**Comment by zoepage** [comment]
Thanks for the feedback @miketaylr. I can see the issue you're having.

@karlcow As every padding / margin has a purpose and groups specific elements to guide the user through the content, your suggestion would not work as the filter would suddenly appear as a 1st grade element, but it is a supporting one for the content (which means, the site would still work without it, so 3rd grade element).

What would work is following:
<img width="768" alt="screen shot 2018-02-19 at 12 08 25 pm" src="https://user-images.githubusercontent.com/562354/36374977-a358f768-156d-11e8-8823-f5ed7cf283dd.png">

1. aligning the filter bar with the content of the issue
2. decrease the margin-left/right for the navigation

Would this be something that works for you @miketaylr?
