### ISSUE TITLE
Report as buttons not aligned when signed in

### ISSUE THREAD

**Issue by adamopenweb** [webcompat/webcompat.com#2081]
The form buttons for reporting anonymous or on Github are not aligned once I sign in.

<img width="500" alt="screen shot 2018-02-15 at 4 00 04 pm" src="https://user-images.githubusercontent.com/6587558/36280830-9e9a0048-1269-11e8-9960-c4f636370746.png">

**Comment by zoepage** [comment]
Thanks Adam. This is definitely a bug. The buttons should take the full width when they don't fit next to each other.

**Comment by zoepage** [comment]
@Regaddi you'd be interested in tackling that one? Happy to walk you through.

**Comment by Regaddi** [comment]
I'll give it a shot tomorrow morning on train to work ✌️

**Comment by zoepage** [comment]
Sweet, thanks! :)

The padding issue is fixed. What we need is that the buttons use the full width, when they can't use their space. 

So, something like:
<img width="197" alt="screen shot 2018-03-12 at 10 23 48 pm" src="https://user-images.githubusercontent.com/562354/37310399-142cb060-2644-11e8-8cbd-a84c83f3a357.png">

**Comment by Regaddi** [comment]
This applies also to desktopish screen sizes, where longer usernames let the yellow button drop below, right? So I might follow a flexbox approach here.

**Comment by Regaddi** [comment]
I've got some progress here. I need some further details to finalize:

![image](https://user-images.githubusercontent.com/1336590/37327077-248c084c-2695-11e8-877a-c17408045416.png)

![image](https://user-images.githubusercontent.com/1336590/37327086-2c4758de-2695-11e8-903a-1dc41dbe9ba4.png)

The flexbox approach worked pretty well. However, when the buttons are aligned side by side, there is no gap between them.
Should there be a little gap of let's say 5px or 10px?
Or is this irrelevant due to the "Report Anonymously" having a white background anyway?

**Comment by zoepage** [comment]
Thanks! That looks great already. Glad also you took the flexbox approach as this was the idea, but I saw I didn't mentioned it. 🙈

+1 on gap. There was already a bug filed (which I can't find right now).

Also, the background of the `report anonymously` button should not be white. 🤔

**Comment by Regaddi** [comment]
![image](https://user-images.githubusercontent.com/1336590/37331297-db870610-26a3-11e8-83c4-429dfbf12887.png)

![image](https://user-images.githubusercontent.com/1336590/37331330-f2eb0090-26a3-11e8-9036-cb720701f9f7.png)


I just added some border to visualize the gap (20px now, to be consistent with the gap to the upload-element).

I introduced a new CSS class for this behaviour, called `.form-button-multiple` which needs to be added additionally to the `.form-button` element, when there are multiple buttons used inside.

**Comment by zoepage** [comment]
Sounds great. Feel free to send a PR when you are done and add `r? @zoepage`. 
Thanks!

**Comment by zoepage** [comment]
merged #2226
