### ISSUE TITLE
[design] wide yellow header

### ISSUE THREAD

**Issue by karlcow** [webcompat/webcompat.com#2082]
The wide yellow header feels unbalanced with the rest of the page.
Probably related to #2078
<img width="1057" alt="capture d ecran 2018-02-16 a 07 30 36" src="https://user-images.githubusercontent.com/505230/36284808-807c5916-12ec-11e8-8e35-db0314e46701.png">

**Comment by zoepage** [comment]
I'd suggest to give it a week or two as this issue came up before a few times, but it turned out it was basically just needed a moment of adjustment for them. After people got used to it, it didn't matter anymore. 

Happy to discuss this in a bit again.

**Comment by zoepage** [comment]
As there was no answer on this, closing for now. We can re-open if this is still an issue.

**Comment by miketaylr** [comment]
> After people got used to it, it didn't matter anymore.

I actually was just thinking this. I don't mind it anymore.
