### ISSUE TITLE
Use of wompats term

### ISSUE THREAD

**Issue by karlcow** [webcompat/webcompat.com#2084]
> Find out and meet the Wompats. 

Let's not add terms like this in the project.

**Comment by zoepage** [comment]
I'd be interested in the reason for this. :)

**Comment by karlcow** [comment]
@zoepage This is a term which has no meaning in the 4+ years of the project. It was created from my understanding during the Berlin sprint as a twitter joke and it has been used during in talks. The same way that @miketaylr used "can of worms", etc. These are funny transitional jokes, and they are cool because they are just that. They don't belong on the site itself.

**Comment by zoepage** [comment]
The main reason for creating this term as well as going on with this is to create a term for a group, so people can relate to it and feel like they belong. It also makes identifying other peers of your "group" easier. 

Other existing examples are:
- Pythonistas (Python community)
- Gophers (Go community)
- Documentarians (Docs community)
- Rustaceans (Rust community)
- Hoodies (Hood.ie community)
- Djangonauts (Django community)
... and others.

**Comment by karlcow** [comment]
Then let it grow and they will own it (they, the community if there is a strong one. Grassroot style. The mass will decide), no need to force it down.

**Comment by zoepage** [comment]
The term already got really positive feedback and is something people enjoy adapting. I guess, this happened then already.

**Comment by miketaylr** [comment]
I'm -1 on the term (I've already given that feedback to Ola a while back), mostly because wombat is already an npm thing: https://www.google.ca/search?q=npm+wombat

**Comment by miketaylr** [comment]
I think we ended up not shipping this, sorry little wompats. ;___;
