### ISSUE TITLE
Refactor Typos

### ISSUE THREAD

**Issue by karlcow** [webcompat/webcompat.com#2085]
Instead of having all of us opening an individual issue for each typo. Let's put them here.

* [x]  "People expect websites to work regardless of the device or browser they are using. If they are behaving differently, that is most **likey** a web compatibility bug we are looking for. "

**Comment by softvision-sergiulogigan** [comment]
I think "webcompat" should be capitalized here, as it's not referring to the website (webcompat.com), but to the project.
https://staging.webcompat.com/contributors/build-tools
![image](https://user-images.githubusercontent.com/16573771/37091337-73737d8e-2210-11e8-8a57-06baf45d7a5d.png)

**Comment by softvision-sergiulogigan** [comment]
I think I found a typo here:
[...]Microsoft Edge team and Google Chrome team are also participating **from** time to time.[...]
https://staging.webcompat.com/contributors/build-tools
![image](https://user-images.githubusercontent.com/16573771/37091443-d1e56256-2210-11e8-8c4e-f88dec63ed08.png)

**Comment by softvision-sergiulogigan** [comment]
And also I think here is missing a **From**
![image](https://user-images.githubusercontent.com/16573771/37091555-4b928a66-2211-11e8-9eb0-034dd98c84dd.png)

**Comment by softvision-sergiulogigan** [comment]
And also here (if the above ones are valid)
![image](https://user-images.githubusercontent.com/16573771/37091818-3a817e70-2212-11e8-9326-ab93970ad8e4.png)
https://staging.webcompat.com/contributors/organize-webcompat-events

**Comment by softvision-sergiulogigan** [comment]
Found another typo here:

[...]It's also a good ~opportunities~ **opportunity** for people[...]
![image](https://user-images.githubusercontent.com/16573771/37091888-6c952470-2212-11e8-8be8-6ea3eea07b1f.png)

https://staging.webcompat.com/contributors/organize-webcompat-events

**Comment by zoepage** [comment]
merged #2293
