### ISSUE TITLE
[content] Alumni page

### ISSUE THREAD

**Issue by karlcow** [webcompat/webcompat.com#2086]
I wonder if we need an alumni page for the site.
https://staging.webcompat.com/contributors
https://staging.webcompat.com/contributors/alumni
Some people have participated to this website meaningfully in the past.

See for example
* https://www.w3.org/People/
* https://www.w3.org/People/Alumni

**Comment by zoepage** [comment]
Cool! I think, this is a really good idea. 
Feel free to gather the content and send a PR. :)

**Comment by karlcow** [comment]
@zoepage thanks. Do you have a preferred way on where it should live and interact with other pages.

In the current contributors
@haseebgit is probably missing. He helped a lot in India to kick start webcompat


For Alumni, this would require to collect the bio of (at least).

* @hallvors 
* @calexity 
* @tagawa 
* @cch5ng 
* @deepthivenkat 


@miketaylr Do you see other people?

**Comment by zoepage** [comment]
Thanks @karlcow 

What we need is:
- short bio (max 250 chars)
- location
- 1-2 preferred links (e.g. twitter, web site etc., GH link will always be included)

**Comment by miketaylr** [comment]
> @miketaylr Do you see other people?

This seems like a nearly complete list of "people who have made significant contributions in the past", just missing Misha I think. @adamopenweb anyone else?

**Comment by zoepage** [comment]
For the record: Mesa would be @lockettm

**Comment by adamopenweb** [comment]
Also should be included:
@tsl143 
@bslassey
@lmandel

**Comment by karlcow** [comment]
@ksy36 Could you give us simple description so we can add you to the [contributors list](https://webcompat.com/contributors)? See what other people gave if you need inspiration. Thanks.
