### ISSUE TITLE
Top sticky header is breaking the anchors

### ISSUE THREAD

**Issue by karlcow** [webcompat/webcompat.com#2087]
Go to https://staging.webcompat.com/contributors/web-platform-research#surveys
<img width="856" alt="capture d ecran 2018-02-16 a 08 01 27" src="https://user-images.githubusercontent.com/505230/36285620-9bd73278-12ef-11e8-929b-090d89e9e8cb.png">

We should be able to read the header of this section. 

Personally I don't think the header should be sticky. It should just go away when we scroll.

**Comment by zoepage** [comment]
>  It should just go away when we scroll.

I disagree, as scrolling will get annoying on some pages where we have a lot of content. 
A solution could be to have a combination of both: http://hood.ie/

**Comment by miketaylr** [comment]
Another symptom is when we click Report Bug:

(the fixed header cuts off half of the black button)

![screenshot_20180316-175522](https://user-images.githubusercontent.com/67283/37548044-4bf420bc-2943-11e8-96e6-0f985734ec28.png)

**Comment by miketaylr** [comment]
> A solution could be to have a combination of both: http://hood.ie/

So, it disappears when you scroll down, but re-appears when you start to scroll up. This seems like a great solution.
