### ISSUE TITLE
Contribute -> Team

### ISSUE THREAD

**Issue by karlcow** [webcompat/webcompat.com#2088]
When someone clicks on Contribute in the top header.
<img width="393" alt="capture d ecran 2018-02-16 a 08 04 20" src="https://user-images.githubusercontent.com/505230/36285722-1a504a04-12f0-11e8-928e-2dc42f621629.png">

it lands to a page where the main content is The team. It feels weird and put us before the tasks. I think we should direct people to ways of contributing, not us.

**Comment by zoepage** [comment]
1. The index will get a quick link section like following to direct people to the ways of contributing:
<img width="1387" alt="screen shot 2017-11-27 at 2 57 38 pm" src="https://user-images.githubusercontent.com/562354/36375365-54da13d6-156f-11e8-81a4-394f6e16729a.png">

2. One of the identified issues, why contributors do not stick around or don't contribute in first place is the not transparent community behind the project. By introducing the team, we create a more welcoming and transparent environment. 

Possible solutions here could be: 
- Adding a intro on the team to make clear people can / want join it.
- Adding a `call to action` to join the team at the end of the list.

**Comment by zoepage** [comment]
merged in #2238
