### ISSUE TITLE
[design] right side menu on issue doesn't stick

### ISSUE THREAD

**Issue by karlcow** [webcompat/webcompat.com#2090]
1. Go to https://staging.webcompat.com/issues/1368
2. Scroll a bit. The right side context is going away.

![capture d ecran 2018-02-16 a 08 48 47](https://user-images.githubusercontent.com/505230/36287143-62ad4742-12f6-11e8-8f3b-fd292375e04e.png)

This is a regression. We had won this feature in the past, to keep the context around on desktop so it's faster to change labels and status.

![capture d ecran 2018-02-16 a 08 53 12](https://user-images.githubusercontent.com/505230/36287222-e332fede-12f6-11e8-9caf-daf7d0bc4dcc.png)

**Comment by zoepage** [comment]
merged #2133
