### ISSUE TITLE
Comment section - Huge upload screenshot / Small comment section

### ISSUE THREAD

**Issue by karlcow** [webcompat/webcompat.com#2091]
That doesn't have the right feeling.

* [ ] we can't see the comment section
* [ ] Upload screenshot is using all the space.
* [ ] Comment button seems out of place.

![capture d ecran 2018-02-16 a 09 01 18](https://user-images.githubusercontent.com/505230/36287452-558f8280-12f8-11e8-8b86-2f3becda1e70.png)

I would imagine something more like this.

![capture d ecran 2018-02-16 a 09 27 47](https://user-images.githubusercontent.com/505230/36287971-b57ef68c-12fb-11e8-8efd-94cd0d64c1c7.png)

**Comment by karlcow** [comment]
forgotten the background-color

![capture d ecran 2018-02-16 a 09 29 32](https://user-images.githubusercontent.com/505230/36288004-ed184ddc-12fb-11e8-863a-25aed9971360.png)

**Comment by karlcow** [comment]
> Upload screenshot is using all the space.

I guess this part is #2128

For the comment section, what it looks like as of today's refactor branch.

<img width="678" alt="capture d ecran 2018-03-21 a 09 37 38" src="https://user-images.githubusercontent.com/505230/37689978-946c52a0-2ceb-11e8-9d6a-61310ece11a5.png">

**Comment by zoepage** [comment]
As described in the release document, we'll take care of this as we classified this as a P1 bug.

**Comment by karlcow** [comment]
very cool!

**Comment by zoepage** [comment]
merged #2283
