### ISSUE TITLE
Adding a comment is broken.

### ISSUE THREAD

**Issue by karlcow** [webcompat/webcompat.com#2092]
1. Go to an issue 
2. Enter a simple comment
3. We are redirected to https://staging.webcompat.com/issues/1360?image=  
  Without the comment.  
  We need to refresh to see the comment.

**Comment by miketaylr** [comment]
It shouldn't even redirect or reload the page. It should re-render the template.

**Comment by miketaylr** [comment]
The `?image` likely comes from the image upload input which has `name=image`. But we shouldn't be doing a form submission, this is supposed to be handle by XHR.

**Comment by miketaylr** [comment]
This is what broke it: https://github.com/webcompat/webcompat.com/pull/2039/files#diff-1135c93681edf8952cb4ffe7b89d83b1R1

If you just change a div to a form without preventing the default form action, bad things will happen. I'll fix this in #2108.
