### ISSUE TITLE
Upload images in Comment fails

### ISSUE THREAD

**Issue by karlcow** [webcompat/webcompat.com#2093]
1. Go to https://staging.webcompat.com/issues/1360
2. Upload a screenshot in the comment section
3. We are redirected to https://staging.webcompat.com/issues/1360?image=Capture+d%E2%80%99e%CC%81cran+2018-02-16+a%CC%80+09.29.32.png#issuecomment-366109701

A reload doesn't show the image. The upload has failed.

**Comment by magsout** [comment]
@karlcow @zoepage I'm not able to reproduce this issue, maybe a commit fixed this issue?

**Comment by zoepage** [comment]
I'm not able to reproduce either...

**Comment by karlcow** [comment]
Tried this too like in #2095 This has been fixed. 
Thanks a lot @zoepage and @magsout
