### ISSUE TITLE
nesting div for the main content.

### ISSUE THREAD

**Issue by karlcow** [webcompat/webcompat.com#2094]
Not sure if it's a typo in a template, but in case a `div` to just wrap the content seems to be bogus. 

![capture d ecran 2018-02-16 a 09 41 10](https://user-images.githubusercontent.com/505230/36288352-9af50d0e-12fd-11e8-89ad-a9a865fde5ae.png)

**Comment by karlcow** [comment]
Hmmm I check some part of the markup. I'm not sure if it's interesting/useful/constructive as a review or not. Some of the things I see are not right in the redesign in terms of semantics. 🧠 (Note that I don't think the current ones are correct too, it's just that with redesign I hoped for a better markup.)

Also let's not forget that I'm an HTML dinosaur who loves reading HTML. 🧓🏻🦖 I will go extinct soon with 🌊 or ☄️

🕳

**Comment by zoepage** [comment]
That div seems like a left-over and should be removed.
It can be found here: 
https://github.com/webcompat/webcompat.com/blob/refactor/webcompat/templates/layout.html#L39-L42

**Comment by amitsin6h** [comment]
I want to take this

**Comment by zoepage** [comment]
merged #2222
