### ISSUE TITLE
Posting a comment with markdown markup

### ISSUE THREAD

**Issue by karlcow** [webcompat/webcompat.com#2095]
1. Go to an issue
2. Post a comment with markup.
![capture d ecran 2018-02-16 a 09 48 48](https://user-images.githubusercontent.com/505230/36288560-9cf72ac8-12fe-11e8-9d4d-0f27e4ef6e79.png)
3. we end up with a bad redirection and the comment not being posted.

**Comment by miketaylr** [comment]
It seems like maybe issue commenting broken now cf. #2093

**Comment by zoepage** [comment]
Interesting!
The comment gets posted, but can be viewed after the reload.
https://staging.webcompat.com/issues/1372?image=

**Comment by karlcow** [comment]
It's not: Try this for example.

```html
<ul class="nav-left">
            <li class="nav-item">
                <a href="/" title="Navigate to main page." class="js-Navbar-link nav-link">
                    <svg class="icon nav-icon" viewBox="0 0 30 30" role="presentation">
                        <title>Home</title>
                        <use href="#svg-home">home</use>
                    </svg>
                    <span class="link-text">Home</span>
                </a>
            </li>
            <li class="nav-item">
                <a href="/issues/new" title="Report a bug" class="js-Navbar-link nav-link">
                    <svg class="icon nav-icon" viewBox="0 0 30 30" role="presentation">
                        <title>bug</title>
                        <use href="#svg-zap">bug</use>
                    </svg>
                    <span class="link-text">Report a bug</span>
                </a>
            </li>
        </ul>
```

**Comment by magsout** [comment]
@zoepage @karlcow 

I commented https://staging.webcompat.com/issues/1372 and the markup seems working. I tried with your example @karlcow

**Comment by karlcow** [comment]
ah! cool! Let me try too! Excellent. This is working.
Thanks. Something has fixed it.
