### ISSUE TITLE
twitter icon to https://twitter.com/webcompat/with_replies

### ISSUE THREAD

**Issue by karlcow** [webcompat/webcompat.com#2097]
The https://twitter.com/webcompat/with_replies doesn't work anymore for the last couple of months if you are not logged in. This is a bummer. Intended change by twitter.

The only equivalent now is something along
https://twitter.com/search?f=tweets&vertical=default&q=%40webcompat&src=typd

**Comment by zoepage** [comment]
Thanks for the hint. This is good to know.

**Comment by amitsin6h** [comment]
I want to take this

**Comment by zoepage** [comment]
You claimed 2 issues. Please decide on one. Thanks

**Comment by amitsin6h** [comment]
@zoepage want to work on this first.

**Comment by zoepage** [comment]
Cool. Let me know, if you have any questions.

**Comment by amitsin6h** [comment]
@zoepage sure

**Comment by amitsin6h** [comment]
@zoepage how can I run webcompat locally

**Comment by zoepage** [comment]
@amitsin6h https://github.com/webcompat/webcompat.com/blob/refactor/docs/dev-env-setup.md

**Comment by amitsin6h** [comment]
@zoepage yeah manged to run :+1:

**Comment by amitsin6h** [comment]
@zoepage could you please review my PR #2185
