### ISSUE TITLE
status categories on all issues page

### ISSUE THREAD

**Issue by karlcow** [webcompat/webcompat.com#2099]
Go to https://staging.webcompat.com/issues?page=1&per_page=50&state=open&stage=all&sort=created&direction=desc

The categories take a lot of space.
![capture d ecran 2018-02-16 a 12 31 08 2](https://user-images.githubusercontent.com/505230/36292481-740f038a-1315-11e8-83b4-df42876daeb6.png)

**Comment by magsout** [comment]
@karlcow if screen > 960px:

![capture d ecran 2018-02-16 a 22 58 48](https://user-images.githubusercontent.com/1997108/36331157-004c96bc-136d-11e8-9a33-b844d1b947c1.png)

**Comment by zoepage** [comment]
The view as reported is actually a feature. We can add a filter icon to it, so we can toggle the visibility, if this would improve the experience.

**Comment by karlcow** [comment]
ah I see. I don't know if I'm the only one, but I often have my window under 960px on desktop. And in the current design that looks weird compared to the old one.

I often work like this (right window):
<img width="1080" alt="capture d ecran 2018-02-20 a 15 31 13" src="https://user-images.githubusercontent.com/505230/36410255-42ff2b8a-1653-11e8-87fd-826dac529bcb.png">

A long narrow window that I put on the right side of the screen for exploring the issues. 

Maybe I can live with it (aka the new design).

**Comment by zoepage** [comment]
@karlcow 

> We can add a filter icon to it, so we can toggle the visibility, if this would improve the experience.

I'm not sure, if your comment refers to the suggested solution?

**Comment by zoepage** [comment]
Closing as there is no feedback. We can re-open, if the issue comes back up.
