### ISSUE TITLE
Remove screenshot is awkward and not readable

### ISSUE THREAD

**Issue by karlcow** [webcompat/webcompat.com#2100]
1. Fill the form. 
2. Add a screenshot.
3. Look at the remove screenshot part.

![capture d ecran 2018-02-16 a 12 41 32 2](https://user-images.githubusercontent.com/505230/36292693-f463cf38-1316-11e8-806d-b5c98deb1790.png)

The remove part is not visible and really usable in that state.

**Comment by miketaylr** [comment]
And depending on the type of screenshot (imagine a pure black image of some graphics problem), you won't be able to see it at all.

**Comment by zoepage** [comment]
The hover changes the button + label to yellow, but I can see the issue.

Options we have:
- add a light shadow to the dark button + label and a dark one to the yellow.
- add opacity of e.g. 0.7 to the image preview
- add an overlay to the image preview

Which ones would you prefer?

**Comment by karlcow** [comment]
Probably the remove upload should not be on top of the image at all.
That was the sense of the issue of #2055 if I understood. 
I would put the remove button either under the image preview, or just a "x" style button in the top right corner as we see in all sites now. That should cognitively ring a bell to people who sees that.

<img width="782" alt="capture d ecran 2018-02-19 a 21 53 14" src="https://user-images.githubusercontent.com/505230/36378758-722331f2-15bf-11e8-9235-bbc4f3b1c76b.png">

**Comment by zoepage** [comment]
This creates the same issue with visibility as the one right now as this is also on the image.

So, I'd say we go back to the 3 suggestions above.

**Comment by zoepage** [comment]
As there was no feedback on suggested solutions, I'll close this issue as we can re-open when it comes back.

**Comment by miketaylr** [comment]
Similar to what @karlcow suggests in https://github.com/webcompat/webcompat.com/issues/2100#issuecomment-366685241, something like the following would be pretty good, and very hard to miss:

<img width="205" alt="screen shot 2018-07-06 at 10 05 19 am" src="https://user-images.githubusercontent.com/67283/42386087-22fadb92-8104-11e8-9a02-e27b9092f234.png">

**Comment by miketaylr** [comment]
@Regaddi maybe an issue you could help us out with?

**Comment by karlcow** [comment]
@magsout will check what could be done.
