### ISSUE TITLE
Contrast in between instructions and user input

### ISSUE THREAD

**Issue by karlcow** [webcompat/webcompat.com#2101]
The new form is generally more elegant than the previous one, but it also has its own set of UX issues.
Once I have filed it, it becomes hard to review and see at first sight what I have entered there. Specifically in the Description and textarea sections.

![capture d ecran 2018-02-16 a 12 41 32 2](https://user-images.githubusercontent.com/505230/36292757-6664a95e-1317-11e8-97f3-f2315d5121bd.png)

**Comment by karlcow** [comment]
What about changing the color of the background once some text are in there.

![capture d ecran 2018-02-16 a 12 50 55](https://user-images.githubusercontent.com/505230/36292859-1e0508ce-1318-11e8-90a9-3d0407865dda.png)

**Comment by zoepage** [comment]
I don't think adding a different background is the solution here as this is not easy on the eye and will take away the focus of the other parts of the form.

A good solution here could be to increase the whitespace between the inputs / textarea as well the line-height in the textarea. 

Would this solve the issue?

**Comment by karlcow** [comment]
Just to be sure we understood each other. I have written (after fixing grammar)

> What about changing the color of the background **once some text is in there.**

And I added the background-color **because it was not easy** on my eyes. 😁 Getting old here 🤓 eyesight getting low and contrast helps. Accessibility, my love.

> increase the whitespace between the inputs / textarea as well the line-height in the textarea. Would this solve the issue?

I don't know let me try. Opening devtools. marginally better by overblowing it. 😕 and not really pleasing. 

<img width="956" alt="capture d ecran 2018-02-19 a 22 04 55" src="https://user-images.githubusercontent.com/505230/36379184-fc0c86ba-15c0-11e8-8aa3-52f46b625178.png">

What did you have in mind?

**Comment by karlcow** [comment]
ahah. And sorry just realized that I used a Frenchism which might be misinterpreted. 

> Accessibility, my love.

refers to http://www.imdb.com/title/tt0052893/ Hiroshima mon amour. Feeling dumb suddenly.

**Comment by zoepage** [comment]
I agree. This was very inappropriate. I'd kindly ask you to remove this line from the comment.

**Comment by zoepage** [comment]
merged #2200
