### ISSUE TITLE
Yes - No choice for Test in another browser

### ISSUE THREAD

**Issue by karlcow** [webcompat/webcompat.com#2102]
I was wondering if it's the best way to ask this question, which is currently 3 states

* yes
* no
* Nothing (nobody knows) 

Should it be?

Did the site work in another browser?
* [ ] yes [this one]

(a non answer to the question would mean I didn't check or I don't care)
The textarea gives the possibility to give the name for a browser with an autosuggestive list of browser names on focus ala keyword in stackoverflow.

**Comment by miketaylr** [comment]
It would be an improvement over what we get now, I think.

**Comment by zoepage** [comment]
We had this discussion here already: https://github.com/webcompat/webcompat.com/issues/1278#issuecomment-275170978 

I'll close this as a dup and lets take the conversation there.
