### ISSUE TITLE
[form] breathing space for the mandatory red asterisk

### ISSUE THREAD

**Issue by karlcow** [webcompat/webcompat.com#2103]
Not a bug, just a feeling.

![capture d ecran 2018-02-16 a 13 02 12](https://user-images.githubusercontent.com/505230/36293059-c0e6fccc-1319-11e8-9142-bcee6214afc9.png)

Maybe a bit more space for the mandatory asterisk

![capture d ecran 2018-02-16 a 13 01 52](https://user-images.githubusercontent.com/505230/36293066-de2c2adc-1319-11e8-85be-8fc6001713aa.png)

**Comment by magsout** [comment]
@zoepage is it enought https://github.com/webcompat/webcompat.com/pull/2143 ? Or we need something more ?

**Comment by zoepage** [comment]
No, this is enough and got merged. :)
