### ISSUE TITLE
favicon homescreen - Android firefox

### ISSUE THREAD

**Issue by magsout** [webcompat/webcompat.com#211]
Quality is bad and i don't know why

Border: Chrome
Whithout border : firefox

![2014-07-30 08 55 12-1](https://cloud.githubusercontent.com/assets/1997108/3748597/526d6dc8-17df-11e4-98b0-df1ba3e23b77.png)

**Comment by miketaylr** [comment]
We need to find the right link for Fennec.

**Comment by miketaylr** [comment]
The Fennec team is going to explore picking the nicer quality icons for homescreen icons, similar to Chrome Mobile. :+1:

**Comment by magsout** [comment]
ohh coool

**Comment by magsout** [comment]
@miketaylr any update ? or have you got the bug url ?

**Comment by miketaylr** [comment]
*Possibly* the fix for this landed yesterday, so it should be in tte next Nightly. https://bugzilla.mozilla.org/show_bug.cgi?id=1238656. We should re-open that bug if it doesn't do what we want (I haven't tested yet)

**Comment by miketaylr** [comment]
OK, I think this is fixed!

**Comment by miketaylr** [comment]
(it's not 100% the same as Chrome, but it gives a hi-res icon that doesn't look like garbage)

**Comment by magsout** [comment]
Nice 👍
