### ISSUE TITLE
Image upload button too big for issue page

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat.com#2128]
For the issue page, we don't show any previews or anything, we just have a regular "button" you click to select an image, then it's path is put in the comment textarea.

Old:
<img width="830" alt="screen shot 2018-02-16 at 4 20 35 pm" src="https://user-images.githubusercontent.com/67283/36331886-606b9832-1335-11e8-8f20-fe204cb669bd.png">

New:
<img width="616" alt="screen shot 2018-02-16 at 4 20 45 pm" src="https://user-images.githubusercontent.com/67283/36331893-64faa38e-1335-11e8-9890-5330e6669b33.png">

It probably doesn't make sense to re-use the same upload component from the new issue page here.

**Comment by zoepage** [comment]
We can make the section smaller, but I'd like to stick with the re-use of the upload component as this is consistent UX. Is there anything we need also to think about except of the size of the upload section?

**Comment by miketaylr** [comment]
> I'd like to stick with the re-use of the upload component as this is consistent UX

If it's less tall, +1.

**Comment by zoepage** [comment]
merged #2283
