### ISSUE TITLE
Issue page flash of unstyled content

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat.com#2134]
STR: go to an issue page on staging.webcompat.com. that's it.

Before we attempted to fade everything in once content was ready, now it does this:

![fouc](https://user-images.githubusercontent.com/67283/36333434-8bb7ca04-133c-11e8-84a3-895fe59000d7.gif)

**Comment by zoepage** [comment]
This is the issue, we are talking about: https://staging.webcompat.com/issues/200

Just to make sure, I get this right. You are speaking about the jump, right?
