### ISSUE TITLE
Missing padding between "Upload screenshot" area and the "Report" buttons

### ISSUE THREAD

**Issue by softvision-oana-arbuzov** [webcompat/webcompat.com#2148]
URL: https://staging.webcompat.com 
Browser / Version: Firefox Nightly 60.0a1 (2018-02-18) (Mobile), Chrome 64.0.3282.137 (Mobile).
Operating System: Google Pixel (Android 8.0.0) - 1080 x 1920 pixels (~441 ppi pixel density)

**Steps to Reproduce:**
    1. Navigate to https://staging.webcompat.com
    2. Tap "Report bug" button.
    3. Scroll down the page until "Upload screenshot" area.
    4. Observe "Report" buttons layout.

**Expected Behavior:**
    Padding is available between the buttons and the "Upload screenshot" area.

**Actual Behavior:**
    No padding is available between the buttons and the "Upload screenshot" area.

**Note**
    1. Not reproducible on Desktop.
    2. Affected area:
```html
<div class="form-button form-element js-Form-group">
	<button class="button js-Button is-disabled" id="submitanon" name="submit-type" type="submit" value="github-proxy-report" disabled="">
        Report Anonymously
      </button>
	<button class="button button-primary right js-Button is-disabled" id="submitgithub" name="submit-type" type="submit" value="github-auth-report" disabled="">
        Report via GitHub
      </button>
</div>
```
        
**Watchers:**
@softvision-sergiulogigan
@softvision-oana-arbuzov

![screenshot-1519031717237](https://user-images.githubusercontent.com/12184325/36370465-9c1c6a44-1567-11e8-964e-875880aefdb1.jpg)

**Comment by softvision-oana-arbuzov** [comment]
Suggestion: Adding `padding-top` of 5px to
```css
.form-element-bottom .form-button {
    margin-top: auto;
}
```

![screenshot-1519032432067](https://user-images.githubusercontent.com/12184325/36370540-d60a5e00-1567-11e8-8532-2f3c29bf3c17.jpg)

**Comment by zoepage** [comment]
Related to #2081

**Comment by zoepage** [comment]
This will be fixed through #2101 -> #2200

**Comment by zoepage** [comment]
fixed through https://github.com/webcompat/webcompat.com/pull/2200#issue-172054001

**Comment by softvision-sergiulogigan** [comment]
This issue is also reproducible on Chrome (Desktop).
![image](https://user-images.githubusercontent.com/16573771/37085694-5c02083a-21fe-11e8-9776-9e6304be4f83.png)

**Comment by zoepage** [comment]
This issue was solved, but not deployed yet.
