### ISSUE TITLE
"Description required/A valid URL is required" multiply when deleting the input

### ISSUE THREAD

**Issue by softvision-oana-arbuzov** [webcompat/webcompat.com#2149]
URL: https://staging.webcompat.com 
Browser / Version: Firefox Nightly 60.0a1 (2018-02-18) (Mobile), Chrome 64.0.3282.137 (Mobile).
Operating System: Google Pixel (Android 8.0.0) - 1080 x 1920 pixels (~441 ppi pixel density)

**Steps to Reproduce:**
    1. Navigate to https://staging.webcompat.com
    2. Tap "Report bug" button.
    3. Type in the "Site URL".
    4. Delete the input.
    5. Observe error message after performing steps 3-4 a few times.  

**Expected Behavior:**
    Error message is displayed only once.

**Actual Behavior:**
     Error message multiples.

**Note**
    1. Also reproducible on Desktop.
    2. Also reproducible when deleting input form "Please describe what was wrong" field.
    3. Affected area:
```html
<div class="js-Form-information">
	<label class="form-label form-required" for="url">Site URL</label>
	<small class="label-icon-message">A valid URL is required.</small>
</div>
<!--not needed-->
<div class="js-Form-information">
	<label class="form-label form-required" for="description">Please describe what was wrong</label>
	<small class="label-icon-message">Description required.</small>
</div>
``` 
        
**Watchers:**
@softvision-sergiulogigan
@softvision-oana-arbuzov

![screenshot-1519032824661](https://user-images.githubusercontent.com/12184325/36370899-13aad054-1569-11e8-9365-cf3b3a0310e2.jpg)

**Comment by zoepage** [comment]
Uh, cool! A feature! :D
Related to #2074 && needs fixing.

**Comment by zoepage** [comment]
@softvision-oana-arbuzov 
Could you please test `refactor` as I can reproduce on staging, but not locally?
That would be great. Thank you!

**Comment by karlcow** [comment]
This is fixed!

@zoepage do you know what PR/commit has fixed it? so we can cross reference.

**Comment by zoepage** [comment]
Cool! :) Thanks for re-checking! :)
