### ISSUE TITLE
"You were successfully logged out." message overlaps the top actions bar buttons

### ISSUE THREAD

**Issue by softvision-oana-arbuzov** [webcompat/webcompat.com#2152]
URL: https://staging.webcompat.com/
Browser / Version: Firefox Nightly 60.0a1 (2018-02-16), Chrome 64.0.3282.167 
Operating System: Windows 10 Pro

Steps to Reproduce:
1. Navigate to https://staging.webcompat.com
2. Click "Login" button and sign in with valid credentials.
3. After sign is is performed successfully, click "Logout".
4. Observe message displayed.

Expected Behavior:
An overlay is displayed with the "You were successfully logged out." message. 

Actual Behavior:
"You were successfully logged out." message overlaps the top action bar button. 

Note
1. Affected area: 
```html
<div class="notification-bar js-flashmessage notification is-active" style="display: none;">You were successfully logged out.</div>
```

Watchers:
@softvision-sergiulogigan
@softvision-oana-arbuzov

![screenshot_4](https://user-images.githubusercontent.com/12184325/36374086-d5537630-1572-11e8-8b20-9671e27817e1.png)

**Comment by zoepage** [comment]
The background color is missing here, which would be added by the class `notification-info` 
.

**Comment by miketaylr** [comment]
This should be fixed now.
