### ISSUE TITLE
"Share on Twitter/"Share on Facebook" buttons should be available all the times for a reported issue

### ISSUE THREAD

**Issue by softvision-oana-arbuzov** [webcompat/webcompat.com#2157]
URL: https://staging.webcompat.com/
Browser / Version: Firefox Nightly Mobile 60.0a1 (2018-02-18), Firefox Nightly Desktop 60.0a1 (2018-02-16), Chrome Desktop 64.0.3282.167, Chrome Mobile 64.0.3282.137 
Operating System: Windows 10 Pro, Google Pixel (Android 8.0.0) - 1080 x 1920 pixels (~441 ppi pixel density)

**Steps to Reproduce:**
1. Navigate to https://staging.webcompat.com/
2. Tap "Report bug" button.
3. Type in all required information.
4. Tap "Report" button (anonymous of with the Github account).
5. After issue is logged successfully, observe displayed of "Share on Twitter/"Share on Facebook" buttons.

**Expected Behavior:**
"Share on Twitter/"Share on Facebook" buttons are displayed in the "Thanks" message and become available also after refreshing the screen (as a separate "Share" section).

**Actual Behavior:**
"Share on Twitter/"Share on Facebook" buttons are displayed in the "Thanks" message and are no longer available after refreshing the screen.

**Note**
1. "Thanks" message: 
```html
<div class="notification-bar js-flashmessage is-active notification-thanks">
	<h4>Thanks for reporting an issue!</h4>
	<p>You're helping us make the web a better place to work and play.</p>
	<p>Tell your friends about the bug you just filed:</p>
	<a class="wc-Button wc-Button--action" href="https://twitter.com/intent/tweet?text=I%20just%20filed%20a%20bug%20on%20the%20internet%3A&amp;url=https%3A%2F%2Fwebcompat.com%2Fissues%2F1376&amp;via=webcompat" target="_blank">Share on Twitter</a>
	<a class="wc-Button wc-Button--action" href="https://facebook.com/sharer/sharer.php?u=https%3A%2F%2Fwebcompat.com%2Fissues%2F1376" target="_blank">Share on Facebook</a>
</div>
```

Watchers:
@softvision-sergiulogigan
@softvision-oana-arbuzov

![screenshot-1519046105222](https://user-images.githubusercontent.com/12184325/36381088-2428624c-158d-11e8-843c-471f3f19c7f2.jpg)

**Comment by zoepage** [comment]
Those are the part of a thank you message, that still needs fixing.
