### ISSUE TITLE
Close button is not centered

### ISSUE THREAD

**Issue by softvision-sergiulogigan** [webcompat/webcompat.com#2159]
**Environment:**
Browser / Version: Chrome 64.0.3282.167 (Desktop), Firefox Nightly 60.0a1 (Desktop)
Operating System: Windows 10

**Steps to Reproduce:**
1. Go to https://staging.webcompat.com/
2. Click on the upper Search button.
3. Observe the Search bar's Close button.

**Expected Behavior:**
Close button is centered.

**Actual Behavior:**
Close button is not centered.

**Notes:**
1. Screen capture attached.

Watchers:
@softvision-sergiulogigan
@softvision-oana-arbuzov

sv;

![ff](https://user-images.githubusercontent.com/16573771/36382201-d06a5436-1590-11e8-80ff-f0d5c02cfcb9.png)

**Comment by zoepage** [comment]
dup #2098
