### ISSUE TITLE
Search bar's padding is inconsistent between FF and Chrome

### ISSUE THREAD

**Issue by softvision-sergiulogigan** [webcompat/webcompat.com#2160]
**Environment:**
Browser / Version: Chrome 64.0.3282.167 (Desktop), Firefox Nightly 60.0a1 (Desktop)
Operating System: Windows 10

**Steps to Reproduce:**
1. Go to https://staging.webcompat.com/
2. Click on the upper Search button.
3. Observe the Search bar's padding.

**Expected Behavior:**
The Search bar's padding is consistent between Chrome and Firefox.

**Actual Behavior:**
The Search bar's padding is not consistent between Chrome and Firefox.

**Notes:**
1. Screen capture attached.

Watchers:
@softvision-sergiulogigan
@softvision-oana-arbuzov

sv;

![chrome](https://user-images.githubusercontent.com/16573771/36382343-416f2a44-1591-11e8-93c8-5a4e3600eccf.png)
![ff](https://user-images.githubusercontent.com/16573771/36382345-418ff792-1591-11e8-9eeb-f13c4d1d9d82.png)

**Comment by zoepage** [comment]
Related to #2098

**Comment by Regaddi** [comment]
Is this still an issue? Can't see any differences (localhost) between Chrome and Firefox on my machine 🤔

**Comment by softvision-sergiulogigan** [comment]
@Regaddi looks like the issue has been fixed.

![image](https://user-images.githubusercontent.com/16573771/37815739-bf20745c-2e78-11e8-8d94-95146ee8c250.png)

**Comment by zoepage** [comment]
yaay! 🎉
