### ISSUE TITLE
Navigation bar incorrectly displayed when tapping the New Issue (Lightning) button

### ISSUE THREAD

**Issue by softvision-sergiulogigan** [webcompat/webcompat.com#2164]
**Environment:**
Browser / Version: Chrome 64.0.3282.137 (Mobile), Firefox Nightly 60.0a1 (Mobile)
Operating System: Android 7.0

**Steps to Reproduce:**
1. Go to https://staging.webcompat.com/
2. Tap the Contribute or All Issues button.
3. Tap the New Issue (Lightning) button.

**Expected Behavior:**
The Navigation bar is correctly displayed.

**Actual Behavior:**
The Navigation bar is thicker than normal, and it overlaps the page title. Also the containing buttons are arranged vertically.

**Notes:**
1. Screen capture attached.

Watchers:
@softvision-sergiulogigan
@softvision-oana-arbuzov

sv;

![screen capture](https://user-images.githubusercontent.com/16573771/36384237-4aa44922-1597-11e8-9aa0-d95e1d2326ab.gif)

**Comment by zoepage** [comment]
This is definitely a bug that needs to be fixed. Thanks!

**Comment by zoepage** [comment]
I closed without adding the comment :D SORRY!
This is a dup of #1966

**Comment by zoepage** [comment]
merged #2233
