### ISSUE TITLE
Write functional tests for browser label search suggestion

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat.com#2171]
The refactor broke this for a while, which exposed the fact we don't have tests for it:

https://github.com/webcompat/webcompat.com/pull/2168

STR and Expected behavior were more elegantly written by @softvision-oana-arbuzov in https://github.com/webcompat/webcompat.com/issues/2153#issue-298259452:

> **Steps to Reproduce:**
> 1. Navigate to https://staging.webcompat.com/issues?page=1&per_page=50&state=open&stage=all&sort=created&direction=desc
> 2. Tap the "Search" field and type in a string that returns no results (e.g. Testtesttest).
> 3. After error message is displayed, observe suggestions - popular labels (e.g. android/chrome/firefox/ie).
> 4. Tap one of the popular labels and observe behavior (e.g. chrome).

> **Expected Behavior:**
> Redirect to specific page is performed
> (e.g. https://webcompat.com/issues?page=1&per_page=50&state=open&stage=all&sort=created&direction=desc&q=label%3Abrowser-chrome).

**Comment by miketaylr** [comment]
This probably fits well as a new test in `tests/functional/search-auth.js`

**Comment by zoepage** [comment]
this was merged in #2191
