### ISSUE TITLE
Triage Dashboard layout is broken on Chrome

### ISSUE THREAD

**Issue by softvision-sergiulogigan** [webcompat/webcompat.com#2174]
**Environment:**
Browser / Version: Chrome 64 (Desktop), Firefox Nightly 60.0a1 (Desktop)
Operating System: Windows 10

**Steps to Reproduce:**
1. Go to https://webcompat.com/dashboard/triage
2. Observe the "Older than 48h" issue cards layout

**Expected Behavior:**
The cards are correctly arranged.

**Actual Behavior:**
The cards laypout is broken.

**Notes:**
1. Screen capture attached.
2. The issue is not reproducible on Firefox.

Watchers:
@softvision-sergiulogigan
@softvision-oana-arbuzov

sv;

![image](https://user-images.githubusercontent.com/16573771/36467205-634d357e-16e6-11e8-82c7-378a261ab111.png)

**Comment by softvision-sergiulogigan** [comment]
Ping @magsout and @karlcow for this one.

**Comment by magsout** [comment]
thanks @softvision-sergiulogigan

**Comment by magsout** [comment]
I'm not able to reproduce this issue:

![capture d ecran 2018-02-21 a 18 41 48](https://user-images.githubusercontent.com/1997108/36495911-0019735e-1737-11e8-98fa-cff3dfa2505c.png)

@karlcow do you?

**Comment by zoepage** [comment]
Can't reproduce either. 🤔

**Comment by karlcow** [comment]
not enough issue to reproduce currently.

**Comment by magsout** [comment]
@zoeoage thanks

@karcow I tried locally because yeah you work too fast so not enought issues ;)

**Comment by softvision-sergiulogigan** [comment]
well, well, well!

Broken:
![image](https://user-images.githubusercontent.com/16573771/36525918-cae1d298-17b4-11e8-9da2-e1d6841c7a06.png)

Unbroken, on a fresh new Chrome profile:
![image](https://user-images.githubusercontent.com/16573771/36525937-d768d7d2-17b4-11e8-89e6-279e60bd01de.png)

I have a few add-ons, but none related to how a webpage is rendered (apart from uBlock Origin). However, disabling uBlok, doesn't change anything.

**Comment by softvision-sergiulogigan** [comment]
Clearing cookies and a bunch of other stuff, solved the issue.

**Comment by magsout** [comment]
@softvision-sergiulogigan ok cool, thanks ;)
