### ISSUE TITLE
Unable to use "Back" button after clicking between labels

### ISSUE THREAD

**Issue by softvision-oana-arbuzov** [webcompat/webcompat.com#2175]
URL: https://staging.webcompat.com/issues?page=1&per_page=50&state=open&stage=needsdiagnosis&sort=created&direction=desc
Browser / Version: Firefox Nightly 60.0a1 (2018-02-20) (Mobile&Desktop), Chrome 64.0.3282.137 (Mobile), Chrome 64.0.3282.167 (Desktop).
Operating System: Window 10 Pro, Google Pixel (Android 8.0.0) - 1080 x 1920 pixels (~441 ppi pixel density)

**Steps to Reproduce:**
    1. Navigate to https://staging.webcompat.com/issues?page=1&per_page=50&state=open&stage=needsdiagnosis&sort=created&direction=desc
    2. Click a few labels (e.g "chrome", "critical", "type-stylo").
    3. Click the browser "Back" button.
    4. Observe behavior.

**Expected Behavior:**
     Redirect to previous label is performed (e.g "critical" ).

**Actual Behavior:**
     Nothing happens, redirect to previous label is not performed.

**Note**
    1. Also Reproducible on Mobile.
        
**Watchers:**
@softvision-sergiulogigan
@softvision-oana-arbuzov

![backbtnnotworking_labelchange](https://user-images.githubusercontent.com/12184325/36471358-d680f98a-16f6-11e8-956c-f08fe5674cb9.gif)

**Comment by zoepage** [comment]
This is an old bug we never fixed? #793

**Comment by zoepage** [comment]
closing as duplicate.
