### ISSUE TITLE
remove leftover `&` from .travis.yml

### ISSUE THREAD

**Issue by zoepage** [webcompat/webcompat.com#2184]
Looks like there is a leftover character (= `&`) in the travis config:
https://github.com/webcompat/webcompat.com/blob/refactor/.travis.yml#L46

We should remove it.

**Comment by amitsin6h** [comment]
@zoepage do we need to remove (&) character from config. Let me take this also

**Comment by zoepage** [comment]
@amitsin6h happy to assign it to you after the fixed PR. :)

**Comment by amitsin6h** [comment]
@zoepage can I take this now.

**Comment by zoepage** [comment]
Yes :)

**Comment by amitsin6h** [comment]
@zoepage I just want to know that do I need to make separate folder to clone `refactor` branch or I can do it with `master`

**Comment by zoepage** [comment]
@amitsin6h 
You can pull refactor and make a branch out of this.
You need to run following for this:

```
$ git checkout refactor
$ git pull origin refactor
$ git checkout -b issues/2184
```

Then you can make the changes.

**Comment by miketaylr** [comment]
> Looks like there is a leftover character (= &) in the travis config:

This isn't a typo, it's redirecting output to a subshell.

See https://superuser.com/questions/358491/what-does-the-mean-when-used-in-the-end-of-a-bash-script

**Comment by amitsin6h** [comment]
@miketaylr :+1:

**Comment by amitsin6h** [comment]
@miketaylr we can close this issue then

**Comment by miketaylr** [comment]
Sounds good, thanks @amitsin6h!
