### ISSUE TITLE
CSP blocking sourcesanspro font.

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat.com#2195]
(I looked for a dupe, forgive me if it already exists!)

At the following URL, https://staging.webcompat.com/issues?page=1&per_page=50&state=open&stage=all&sort=created&direction=desc&q=testetsts

`Content Security Policy: The page’s settings blocked the loading of a resource at https://fonts.gstatic.com/s/sourcesanspro/v11/6xK3dSBYKcSV-LCoeQqfX1RYOo3qOK7lujVj9w.woff2 (“font-src”).`

Our current `font-src` policy is:

`"font-src 'self' https://fonts.gstatic.com/s/opensans/; "`

@zoepage should we just whitelist `https://fonts.gstatic.com` instead?

**Comment by miketaylr** [comment]
We use the following font-stack at least in reset-add.css: `font-family: "Source Sans Pro", "Open Sans", sans-serif;`.

**Comment by zoepage** [comment]
merged #2207
