### ISSUE TITLE
Remove hardcoded instances of "http://localhost:5000/" from functional tests

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat.com#2198]
They should instead pull that in from intern `siteRoot` config property.

**Comment by Kagamihime** [comment]
@miketaylr I’d like to work on this for my outreachy contribution :)

**Comment by miketaylr** [comment]
Great, thank you!

**Comment by miketaylr** [comment]
Let me know if you run into any problems getting the functional tests running: 

https://github.com/webcompat/webcompat.com/blob/refactor/docs/tests.md

Once this bug is finished, it should be possible for tests to pass from the following 2 commands:

`npm run test:js -- --siteRoot=http://127.0.0.1:5000/` & 
`npm run test:js`

One more thing: if might be simpler for you to work off the `refactor` branch, but it's possible from `master` as well -- but the above commands will be slightly different.

**Comment by miketaylr** [comment]
I think there's only one instance left: https://github.com/webcompat/webcompat.com/blob/0d260f567f7f34a938d1edfa9f4224cae2b813c0/tests/functional/lib/window-helpers.js#L35
