### ISSUE TITLE
"Non-Compat" milestone tag seems to have a due date

### ISSUE THREAD

**Issue by reinhart1010** [webcompat/webcompat.com#2206]
Link: https://github.com/webcompat/web-bugs/milestone/1

The "Non-Compat" milestone tag seems to have a due date of January 16, 2032, unlike others (such as invalid and sitewait) which do not have. This might be a human error.

**Comment by miketaylr** [comment]
Oh that's... interesting. :)

Thanks @reinhart1010 I just removed it.
