### ISSUE TITLE
Screenhots are not displayed

### ISSUE THREAD

**Issue by softvision-sergiulogigan** [webcompat/webcompat.com#2216]
Environment:
Windows 10, Nightly 60, Chrome 64.

STR:
1. Navigate to https://staging.webcompat.com/contributors/site-outreach
2. Scroll to the "SlideShare" section.
3. Observe the "Slideshare Interface" and "Dribble Interface" screenshots.

Expected Results:
The Screenshots are displayed.

Actual Results:
The Screenshots are not displayed. Only the description is visible.

Note:
On Chrome, a Broken Image placeholder is displayed.

![image](https://user-images.githubusercontent.com/16573771/37090575-908f7a92-220d-11e8-983d-14e36f0985ff.png)

![image](https://user-images.githubusercontent.com/16573771/37090890-cb8ce3a4-220e-11e8-9585-49048f186e01.png)

**Comment by Regaddi** [comment]
The images are not even available in the source code. Maybe they've been missed be added to a commit? @zoepage

**Comment by karlcow** [comment]
See https://webcompat.com/contributors

Current: https://github.com/webcompat/webcompat.com/tree/v8.1.0/webcompat/static/img
Refactor: https://github.com/webcompat/webcompat.com/tree/af05c8a0259ac0af6b81aa530d7606e8e568eb7f/webcompat/static/img

They will be probably added when it will be time.

**Comment by zoepage** [comment]
merged #2328
