### ISSUE TITLE
A message is displayed when using the Chrome bug reports link

### ISSUE THREAD

**Issue by softvision-sergiulogigan** [webcompat/webcompat.com#2217]
Environment:
Windows 10, Nightly 60, Chrome 64.

STR
1. Navigate to https://staging.webcompat.com/contributors/site-outreach
2. Click the "Chrome bug reports" link.

Expected results:
The Chrome bug reports interface is opened.

Actual results:
A message is displayed for 2 seconds, thenthe Chrome bug reports interface is opened.

![image](https://user-images.githubusercontent.com/16573771/37091014-4faa7566-220f-11e8-80ad-31278596cf8c.png)

**Comment by miketaylr** [comment]
@softvision-sergiulogigan does this still reproduce for you? It did for me once,but now I just get a blank page for a second, then the chrome bug report page loads. Possibly a server change on their side?

**Comment by softvision-sergiulogigan** [comment]
I'm getting this, @miketaylr 
![screen capture](https://user-images.githubusercontent.com/16573771/38127038-f6961818-33fc-11e8-9622-ad1c3618480d.gif)

On the first attempt, the message is displayed for a second or so, then the Chrome bug report page opens.
On the second attempt, the message is no longer displayed.

The same behavior can be observed on both Chrome and Nightly 61.

**Comment by Regaddi** [comment]
I guess we can't change that. We link to a short URL (crbug.com/new) which redirects to the actual bug report page (bugs.chromium.org/p/chromium/issues/entry?...). There are some prefilled parameters e.g. the user agent string, which I assume has been read out by the page shown before.

**Comment by miketaylr** [comment]
Yeah, I think this is just a Google server setup. If it repros in Chrome, especially. Let's go ahead and close here.
