### ISSUE TITLE
"Download our Chrome Extension" – Text wraps below icon

### ISSUE THREAD

**Issue by Regaddi** [webcompat/webcompat.com#2224]
**Description:**
In smaller viewports, when the header bar has not enough space, the text "Download our Chrome Extension" is wrapped below the download icon.

**Browser:**
Chrome Version 65.0.3325.146
macOS High Sierra 10.13.3

**Suggested fix:**
Add `white-space: nowrap;` to the element `nav-link js-addon-link`.

**Additional comment:**
If you don't mind, I'll submit a PR in a minute to fix this.

**Screenshot:**
![image](https://user-images.githubusercontent.com/1336590/37326688-8c7be168-2693-11e8-853d-503757a6b8cd.png)

**Watchers:**
@zoepage

**Comment by Regaddi** [comment]
Nevertheless, when the user is not logged in, a link drops to the next line on 665px viewport width:

![image](https://user-images.githubusercontent.com/1336590/37333023-8a98ae16-26a8-11e8-81a9-ddbfbf443591.png)

Also on Firefox:

![image](https://user-images.githubusercontent.com/1336590/37333044-9fe2bae6-26a8-11e8-9da6-e33c68ff2cce.png)

**Comment by zoepage** [comment]
This is probably related to #2164

**Comment by zoepage** [comment]
merged #2233
