### ISSUE TITLE
Take Screenshots for contribute section

### ISSUE THREAD

**Issue by karlcow** [webcompat/webcompat.com#2227]
This is a followup on the https://github.com/webcompat/webcompat.com/issues/1933#issuecomment-357665444 
> @zoepage we can't make images until the design is finished. This seems to be the last part.

and the webcompat meeting we had today, where I committed myself to do do it.

@zoepage Do you feel confident that we can make the screenshots for all sections? 
Or I just go ahead and do it and we fix later?

Do you want the images inside the git repo? I don't know if we have a policy for this. I think some developers don't want images in versioning system, some don't care. I do not have an opinion.

**Comment by zoepage** [comment]
This is a duplicate of #2216. Closing in favor as I already assigned myself to it.

Thanks @karlcow
