### ISSUE TITLE
Improve documentation for OAuth development setup

### ISSUE THREAD

**Issue by Regaddi** [webcompat/webcompat.com#2228]
[The current documentation for local deveopment setup](https://github.com/webcompat/webcompat.com/blob/master/docs/dev-env-setup.md#configuring-the-server) is missing some detailed instructions, when you're not part of the webcompat Github organization and need to configure an OAuth Client ID & Secret.

I'd suggest to add some deeplinks and a quick guide to setup your own OAuth application.

Something like:

> 1. Open https://github.com/settings/applications/new
> 2. http://localhost:5000 and http://localhost:5000/callback
> 3. Save and go to https://github.com/settings/developers
> 4. Click on your just created application
> 5. You'll see your freshly generated Client ID and Secret

**Comment by karlcow** [comment]
@shristit see https://github.com/webcompat/webcompat.com/issues/2468#issuecomment-423526484

**Comment by laghee** [comment]
Fixed by PR #2652
