### ISSUE TITLE
Normalize naming of npm scripts

### ISSUE THREAD

**Issue by zoepage** [webcompat/webcompat.com#2230]
In our `package.json` we have different scripts,  e.g. for linting JS or testing. The writing is different (capital letters, small letters...) This is really confusing as I run into that issue all the time. 😅

My suggestion: we should go with small letters all the way.

Here are the lines that need to be changed:
https://github.com/webcompat/webcompat.com/blob/master/package.json#L59-L60
https://github.com/webcompat/webcompat.com/blob/master/package.json#L62
https://github.com/webcompat/webcompat.com/blob/master/package.json#L78

`JS` -> `js`

Thanks! :)

**Comment by mpaarating** [comment]
I got this :D

**Comment by zoepage** [comment]
merged #2243
