### ISSUE TITLE
a11y audit for site

### ISSUE THREAD

**Issue by zoepage** [webcompat/webcompat.com#2231]
We'd like to check how accessible the site is and what we can do to improve this.
You can use https://sonarwhal.com/ to check for those issues.

**Comment by Regaddi** [comment]
Here's a first report: https://sonarwhal.com/scanner/ce319f12-d3c3-4ca0-9687-ab71cb002957

**Comment by zoepage** [comment]
Updated the report for staging:
https://sonarwhal.com/scanner/d6db505b-eafd-4b8c-816f-6378bb690835

**Comment by miketaylr** [comment]
These reports are all dead. 👻
