### ISSUE TITLE
Empty search submit shows "undefined" in search bar

### ISSUE THREAD

**Issue by Regaddi** [webcompat/webcompat.com#2234]
**Steps to reproduce:**

1.  Go to https://staging.webcompat.com
2. Click on "Search"
3. Leave input empty and hit enter
4. Searchbar on issue navigator contains "undefined"

<img width="973" alt="bildschirmfoto 2018-03-14 um 14 08 04" src="https://user-images.githubusercontent.com/1336590/37404110-2825941c-2791-11e8-97b3-b2d80474e5ec.png">

**Comment by zoepage** [comment]
YES! You could reproduce! Nice :D
(I ran into that issue, but could not reproduce.)

**Comment by zoepage** [comment]
didn't we fix this a few days ago? 🤔
yes, with #2237
