### ISSUE TITLE
Label Box header in /issues on mobile

### ISSUE THREAD

**Issue by zoepage** [webcompat/webcompat.com#2244]
The header of the label box needs to be visible above the issue on mobile.

Expected:
https://webcompat.com/issues/16036

Actual:
Header stays visible above the label box that jumps below the issue content and comments.

@magsout would this be something you'd be interested in working on?

**Comment by magsout** [comment]
@zoepage On mobil we want to have

`label box`
`Issue informations`
`comments`
`form comment`

correct?

**Comment by zoepage** [comment]
:)

<img width="582" alt="screen shot 2018-03-16 at 9 59 45 pm" src="https://user-images.githubusercontent.com/562354/37544479-69655cb6-2965-11e8-9503-900366a91405.png">

We also need to make sure the drop downs also are in the right place I guess?

**Comment by magsout** [comment]
merged #2253
