### ISSUE TITLE
Issue detail page grid off

### ISSUE THREAD

**Issue by Regaddi** [webcompat/webcompat.com#2247]
The issue detail page got a little bit off after solving #2245.

![image](https://user-images.githubusercontent.com/1336590/37539139-3527bb0e-2953-11e8-9c0e-9b627d573c08.png)

I'd suggest the following layout as a fix (got everything ready locally):

![image](https://user-images.githubusercontent.com/1336590/37539204-6b172330-2953-11e8-92a9-f894d7fb6255.png)

@zoepage ?

**Comment by zoepage** [comment]
@Regaddi  +1

**Comment by zoepage** [comment]
merged #2251

**Comment by zoepage** [comment]
Comments and Uploads are missing a `grid-nested` class. Just as a quick addition.
