### ISSUE TITLE
Top navbar jump when logging in / out

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat.com#2248]
Unsure if this already exists, but I bet @zoepage would know!

STR:

1. go to staging.webcompat.com
2. log in
3. observe shift in top bar height
4. log out
5. observe shift back

![jump](https://user-images.githubusercontent.com/67283/37539283-55b6db8e-2921-11e8-86ce-9d686c2c6cff.gif)

**Comment by zoepage** [comment]
merged in #2249

**Comment by miketaylr** [comment]
awesome.
