### ISSUE TITLE
The strings in the Navigation Bar are blurred, on Chrome

### ISSUE THREAD

**Issue by softvision-sergiulogigan** [webcompat/webcompat.com#2258]
Browser / Version: Chrome  65.0.3325.162 (Desktop)
Operating System: Windows 10

**Steps to Reproduce:**
1. Go to https://staging.webcompat.com/
2. Observe the Navigation Bar.

**Expected Behavior:**
The text is correctly displayed.

**Actual Behavior:**
The text is blurred.

**Notes:**
1. Screen capture attached.
2. The issue is not reproducible on Nightly 61.

Watchers:
@softvision-sergiulogigan
@softvision-oana-arbuzov

sv;

![image](https://user-images.githubusercontent.com/16573771/37583872-f25ac1c6-2b5b-11e8-8e5d-9f1b7e023fe1.png)

**Comment by zoepage** [comment]
Hm, WFM. 🤔

**Comment by softvision-sergiulogigan** [comment]
@zoepage This is how I see them, on the same monitor:

Above - Chrome, below - Nightly 61.
![image](https://user-images.githubusercontent.com/16573771/37598155-21621aa4-2b8a-11e8-9d02-d4b68a732a24.png)

**Comment by miketaylr** [comment]
Text is blurry for me in Chrome and Safari. 

![screen shot 2018-03-19 at 2 30 53 pm](https://user-images.githubusercontent.com/67283/37617814-2c2fcf74-2b82-11e8-9516-da5a1188ab48.png)

**Comment by miketaylr** [comment]
Note: it's only blurry on a low-DPI external monitor for me, so not on a retina device.

**Comment by zoepage** [comment]
merged #2263

**Comment by softvision-sergiulogigan** [comment]
Tested again, and observed that this issue is still reproducible on Chrome 65, but ONLY on https://staging.webcompat.com/. All other pages display the un-blurred text.

**Comment by zoepage** [comment]
ping @Regaddi :)

**Comment by softvision-sergiulogigan** [comment]
This issue is also reproducible on Ubuntu 16.04, on Chrome.

**Comment by zoepage** [comment]
merged #2315
