### ISSUE TITLE
labels colors don't update correctly

### ISSUE THREAD

**Issue by zoepage** [webcompat/webcompat.com#2262]
I found 2 issues, I guess related.

1. When I select labels they are added, but not saved. So they disappear on reload and the old state is been reset.

2. After selecting the labels, the color disappears (just in Chrome). Here not the right class is applied like e.g. `browser-chrome`, but a color `browser-ededed`.

![chrome_labels](https://user-images.githubusercontent.com/562354/37624635-15674046-2bc9-11e8-91f4-51318a96ffbe.gif)

@miketaylr You have any idea?

**Comment by miketaylr** [comment]
Good find @zoepage. Let's see what's up...

**Comment by miketaylr** [comment]
(also just noticed the milestone editor says Filter Labels, let's fix that here too).

![screen shot 2018-03-20 at 3 59 33 pm](https://user-images.githubusercontent.com/67283/37682490-b65153f0-2c57-11e8-986a-0fad390ceb94.png)

**Comment by miketaylr** [comment]
Here's the bug:

https://github.com/webcompat/webcompat.com/blame/refactor/webcompat/templates/issue/issue-labels-sub.jst#L3

**Comment by zoepage** [comment]
merged #2273
