### ISSUE TITLE
Unable to start the Local Server on Windows 10

### ISSUE THREAD

**Issue by softvision-oana-arbuzov** [webcompat/webcompat.com#2267]
**Environment:**
Operating System: Windows 10 Pro

**Steps to Reproduce**
    1. Followed the information from [Development Environment setup](https://github.com/webcompat/webcompat.com/blob/master/docs/dev-env-setup.md#installing-virtualenv) guide.
    2. Tried to start local server http://localhost:5000/, using `npm run start` or `python run.py`.

**Expected Behavior:**
Local sever is started and Webcompat.com page is displayed.

**Actual Behavior:**
Local sever is not started and errors are revived in the console.

**Note:**
1. Not reproducible on Linux Ubuntu 16.04.
2. Attached screenshot with installed versions of programs (python, node, npm, virtualenv).
![screenshot_1](https://user-images.githubusercontent.com/12184325/37659358-6ae7e658-2c58-11e8-99c4-c13072249509.png)
3. `secrets.py` file contains the correct information:
```py
# Staging and Local instances use the same test repo
else:
    ISSUES_REPO_URI = os.environ.get('ISSUES_REPO_URI') or 'webcompat/webcompat-tests/issues'
```
Added the correct Cliend ID and Client Secret [(instructions here)](https://github.com/settings/applications/new) to:
```py
else:
    # We're running on localhost, use the test application
    GITHUB_CLIENT_ID = os.environ.get('FAKE_ID') or '  '
    GITHUB_CLIENT_SECRET = os.environ.get('FAKE_SECRET') or '  '
    GITHUB_CALLBACK_URL = 'http://localhost:5000/callback'
```
Added the correct OAUTH_TOKEN [(instructions here)](https://help.github.com/articles/creating-a-personal-access-token-for-the-command-line/) to:
```py
OAUTH_TOKEN = os.environ.get('OAUTH_TOKEN') or '  '  # nopep8
```

4. 
# Start local server using `npm run start`
Error:
```js
> webcompat@ start D:\Arbuzov Oana My Docs\Mozilla\WebcompatRepository\webcompat.com
> source env/bin/activate || . env/bin/activate && python run.py

'source' is not recognized as an internal or external command,
operable program or batch file.
'.' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! webcompat@ start: `source env/bin/activate || . env/bin/activate && python run.py`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the webcompat@ start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\oana.arbuzov\AppData\Roaming\npm-cache\_logs\2018-03-20T13_43_56_404Z-debug.log
```
Attached error log.

# Start local server using `python run.py`
Error:
```js
Statuses Initialization…
Fetching milestones from Github…
It failed with 404 Client Error: Not Found for url: https://api.github.com/repos%5Cwebcompat/webcompat-tests%5Cmilestones!
We will read from data/milestones.json.

Oooops.
We can't find D:\Arbuzov Oana My Docs\Mozilla\WebcompatRepository\webcompat.com\data\milestones.json
Double check that everything is configured properly
in config/secrets.py and try again. Good luck!

Milestones are not initialized.
```
[2018-03-20T13_43_56_404Z-debug.log](https://github.com/webcompat/webcompat.com/files/1829553/2018-03-20T13_43_56_404Z-debug.log)

Watchers:
@softvision-sergiulogigan
@softvision-oana-arbuzov

**Comment by miketaylr** [comment]
> 'source' is not recognized as an internal or external command,

Ah, yeah. This is a unix-ism.

https://en.wikipedia.org/wiki/Source_(command)

I bet there are cross-platform ways we can do this.

**Comment by softvision-oana-arbuzov** [comment]
After further investigations we found the bellow results that are applicable for Windows:
- "Git" app needs to be installed on Windows (to have GitBash);
- `python v.2.7 and v.3.6` need to be installed in order to have pip1 and pip2;
- virtualenv can be activated with `env/Script/activate` or `.env/Script/activate`;
![image](https://user-images.githubusercontent.com/12184325/41525245-fc0806b4-72e8-11e8-8589-45565ee10da1.png)
![image](https://user-images.githubusercontent.com/12184325/41525213-e0e39df8-72e8-11e8-9139-94dd0451bc53.png)

- `/` is encoded with `%5C` in `webcompat/webcompat-tests/issues` (secrets.py file) when trying to start the server;
![image](https://user-images.githubusercontent.com/12184325/41525230-f10ef1aa-72e8-11e8-8f46-699127e4fcc7.png)

- "tmp" from Linux/Mac folder in `__init__.py` file from `Config` folder (`C:\\tmp\\webcompat.log`) is "temp" folder on Windows;
![image](https://user-images.githubusercontent.com/12184325/41525196-d1e1e684-72e8-11e8-97f0-b2a3d8210a9a.png)

**Comment by softvision-oana-arbuzov** [comment]
Logged issues on:
> `/` is encoded with `%5C` in `webcompat/webcompat-tests/issues` (secrets.py file) when trying to start the server; => #2497  
> update documentation for dependencies on Windows  => #2498

**Comment by miketaylr** [comment]
> "Git" app needs to be installed on Windows (to have GitBash);

I think we should just support and document running the app on Windows 10+ using Ubuntu. It should be possible to get it going via other distros or GitBash, but let's just pick Ubuntu:

https://docs.microsoft.com/en-us/windows/wsl/install-win10

**Comment by miketaylr** [comment]
> python v.2.7 and v.3.6 need to be installed in order to have pip1 and pip2;

We also don't want to recommend installing multiple pythons -- it should be possible to get it running with only python27. (We'll recommend python3 when we port everything over).

**Comment by karlcow** [comment]
>  python v.2.7 and v.3.6 need to be installed in order to have pip1 and pip2;

just for the sake of clarity. python2.7 is the only one necessary and install pip (or pip2) depending on your install. The issue was for people who had already a python3 install with pip as an alias of pip3.
