### ISSUE TITLE
Scrolling overflow chops off milestones editor 

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat.com#2274]
![overflow-weird](https://user-images.githubusercontent.com/67283/37689067-0778f40e-2c71-11e8-8902-03b63941ea18.gif)

STR: go to staging, log in, go to an issue and open the status editor.

On desktop at least everything is chopped off unless you scroll.

**Comment by karlcow** [comment]
Ah I was about to report the same thing.

<img width="346" alt="capture d ecran 2018-03-21 a 09 40 10" src="https://user-images.githubusercontent.com/505230/37690084-31b51dc6-2cec-11e8-8871-54d637cdac06.png">

I had the same issue. At first click it is weird because it seems there is only one milestones

**Comment by miketaylr** [comment]
> I had the same issue. At first click it is weird because it seems there is only one milestones

Yeah, I thought I had broken the milestones. :)

**Comment by miketaylr** [comment]
@zoepage P0?

**Comment by zoepage** [comment]
I've added it as P1 to the list already.

**Comment by miketaylr** [comment]
This is fixed now, but I'm not super happy with the solution, so let's keep this open. After some experience with the new site, let's revisit.

**Comment by miketaylr** [comment]
This looks pretty bad in Windows.
![overflow](https://user-images.githubusercontent.com/67283/38005549-bd2538ae-3206-11e8-9386-773a0b26e6c3.gif)

**Comment by zoepage** [comment]
@Regaddi @magsout 
Ideas?

**Comment by Regaddi** [comment]
I think we should move the label-editor from "inline" to something more like a pop-out-box. So scrolling is not affected in any way. Just like Github does, maybe?

![image](https://user-images.githubusercontent.com/1336590/38018086-3702d2ae-3274-11e8-9ca1-9b55a25d5754.png)

**Comment by zoepage** [comment]
I second that idea. :)
