### ISSUE TITLE
Add None default argument value for authorized method in views.py

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat.com#2280]
To fix this bug, we should add a default value of `None` to the `access_token` argument:

`def authorized(access_token=None)`

https://github.com/webcompat/webcompat.com/blob/7cc40a31b33b6ca565e6872dc9f57dd2e4a2e4e1/webcompat/views.py#L108

**Comment by karlcow** [comment]
@miketaylr Could you give more context? How does the bug manifest? In which circumstances? `authorized()` seems to be called only once in `views.py`

**Comment by miketaylr** [comment]
> Could you give more context? How does the bug manifest? In which circumstances?

It doesn't manifest (that we know of).

https://github.com/webcompat/webcompat.com/blob/7cc40a31b33b6ca565e6872dc9f57dd2e4a2e4e1/webcompat/views.py#L86 is the only instance where it is called directly. Otherwise, it's called as the `@github.authorized_handler` when GitHub OAuth returns.

We handle `None` in the code, but don't handle other invalid situations, so I think it would be good to just make the default arg be `None`.

**Comment by karlcow** [comment]
Thanks! understood now.
