### ISSUE TITLE
Image error overflows out of container

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat.com#2281]
STR:

In Safari, go to staging.webcompat.com and select a non-image file (like a .txt file) for the screenshot upload.

![screen shot 2018-03-21 at 5 07 13 pm](https://user-images.githubusercontent.com/67283/37740088-72ba50dc-2d2a-11e8-9b10-40b5be29edc1.png)

(this doesn't seem like a release blocker, perhaps P2?)

If I remove the explicit width from `.form-upload .label-icon`, it fits. 

![screen shot 2018-03-21 at 5 09 40 pm](https://user-images.githubusercontent.com/67283/37740143-aaac7ae2-2d2a-11e8-816c-a19fa2e5fb9a.png)

**Comment by zoepage** [comment]
Added as P2 to the list

**Comment by zoepage** [comment]
merged #2291
