### ISSUE TITLE
Question: Twitter & Github brand guidelines

### ISSUE THREAD

**Issue by Regaddi** [webcompat/webcompat.com#2289]
I've just stumbled across the twitter SVG included at the bottom of the page.

Is this compliant with the Twitter brand guidelines?

https://about.twitter.com/en_gb/company/brand-resources.html

![image](https://user-images.githubusercontent.com/1336590/37784018-31ec6040-2df7-11e8-958c-1cc634e28a0c.png)

Same applies for the Github logo:

https://github.com/logos

![image](https://user-images.githubusercontent.com/1336590/37784213-865d614c-2df7-11e8-955e-a8e7db90b30e.png)

**Comment by miketaylr** [comment]
Probably not, at least for GitHub. The Twitter one is less clear, but I think in spirit they want people to use their official assets.

> https://github.com/logos

> Please don’t do these things
>  Create a modified version of the Octocat or GitHub logo

**Comment by zoepage** [comment]
From a designer perspective, I'd say that the twitter logo is a gray zone and our version still in the scope of what is okay as the form did not change.

> Create a modified version of the Octocat or GitHub logo

This is design speak for changing the logo / form, adding elements etc. The version we have should be just a "reduced" version. :)

**Comment by miketaylr** [comment]
SGTM.
