### ISSUE TITLE
Investigate lost commits after rebasing refactor branch

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat.com#2296]
@zoepage said the current refactor branch (which is on staging) is missing commits, or had some bad rebase side effects.

Ola, can you point us to what is wrong, so we can document it here?

**Comment by miketaylr** [comment]
> <ola> oklay, staging is broken. so please don't check :D I'll fix it up and send a PR so we can deploy on monday. :)
> <ola> It contains merge conflicts

Current refactor doesn't contain any instances of `<<<<`, etc. so I think @zoepage is referring to something else, possibly the wrong commit was merged in during rebase.

**Comment by miketaylr** [comment]
Here's one instance where we have double content now:

https://github.com/webcompat/webcompat.com/blob/refactor/tests/unit/test_urls.py#L95

**Comment by zoepage** [comment]
@miketaylr we can close this, right?

**Comment by zoepage** [comment]
merged #2297
