### ISSUE TITLE
Remove screenshot hover activation possibly misleading

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat.com#2301]
STR:

1. go to staging.webcompat.com/issues/new
2. upload an image
3. hover over the edge of the image and note "Remove screenshot" turning yellow
4. click

Expected: it gets removed
Actual: it only gets removed if you click the `.js-remove-upload` div.

My brain assumed that since the color changed, it was an active clickable area. Should we make the entire preview be the click target?

**Comment by zoepage** [comment]
Oh, looks like a leftover from the rebase.

> Should we make the entire preview be the click target?

This is how it should be, yes.
