### ISSUE TITLE
Make login + view issue + shortcut hints less prominent

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat.com#2303]
On the issues page I think we should find a way to make the following info a bit less prominent. Possibly smaller text, or combine the login + view issue into a single line. It might also look nice inside of a white box, rather than all floating in the bg color.

![screen shot 2018-03-27 at 9 26 20 pm](https://user-images.githubusercontent.com/67283/38005234-8fb10156-3205-11e8-9c14-9a0ea43aab20.png)

**Comment by miketaylr** [comment]
I just noticed this little box when you file an issue, seems maybe like we could do something similar.
![screen shot 2018-03-27 at 9 30 46 pm](https://user-images.githubusercontent.com/67283/38005429-2ff77280-3206-11e8-9eab-f27f5c515f33.png) (or not, but I like how it's not very prominent)

**Comment by zoepage** [comment]
> I just noticed this little resources area when you file an issue, seems maybe like we could do something similar.

So, you mean we should place it underneath the label box? This might be an issue as we still do not have a good solution for small resolutions and the scrolling (when having many labels).

But a white box should be a great start! :)

**Comment by miketaylr** [comment]
> So, you mean we should place it underneath the label box?

Nah, not really. I think where it is is good, just could use a little styling love... smaller text in a white box would probably do it.

**Comment by miketaylr** [comment]
Looks like we forgot to close this.
