### ISSUE TITLE
Attachment doesn't keep aspect ratio

### ISSUE THREAD

**Issue by softvision-sergiulogigan** [webcompat/webcompat.com#2308]
**Environment:**
Browser / Version: Chrome 65.0.3325.181 (Desktop), Firefox Nightly 61.0a1 (Desktop)
Operating System: Windows 10

**Steps to Reproduce:**
1. Go to https://staging.webcompat.com/issues/new
2. Fill in all the text fields.
3. Attach a Mobile Device screenshot.
4. Submit the issue.

**Expected Behavior:**
The screenshot is correctly displayed.

**Actual Behavior:**
The screenshot has not kept its aspect ratio.

**Notes:**
1. Screen capture attached.
2. Reproducible both on Chrome and Firefox.
3. On GitHub, the attachment is correctly displayed.

Watchers:
@softvision-sergiulogigan
@softvision-oana-arbuzov

sv;

![image](https://user-images.githubusercontent.com/16573771/38019262-cd04d9cc-327f-11e8-987c-62fae4dc716c.png)

**Comment by Regaddi** [comment]
There's a `max-height` set on images inside the issue.

https://github.com/webcompat/webcompat.com/blob/refactor/webcompat/static/css/src/issue.css#L98

This should possibly be removed to prevent the squeezing of the image.
