### ISSUE TITLE
Remove PurifyCSS

### ISSUE THREAD

**Issue by zoepage** [webcompat/webcompat.com#2331]
In #2306, we added https://www.npmjs.com/package/grunt-purifycss to check for unused CSS.

We added the grunt task as well a npm script that can be called with `npm run clean:css`.
It will generate a `tmp/` folder with the reduced css (Just used CSS). It also shows which classes are not used thanks to the `rejected` option and can minify the CSS.

This is how the log looks like:
<img width="931" alt="screen shot 2018-03-28 at 8 37 14 pm" src="https://user-images.githubusercontent.com/562354/38049341-4420797e-32c8-11e8-8bd5-4870738a9ba1.png">

The question now is... Do we want to replace https://www.npmjs.com/package/grunt-contrib-cssmin and use the generated and reduced CSS file and move it to our `dist` folder as the default?

If so, we should not forget to update the docs.

**Comment by miketaylr** [comment]
We should decide what to do with this. Remove it, use it, etc.

**Comment by karlcow** [comment]
We might be able to clean up the CSS. @miketaylr will check.

**Comment by miketaylr** [comment]
looking at the bugs in the repo:

https://github.com/purifycss/purifycss/issues/161
https://github.com/purifycss/purifycss/issues/162
https://github.com/purifycss/purifycss/issues/156

And see also https://github.com/facebook/create-react-app/issues/1092#issuecomment-264969752.

I don't think this project is in a good state for us to use in production. Let's just remove.
