### ISSUE TITLE
Back button issues when navigating to /issues

### ISSUE THREAD

**Issue by vladikoff** [webcompat/webcompat.com#2338]
1. go to https://webcompat.com/
2. scroll down to footer, click on "List of issues"
3. get to issue list, **press browser back button**
4. browser doesn't go back to the main page, stays on /issues

Chrome 65.0.3325 /// Mac OS X 10.13.2

**Comment by karlcow** [comment]
Confirmed on Firefox Nightly too. 
I don't even know how it's possible :) Thanks @vladikoff for the report.

**Comment by karlcow** [comment]
Oh…
when we click on https://webcompat.com/issues
The JS client is rewriting this as 
https://webcompat.com/issues?page=1&per_page=50&state=open&stage=all&sort=created&direction=desc

This should probably not happen.

**Comment by zoepage** [comment]
Thanks for reporting!

This is a known issue (sorry on my phone && can't find it right now :/)

There was already context in the other bug on what caused it.
