### ISSUE TITLE
Triage Dashboard summary info is not centered

### ISSUE THREAD

**Issue by softvision-sergiulogigan** [webcompat/webcompat.com#2341]
**Environment:**
Browser / Version: Chrome 65.0.3325.181 (Desktop), Firefox Nightly 61.0a1 (Desktop)
Operating System: Windows 10

**Steps to Reproduce:**
1. Go to https://webcompat.com/dashboard/triage
2. Observe the position of the summary info.

**Expected Behavior:**
The summary info is centered.

**Actual Behavior:**
The summary info is not centered.

**Notes:**
1. Screen capture attached.
2. Reproducible both on Chrome and Firefox.

Watchers:
@softvision-sergiulogigan
@softvision-oana-arbuzov

sv;

![image](https://user-images.githubusercontent.com/16573771/38074784-b2a7f550-3338-11e8-9deb-f8a8f9a3673d.png)

**Comment by magsout** [comment]
```
.wc-Stats {
    max-width: 840px; // removed that line
    display: flex;
    align-items: center;
    justify-content: center;
    flex-wrap: wrap;
}
```

**Comment by magsout** [comment]
@karlcow you added this line https://github.com/webcompat/webcompat.com/pull/2290/files#diff-03e144e6f1cee1f83618ef9127f23949R3 reason you did that? If we removed this line the content is center, so I miss something I think

**Comment by karlcow** [comment]
yup if the window is very large the cards/list will be align on the left but the 3 boxes will be at the center. We can fix it. :) I can propose a little tweak.

**Comment by softvision-sergiulogigan** [comment]
When you have the time for this, @magsout @karlcow or maybe even @laghee ...

**Comment by karlcow** [comment]
I will check later this week. :)

**Comment by karlcow** [comment]
If we set everything at 960px we get a good compromise.

**Comment by karlcow** [comment]
<img width="1127" alt="capture d ecran 2018-08-10 a 11 32 06" src="https://user-images.githubusercontent.com/505230/43935907-10550258-9c91-11e8-90af-17c21f143e53.png">
<img width="1127" alt="capture d ecran 2018-08-10 a 11 32 12" src="https://user-images.githubusercontent.com/505230/43935908-108ce6e6-9c91-11e8-9c50-d169f0a8284c.png">

**Comment by karlcow** [comment]
@softvision-sergiulogigan I hope this will work for you.
And this is the layout for very very very large windows. 😛 
<img width="2437" alt="capture d ecran 2018-08-10 a 11 36 25" src="https://user-images.githubusercontent.com/505230/43936029-ae637c2c-9c91-11e8-9c6d-077d01b3468b.png">

**Comment by karlcow** [comment]
@softvision-sergiulogigan 

> I was actually expecting something like...

It's what it does. but it keeps the cards and the stats aligned together.
The very large screenshot up there is for a very large window.

Do you want the cards to spread on the full width of the window?
<img width="3178" alt="capture d ecran 2018-08-14 a 14 11 59" src="https://user-images.githubusercontent.com/505230/44072873-0c8eef9c-9fcc-11e8-87ca-c1fe4677e01d.png">

**Comment by softvision-sergiulogigan** [comment]
> Do you want the cards to spread on the full width of the window?

IMO, this would be the expected behavior, @karlcow ...

**Comment by karlcow** [comment]
ok! We can do that. :) I'm not a big fan of full screen stuff. But why not. :)
@magsout I will fix the PR.
