### ISSUE TITLE
“Search” icon from the input field is not functional

### ISSUE THREAD

**Issue by softvision-oana-arbuzov** [webcompat/webcompat.com#2342]
URL: www.staging.webcompat.com , www.webcompat.com 
Browser / Version: Firefox Nightly 61.0a1 (2018-03-28), Chrome 65.0.3325.181
Operating System: Windows 10 Pro, Samsung Galaxy S7 Edge (Android 7.0) - 1440 x 2560 pixels (~534 ppi pixel density) 

**Steps to Reproduce:**
    1. Navigate to https://webcompat.com/issues?page=1&per_page=50&state=open&stage=all&sort=created&direction=desc 
    2. Tap the “Search” field and type in a keyword (e.g. test).
    3. Click the “Search” icon.
    4. Observe behavior.
       
**Expected Behavior:**
The search is performed.

**Actual Behavior:**
The search is not performed.

**Note**
    1. Workaround:  Clicking keyboard “Enter” button the search is performed.
        
**Watchers:**
@softvision-sergiulogigan
@softvision-oana-arbuzov

sv; 

![searchiconnotfunctional](https://user-images.githubusercontent.com/12184325/38075006-75247612-3339-11e8-91e1-7870574e2a47.gif)

**Comment by zoepage** [comment]
Looks like another rebase bug we didn't catch.

**Comment by magsout** [comment]
I'm not able to reproduce. 

@softvision-oana-arbuzov  if you watch the url you can see that your query is add.

- go to https://webcompat.com/issues?page=1&per_page=50&state=open&stage=all&sort=created&direction=desc
- 2. Tap the “Search” field and type in a keyword (e.g. test).
- 3. Click the “Search” icon.
- watch your url you have now test which is add after `q=`: https://webcompat.com/issues?page=1&per_page=50&state=open&stage=all&sort=created&direction=desc&q=test

You can try with somethig like : `material` click the search icon, and try again with test .
