### ISSUE TITLE
Change GA account from personal to Mozilla account

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat.com#2344]
Apparently Mozilla has better privacy guarantees/policies, due to our business relationship for Google Apps. 

So let's switch the analytics over to that.

**Comment by miketaylr** [comment]
> @miketaylr I can remove the old one?

remove how? (in which context?)

**Comment by magsout** [comment]
@miketaylr sorry, my message was not super clear. I mean in my GA. You gave me access to the AG, but you replaced it with that of mozilla GA. So is it worth keeping the old one?

**Comment by miketaylr** [comment]
Ah, eh, only if you care about historical data. Once the new one is deployed it will be useless.

**Comment by miketaylr** [comment]
> As #2345 got merged, shall we close?

Yep, sorry!
