### ISSUE TITLE
Long URL overflow

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat.com#2347]
STR:

1. go to https://webcompat.com/issues/1732

Expected: URL wraps
Actual: It doesn't

<img width="1741" alt="screen shot 2018-03-29 at 11 02 09 pm" src="https://user-images.githubusercontent.com/67283/38124122-3fb026f4-33a5-11e8-9a04-f4a14ba97d58.png">

**Comment by Regaddi** [comment]
Suggested fix:

```css
.comment-body a {
  Word-Break: break-all;
}
```
