### ISSUE TITLE
Add TravisBuddy bot to comment on test failures

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat.com#2352]
Sometimes it's hard to notice that tests are failing, or why. TravisBuddy is a bot that will explain failures in a comment.

https://github.com/didi/cube-ui/pull/47 is an example of it being used.

https://www.travisbuddy.com/
https://github.com/bluzi/travis-buddy

Thoughts?

**Comment by magsout** [comment]
Didn’t know but good idea

**Comment by zoepage** [comment]
+1 on this. The wording of the messages also are following our CoC guidelines. :)

**Comment by miketaylr** [comment]
Cool, thanks. Let's try it out for a while!
