### ISSUE TITLE
Unable to upload image in Focus Android

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat.com#2359]
(spun out from https://github.com/webcompat/webcompat.com/issues/2271)

STR:

1. go to webcompat.com/issues/new in Focus Android
2. click on Upload screenshot

Expected: filepicker dialog
Actual: nothing

**Comment by miketaylr** [comment]
...does this even work in Focus? 

`data:text/html, <input type=file>` does nothing.

**Comment by miketaylr** [comment]
Welp, no: https://github.com/mozilla-mobile/focus-android/issues/937

**Comment by zoepage** [comment]
Shall we sniff for `Focus/Klar` and display a message?

**Comment by miketaylr** [comment]
Given this is a focus bug, there's nothing we can do here.
