### ISSUE TITLE
markdown quotes do not have very identifiable styles

### ISSUE THREAD

**Issue by karlcow** [webcompat/webcompat.com#2360]
Go to the comment section. 
Insert a comment with a quote

```
> This is a quote

blahabla
```

Result:

<img width="651" alt="capture d ecran 2018-04-04 a 11 02 24" src="https://user-images.githubusercontent.com/505230/38284809-1fdd5b4c-37f8-11e8-9efa-502edb0a1ed5.png">

https://webcompat.com/issues/16317#issuecomment-378456081

**Comment by Regaddi** [comment]
The `<blockquote>` element doesn't have any styles defined at all.

How about something like this? (Idea only)

![image](https://user-images.githubusercontent.com/1336590/38320001-a2efa8a6-3833-11e8-9e51-ee57199ba9e3.png)

**Comment by miketaylr** [comment]
Either options is a big improvement! For the first by @Regaddi, I would say maybe something a little less prominent (perhaps just smaller quote graphics).

**Comment by karlcow** [comment]
+1 for simplicity. It will better fit the design by @zoepage
