### ISSUE TITLE
Remove waffle.io ?

### ISSUE THREAD

**Issue by zoepage** [webcompat/webcompat.com#2380]
Are we still using waffle.io? If not, we might want to remove it from our README.md?

**Comment by miketaylr** [comment]
I don't think we've been using it very actively. Github projects is a good alternative, if we feel like we need to organize a specific project.

**Comment by zoepage** [comment]
Okay, let's remove it then from the README.md.

Are there any labels that we can also remove that are used by waffle.io?

**Comment by magsout** [comment]
@zoepage The only label used by waffle is 

![capture d ecran 2018-04-13 a 21 31 56](https://user-images.githubusercontent.com/1997108/38754446-3092cec4-3f62-11e8-84d1-10f5e02278b8.png)

**Comment by zoepage** [comment]
@magsout Wasn't `ready` also one? 🤔

**Comment by magsout** [comment]
@zoepage ah, hum is it @karlcow that puts this label there https://github.com/webcompat/webcompat.com/pull/2379 ? Or his account connected with waffle?

**Comment by zoepage** [comment]
Both might be possible. We should just keep this in mind when we remove waffle.io :)

**Comment by Obtin** [comment]
@zoepage @karlcow is this issue still active ? If yes, I would like to take this up.

**Comment by karlcow** [comment]
@Obtin please do ! :) thanks.

**Comment by karlcow** [comment]
The line in question.
https://github.com/webcompat/webcompat.com/blame/d56cd783366d725bcf2cf560723a590faf41e08f/README.md#L11

**Comment by karlcow** [comment]
Closed by #2588
