### ISSUE TITLE
Add security.txt?

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat.com#2381]
`2018/03/10 11:12:23 [error] 14951#0: *1443272 open() "XXXXX/staging.webcompat.com/.well-known/security.txt" failed (2: No such file or directory), client: XXXXXX, server: staging.webcompat.com, request: "GET /.well-known/security.txt HTTP/1.1", host: "XXXXXX"`

I never heard about this, but it seems interesting: https://securitytxt.org/

**Comment by zoepage** [comment]
I really like the idea. :)

Just one question to get context, do we have a process in place for what happens after someone will report an issue?

**Comment by miketaylr** [comment]
> Just one question to get context, do we have a process in place for what happens after someone will report an issue?

The not great process right now would be: "figure out how to fix it, ASAP". But we could create one here on the wiki.

**Comment by karlcow** [comment]
Let's do this with a simple text message.
Be careful with the current ignore all `/.well-known/`
