### ISSUE TITLE
GA data retention policy

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat.com#2390]
I just got an email from Google Analytics saying they added the ability to delete user data after a period of time, starting in May:

https://support.google.com/analytics/answer/7667196

I think it makes sense to select the smallest period of time (14 months), any reason that's a bad idea? @adamopenweb?

We will need to update the privacy policy with whatever we choose.

**Comment by adamopenweb** [comment]
I can't think of any reason to keep longer than 14 months.

**Comment by digitarald** [comment]
If we use the Mozilla GA account this should be covered.

**Comment by miketaylr** [comment]
> If we use the Mozilla GA account this should be covered.

Currently we use a webcompat GA account, which was created from Mozilla google apps account (mine).
