### ISSUE TITLE
No focus style for image upload

### ISSUE THREAD

**Issue by Regaddi** [webcompat/webcompat.com#2399]
There is currently no style defined for the upload area in the bugform.
I'd suggest to use the existing hover styles on focus, just like other input fields.

Since the element, that receives focus is the `<input type="upload">` and the styles are applied to the element around, I'd suggest using the `:focus-within` pseudo selector.

![image](https://user-images.githubusercontent.com/1336590/38852708-2a2a18e2-421b-11e8-9264-4ba1f3d89b06.png)

**Comment by zoepage** [comment]
merged #2400
