### ISSUE TITLE
Add ability to upload images to backend

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat.com#24]
Screenshots are super helpful for bug reports. We should consider adding this ability to our form and hosting images ourselves (or via a 3rd party API like imgur).

**Comment by miketaylr** [comment]
Sorry for all the noise here. Just organizing my thoughts. We have 2 related Milestones:

1. Image uploading
2. Add a screenshot feature

2 depends on 1.

**Comment by miketaylr** [comment]
There will be 3 possible ways to upload an image:

1. When reporting an image, there should be an input[type=file]
2. When commenting on an image, there should be an `input[type=file]` (in addition to dragon drop, eventually) :dragon: :dragon_face: 
3. When reporting an image from one of our addons that supports some sort of a screenshot API

Here's how I see this working for us, roughly:

For issue creation:
1) The file is uploaded and returns a URI pointer to the file
2) That URI is embedded in the issue body using GitHub image markdown syntax: `![file name here](http://path/to/image/)`
3) (I think GitHub uploads all these to their own CDN)

For issue commenting:
Same thing, but included inside a comment rather than the issue body.

![test](http://ecx.images-amazon.com/images/I/41%2BeZQfvcAL._SY355_.jpg)

**Comment by miketaylr** [comment]
Testing something 

![](https://miketaylr.com/bzla/tacocat.jpg)

**Comment by miketaylr** [comment]
>  3) (I think GitHub uploads all these to their own CDN)

So, that's true for true uploads. If you just provide a link to an image, it uses a content proxy:

https://cloudup.com/iSnv2nObVWn

**Comment by miketaylr** [comment]
Thinking of what's left to do:

* [ ] Configure server with location for file uploads (outside of www root)
* [ ] Some form of testing

**Comment by miketaylr** [comment]
So far it's working (on staging): http://staging.webcompat.com/issues/267

**Comment by miketaylr** [comment]
@magsout how hard is it to add a glyph to our symbol font? I want to add the one @calexity suggested here: https://github.com/webcompat/webcompat.com/issues/431#issuecomment-68215433

**Comment by magsout** [comment]
@miketaylr branch origin/issues/24/1 ?

**Comment by magsout** [comment]
@miketaylr just added icon

**Comment by miketaylr** [comment]
@magsout you rock!

**Comment by magsout** [comment]
```    from flaskext.uploads import configure_uploads
ImportError: No module named flaskext.uploads
make: *** [start] Error 1
```

hum, why ?

**Comment by miketaylr** [comment]
@magsout ah, i added a new flask module. you can either do `pip install -r requirements.txt` again or just `pip install Flask-Uploads`.

**Comment by magsout** [comment]
```
Exception:
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/Library/Python/2.7/site-packages/pip/commands/install.py", line 283, in run
    requirement_set.install(install_options, global_options, root=options.root_path)
  File "/Library/Python/2.7/site-packages/pip/req.py", line 1431, in install
    requirement.uninstall(auto_confirm=True)
  File "/Library/Python/2.7/site-packages/pip/req.py", line 598, in uninstall
    paths_to_remove.remove(auto_confirm)
  File "/Library/Python/2.7/site-packages/pip/req.py", line 1836, in remove
    renames(path, new_path)
  File "/Library/Python/2.7/site-packages/pip/util.py", line 295, in renames
    shutil.move(old, new)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 299, in move
    rmtree(src)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 252, in rmtree
    onerror(os.remove, fullname, sys.exc_info())
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 250, in rmtree
    os.remove(fullname)
OSError: [Errno 13] Permission denied: '/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pytz/__init__.py'

Storing debug log for failure in /Users/GuillaumeDEMESY/Library/Logs/pip.log
```



sounds not good

**Comment by miketaylr** [comment]
Did you have your virtualenv activated? `source env/bin/activate`? If so, I would try with `sudo`.

**Comment by magsout** [comment]
I cloned Webcompat:

```console
sudo make install
make start (works)
git checkout origin/issues/24/1
git checkout -b issues/24/1
source env/bin/activate
sudo pip install -r requirements.txt
```

And I have that error, any idea ?

```
Traceback (most recent call last):
  File "run.py", line 22, in <module>
    from webcompat import app
  File "/Users/GuillaumeDEMESY/Github/webcompat/webcompat.com/webcompat/__init__.py", line 27, in <module>
    import webcompat.views
  File "/Users/GuillaumeDEMESY/Github/webcompat/webcompat.com/webcompat/views.py", line 35, in <module>
    from webcompat.api.uploads import upload
  File "/Users/GuillaumeDEMESY/Github/webcompat/webcompat.com/webcompat/api/uploads.py", line 24, in <module>
    configure_uploads(app, images)
  File "/Users/GuillaumeDEMESY/Github/webcompat/webcompat.com/env/lib/python2.7/site-packages/flaskext/uploads.py", line 194, in configure_uploads
    config = config_for_set(uset, app, defaults)
  File "/Users/GuillaumeDEMESY/Github/webcompat/webcompat.com/env/lib/python2.7/site-packages/flaskext/uploads.py", line 162, in config_for_set
    raise RuntimeError("no destination for set %s" % uset.name)
RuntimeError: no destination for set uploads
make: *** [start] Error 1
```

**Comment by miketaylr** [comment]
Hmm. It sounds like the following should prevent that error: https://github.com/webcompat/webcompat.com/blob/issues/24/1/config.py.example#L49-L51

Let me uninstall it and try to reproduce.

**Comment by miketaylr** [comment]
@magsout ah yeah. The tricky thing is we have new stuff in config.py.example that won't be automatically copied over to config.py when you switch branches.

So to get it running, you can copy the following lines into your config.py:

```
LOCALHOST = not PRODUCTION and not DEVELOPMENT
# Image uploading settings
# See http://pythonhosted.org/Flask-Uploads/#configuration
if PRODUCTION:
    UPLOADS_DEFAULT_DEST = ''
    UPLOADS_DEFAULT_URL = ''
elif DEVELOPMENT:
    UPLOADS_DEFAULT_DEST = ''
    UPLOADS_DEFAULT_URL = ''
elif LOCALHOST:
    UPLOADS_DEFAULT_DEST = BASE_DIR + '/uploads/'
    UPLOADS_DEFAULT_URL = 'http://localhost:5000/'
```

Kind of a PITA...

**Comment by miketaylr** [comment]
Let me add a line to CONTRIBUTING.md about this error message.

**Comment by magsout** [comment]
perfect :+1:

**Comment by magsout** [comment]
@miketaylr you are doing this option https://cloud.githubusercontent.com/assets/1103366/5564597/aee8f9bc-8e97-11e4-804e-05bfc887de82.png ?

**Comment by magsout** [comment]
not this https://cloud.githubusercontent.com/assets/1103366/5564563/39e236a2-8e96-11e4-9c87-225c2606e9b8.png ?

**Comment by magsout** [comment]
Just add icon and button style : 

![capture d ecran 2015-08-14 a 23 41 20](https://cloud.githubusercontent.com/assets/1997108/9284670/03ce4c7a-42de-11e5-93e4-fc2c8eb270e4.png)

**Comment by miketaylr** [comment]
@magsout yes! It looks great, thanks. :+1: 

The "include a screenshot automatically" thing will have to be controlled by addons--but we're not there yet.

**Comment by miketaylr** [comment]
Just a few things left:

- [ ] add clientside validation for file extension to bugform.js
- [ ] tweak `webcompat.api.uploads#upload` to return a JSON response with filename and URI (right now the way I'm doing this is a hack). This will also make comment image uploads via JS easier.
