### ISSUE TITLE
details element parsed as string not HTML

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat.com#2408]
https://staging.webcompat.com/issues/1489

<img width="653" alt="screen shot 2018-04-18 at 10 42 22 am" src="https://user-images.githubusercontent.com/67283/38948735-33c1fc14-42f5-11e8-92b3-d5488216df8f.png">

**Comment by miketaylr** [comment]
I'll investigate, but if this is semi-complicated, we should just remove `details` and use a markdown header.

**Comment by miketaylr** [comment]
On GitHub
<img width="293" alt="screen shot 2018-04-18 at 10 45 54 am" src="https://user-images.githubusercontent.com/67283/38948913-b7f7f916-42f5-11e8-8737-f55759818150.png">

**Comment by miketaylr** [comment]
Hm. 

<img width="394" alt="screen shot 2018-04-18 at 10 49 37 am" src="https://user-images.githubusercontent.com/67283/38949082-3aec7a2c-42f6-11e8-9335-28a6627548bf.png">

**Comment by miketaylr** [comment]
Ah, I think it's just being sanitized to a string. Let's see if we can hack it.

**Comment by Regaddi** [comment]
Phew. It's basically mixed Github flavoured Markdown with HTML in it. This might be tricky.

**Comment by Regaddi** [comment]
Seems like https://github.com/svbergerem/markdown-it-sanitizer is not maintained anymore. I'm currently reaching out to @svbergerem to clarify.

**Comment by svbergerem** [comment]
@Regaddi No, the project is not dead. I'm not aware of any bugs and I didn't have enough time to implement new features. I already planned a bigger refactoring in 2016 that would allow adding and removing accepted tags. I just started working on the project again and I'll let you know when there is anything new.

**Comment by miketaylr** [comment]
> Just to note that markdown allows inline HTML. It's a feature. :)

Yes, but we use the sanitizer to restrict what's allowed. Lots of scary things can sneak into valid HTML.

**Comment by miketaylr** [comment]
@Regaddi showed me a workaround that we could ship until the sanitizer lib is updated, I might have some time to work on that tonight (before he wakes up), since I'm just hanging out at an AirBNB away from my family.

**Comment by miketaylr** [comment]
> I might have some time to work on that tonight (before he wakes up)

(probably not happening tonight!)

my idea was to essentially create a new file in the `/static/js/lib/mixin` directory, something like `allowlist.js`, then include it into the comment and issue model files similar to https://github.com/webcompat/webcompat.com/blob/cb766b2c2b7e628c9238195a71c28faaed6b349e/webcompat/static/js/lib/issue-list.js#L262.

![ff9d7l](https://user-images.githubusercontent.com/67283/38970173-cdfff314-4348-11e8-9d14-e190fb932abf.jpg)

I think that's probably better than forking the sanitizer lib, short-term.
