### ISSUE TITLE
Clean up media queries in stylesheets

### ISSUE THREAD

**Issue by Regaddi** [webcompat/webcompat.com#2417]
There are some media queries not using the breakpoint variables. We should investigate those and fix them.

**Comment by zoepage** [comment]
I think @magsout can give some context here?

**Comment by magsout** [comment]
@zoepage um, sorry, I don't know what some context I can give?

**Comment by zoepage** [comment]
@magsout As far as I remember, you added some breakpoints that were not the variable ones while building the label box? Or am I mistaken?

**Comment by magsout** [comment]
@zoepage ah, ok, sorry, I didn't understand the issue, so i didn't understand your message ;)

thanks.

let me see into the code.

**Comment by magsout** [comment]
few month later I don't remember what the point is this issue, @Regaddi could you explain to me, what exactly it is?

**Comment by magsout** [comment]
thanks @Regaddi 

Still have one question.

sorry sorry, but what do you mean by `the predefined breakpoints` ?

**Comment by Regaddi** [comment]
I thought of these: https://github.com/webcompat/webcompat.com/blob/master/webcompat/static/css/src/variables.css#L11-L13

Maybe I misinterpreted them. There has been a discussion (not sure which issue it was) about using the variables in the breakpoints, but unluckily this is not possible with plain CSS.
However, I think it is a good idea to have consistent media queries within the whole project.

**Comment by magsout** [comment]
@Regaddi ok, thanks for the explanation.

**Comment by magsout** [comment]
I'm going to close this issue, because it's hard to have consistent mq, I mean it depends of component and the behavior, IMHO it's not a bad thing.
