### ISSUE TITLE
The All Issues section is not working

### ISSUE THREAD

**Issue by softvision-sergiulogigan** [webcompat/webcompat.com#2428]
**Environment:**
Browser / Version: Chrome 66 (Desktop), Firefox Nightly 61.0a1 (Desktop)
Operating System: Windows 10

**Steps to Reproduce:**
1. Go to https://webcompat.com
2. Click on the All Issues button.

**Expected Behavior:**
The correct page is opened.

**Actual Behavior:**
An error page is opened. Internal Server Error.

**Notes:**
1. Screen capture attached.
2. Reproducible both on Chrome and Firefox.
3. Console: Content Security Policy: The page’s settings blocked the loading of a resource at self (“script-src”). Source: onfocusin attribute on DIV element.

Watchers:
@softvision-sergiulogigan
@softvision-oana-arbuzov

sv;

![image](https://user-images.githubusercontent.com/16573771/39347337-06fa7690-49fb-11e8-8def-c87b7a52a6f7.png)

**Comment by magsout** [comment]
thanks @softvision-sergiulogigan 

fixed by  @karlcow 

![capture d ecran 2018-04-27 a 11 18 36](https://user-images.githubusercontent.com/1997108/39355603-ede346f6-4a0d-11e8-929c-71bfd262949c.png)
