### ISSUE TITLE
Add 2 new tracking protection related type labels

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat.com#2434]
I'd like to automatically add one of the 2 labels to new issues, if users report a site where TP blocked something:

`type-tracking-protection-basic`
`type-tracking-protection-strict`

We may or may not do anything with them (or maybe automatically close `-strict` ones as wontfix, but it will be able to have the label to track the sites going foward.

**Comment by karlcow** [comment]
That's a good piece of information to speed up triage/diagnosis.
And indeed we could close automagically the strict ones with webcompat-bot and a boilerplate text.
