### ISSUE TITLE
textarea in /issues/new form is visually difficult to use

### ISSUE THREAD

**Issue by karlcow** [webcompat/webcompat.com#2443]
This is a followup on #2101 
Now that I have been using the new form for the last couple of months I can confirm for the lack of contrasts for the textarea boundaries make it very difficult and straining on the eyes.

It's visually hard to define the boundaries of this textarea. Specifically with long prose. 

<img width="471" alt="capture d ecran 2018-05-09 a 08 44 27" src="https://user-images.githubusercontent.com/505230/39788393-49d901ca-5365-11e8-95e5-4641c1e49563.png">

adding a slight contrast in the background helps a lot 
<img width="474" alt="capture d ecran 2018-05-09 a 08 48 52" src="https://user-images.githubusercontent.com/505230/39788543-e6251c76-5365-11e8-923a-774c97965da2.png">

or another font style.

<img width="504" alt="capture d ecran 2018-05-09 a 08 53 18" src="https://user-images.githubusercontent.com/505230/39788681-7c981e06-5366-11e8-9f55-e09f0b743b90.png">

**Comment by suhailsinghbains** [comment]
Hi @karlcow .
Would like to work on this bug, I can make the textarea just like this [right puicture](https://user-images.githubusercontent.com/505230/36292757-6664a95e-1317-11e8-97f3-f2315d5121bd.png) or something just very different.

**Comment by karlcow** [comment]
@suhailsinghbains Thanks for proposing. The right side is what we had before and we do not want necessary to go back to this. I don't think it will fit the square mood that was set by the previous iteration. Let's wait next month, we will probably discuss this and possible solutions. We have a f2f meeting partly for this soon.

**Comment by magsout** [comment]
@karlcow @miketaylr is it enought? What do you think?

![capture d ecran 2018-10-02 a 09 13 46](https://user-images.githubusercontent.com/1997108/46334209-860db380-c623-11e8-964e-8c3ec9324b80.png)

**Comment by miketaylr** [comment]
Looks great!
