### ISSUE TITLE
When starting the project in local, logs and debugging mode are not accessible anymore

### ISSUE THREAD

**Issue by karlcow** [webcompat/webcompat.com#2445]
Before when we were starting the project locally, the logs were displayed on the terminal, 
and we were given a PIN number for debugging live.

This is not happening anymore.

**Comment by karlcow** [comment]
To clarify this is a regression. We should have something like more or less:


```
 * Forcing debug mode on
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 861-432-160
```

Plus the message about initializing milestones.

This above was the result of running `FLASK_DEBUG=1 flask run` instead of `python run.py`.

**Comment by karlcow** [comment]
```bash
FLASK_DEBUG=1 FLASK_APP=run.py flask run
```

```
 * Serving Flask app "run"
 * Forcing debug mode on
Statuses Initialization…
Fetching milestones from Github…
Milestones saved in data/
Milestones in memory
Statuses Initialization…
Fetching milestones from Github…
Milestones saved in data/
Milestones in memory
```

**Comment by karlcow** [comment]
ok understood. 
The culprit was basically these lines.

https://github.com/webcompat/webcompat.com/blob/42d7d7a2a5315a448ec8fdaebdcc7a23a6ea128c/config/__init__.py#L174-L177

Flask has loggers quite hardcoded and anything simple you do has a tendency to break the rest of logging.

So I remove the logging for now and switched to print statements for milestones. 
We will need a way to figure out to make this work in a smoother more elegant way.

This comment gives good information about the whys
https://stackoverflow.com/questions/17743019/flask-logging-cannot-get-it-to-write-to-a-file#answer-47808630

**Comment by miketaylr** [comment]
Thanks for figuring this out @karlcow. There were some changes to how logging works in Flask 1.0, I don't know how or if it is useful in this instance: https://github.com/pallets/flask/pull/2436
