### ISSUE TITLE
Grid Layout not correct in Microsoft Edge

### ISSUE THREAD

**Issue by Regaddi** [webcompat/webcompat.com#2446]
**Browser Version:**
Microsoft Edge 40.15063.0.0
Microsoft EdgeHTML 15.15063

**Main page**
![image](https://user-images.githubusercontent.com/1336590/39836464-bb772c3a-53d3-11e8-9e5b-1bb9d459a99b.png)
![image](https://user-images.githubusercontent.com/1336590/39836631-56d0c600-53d4-11e8-9bc1-52d628097ece.png)

**Contribute**
![image](https://user-images.githubusercontent.com/1336590/39836508-f0e89926-53d3-11e8-8ba8-7ab1cac0b34b.png)
![image](https://user-images.githubusercontent.com/1336590/39836543-122d410e-53d4-11e8-8064-3736f165f842.png)

**Comment by miketaylr** [comment]
Probably not worth worrying about for old Edge.
