### ISSUE TITLE
Radio with wrong styling (misaligned and not round) in Microsoft Edge

### ISSUE THREAD

**Issue by Regaddi** [webcompat/webcompat.com#2447]
**Browser Version**
Microsoft Edge 40.15063.0.0
Microsoft EdgeHTML 15.15063

![image](https://user-images.githubusercontent.com/1336590/39836701-8adf8d3c-53d4-11e8-8f5c-6ece03ed4f9a.png)

**Comment by miketaylr** [comment]
This was old Edge, so no longer an issue worth fixing IMO.
