### ISSUE TITLE
Add logging capabilities to Flask

### ISSUE THREAD

**Issue by karlcow** [webcompat/webcompat.com#245]
It would be good to have logging capabilities for the different calls of the program, that would help us have a better understanding on where we do wrong things and where to solve redundancies.

**Comment by karlcow** [comment]
Things to log. Missmatch with the DB. 

> If you delete Session.db and restart the app, the database will be created with the correct columns. I'll add something to CONTRIBUTING.md about this error so people can find it in the future.

see discussion in #700

**Comment by karlcow** [comment]
Things to log. User login error.

**Comment by karlcow** [comment]
I would recommend we create a file that we rotate once a day, and that we send automatically by email with a cron. This to avoid to have a dependency on queuing jobs inside flask. Also we currently have no need for live debugging info. We can revisit this a bit later. 

The log file can be sent to a couple of persons maybe @miketaylr and myself.

**Comment by karlcow** [comment]
in #704 @miketaylr said:

> +1, thanks @karlcow. Before we log anything that might be privacy-sensitive, let's be sure to update our privacy document. And maybe adding a few notes on usage to CONTRIBUTING.md would be a good addition as well.

Opened #705 and #706 for this purpose.

**Comment by miketaylr** [comment]
Thanks Karl.
