### ISSUE TITLE
Triage dashboard displays incorrect information

### ISSUE THREAD

**Issue by softvision-sergiulogigan** [webcompat/webcompat.com#2450]
**Environment:**
Browser / Version: Chrome 66 (Desktop), Firefox Nightly 62.0a1 (Desktop)
Operating System: Windows 10

**Steps to Reproduce:**
1. Go to https://webcompat.com/dashboard/triage
2. Observe the "Older than 48h" information box.

**Expected Behavior:**
The "Older than 48h" information box displays the same number as the number of cards.

**Actual Behavior:**
The "Older than 48h" information box displays a different number of issues than the number of cards.

**Notes:**
1. Screen capture attached.
2. Reproducible both on Chrome and Firefox.

Watchers:
@softvision-sergiulogigan
@softvision-oana-arbuzov

sv;

![image](https://user-images.githubusercontent.com/16573771/39871308-0c884b42-546d-11e8-9f1c-2132869d5a33.png)

**Comment by magsout** [comment]
Some Issues are not tagged by the back-end, so theses issues are always hidden

![capture d ecran 2018-05-10 a 15 05 07](https://user-images.githubusercontent.com/1997108/39872031-f73e413e-5466-11e8-9b5f-a7cd3cd8b783.png)

**Comment by magsout** [comment]
Follow Up on discussions with @karlcow on this morning, we thought it was about issues without milestone

**Comment by softvision-sergiulogigan** [comment]
Now we have 3 counted, and 5 displayed.

![image](https://user-images.githubusercontent.com/16573771/40310582-ee43e838-5d15-11e8-8e7e-20a3655fb756.png)

**Comment by softvision-sergiulogigan** [comment]
@magsout any updates on this issue? Is it easily fixable?

**Comment by magsout** [comment]
@softvision-sergiulogigan I tried to figure out why issues does'nt appears. 

I don't get it why yet ;p

But it seems nothing to do with label or milestone.. I have some work on the metrics dashboard, but I wiil try to spend some time on it

**Comment by magsout** [comment]
Few examples of issues not tagged:

https://webcompat.com/issues/17349
https://webcompat.com/issues/17360
https://webcompat.com/issues/17365

**Comment by magsout** [comment]
@karlcow  is it possible to see the object of these issues?

or maybe I missed something in the code:

```
  <article
    data-number="{{ issue['number'] }}"
    class="
      wc-Triage
      {% if issue['older'] %} priority {% endif %}
      {% if issue['needsinfo'] %} {{ 'needsinfo is-hidden' }} {% endif %}
      {% for browser in issue['browsers'] %}
        {{ browser }}
      {% endfor %}
    "
  >
```

**Comment by karlcow** [comment]
@magsout what do you mean?
do you mean you want to know what's inside `issue`
The template receives two pieces of data:

https://github.com/webcompat/webcompat.com/blob/011183b86a75b5a64ce4a19438c58cc69d2b2240/webcompat/views.py#L432-L443

* a needstriage_list
* stats

The `needstriage_list`

```python
[{'browsers': ['fixme'],
  'created_at': u'2018-06-14T15:19:43Z',
  'needsinfo': False,
  'number': 1543,
  'older': True,
  'title': u'yoopi - unknown',
  'updated_at': u'2018-06-14T15:19:44Z'},
 {'browsers': ['firefox'],
  'created_at': u'2018-06-14T22:50:31Z',
  'needsinfo': False,
  'number': 1544,
  'older': True,
  'title': u'testing-form.example.com - see bug description',
  'updated_at': u'2018-06-14T22:50:31Z'},
 {'browsers': ['firefox'],
  'created_at': u'2018-06-15T18:31:02Z',
  'needsinfo': False,
  'number': 1545,
  'older': True,
  'title': u'2971-report.example.com - see bug description',
  'updated_at': u'2018-06-15T18:31:03Z'},
 {'browsers': ['firefox'],
  'created_at': u'2018-06-15T18:32:26Z',
  'needsinfo': False,
  'number': 1546,
  'older': True,
  'title': u'2971-report.example.com - see bug description',
  'updated_at': u'2018-06-15T18:32:26Z'},
 {'browsers': ['firefox'],
  'created_at': u'2018-06-20T13:33:24Z',
  'needsinfo': False,
  'number': 1547,
  'older': True,
  'title': u'staging.webcompat.com - see bug description',
  'updated_at': u'2018-06-20T13:33:25Z'},
 {'browsers': ['firefox-mobile'],
  'created_at': u'2018-06-21T07:14:44Z',
  'needsinfo': False,
  'number': 1548,
  'older': True,
  'title': u'es.m.wikipedia.org - design is broken',
  'updated_at': u'2018-06-21T07:14:45Z'},
 {'browsers': ['firefox-mobile'],
  'created_at': u'2018-06-22T01:26:49Z',
  'needsinfo': False,
  'number': 1549,
  'older': True,
  'title': u'testing.example.org - unknown',
  'updated_at': u'2018-06-22T01:26:49Z'},
 {'browsers': ['chrome'],
  'created_at': u'2018-06-26T07:53:13Z',
  'needsinfo': False,
  'number': 1550,
  'older': False,
  'title': u'nextcloud.com - design is broken',
  'updated_at': u'2018-06-26T07:53:14Z'},
 {'browsers': ['firefox'],
  'created_at': u'2018-06-26T13:02:43Z',
  'needsinfo': False,
  'number': 1551,
  'older': False,
  'title': u'www.simsdom.com - site is not usable',
  'updated_at': u'2018-06-26T13:17:33Z'}]
```

and the `stats`

```
{'total': 9, 'needsinfo': 0, 'older': 7}
```

**Comment by karlcow** [comment]
<img width="723" alt="capture d ecran 2018-06-27 a 10 44 16" src="https://user-images.githubusercontent.com/505230/41948316-17dca240-79f7-11e8-8db5-dab012d6c174.png">

**Comment by magsout** [comment]
@karlcow 
> do you mean you want to know what's inside issue

Yes, I do.

I don't understand why these issues [17421](https://webcompat.com/issues/17421) [17422](https://webcompat.com/issues/17422) [17423](https://webcompat.com/issues/17423) for example, are not tagged by any status:

![capture d ecran 2018-06-27 a 08 58 39](https://user-images.githubusercontent.com/1997108/41957766-5071e002-79e8-11e8-8f2b-b62195ef6c97.png)

So no matter which filter is selected, these issues will never show up. I wonder if there is a bug on front side or back side. I don't see evdident on front side. Then, I wonder if it's possible to see 
![capture d ecran 2018-06-27 a 09 00 33](https://user-images.githubusercontent.com/1997108/41957854-92f273ba-79e8-11e8-8225-737013cb2631.png) for theses issue in specific, because I don't get it how to fix the bug

**Comment by karlcow** [comment]
Let's see for 17421.

opened on `2018-06-25T15:42:47Z` 
right now it is `2018-06-27T07:38:48Z`

so it's normal it doesn't show up. That's less than 48h?

**Comment by magsout** [comment]
follow up the discussion on irc

![capture d ecran 2018-06-27 a 09 45 30](https://user-images.githubusercontent.com/1997108/41960008-d88be932-79ee-11e8-8090-f0773e3b400a.png)

make sense now

**Comment by karlcow** [comment]
This doesn't seem to address @softvision-sergiulogigan concern though. We need to figure out why there's a discrepancy in between the two when it's happening.

**Comment by softvision-sergiulogigan** [comment]
As soon as we reach decent numbers of issues displayed in the Dasboard, and *if* the issue is still around, I'll let you know, so you can investigate further.

**Comment by laghee** [comment]
OK, so it's happening now, and I noticed two things:

- despite being tagged as `needsinfo-adamopenweb`, [this issue](https://webcompat.com/issues/17414) is still displayed under 48+ and not `needsinfo` (Issue #2511 ) -- so that may be what's messing with the numbers
- the `sort` function -- it looks like `oldest` and `newest` are doing the opposite of the expected:

<img width="1117" alt="screenshot 2018-06-27 10 30 14" src="https://user-images.githubusercontent.com/20972610/41962363-21c1eef2-79f5-11e8-8c82-52ebd303e59f.png">
<img width="1130" alt="screenshot 2018-06-27 10 30 07" src="https://user-images.githubusercontent.com/20972610/41962375-274fa4f4-79f5-11e8-8c56-ebdcc2e716bb.png">

**Comment by magsout** [comment]
@laghee oh good catch 
>the sort function seems reversed -- like oldest and newest are doing the opposite of the expected:

**Comment by softvision-sergiulogigan** [comment]
This is from the 4th of July

![image](https://user-images.githubusercontent.com/16573771/42280476-853ffda2-7fa9-11e8-9499-c73c29da0239.png)

**Comment by softvision-sergiulogigan** [comment]
And this is from the 7th of August

![image](https://user-images.githubusercontent.com/16573771/43762811-a704da32-9a31-11e8-8d9c-810a7ffa155e.png)

**Comment by softvision-sergiulogigan** [comment]
Let's update this with another screenshot

![image](https://user-images.githubusercontent.com/16573771/46517831-d2523100-c879-11e8-9345-830169f62d5b.png)

**Comment by softvision-sergiulogigan** [comment]
Today we have a weird behavior...
Triage Dashboard does not display the correct values for all the issues we have

![image](https://user-images.githubusercontent.com/16573771/46936251-7a2fe180-d066-11e8-9a3e-5868812dca0f.png)

Dashboard says 85 (+15 Needsinfo ones) and we really have 180 items.
Is the dashboard limited to counting only 100 items, @karlcow ?

**Comment by karlcow** [comment]
Maybe… I'll have to check why.

Thanks for reporting @softvision-sergiulogigan

**Comment by karlcow** [comment]
Let's close this. This dashboard has been transferred to [webcompat metrics](https://github.com/webcompat/webcompat-metrics-client/issues/172)
