### ISSUE TITLE
Labels color scheme is different on webcompat.com than on github

### ISSUE THREAD

**Issue by softvision-sergiulogigan** [webcompat/webcompat.com#2452]
**Environment:**
Browser / Version: Chrome 66 (Desktop), Firefox Nightly 62.0a1 (Desktop)
Operating System: Windows 10

**Prerequisites:**
Open 2 Nightly windows.

**Steps to Reproduce:**
1. Go to (for example) https://github.com/webcompat/web-bugs/issues/16883 in one of the windows.
2. Go to (for example) https://webcompat.com/issues/16883 in the other window.
4. Observe the Labels color scheme.

**Expected Behavior:**
labels have the same color.

**Actual Behavior:**
Labels have different color.

**Notes:**
1. Screen capture attached.
2. Reproducible both on Chrome and Firefox.

Watchers:
@softvision-sergiulogigan
@softvision-oana-arbuzov

sv;

![image](https://user-images.githubusercontent.com/16573771/39997817-d7942d34-578c-11e8-8ff8-b2796b16d6ce.png)

**Comment by zoepage** [comment]
This is not a bug, but a feature as we decided to group the labels.

**Comment by softvision-sergiulogigan** [comment]
Let's close it, then...
Thanks, @zoepage
