### ISSUE TITLE
Create a clone of 100 recent-ish issues in a test repo, to be deployed on staging

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat.com#2454]
As part of the next iteration of the pre-triage experiment, we'd like to clone the most recent 100 firefox issues (just the initial description, no comments) into a new repo, and deploy it to staging.

Some Participation team contributors will work on these, and we'll evaluate after the fact.

Note: once we begin the experiment, which will run for one week, we shouldn't use staging for testing. (I can add a password if we feel like that's a good idea).

**Comment by miketaylr** [comment]
We have some existing code that could probably be modified easily, https://github.com/webcompat/issue-importer... but I bet there are other projects out there.

**Comment by miketaylr** [comment]
https://github.com/muff1nman/github-issues-import looks nicer.

**Comment by miketaylr** [comment]
Created https://github.com/webcompat/pretriage-test-issues.

**Comment by miketaylr** [comment]
@softvision-sergiulogigan @softvision-oana-arbuzov I imported 100 recent issues https://github.com/webcompat/pretriage-test-issues/issues (the closed ones that say "test" were me screwing things up 🙈).

When we're ready to start this, please ping me and I can deploy these issues to the staging server.

**Comment by softvision-sergiulogigan** [comment]
This looks a-w-e-s-o-m-e!
Thanks Mike for the support!
