### ISSUE TITLE
Error setting up this project locally for development

### ISSUE THREAD

**Issue by mischah** [webcompat/webcompat.com#2455]
# Steps to reproduce

I’m on MacOS

```
$ git clone git@github.com:webcompat/webcompat.com.git
$ cd webcompat.com.git
$ npm run setup
$ cp config/secrets.py.example config/secrets.py
$ npm start

[…]
Statuses Initialization…
Fetching milestones from Github…
It failed with 404 Client Error: Not Found for url: https://api.github.com/repos/milestones!
We will read from data/milestones.json.

Oooops.
We can't find /Users/mkuehnel/Documents/Projects/webcompat.com/data/milestones.json
Double check that everything is configured properly
in config/secrets.py and try again. Good luck!
[…]
```

# Reason

<https://api.github.com/repos/milestones> returns:

```
{
  "message": "Not Found",
  "documentation_url": "https://developer.github.com/v3"
}
```

# Potential fix

Guess it should be <https://api.github.com/repos/webcompat/webcompat.com/milestones>, right?

**Comment by mischah** [comment]
Looking at `config/secrets.py` I guess I’m missing environmental variables?

**Comment by mischah** [comment]
I created `data/milestones.json` and entered the content of <https://api.github.com/repos/webcompat/webcompat.com/milestones>.

It doesn’t let me start:

```
> webcompat@ start /Users/mkuehnel/Documents/Projects/webcompat.com
> source env/bin/activate || . env/bin/activate && python run.py

Statuses Initialization…
Fetching milestones from Github…
It failed with 404 Client Error: Not Found for url: https://api.github.com/repos/milestones!
We will read from data/milestones.json.

Milestones are not initialized. Check logs.
```

**Comment by zoepage** [comment]
@mischah You always need the OAuth value https://github.com/webcompat/webcompat.com/blob/master/config/secrets.py.example#L72 in the `secrets.py`.

This is how you can create it: https://help.github.com/articles/creating-a-personal-access-token-for-the-command-line/

More info can be found in the setup docs here: https://github.com/webcompat/webcompat.com/blob/master/docs/dev-env-setup.md#configuring-the-server

LMK, if you have any other question! <3

**Comment by mischah** [comment]
Thank you so much.

**Comment by mischah** [comment]
## Update

1. I’ve created a [test repo](https://github.com/mischah/test-repo/milestones) with a milestone
2. Added the issue url to `secrets.py`:
   ```
   # Production GiHub Issues repo URI. Can be ignored for local testing.
   if env.PRODUCTION:
       ISSUES_REPO_URI = 'mischah/test-repo/issues'
   # Staging and Local instances use the same test repo
   else:
       ISSUES_REPO_URI = os.environ.get('ISSUES_REPO_URI') or 'mischah/test-repo/issues'
   ```
3. Created an access token with each and every permission
4. Added the token to `secrets.py`
   ```
   OAUTH_TOKEN = os.environ.get('OAUTH_TOKEN') or '[myToken]'  # nopep8
   ```

## Result

`data/milestones.json` is filled with the milestone from my test Repo 🎉 

**But I can’t start** 😢 

```
Statuses Initialization…
Fetching milestones from Github…
Milestones saved in data/
Milestones are not initialized. Check logs.
```

**Comment by mischah** [comment]
Finally found the log 😆 

It says:

```
WARNING 2018-05-18 16:02:01 A milestone is missing or has been added: [u'worksforme', u'1.0.0', u'non-compat', u'needscontact', u'invalid', u'needstriage', u'duplicate', u'needsdiagnosis', u'sitewait', u'wontfix', u'fixed', u'incomplete', u'contactready']
```

I have no clue what that means.

Added the issue labels to my test project because of being clueless 😂 
<https://github.com/mischah/test-repo/labels>

**Comment by zoepage** [comment]
@miketaylr @karlcow

**Comment by miketaylr** [comment]
Heya @mischah, thanks for filing a bug! There's a good chance our docs are missing something important here. 

My hunch is that you need to mirror the milestones from webcompat/web-bugs: https://github.com/webcompat/web-bugs/milestones

(we should have a bootstrap script that does this junk for you...)

Does it work if you make sure those milestones exist in your test repo?

**Comment by mischah** [comment]
Hah, thats it. I read them (from the logs) as issue labels 🙈 

Why are you using milestones to categorize your issues?

However, I’m going to create a PR to add the following to the docs:
- Location of the logs
- Needed milestones

**Comment by miketaylr** [comment]
> Why are you using milestones to categorize your issues?

Milestones are mutually exclusive, and our bugs can only ever be in a single state: needs triage, diagnosis, outreach, invalid, etc. We use labels for metadata.

(also, the repo only exists for issues, so we avoid any awkward conflict trying to use milestones how they're normally used)  

> However, I’m going to create a PR to add the following to the docs:

thanks!

**Comment by mischah** [comment]
Thanks for the info. Makes sense, but feels weird.

**Comment by karlcow** [comment]
@mischah As mike already replied for the why, just an additional comment. Think about the GitHub repo as a backend for https://webcompat.com/ not as the main UI to interact with bugs.

**Comment by Obtin** [comment]
@miketaylr I duplicated the milestones (manually added these for now). But it still gives the same error.

**Comment by karlcow** [comment]
What is happening for @mischah is that he created his own test repos BUT in the list of milestones there is this milestone `u'1.0.0'` which is not existent in the project.

for @Obtin it would be good to know what errors do you receive? What the logs are saying? Thanks.

**Comment by miketaylr** [comment]
It would probably be good to open a new issue as well, @Obtin. Thanks.

**Comment by Obtin** [comment]
@karlcow 
![webcompat](https://user-images.githubusercontent.com/25207205/45915316-e5e4ad00-be20-11e8-898b-67734f9346c9.png)
