### ISSUE TITLE
Missing a pull request template

### ISSUE THREAD

**Issue by mischah** [webcompat/webcompat.com#2460]
It could help people to discover and stick to the pull request guidelines.

**Comment by karlcow** [comment]
I didn't know what it was, so I went through the documentation.
Here some documentation for context.

* [Issue and Pull Request templates](https://blog.github.com/2016-02-17-issue-and-pull-request-templates/)
* [Creating a pull request template for your repository](https://help.github.com/articles/creating-a-pull-request-template-for-your-repository/)
* [Pull request templates](https://help.github.com/articles/about-issue-and-pull-request-templates/#pull-request-templates)

> You must create templates on the repository's default branch. Templates created in other branches are not available for collaborators to use. You can store your pull request template in the repository's visible root directory, the docs folder, or the hidden .github directory. Pull request template filenames are not case sensitive, and can have an extension such as .md or .txt.

Thanks @mischah
