### ISSUE TITLE
Multiple links are broken. README and contributing DOCs

### ISSUE THREAD

**Issue by karlcow** [webcompat/webcompat.com#2466]
@mischah I believe you moved the docs recently in #2192
![capture d ecran 2018-05-24 a 13 20 08](https://user-images.githubusercontent.com/505230/40464311-7f93dd48-5f55-11e8-8f1d-a82db36e8639.png)

Now the Contributing link is a 404.

**Comment by karlcow** [comment]
The links in the documentation are also broken.

**Comment by mischah** [comment]
Oops. Sorry. Going to fix this as soon as I am at my desk.

--

Von unterwegs gesendet.
