### ISSUE TITLE
Improve pull request template

### ISSUE THREAD

**Issue by mischah** [webcompat/webcompat.com#2468]
The issue number in the pull request template isn’t clickable by default when a PR is created.

# Reason

The issue number is wrapped by backticks for formatting reasons:

```
This PR fixes issue `#nnnn`
```

See:
https://github.com/webcompat/webcompat.com/blob/master/.github/pull_request_template.md

We should remove the backticks 😊

**Comment by suhailsinghbains** [comment]
Hi @mischah I would to work on this bug, please can I be assigned this.

**Comment by shristit** [comment]
Hi @mischah , can i work on this issue , aspirant to be outreachy intern this year with this project 
Thanks

**Comment by mischah** [comment]
Please feel free to submit a pull request 😊

**Comment by karlcow** [comment]
@shristit 

for the Outreachy contribution, we're asking all applicants to do an exercise related to the proposed project before asking for any other code contributions:
#2579
We would ask that you keep your evaluation secret until the Outreachy selection period is done. Thanks!

You still can try this issue if you wish.

Thanks.

**Comment by shristit** [comment]
Oops ok edited all the comments :)

**Comment by karlcow** [comment]
@shristit there was no issue with your comment. :) We just ask outreachy applicants to answer #2579 and send to @miketaylr and me as mentioned in the outreachy topic description. Your analysis of #2579 has to be kept secret. Good luck. Thanks.
