### ISSUE TITLE
400 on POST on localhost

### ISSUE THREAD

**Issue by karlcow** [webcompat/webcompat.com#2474]
@miketaylr 
So from the changelog I see that the code has been deployed since April 2018 version 10.0.0
That might be a good thing.

For me currently on localhost.

```bash
git checkout master
python fetch upstream
git merge upstream/master
grunt
python run.py
```

So far so good.

1. Open a browser
2. Go to http://localhost:5000/issues/new
3. File a bug report
4. Submit.

```
127.0.0.1 - - [31/May/2018 17:30:02] "POST /issues/new HTTP/1.1" 400 -
```

First question… is it only me?

**Comment by karlcow** [comment]
I can confirm that I have this behavior on a fresh install of the project.
Could someone else test too? @miketaylr

**Comment by miketaylr** [comment]
@karlcow I just ran into this trying to deploy the latest v11.0.0 tag, and I wonder if it's related to ua-parser upgrade? Let me bisect using the staging branch, and we'll find out soon enough. Thanks for filing.

**Comment by miketaylr** [comment]
(i had been testing some virtualenv deploy stuff, so the site was only broken for about 1 minute, b/c i wanted to be very sure it was working)

**Comment by miketaylr** [comment]
```
[2018-06-01 18:45:26,998] ERROR in __init__: Exception thrown:
Traceback (most recent call last):
(snip)
  File "./webcompat/views.py", line 239, in create_issue
    abort(400)
(snip)
BadRequest: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
```

**Comment by miketaylr** [comment]
https://github.com/webcompat/webcompat.com/blob/707938a42229cbe6dac1088540834f9ed424864f/webcompat/views.py#L239 suggests that there isn't a `submit-type` on the form object. investigating.

**Comment by karlcow** [comment]
ok good! You found what was wrong.
