### ISSUE TITLE
Invalid link on Build Tools page

### ISSUE THREAD

**Issue by WesleyBranton** [webcompat/webcompat.com#2478]
The link element attached to the "welcome to contribute" wording on the [Build Tools page](https://webcompat.com/contributors/build-tools) links to a contribution page that has been moved. It appears that the change has been made in the master branch of the repo, but has not yet been pushed out to the live site.

**Comment by karlcow** [comment]
@WesleyBranton Thanks for spotting this.
Breakage part of #2192 
ping @mischah

**Comment by Regaddi** [comment]
Seems to be fixed now.

**Comment by karlcow** [comment]
Indeed. Thanks @Regaddi
