### ISSUE TITLE
some labels are not setable on webcompat.com

### ISSUE THREAD

**Issue by karlcow** [webcompat/webcompat.com#2482]
Go to any issues, try for example to set `type-bad-performance`. 
This is a regression compared to the previous version of webcompat.com.

**Comment by miketaylr** [comment]
@karlcow I was able to set this label, see https://github.com/webcompat/web-bugs/issues/2222#event-1679806809.

But I noticed that filtering doesn't really work... #2453?

**Comment by karlcow** [comment]
@miketaylr 

example:

![capture d ecran 2018-06-28 a 13 43 41](https://user-images.githubusercontent.com/505230/42013681-66553224-7ad9-11e8-8c80-306a51af0484.png)

#2453 is closed but the issue is not resolved.

**Comment by karlcow** [comment]
Ah and I don't see any type-* labels.

![capture d ecran 2018-06-28 a 13 45 44](https://user-images.githubusercontent.com/505230/42013742-a8ef009c-7ad9-11e8-8825-b735757f2115.png)

**Comment by miketaylr** [comment]
cc @laghee, in case you need a medium sized bug to work on when you're tired of thinking about dashboards. :)

**Comment by miketaylr** [comment]
@karlcow when I look at https://staging.webcompat.com/issues/1562, I'm able to filter for `type-` and see them when I scroll... but, indeed on webcompat.com production I don't.

<img width="376" alt="screen shot 2018-06-28 at 12 29 01 pm" src="https://user-images.githubusercontent.com/67283/42050557-ef5d8824-7ace-11e8-86e9-85a3da4b491f.png">

**Comment by laghee** [comment]
@karlcow @miketaylr I see that the `type-` labels aren't showing up (nor is `windows` ... something alphabetical?), but I can't reproduce filtering errors on labels that do appear. If you have an example, let me know.

I'm confused on which label prefixes are intended to be masked and which aren't. As far as I can tell, those that are currently masked on webcompat.com are:
```
browser-
os-
priority-
status-
```

But not masked is:
```
severity-
```
And these are completely missing, but present on GH (may not be exhaustive):
```
status-needsinfo-patrickkettner
status-needsinfo-sergiu
status-needsinfo-wisniewskit 
type-all-labels
windows
```

So where should `type-` fall here? Masked or unmasked?

**Comment by miketaylr** [comment]
`type-` should be unmasked, IMO.

`windows` just seems like a mistake -- it could either get deleted or renamed `os-windows`

**Comment by karlcow** [comment]
This should be fixed. The Regex is probably wrong.

**Comment by karlcow** [comment]
@miketaylr @laghee who is working on this?

**Comment by laghee** [comment]
OK, so my suspicion, which made sense to @karlcow, is that the problem here isn't in the filtering regex, but in the fact that we aren't handling pagination in our call to the GitHub api. Basically it looks like we're only fetching the first 100 labels in the repo. New issue filed (#2726).

**Comment by miketaylr** [comment]
thanks @laghee!

**Comment by karlcow** [comment]
I requalified some labels, and moved some, we are down to 122 (still too many), but better.
