### ISSUE TITLE
Website: redundant alternative text for SVGs, account dropdown incorrect ARIA, unnecessary role="button" on buttons

### ISSUE THREAD

**Issue by patrickhlauke** [webcompat/webcompat.com#2483]
(as discussed in person with @miketaylr the other week) the various SVGs used on the site have duplicate/triplicate alternative text. in general:

- if they're purely decorative, don't include any extra `<title>` or any text in the `<use></use>` elements, set `aria-hidden="true"` to be safe
- if they're part of a control (like a button) that already has a name/label (e.g. text content, an existing `aria-label`, or similar) they're decorative, so see above

while looking over this issue, I also stumbled across a few other things:

- a few invalid `aria-role="hide"` attributes?
- redundant `role="button"` on `<button>` elements
- `aria-pressed` is used for the account dropdown in the header. but it's then updated (true/false) not on the button itself, but its parent `<li>` element by the script. also, `aria-expanded` is probably more appropriate.

**Comment by miketaylr** [comment]
Fixed by https://github.com/webcompat/webcompat.com/commit/958bac4e5b8565a769ad5539f10bd1139b8b5467.

❤️
