### ISSUE TITLE
Put checked labels at the start of the label editor

### ISSUE THREAD

**Issue by karlcow** [webcompat/webcompat.com#2505]
When a bug has labels, for example:

<img width="321" alt="capture d ecran 2018-06-19 a 09 03 10" src="https://user-images.githubusercontent.com/505230/41568271-b508f3ba-739f-11e8-9a04-f5b606f11339.png">

And we choose to modify a label, the checked labels are not at the start of the list

<img width="337" alt="capture d ecran 2018-06-19 a 09 03 02" src="https://user-images.githubusercontent.com/505230/41568297-d6ade28c-739f-11e8-9e73-aa67d5967bd4.png">

**Comment by Regaddi** [comment]
I think we will need to swap out the checkboxes for custom styled ones.
This way we could restructure the HTML to take advantage of the `:checked + label` selector and re-order the checked labels to the top of the list (with the `order` attribute).

We can simply use the `BALLOT BOX` ☐ and `BALLOT BOX WITH CHECK` ☑︎ Unicode character as a first draft. Maybe we want to have some webcompy-fancy-custom-styling afterwards.
I'll push a PR in a minute, let's discuss it there 😄

**Comment by miketaylr** [comment]
Can this be closed now @Regaddi?

**Comment by karlcow** [comment]
This part is working but it broke the milestones.
