### ISSUE TITLE
Add-ons for Edge (?)

### ISSUE THREAD

**Issue by karlcow** [webcompat/webcompat.com#251]
Maybe the @TheWebJustWorks team would be interested to create an add-on for InternetExplorer so that it could be added to a list of addons for the site. The top link where there is currently add-on for firefox would become a link to a page proposing the users to install an add-on for their own browsers.

http://windows.microsoft.com/en-US/internet-explorer/manage-add-ons#ie=ie-11

**Comment by miketaylr** [comment]
If Edge supports an addon, we want this.

**Comment by miketaylr** [comment]
Let's close this and when they annouce support for add-ons in Edge, we can open an issue in the https://github.com/webcompat/webcompat-reporter-extensions repo.
