### ISSUE TITLE
Sort option becomes misaligned when the text has longer size

### ISSUE THREAD

**Issue by softvision-oana-arbuzov** [webcompat/webcompat.com#2512]
URL: https://webcompat.com/ and https://staging.webcompat.com 
Browser / Version: Firefox Nightly 62.0a1 (2018-06-19) , Chrome 67.0.3396.87
Operating System: Windows 10 Pro

**Steps to Reproduce:**
    1. Navigate to https://webcompat.com/issues?page=1&per_page=50&state=open&stage=all&sort=created&direction=desc 
    2. Click “Sort” button.
    3. Select one of the sorting options that has longer text size (e.g. “Most Commented”).
    4. Observe option alignment.
       
**Expected Behavior:**
Option is correctly aligned (on the same position with the rest of the top bar action buttons).

**Actual Behavior:**
Option is misaligned.

**Note**
    1. Screenshot attached.
    2. Affected area:
```html
<button type="button" class="button js-Dropdown-toggle">
	<span class="js-Dropdown-label">
        Most Commented
      </span>
	<svg class="icon nav-icon" viewBox="0 0 30 30" role="presentation" aria-hidden="true">
		<use xlink:href="#svg-chevron-right"></use>
	</svg>
</button>
```

![image](https://user-images.githubusercontent.com/12184325/41658465-17414bae-749f-11e8-930b-845c3baea19d.png)
        
**Watchers:**
@softvision-sergiulogigan
@softvision-oana-arbuzov

sv;

**Comment by zoepage** [comment]
@Regaddi wanna grab that one? :)
