### ISSUE TITLE
Update tests.md for changes to browser testing and outdated links

### ISSUE THREAD

**Issue by laghee** [webcompat/webcompat.com#2514]
To be fixed:

- "See dev env setup" link under [Functional Tests](https://github.com/webcompat/webcompat.com/blob/31db9c976d5824abd079568a1bce216b4656a598/docs/tests.md#functional-tests) is dead
- Text after `npm test` command  contradicts new headless browser default: 

> ...you should see the browser open and various pages appear and disappear automatically for a minute or two. The tests are complete when the browser window closes...

- Testing Flask link under [Python Unit Tests](https://github.com/webcompat/webcompat.com/blob/31db9c976d5824abd079568a1bce216b4656a598/docs/tests.md#python-unit-tests) returns a 404
- The Intern wiki has been killed (Intern claims it's been "moved" to the regular docs, but in my experience their corresponding links are almost always wrong, and much of that sometimes extra information appears to be simply lost 🙄 ) so all the links under [JS Functional Tests](https://github.com/webcompat/webcompat.com/blob/31db9c976d5824abd079568a1bce216b4656a598/docs/tests.md#js-functional-tests) should be updated to point to the updated-yet-not-always-copiously-detailed [docs](https://theintern.io/docs.html#Intern/4/docs/README.md)

**Comment by Anushi1998** [comment]
@laghee @miketaylr 

- `See dev env setup` link under Functional Tests is resolved by #2590 
- Text after npm test command contradicts new headless browser default:
What should I add for that?

**Comment by laghee** [comment]
Hi, @Anushi1998 -- thanks for working on this! Have you tried running the tests? That would give you the best idea of what actually happens. Basically you get a little spinny progress widget that counts off each test with a check mark for passing or an `x` for failing, first in Firefox, then in Chrome:

<img width="504" alt="screenshot 2018-09-29 13 04 45" src="https://user-images.githubusercontent.com/20972610/46250123-e82ea480-c3e8-11e8-8b06-8fe05cc567aa.png">

When it's done, you get a full test report:

<img width="983" alt="screenshot 2018-09-29 13 10 13" src="https://user-images.githubusercontent.com/20972610/46250135-275cf580-c3e9-11e8-9980-2c9fea42332a.png">


So on line 92, where it says:

> Shortly after running this command, you should see the browser open and various pages appear and disappear automatically for a minute or two. The tests are complete when the browser window closes and you see a report of how many passed or failed in the terminal window that you ran the `intern-runner` command in.

I would just change to something like "Shortly after running this command, a progress indicator should appear in the terminal window and spin through each functional test in Firefox and then in Chrome. When all the tests complete, you'll see the final report of passes and failures in the window."

**Also:** Two more things in the line below I just noticed -- **1)** "seperate" is the wrong spelling (should be "sep**a**rate") and  **2)** I think we should add a comma between "server" and "with" so it's clear that this is not the command to start the server:

> You can also run the functional tests as well as the python tests in a **seperate** tab, after starting the server **[add comma]** with:
