### ISSUE TITLE
The “Report Site Issue” extension icon is smaller on Chrome than on Firefox

### ISSUE THREAD

**Issue by softvision-sergiulogigan** [webcompat/webcompat.com#2541]
**Prerequisites**
1. Webcompat Reporter add-on must be installed on Firefox.
2. Webcompat Reporter extension must be installed on Chrome.

**Steps to Reproduce**
1. Open Chrome. 
2. Navigate to any website (e.g. http://www.bbc.co.uk/bbcfilms/catalogue).
3. Observe the “Report Site Issue" extension icon from top right corner.

**Expected Behavior:**
The “Report Site Issue” icon has the same size as on Firefox.
 
**Actual Behavior:**
The “Report Site Issue” icon is smaller than the one on Firefox.

**Note:**
1. Screenshot attached.

**Watchers:**
@softvision-sergiulogigan
@softvision-oana-arbuzov

sv; 
[![Screenshot Description](https://staging.webcompat.com/uploads/2018/7/255f658b-7ff5-48b4-af5a-87a8726e0ec6-thumb.jpg)](https://staging.webcompat.com/uploads/2018/7/255f658b-7ff5-48b4-af5a-87a8726e0ec6.jpg)

**Comment by miketaylr** [comment]
That's weird!

**Comment by miketaylr** [comment]
Let's close in favor of the addon repo bug I filed.
