### ISSUE TITLE
The “State” drop-down menu`s text is misaligned

### ISSUE THREAD

**Issue by softvision-oana-arbuzov** [webcompat/webcompat.com#2543]
**URL**: https://webcompat.com/dashboard/triage

**Browser / Version**: Chrome 67.0.3396.99
**Operating System**: Windows 10
**Tested Another Browser**: Yes

**Problem type**: Design is broken

**Steps to Reproduce**:
1. Navigate to https://webcompat.com/dashboard/triage 
2. Observe the “State” drop-down menu (e.g. "48+ hours").

**Expected Behavior:**
The “State” drop-down menu`s text is centered.
 
**Actual Behavior:**
The “State” drop-down menu`s text is misaligned.

**Notes:**
1. Not reproducible on Firefox Release 61.0 and Firefox Nightly 63.0a1 (2018-07-04).
2. Screenshot attached.

**Affected area**
```html
<select class="wc-Filter-select" name="state" id="js-Filter-state">
	<option value="priority" selected="selected">⏰ 48+ hours</option>
	<option value="needsinfo">🛎 Needsinfo</option>
</select>
```

**Watchers:**
@softvision-sergiulogigan
@softvision-oana-arbuzov

sv;

[![Screenshot Description](https://staging.webcompat.com/uploads/2018/7/1ab2d7c1-bbfc-4c56-af56-f6b74e3daa5e-thumb.jpg)](https://staging.webcompat.com/uploads/2018/7/1ab2d7c1-bbfc-4c56-af56-f6b74e3daa5e.jpg)

**Comment by miketaylr** [comment]
I wonder if Chrome has issues with Emoji in `<option>`.

**Comment by karlcow** [comment]
Not this one :) https://nicolas-hoizey.com/2017/10/chrome-fails-showing-big-emojis.html
but found it quite interesting. https://bugs.chromium.org/p/chromium/issues/detail?id=719648#c13

select (firefox left, Chrome right)
<img width="677" alt="capture d ecran 2018-07-06 a 09 31 44" src="https://user-images.githubusercontent.com/505230/42354102-73d612e8-80ff-11e8-975e-4c00696acdae.png">

option (firefox left, chrome right)
<img width="677" alt="capture d ecran 2018-07-06 a 09 32 34" src="https://user-images.githubusercontent.com/505230/42354107-93cf6838-80ff-11e8-82d3-07ef810c53ca.png">

**Comment by karlcow** [comment]
hmmm simple test (firefox left, chrome right)
https://codepen.io/webcompat/pen/oyrzwo
<img width="499" alt="capture d ecran 2018-07-06 a 09 45 20" src="https://user-images.githubusercontent.com/505230/42354371-5700ecf4-8101-11e8-8428-bde98629b606.png">

**Comment by karlcow** [comment]
Added variability to the test.

<img width="704" alt="capture d ecran 2018-07-06 a 09 57 20" src="https://user-images.githubusercontent.com/505230/42354620-06742ac4-8103-11e8-9613-428ea268c10b.png">

**Comment by karlcow** [comment]
Maybe related to https://bugs.chromium.org/p/chromium/issues/detail?id=777201
I wonder if @jfkthame knows what is happening.

For example the div example with the outline seems more logical in chrome, but the option alignment seems more logical… in Firefox. Life!

**Comment by magsout** [comment]
I'm going to close this issue, because there is no dashboard on webcompat.com
