### ISSUE TITLE
Typo in addons template for opera

### ISSUE THREAD

**Issue by laghee** [webcompat/webcompat.com#2547]
[There's a minor typo in the class attribute for the opera addon:](https://github.com/webcompat/webcompat.com/blob/958bac4e5b8565a769ad5539f10bd1139b8b5467/webcompat/templates/nav/addon-links.html#L34)

<img width="369" alt="screenshot 2018-07-10 18 54 50" src="https://user-images.githubusercontent.com/20972610/42525176-c60337aa-8472-11e8-9753-72603157f472.png">

**Comment by suhailsinghbains** [comment]
Hi, can I please be assigned this issue?
Would love to fix it.

**Comment by suhailsinghbains** [comment]
I had done the required changes locally, but, couldn't run the project & test it for myself.
I will test it first, I think there was an issue with my PC.
Will update you soon! And yes, thanks for the links & the specific code line.
