### ISSUE TITLE
Milestone checkmarks are missing in dropdown

### ISSUE THREAD

**Issue by laghee** [webcompat/webcompat.com#2554]
There's something wonky with the milestone selector dropdown in the issue views. I would expect the dropdown menu to display the selected status as being checked (similar to how labels work), but in reality there's no indication whatsoever of the current status. At least not beyond the displayed tag at the top of the sidebar (which you can't see once you click in the editor because the whole sidebar scrolls up):

<img width="297" alt="screenshot 2018-07-12 21 05 21" src="https://user-images.githubusercontent.com/20972610/42653965-51d8092c-8617-11e8-9273-719967482069.png">

Trying to change a milestone is confusing because there's no visual feedback (other than a brief blue outline) until you click outside the menu (this gif is super long and slow for some reason -- converted from a .mov ... clearly need a better screen capture method 🤓 ):

![milestones](https://user-images.githubusercontent.com/20972610/42654248-512a60d2-8618-11e8-9bcf-511ce09d0606.gif)

(**Edited to add:** I'm assuming this has to do with pr #2521 and how we changed checkmark visibility.)
Perhaps this could be solved by implementing #2275 ? I don't think it matters **what** shows up in the box as long as something does ... maybe even a radio-selector-🐝 ??

( **Also, even while logged in on webcompat.com, the change shows up as being performed by the bot instead of me on github. That might be by design, though?)

**Comment by magsout** [comment]
@laghee yes, it's a bug, but it's fixed with this PR https://github.com/webcompat/webcompat.com/pull/2539 but not deploy yet.

**Comment by magsout** [comment]
@laghee 
>**Also, even while logged in on webcompat.com, the change shows up as  being performed by the bot instead of me on github. That might be by  design, though?)
--

It's normal, it's the current behavior. Every changes about milestones or status are made by the bot, not the user itself

**Comment by laghee** [comment]
>It's normal, it's the current behavior. Every changes about milestones or status are made by the bot, not the user itself

Thanks! Good to know.

>it's a bug, but it's fixed with this PR #2539 but not deploy yet.

OK, that's good then. I thought staging was from master, though? (It's there too.)

**Comment by karlcow** [comment]
@laghee staging is manually deployed. Not from master automagically like webcompat-metrics :)

**Comment by laghee** [comment]
@karlcow Aha, OK, so everything deployed is manual. ✔️  Got it now! Thx!

**Comment by laghee** [comment]
Closing as works since deployment v12.1.0 🎉
