### ISSUE TITLE
figure out a way to identify firefox reality reporters

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat.com#2560]
right now they have a built-in reporter that uses the following link: 

https://webcompat.com/issues/new?src=web-fxr

We should add a label, or parse their UA string.

**Comment by miketaylr** [comment]
(i've ordered a device to test this with, should be able to know more next week)

**Comment by karlcow** [comment]
A bit more context for understanding this issue https://mixedreality.mozilla.org/

and 

>We believe that the future of the web will be heavily intertwined with virtual and augmented reality, and that future will live through browsers. That’s why we’re building Firefox Reality, a new kind of web browser that has been designed from the ground up to work on stand-alone virtual and augmented reality (or mixed reality) headsets.

— https://blog.mozilla.org/blog/2018/04/03/mozilla-brings-firefox-augmented-virtual-reality/
