### ISSUE TITLE
Unclear status-change instructions at /contributors/reproduce-bug

### ISSUE THREAD

**Issue by laghee** [webcompat/webcompat.com#2563]
It sounds like we're telling people to change to needstriage status **after** they've triaged a bug they can reproduce. `NEEDSTRIAGE` here should be changed to `NEEDSDIAGNOSIS`:

<img width="884" alt="screenshot 2018-08-03 13 41 40" src="https://user-images.githubusercontent.com/20972610/43641275-48445538-9723-11e8-95a5-a3c059e91d30.png">

https://github.com/webcompat/webcompat.com/blob/42781cc3a673b622b9fd0d5b07f6250895160a4b/webcompat/templates/contributors/reproduce-bug.html#L104

Also, in the second-to-last sentence here ("If the issue was reported anonymous..."), `anonymous` should be changed to `anonymously`:
https://github.com/webcompat/webcompat.com/blob/42781cc3a673b622b9fd0d5b07f6250895160a4b/webcompat/templates/contributors/reproduce-bug.html#L54

**Comment by hritvi** [comment]
@laghee If it is still open may I work on this?

**Comment by laghee** [comment]
Hi, @hritvi! We'd be happy to have you work on this, but if you're an Outreachy applicant, it would be great if you could look at issue #2579 first.

If you run into any bugs setting up a local environment, feel free to file them!
