### ISSUE TITLE
"Report via GitHub" buttons leads to homepage without submitting the issue

### ISSUE THREAD

**Issue by reinhart1010** [webcompat/webcompat.com#2564]
This issue affects the main Webcompat site. I have tested it against staging server while reporting webcompat/webcompat-tests#1637 on both sites.

**Steps to Reproduce**:
1. Log in to your GitHub account, and do **not** log in to the Webcompat site.
2. Try add a new issue and tap on **Report via GitHub**

Here, the button leads to the home page without having the issue submitted.

**Comment by miketaylr** [comment]
Yikes, thanks for the report @reinhart1010!

I just reproduced, but haven't investigated... I would guess something unexpected happens when we go to GitHub for an oauth exchange, and it's already happened?

I'm going to reset all tokens for the staging account to test that theory.

**Comment by miketaylr** [comment]
Hm, no. Still broken.

Actually... I think this might be fallout from https://github.com/organizations/webcompat/settings/applications/111644

**Comment by reinhart1010** [comment]
There was another issue where I cannot log in straight from the homepage (production). This was also fixed, too.
