### ISSUE TITLE
(Samsung Internet) White gap visible in homepage

### ISSUE THREAD

**Issue by reinhart1010** [webcompat/webcompat.com#2576]
Tested on Samsung Intermet 7.4 (Chrome 59), Android 7.0.

![screenshot_20180909-180051](https://user-images.githubusercontent.com/17312341/45263812-06912800-b45b-11e8-801d-96db4af5b6ed.png)

**Comment by reinhart1010** [comment]
This one is still reproducible, even on the Staging version. When will this change be applied?

**Comment by magsout** [comment]
@reinhart1010 oups... re open the issue. Thanks
