### ISSUE TITLE
Add /tmp to deploy.ignore

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat.com#2585]
Otherwise we end up deploying local logs and CSP reports.

https://github.com/webcompat/webcompat.com/blob/master/config/deploy.ignore

**Comment by suhailsinghbains** [comment]
Hi @miketaylr 
I would love to work on this. I'll send a PR soon, if you assign the bug to me please.

**Comment by karlcow** [comment]
@suhailsinghbains it seems @shristit already submitted a PR in between the time us being aware of your message and the PR.

**Comment by karlcow** [comment]
@suhailsinghbains Please see if you are interested in contributing more https://github.com/webcompat/webcompat.com/labels/good%20first%20bug
@shristit Make sure next time to check if nobody has requested to work on something before doing a PR.

Make sure to read carefully https://github.com/webcompat/webcompat.com/blob/master/docs/pr-coding-guidelines.md

Thanks to both of you.
