### ISSUE TITLE
The parameter subpath is not passed to the route

### ISSUE THREAD

**Issue by karlcow** [webcompat/webcompat.com#2587]
Here in views.py

https://github.com/webcompat/webcompat.com/blob/39da3a084bd3d5001dd962a9600674bfd15766e3/webcompat/views.py#L469-L471

we have forgotten to pass the parameter to the function. It should be

```python
@app.route('/.well-known/<path:subpath>')
@cache_policy(private=False, uri_max_age=31104000, must_revalidate=False)
def wellknown(subpath):
```

**Comment by karlcow** [comment]
1. Add the subpath to the function
2. Create a test in https://github.com/webcompat/webcompat.com/blob/master/tests/unit/test_rendering.py to check we get the right content.

**Comment by kritisingh1** [comment]
Hi @karlcow may I work on this issue? Thanks!

**Comment by karlcow** [comment]
@kritisingh1 Yes sure. :) 

There is [documentation](https://github.com/webcompat/webcompat.com/blob/master/.github/CONTRIBUTING.md)  covering all the initial steps for starting with the project and starting with the first pull request. 

If you are stuck somewhere, the document also includes information on how and where to get help!
