### ISSUE TITLE
label + milestone editor overflow issues

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat.com#2597]
I swear I had reported this elsewhere, but I can't seem to find it.

Clicking on the label or milestone editor results in awkward overflow issues. We should just make them behave like GitHub currently -- that is, they show "float" above all other content while open.

<img width="424" alt="screen shot 2018-09-24 at 7 01 08 pm" src="https://user-images.githubusercontent.com/67283/45985533-46940580-c02c-11e8-928f-ac71eac43cf7.png">

**Comment by miketaylr** [comment]
One use case where this is pretty crappy:

if you try to filter on `type-`, and there's something you need below the overflow, I'm not even sure how to get it without typing it out entirely.

**Comment by vaishnavipamulapati** [comment]
I think this is happening as a result of the `overflow-y` style applied to the `label-box` [class](https://github.com/webcompat/webcompat.com/blob/master/webcompat/static/css/src/label-box.css#L4).
We could probably just remove that and have it render outside the box.
It would look like this:
![image](https://user-images.githubusercontent.com/29792199/46056044-6c282880-c16c-11e8-8d16-03d3670664ef.png)

**Comment by karlcow** [comment]
@magsout will check how to pull out the editor widget out of the aside context. It requires a bit of UX work.

**Comment by magsout** [comment]
@miketaylr @karlcow 

I tried something:

![capture d ecran 2018-10-01 a 16 33 15](https://user-images.githubusercontent.com/1997108/46295187-bf004680-c597-11e8-9b77-e557ed80a545.png)

**Comment by karlcow** [comment]
@magsout Yes. We are getting  closer, I would not do such a strong opacity in the background.
