### ISSUE TITLE
Figure out why GA shows no data

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat.com#2599]
Maybe we broke this?

**Comment by miketaylr** [comment]
hey look, we had one user last tuesday!

![screen shot 2018-09-25 at 12 27 36 pm](https://user-images.githubusercontent.com/67283/46031428-71c73500-c0be-11e8-975f-f51d7ef61a0a.png)

(i wonder if i used the wrong logic in #2300... something to investigate)

**Comment by karlcow** [comment]
I'm still in the mood of getting rid of GA. :)
but it's probably worth understanding what is not working.

**Comment by miketaylr** [comment]
> I'm still in the mood of getting rid of GA. :)

@karlcow wins the award for "most consistent values" 💯 ⭐️

**Comment by miketaylr** [comment]
Ah, user error here. There are 2 accounts in Google Analytics (webcompat.com and webcompat.com-moz). I don't remember why...

So this is working.
