### ISSUE TITLE
Focus search input when the search icon is pressed (and search input is empty)

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat.com#2610]

**Comment by meetmuhd** [comment]
This problem (no focus in search input after search icon is pressed) still persists for me, but I noticed this issue which first identified it has been closed. I am interested in attempting a fix if it is confirmed as worthy of revisiting, please. @magsout @miketaylr

**Comment by miketaylr** [comment]
@meetmuhd yes please! It's probably good to file a new issue and describe steps to reproduce, etc. then of course we would love a patch. :)

**Comment by miketaylr** [comment]
(oops)
