### ISSUE TITLE
Move text messages for certain routes into config

### ISSUE THREAD

**Issue by karlcow** [webcompat/webcompat.com#2612]
That sounds more logical to move the text messages into the config. 
Example: https://github.com/webcompat/webcompat.com/blob/dad37868fa082dc7a908f28b3a7399d4d572a4d0/webcompat/views.py#L447-L450

like we did for `/.well-known/security.txt`

**Comment by Arasador** [comment]
I would like to work on this, since it seems pretty straight forward. A good first bug.

**Comment by karlcow** [comment]
@Arasador please do! Thanks.
 
There is [documentation](https://github.com/webcompat/webcompat.com/blob/master/.github/CONTRIBUTING.md)  covering all the initial steps for starting with the project and starting with the first pull request. 

If you are blocked somewhere, the document also includes information on how and where to get help! You can also ping me here in the comments.

**Comment by Auralcat** [comment]
@Arasador are you working in this issue? I'd like to help if possible.
