### ISSUE TITLE
Flag issues which are spam

### ISSUE THREAD

**Issue by karlcow** [webcompat/webcompat.com#2627]
When we identify an issue which is spam, we could flag it with a label. `type-spam` or something

This would help us to adopt different strategy when displaying issues to users, when returning search results, etc.

To discuss. Opinion? @softvision-oana-arbuzov @softvision-sergiulogigan @adamopenweb @miketaylr @magsout

**Comment by softvision-oana-arbuzov** [comment]
@karlcow we could do that. 
Should we add the label to all the issues reported as:
- scam
- virus
- phishing
- deceptive site
- adware 
- random redirect 
- random typed letters
- invites to different blogs/sites
- hacking.

**Comment by miketaylr** [comment]
> Should we start adding the label to all the issues reported as:

I think those are different types of issues -- I believe @karlcow is describing an actual spam issue: the user is trying to abuse the site or report nonsense. 

The other types of issues (where *they* try to report spam or scams they have encountered)... it would be good to come up with a better solution for how to delete those, but I wouldn't classify them as spam (unless it got abusive, etc.)

**Comment by karlcow** [comment]
Created! thanks
https://github.com/webcompat/web-bugs/labels/type-spam
