### ISSUE TITLE
Add greenkeeper for dependencies and devDependencies

### ISSUE THREAD

**Issue by magsout** [webcompat/webcompat.com#2633]
https://greenkeeper.io/ like on metrics repo https://github.com/webcompat/webcompat-metrics-client/pulls?q=is%3Apr+is%3Aclosed+label%3Agreenkeeper

**Comment by miketaylr** [comment]
@magsout let's do it.

**Comment by karlcow** [comment]
This is done. I guess. We receive the pull requests ;)
