### ISSUE TITLE
CircleCI not running for PRs from forks

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat.com#2637]
@magsout I wonder if you know how to fix this. 

In https://circleci.com/gh/webcompat/webcompat.com/edit#advanced-settings, we have "Build Forked Pull Requests" enabled, but when Karl opened a PR (see the recent test one), we don't see his build status.

I'm confused... have you seen this before?

**Comment by miketaylr** [comment]
But he just pushed a branch to the repo and made a PR (not from a fork), and it's running: https://github.com/webcompat/webcompat.com/pull/2638

**Comment by miketaylr** [comment]
Ah, it seems you have to enable shared secrets for forks builds to run. Hmm. It says it's dangerous, but I'm not sure what the attack vector is.

**Comment by miketaylr** [comment]
We're coming up with a plan.

**Comment by miketaylr** [comment]
https://github.com/webcompat/devops/issues/33

**Comment by magsout** [comment]
@miketaylr if you watch this PR #2648 everything is fine? the test passed and circleci ran correctly.

**Comment by miketaylr** [comment]
> @miketaylr if you watch this PR #2648 everything is fine? the test passed and circleci ran correctly.

yep!
