### ISSUE TITLE
Documentation directory in the hierarchy

### ISSUE THREAD

**Issue by karlcow** [webcompat/webcompat.com#264]
Because of the issue #261 and a few others in the recent weeks on documenting our projects. I was thinking that we could consolidate a bit what we are doing. There are **many ways** of writing documentations. I don't want that much to argue about the methodology than trying to see if it sounds sane enough. So I need to input of @tagawa @calexity @magsout about it.
1. Creating a /docs/
2. Consolidating some documentation found elsewhere in their own chapters under docs/
   1. Coding Style. See also the [flake 8 comment](https://github.com/webcompat/webcompat.com/pull/265#issuecomment-55747481)
   2. [Style guidelines](https://github.com/webcompat/webcompat.com#design-chart-guidelines)
   3. [Server setup](https://github.com/webcompat/webcompat.com/blob/master/CONTRIBUTING.md#working-environment-setup)
   4. [Running Tests](https://github.com/webcompat/webcompat.com/blob/master/CONTRIBUTING.md#running-tests)
3. Adding missing docs
   1. Architecture of WebCompat
   2. Description of the different functions with variables.
   3. Writing unit tests
   4. Writing functional tests
   5. Nginx configuration
   6. Maintaining the CSS.
   7. etc.

What kind of docs do we want something ala [readthedocs](https://readthedocs.org/) or some loosely connected files with different styles.

**Comment by karlcow** [comment]
I have done cleaning in #436 for the labels. But subsequent commits will be here.

**Comment by magsout** [comment]
just testing about auto genereted style guide:

![capture d ecran 2015-05-23 a 21 29 16](https://cloud.githubusercontent.com/assets/1997108/7785524/b47963ac-0193-11e5-80b8-6f679d02bad6.png)

**Comment by calexity** [comment]
Wow this looks helpful and nicely laid out @magsout

**Comment by dshgna** [comment]
> This tutorial about Sphinx+Github is relevant to this issue. Basically readthedocs is a service which is using Sphinx a system of templating for writing docs and host it on its server. This tutorial explains how to do it without readthedocs.

@karlcow It's sometime after the initial discussion, but I'd be very much interested in working on this.

**Comment by karlcow** [comment]
@dshgna given that I have not dedicated enough time to this. That would be great. But it's a long term project. It will take time. But yes please do and we can help you when needed. And if there are other priorities before you finish it's ok. Someone else will take over. 

Maybe to make it easier for you and make the review process easier. I would encourage you to tackle each section with its own issue. and we make small progress step by step. So something along:

1. Open an issue about the section you want to write as a doc with a link to this bug number.
2. Edit/Commit dance
3. Pull Request 
4. Next go to 1. and Repeat for the next section.

I could modify the first comment to make a task list, Or maybe we create a Milestone for documentation. 
Maybe a Milestone would be better. 

ok done.
https://github.com/webcompat/webcompat.com/milestones/Documentation%20Reorganization

Add new issues to this Documentation Reorganization Milestone

**Comment by dshgna** [comment]
Thanks @karlcow 
@magsout Need to coordinate a bit with you here as the style guide is currently on gh-pages, Perhaps it would be okay to move it to a different page style.html? I'll try this out on my branch and get back.

**Comment by miketaylr** [comment]
Unassigning @karlcow because he doesn't have the bandwidth to work on this right now.

**Comment by karlcow** [comment]
I had started this in the past
http://web-compatibility-app-development.readthedocs.io/en/latest/
I can transfer the ownership of everything on this.

**Comment by zoepage** [comment]
@karlcow haven't seen this before. :) It's helpful and something we should add more information to it. Maybe we'll find a way to automate parts of the documentation (like packages or API documentation) to keep it up-to-date and reduce work?

**Comment by miketaylr** [comment]
Closing in favor of #1526.
