### ISSUE TITLE
New filed bugs don't get Milestone or Labels

### ISSUE THREAD

**Issue by softvision-sergiulogigan** [webcompat/webcompat.com#2644]
Starting with #19399 until #19427 (so far), newly logged bugs on webcompat.com did not get Milestone or Labels automatically.

![image](https://user-images.githubusercontent.com/16573771/46517697-2577b400-c879-11e8-9449-6d124339a89a.png)

**Comment by miketaylr** [comment]
oops. I will try to clean this up on Monday (in terms of milestone and labels), sorry for the extra work @softvision-sergiulogigan @softvision-oana-arbuzov.

I wonder what could be wrong...

**Comment by karlcow** [comment]
Same issue on staging. 
https://staging.webcompat.com/issues/1695
I'm opening an issue on devops.

**Comment by karlcow** [comment]
I added needstriage to 65 issues
https://github.com/webcompat/web-bugs/issues?q=is%3Aopen+is%3Aissue+milestone%3Aneedstriage

**Comment by karlcow** [comment]
In the process of being fixed.

**Comment by karlcow** [comment]
This is fixed! https://webcompat.com/issues/19519
