### ISSUE TITLE
Blacklisted Domains not working

### ISSUE THREAD

**Issue by Anushi1998** [webcompat/webcompat.com#2650]
[`is_blacklisted_domain`](https://github.com/webcompat/webcompat.com/blob/master/webcompat/helpers.py#L581-L587) will not return `true` if we call (say) http://cityweb.de. Moreover you always need to append `http` or `https` because otherwise Site URL would say `A valid URL is required`.

![image](https://user-images.githubusercontent.com/16550254/46910786-c9a7cd80-ceff-11e8-81cf-dae5ce885580.png)

A possible fix would be to extract domain from url and call `is_blacklisted_domain` with that instead of passing complete url (which is what I think the variable names also supposed to suggest). One more thing we can do is instead of checking hard we can use Regex because I think there is a less chance (say) cityweb.de will occur in some other URL.

Looking for further suggestions

@miketaylr @karlcow @wisniewskit

**Comment by wisniewskit** [comment]
My two cents would be to validate the URL somewhere using [urlparse](https://docs.python.org/2/library/urlparse.html), and then pass `parseResults.netloc` into `is_blacklisted_domain`. But I'm not sure what we want to do with "invalid" URLs, as I haven't worked on this code.

**Comment by Anushi1998** [comment]
@wisniewskit Aren't we supposed to block them (from creating an issue with this URL) and return back to `index` page? Please let me know if there is some other thing we are doing also

**Comment by wisniewskit** [comment]
No, I think that's the entire point of the blacklist.. so if it's not enough to just fix things so that only the domain is being passed into that function (rather than the entire URL), then we'll have more work to do.

**Comment by Anushi1998** [comment]
@wisniewskit Okay. Thanks :')

**Comment by karlcow** [comment]
That's my mistake. I regressed it! Previously.
https://github.com/webcompat/webcompat.com/blob/5339d389da58da561b91bfec5e6da30d7322af2d/webcompat/views.py#L214-L216

**Comment by Anushi1998** [comment]
@karlcow Should I make changes by looking into this commit ?

**Comment by karlcow** [comment]
not necessary. :) The suggestion from @wisniewskit is good.

**Comment by karlcow** [comment]
@Anushi1998 Though we need to double check if form['url'] is always an URL. :)

**Comment by Anushi1998** [comment]
Okay, cool! I will make the changes and submit them :)

**Comment by Anushi1998** [comment]
@karlcow Anything that starts from `http://` and `https://` is [valid URL](https://github.com/webcompat/webcompat.com/blob/master/webcompat/static/js/lib/bugform.js#L313) on Site URL. Can you please be specific about how can I double check this thing?

Moreover why the url starting from other schemes are considered invalid?

**Comment by karlcow** [comment]
@Anushi1998 here an example. I entered `http:// 2650.example.com` (notice the space before 2650)
https://github.com/webcompat/webcompat-tests/issues/1706.

```python
>>> import urlparse
>>> form_url = 'http:// 2650.example.com'
>>> urlparse.urlparse(form_url)
ParseResult(scheme='http', netloc=' 2650.example.com', path='', params='', query='', fragment='')
>>> urlparse.urlparse(form_url).netloc
' 2650.example.com'
```

This is probably a mistake on our side that we allow it in the first place in the JS. I opened #2662

**Comment by karlcow** [comment]
@Anushi1998 
> Moreover why the url starting from other schemes are considered invalid?

because we are interested by **websites** compatibility issues and we are addressing the most generic cases. People report issues about things not working when they are interpreted by the browser, so `http`.
