### ISSUE TITLE
Update dev-env-setup.md to reflect the current reality

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat.com#2651]
The stuff around secrets.py needs to be updated, quite a bit changed in the past few weeks. For example...

> Add the right values to the repo issues URIs. ISSUES_REPO_URI = "<user>/<repo>/issues". For example, miketaylr's setup needs to say ISSUES_REPO_URI = "miketaylr/test-repo/issues"

**Comment by karlcow** [comment]
Yes I was even thinking if we should add a special checking/validation script to send a message in the console when people are starting the project. Something along "Hey it seems your configuration is still based on the old model." At least for a little while.

**Comment by miketaylr** [comment]
> Something along "Hey it seems your configuration is still based on the old model." At least for a little while.

That would be cool.
