### ISSUE TITLE
[discussion] Add a few probot apps to web-bugs repo

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat.com#2654]
I plan on adding the following bots to our web bugs repo next week (or sooner, if no objections):

1. lock https://probot.github.io/apps/lock/

After 7 days (less??) of being closed, lock all issues with a (custom) message encouraging users to file a new bug. 

2. "no response" https://github.com/probot/no-response

When an issue has a "status-needsinfo" label and does not get a reply for 7 days, the bot will close the issue as incomplete, with a friendly message to add more info, or file a new bug.

If anyone has any objections, let's discuss them here.

**Comment by karlcow** [comment]
This probably creates a dependency on webcompat.com UI that we need to be careful about. When the issue is closed, we need to make sure that the form/button for comments are not accessible anymore. 
* We need to understand what are the interactions with labels and milestones too.

Some tests in 
* https://github.com/webcompat/webcompat-tests/issues/666
* https://webcompat.com/issues/666 

webcompat-bot reopened the issue when change the status.

**Comment by miketaylr** [comment]
> When the issue is closed, we need to make sure that the form/button for comments are not accessible anymore.

This should be pretty simple, there's a `locked` property we can reflect in the model.

**Comment by miketaylr** [comment]
See https://github.com/webcompat/webcompat.com/issues/2656

**Comment by Anushi1998** [comment]
@miketaylr This sounds interesting to me. Can I be of some help?

PS: I may need some time and I do not have any problem in case you do not consider me if this is urgent or requires some knowledge :-)

**Comment by miketaylr** [comment]
@Anushi1998 thanks! most of the work for setting up the bots requires admin access. when I dig into this later this week, if i see other bugs i can spin out for contributions, i'll ping you!

**Comment by Anushi1998** [comment]
@miketaylr Sure, thanks :)

**Comment by miketaylr** [comment]
I think we need to update the bot before we can land this, without much hacking around on our end: https://github.com/probot/no-response/issues/29

**Comment by miketaylr** [comment]
OK, no-response isn't interested in patches, so I forked it: https://github.com/miketaylr/no-response

<img width="790" alt="screen shot 2018-10-31 at 5 14 14 pm" src="https://user-images.githubusercontent.com/67283/47821936-740d5680-dd30-11e8-88e1-5848b1dae018.png">

Need to write the front-end parts, then we're good (I'm guessing just hide the comment widget if it's locked should be sufficient).

**Comment by miketaylr** [comment]
I'm gonna close this and open issues for each bot.

**Comment by karlcow** [comment]
@miketaylr What do you think about moving the no-response bot to the webcompat repo?

**Comment by miketaylr** [comment]
> @miketaylr What do you think about moving the no-response bot to the webcompat repo?

happy to move it over! will do.

**Comment by miketaylr** [comment]
> happy to move it over! will do.

OK, made the request. https://github.com/webcompat/no-response is a thing now.

**Comment by karlcow** [comment]
thanks.
