### ISSUE TITLE
Not all issues get Priority Labels automatically assigned

### ISSUE THREAD

**Issue by softvision-sergiulogigan** [webcompat/webcompat.com#2655]
Not all issues get a `priority-[something]` label

Example:
https://github.com/webcompat/web-bugs/issues/19723

![image](https://user-images.githubusercontent.com/16573771/47014830-0b30b680-d154-11e8-9b05-06ac96f6f8b7.png)

**Comment by miketaylr** [comment]
I wonder if gmail has ever gotten a priority label...

**Comment by miketaylr** [comment]
@karlcow can you take a look at some point? unsure if we broke this or what.

**Comment by karlcow** [comment]
https://github.com/webcompat/web-bugs/issues?utf8=%E2%9C%93&q=is%3Aissue+-label%3Apriority-critical+-label%3Apriority-normal+-label%3Apriority-important+

I don't think we broke anything, but I do wonder if the label assignment always work.

<img width="1024" alt="capture d ecran 2018-10-17 a 09 03 03" src="https://user-images.githubusercontent.com/505230/47054218-8d1fee80-d1eb-11e8-966e-6e7150af6936.png">

**Comment by karlcow** [comment]
<img width="1010" alt="capture d ecran 2018-10-17 a 09 05 25" src="https://user-images.githubusercontent.com/505230/47054262-d6703e00-d1eb-11e8-9ea1-2d7163901442.png">

Also… `gmail.com` never seems to receive a label.

https://github.com/webcompat/web-bugs/issues?utf8=%E2%9C%93&q=is%3Aissue+%27gmail+com%27+in%3Atitle

**Comment by karlcow** [comment]
Also if issues are not in the priority DB, they don't get assigned a label. 
This is not a dynamic process where we query each time Alexa (that would be expensive), we collect data from Alexa and compile a DB which is used to assess the priority.
https://github.com/webcompat/webcompat.com/blob/0974eefafe7273e8f0952a05427ad45506f8846b/webcompat/webhooks/helpers.py#L80-L97

**Comment by miketaylr** [comment]
It sounds like a non-issue. Thanks for investigating Karl.
