### ISSUE TITLE
Make console logs in browser configuration details easier to read

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat.com#2659]
Now that we have console logs coming in, we can think of ways to make them prettier.

<img width="1494" alt="screen shot 2018-10-16 at 4 27 47 pm" src="https://user-images.githubusercontent.com/67283/47048575-6e284a80-d160-11e8-8995-19c502a1ec3a.png">
<img width="1514" alt="screen shot 2018-10-16 at 4 28 14 pm" src="https://user-images.githubusercontent.com/67283/47048621-90ba6380-d160-11e8-9ae1-b258f756b679.png">

cf. https://github.com/webcompat/webcompat.com/pull/2658

**Comment by karlcow** [comment]
Almost there. #2670 is here to fix a couple of things. And then we can prettify.

**Comment by karlcow** [comment]
This is an example of a log as kept right now. I'm trying to understand a couple of things. 

Where the `console.log(` is coming from 

@wisniewskit As you worked on it, could you tell me?

```python
[u'[console.log(==== uploader chunkcheck: true ===) https://www.filemail.com/bundles/js/default?v=R1iSYgzt8XCQHg-EMwry4hVKE5504Mw8JlbomBZDl7o1:214:759]',
 u'[console.log(\tdefault mode: browser) https://www.filemail.com/bundles/js/default?v=R1iSYgzt8XCQHg-EMwry4hVKE5504Mw8JlbomBZDl7o1:211:12887]',
 u'[console.log(Instantiating FileInput...) https://www.filemail.com/bundles/js/default?v=R1iSYgzt8XCQHg-EMwry4hVKE5504Mw8JlbomBZDl7o1:211:12887]',
 u'[console.log(Trying runtime: html5) https://www.filemail.com/bundles/js/default?v=R1iSYgzt8XCQHg-EMwry4hVKE5504Mw8JlbomBZDl7o1:211:12887]',
 u'[console.log([object Object]) https://www.filemail.com/bundles/js/default?v=R1iSYgzt8XCQHg-EMwry4hVKE5504Mw8JlbomBZDl7o1:211:12887]',
 u'[console.log(\tdefault mode: browser) https://www.filemail.com/bundles/js/default?v=R1iSYgzt8XCQHg-EMwry4hVKE5504Mw8JlbomBZDl7o1:211:12887]',
 u'[console.log(\tselected mode: browser) https://www.filemail.com/bundles/js/default?v=R1iSYgzt8XCQHg-EMwry4hVKE5504Mw8JlbomBZDl7o1:211:12887]',
 u"[console.log(Runtime 'html5' initialized) https://www.filemail.com/bundles/js/default?v=R1iSYgzt8XCQHg-EMwry4hVKE5504Mw8JlbomBZDl7o1:211:12887]",
 u'[console.log(Instantiating FileDrop...) https://www.filemail.com/bundles/js/default?v=R1iSYgzt8XCQHg-EMwry4hVKE5504Mw8JlbomBZDl7o1:211:12887]',
 u'[console.log(Trying runtime: html5) https://www.filemail.com/bundles/js/default?v=R1iSYgzt8XCQHg-EMwry4hVKE5504Mw8JlbomBZDl7o1:211:12887]',
 u'[console.log([object Object]) https://www.filemail.com/bundles/js/default?v=R1iSYgzt8XCQHg-EMwry4hVKE5504Mw8JlbomBZDl7o1:211:12887]',
 u'[console.log(\tdefault mode: browser) https://www.filemail.com/bundles/js/default?v=R1iSYgzt8XCQHg-EMwry4hVKE5504Mw8JlbomBZDl7o1:211:12887]',
 u'[console.log(\tselected mode: browser) https://www.filemail.com/bundles/js/default?v=R1iSYgzt8XCQHg-EMwry4hVKE5504Mw8JlbomBZDl7o1:211:12887]',
 u"[console.log(Runtime 'html5' initialized) https://www.filemail.com/bundles/js/default?v=R1iSYgzt8XCQHg-EMwry4hVKE5504Mw8JlbomBZDl7o1:211:12887]",
 u'[console.log(Instantiating FileDrop...) https://www.filemail.com/bundles/js/default?v=R1iSYgzt8XCQHg-EMwry4hVKE5504Mw8JlbomBZDl7o1:211:12887]',
 u'[console.log(Trying runtime: html5) https://www.filemail.com/bundles/js/default?v=R1iSYgzt8XCQHg-EMwry4hVKE5504Mw8JlbomBZDl7o1:211:12887]',
 u'[console.log([object Object]) https://www.filemail.com/bundles/js/default?v=R1iSYgzt8XCQHg-EMwry4hVKE5504Mw8JlbomBZDl7o1:211:12887]',
 u'[console.log(\tdefault mode: browser) https://www.filemail.com/bundles/js/default?v=R1iSYgzt8XCQHg-EMwry4hVKE5504Mw8JlbomBZDl7o1:211:12887]',
 u'[console.log(\tselected mode: browser) https://www.filemail.com/bundles/js/default?v=R1iSYgzt8XCQHg-EMwry4hVKE5504Mw8JlbomBZDl7o1:211:12887]',
 u"[console.log(Runtime 'html5' initialized) https://www.filemail.com/bundles/js/default?v=R1iSYgzt8XCQHg-EMwry4hVKE5504Mw8JlbomBZDl7o1:211:12887]",
 u'[console.log(Instantiating FileDrop...) https://www.filemail.com/bundles/js/default?v=R1iSYgzt8XCQHg-EMwry4hVKE5504Mw8JlbomBZDl7o1:211:12887]',
 u'[console.log(Trying runtime: html5) https://www.filemail.com/bundles/js/default?v=R1iSYgzt8XCQHg-EMwry4hVKE5504Mw8JlbomBZDl7o1:211:12887]',
 u'[console.log([object Object]) https://www.filemail.com/bundles/js/default?v=R1iSYgzt8XCQHg-EMwry4hVKE5504Mw8JlbomBZDl7o1:211:12887]',
 u'[console.log(\tdefault mode: browser) https://www.filemail.com/bundles/js/default?v=R1iSYgzt8XCQHg-EMwry4hVKE5504Mw8JlbomBZDl7o1:211:12887]',
 u'[console.log(\tselected mode: browser) https://www.filemail.com/bundles/js/default?v=R1iSYgzt8XCQHg-EMwry4hVKE5504Mw8JlbomBZDl7o1:211:12887]',
 u"[console.log(Runtime 'html5' initialized) https://www.filemail.com/bundles/js/default?v=R1iSYgzt8XCQHg-EMwry4hVKE5504Mw8JlbomBZDl7o1:211:12887]",
 u'[console.log(Instantiating FileDrop...) https://www.filemail.com/bundles/js/default?v=R1iSYgzt8XCQHg-EMwry4hVKE5504Mw8JlbomBZDl7o1:211:12887]',
 u'[console.log(Trying runtime: html5) https://www.filemail.com/bundles/js/default?v=R1iSYgzt8XCQHg-EMwry4hVKE5504Mw8JlbomBZDl7o1:211:12887]',
 u'[console.log([object Object]) https://www.filemail.com/bundles/js/default?v=R1iSYgzt8XCQHg-EMwry4hVKE5504Mw8JlbomBZDl7o1:211:12887]',
 u'[console.log(\tdefault mode: browser) https://www.filemail.com/bundles/js/default?v=R1iSYgzt8XCQHg-EMwry4hVKE5504Mw8JlbomBZDl7o1:211:12887]',
 u'[console.log(\tselected mode: browser) https://www.filemail.com/bundles/js/default?v=R1iSYgzt8XCQHg-EMwry4hVKE5504Mw8JlbomBZDl7o1:211:12887]',
 u"[console.log(Runtime 'html5' initialized) https://www.filemail.com/bundles/js/default?v=R1iSYgzt8XCQHg-EMwry4hVKE5504Mw8JlbomBZDl7o1:211:12887]",
 u'[console.info(SoundManager V2.97a.20150601 (HTML5-only mode)) https://www.filemail.com/bundles/js/default?v=R1iSYgzt8XCQHg-EMwry4hVKE5504Mw8JlbomBZDl7o1:184:11563]',
 u'[console.info(SoundManager 2 HTML5 support: mp3 = true, mp4 = true, ogg = true, opus = true, wav = true) https://www.filemail.com/bundles/js/default?v=R1iSYgzt8XCQHg-EMwry4hVKE5504Mw8JlbomBZDl7o1:184:11563]',
 u'[console.info(SoundManager 2: Ready. ) https://www.filemail.com/bundles/js/default?v=R1iSYgzt8XCQHg-EMwry4hVKE5504Mw8JlbomBZDl7o1:184:11563]',
 u'[JavaScript Error: "downloadable font: OS/2: Bad sTypoLineGap, setting it to 0: -32 (font-family: "filemail" style:normal weight:400 stretch:100 src index:1) source: https://www.filemail.com/fonts/filemail.woff?-x1gbnc" {file: "unknown" line: 2 column: 11 source: "@font-face {\n  font-family: "filemail";\n  src: url("/fonts/filemail.eot?#iefix-x1gbnc") format("embedded-opentype"), url("/fonts/filemail.woff?-x1gbnc") format("woff"), url("/fonts/filemail.ttf?-x1gbnc") format("truetype"), url("/fonts/filemail.svg?-x1gbnc#filemail") format("svg");\n  font-style: normal;\n  font-weight: normal;\n}"}]',
 u'[JavaScript Warning: "Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://127.0.0.1:56666/?_=1542831690530. (Reason: CORS request did not succeed)."]']
```

**Comment by karlcow** [comment]
Also another big problem 😨 
in https://github.com/webcompat/web-bugs/issues/21657
We can see that the string is truncated. We need to figure out if the truncation happens on webcompat.com side or on the reporter side.

**Comment by karlcow** [comment]
@wisniewskit ah got an answer to my question:

> Where the console.log( is coming from

https://searchfox.org/mozilla-central/rev/8f89901f2d69d9783f946a7458a6d7ee70635a94/browser/extensions/webcompat-reporter/experimentalAPIs/tabExtras.js#40-55

```js
  function getConsoleMessages(windowIds) {
    const ConsoleAPIStorage = Cc["@mozilla.org/consoleAPI-storage;1"]
                              .getService(Ci.nsIConsoleAPIStorage);
    let messages = [];
    for (const id of windowIds) {
      messages = messages.concat(ConsoleAPIStorage.getEvents(id) || []);
    }
    return messages.map(evt => {
      const {columnNumber, filename, level, lineNumber, timeStamp} = evt;
      const args = evt.arguments.map(arg => {
        return "" + arg;
      }).join(", ");
      const message = `[console.${level}(${args}) ${filename}:${lineNumber}:${columnNumber}]`;
      return {timeStamp, message};
    });
  }
```

We should probably make it more structured. 

```python
{'level':${level}, 
  'log': ${args},
  'uri': ${filename},
  'pos': ${lineNumber}:${columNumber},
  }
```

**Comment by wisniewskit** [comment]
Ah, you beat me to it, sorry. Yes, I don't mind structuring these things rather than using strings. This was my first attempt. I think your suggestion is fine. When we've decided, let's open a Bugzilla bug to fix the desktop and Fennec reporters.

I don't know where the truncation happens, though. I tried to avoid intentionally truncating anything (that was of course the whole reason to use POST requests in the first place). I will try to investigate this ASAP.

**Comment by karlcow** [comment]
@wisniewskit thanks. I just reformatted a bit. Trying to make sense myself. :)

**Comment by karlcow** [comment]
Also @wisniewskit did you see all the logs which are object returns `[object Object]` and not the content. Probably not useful in the current form.

**Comment by wisniewskit** [comment]
No, I haven't? Please link me to one or two issues where that happens, and I'll gladly investigate that as well.

**Comment by karlcow** [comment]
@wisniewskit https://github.com/webcompat/web-bugs/issues/21650 This one see the details. 
Now try in your own browser. 

This is comment https://github.com/webcompat/webcompat.com/issues/2659#issuecomment-440858991 see the log and the screenshot.

**Comment by karlcow** [comment]
* Paper trail https://bugzilla.mozilla.org/show_bug.cgi?id=1510073 for the structure of the log.

**Comment by ksy36** [comment]
Regarding the object format from [this bug ](https://bugzilla.mozilla.org/show_bug.cgi?id=1510067), I've looked at the previewers that Nicolas [mentioned](https://searchfox.org/mozilla-central/source/devtools/server/actors/object/previewers.js) and looks like it may be something that could work for us.
 
They limit a number of properties down to 10 and fold the rest:

<img width="1677" alt="Screen Shot 2019-06-28 at 10 16 17 PM" src="https://user-images.githubusercontent.com/1303908/60378591-4076ef00-99d9-11e9-96cf-cc35b51fbada.png">

We, perhaps, could do something similar - for all objects and arrays in console.log send maximum 10 properties/elements from the extension, so we have a "preview"? That could help with really big or nested objects. 

So webcompat.com will just receive a part of it, and to see the whole object we'd need to go to the actual website and look in the console.

@karlcow @wisniewskit @denschub  do you think that would be sufficient enough for diagnosis?

**Comment by karlcow** [comment]
Good lurking. Thanks @ksy36 Agreed with you.

**Comment by wisniewskit** [comment]
> So webcompat.com will just receive a part of it, and to see the whole object we'd need to go to the actual website and look in the console.

Why not only show it that way in the UI, but still send the data to webcompat.com? That way we could still (for example) access the full result as a comment in the HTML or something like that, without having to reproduce the problem ourselves.

**Comment by ksy36** [comment]
So this proposal is only for the objects in console log, e.g. when a site has `console.log(window)` we would just send 10 properties of the window object. The rest of the data will still come in full.
 
The main reason for that is that objects can be really huge or have circular references in them. And probably they're not as useful for diagnosis as errors, for example. And we can always make it better, if preview is not enough.

**Comment by wisniewskit** [comment]
Right, I suppose that's fine now that I've thought it through again.

**Comment by miketaylr** [comment]
There's a few possible approaches to this, I think there's some very low hanging fruit here. :)

One idea (I think from @karlcow) is to just upload the console messages as a text blob and store them on disk (eventually in the cloud, once that's sorted for images), and just hyperlink to them in the issue. This could work. And if we served them as `application/json`, I think the built-in Firefox JSON viewer would kick in and be nice -- but only if we structured everything as a JSON object. 

Maybe something like:

```
{
  "line 1": "logged message: blah",
  "line 2": Object()
}
```

Or we could save the text blob as another format and beautify the text, etc. Just an idea.

**Comment by wisniewskit** [comment]
@miketaylr, I'd rather we keep them as JSON (which they are already)... too many nightmares about having to parsing text blobs that were incorrectly formatted. Unless we have zero control over the server containing the blobs, it shouldn't be too tricky to create a programmatic to check if the user wants a plain text or JSON formatted message (or we could just do a simple fetch-as-JSON and then make a table/list/text blob on the client side).

**Comment by ksy36** [comment]
I've tried looking at the logs in the built-in Firefox JSON viewer. It's better than what we have right now, but seems hard to navigate and catch obvious errors..

<img width="1679" alt="Screen Shot 2019-11-21 at 2 49 20 PM" src="https://user-images.githubusercontent.com/1303908/69372040-f2f06c80-0c6e-11ea-858e-1afec7a832d5.png">

Also tried building a simple colored list based on JSON (used devtools colors).

<img width="1678" alt="Screen Shot 2019-11-21 at 2 48 06 PM" src="https://user-images.githubusercontent.com/1303908/69372025-ebc95e80-0c6e-11ea-8134-28fcd014457e.png">
 
This looks better, though messages about cookies blocking could be grouped together. Tried this on another site and got 74 of them :)

So perhaps we could do:

1. Once the form is submitted, save logs as json file on webcompat
2. When building a body of a github issue instead of having console logs in `<pre>` tag, provide a link to webcompat.com, something like https://webcompat.com/logs/45169 (View console logs)
3. On this new route we parse the previously saved json and display this colored list

thoughts? @karlcow @miketaylr @wisniewskit

**Comment by miketaylr** [comment]
This seems like a cool idea to me. And if we save the raw JSON to the server, we can change the way we display it in the future.



> though messages about cookies blocking could be grouped together

That could be good -- or it might be interesting to have it reflect the way that devtools current displays it, which I guess is in the order its displayed here. Seems like a good "v2" improvement if you want to do it. :)
