### ISSUE TITLE
URL requirement on the form accepts URL with a space in the domain name

### ISSUE THREAD

**Issue by karlcow** [webcompat/webcompat.com#2662]
Example: 
`http:// 2650.example.com`

Note that domain syntax is under-defined in HTML

* see https://url.spec.whatwg.org/#valid-domain
* See https://github.com/whatwg/url/issues/245

**Comment by karlcow** [comment]
![capture d ecran 2018-10-18 a 09 30 25](https://user-images.githubusercontent.com/505230/47124375-785d5c80-d2b8-11e8-9791-87edfc65771d.png)

**Comment by Anushi1998** [comment]
@karlcow Can I just add a check for space ahead of schemes to avoid this? Or would it be a better idea to actually peek into the webpage to see if it is pointing to a valid URL or not?

**Comment by karlcow** [comment]
Currently what is checking the code and displays the green tick mark needs to be a red cross when there is a space in the domain portion of the URL.

**Comment by Anushi1998** [comment]
Okay, I will make the changes :)

**Comment by karlcow** [comment]
@Anushi1998 you should also double with the functional tests too. Add one if it doesn't exist yet.

**Comment by Anushi1998** [comment]
Would it be a good idea to validate URL more properly as of now we are only checking for `http://` or `https://` schemes (see [here](https://github.com/webcompat/webcompat.com/blob/master/webcompat/static/js/lib/bugform.js#L305-L307))?
My two cents would be 
- Visiting the URL and checking the return status code. (Would be slow, depending on network connection of client) 
- Or, writing a function something like https://github.com/kvesteri/validators/blob/master/validators/url.py

**Comment by karlcow** [comment]
> Visiting the URL and checking the return status code. (Would be slow, depending on network connection of client)

It should probably not be a requirement for validation. In the past we had people reporting issues with internal websites and router and these will probably return a 4** class HTTP error. 

We can try to minimize the impact. So I would suggest only fixing the space issue in there for now and we will tackle more issues if they appear.  Step by step :)

**Comment by Anushi1998** [comment]
Okay, cool.
I will do it by today :)
