### ISSUE TITLE
Remove lint-stage 

### ISSUE THREAD

**Issue by magsout** [webcompat/webcompat.com#2676]
Not sure it's a good thing. With test we can see if the linter is not happy, plus:

![capture d ecran 2018-10-25 a 13 55 30](https://user-images.githubusercontent.com/1997108/47498497-bbda3c80-d85d-11e8-8caa-c96a9d2457ed.png)

**Comment by marimeireles** [comment]
Hey, I know I'm new here and all
But if I can give my 2 cents: I think this kind of tool is really useful. As a new contributor it helped me to write code and keep coherence in an easy way. 
But I never got these errors and I've used it just a little, so maybe it's not worth keeping it.
Maybe a good solution would be look for a new linter?

**Comment by magsout** [comment]
@marimeireles thanks for youy feedback.

>As a new contributor it helped me to write code and keep coherence in an easy way.

oh, cool, thanks. I'm glad to see it helpful

> Maybe a good solution would be look for a new linter?

I think, we just to update the script in `package.json`

**Comment by magsout** [comment]
#2688
