### ISSUE TITLE
simple and nested lists style on webcompat.com is not taken into account.

### ISSUE THREAD

**Issue by karlcow** [webcompat/webcompat.com#2681]
This is the rendering of a list on Github
<img width="474" alt="capture d ecran 2018-10-29 a 07 26 46" src="https://user-images.githubusercontent.com/505230/47622762-3f40aa00-db4c-11e8-9779-7f03c5a0004b.png">
This is the rendering of a list on Webcompat.com
<img width="485" alt="capture d ecran 2018-10-29 a 07 26 58" src="https://user-images.githubusercontent.com/505230/47622764-4bc50280-db4c-11e8-8e5d-d7680e21918d.png">

**Comment by rafia95** [comment]
@karlcow I can work on it :)

**Comment by Anushi1998** [comment]
@rafia95 Cool, go forward.
If you need any help in generating Pull request, let me know :)

**Comment by karlcow** [comment]
Fixed by #2715
