### ISSUE TITLE
Different Linux distro in chrome and firefox

### ISSUE THREAD

**Issue by Anushi1998** [webcompat/webcompat.com#2684]
In Chrome it shows Linux
![image](https://user-images.githubusercontent.com/16550254/47629519-d54ae500-daf8-11e8-880a-62eaaaf746ed.png)

In Firefox it shows Ubuntu
![image](https://user-images.githubusercontent.com/16550254/47629539-e85db500-daf8-11e8-827e-43951e2c3939.png)

A possible fix would be to consider the description field in `lsb_release -a` if we are on Linux. I will check if Windows and Android also have this issue.

**Comment by karlcow** [comment]
@Anushi1998 
Could you check what is the user agent string on Chrome on your Ubuntu linux?
And the one for Firefox.

**Comment by Anushi1998** [comment]
@karlcow 
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.67 Safari/537.36

**Comment by Anushi1998** [comment]
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.67 Safari/537.36

**Comment by karlcow** [comment]
So it's not really dependent on us but on Canonical. :)
the project is using [ua-parser](https://github.com/ua-parser/uap-python) which returns the system.
Chromium doesn't have the Ubuntu so it doesn't report it. 

So I would say that this is working for me. :)
