### ISSUE TITLE
Add No Response (plus Milestones) bot to web-bugs repo

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat.com#2693]
Spun out from https://github.com/webcompat/webcompat.com/issues/2654

**Comment by softvision-sergiulogigan** [comment]
@miketaylr, the needsinfo bot doesn't seem to be running. When you have the time, could you please check?

We have a lot of issues that could have been closed by the no-response bot, but didn't.
https://github.com/webcompat/web-bugs/milestone/2 (at the bottom of the list))
