### ISSUE TITLE
Re-add lockbot to web-bugs repo

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat.com#2709]
Just a heads up: I removed lockbot from the repo, because it was going to lock and add a comment to about 20,000 issues. We can investigate a new app, or fork and host a version ourselves that only considers issues *after* it's installed.

Filing here to track that work at some future point.

**Comment by denschub** [comment]
https://github.com/dessant/lock-threads/pull/8 🔥🦊

**Comment by denschub** [comment]
PR has been merged and changes have been deployed. So, 

```patch
diff --git a/.github/lock.yml b/.github/lock.yml
index 5424f27..1422387 100644
--- a/.github/lock.yml
+++ b/.github/lock.yml
@@ -3,6 +3,10 @@
 # Number of days of inactivity before a closed issue or pull request is locked
 daysUntilLock: 7

+# Skip issues and pull requests created before a given timestamp. Timestamp must
+# follow ISO 8601 (`YYYY-MM-DD`). Set to `false` to disable
+skipCreatedBefore: 2018-11-01
+
 # Issues and pull requests with these labels will not be locked. Set to `[]` to disable
 exemptLabels:
   - status-needsinfo-denschub
```

should make the world happy.

**Comment by miketaylr** [comment]
So cool, thank you @denschub. I'll re-deploy this week at some point.

**Comment by miketaylr** [comment]
OK! Re-added, with `skipCreatedBefore` set to `2018-11-12`
