### ISSUE TITLE
Can't file bug as myself

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat.com#2718]
I just tried to create a non-anonymous bug, and clicking on "Report as miketaylr" didn't work.

The first time it asked me to auth (b/c I was using a new profile), and when that was done it redirected me to the homepage.

I tried again, already logged in, and clicking "Report as miketaylr" again sent me to the homepage, with no new bug.

https://github.com/webcompat/web-bugs/issues/21857 is the bug I ended up filing anonymously.

**Comment by karlcow** [comment]
```bash
# defce98 v15.1.1 changelog update
python run.py
```

Anonymous -> Report -> Report as github
https://github.com/webcompat/webcompat-tests/issues/1724

Logged-in -> Report -> Report as karlcow
https://github.com/webcompat/webcompat-tests/issues/1725

This is working. I probably don't understand the steps to reproduce.

**Comment by karlcow** [comment]
@miketaylr could you clarify what you were trying to do?

**Comment by miketaylr** [comment]
> @miketaylr could you clarify what you were trying to do?

just report a bug. I will try again.

**Comment by miketaylr** [comment]
Who even knows what was going on this day.
