### ISSUE TITLE
tests: labels

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat.com#272]
we need intern tests for:

(list modified by @karlcow on 2015-08-07)

* [ ] **setup**: check if we are logged in 
* [x] **tearDown**: erase all labels
* [x] label gear is here
* [x] label widget opens
* [x] setting a label makes it appear in the list of labels
* [x] removing a label makes it disappear from the list of labels
* [ ] label filter works

**Comment by karlcow** [comment]
Started to write a test for this, not there yet. Just a head up.
https://github.com/karlcow/webcompat.com/commit/5e2ae26c225653fd2ade32f9b05e8d69a8d7b1b0

**Comment by miketaylr** [comment]
:heart:

**Comment by karlcow** [comment]
I'm testing with 

```python
    ISSUES_REPO_URI = os.environ.get('ISSUES_REPO_URI') or "miketaylr/nobody-look-at-this/issues"
```

and 

``` js
define([
  // './functional/index',
  // './functional/comments',
  // './functional/issue-list',
  // './functional/issues',
  // './functional/reporting',
  // './functional/contributors',
  // './functional/history-navigation',
  './functional/labels'
], function () {
  'use strict';
});
```

to ease my pain.

**Comment by karlcow** [comment]
> In that case, the automatic login will fail and you then have 10 seconds to manually enter a username and password in the GitHub login screen that appears.

hmm it doesn't seem I get the 10 seconds

**Comment by karlcow** [comment]
ok managed to enter my credentials quick enough.

```
/Users/karl/code/webcompat.com/node_modules/intern/runner.js:67
× firefox 38.0.5 on MAC - labels - setting a label
NoSuchElement: [POST http://localhost:4444/wd/hub/session/cddc1cb6-5f87-4617-830a-a6238fa0446a/element / {"using":"css selector","value":"LabelEditor-launcher"}] Unable to locate element: {"method":"css selector","selector":"LabelEditor-launcher"}
For documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.html
```

huh?
Checking a page https://webcompat.com/issues/100
Indeed I do not see the gear. Exploring the DOM.

``` html
<div class="Label-wrapper">
          <span class="Label Label--title">Labels</span>
          
          <span class="LabelEditor-wrapper">
<button class="LabelEditor-launcher wc-Icon wc-Icon--gear" aria-hidden="true"><span class="wc-sronly">Edit Labels</span></button>
</span>
          
          <span class="Label-list">
          
          </span>
        </div>
```

so `LabelEditor-launcher` is there **but** it has a `display: none;` this being logged in.

```css
.LabelEditor-launcher {
    display: none;
    border: medium none;
    width: 1.3em;
    height: 1.3em;
    font-size: 1.4em;
    padding: 0px;
    opacity: 0.8;
}
```

Weird. /me is heading to a recent issue. Same thing.
https://webcompat.com/issues/1519

Oh weird. Logged out and logged in again, and the gear is back.

**Comment by karlcow** [comment]
Ah gotcha… stupid me. `LabelEditor-launcher` instead of `.LabelEditor-launcher` typo :crown: 

Let's go to the next typo:

``` html
<label class="LabelEditor-item">
              <span class="LabelEditor-color" style="background-color:#cccccc">
                <input class="LabelEditor-checkbox" name="duplicate" data-color="cccccc" type="checkbox">
              </span>
              <span class="LabelEditor-name">duplicate</span>
              </label>
```
Ah habits. I mixed up XPath syntax with CSS selectors. I'm more familiar with the former.

`findByCssSelector('label.LabelEditor-item input[name="contactready"]').click()` this should work better

It is still not working. I wonder if it also depends on a specific version of labelnames.

![capture d ecran 2015-08-05 a 10 20 22](https://cloud.githubusercontent.com/assets/505230/9076307/d1e38358-3b5b-11e5-956c-b290c6d4c3d5.png)

At least it's opening the thing as planned. 

![capture d ecran 2015-08-05 a 10 24 57](https://cloud.githubusercontent.com/assets/505230/9076359/57fc1e28-3b5c-11e5-8ccc-f5193ce44580.png)

And indeed it requires `status-*`
Let's commit the code for the first test and see if @miketaylr as more luck than me.

**Comment by karlcow** [comment]
Note that at the moment github has connectivity issues.

**Comment by karlcow** [comment]
I closed the previous pull request and created a new one. It's not complete but it's working and this is #666 for the code conspiracy theorists :scream:

**Comment by miketaylr** [comment]
Coooooool. :star2:

**Comment by karlcow** [comment]
ok. 

I need to adjust the setup with things discussed in  https://github.com/webcompat/webcompat.com/pull/666#discussion_r36476883

**Comment by karlcow** [comment]
Thinking out loud.

@miketaylr when we check a label, what does the code do?
I guess it creates an object that will be used by a POST?
Which object is it?

Functional tests are here to test the UI interactions, not the protocol. We will probably remove some pain if we are not testing the communications **at this level**.

The gear being here or not is dependent on having a login state, but adding and removing a label is not entirely dependent on the communications with the server. The test is here for saying when we click on that thing it sends the right object to the next piece of code (that will eventually results in a request).

With https://theintern.github.io/intern/#page-objects it might be easier to do that. 

What do you think?

**Comment by karlcow** [comment]
Ok I guess that is 
https://github.com/webcompat/webcompat.com/blob/master/webcompat/static/js/lib/labels.js#L144

```js
{labels: modelUpdate}
```

Selector: `"input[type=checkbox]:checked"`
if only one label `modelUpdate[0].name` will give `contactready` once checked.

**Comment by karlcow** [comment]
ok good. This didn't explode

```
→ git pull --rebase upstream master
remote: Counting objects: 7, done.
remote: Compressing objects: 100% (7/7), done.
remote: Total 7 (delta 2), reused 0 (delta 0), pack-reused 0
Unpacking objects: 100% (7/7), done.
From https://github.com/webcompat/webcompat.com
 * branch            master     -> FETCH_HEAD
   e2fe3ab..a1faa33  master     -> upstream/master
First, rewinding head to replay your work on top of it...
Applying: #272 fixing a couple of jslint
Applying: #272 Adds a labels tests section
Applying: #272 Adds login to the site
Applying: #272 tests if label gear is visible
Applying: #272 tests the addition of contactready label
Applying: #272 move the login to the setup
```

**Comment by karlcow** [comment]
ahah. I was too fast

```
→ git push origin 272/2
To git@github.com:karlcow/webcompat.com.git
 ! [rejected]        272/2 -> 272/2 (non-fast-forward)
error: failed to push some refs to 'git@github.com:karlcow/webcompat.com.git'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Integrate the remote changes (e.g.
hint: 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
```

**Comment by karlcow** [comment]
pull, merge, add, commit… and push

```
→ git push origin 272/2
Counting objects: 37, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (37/37), done.
Writing objects: 100% (37/37), 3.52 KiB | 0 bytes/s, done.
Total 37 (delta 29), reused 0 (delta 0)
To git@github.com:karlcow/webcompat.com.git
   94dce03..9553491  272/2 -> 272/2
```

**Comment by karlcow** [comment]
Can't crack this one yet. This is not working. Putting it here to not forget.

``` js
    'Search filter is working': function () {
      return this.remote
        .setFindTimeout(intern.config.wc.pageLoadTimeout)
        .get(require.toUrl(url(100)))
        .findByCssSelector('.LabelEditor-launcher').click()
        .end()
        .findByCssSelector('.LabelEditor-search').click()
        .type('duplicate')
        .end()
        .findByCssSelector('.LabelEditor-name')
        .getVisibleText()
        .then(function (text) {
          assert.include(text, 'duplicate', 'Search filter reduces the list to what is typed');
        })
        .end();
    }
```

**Comment by karlcow** [comment]
@miketaylr @tagawa @magsout **Useful tip**:
When you need to run an individual test suite during development.

```
node_modules/.bin/intern-runner config=tests/intern functionalSuites=tests/functional/labels.js user="username" pw="secret_lies"
```

This `functionalSuites=tests/functional/labels.js` will select the test suite to run. This is also good for testing how independent are our test suite from each other. :)

**Comment by karlcow** [comment]
@vladikoff do you know a way to have `intern-runner` print things in the shell terminal where we run the tests? Basically an equivalent of a `console.log()` message or what we would in python for quick debugging with a `print()` statement.

**Comment by vladikoff** [comment]
@karlcow Hey Karl,

If you pass `reporters=console` ( `reporters=Console` in intern 3)  then it will print your console messages. The trick is that the "pretty" reporters does some terminal magic for animation purposes so I think the log (console.log) gets erased because it refreshes the frame. I'm not sure if that can be fixed or that's just how animations like this work in terminals.

![image](https://cloud.githubusercontent.com/assets/128755/9214419/7b7f2066-406b-11e5-81e7-d614c6c5ec35.png)

**Comment by karlcow** [comment]
@vladikoff alleluiah! Thanks. Exactly what I wanted. big :joy:

**Comment by karlcow** [comment]
grmbl… grmbl…

I guess I'll have to introduce a bit more delay. 

```
PASS: main - labels - Label appears once selected (563ms)
FAIL: main - labels - Label has been sent to GitHub (12403ms)
NoSuchElement: [POST http://localhost:4444/wd/hub/session/09c47bda-3f4f-4ab8-9c6c-2fcaa4306b4d/element / {"using":"css selector","value":".Label--badge"}] Unable to locate element: {"method":"css selector","selector":".Label--badge"}
```

**Comment by karlcow** [comment]
The issue takes time too. Here I just did a reload. so everything is in cache. This is/should be the case for `http://localhost:5000/api/issues/2`, but we can see it takes almost 10s for localhost to receive the response. I wonder why it takes so much time.

![capture d ecran 2015-08-13 a 13 52 02](https://cloud.githubusercontent.com/assets/505230/9242802/aeb62d96-41c2-11e5-8ab7-c4f36f292207.png)

I wonder if the issue is on the python side.
