### ISSUE TITLE
Firefox Reality issues get a browser-fixme label

### ISSUE THREAD

**Issue by softvision-sergiulogigan** [webcompat/webcompat.com#2728]
Looks like the Firefox Reality issues get a `browser-fixme` label as well as a `browser-firefox-reality` one.
We sould not apply the `browser-fixme` label in these situations.

Here's a recent example:
https://github.com/webcompat/web-bugs/issues/22349

![image](https://user-images.githubusercontent.com/16573771/49656248-8cfedb00-fa45-11e8-9ea3-be80e7707475.png)

**Comment by karlcow** [comment]
The user agent for Firefox Reality has the form.

```
Mozilla/5.0 (Android 7.1.2; Mobile VR; rv:66.0) Gecko/66.0 Firefox/66.0
```

The extra-labels are specified at 

https://github.com/webcompat/webcompat.com/blob/38c6835ee28900601910ad0afbf43b90a31b3169/config/__init__.py#L183-L196

And the fixme is set by 
https://github.com/webcompat/webcompat.com/blob/38c6835ee28900601910ad0afbf43b90a31b3169/webcompat/webhooks/helpers.py#L37-L42

The tests for the webhook are at:
https://github.com/webcompat/webcompat.com/blob/38c6835ee28900601910ad0afbf43b90a31b3169/tests/unit/test_webhook.py#L147-L151

**Comment by karlcow** [comment]
```diff
diff --git a/tests/unit/test_webhook.py b/tests/unit/test_webhook.py
index 2ff0202..c4aede9 100644
--- a/tests/unit/test_webhook.py
+++ b/tests/unit/test_webhook.py
@@ -164,6 +164,7 @@ class TestWebhook(unittest.TestCase):
              ({'browser': 'Firefox 30.0',
              'extra_labels': 'browser-focus-geckoview'}, 'browser-firefox'),
             ({}, 'browser-fixme'),
+            ({'browser': 'Mozilla/5.0 (Android 7.1.2; Mobile VR; rv:66.0) Gecko/66.0 Firefox/66.0'}, 'browser-firefox-reality'),  # noqa
         ]
         for metadata_dict, expected in metadata_tests:
             actual = helpers.extract_browser_label(metadata_dict)
```

that gives

```
 nosetests tests/unit/test_webhook.py
F..............
======================================================================
FAIL: Extract browser label name.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/karl/code/webcompat.com/tests/unit/test_webhook.py", line 171, in test_extract_browser_label
    self.assertEqual(expected, actual)
AssertionError: 'browser-firefox-reality' != 'browser-fixme'

----------------------------------------------------------------------
Ran 15 tests in 0.092s

FAILED (failures=1)
```

I guess we need to check that if a proper extra-label exists, we don't need to validate or extract what should be the label.

**Comment by karlcow** [comment]
I have a fix for this in #2850.
To note that there is a larger issue which probably depends on third party libraries for identifying browsers. Reality is unknown.

This issue is in fact larger than reality. 
It's about any browser specified both through extra labels and through identification. In the case of reality the identification failing, it got a browser-fixme.

**Comment by karlcow** [comment]
@softvision-sergiulogigan this is deployed. Firefox reality should get its proper label without fixme

**Comment by karlcow** [comment]
The meta issue about this is:
```python
>>> from ua_parser import user_agent_parser
>>> import pprint
>>> pprint.pprint(user_agent_parser.Parse('Mozilla/5.0 (Android 7.1.2; Mobile VR; rv:66.0) Gecko/66.0 Firefox/66.0'))
{'device': {'brand': u'Generic',
            'family': u'Generic Smartphone',
            'model': u'Smartphone'},
 'os': {'family': 'Android',
        'major': '7',
        'minor': '1',
        'patch': '2',
        'patch_minor': None},
 'string': 'Mozilla/5.0 (Android 7.1.2; Mobile VR; rv:66.0) Gecko/66.0 Firefox/66.0',
 'user_agent': {'family': 'Android', 'major': '7', 'minor': '1', 'patch': '2'}}
```

I opened an issue on 
https://github.com/ua-parser/uap-core/issues/404
