### ISSUE TITLE
Document (in the wiki?) how to file a bug (semi?) programmatically

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat.com#2730]
If there are new clients that want to create new webcompat bugs, we should document how to do that.

@karlcow documented the old / GET system here:

https://github.com/webcompat/webcompat.com/issues/2525#issuecomment-403676858

We should add what is new in the new POST world.

**Comment by karlcow** [comment]
This was done in https://github.com/webcompat/webcompat.com/wiki/Architecture#http-post-with-a-json-body--recommended
