### ISSUE TITLE
Create an Update mock outs mode that fetches new mock outs when needed

### ISSUE THREAD

**Issue by marimeireles** [webcompat/webcompat.com#2738]
While working on #2727 I had to make a change on the fixture files.
Instead of changing these files manually the point here is to make a script that runs it automatically.

The goal of this issue is to:
* Create a flag on the terminal that allows the user to enter in this mode
* Fetch the new mock outs and update the old files

**Comment by karlcow** [comment]
See the discussion in #2739 why we closed it.
