### ISSUE TITLE
Some files are being processed on Parse HTML when they should be processed on Evaluate script

### ISSUE THREAD

**Issue by marimeireles** [webcompat/webcompat.com#2740]
I believe this is happening because of the position where these files are called on the html. When the html finds a <script> tag it will fetch the script and executes it and only after it's done it'll come back to parse the html.

I've identified this problem on the following files:
`webcompat/static/js/lib/models/issue.js`
`webcompat/static/js/lib/bugform.js`
`webcompat/static/js/lib/untriaged.js`

It may be more around the project.

There are many ways to fix this problem, either by attaching `async`, `defer` to the html or the way I noticed had a better result adding `window.onload` on the js file.

**Comment by marimeireles** [comment]
Hey @miketaylr do you think it's worth looking for more of these in the project?
(And if I find any other relevant results I add in the same PR.)

Also, I think it'd be nice if Oana or Sergiu could test it once the PR is ready. I've only obtained small improvements on my previous tests when I applied these changes, so it might be a factor on my side rather than a real performance improvement.

**Comment by karlcow** [comment]
@marimeireles @miketaylr Using `window.performance` https://github.com/webcompat/webcompat.com/issues/1870#issuecomment-344508357 might help to measure what gain do we have. Because this project is about performance improvement, it would be cool to make sure the before/after.

**Comment by miketaylr** [comment]
Yes, agree on measuring things here! Even something crude like logging to the console the numbers then sergiu or oana can report what they see from Romania.

**Comment by marimeireles** [comment]
I think using a tool like this one is important so we can have a more precise measure than just looking at the devtools panel and trying to estimate how long is taking to load the scripts. 

But I can't use this tool because it only allows me to measure times inside the js and what I'm trying to do here is estimate how long does it take to completely load the webpage, taking into account all of the scripts that are part of it.

I'll look for a tool that allows me to measure that. But it's good to know about it, I'll definitely use for other parts of my project. :)

**Comment by marimeireles** [comment]
`webcompat/static/js/lib/models/issue.js` has a 2.5% of total loading time, most of this time is spent loading Markdown-it lib, when we fix #2727 , I believe it won't be an issue anymore.

`webcompat/static/js/lib/bugform.js` has a 3.3% of total loading time. I measured the loading times for  `bugform.js` for different pages using `async`, `defer` and the `window.onload` methods, here is a table with my results average obtained using `window.performance`:

| method     | homepage | all issues | single issue | report bug |
|--------|----------|------------|--------------|------------|
|no changes| 6.5| 3.6| 3.8|7.1 |
| async  |      7.3    |        -    |          -    |     6.5       |
| defer  |       7.5   |    4.3        |     -         |     -       |
| onload |     6.7     |    3.2        |      3.4        |      13.6      |
(time in ms)

What I could observe from this is that `async` and `defer` don't really improve the loading time and they give me a more sparse set of loading times. 
When I used `onload` it helped in most of the pages but the [report bug](https://webcompat.com/issues/new), because this was a main element for the page and it isn't worth it to load it later, apparently.

with the new #2737 fix ` webcompat/static/js/lib/untriaged.js` now only takes up 0.1% of total time, so it's not relevant anymore.

I've looked around the code and didn't find any other files that might be loading at the wrong time. I don't think it's worthwhile to implement these changes, there isn't a real performance improvement and IMO we can close this issue and focus on other solutions.

**Comment by marimeireles** [comment]
What do you think @miketaylr and/or @karlcow ?
You think I should explore more? I think it's a bad direction to go. :p

**Comment by miketaylr** [comment]
> there isn't a real performance improvement and IMO we can close this issue and focus on other solutions

That makes sense to me! Relatedly, we don't even need to load bugform.js for all issues / single issue pages... so the potential wins there could be solved by figuring out a modular JS loading solution (and not loading it at all :)).

**Comment by miketaylr** [comment]
(it would make a cool blog post, to document what you learned... if you need things to blog about in the future :P)

**Comment by karlcow** [comment]
@marimeireles It's very cool and indeed I agree with your conclusions. Nice thing to document or add in a future blog post. Explorations like these are essential.

**Comment by marimeireles** [comment]
> so the potential wins there could be solved by figuring out a modular JS loading solution (and not loading it at all :)).

Good to know! I have an issue to explore that. 

Thanks for the feedback @karlcow and @miketaylr . :)
