### ISSUE TITLE
Change “Reproduce a Bug” with “Triage a Bug”

### ISSUE THREAD

**Issue by softvision-oana-arbuzov** [webcompat/webcompat.com#2741]
**Environment:**
URL: https://webcompat.com/contributors/reproduce-bug  
Browser / Version: Firefox Nightly 64.0a1 (2018-12-13)
Operating System: Windows 10 Pro

**Steps to Reproduce:**
    1. Navigate to https://webcompat.com/contributors/reproduce-bug 
    2. Observe the section.
       
**Expected Behavior:**
The section refers only to “Triage a bug”.

**Actual Behavior:**
The section refers both to “Reproduce a bug” and “Triage a bug”.

**Note**
    1. Screenshot attached.

Affected area:
```html
<a class="link-text" href="/contributors/reproduce-bug">
          Reproduce a Bug
</a>
```
```html
<a class="footer-item-link" href="/contributors/reproduce-bug">Reproduce a Bug</a>
```

**Watchers:**
@softvision-sergiulogigan
@softvision-oana-arbuzov
@cipriansv 

sv; 

![screenshot_2](https://user-images.githubusercontent.com/12184325/50010735-e2e1fe80-ffc2-11e8-8fe2-292142cf5164.jpg)

**Comment by pachicodes** [comment]
Hi, I would like to help with this !
