### ISSUE TITLE
HTML tags inside the "code" markdown tag is rendered in webcompat.com

### ISSUE THREAD

**Issue by reinhart1010** [webcompat/webcompat.com#2746]
SeeAlso: https://webcompat.com/issues/23056 or webcompat/web-bugs#23056

In Markdown (especially [GitHub Flavored Markdown](https://github.github.com/gfm/)) we can add codes under a backtick character. Here, webcompat.com seems to render the HTML code inside these characters to produce this issue. For example, writing "`All HTML (backtick)<select>(backtick) choices are not visible`" will render as "All HTML `<select>` choices are not visible" in GitHub and

![a real HTML select](https://user-images.githubusercontent.com/17312341/50203175-34a7d180-0393-11e9-9864-ad091f29b1ab.png)

in webcompat.com.

**Comment by marimeireles** [comment]
I think I was able to fix it with my new patch :)
Here is a screenshot
![screen shot 2018-12-19 at 11 48 35](https://user-images.githubusercontent.com/17600982/50224242-8301a400-0384-11e9-8089-c71f742ca90a.png)
& a [link](https://github.com/webcompat/webcompat.com/pull/2731/commits/61c019438e68b4a806946ce93e31fc623e2e8cc3) to the code I used.

If someone types `<strong>Description</strong>: <br>\n<strong>Steps to Reproduce</strong>:` the code will break and won't show anything after that, but I think it's pretty unlikely :p
I'm not good at regex, so, I don't know if there is a solution better than this one. If there is, please let me know.

**Comment by marimeireles** [comment]
Thanks for the bug report @reinhart1010! 🌟
Helped me find a serious bug on the code I was writing that I haven't noticed before.

**Comment by karlcow** [comment]
Probably the current code is breaking the feature.

http://localhost:5000/issues/1736
https://github.com/webcompat/webcompat-tests/issues/1736


We don't get the HTML tags, but we don't get the right thing either. Probably we should explore a way to stringify the content (text only no markup.) in there and use this stringified content only aka textContent.

```
10:05:57.955 var title = 'E roda a <strong>melancolia</strong><br> seu interminável fuso!<br>'
10:05:57.967 undefined
10:06:13.359 var newDiv = document.createElement('div');
10:06:13.366 undefined
10:06:36.780 newDiv.innerHTML = title
10:06:36.790 "E roda a <strong>melancolia</strong><br> seu interminável fuso!<br>"
10:06:46.040 newDiv.textContent
10:06:46.047 "E roda a melancolia seu interminável fuso!"
```

**Comment by marimeireles** [comment]
I got a feeling... I could fix this easily if we decide to use python to render everything using the [safe](http://jinja.pocoo.org/docs/2.10/templates/#html-escaping) option Jinja offers... I tried to run some quick tests, but it's complicated to deal with the aside bar on issues and I gave up.  

I'm just gonna finish my analysis on the python thing and then depending on my results I'll chose my approach to fix this.

**Comment by marimeireles** [comment]
The problem here is that the JQuery selector I'm using doesn't select the whole phrase, it breaks when it finds HTML code.
https://github.com/webcompat/webcompat.com/blob/d2edc8ce4f303055e3ef7c82e64d730a4c4ca57e/webcompat/static/js/lib/models/issue.js#L92-L101
I remember I was responsible for making this change, before using JQuery we were using regex. But I implemented a solution with regex and someone said it's not a good idea. But I don't have any other ideas of what else we could try here. Do you @karlcow ?

> Probably we should explore a way to stringify the content (text only no markup.) in there and use this stringified content only aka textContent.

The content of body is already a `string`.

**Comment by marimeireles** [comment]
I think I might have found something: https://api.jquery.com/multiple-selector/
I'll test it tomorrow. Sorry for pinging you Karl.

**Comment by karlcow** [comment]
Ok let's see.

<img width="951" alt="capture d ecran 2019-02-13 a 07 53 37" src="https://user-images.githubusercontent.com/505230/52673559-7e143780-2f64-11e9-8a23-d167946f6e0d.png">


if I do `document.getElementById('js-Issue-information').textContent`

it returns:

```
URL: https://m.facebook.com/login/identify/?ctx=recover&search_attempts=1
Browser / Version: Firefox Mobile 66.0
Operating System: Android 7.1.2
Tested Another Browser: No
Problem type: Something else
Description: I tell you people he is the server. The program I saw was  voulen Surber light Voli-Tile serve
Steps to Reproduce:
Hhjj

Browser Configuration

  mixed active content blocked: falseimage.mem.shared: truebuildID: 20190207161357tracking content blocked: falsegfx.webrender.blob-images: truehasTouchScreen: truemixed passive content blocked: falsegfx.webrender.enabled: falsegfx.webrender.all: falsechannel: beta

Console Messages:
[u'[console.timeStamp(t_start) https://m.facebook.com/login/identify/?ctx=recover&search_attempts=1:1:1197]', u'[console.timeStamp(t_domcontent) https://m.facebook.com/login/identify/?ctx=recover&search_attempts=1:1:1197]', u'[console.timeStamp(t_tti) https://m.facebook.com/login/identify/?ctx=recover&search_attempts=1:1:1197]', u'[console.timeStamp(t_layout) https://m.facebook.com/login/identify/?ctx=recover&search_attempts=1:1:1197]', u'[console.timeStamp(t_paint) https://m.facebook.com/login/identify/?ctx=recover&search_attempts=1:1:1197]']


From webcompat.com with ❤️
	"
```

which can be parsed as regex this time because it is text and not HTML.
```js
const regex = /Description:(.*)\n+Steps to Reproduce:/gm;
```

see https://regex101.com/r/wu6I7c/1

**Comment by marimeireles** [comment]
ok! Thanks for that Karl, I'm gonna use regex then.
And very cool website! I didn't know it.

Currently this is the result I'm getting on all issues:
![screen shot 2019-02-13 at 11 14 56](https://user-images.githubusercontent.com/17600982/52714345-c6d9e980-2f80-11e9-9559-8193bae17073.png)
and on single issue:
![screen shot 2019-02-13 at 11 15 05](https://user-images.githubusercontent.com/17600982/52714359-ce998e00-2f80-11e9-96aa-e6fbd613fb57.png)
I think we want an uniform description throughout the website, right? So I'll try to remove the HTML rendering from the side bar.

**Comment by marimeireles** [comment]
Ok... I tried everything I could think of but I'm not being able to not escape HTML characters. I've tried on the javascript and I tried on the HTML template, but it doesn't work. Things are just automatically rendered... Any idea @karlcow ?
Thanks!

**Comment by karlcow** [comment]
@marimeireles 

> I'm not being able to not escape HTML characters.

You should not have any if before parsing you are using :)

```js
document.getElementById('js-Issue-information').textContent
```

this returns a string without markup.

**Comment by marimeireles** [comment]
But wait
Do we want something like this:
> Currently this is the result I'm getting on all issues:
![screen shot 2019-02-13 at 11 14 56](https://user-images.githubusercontent.com/17600982/52714345-c6d9e980-2f80-11e9-9559-8193bae17073.png)

or like this:
>![screen shot 2019-02-13 at 11 15 05](https://user-images.githubusercontent.com/17600982/52714359-ce998e00-2f80-11e9-96aa-e6fbd613fb57.png)

Do you want me to escape the chars or not? 
Sorry :p I should have asked that a long time ago, I think.

**Comment by karlcow** [comment]
the second one. :)

**Comment by karlcow** [comment]
To make it clearer
https://staging.webcompat.com/issues/1736

Current rendering

![capture d ecran 2019-02-14 a 10 42 13](https://user-images.githubusercontent.com/505230/52756593-36191180-3045-11e9-81b8-d04b0d2d8ccb.png)

```js
document.getElementById('js-Issue-information').textContent
```

returns:

```
"
	  


URL: https://2727.example.com/
Browser / Version: Firefox 65.0
Operating System: Mac OS X 10.14
Tested Another Browser: Yes
Problem type: Desktop site instead of mobile site
Description: This is a test for the new world
Steps to Reproduce:
Details about our bugs might be scary
What about :love: ?

Love is all we need.



Browser Configuration

  None


From webcompat.com with ❤️
	"
```

that we can parse with the regex.

it will return:

```
 This is a test for the new world
```

It's less than 75 characters. So we can use it as is.

if more than 75 characters. We can cut it. 
In the future we can imagine using [`-webkit-line-clamp`](https://bugzilla.mozilla.org/show_bug.cgi?id=866102) or equivalent.

**Comment by marimeireles** [comment]
Okay. I finally understood what you meant.

`document.getElementById('js-Issue-information').textContent` returns:

```
  <div class="js-Issue-markdown issue-details">
	  <%= body %>
	</div>
```

If I try to access anything using document.get[...] returns something like this.

**Comment by marimeireles** [comment]
If we don't have access to the real HTML then the only thing left is to regex the content of body, right?
But I think that's a terrible idea... We'd probably have to add a lib just to do that.

I made a PR with my code to show what I've done so far.

**Comment by karlcow** [comment]
@marimeireles 

```js
document.createRange().createContextualFragment('<p>booo <strong>bar</strong><br/>\n  Yes!</p>').textContent
```

this returns 

```
"booo bar
  Yes!"
```

**Comment by karlcow** [comment]
@miketaylr can tell if it's evil or not. but this is working.

**Comment by miketaylr** [comment]
> If I try to access anything using document.get[...] returns something like this.

The reason that's grabbing the template contents, instead of the body contents is because you're likely doing that too early. If you grab the text after the body template has been rendered (aka, when it's been populated with a real DOM), it works as expected.

It does require making sure we render the aside after we render the body though:

```diff
mitaylor at omg-5 in ~/dev/webcompat.com on marimeireles-issues/2746/1*
🐓 git diff
─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
modified: webcompat/static/js/lib/issues.js
─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
@ issues.js:151 @ issues.AsideView = Backbone.View.extend({
issues.BodyView = Backbone.View.extend({
  mainView: null,
  initialize: function(options) {
+    this.issueModel = options;
    this.mainView = options.mainView;
  },
  render: function() {
@ issues.js:180 @ issues.BodyView = Backbone.View.extend({
        .addClass("issue-details-nsfw");
    }

+    new issues.AsideView(this.issueModel).render();
+    console.log(
+      "after render:",
+      document.getElementById("js-Issue-information").textContent
+    );
    return this;
  }
});
@ issues.js:409 @ issues.MainView = Backbone.View.extend(
      var issueModel = { model: this.issue };
      this.metadata = new issues.MetaDataView(issueModel);
      this.body = new issues.BodyView(_.extend(issueModel, { mainView: this }));
-      this.aside = new issues.AsideView(issueModel);
+      // we init the aside after we render body, so we can pull the textContent
+      // out of the DOM
      this.labels = new issues.LabelsView(issueModel);
      this.milestones = new issues.MilestonesView(issueModel);
      this.textArea = new issues.TextAreaView();
      this.imageUpload = new issues.ImageUploadView();

+      console.log(
+        "too early",
+        document.getElementById("js-Issue-information").textContent
+      );
 
      callback();
    },
    fetchModels: function() {
```

![screen shot 2019-02-19 at 12 40 04 pm](https://user-images.githubusercontent.com/67283/53039147-18341e00-3444-11e9-80d3-06819f4f958f.png)

**Comment by marimeireles** [comment]
Ahhhh
true.
Thanks Mike!
