### ISSUE TITLE
Upgrading the server to HTTP/2 to use push

### ISSUE THREAD

**Issue by marimeireles** [webcompat/webcompat.com#2747]
A series of blog posts that documents what I'm doing: 

[Building blocks](https://psychonautgirl.space/2018/journey-into-http2-building-blocks/)

**Comment by marimeireles** [comment]
[ ] [observatory](https://observatory.mozilla.org/analyze/webcompat.com#ssh)
Gave some interesting recommendations. I have to look deeper into them, understand what they mean, etc.

[ ] [redbot](https://redbot.org/)
Might be useful to run some analysis and give some insights. It also offers some useful recommendations.

**Comment by karlcow** [comment]
For observatory you might want to compare

* [staging](https://observatory.mozilla.org/analyze/staging.webcompat.com#ssh)
*  [production](https://observatory.mozilla.org/analyze/webcompat.com#ssh)

ping @miketaylr for the… hmm… results.

**Comment by miketaylr** [comment]
> ping @miketaylr for the… hmm… results.

cool, we can tweak things here. FWIW, we used to have an A on webcompat.com, but Observatory changes (which makes sense).

I'll go update production in a few and see if we can get at least a C :P

**Comment by miketaylr** [comment]
@marimeireles I would ignore the observatory stuff for now, it's not really related to HTTP2, but to SSL encryption stuff. Good to fix, but I would consider that a separate task.

**Comment by marimeireles** [comment]
>(i made some tweaks on staging to start with:

nice!

**Comment by marimeireles** [comment]
I gathered some data about how the website is performing without any change so I can be able to compare after I make my changes.

I tried to use perf-html at first because I saw this tool at All Hands and it seemed really good. Unfortunately it wasn't very useful for me. At the moment I'm just analyzing the Network tab, how long the requests are taking to load, etc. and the DevTools Network tab is better than perf-html to do that.
I found out that perf-html's flame graph is really good and if I want to learn more about how a website interacts with the Firefox Browser, I think this tool is going to be really useful.

I wanted to compare if there were meaningful differences between firefox and chrome.

Firefox using Nexus 5 and 5mb/s internet connection:

|         Attribute              | homepage | all issues | single issue(100) | report bug | searching(for "android") |
|-----------------|----------|------------|--------------|------------|-----------|
| Time to first paint |      1833ms    |    5645ms        |   3344ms           |      1932ms      |    4245ms       |
| Speed index          |          1812ms  |       2049ms       |      2339ms      |    1848ms       | 2022ms        |
| Time to start render             |     1811ms    |       2130ms     |      1678ms   |    1846ms     |1963ms       |
| Time to load all requests   | 4000ms |      4400ms      |     5200ms         |     4300ms    |  3315ms     |

Chrome using Nexus 5 and 5mb/s internet connection:

|            Attribute  | homepage | all issues | single issue(100) | report bug | searching(for "android") |
|-----------------|----------|------------|--------------|------------|-----------|
| Time to first paint |      1923ms    |    5908ms        |   2888ms           |      1757ms      |    5641ms       |
| Speed index          |          1527ms  |       1758ms       |      2888ms      |    1483ms       | 1579ms |
| Time to start render             |     1503ms    | 1654ms     |      1493ms   |    1439ms     |1494ms       |
| Time to load all requests   | 5250ms |      5780ms      |     5820ms         |     4670ms    |  4115ms     |

Chrome consistently performed worse in all of my "Time to load all requests" tests. I've ran about 5 tests and calculate the mean.

I believe the rest has a normal variance.

**Comment by marimeireles** [comment]
To update the server to use `push` on production it's necessary to add a session cookie. We don't want to push the files every time for every user, only when it's needed.

According to [this](https://docs.google.com/document/d/1K0NykTXBbbbTlv60t5MyJvXjqKGsCVNYHyLEXIxYMv0/edit#) article from these google guys "Push just enough resources to fill idle network time, and no more." I'll run some tests using devtools to get an idea of how much idle time we have. Maybe splitting the files (#2743) can actually make a difference.

**Comment by marimeireles** [comment]
Okay, according to my tests we have a mean idle time till the page begins loading of 1200ms when I'm on my Sony G8341 and 950ms when I'm on my mac. 
Looking at how long the files take to load completely is not a lot of time. It's enough to load the minified css file, which is probably the most critical file for first paint, but it's not nearly enough to load the js files, the main js file take about 1.9s to load completely.

**Comment by marimeireles** [comment]
Realized it would be useful to have the loading time of the bundle files for comparison with http2 and with/without push.
(Time in ms made on webcompat.com homepage. The values represented here are the median of 5 tests. Tested on Chrome only.)

No change at all:

|Device |CSS| JS | Total time |
|-------|----|---|---|
Mac |  516| 1900 | 2760 |
Sony     | 506 | 1970  | 3200  |

Pushing only the CSS and all of .svg images:

|Device |CSS| Total time:
|-------|----|------|
Mac |   4  | 1810|
Sony     | 23 |  3810 |

Pushing the CSS + images + JS:

|Device |CSS| JS | Total time|
|-------|----|---|----|
Mac | 3 |1210 | 2400|
Sony | 23  | 3060  | 4140 |

I chose to load only the .svg images because looking at the waterfall on devtools they were loaded first by the website.
I don't understand why there was a decrease on performance from computer to mobile on "Pushing only the CSS and all of .svg images".

Apparently we do have enough time to push both the css and the js without causing performance decreasing, according to the data of "Pushing the CSS + images + JS", but I'm still puzzled why the performance on my Sony is inferior to the one that I don't do any push. I have no idea why this is happening, I'll try to run some profilers to see if they can offer me some answer to that.

**Comment by marimeireles** [comment]
It's all going to be summarized on my blog post, so you don't need to read it.
I'm finally finishing it and should be ready by the end of the day.

**Comment by marimeireles** [comment]
This is finished, I just want to finish #2770 before updating the server.

**Comment by marimeireles** [comment]
@miketaylr and I got to the conclusion that'd be better make push requests using flask instead of doing it directly on nginx.
The reason why we think this is better is because it's easier to handle a python file that is in the repo than dealing with the server.

So I'll just enable the Staging server to make http2 requests and the rest of the changes concerning push will be in this new issue #2778.
