### ISSUE TITLE
Use gzip compression for transferring compressable responses

### ISSUE THREAD

**Issue by marimeireles** [webcompat/webcompat.com#2751]
According to WebPageTest we'd gain a lot of performance if we gzipped all of our minified files and svgs.

![screen shot 2018-12-28 at 11 27 54](https://user-images.githubusercontent.com/17600982/50516747-baaed100-0a93-11e9-8d1d-5490241a62b9.png)

**Comment by marimeireles** [comment]
When I try to add gzip on staging I get the following error:
`nginx: [emerg] "gzip" directive is duplicate in /etc/nginx/sites-enabled/staging.webcompat.com:70`
I've already searched for "gzip" on my current file and it's not here, which makes me believe that there is another configuration file with gzip enabled, but for some reason gzip isn't working on that file. So we need to remove from there and add on `etc/nginx/sites-enabled/staging.webcompat.com`. 
To do that I'll need permission to edit other places @miketaylr. If you think it's easier for you to change it, it's okay too. :)

**Comment by miketaylr** [comment]
gzip is configured in `nginx.conf`:

We haven't modified this file on the staging server, so these are the defaults:

```
##
# Gzip Settings
##

gzip on;

# gzip_vary on;
# gzip_proxied any;
# gzip_comp_level 6;
# gzip_buffers 16 8k;
# gzip_http_version 1.1;
# gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;
```

@marimeireles I'll give you access to this file.

**Comment by miketaylr** [comment]
In case it's helpful, these are the settings on production:

```
	##
	# Gzip Settings
	##

	gzip on;
	gzip_disable "msie6";

	gzip_vary on;
	gzip_proxied any;
	gzip_comp_level 6;
	gzip_buffers 16 8k;
	gzip_http_version 1.0;

	# Turn on gzip for all content types that should benefit from it.              
	gzip_types application/ecmascript;
	gzip_types application/javascript;
	gzip_types application/json;
	gzip_types application/pdf;
	gzip_types application/postscript;
	gzip_types application/x-javascript;
	gzip_types image/svg+xml;
	gzip_types text/css;
	gzip_types text/csv;
	# "gzip_types text/html" is assumed.                                           
	gzip_types text/javascript;
	gzip_types text/plain;
	gzip_types text/xml;
```

**Comment by marimeireles** [comment]
Actually, according to [this tool](https://tools.paulcalvano.com/compression.php) I think we'll benefit more from using brotli.

![screen shot 2019-01-08 at 14 59 42](https://user-images.githubusercontent.com/17600982/50846404-35120780-1356-11e9-859e-44e5df6a52bf.png)

**Comment by marimeireles** [comment]
[This](https://www.tinywp.in/nginx-brotli/) might help me in my journey.

**Comment by marimeireles** [comment]
I'm going to open a new issue to run tests using brotli.

**Comment by marimeireles** [comment]
We weren't using the correct Gzip Settings on the Staging server.
I just updated it with the same content that we have on Production and it's working.
@karlcow should I open a PR? I think we should add this to Changelog right?

**Comment by karlcow** [comment]
Also https://bugzilla.mozilla.org/show_bug.cgi?id=1356686
We need to see if it has a cost at the browser level. The network will be improved for sure.

https://caniuse.com/#feat=brotli
* IE
* Opera Mini
* Blackberry
* Safari (prior to macOS 10.13 does not support it.)
do not support it.
Some other articles
https://medium.com/oyotech/how-brotli-compression-gave-us-37-latency-improvement-14d41e50fee4
https://www.enovate.co.uk/blog/2017/02/28/how-to-brotli-compression-with-nginx

**Comment by marimeireles** [comment]
>@marimeireles do you mean opening a PR for changing the nginx.conf file

Yes. @miketaylr said it'd be a good idea to create a new session in our `prod-server.md` to add the configurations of Staging so he wouldn't get lost on what to do as I updated it. You think it's a bad idea?

Thanks for the links, @karlcow!

"We spend 53ms on the main thread decompressing the brotli stream.  I bet this is a lot worse on a slow machine."
That seems like a problem... I didn't know that. I'll make sure to profile it using perf-html when I try it in our server.

> Safari (prior to macOS 10.13 does not support it.)

And also to think of something to detect the user browser and chose the correct zipper. If such thing exists and it's not super resource consuming.

**Comment by miketaylr** [comment]
> And also to think of something to detect the user browser and chose the correct zipper. If such thing exists and it's not super resource consuming.

Browsers will send `accept-encoding` with `br` if they support it (and `gzip` for gzip), so we should respond accordingly. Defaulting to gzip, and using brotli when they claim to support it seems like a reasonable option.

**Comment by marimeireles** [comment]
Great! 

Good to know, thanks Mike!

**Comment by karlcow** [comment]
> Yes. @miketaylr said it'd be a good idea to create a new session in our `prod-server.md` to add the Staging configuration so he wouldn't get lost on what to do as I updated it. You think it's a bad idea?

Ah understood! Sorry.
https://github.com/webcompat/webcompat.com/blob/master/docs/prod-server.md

yes go for it.
