### ISSUE TITLE
Show the GitHub nickname form only to those who are not logged in (anonymous reporting)

### ISSUE THREAD

**Issue by karlcow** [webcompat/webcompat.com#2753]
Followup on #1822

So we had success with the GitHub Name reporting.

See for example 
* https://github.com/webcompat/web-bugs/issues/23596
* https://github.com/webcompat/web-bugs/issues/23594
* https://github.com/webcompat/web-bugs/issues/23588

That's cool. But we have also too much success ;)

* https://github.com/webcompat/web-bugs/issues/23629
* https://github.com/webcompat/web-bugs/issues/23635
* https://github.com/webcompat/web-bugs/issues/23653

We should probably not bother people which are already logged in into thinking they need to enter their nick.

**Comment by magsout** [comment]
@karlcow we could hide the input if user is connected using this condition https://github.com/webcompat/webcompat.com/blob/master/webcompat/templates/nav/shared-nav-links.html#L17
