### ISSUE TITLE
short title feature is broken.

### ISSUE THREAD

**Issue by karlcow** [webcompat/webcompat.com#2767]
Ok finally deployed v15.6.0 with @marimeireles code.

It is working but we have regression too such as
https://webcompat.com/issues/24599

The title on the right side is supposed to be short.

**Comment by karlcow** [comment]
Previous code: https://github.com/webcompat/webcompat.com/blob/81e33b8a339137c76806565c4da6a8f80d951903/webcompat/static/js/lib/models/issue.js#L92-L97

I was arbitrary cutting at 75 characters. 
And there is a plan to limit people on the description field #2629

**Comment by marimeireles** [comment]
Sorry I missed that 🙈
Thanks Karl.

**Comment by marimeireles** [comment]
It's working on localhost. http://localhost:5000/issues/1745
![screen shot 2019-01-21 at 11 22 38](https://user-images.githubusercontent.com/17600982/51477231-ea898580-1d6e-11e9-9d0d-a179aaf1faf6.png)

**Comment by miketaylr** [comment]
> It's working on localhost. http://localhost:5000/issues/1745

Does this mean the bug is fixed? Or do you have a local PR that needs to be sent in?

**Comment by karlcow** [comment]
This is not fixed yet.
