### ISSUE TITLE
Auto add "priority-normal" label to issues that don't get any default priority label

### ISSUE THREAD

**Issue by softvision-sergiulogigan** [webcompat/webcompat.com#2769]
Spinoff of #2655

Could we auto-assign the "priority-normal" label to all the issues that aren't getting any priority label right now, due to the fact that the domain is missing from the priority DB?

Right now, we are doing this manually to all triaged issues (even the invalid/non-compat/duplicate etc. ones).

cc @softvision-oana-arbuzov, @cipriansv

**Comment by karlcow** [comment]
Yes no priority is a valid (non) status. It just means that it didn't raise our bar to be included in `priority-*`. And we should not that add them manually. They are added by the bot. It's the purpose of the bot.

**Comment by karlcow** [comment]
The initial question is why is there a need for a `priority-normal` on all issues?

**Comment by softvision-sergiulogigan** [comment]
I am under the impression that we discussed this in a weekly meeting, some time ago, and included it in our ways of working.

If this is not necessary, we can stop manually attributing `priority-*` labels to the issues we close, and only attributing them to the ones that go into Needsdiagnosis.

**Comment by miketaylr** [comment]
IMO, no label as a signal for `priority-low` is fine (and less work ;P)

**Comment by miketaylr** [comment]
I still think we should rename the priority labels to reflect what they actually do, I'll try to find the issue for that and send in a PR.

**Comment by karlcow** [comment]
@miketaylr this is what you are looking for

 Rename priority labels to reflect alexa ranking #2574 
Closing here.
