### ISSUE TITLE
Create a cookie to prevent pushing cached data on ngnix 

### ISSUE THREAD

**Issue by marimeireles** [webcompat/webcompat.com#2770]
While running tests on staging I found out I was using a paid option from ngnix+ to set cookies `add_header Set-Cookie` and it wasn't working for our server because we don't have ngnix+ :(

So we need to figure out another way to stop the server from sending push files for the user once the user already has those files.

**Comment by marimeireles** [comment]
I thought it was working because when I checked the memory tab on dev tools it showed a session cookie and I thought it was the cookie I created. When I checked to see if the files were really being pushed after I erased the cookies they weren't.

Eventually it led me to this https://www.nginx.com/products/nginx/modules/cookie-flag/

**Comment by marimeireles** [comment]
I thought it was working because when I checked the application tab on dev tools it showed a session cookie and I thought it was the cookie I created. When I checked to see if the files were really being pushed after I erased the cookies they weren't.

Eventually it led me to this https://www.nginx.com/products/nginx/modules/cookie-flag/

**Comment by miketaylr** [comment]
Reading a bit more on this, Push happens as the result of a `Link` header being returned with a response that looks something like `Link: </css/styles.css>; rel=preload; as=style`.

That can happen at the nginx level, or at the Flask level. There might be existing solutions already, but we could probably do something similar to our cache policy decorator:

https://github.com/webcompat/webcompat.com/blob/384c4feeef14a13655b8264dde9f10bfa5614134/webcompat/helpers.py#L519-L549

Maybe we could write a decorator for a view that looked something like:
`@http2_push(resources=['foo.js', 'bar.css'])`

I don't know enough about the push cache to know if we have to track if it's already been pushed at the app level, or if the browser is smart enough to deal with that.

**Comment by marimeireles** [comment]
Wait a second: https://bugzilla.mozilla.org/show_bug.cgi?id=1367551
I think that was a bug and it was fixed! :)
So... I don't think we need to worry about it anymore.

But you still think it'd be better if we make the requests using Flask, right @miketaylr ?

**Comment by miketaylr** [comment]
> It was a Firefox bug and it was fixed: https://bugzilla.mozilla.org/show_bug.cgi?id=1367551

Cool!

@marimeireles I still think it would be nicer to control push at the application level, rather than need to invent a new process for updating nginx configs for resources we want to push. But if you have ideas around how to do the other approach, let's discuss them here. :)

**Comment by marimeireles** [comment]
Reading more about the lib Karl found I learned that they have a [system](https://github.com/shreyanshk/flask-firehose#tracking-pushed-resources) to prevent pushing repeated files.
I didn't understand how it works, but I should make some tests with it tomorrow. If it works we probably won't need to implement a cookie.

**Comment by marimeireles** [comment]
Just a reminder that I have to keep an eye to see if firehose is doing it's job to prevent files from being pushed more than once.
I have to check if this is happening once this PR https://github.com/webcompat/webcompat.com/pull/2792 is deployed. @karlcow, can you please let me know when you do that?
Thank you.

**Comment by marimeireles** [comment]
The cache feature implemented on `flask-firehose` is working, so I don't need to do anything here.
