### ISSUE TITLE
How to optimize our use of favicons?

### ISSUE THREAD

**Issue by marimeireles** [webcompat/webcompat.com#2771]
Currently we have 5 or 6 different favicons and instead of downloading only the right one Firefox and Chrome download a bunch of different favicons. That sums up to more than 50kb and a bunch of new requests.

There are small res. favicons to show on the top of the tab and bigger ones to show on the new tab session, or when you download the website to be the icon of the website. 

According to Mike this might be a good low hanging fruit and we could just erase a bunch of those.

I want to learn more about how they work to understand which ones I can erase and if it's possible to optimize it downloading only the ones we're going to use. Mike said this would be a good starting point: https://mathiasbynens.be/notes/touch-icons

**Comment by magsout** [comment]
Hum, interesting because I was pretty sure that browsers just download only the one favicon depending on the size.

**Comment by magsout** [comment]
@marimeireles 
>Currently we have 5 or 6 different favicons and instead of downloading only the right one Firefox and Chrome download a bunch of different favicons. That sums up to more than 50kb and a bunch of new requests.

You see that in the devtools?

**Comment by marimeireles** [comment]
@magsout 

Yes. Here is a screenshot from the network tab on Chrome devtools:
<img width="610" alt="screen shot 2019-01-24 at 18 42 13" src="https://user-images.githubusercontent.com/17600982/51707234-d6ac8080-2007-11e9-8219-7db070da623c.png">

And here is one from Firefox:
<img width="432" alt="screen shot 2019-01-24 at 18 43 19" src="https://user-images.githubusercontent.com/17600982/51707335-15423b00-2008-11e9-9067-a21bdc515f23.png">

Firefox handles it better, apparently.

**Comment by karlcow** [comment]
On a fresh profile, empty cache browser.

Chrome Canary Version 73.0.3682.0 (Build officiel) canary (64 bits)
<img width="1150" alt="capture d ecran 2019-01-25 a 09 44 02" src="https://user-images.githubusercontent.com/505230/51717825-d783f780-2085-11e9-8096-f4479e40ecfb.png">

Firefox Nightly 66.0a1 (2019-01-24) (64-bit)
<img width="1152" alt="capture d ecran 2019-01-25 a 09 46 03" src="https://user-images.githubusercontent.com/505230/51717892-19ad3900-2086-11e9-8d26-a92e339f4d02.png">

So that seems to be working for me

then I did a request on https://webcompat.com/issues/1000
Firefox is not re-fetching the icons. It's in the cache.

<img width="1152" alt="capture d ecran 2019-01-25 a 09 49 09" src="https://user-images.githubusercontent.com/505230/51717997-7b6da300-2086-11e9-96d7-7fc2fa8fdc6b.png">

and same thing for Chrome Canary.

<img width="1150" alt="capture d ecran 2019-01-25 a 09 51 28" src="https://user-images.githubusercontent.com/505230/51718055-d7382c00-2086-11e9-8c7a-8ea95bfd8a56.png">

**Comment by karlcow** [comment]
The bad citizen here is Safari Tech Preview Release 74 (Safari 12.2, WebKit 14608.1.1.1)

<img width="1088" alt="capture d ecran 2019-01-25 a 10 30 19" src="https://user-images.githubusercontent.com/505230/51719319-5714c500-208c-11e9-9df1-b274a523c4d4.png">

**Comment by marimeireles** [comment]
* Look if there are open bugs on safari and chrome

**Comment by marimeireles** [comment]
I found a Chrome bug that apparently fixes this.
I can't reproduce this behavior anymore on Chrome.
Safari still shows this problem. I didn't find any bug logged in about it.

My plan is to simply erase most of the favicons. Maybe the 32x32 and the 196x196? I think 196 is kind of exaggerated but since we have the function to download the website to work as an app on mobile and Chrome for Android home screen icon requires this size to looks good maybe we should  keep it. 32x32 is the size broadly used by browsers. source[[1]](https://www.emergeinteractive.com/insights/detail/The-Essentials-of-FavIcons)[[2]](https://stackoverflow.com/a/19590415/10756713)

Mike said it'd be better to do that so we don't have to worry with giving maintenance to this.

**Comment by marimeireles** [comment]
I just found out that I can erase the 196 too.
We have a lot of different icons to interact with mobile and a lot of configuration specific to web app.

**Comment by marimeireles** [comment]
I don't think we need to drop support to the progressive app thing, what do you think @miketaylr ?
As long as it's not causing any problems I think we can keep it.

**Comment by miketaylr** [comment]
> I found a Chrome bug that apparently fixes this.

Can you link it here @marimeireles ? If there isn't a bug open for Safari, we should open one.

**Comment by marimeireles** [comment]
Here is the bug for [Chrome](https://chromium-review.googlesource.com/c/chromium/src/+/1323551/4).
I looked in the [Safari bug tracker](https://bugs.webkit.org/buglist.cgi?quicksearch=favicon) and found [this](https://bugs.webkit.org/show_bug.cgi?id=68861), but I'm not sure if it's the right thing... I don't think so.

**Comment by marimeireles** [comment]
Mike asked for a more extensive research so here is what I found:

Here is an [analysis](https://realfavicongenerator.net/favicon_checker?protocol=https&site=webcompat.com%2F) of webcompat's currently favicon compatibility.

I think we have to keep at least some icons, we need a specific icon for apple devices and one for Safari, at least. 

This [page](https://mobiforge.com/design-development/adding-favicons-in-a-multi-browser-multi-platform-world) offers a good amount of information of what each browser needs and it recommends a minimal setup for a webpage to be compatible with all browsers & devices:

* favicon.ico (with 16×16, 32×32 icon sizes)
* favicon-16x16.png: Modern equivalent of original ICO format
* favicon-32x32.png: Safari
* apple-touch-icon-180.png: Apple touch icon
* icon-192.png: Chrome/Android
* safari-pinned-tab.svg: Safari pinned tab SVG
* mstile-150x150.png: MS tile

The 192x192 image is used by Android Phone and Windows 8(or +) when the user downloads the website to use it as a progressive app. Since we're dropping our support to progressive apps I don't think we need to have that anymore.  [[1]](https://developers.google.com/web/fundamentals/app-install-banners/)[[2]](https://docs.microsoft.com/en-us/previous-versions/windows/internet-explorer/ie-developer/samples/gg491740(v=vs.85))

Without the progressive app functionality we also won't need the 192x192 for Android nor the mstile for Windows. According to this [website](https://realfavicongenerator.net/faq) I think we can also get rid of the 32x32 png, since it's only used by Safari and we already have a 32x32 image inside the favicon.ico.

So that leaves use with:

* favicon.ico (with 16×16, 32×32 icon sizes)
* favicon-16x16.png: Modern equivalent of original ICO format
* apple-touch-icon-180.png: Apple touch icon
* safari-pinned-tab.svg: Safari pinned tab SVG

What do you think @miketaylr ?

**Comment by marimeireles** [comment]
I just realized we don't have a 180x180 icon so I can use as an apple touch icon. Where can I find a nice image from webcompat's favicon so I can make one?

**Comment by marimeireles** [comment]
I found a 310x310.png file and converted it to 180x180. I think it looks fine:

![apple-touch-icon-180x180](https://user-images.githubusercontent.com/17600982/52919056-ea809500-32dc-11e9-84a4-2cf7770223f0.png)

With a 180 icon we don't need to have all of the other icons. Apple products will just use this image to scale to whatever size they need. Apparently, using a 180x180 icon is how Apple's website are doing it, so that's another good reason we do the same.

**Comment by marimeireles** [comment]
Should I add a no here, or maybe just erase it? Or we still want to be mobile capable?

```
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="mobile-web-app-capable" content="yes">
```

**Comment by marimeireles** [comment]
My PR contains these changes ^

**Comment by marimeireles** [comment]
If you don't want to drop support to the progressive app thing we can still do it with one 196x196 to android + a 180x180 to apple.

**Comment by marimeireles** [comment]
Here are some measures about the performance on Safari before & after changes:
Time in ms, size in kb.
The result in the table is the median between 4 tests for each page.

Before:

|              | Home page | Issue | New issue | All issues |
|--------------|-----------|-------|-----------|------------|
| Size         | 445.1     | 769.4 | 405       | 614.9      |
| Loading time | 315       | 199   | 273       | 258        |


After:

|         | Home page | Issue | New issue | All issues |
|--------------|-----------|-------|-----------|------------|
| Size         | 420.6     | 745   | 381       | 590.4      |
| Loading time | 276       | 165   | 245       | 234        |

We have an improvement of loading time of about 30ms per page in Safari.
Which is more or less 10%.
