### ISSUE TITLE
Test Staging performance using brotli as a zipper

### ISSUE THREAD

**Issue by marimeireles** [webcompat/webcompat.com#2772]
Continuing the exploration that began on #2751 . 
I just wanted to make things more organized.

**Comment by marimeireles** [comment]
Hey @miketaylr . To go forward I'll need your help here.
We need to install the [ngnix brotli module](https://github.com/google/ngx_brotli) on staging.

**Comment by marimeireles** [comment]
Also, according to [this](https://medium.com/@blikenoother/nginx-brotli-compression-developed-by-google-which-helps-reducing-18-latency-over-gzip-d9f5f5f28b92) article the preference over brotli should be automatic.

**Comment by miketaylr** [comment]
I'll need to come back to this in a few days, compiling the latest nginx with brotli support seems to make our server grumpy.

```
mike@staging-server:/usr/local/src$ sudo dpkg -i *.deb
[sudo] password for mike: 
dpkg: regarding nginx_1.14.2-1~bionic_amd64.deb containing nginx:
 nginx conflicts with nginx-common
  nginx-common (version 1.14.0-0ubuntu1.2) is present and installed.

dpkg: error processing archive nginx_1.14.2-1~bionic_amd64.deb (--install):
 conflicting packages - not installing nginx
Selecting previously unselected package nginx-dbg.
(Reading database ... 131236 files and directories currently installed.)
Preparing to unpack nginx-dbg_1.14.2-1~bionic_amd64.deb ...
Unpacking nginx-dbg (1.14.2-1~bionic) ...
dpkg: dependency problems prevent configuration of nginx-dbg:
 nginx-dbg depends on nginx (= 1.14.2-1~bionic); however:
  Version of nginx on system is 1.14.0-0ubuntu1.2.
  Version of nginx on system, provided by nginx-core:amd64, is <none>.

dpkg: error processing package nginx-dbg (--install):
 dependency problems - leaving unconfigured
Errors were encountered while processing:
 nginx_1.14.2-1~bionic_amd64.deb
 nginx-dbg
```

**Comment by marimeireles** [comment]
Maybe it's just because our server is a little outdated?

> nginx-dbg depends on nginx (= 1.14.2-1~bionic); however:
  Version of nginx on system is 1.14.0-0ubuntu1.2.

Or is it because our ubuntu is outdated? Because nginx-dbg was supposed to run on Ubuntu bionic?

**Comment by miketaylr** [comment]
Nah, we're running Ubuntu 18.04.1 LTS. Super modern.

**Comment by karlcow** [comment]
This might help 
https://www.tinywp.in/nginx-brotli/ This is recent

**Comment by karlcow** [comment]
also interesting comment at the end

> Please remember that Brotli is a new standard (even though, it is 3 years old). It works best if assets are compressed already. Nginx takes time to compress on the fly, especially using brotli. If you still wish to use it dynamically, you may want to check it Akamai’s in-depth research on how brotli fairs with gzip in terms of size and speed. Nevertheless, brotli does make a site a bit leaner, thus faster!

**Comment by karlcow** [comment]
The Akamai pointer to [Understanding Brotli's Potential](https://blogs.akamai.com/2016/02/understanding-brotlis-potential.html)

> Though Brotli slows down the higher the compression setting, it's entirely possible to trade-in some of those bytes for a faster compression setting. If you're going to replace GZIP for compression of dynamic assets, a Brotli quality of "4" is a good place to start. If you're running it ahead of time and queuing up those resources for a later request, then run it full blast and watch the bytes fade away.

**Comment by miketaylr** [comment]
OK, using https://github.com/angristan/nginx-autoinstall, I got this to work.

```
root@staging-server:~# nginx -V
nginx version: nginx/1.14.2
built by gcc 7.3.0 (Ubuntu 7.3.0-27ubuntu1~18.04) 
built with OpenSSL 1.1.0g  2 Nov 2017
TLS SNI support enabled
configure arguments: [snip a bunch] --add-module=/usr/local/src/nginx/modules/ngx_brotli
```

**Comment by karlcow** [comment]
so currently we still reply with gzip.

`content-encoding: gzip`

in 

```http
HTTP/2.0 200 OK
server: nginx/1.14.2
date: Thu, 21 Feb 2019 05:27:30 GMT
content-type: text/html; charset=utf-8
strict-transport-security: max-age=31536000; includeSubDomains;
x-content-type-options: nosniff
x-xss-protection: 1; mode=block
x-frame-options: DENY
content-security-policy: default-src 'self'; object-src 'none'; connect-src 'self' https://api.github.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' https://www.google-analytics.com https://*.githubusercontent.com data:; manifest-src 'self'; script-src 'self' https://www.google-analytics.com https://api.github.com 'nonce-09ead7382112d3bb53b6d3d38646a484aa206291'; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; base-uri 'self'; frame-ancestors 'self'; report-uri /csp-report
vary: Accept-Encoding, Cookie
content-encoding: gzip
X-Firefox-Spdy: h2
```

**Comment by marimeireles** [comment]
Yes, @karlcow.
I'm the responsible for changing this. I'm going to do this today! :)

**Comment by marimeireles** [comment]
Ok, so here is the frontend comparison between brotli vs. gzip:
(time in ms, median of 5 tests on Chrome)

**brotli homepage / gzip homepage**

total size: 250.5kb / 254.1kb
first paint: 1717 / 2013
visual complete: 1733 / 2000
last visual change: 1967 / 2533

**brotli 1754 / gzip 1754**

total size: 644.1kb / 640.4kb
first paint: 1527 / 1500
visual complete: 3500 / 3833
last visual change: 3500 / 3833

**brotli new / gzip new**

total size: 192.4kb / 196kb
first paint: 1469 / 1650
visual complete: 1900 / 2000
last visual change: 2167 / 2367

By these results I'd say it's worth it to use Brotli. But I remember Karl linked a Firefox bug about brotli consuming a lot of processing (or something?) so I intend to make some tests using perf-html and also some tests on my Nexus 5 to see if using this compressing method is really worth it.

**Comment by marimeireles** [comment]
I found the [bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1356686) and I can't reproduce it on our website. All of the process related to brotli consume 1ms.
![screen shot 2019-02-21 at 15 49 24](https://user-images.githubusercontent.com/17600982/53193671-52dab980-35f0-11e9-9e91-5c2c187eeb2b.png)

The bug wasn't fixed, though. I'll try to run some tests on Facebook just to check if the bug magically disappeared of for some weird reason it doesn't happen in our website.
(I did my tests on a brand new profile the only addon was the perf-html one)

**Comment by marimeireles** [comment]
The problem is still reproducible on Facebook. Maybe it's something related to their server interaction with Brotli?
<img width="1680" alt="screen shot 2019-02-21 at 16 25 57" src="https://user-images.githubusercontent.com/17600982/53196016-b3202a00-35f5-11e9-8111-72c99242ee02.png">

Taking these founds into account I think we should implement these changes on our production server. What do you think @miketaylr and @karlcow? Any other test I might be missing?

**Comment by marimeireles** [comment]
These are the results for mobile:

**brotli mobile home page / gzip mobile home page**

total size: 215.9kb / 217.1kb
first paint: 4365 / 4242
fully loaded: 13818 / 14268

**brotli mobile issue 1754 / gzip mobile issue 1754**

total size: 232.9kb / 229.7kb
first paint: 4364 / 4066
fully loaded: 13699 / 13113

**brotli mobile new / gzip mobile new**

total size: 168.3 / 167
first paint: 3189 / 4436
fully loaded: 11430 / 12076

All of them are pretty good except for the one that renders the single issue page. I'm suspecting that if brotli has to work a little bit more to compress a lot of images it starts to get too heavy to run in the mobile. I'll create a big issue with a lot of images and measure performance to see what happens.

**Comment by marimeireles** [comment]
Also, a thing that I found interesting is that if you look at the total size we're downloading it doesn't change much if we're using brotli or gzip but the performance increases a lot more than 1s in some cases. I don't know how to explain that.

**Comment by miketaylr** [comment]
If I understand correctly, it's interesting that the new issue page is slower, and the home page also is slower in it's time to first paint. But these are results in Chrome Desktop.

@marimeireles have you measured on a real phone, via remote debugging?

**Comment by miketaylr** [comment]
(maybe you have, it's not clear to me what "These are the results for mobile:" corresponds to in terms of device or network speed)

**Comment by marimeireles** [comment]
@miketaylr yes, but here are results from mobile

**Comment by marimeireles** [comment]
Firefox does have a worse performance with brotli with slower processors. 
I've made these tests using my Nexus 5 that has processing capabilities with good sampling around the world. I ran 5 tests for each page, the result here is the median of 5 runs. Time in ms, internet speed of 5mbps.

**brotli mobile home page / gzip mobile home page**

load time: 3040 / 3110
DOMContentloaded: 2630 / 2810
finish load time: 5320 / 4920
files transfered: 438.63kb, 193.15kb/ 438.63kb, 191.69kb
brotli decompressing time: 31 / 4

**brotli mobile new / gzip mobile new**

load time: 2690 / 3120
DOMContentloaded: 2050 / 2470
finish load time: 2650 / 3160
files transfered: 360.08kb, 142.32kb / 360.08kb, 140.91kb
brotli decompressing time: 32 / 6

**brotli mobile 1762 / gzip mobile 1762**

load time: 2520 / 3290
DOMContentloaded: 2460 / 3240
finish load time: 13390 / 14370
files transfered: 6.07mb, 5.73mb / 6.07mb, 5.73mb
brotli decompressing time: 20 / 3

There is some time of brotli decompression even when I only use gzip in our server. Something else is triggering this. I couldn't figure out what because I can't really read the [perf-html](http://bit.ly/2IM43PY) output.

Here are some considerations:

* I thought brotli could had been causing problems because it had a slow image decompression system, but that's wrong. The images are fetch from Github and brotli has nothing to do with them.

* I've tested extensively on both Chrome and Firefox mobile and desktop versions. The performance of brotli on mobile is always worse, I imagine it's because it has a hard time decompressing stuff on smaller processors. But seeing the results performance tends to improve if we're using brotli. The surprise for me was that brotli doesn't compress much better than gzip, in my analysis on Firefox mostly it didn't make a difference to compress stuff using brotli or gzip. I did a small research and it's very weird that I find these results according to this [post](https://blog.cloudflare.com/results-experimenting-brotli/) we should perceive bigger differences. My best guess to answer why our performance improve so much while we're using brotli is that even though brotli uses a lot of processing it decompress stuff much faster than gzip.

I'm interested in running some tests using a smaller compression level to see if our results improve.

**Comment by marimeireles** [comment]
I got some really sparse results while testing with other levels of compression on the new issue page:
(mobile firefox, time in ms)

Level 3: 28 34 32 23 33 median: 32
Level 4: 41 25 29 38 24 median: 29
Level 5: 29 16 32 31 45 median: 31

Here is a relation of sizes:

| Level | 3        | 4        | 5        |
|-------|----------|----------|----------|
| Size  | 145.14kb | 142.32kb | 136.18kb |

According to this data we should stick with the level 4 compression. From 4 to 5 there is some significantly size decrease, but I'm not sure if it's beneficial due to the small rize in the decompression time.

**Comment by marimeireles** [comment]
I also tested the load time of the page and using level 3 compression proved to be worse than level 5 and 4. Level 5 showed some similar results to level 4, but level 4 is still has the fastest rendering.
(tested on firefox mobile)

**brotli mobile home page**

load time: 3100
DOMContentloaded: 2740
finish load time: 5100
files transfered: 438.63kb, 186.29kb

**brotli mobile new**

load time: 2740
DOMContentloaded: 2030
finish load time: 2700
files transfered: 360.08kb, 136.18kb

**Comment by marimeireles** [comment]
(tested on firefox mobile)

Level 5 results:
**brotli mobile home page**

load time: 3100
DOMContentloaded: 2740
finish load time: 5100
files transfered: 438.63kb, 186.29kb

**brotli mobile new**

load time: 2740
DOMContentloaded: 2030
finish load time: 2700
files transfered: 360.08kb, 136.18kb

Level 3 results:
**brotli mobile new**
load time: 3500
DOMContentloaded: 2970
finish load time: 3590
files transfered: 360.08kb, 145.14kb
