### ISSUE TITLE
Make HTTP2 server push with Flask

### ISSUE THREAD

**Issue by marimeireles** [webcompat/webcompat.com#2778]
Mike said it'd be a good idea to use the same idea as this lib is using: https://github.com/jdaroesti/flask-http2-push to make the server push.

It seems pretty straightforward and I think it's a good option.

**Comment by karlcow** [comment]
https://github.com/jdaroesti/flask-http2-push/blob/master/flask_http2_push.py

**Comment by marimeireles** [comment]
Ok... Bad news, preload doesn't work on Firefox: https://caniuse.com/#feat=link-rel-preload and we [don't have a estimate](https://bugzilla.mozilla.org/show_bug.cgi?id=1394778#c65) for when will it be.
So this approach using preload doens't work... I'll try to find something else we can use.

**Comment by marimeireles** [comment]
I didn't find anything...
I was thinking about implementing this for Chrome... and not using push on Firefox, what do you think @karlcow or @miketaylr ... I don't know who to ping here.

**Comment by marimeireles** [comment]
I could push things directly from the server using `http_push` instead of preload, that'd push files to Firefox, but it's not worth it since it will push the files every time and it's much faster to just load the files from cache if it's not the first time the user access the website.

**Comment by karlcow** [comment]
> I was thinking about implementing this for Chrome... and not using push on Firefox,

but that would mean user agent sniffing, and I would avoid this at all cost (for such a feature).

We are not also a huge site, so maybe improving performances with HTTP/2 was a cool idea to explore but not yet worth implementing given the lack of support as you demonstrated. You discovered, studied, found a roadblock. It's part of the process. We are not forced to push it to the implementing end. We can close and put this on the back log until there is a better interop in between browsers.

**Comment by miketaylr** [comment]
> but that would mean user agent sniffing, and I would avoid this at all cost (for such a feature).

@karlcow would it really require UA sniffing? if we just send the push `Link` header with the request for the html, and the browser supports it, it will populate the preload/push cache and then there's a perf win. if it doesn't, nothing should happen (for Firefox, until https://bugzilla.mozilla.org/show_bug.cgi?id=1222633 is fixed).

**Comment by miketaylr** [comment]
Also, I'm pretty sure we do support http2 push? 

https://bugzilla.mozilla.org/show_bug.cgi?id=1150812

https://tools.ietf.org/html/rfc7540#section-8.2.1
https://searchfox.org/mozilla-central/search?q=PUSH_PROMISE&path=

I believe https://bugzilla.mozilla.org/show_bug.cgi?id=1222633 is for html `<link rel=preload>`, and has nothing to do with http2 push support. 

Frustratingly, Firefox DevTools don't differentiate pushes resources from non-pushed.

@marimeireles if you have the code implemented, it would be good to send in a PR so we can deploy to staging and do the measurements. Even if it results in a perf increase for only Chrome, it's still a perf win.

**Comment by miketaylr** [comment]
(we just need to ensure that https://nginx.org/en/docs/http/ngx_http_v2_module.html#http2_push_preload is turned on in the nginx config on staging)

**Comment by marimeireles** [comment]
> Also, I'm pretty sure we do support http2 push?

We do. It works if I use `http_push` on nginx instead of `preload`

> I believe https://bugzilla.mozilla.org/show_bug.cgi?id=1222633 is for html <link rel=preload>, and has nothing to do with http2 push support.

I thought it was the same thing. I'll try to find a way to analyze this. If I don't find any tool to measure push on Firefox measuring how long does a request take to be loaded with/without the preload push should be enough to discriminate if it's being used or not.

> (we just need to ensure that https://nginx.org/en/docs/http/ngx_http_v2_module.html#http2_push_preload is turned on in the nginx config on staging)

Yes. Good point. We can't forget about that, I've just fixed staging.

> if you have the code implemented

Okay! I'm just gonna trim it and I'll open a PR.

**Comment by karlcow** [comment]
> @karlcow would it really require UA sniffing? if we just send the push Link header with the request for the html, and the browser supports it, it will populate the preload/push cache and then there's a perf win. if it doesn't, nothing should happen (for Firefox, until https://bugzilla.mozilla.org/show_bug.cgi?id=1222633 is fixed).

Indeed probably. Let's try.

**Comment by karlcow** [comment]
We probably needs to rewrite it a bit. There are things which I'm mildly comfortable with in the current flask_http2_push.py
Let me check this today or tomorrow.

**Comment by karlcow** [comment]
Ah this one, [Flask Firehose](https://github.com/shreyanshk/flask-firehose), seems a lot better. 

* More recently maintained. 
* Do not use the python `global` but the `g` from flask
* Python 3 compatible

We could test it. 

We would just need to add it to requirements.txt and test it. 

@marimeireles Could you try locally before creating a PR? Thanks.

**Comment by marimeireles** [comment]
Nice found!
I'm going to run some tests here. Thanks @karlcow .

**Comment by marimeireles** [comment]
Can't forget to add `proxy_pass http://upstream;` to the md file if we use this. In our case upstream == http://staging.webcompat.com right @karlcow?

**Comment by marimeireles** [comment]
I'm having a hard time to figure out how to make this lib works.
I've set up a local server to run tests but it's not working when I try to push things from flask.
On the other hand when I try to push things using the nginx.conf file it works. Which makes me believe that there is something wrong with the lib we're using, even though it's super simple...

I talked to Mike and he proposed us to use [Quart](https://gitlab.com/pgjones/quart). Quart is designed to be fully compatible with the Flask public API, so hopefully we won't have any compat issues. I intend to look around this lib.

I'm also going to make a PR with the changes I made that's going to be merged to Staging to see if there is something wrong with my local server or if it's really the lib that doesn't work.

**Comment by karlcow** [comment]
@marimeireles 

>  I've set up a local server to run tests but it's not working when I try to push things from flask.

What is not working? :) The wrong HTTP headers? The wrong markup? Something else?

> On the other hand when I try to push things using the nginx.conf file it works.

How do you notice the difference? 

> I talked to Mike and he proposed us to use [Quart](https://gitlab.com/pgjones/quart). Quart is designed to be fully compatible with the Flask public API, so hopefully we won't have any compat issues. I intend to look around this lib.

As an exercise? Or as an intent to switch framework? As an exercise +1, but I don't think we should switch to an async framework :) Probably a lot of rewriting.

fwiw, I created an [issue](https://github.com/w3c/preload/issues/135) on the preload spec about conflicting HTTP and HTML `Link`/`link` with regards to my comments on the code.

**Comment by marimeireles** [comment]
> What is not working? :) The wrong HTTP headers? The wrong markup? Something else?

When I use the firehose lib to make push it's not working.  It doesn't make any difference, they don't add anything to the HTTP headers.

> How do you notice the difference?

By checking Chrome DevTools.

> As an exercise? Or as an intent to switch framework? As an exercise +1, but I don't think we should switch to an async framework :) Probably a lot of rewriting.

Not as an exercise. Yeah, I don't know anything about that. I started to read some blog posts on the internet and it seemed fairly simple but the lib is not well supported by libs other than the official one, so it might mean a lot of rewriting. Before dealing with that about that I'll try to write my own code.

> fwiw, I created an [issue](https://github.com/w3c/preload/issues/135) on the preload spec about conflicting HTTP and HTML `Link`/`link` with regards to [my comments on the code](https://github.com/webcompat/webcompat.com/pull/2792#discussion_r254121992).

That's cool! Thanks Karl :)

**Comment by karlcow** [comment]
> When I use the firehose lib to make push it's not working. It doesn't make any difference, they don't add anything to the HTTP headers.

So that's the surprising thing, because HTTP Link header was added for me as [shown in my comment](https://github.com/webcompat/webcompat.com/pull/2792#discussion_r254121992) in bare Flask + Firehose

Are you testing bare Flask + Firehose OR Flask + Firehose + nginx? I haven't tested with nginx. So I wonder if the difference partly comes from here.

**Comment by marimeireles** [comment]
> Are you testing bare Flask + Firehose OR Flask + Firehose + nginx? I haven't tested with nginx. So I wonder if the difference partly comes from here.

Oh, wow. Yeah, that's interesting. That's what I was trying to test by adding these changes to Staging on https://github.com/webcompat/webcompat.com/pull/2792.
So there is probably something wrong with my nginx.conf file. But it's pretty amazing, I spent hours looking at it. I probably read everything related to what I was trying to do in the internet and I didn't find the problem. Would you like to take a look in my file? Mike didn't find anything wrong either.

**Comment by karlcow** [comment]
>  So there is probably something wrong with my nginx.conf file. But it's pretty amazing, I spent hours looking at it. I probably read everything related to what I was trying to do in the internet and I didn't find the problem. Would you like to take a look in my file? Mike didn't find anything wrong either.

Sure! :) Sent me an email.

**Comment by marimeireles** [comment]
@karlcow deployed my test version to Staging and it's working like a charm.

<img width="1515" alt="screen shot 2019-02-06 at 20 51 11" src="https://user-images.githubusercontent.com/17600982/52380163-dd99b100-2a53-11e9-8451-7789fb3407e7.png">

<img width="1223" alt="screen shot 2019-02-06 at 21 11 38" src="https://user-images.githubusercontent.com/17600982/52380148-d70b3980-2a53-11e9-8622-54b7665b9ada.png">
