### ISSUE TITLE
Fix dev-env-setup.md around github client ID and client secret

### ISSUE THREAD

**Issue by laghee** [webcompat/webcompat.com#2782]
So in trying to set up webcompat on another laptop, I discovered that this: 

![screenshot 2019-01-28 13 39 53](https://user-images.githubusercontent.com/20972610/51836947-3c4b8600-2302-11e9-8ca0-faa255ee5a87.png)
...only works if you have owner status in the organization -- regular members following that link get a 404. I think we should either specify that or delete the suggestion (since it only applies to 4 people).

**Comment by karlcow** [comment]
@laghee https://github.com/webcompat/webcompat.com/blame/master/docs/dev-env-setup.md#L187

Do you suggest to remove in 

```md
3. Add values for `GITHUB_CLIENT_ID` and `GITHUB_CLIENT_SECRET`.
 If you're part of the [webcompat GitHub organization](https://github.com/webcompat), 
you can [get the client ID and client secret from GitHub](https://github.com/organizations/webcompat/settings/applications/). 
Otherwise, create your own local application 
([instructions here](https://github.com/settings/applications/new)) &mdash; when prompted
 for an "Authorization callback URL", use `http://localhost:5000/callback`, 
and take note of the client ID and client secret GitHub give you. 
```

so it becomes something like this?

> 3. Add values for `GITHUB_CLIENT_ID` and `GITHUB_CLIENT_SECRET`. Create your own local application ([instructions here](https://github.com/settings/applications/new)) &mdash; when prompted for an "Authorization callback URL", use `http://localhost:5000/callback`, and take note of the client ID and client secret GitHub give you. 

any improvements is welcome.

**Comment by laghee** [comment]
Yes, that seems like the simplest route. I might try to send in a PR later today.
