### ISSUE TITLE
GitHub username text is unclear

### ISSUE THREAD

**Issue by martinthomson** [webcompat/webcompat.com#2791]
This text...

> Sharing your GitHub username—without logging in—could help us with diagnosis. This will be publicly visible.

... combined with the two buttons "Report Anonymously" and "Report via GitHub" is confusing.

The without logging in might be read to imply that you are not going to be required to authorize an application or log in even if you choose the "Report via GitHub" option.  That is not the case.

Also, "This will be publicly visible" might be read to imply that none of the other information will be.  It's all public info (#2690).

My suggestion:

> Your GitHub username (optional):
> [ @github-username ]
> [ Report ] [ Login and Report ]

With the latter only becoming accessible when a GitHub username is entered (I think that this is already the case, but I didn't double-check).

**Comment by karlcow** [comment]
@martinthomson thanks for the comment.

Currently the flow is this (and sure can be improved as we are testing for the last couple of weeks this new feature aka github username)

1. Report Anonymously
2. Report Anonymously + GitHub username (which will add the username to the report, without the person having to login)
3. Report via GitHub (login process)

The difference in between 2 and 3 is that people do not have to give webcompat so many permissions.  See #655 This was the intent to cater for people who are uncomfortable with this big list of permissions.

Also the GitHub username field is only visible if the user is **not** already logged in. The flow you are proposing is not exactly doing the same thing (if I understood).

**Comment by martinthomson** [comment]
Thanks @karlcow,

I'm not suggesting a change in process.  I think that these are the right reporting flows, given the constraints as I understand them.  All I'm doing here is trying to suggest using different words on the form to better communicate what is going to happen.

**Comment by karlcow** [comment]
This relates to #2762 too.

**Comment by karlcow** [comment]
@martinthomson 

We changed things a bit. The username is not hotlinked anymore. 
see https://webcompat.com/issues/29931

![Capture d’écran 2019-04-25 à 12 58 04](https://user-images.githubusercontent.com/505230/56708994-d7b19300-6759-11e9-874b-5627f547f43d.png)
![Capture d’écran 2019-04-25 à 12 58 23](https://user-images.githubusercontent.com/505230/56708995-d7b19300-6759-11e9-832c-87745b96f386.png)

And the wording has been tweaked.

![Capture d’écran 2019-04-25 à 13 01 29](https://user-images.githubusercontent.com/505230/56709067-4abb0980-675a-11e9-85e8-80743eeb1a08.png)

Let's see if that improves thing a bit. 

Thanks for the feedback.

**Comment by martinthomson** [comment]
Maybe remove the "publicly visible" bit from the github username field. It is redundant now (and thus still a little confusing).
