### ISSUE TITLE
can't submit on Firefox beta 66 on Android (s8)

### ISSUE THREAD

**Issue by rpavlik** [webcompat/webcompat.com#2796]
Ironically... Clicking the buttons did change the color, in what looked like it might be a hover effect, but could not submit. Tried removing the screen cast I had attached (made with the Samsung smart select tool) from the upload a screenshot box, but that didn't help. Neither did closing the app (swiping away on Samsung triggers the over-eager process killer and sometimes helps with Firefox bugs) and reopening it.

**Comment by rpavlik** [comment]
Just verified that it does work ok in Firefox stable 65 on Android, used that to submit the issue I found.

**Comment by softvision-sergiulogigan** [comment]
I have just filed https://github.com/webcompat/web-bugs/issues/25836 from a Samsung Galaxy S8, Android  8, 1440 x 2960 pixels (~570 ppi pixel density) and used Firefox Beta 66.0b6

@rpavlik do you have some add-ons installed that may cause the described behavior?

**Comment by rpavlik** [comment]
Only relevant add-on is ublock origin. Will try it again next time I find a broken site.

**Comment by karlcow** [comment]
Two possibilities. It could be uBlock. but it could also be the screencast.

**Comment by karlcow** [comment]
@rpavlik does it work without addons?

**Comment by karlcow** [comment]
I'm closing this for now. It's the only report of this sort we got so far. Please reopen with more details.
