### ISSUE TITLE
Expose assigned status on issue page

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat.com#2799]
Not sure we need a full-blown "assignee editor", but perhaps an "assign myself" button, with a keyboard shortcut for convenience.

Probably OK to hard-code a list of people who can be assigned to the diagnosis team, at least to start with.

We would just use the regular edit an issue API, updating the `assignees` field: https://developer.github.com/v3/issues/#edit-an-issue

**Comment by karlcow** [comment]
Maybe the hard-coded people needs to be in the config file. 
@miketaylr do you want to work on that?

**Comment by karlcow** [comment]
@miketaylr do we still want to do that? Or we close it?

**Comment by miketaylr** [comment]
I think we can close it and re-visit if we have a useful use case. Thanks.

(And sorry for missing the other ping. 💌 )
