### ISSUE TITLE
Update lodash to any version >=4.17.1

### ISSUE THREAD

**Issue by marimeireles** [webcompat/webcompat.com#2807]
Our currently dependency tree:

├─┬ eslint@5.12.1
│ ├─┬ inquirer@6.2.1
│ │ └── lodash@4.17.11  deduped
│ ├── lodash@4.17.11
│ └─┬ table@5.2.1
│   └── lodash@4.17.11  deduped
├─┬ grunt@1.0.3
│ ├─┬ grunt-legacy-log@2.0.0
│ │ ├─┬ grunt-legacy-log-utils@2.0.1
│ │ │ └── lodash@4.17.11  deduped
│ │ └── lodash@4.17.11  deduped
│ └─┬ grunt-legacy-util@1.1.1
│   └── lodash@4.17.11  deduped
├─┬ grunt-contrib-jst@1.0.0
│ └── lodash@2.4.2
├─┬ grunt-contrib-watch@1.1.0
│ ├─┬ async@2.6.1
│ │ └── lodash@4.17.11  deduped
│ ├─┬ gaze@1.1.3
│ │ └─┬ globule@1.2.1
│ │   └── lodash@4.17.11  deduped
│ └── lodash@4.17.11  deduped
├─┬ handlebars@4.1.0
│ └─┬ async@2.6.2
│   └── lodash@4.17.11  deduped
├─┬ intern@4.4.1
│ ├─┬ benchmark@2.1.4
│ │ └── lodash@4.17.11  deduped
│ ├─┬ istanbul-lib-instrument@1.10.2
│ │ ├─┬ babel-generator@6.26.1
│ │ │ └── lodash@4.17.11  deduped
│ │ ├─┬ babel-template@6.26.0
│ │ │ └── lodash@4.17.11  deduped
│ │ ├─┬ babel-traverse@6.26.0
│ │ │ └── lodash@4.17.11  deduped
│ │ └─┬ babel-types@6.26.0
│ │   └── lodash@4.17.11  deduped
│ └── lodash@4.17.11  deduped
├─┬ lint-staged@8.1.0
│ └── lodash@4.17.11  deduped
├─┬ postcss-reporter@6.0.1
│ └── lodash@4.17.11  deduped
├─┬ stylelint@9.10.1
│ ├── lodash@4.17.11  deduped
│ └─┬ postcss-jsx@0.36.0
│   └─┬ @babel/core@7.2.2
│     ├─┬ @babel/generator@7.2.2
│     │ └── lodash@4.17.11  deduped
│     ├─┬ @babel/traverse@7.2.3
│     │ └── lodash@4.17.11  deduped
│     ├─┬ @babel/types@7.2.2
│     │ └── lodash@4.17.11  deduped
│     └── lodash@4.17.11  deduped
├─┬ stylelint-order@2.0.0
│ ├── lodash@4.17.11  deduped
│ └─┬ postcss-sorting@4.0.1
│   └── lodash@4.17.11  deduped
└─┬ svg-sprite-generator@0.0.7
  └─┬ cheerio@0.19.0
    └── lodash@3.10.1

**Comment by marimeireles** [comment]
There is an old issue (https://github.com/webcompat/webcompat.com/issues/1699) asking to update it to version 4.0.0, but that's too old now. It's not relevant anymore so I'll close it.

**Comment by marimeireles** [comment]
How can we fix it?
By adding lodash to our package.json file and specifying the version?

**Comment by miketaylr** [comment]
@marimeireles why do we want to upgrade it? is it a security thing? or feature thing?

**Comment by miketaylr** [comment]
> There is an old issue (#1699) asking to update it to version 4.0.0, but that's too old now.

(And that issue is about the client lib, not anything inside node_modules)

**Comment by marimeireles** [comment]
It's a security thing.

> 
(And that issue is about the client lib, not anything inside node_modules)

I'll reopen it then.
