### ISSUE TITLE
Test if fetching the fonts from our server is faster than fetching from Google

### ISSUE THREAD

**Issue by marimeireles** [webcompat/webcompat.com#2809]
This issue is somewhat related to https://github.com/webcompat/webcompat.com/issues/2750.

**Comment by marimeireles** [comment]
* We don't have to add anything to our mime.types file because it already has the woffs formats by default.

I tested and found this tool really helpful to download the correct set of fonts: https://github.com/fontello/fontello/wiki/How-to-setup-server-to-serve-fonts

You just have to run the command:
```
./google-font-download \
    "'Open Sans:400'" "'Open Sans:600'" \
    "'Source Sans Pro:300'" "'Source Sans Pro:400'"
```

**Comment by marimeireles** [comment]
Currently this are our stats for dealing with text in the new issue page:
(time in ms, median of 5 tests on Chrome)

CSS request time: 141
CSS size: 964b
Fonts request time: 112
Fonts size: 29.6kb
First paint: 1309
Fully loaded: 3587
First visual change: 1333

Time on mobile to load the font since first paint:
546ms in a internet speed of 500~600kbps
848ms in a internet speed of 200~300kbps

**Comment by marimeireles** [comment]
I found a [utility](https://github.com/filamentgroup/glyphhanger#installing-pyftsubset) capable of subsetting the webfonts we use based on the chars that exists in webcompat.com. I was able to significantly decrease the size of the files!

<img width="971" alt="screen shot 2019-02-21 at 10 37 37" src="https://user-images.githubusercontent.com/17600982/53172817-0332c880-35c5-11e9-8356-c83d9357bcca.png">

@karlcow let me know if you want me to send you these subsetted files somehow or if you want to run the tool yourself.

**Comment by karlcow** [comment]
I'll check that on Monday (JST).

**Comment by karlcow** [comment]
(just for memory)
downloading font locally also means that there is a risk in the future that bugs in the fonts are not fixed, because it's… a local copy.

@marimeireles which kind of subsetting do you want to do on the fonts.

> based on the chars that exists in webcompat.com.

which chars exists?

We already have a static font directory. :) Do you need something else? Apart of the fonts inside.
https://github.com/webcompat/webcompat.com/tree/master/webcompat/static/font

**Comment by marimeireles** [comment]
> downloading font locally also means that there is a risk in the future that bugs in the fonts are not fixed, because it's… a local copy.

Yes. That's a downside we have to consider. If hosting fonts doesn't make a lot of difference I don't think we should do it.

> which chars exists?

Sorry, these: U+20,U+21,U+27,U+2A,U+2C-2E,U+30-32,U+34-36,U+38-3A,U+3F,U+41-4A,U+4C-59,U+61-7A,U+2014,U+2019,U+1F389

> We already have a static font directory. :) Do you need something else? Apart of the fonts inside.

I don't understand. What's inside this webcompat font?

The meaning of this issue is to fetch all of the fonts we currently use on webcompat.com from our server instead of google's.

**Comment by karlcow** [comment]
> I don't understand. What's inside this webcompat font?

I was replying to the earlier comment. 

> And then create a directory for the fonts in the root of our server, if I got it right.

the directory already exists. Then to answer to "What's inside this webcompat font?" 
If you follow the [link above](https://github.com/webcompat/webcompat.com/tree/master/webcompat/static/font) 😉 , you can see that there is a `webcompat/` directory, we could create more there.


> Sorry, these: U+20,U+21,U+27,U+2A,U+2C-2E,U+30-32,U+34-36,U+38-3A,U+3F,U+41-4A,U+4C-59,U+61-7A,U+2014,U+2019,U+1F389

Sorry I have difficulties to understand. I understand the subsetting process. 

* U+20 = space
* U+21 = !
* U+27 = '
* U+2A = *
* U+2C-2E = , -, .
* etc.
* U+1F389 = Party emoji (!?)


which are really basic characters, roman alphabet and numbers. Which seems to target source code in general but without the possibility of strange characters in comments (French, Chinese, Japanese, Korean, etc.), with some specific addition like the party emoji. The ranges are a bit bizarre. For example, the `+` plus sign is not included. The number `3` and `7` are not included, etc.

@marimeireles I guess a tool was used on a page for the sample? which tool? which page(s)?

**Comment by marimeireles** [comment]
> the directory already exists. Then to answer to "What's inside this webcompat font?"
If you follow the [link above](https://github.com/webcompat/webcompat.com/tree/master/webcompat/static/font) 😉 , you can see that there is a `webcompat/` directory, we could create more there.

Oh, okay! Got it.

> @marimeireles I guess a tool was used on a page for the sample? which tool? which page(s)?

Sorry for not giving you the complete information. I've used [glyphhanger](https://github.com/filamentgroup/glyphhanger#installing-pyftsubset) to download the fonts. 
Glyphanger uses a tool called `fonttools` that allows you to subset the fonts that exist in your website. It crawls your website and returns you the fonts subsets you're using. I thought it'd be a good idea to use it, I didn't really check (which was a mistake!) because I read more than one article recommending me to use that... But this doesn't seem to work well. Thanks for actually checking the subset.

I'm sorry I was so confused at this thing. I'll upload the complete font sets tomorrow morning.
Thanks for clearing things up!

**Comment by karlcow** [comment]
Closing the issue. see the Comment on the PR #2815 for the reasoning.
Thanks a lot.
