### ISSUE TITLE
Adding Contributors: Ciprian Ciocan 

### ISSUE THREAD

**Issue by softvision-oana-arbuzov** [webcompat/webcompat.com#2817]
@cipriansv would you like to be on this page? https://webcompat.com/contributors

Could you share with us the same type of details that other people have sent?

**Comment by karlcow** [comment]
Reminder for @cipriansv or tell us if you want us to close it :)

**Comment by cipriansv** [comment]
IT enthusiast. Basketball referee on my spare time. Love coffee and good food.

**Comment by karlcow** [comment]
Thanks.
So if anyone wants to jump on this. 
The file to modify is https://github.com/webcompat/webcompat.com/blob/eae44eda6b0e1db226d9c4acaa90839c99199593/webcompat/templates/contributors.html#L47-L66
