### ISSUE TITLE
Create a local list of labels to improve perf and avoid pagination issues

### ISSUE THREAD

**Issue by laghee** [webcompat/webcompat.com#2830]
Stealing my own comment on The current PR
https://github.com/webcompat/webcompat.com/pull/2784#issuecomment-458407014

```python
@api.route('/issues/labels')
@mockable_response
def get_repo_labels():
    """XHR endpoint to get all possible labels in a repo."""
    params = request.args.copy()
    path = 'repos/{0}/labels'.format(REPO_PATH)
    return api_request('get', path, params=params)
```

I propose we go with a local list of labels.

## local
We do not request milestones each time we use them because we consider them stable. We could perfectly through a CRON job (for example, once a day or once a hour), have a script creating a local JSON file with the list of all labels. The JSON is then local, cached, with the appropriate ETAGs, and can be requested by the JS to build the menu without having to make any requests to GitHub. Performance++

Possible issue:
Being unsettled because the labels are not sync on webcompat.com with what exist on GitHub. Though currently… we don't have the end of the list at all… so probably an improvement. 😛 

`issues/labels` will read a file and we can probably have a bit of application caching for this as well. 

I will close the current PR.

* [ ] create a script to fetch the full labels list
  * https://api.github.com/repos/webcompat/web-bugs/labels
  * This returns a json which looks like
```json
[
  {
    "id": 887136356,
    "node_id": "MDU6TGFiZWw4ODcxMzYzNTY=",
    "url": "https://api.github.com/repos/webcompat/web-bugs/labels/Pre-triage",
    "name": "Pre-triage",
    "color": "f6ff84",
    "default": false
  },
  {
    "id": 904761165,
    "node_id": "MDU6TGFiZWw5MDQ3NjExNjU=",
    "url": "https://api.github.com/repos/webcompat/web-bugs/labels/Re-triaged",
    "name": "Re-triaged",
    "color": "30c148",
    "default": false
  },
```
The HTTP headers contains
```
<https://api.github.com/repositories/17914657/labels?page=2>; rel="next", <https://api.github.com/repositories/17914657/labels?page=6>; rel="last"
``` 
This gives the pagination requests.

* [ ] store the data in a utf-8 text? document with one word per line or in a JSON, maybe the same format that the JS is expecting. To discuss
```
Pre-triage
Re-triaged
…
```
* [ ] create a cron which run this script every x minutes.
* [ ] create a function to convert to the data (if store in text)
* [ ] adjust the route to read the data from the file.
* [ ] check the notion of application python caching for avoiding to re-read the file on the filesystem if not necessary at each request.

@laghee 

1. do you still want to work on this?
2. if yes do you prefer to have a fresh issue about it?

Thanks.

_Originally posted by @karlcow in https://github.com/webcompat/webcompat.com/issues/2726#issuecomment-477005645_

**Comment by laghee** [comment]
Thanks, @karlcow! I'd be happy to pick this up again. I went ahead and made this issue since the direction essentially changed re: pagination --> local list.

**Comment by laghee** [comment]
OK, @karlcow, I have some questions about the CRON job. I know we have a NGINX server, but I'm not 100% sure what kind of environment it lives in. So I'm wondering in what language or syntax the script for this should be written. Perl? Bash? Either? Something else? And where do I put it exactly? 😜

**Comment by karlcow** [comment]
@laghee ooops sorry, completely missed that. 
You can write in python. that would be the simplest as we already run python on the server.
