### ISSUE TITLE
Uppercase extension for images filename are rejected in comments

### ISSUE THREAD

**Issue by karlcow** [webcompat/webcompat.com#2837]
This seems to be a regression as it was already fixed in #802 

Steps to reproduce. 

1. Use an image with `blah.PNG`
2. Go to comment section, upload the image.
3. Enjoy!

<img width="746" alt="Capture d’écran 2019-04-08 à 08 24 44" src="https://user-images.githubusercontent.com/505230/55691342-452e9700-59d8-11e9-88fb-00f2b5afd591.png">

* [ ] Check that Uppercase extensions are working on JS client side
* [ ] Check that uppercase extensioons are working on python server side
* [ ] Tests for the uploaders both JS and Python cover uppercase extensions name

Reported on IRC by @alex-mayorga

**Comment by marimeireles** [comment]
hmm
could the bug be because of this line?

https://github.com/webcompat/webcompat.com/blob/94980e4aa05129988e0253811008eeef5e077af6/webcompat/static/js/lib/bugform.js#L293

**Comment by marimeireles** [comment]
That only happens for me in the comment session for me.
When I tried to create a new issue with a `JPEG` image it worked but when I try to add any of these formats uppercased in a comment I get this same error.
So it's probably not that https://github.com/webcompat/webcompat.com/issues/2837#issuecomment-480801466

**Comment by marimeireles** [comment]
I think I found the problem...
We were missing a lowercase conversion in line 275:
https://github.com/webcompat/webcompat.com/blob/94980e4aa05129988e0253811008eeef5e077af6/webcompat/static/js/lib/issues.js#L275-L276

**Comment by karlcow** [comment]
Very good @marimeireles and it has been like this for a long time.
https://github.com/webcompat/webcompat.com/blame/3021f73fcdf43ef2b305d4167c6d1b8a97f10280/webcompat/static/js/lib/issues.js#L212-L223
