### ISSUE TITLE
Adds type-mobify to EXTRAL_LABELS

### ISSUE THREAD

**Issue by karlcow** [webcompat/webcompat.com#2845]
In the case where we will be able to detect from the reporter add-on that the site is using mobify, we will make it possible to add it as a valid extra label.

see mozilla/webcompat-team-okrs#79

**Comment by karlcow** [comment]
Client side will be handled by https://bugzilla.mozilla.org/show_bug.cgi?id=1544359

**Comment by miketaylr** [comment]
https://github.com/webcompat/webcompat.com/blob/master/config/__init__.py#L185
