### ISSUE TITLE
Speaking title for homepage

### ISSUE THREAD

**Issue by rraue** [webcompat/webcompat.com#2846]
The title of the hoepage is set right now to `<title>Web Compatibility | webcompat.com</title>` and thats not very "speaking" and the url in the title is redundand, as the url is mostly visible anyways. For a better CTR and understanding for users what the page is about I would set the H1 as the title:
`<title>Bug reporting for the web | Web Compatibility</title>` or even more actionable:
`<title>Report a bug for the web | Web Compatibility</title>`

**Comment by karlcow** [comment]
@rraue thanks for the feedback.

Yes that could be done. Setting this as good first bug. 
The [layout.html](https://github.com/webcompat/webcompat.com/blob/master/webcompat/templates/layout.html) template needs to be edited.

https://github.com/webcompat/webcompat.com/blob/38c6835ee28900601910ad0afbf43b90a31b3169/webcompat/templates/layout.html#L4


* These are the [contribution guidelines](https://github.com/webcompat/webcompat.com/blob/master/docs/pr-coding-guidelines.md).
* Make sure that [all the tests are still passing](https://github.com/webcompat/webcompat.com/blob/master/docs/tests.md).

**Comment by rraue** [comment]
I talked to @zoepage she helped me to adjust this change. better set a title in index.html than change the default in layout.html.
