### ISSUE TITLE
The form breaks reports with HTML snippets

### ISSUE THREAD

**Issue by softvision-sergiulogigan** [webcompat/webcompat.com#2849]
Originally posted here: https://github.com/webcompat/web-bugs/issues/29412

**URL**: https://webcompat.com/issues/29411

**Browser / Version**: Firefox 68.0
**Operating System**: Mac OS X 10.14
**Tested Another Browser**: No

**Problem type**: Something else
**Description**: This webcompat form doesn't escape HTML
**Steps to Reproduce**:
The form doesn't make it clear it expects markdown. I assumed it's plain text, and pasted in an HTML snippet as part of my report. The HTML was lost, so you've got an incomplete report.

The form should change `<` to `&lt;` instead of stripping HTML.
[![Screenshot Description](https://webcompat.com/uploads/2019/4/09482d3e-74d3-4629-8f5b-cacf7217fdf3-thumb.jpeg)](https://webcompat.com/uploads/2019/4/09482d3e-74d3-4629-8f5b-cacf7217fdf3.jpeg)

**Comment by karlcow** [comment]
I will close this as wontfix. Because it's not us escaping the HTML in this case, but… 🥁 github. :)

I will fix the initial post.

**Comment by karlcow** [comment]
That said we can probably add a message about markdown.
