### ISSUE TITLE
Consider adding `engine-gecko` label for Firefox browsers?

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat.com#2856]
A proposal -- curious about other people's input here.

I would like us to add a label -- the exact wording doesn't matter to me -- that captures that the browser is a Mozilla-produced product running on Gecko.

The use case is I want to track all issues on webcompat.com that affect Gecko-based Firefox browsers.

Currently, GitHub search doesn't allow logical OR searches. 

So instead of having something like `... label:browser-firefox OR label:firefox-mobile..`, etc., I need to do 6 queries. In addition to firefox and firefox-mobile, we also have `browser-focus-geckoview` and `browser-geckoview` and `browser-firefox-reality`, and `browser-fenix`.

Thoughts? @karlcow @adamopenweb @webcompat/core-developers ?

**Comment by wisniewskit** [comment]
Would this be intended to include Gecko browsers like Waterfox (for the rare report we get in that regard), or just the Mozilla releases?

**Comment by miketaylr** [comment]
> Would this be intended to include Gecko browsers like Waterfox (for the rare report we get in that regard), or just the Mozilla releases?

I thought about this, and I'm not 100% sure. If it's about UA sniffing, probably not. But bugs that stem from core Gecko platform differences would be good to capture.

**Comment by tagawa** [comment]
The concept sounds good to me. My belief is that labels should be honest about what they represent, so a `browser-gecko` label would include all Gecko browsers, e.g. Waterfox. If it's just for Mozilla browsers then `browser-mozilla` seems a better label IMO.

Alternatively, existing labels seem to have a kind of hierarchical naming, e.g. `browser-firefox` and `browser-firefox-mobile`, so if it's for Mozilla-only Gecko browsers then how about `browser-mozilla-gecko` or `browser-gecko-mozilla`?

**Comment by karlcow** [comment]
> Alternatively, existing labels seem to have a kind of hierarchical naming

There's a plan to get away from this 🤣 but I didn't get the time to punch it through. 
see #997 and #2531

**Comment by karlcow** [comment]
* engine-gecko
* engine-blink
* engine-webkit

are the 3 main engines which still exist.

Maybe a bit of engine-presto for Opera Mini, but I'm not even sure. 

The most difficult part is how to identify them, because they usually don't advertise themselves. 
A google example is Firefox Focus on Android which has both a webkit and a geckoview.

I'm interested to understand the false positives we would get with this system.

**Comment by miketaylr** [comment]
Yeah, identifying them wouldn't be perfect. 

We could just create some kind of mapping of known browser-products <-> browser-engines and update it as we went along. Or, not bother with the other engines until someone has a use-case for the data. :p

**Comment by miketaylr** [comment]
> We could just create some kind of mapping of known browser-products <-> browser-engines and update it as we went along

I think I'm gonna go with that. It won't be perfect, but we can improve it in the future.

**Comment by miketaylr** [comment]
(thanks for the input everyone)

**Comment by karlcow** [comment]
> So instead of having something like ... label:browser-firefox OR label:firefox-mobile.., etc., I need to do 6 queries. In addition to firefox and firefox-mobile, we also have browser-focus-geckoview and browser-geckoview and browser-firefox-reality, and browser-fenix.

btw is the goal to just select firefox. 
Then the move in #2531 is supposed to solve that.

**Comment by karlcow** [comment]
@miketaylr Also… we can't do indeed `OR`, but we can do negative `AND`.

I'm using that for diagnosis list and to know if there is a lot to do. :)
For example
[`is:open is:issue milestone:needsdiagnosis sort:comments-asc label:severity-important -label:browser-chrome -label:browser-chrome-mobile -label:browser-samsung `](https://github.com/webcompat/web-bugs/issues?utf8=%E2%9C%93&q=is%3Aopen+is%3Aissue+milestone%3Aneedsdiagnosis+sort%3Acomments-asc+label%3Aseverity-important+-label%3Abrowser-chrome+-label%3Abrowser-chrome-mobile+-label%3Abrowser-samsung)
