### ISSUE TITLE
Update GitHub issue template on webcompat/web-bugs

### ISSUE THREAD

**Issue by reinhart1010** [webcompat/webcompat.com#2861]
GitHub recently updated their templates guide, outlined in https://help.github.com/en/articles/about-issue-and-pull-request-templates. The web-bugs/ISSUE_TEMPLATE.md page now shows a warning.

![image](https://user-images.githubusercontent.com/17312341/57180483-17435200-6eb3-11e9-8251-52f7da6d2cf4.png)

Furthermore, the template seems to be updated to reflect current issue types on webcompat.com.

**Comment by karlcow** [comment]
Thanks a lot @reinhart1010 

This has been done in https://github.com/webcompat/web-bugs/commit/c66a776634e6da6859a47d88b2778bd82c015481
and https://github.com/webcompat/web-bugs/commit/973a9b1981cd29bec34eb525e51f0724fe3b5b31
