### ISSUE TITLE
CORS header ‘Access-Control-Allow-Origin’ missing

### ISSUE THREAD

**Issue by magsout** [webcompat/webcompat.com#2866]
@miketaylr in order to move webcomapt dashboad on metrics, is possible to enable CORS on webcompat.com ?

I get this error:

![Capture d’écran 2019-05-10 à 21 51 36](https://user-images.githubusercontent.com/1997108/57552963-cd081800-736d-11e9-87b9-bf3548418556.png)

**Comment by miketaylr** [comment]
@magsout yeah, we can whitelist the domains we want to talk to. We just want `http://webcompat-dashboard.herokuapp.com`, right?

**Comment by magsout** [comment]
@mikeraylr exactly, just need to figure out how handle webcompat.com on localhost.

**Comment by magsout** [comment]
@miketaylr one thing, bout PR. I think it would be better to add a regexp. For example a small list of URL created during a PR:
- https://webcompat-dashboard-pr-176.herokuapp.com/
- https://webcompat-dashboard-pr-168.herokuapp.com/
- https://webcompat-dashboard-pr-173.herokuapp.com/

**Comment by magsout** [comment]
@miketaylr @karlcow same thing happens locally, do you know how I can allowed cors on webcompat.com?

**Comment by magsout** [comment]
![Capture d’écran 2019-05-15 à 11 01 51](https://user-images.githubusercontent.com/1997108/57763034-e8be4600-7700-11e9-8145-682d5cb4906d.png)

**Comment by miketaylr** [comment]
I'm not sure allowing localhost via CORS is possible... doing some reading:

`security.fileuri.strict_origin_policy` set to false should maybe be a SUPER UNSAFE workaround, don't surf the internet with this disabled.

For CORS, we have a few options: `Access-Control-Allow-Origin: *`
I'm not sure if setting to `http://localhost:5000` will work, but we could test on staging.

The only wildcard CORS allows is `*`, but other options would be to inspect the incoming request and echo back the PR origin if it matched a regexp our server knew about.

I would probably add CORS headers here: https://github.com/webcompat/webcompat.com/blob/81c9c079a6bb272a7f6925b57bcb357b513c6973/webcompat/helpers.py#L480-L490

@magsout to get unstuck, you could say `if localhost: add this header` for you local instance.

@karlcow, WDYT? Should we enabled cors for `*` on production? Or add the "echo back" approach to be more restrictive?

**Comment by magsout** [comment]
@miketaylr oh cool, thanks. I have add:
```
    if not app.config['LOCALHOST']:
        response.headers['Strict-Transport-Security'] = 'max-age=31536000; includeSubDomains;'  # noqa
    response.headers['X-Content-Type-Options'] = 'nosniff'
    response.headers['X-XSS-Protection'] = '1; mode=block'
    response.headers['X-Frame-Options'] = 'DENY'
    if app.config['LOCALHOST']:
        response.headers['Access-Control-Allow-Origin'] = '*'
```

**Comment by miketaylr** [comment]
@magsout i think this would be fine to add to the project, if you would like to send a PR (and not have to maintain patches / worry about committing them).

**Comment by miketaylr** [comment]
Oh, but this doesn't solve the PR deploy issue, does it.

> other options would be to inspect the incoming request and echo back the PR origin if it matched a regexp our server knew about.

This wouldn't be terribly hard to implement, as a solution for that.

**Comment by karlcow** [comment]
> @karlcow, WDYT? Should we enabled cors for `*` on production? Or add the "echo back" approach to be more restrictive?

i honestly don't have an opinion both ways.

**Comment by karlcow** [comment]
@magsout the dashboard you need to move from webcompat is https://webcompat.com/dashboard/triage ?

if yes you are using only the endpoint aka the route generating the JSON request.
and the ui will be done by the webcompat-metrics-client ?

if yes to everything, so then why not moving the code of the dashboard to webcompat-metrics-server. 
The current code has 0 impact on webcompat.com. except using some of the function for requesting data, but we have that on the other side too.

**Comment by karlcow** [comment]
Given https://github.com/webcompat/webcompat-metrics-client/issues/172
I think it would be easier to move the code.

**Comment by magsout** [comment]
@karlcow it’s a yes for everything. 

>The current code has 0 impact on webcompat.com. except using some of the function for requesting data, but we have that on the other side too.

I didn’t know about that.

**Comment by magsout** [comment]
we should close this issue, @karlcow move the API on  Ochazuke https://github.com/webcompat/webcompat-metrics-server/pull/105
