### ISSUE TITLE
extra-labels do not contain type-fastclick

### ISSUE THREAD

**Issue by karlcow** [webcompat/webcompat.com#2869]
In #2823 we added the ability to add a label type-fastclick automatically to the newly created issue.

@wisniewskit gave the bug reporter the possibility to detect automatically. And it is working because the bugs details have `hasFastClick: true`, but what is missing is the extra-labels. 

```
<!-- @browser: Firefox Mobile 68.0 -->
<!-- @ua_header: Mozilla/5.0 (Android 10; Mobile; rv:68.0) Gecko/68.0 Firefox/68.0 -->
<!-- @reported_with: mobile-reporter -->

…

<details>
<summary>Browser Configuration</summary>
<ul>
  …
  <li>hasFastClick: true</li>
  …
</ul>

</details>
```

The syntax is 

```
<!-- @extra_labels: type-fastclick -->
```

In https://bugzilla.mozilla.org/show_bug.cgi?id=1535479 the code in charge for the labels:

https://searchfox.org/mozilla-central/rev/cc280c4be94ff8cf64a27cc9b3d6831ffa49fa45/mobile/android/extensions/report-site-issue/background.js#189-196

oh `label` vs `extra_labels`?

Does that mean it fails for any `extra_labels`

**Comment by karlcow** [comment]
https://github.com/webcompat/webcompat.com/blob/45eaf8862604855387289d197c030d73562153d2/webcompat/views.py#L276-L278

so we are listening to `extra_labels` in the JSON, not `label`. So I guess we need to open a bug on the addon reporter.

I wonder when did we break this? Or maybe it just slipped through her fingers when we switch to a JSON form and we didn't notice since.

**Comment by karlcow** [comment]
Probably there are two ways to fix this. 
1. Fix the addon-reporter
2. Parse the `hasFastClick: true` and re-inject it in `extra_labels`.

not sure about what I prefer…

**Comment by karlcow** [comment]
The doc here might be false
https://github.com/webcompat/webcompat.com/wiki/Architecture#authorized-keys-for-submitting-bug-reports

**Comment by karlcow** [comment]
We opened a bug on the reporter https://bugzilla.mozilla.org/show_bug.cgi?id=1551721
but I start to wonder if it's not in fact my bad on the server side code.

**Comment by karlcow** [comment]
Ha gotcha!

We are expecting `extra_labels` in 
https://github.com/webcompat/webcompat.com/blob/9709a10fb9c47ce5aa7189ff384c79b98b09b33d/webcompat/form.py#L129

If I enter 
https://staging.webcompat.com/issues/new?url=http://example.com&label=type-fastclick

it converts it to the form with an `@extra_labels` in a comment.

```
<!-- @browser: Firefox 68.0 -->
<!-- @ua_header: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:68.0) Gecko/20100101 Firefox/68.0 -->
<!-- @reported_with:  -->
<!-- @extra_labels: type-fastclick -->

```

I just tested on https://github.com/webcompat/webcompat-tests/issues/1793

but when the form is sent with a HTTP POST + json payload, the JSON key needs to be 

`"extra_labels": ["type-fastclick"]`

ok so this should be solved on the reporter side. 
in https://bugzilla.mozilla.org/show_bug.cgi?id=1551721

**Comment by karlcow** [comment]
> The doc here might be false
> https://github.com/webcompat/webcompat.com/wiki/Architecture#authorized-keys-for-submitting-bug-reports

I fixed it a bit.

**Comment by karlcow** [comment]
So we seem to have a bug on our side too. @ksy36 posted the [payload, sent by the reporter](https://bugzilla.mozilla.org/show_bug.cgi?id=1551721#c5)

**Comment by karlcow** [comment]
So staging labeler is broken too. I'm investigating. We receive a 401 from staging.webcompat.com. This is coming from:

https://github.com/webcompat/webcompat.com/blob/367a93a18e18a901e653e8cec84dd44ca84aaa2a/webcompat/webhooks/__init__.py#L30-L31

and the assessment if it's a valid request
https://github.com/webcompat/webcompat.com/blob/367a93a18e18a901e653e8cec84dd44ca84aaa2a/webcompat/webhooks/helpers.py#L142-L150

**Comment by karlcow** [comment]
The github request contains the header

```
X-GitHub-Event: issues
```

so we pass the first check.
`X-Hub-signature` exists, so `post_signature` exists.

so it fails because of `signature_check(key, post_signature, request.data)`

the key is the right one, I have checked. 
This is working on prod, but not staging. 

The returned signature is… different.

https://github.com/webcompat/webcompat.com/blob/367a93a18e18a901e653e8cec84dd44ca84aaa2a/webcompat/webhooks/helpers.py#L136-L139

The only difference I can imagine is the python version in between the two, because the exact same code is running on both instances. The python version on webcompat.com is… hmmm older.

**Comment by karlcow** [comment]
so I wondered if it was the python version, but nope.

```python
import hmac
import hashlib
mac = hmac.new('foo', 'bar', digestmod=hashlib.sha1)
mac.hexdigest()
```


* produc: '46b4ec586117154dacd49d664e5d63fdc88efb51'
* staging: '46b4ec586117154dacd49d664e5d63fdc88efb51'

So the issue is somewhere else. 
Let's try to feed the same data on both side in the form.
still different.

… I found and I'm slapping my face.

```
env = HOOK_SECRET_KEY='foobar'
env = HOOK_SECRET_KEY=foobar
```
spot the difference. I fixed the config 

and now, we get the labeller working again.
https://staging.webcompat.com/issues/1851

**Comment by karlcow** [comment]
Now we can tackle the other part of the issue which is about `extra_labels`. pfewww.

**Comment by karlcow** [comment]
`type-mobify` in extra_labels is deployed on staging and production.

**Comment by wisniewskit** [comment]
Just FYI, the fix to pass `extra_labels` correctly just landed in the Firefox nightlies as part of the patches in https://bugzilla.mozilla.org/show_bug.cgi?id=1490424. I'm not sure if that means we can close this issue now?

**Comment by karlcow** [comment]
@wisniewskit thanks @wisniewskit and @ksy36 for the fix. 
I think we can close. We need to make double sure that this is working. I didn't see yet any issue reported with one of the frameworks, maybe in a couple of days.

**Comment by karlcow** [comment]
Also for the future.
https://github.com/webcompat/webcompat.com/wiki/Frameworks-Detection
