### ISSUE TITLE
Tracking content blocked flag not working properly

### ISSUE THREAD

**Issue by ksy36** [webcompat/webcompat.com#2872]
In [this issue](https://github.com/webcompat/web-bugs/issues/31127) tracking content blocked flag displayed as false, however there are multiple errors in the console message mentioning "the resource was blocked because content blocking is enabled."

**Comment by karlcow** [comment]
I wonder if it's related to #2869 and https://bugzilla.mozilla.org/show_bug.cgi?id=1551721
Thanks @ksy36

**Comment by ksy36** [comment]
Yeah, looks like this is an issue on the reporter side, but it's part of the `details`object. Created a [bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1557373).

**Comment by ksy36** [comment]
This has been addressed in https://bugzilla.mozilla.org/show_bug.cgi?id=1558628
