### ISSUE TITLE
Add support for AB testing in webcompat.com

### ISSUE THREAD

**Issue by johngian** [webcompat/webcompat.com#2873]
As part of our (Open Innovation) experiments to test some UX changes in the reporting flow, it would be useful to be able to use some sort of AB testing capabilities in webcompat.com.

**Comment by karlcow** [comment]
@johngian I think it would be useful to document the AB architecture for this feature. Or if you have any links pointing to how this is working. a 30,000 eagle view on the way this is handled.

**Comment by karlcow** [comment]
@johngian I created an issue for the documentation. #2878 
I also created a project for AB testing so we don't have any loose ends. 
https://github.com/webcompat/webcompat.com/projects/5

**Comment by karlcow** [comment]
I reverted the previous branch that I had merged into master for two reasons:

1. To merge when we have something which is working with HTTP POST
2. To have a kind of minimal experience in place to test.

until then if needed I'll deploy branches and not master on staging. I was too quick merging the first branch.
