### ISSUE TITLE
AB testing and Privacy policy of webcompat.com

### ISSUE THREAD

**Issue by karlcow** [webcompat/webcompat.com#2877]
Opening this issue to not forget about the implications of AB testing on our privacy policy.
Maybe there is no issue, I just want to make sure we gave it a thought.

cc @miketaylr

**Comment by miketaylr** [comment]
Good question. I guess it doesn't hurt mentioning that we may send a cookie to test a different UI.

**Comment by miketaylr** [comment]
I think this is fixed now:

>  To experiment with different improvements to the site, webcompat.com may use a cookie to serve alternative versions of the site to different users for the duration of an experiment. The experiment cookie will stay on your device until you delete it, or until it expires. The cookie contains only the experiment version you should receive and does not record or provide any personally identifiable information.
