### ISSUE TITLE
Unable to upload screenshots from Fenix

### ISSUE THREAD

**Issue by softvision-sergiulogigan** [webcompat/webcompat.com#2879]
This was initially reported here: https://github.com/webcompat/web-bugs/issues/31368

**URL**: https://webcompat.com/issues/new

**Browser / Version**: Firefox Mobile 68.0
**Operating System**: Android 8.1.0
**Tested Another Browser**: Yes

**Problem type**: Something else
**Description**: can't upload screenshots
**Steps to Reproduce**:
Take a screenshot of a site. Report Site Issue to get here. Tap Upload screenshot. File selector appears, defaults to Recents (as usual), but no files are listed. I can navigate to the screenshots folder, or Google Photos, but photos will not upload from there.
Moto G5 Plus.

![image](https://user-images.githubusercontent.com/16573771/58158514-457eab00-7c83-11e9-8031-d7359485e35b.png)

**Comment by karlcow** [comment]
I wonder if it's related to https://github.com/mozilla-mobile/fenix/issues/2587

**Comment by karlcow** [comment]
And in this case it would not be a webcompat issue, just a fenix issue.
Another possibility is the image is too big.

**Comment by jacktose** [comment]
This was fixed in a recent version of Fenix.
(It's working for me on 1.0.1922, but has been for a few builds now.)

**Comment by karlcow** [comment]
Thanks a lot! Let's close.
