### ISSUE TITLE
Use GitHub issue URLs instead of requesting write permissions to everything on GitHub

### ISSUE THREAD

**Issue by Manishearth** [webcompat/webcompat.com#2910]
Currently, when filing a bug, the tool either lets you report anonymously, or report with GitHub.

However, "report with GitHub" requires extensive write permissions -- the ability to write to all your public repos. This seems excessive, though I understand that GitHub's permissions aren't fine-grained enough to request a more reduced scope here.

Github supports [prefilling issues with query parameters](https://help.github.com/en/articles/about-automation-for-issues-and-pull-requests-with-query-parameters), it would be nice if the github version of that tool could just generate that URL (it would have to upload the photos itself via the API, but that's doable server-side).

**Comment by karlcow** [comment]
Yes this is #655 
And it's why in anonymous bug reporting we propose people to leave their github username, if they do not want to go through the excessive permissions request.

One solution would be https://developer.github.com/apps/

**Comment by karlcow** [comment]
I will close for now and put it on backlog.
In the case we come around it. There is a project for improving the form which is going on right now. Thanks a lot for the suggestions! That would be helpful.
