### ISSUE TITLE
Implement mobile redesign on bug form

### ISSUE THREAD

**Issue by munteanu210** [webcompat/webcompat.com#2938]
Implement the [**mobile UI/UX redesign**](https://miro.com/app/board/o9J_kxX9vL0=/) on the bug form. The mobile view consists of the following parts:

1. **Pop-ups with slider** - See issue #2977 for details.

2. **Text area & progress bar** - See issue #2978 for details.

3. **Animations** - See issue #2979 for details.

4. **Wizard layout (all steps)** - See issue #2982 for details.

**Comment by amberakhtar** [comment]
Hi, I want to contribute to this issue. Could you just guide me, where to begin? Thanks

**Comment by munteanu210** [comment]
@amberakhtar Thank you for offering your help with implementing the mobile design. However, we already completed this task in full, and we are about to do a pull request that contains everything.
