### ISSUE TITLE
Have a way to identify reports filed from the experimental form

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat.com#2940]
A couple of options:

* use the `label` GET param
* HTML comment
* apply a label at report time

Something else?

**Comment by amberakhtar** [comment]
Hi Mike, I'm one of the selected applicants from Outreachy. I picked the project from Mozilla - "Prototype an in-browser mechanism to report Web Compatibility issues" which leads me here. I want to contribute to Open source code! Could you guide me a little, where should I begin to solve the issue? Thanks!

**Comment by miketaylr** [comment]
> Could you guide me a little, where should I begin to solve the issue? Thanks!

Hi @amberakhtar, this issue is not the right place. :) Please feel free to email me miket@mozilla.com and I can help you out.

**Comment by karlcow** [comment]
@miketaylr I propose something along this 

```
<!-- @extra_labels: browser-fenix, form-v20191102 -->
```

The reason to put it there is that it stays there. And we can process the information offline.

**Comment by miketaylr** [comment]
> `<!-- @extra_labels: browser-fenix, form-v20191102 -->`

I think the only thing we need to do to accomplish this is send `label=form-v2` (or whatever we pick) and put that in the `EXTRA_LABELS` list.
