### ISSUE TITLE
Allow A/B testing settings to be set via environment variable

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat.com#2944]
This way we wouldn't need to deploy every time we want to tweak the branches, we would just restart uwsgi.

cc @karlcow @johngian

**Comment by karlcow** [comment]
so the goal here is to have to avoid to PR and redeploy the codebase for something which is essential a configuration choice.

https://github.com/webcompat/webcompat.com/blob/6b5f2522a070dbb3c294242aa85d6b2da8845339/config/__init__.py#L203-L212

So we could have an environment variable, which can be read when we restart uwsgi.
