### ISSUE TITLE
Fix husky pre-commit deprecation 

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat.com#2952]
This happens when you make a commit:

> Warning: Setting pre-commit script in package.json > scripts will be deprecated
Please move it to husky.hooks in package.json, a .huskyrc file, or a husky.config.js file
Or run ./node_modules/.bin/husky-upgrade for automatic update

> See https://github.com/typicode/husky for usage

To fix this bug, I think we just need to remove the "precommit" key from "scripts" inside package.json -- we already have husky.hooks (oops).

**Comment by meetmuhd** [comment]
Hello Mike! Could this be assigned to me, please?

**Comment by meetmuhd** [comment]
Hello @miketaylr. Could this issue be assigned to me, please?

**Comment by karlcow** [comment]
@meetmuhd done.

**Comment by karlcow** [comment]
You are welcome to contribute. Please read carefully our [contributing docs](https://github.com/webcompat/webcompat.com/blob/master/docs/pr-coding-guidelines.md)

**Comment by meetmuhd** [comment]
> You are welcome to contribute. Please read carefully our [contributing docs](https://github.com/webcompat/webcompat.com/blob/master/docs/pr-coding-guidelines.md)

Thank you @karlcow. I've read it and made a PR. Will appreciate your kind review and feedback/action.
