### ISSUE TITLE
Incorrect copy for URL panel [New UI]

### ISSUE THREAD

**Issue by mcroud** [webcompat/webcompat.com#2961]
For people coming direct to webcompat.com, the copy should be:

"**Please enter the URL** where you encountered the web compatibility issue":

<img width="939" alt="Screenshot 2019-10-11 at 14 17 32" src="https://user-images.githubusercontent.com/42435754/66654329-e28db080-ec31-11e9-895c-ca7ca363eb05.png">

The copy we have at the moment is that of someone arriving through the "Report site issue..." menu:

<img width="1091" alt="Screenshot 2019-10-11 at 14 15 20" src="https://user-images.githubusercontent.com/42435754/66654208-9fcbd880-ec31-11e9-8a69-c65fc5c03346.png">

**Comment by soniasingla** [comment]
@miketaylr this issue no longer exists, we can mark it done :)

**Comment by miketaylr** [comment]
Yep, the following looks good to me, thanks!

https://github.com/webcompat/webcompat.com/blob/54a27f0a1b0968195e31d3c0c447593d5011af18/webcompat/templates/issue-wizard-form.html#L18-L24
