### ISSUE TITLE
Cannot tab navigate category section [New UI]

### ISSUE THREAD

**Issue by mcroud** [webcompat/webcompat.com#2965]
Upon reaching the Issue Category step, hitting TAB on the keyboard did not reveal to me which category is selected.

<img width="375" alt="Screenshot 2019-10-11 at 14 42 47" src="https://user-images.githubusercontent.com/42435754/66656227-7ca32800-ec35-11e9-9223-6b6a0e0cba09.png">

Can mouse hover and tab focus states have the same styling:

<img width="601" alt="Screenshot 2019-10-11 at 14 44 37" src="https://user-images.githubusercontent.com/42435754/66656355-b7a55b80-ec35-11e9-9718-002554396823.png">

**Comment by ksy36** [comment]
Let close this in favor of accessibility improvement work in https://github.com/webcompat/webcompat.com/issues/3396
