### ISSUE TITLE
Sub category copy is incorrect [New UI]

### ISSUE THREAD

**Issue by mcroud** [webcompat/webcompat.com#2966]
When I select the issue category of **Design is Broken** the sub-catagory copy is related to Audio and Video:

<img width="1112" alt="Screenshot 2019-10-11 at 14 54 39" src="https://user-images.githubusercontent.com/42435754/66657164-41a1f400-ec37-11e9-981e-adddacc97824.png">

Let's follow this pattern (Which for the record didn't exist prior to this issue :) )

Category| Sub category text
------------ | -------------
Desktop site instead of mobile site | -
Site is not usable| Why is the **site not usable**?
Design is broken | How is the **design broken**?
Video or audio doesn't play | What is wrong with **the video or audio**?
Something else | -

**Comment by munteanu210** [comment]
@mcroud @bacharakis This was an easy fix, so I fixed this issue as a part of the [pull request](https://github.com/webcompat/webcompat.com/pull/2984) that contains the mobile view. You can review this update after PR with the mobile view is approved, merged, and deployed on the staging/dev server.

**Comment by bacharakis** [comment]
Assigned to @munteanu210

**Comment by munteanu210** [comment]
This was fixed in PR #2984.

**Comment by bacharakis** [comment]
@mcroud can you please verify that it has been fixed? Cheers

**Comment by mcroud** [comment]
@bacharakis  Yes, I can confirm this is fixed on staging 🎉
