### ISSUE TITLE
Cannot TAB focus browser buttons [New UI]

### ISSUE THREAD

**Issue by mcroud** [webcompat/webcompat.com#2970]
Similar to the Issue category step, I was unable to see any focus states on the browser selection buttons.

When I reached the step I began holding TAB to see if these buttons changed but I did not see any style changes.

<img width="722" alt="Screenshot 2019-10-11 at 15 49 37" src="https://user-images.githubusercontent.com/42435754/66661381-cf351200-ec3e-11e9-900e-64fe075151e5.png">

**Comment by ksy36** [comment]
Let close this in favor of accessibility improvement work in https://github.com/webcompat/webcompat.com/issues/3396
