### ISSUE TITLE
Deleting an uploaded screenshot causes an error [New UI]

### ISSUE THREAD

**Issue by mcroud** [webcompat/webcompat.com#2973]
Maybe screenshots haven't been plumbed in yet, but when I deleted my uploaded image I received the following:

<img width="1119" alt="Screenshot 2019-10-11 at 16 29 43" src="https://user-images.githubusercontent.com/42435754/66664438-70729700-ec44-11e9-81e9-62bf1458305c.png">

**Comment by johngian** [comment]
I couldn't reproduce this locally. I need to spend some more time to see why this happened.

**Comment by munteanu210** [comment]
@mcroud This got fixed after the last pull requests from last week, which were approved and merged last week. I believe that's why Nemo couldn't reproduce it locally. We need to make sure that the staging/dev server has the most recent code from the master branch. Once we have that confirmation from @johngian, then this problem should be gone, and @mcroud 
you should be able to see this as resolved.

**Comment by bacharakis** [comment]
Assigned to @munteanu210

**Comment by johngian** [comment]
I tested on staging and it still fails.

**Comment by johngian** [comment]
Possibly relevant to #2989

**Comment by munteanu210** [comment]
@johngian I saw PR #2990. Let me know if that PR fixed this current issue.

In issue #2989 you described the exact reason why the screenshots and popups / slider don't work on staging. The corresponding files are included in the flag dependency of the A/B test. If the flag has the form-v2 value, then it includes the files related to the popup, slider, and new form. 

In issue #2989 you said that in production and staging this works differently. I am not sure how to solve this, so as I don't know how the A/B tests work in production, and do not know how to update the codes depending on the A/B test scenario.

Let me know if this issue got resolved. If not, let me know what your further approach on this would be.

**Comment by miketaylr** [comment]
We need to deploy the current master to staging to verify that fixed the issue -- @karlcow can you do at some point today please?

**Comment by karlcow** [comment]
this is deployed.

**Comment by johngian** [comment]
I verified it on stage. It looks like its working fine now. Thanks @mcroud for the report.
