### ISSUE TITLE
Mobile pop-ups and slider on the new bug form

### ISSUE THREAD

**Issue by munteanu210** [webcompat/webcompat.com#2977]
Adjust the way the pop-ups look on mobile on the new bug form. [This is the design](https://www.screencast.com/t/uig4ND2M6oh) for the Privacy Policy pop-up on mobile. 

![2019-09-17_2314](https://user-images.githubusercontent.com/505230/66790141-8d9bb400-ef29-11e9-8ecd-7776561c2c50.png)

This is how the "[What compatibility is](https://www.screencast.com/t/Vnh7SQGh)" pop-up with slider looks on mobile.

![2019-09-17_2315](https://user-images.githubusercontent.com/505230/66790163-a4daa180-ef29-11e9-86d9-44cff764dc5a.png)

**Comment by karlcow** [comment]
@munteanu210 I edited the issue above to add the images. Could you do it next time? Thanks.

**Comment by munteanu210** [comment]
> @munteanu210 I edited the issue above to add the images. Could you do it next time? Thanks.
@karlcow, absolutely! Thank you!
