### ISSUE TITLE
[New UI] Add correct border for invalid form element state

### ISSUE THREAD

**Issue by mcroud** [webcompat/webcompat.com#2980]
When a user enters an invalid URL the error message "A valid URL is required." appears twice:

<img width="590" alt="Screenshot 2019-10-14 at 18 07 39" src="https://user-images.githubusercontent.com/42435754/66769646-88008880-eead-11e9-9ac1-c304d5621141.png">

Can we also include the 1px `#D81D45` border as per the design:

<img width="611" alt="Screenshot 2019-10-14 at 18 07 06" src="https://user-images.githubusercontent.com/42435754/66769832-0826ee00-eeae-11e9-90d4-2de6138afe5b.png">

**Comment by soniasingla** [comment]
Hey @miketaylr ! 

Can I work on this issue? Also, `A valid URL is required.` this issue no longer exists but we can add the border as per the above design. WDYT?

**Comment by miketaylr** [comment]
Hi! Let's check that @ksy36 didn't already fix that in her `formv2-refactor` branch.

@ksy36?

**Comment by ksy36** [comment]
No, I didn't add the border, so you can go ahead @soniasingla :)
Another related issue is focus & valid state style changes https://github.com/webcompat/webcompat.com/issues/3038

**Comment by soniasingla** [comment]
Checking on another issue #3038 now :)
