### ISSUE TITLE
Description step has no intro copy [New UI - Mobile]

### ISSUE THREAD

**Issue by mcroud** [webcompat/webcompat.com#3004]
Upon reaching the "Description" step, no explanatory text is present above the text area:

Zeplin | Staging
------------ | -------------
<img  alt="Screenshot 2019-10-22 at 12 42 23" src="https://user-images.githubusercontent.com/42435754/67282325-69ac1580-f4c9-11e9-903c-215adffaaf64.png"> | <img  alt="Screenshot 2019-10-22 at 12 41 23" src="https://user-images.githubusercontent.com/42435754/67282297-5731dc00-f4c9-11e9-85ae-c5fa7926774b.png">

**Comment by miketaylr** [comment]
Oof, bad bug!
