### ISSUE TITLE
Adds a route with the git SHA of the latest deployed version

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat.com#3009]
@johngian showed me this tool https://whatsdeployed.io/. It allows you to see what version of the repo is deployed to what env. Seems useful.

**Comment by miketaylr** [comment]
WDYT, @karlcow?

**Comment by miketaylr** [comment]
example: https://whatsdeployed.io/s/pdF/mozilla/treeherder

<img width="1185" alt="Screen Shot 2019-10-22 at 9 20 13 AM" src="https://user-images.githubusercontent.com/67283/67295744-2d6abc00-f4ad-11e9-9293-d68091fa1214.png">

**Comment by karlcow** [comment]
See #248 ;)

**Comment by miketaylr** [comment]
> karlcow opened this issue on Sep 2, 2014

Truly ahead of its time, that 🐄

**Comment by karlcow** [comment]
https://whatsdeployed.io/ is a project which uses an URL
such as https://dev.example.com/deployed-version.txt
with a `text/plain` content having the `git SHA`.

> Once you've typed in the GitHub organization, GitHub repository and at least one of these URLs you can generated a table that shows what's been deployed on the server(s) compared to what's available in the master branch.

@miketaylr I modified the title. 
This will require also an issue on devops to modify the fabfile to add the value for the route.

Also I wonder if https://whatsdeployed.io/ would be open to use `/.well-known/` instead of the root. @peterbe to not create another magic URL.

See https://tools.ietf.org/html/rfc5785

**Comment by peterbe** [comment]
Where does whatsdeployed.io use the root? You're in control of what URLs you type in. 
For example, for my current project it's `/media/revision.txt`.

**Comment by karlcow** [comment]
@peterbe Ah nice I had missed that I thought because of the example, you were expecting the root. Thanks! and sorry for the noise.

**Comment by karlcow** [comment]
@miketaylr do we want this SHA to be committed in a specific or just accessible from the Web.

1. committed means we need to make a commit before deploying in a static asset.
2. accessible means just put the value in a file in data before deploying and having the route feeding itself from this file.

Probably I prefer the option 2.

**Comment by miketaylr** [comment]
> Probably I prefer the option 2.

This seems simpler, I think I prefer it too.

**Comment by karlcow** [comment]
FYI @miketaylr @johngian 
https://whatsdeployed.io/s/Xqk/webcompat/webcompat.com

<img width="993" alt="Capture d’écran 2019-10-29 à 11 56 33" src="https://user-images.githubusercontent.com/505230/67733975-2ca0cf80-fa43-11e9-8471-10f97023db2c.png">
