### ISSUE TITLE
When reporting with another browser the list of other browsers needs to be updated

### ISSUE THREAD

**Issue by karlcow** [webcompat/webcompat.com#3016]
The current workflow assumes always Firefox.
webcompat.com is about any browsers.

Here I'm reporting on the left with Safari, and I'm getting proposed… Safari.

<img width="1061" alt="Capture d’écran 2019-10-23 à 16 17 31" src="https://user-images.githubusercontent.com/505230/67367646-da7a2d00-f5b0-11e9-8810-6d8767abf322.png">

**Comment by miketaylr** [comment]
If you're testing in Safari, Safari is given as an option to indicate the "other browser you tested on". That doesn't seem useful, but perhaps more importantly, you cannot select Firefox in this scenario.

**Comment by karlcow** [comment]
What @miketaylr said:

For a set of 7 browsers, let's say:  `{A, B, C, D, E, F, G}`
* If you are testing, with browser A, then the proposed icons list should be `{B, C, D, E, F, G}`
* if you are testing, with browser C, then the proposed icons list should be `{A, B, D, E, F, G}`

etc.

**Comment by s-harbage** [comment]
I agree with this. Karlcow is right. I want to select Firefox as a browser I have tested it on for example (if I found the issue in Safari).

**Comment by Ben-Fenner** [comment]
Thank you for reporting this issue @karlcow, I came across the same problem during my first report a couple days ago. Firefox should certainly be an option on this list. Assuming the user is coming from Firefox doesn't make any sense in a project like this.

**Comment by ksy36** [comment]
Thanks for the feedback, I'll take a look at this.

**Comment by s-harbage** [comment]
Isn't working for me. Is still the same as before. I shouldn't see Safari but should see FF:
![image](https://user-images.githubusercontent.com/81268657/166463923-a030bce0-667e-4f75-87f6-66dc0e8dd101.png)

**Comment by ksy36** [comment]
Yeah, it hasn't been deployed yet. I'll deploy it today and post an update here.

**Comment by ksy36** [comment]
I've just deployed this, so the change is live.

Screenshot from Chrome:

<img width="1654" alt="Screen Shot 2022-05-03 at 3 00 50 PM" src="https://user-images.githubusercontent.com/1303908/166524019-198a0804-fb34-49b1-8dc5-c49be2ab1838.png">

**Comment by softvision-oana-arbuzov** [comment]
I can confirm it is working now both on desktop and mobile.
![image](https://user-images.githubusercontent.com/12184325/166674701-cf1f6e00-1ba6-4c4c-ba2e-93ec8ff8a2bc.png)

**Note:** 
- Brave 1.38.111 is detected as Chrome 101.0.4951.54.
![image](https://user-images.githubusercontent.com/12184325/166673207-7eb16795-5656-4918-b856-59337b5aee27.png)
 
**Tested with:**
Browser / Version: Firefox Nightly 102.0a1 (2022-05-03), Chrome 101.0.4951.54, IE 21H2, Microsoft Edge 101.0.1210.32, Opera 86.0.4363.32, SeaMonkey 2.53.11, Pale Moon 29.4.6, Waterfox 91.8.0, Comod IceDragon 65.0.2, Firefox Focus Release 100.1.1 (🦎 100.0-20220428192727), Firefox Nightly 102.0a1 (🦎 102.0a1-20220503094208), Chrome 101.0.4951.41, Microsoft Edge 100.0.1185, Opera 68.3.3557
Operating System: Windows 10 Pro, Google Pixel 5 (Android 12) - 1080 x 2340 pixels, 19.5:9 ratio (~432 ppi density), Samsung Galaxy S8 (Android 9) - 1440 x 2960 pixels, 18.5:9 ratio (~570 ppi density)

@Ben-Fenner and @s-harbage please have a look also.

**Comment by Ben-Fenner** [comment]
Yes, I confirmed myself right after ksy36 let us know it was ready and yes, it is working.
