### ISSUE TITLE
Unable to open logout menu

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat.com#3024]
STR:

1. go to staging.webcompat.com
2. log in
3. click the "avatar V" menu thing in the top right

expected: dropdown opens
actual: nothing?

Doesn't reproduce on production, AFAICT.

**Comment by miketaylr** [comment]
Actually, it seems to reproduce on production but only in Firefox? Working in production in Chrome, but not staging. I am very confused.

**Comment by miketaylr** [comment]
In a private tab in Firefox, on production this is working as expected. Still confused.

**Comment by miketaylr** [comment]
And now in a regular tab in Firefox on production this is working. But not on staging in Chrome. 👀

**Comment by miketaylr** [comment]
Working in Safari... this might just be Chrome Canary bug territory.

**Comment by karlcow** [comment]
<img width="398" alt="Capture d’écran 2019-10-24 à 06 18 38" src="https://user-images.githubusercontent.com/505230/67434970-29ae7500-f626-11e9-929e-f53b730fff7d.png">

Firefox Nightly 72.0a1 (2019-10-22) (64-bit)
macOS 10.15 (19A602)

**Comment by ksy36** [comment]
This is not working for me in Firefox, but only on this page https://webcompat.com/issues/new . Same on staging

**Comment by ksy36** [comment]
Seems to be working only on the main page and not on internal pages :)

**Comment by miketaylr** [comment]
Nice catch @ksy36! For some reason the event handler isn't getting set on the dropdown...

**Comment by karlcow** [comment]
on https://staging.webcompat.com/issues?page=1&per_page=50&state=open&stage=all&sort=created&direction=desc

confirmed.

**Comment by karlcow** [comment]
```html
<li class="nav-item login js-login-link js-DropdownHeader">
  <button class="nav-button nav-link" aria-expanded="false" aria-label="My account">
    <img class="login-avatar-img" src="https://avatars0.githubusercontent.com/u/505230?v=4" alt="User Avatar">
    <svg class="icon nav-icon" viewBox="0 0 30 30" role="presentation" aria-hidden="true">
      <use xlink:href="#svg-chevron-right"></use>
    </svg>
  </button>
  <div class="nav-dropdown-wrapper">
    <ul class="dropdown">
      <li class="nav-dropdown-item">
        <a class="nav-link" href="/me">My Activity</a>
      </li>
      <li class="nav-dropdown-item">
        <a class="nav-link" href="/logout">Logout</a>
      </li>
    </ul>
  </div>
</li>
````

**Comment by miketaylr** [comment]
We set the handler on the homepage here: https://github.com/webcompat/webcompat.com/blob/5e14037d0a0e19c977569c47b3e676fee09a3325/webcompat/static/js/lib/homepage.js#L50-L66

**Comment by karlcow** [comment]
https://github.com/webcompat/webcompat.com/commit/220d5c30b2d88705775ec9371cc50a57f3954341

**Comment by karlcow** [comment]
This is fixing an issue introduced by #2896 for solving #2268
