### ISSUE TITLE
Setting environment variables doens't have intended effect on staging

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat.com#3026]
I'm trying to test staging setting the following variables via our uwsgi config file:

```
# A/B testing experiment ENV variables for staging
# This expects a string with 2 integers
env = FORM_V1_VARIATION='0 0'
env = FORM_V2_VARIATION='0 100'
# one week experimental cookie expiry
env = EXP_MAX_AGE=604800
```

After restarting the application, I still can't get form v2.

If I mirror these values in the local app, either hard-coded in config/__init__.py, or exported as environment variables, I get the form v2 100% of the time (expected behavior). Not sure why, but I need to investigate https://github.com/webcompat/webcompat.com/issues/3024 as a production regression first.

**Comment by miketaylr** [comment]
> env = EXP_MAX_AGE=604800

A cookie is set, and the max age is correct. It's just always set to `form-v1`, which makes me think we're just reading hard-coded defaults for some reason.

**Comment by johngian** [comment]
Trying to reproduce this with uwsgi locally

**Comment by johngian** [comment]
Its the `'` in the env definition in the wsgi ini. Can you try the same without `'`:
```
# A/B testing experiment ENV variables for staging
# This expects a string with 2 integers
env = FORM_V1_VARIATION=0 0
env = FORM_V2_VARIATION=0 100
# one week experimental cookie expiry
env = EXP_MAX_AGE=604800
```

**Comment by miketaylr** [comment]
> Its the `'` in the env definition in the wsgi ini. Can you try the same without `'`:

oof. Thanks. :)
