### ISSUE TITLE
Mobile viewport submit button layout visual issue

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat.com#3029]
Depending on the viewport width, this button looks wonky. The first is on my Pixel 3 phone, the second is resizing the browser. 

![Screenshot_20191024-104944](https://user-images.githubusercontent.com/67283/67502879-3e056880-f64c-11e9-81bf-6392676ca854.png)

![Screen Shot 2019-10-24 at 10 52 44 AM](https://user-images.githubusercontent.com/67283/67502977-760cab80-f64c-11e9-9c02-ce33dca0de29.png)

**Comment by soniasingla** [comment]
@miketaylr this issue no longer exists :)

**Comment by karlcow** [comment]
The issue still exists. When at this stage. It's impossible to scroll down and then access the content of the button.
<img width="776" alt="Capture d’écran 2020-07-20 à 13 39 34" src="https://user-images.githubusercontent.com/505230/87900501-804ebf80-ca8f-11ea-86ef-a82cac4fd05e.png">


The wrapping box seems to have a size determined by flexbox, but when the animation expand the box, the box is not being resized related to the content.

**Comment by karlcow** [comment]
@magsout do you want to give it a shot?

**Comment by ksy36** [comment]
This will most likely be fixed in https://github.com/webcompat/webcompat.com/pull/3404#discussion_r458434068

**Comment by soniasingla** [comment]
This issue has been fixed in this [PR](https://github.com/webcompat/webcompat.com/pull/3404) :)

CC : @ksy36 @karlcow

**Comment by karlcow** [comment]
Thanks!
