### ISSUE TITLE
Text fields do not have correct focus and valid styling [form v2]

### ISSUE THREAD

**Issue by mcroud** [webcompat/webcompat.com#3038]
The styling demo presented focus and validated styling for text fields:

<img width="1276" alt="Screenshot 2019-10-25 at 11 27 37" src="https://user-images.githubusercontent.com/42435754/67564235-783d3b80-f71a-11e9-9006-9d07cec2c6f1.png">

![Untitled5](https://user-images.githubusercontent.com/42435754/67565172-ade32400-f71c-11e9-9a26-6ffcf9365386.gif)

The correct styles are the following:

**Valid**
`border: 1px solid #22b573`

**Focus**
`box-shadow: 0 0 0 3px  #56638c`

**Comment by ksy36** [comment]
Styling demo url: https://cdpn.io/Octavector/debug/5c04c472d928b6a34521febf2789a6d2
