### ISSUE TITLE
Only protocol identifier is accepted as valid URL

### ISSUE THREAD

**Issue by softvision-oana-arbuzov** [webcompat/webcompat.com#3040]
URL: https://staging.webcompat.com/issues/new 
Browser / Version: Firefox Nightly 71.0a1 (2019-10-24)
Operating System: Windows 10 Pro

**Steps to Reproduce:**
    1. Navigate to https://staging.webcompat.com/issues/new
    2. Type in the URL only the protocol identifier (e.g “http:”, “https:”).
    3. Observe behavior.
       
**Expected Behavior:**
URL is not accepted (no green check-mark) and “Confirm” button remains disabled.

**Actual Behavior:**
URL is accepted (green check-mark) and “Confirm” button is enabled.

**Note**
    1. Screenshot attached.
    2. Also reproducible on Chrome 78.0.3904.70.
    3. Valid URL format: protocol identifier + resource name (IP address/domain name) .

Affected area:
```html
<input class="form-field text-field required" id="url" name="url" pattern="" placeholder="e.g. https://example.com" required="" type="url" value="">
```

![image](https://user-images.githubusercontent.com/12184325/67568190-37eab700-f734-11e9-90da-eef0a5266800.png)

**Watchers:**
@softvision-sergiulogigan
@softvision-oana-arbuzov
@cipriansv
 
sv;

**Comment by miketaylr** [comment]
Discussion is relevant to https://github.com/webcompat/webcompat.com/issues/3045.

Thoughts @karlcow?

**Comment by miketaylr** [comment]
(We've gone back and forth before, so unless there is a strong argument to change behavior again, this is probably WONTFIX)

**Comment by miketaylr** [comment]
Actually, let's close in favor of https://github.com/webcompat/webcompat.com/issues/2889
