### ISSUE TITLE
"Device" term is used when "OS" term is more appropriate 

### ISSUE THREAD

**Issue by cipriansv** [webcompat/webcompat.com#3041]
*Environment:*
Browser / Version: Firefox Nightly 72.0a1 (2019-10-24)
Operating System: Ubuntu 18.04.3 LTS

*Steps to Reproduce:*
1. Navigate to https://staging.webcompat.com/issues/new
2. Fill in the form and reach the ”Did you encounter the issue on this device (Linux)”… section
3. Observe the section’s question.

*Expected Behavior:*
 ”Did you encounter the issue on this OS (Linux) using this browser(Firefox)?" should be displayed. 

*Actual Behavior:*
 ”Did you encounter the issue on this device (Linux) using this browser(Firefox)?" is displayed

*Notes:*
1. Screen capture attached.
2. The issue is  also reproducible on Chrome 78.0.3904.70
3. The issue is also reproducible for the next section - “What browser and device were you using when the issue encountered?”

Watchers:
@softvision-sergiulogigan
@softvision-oana-arbuzov

sv;

![Screenshot from 2019-10-25 14-31-52](https://user-images.githubusercontent.com/45160931/67569250-01626b80-f737-11e9-94b6-4d19662b603c.png)

**Comment by miketaylr** [comment]
Let's let @mcroud comment here.

**Comment by mcroud** [comment]
This is a good observation, I suppose working on the mobile experience first biased my thinking towards "devices". 

Holding up my phone I asked a family member what "device" it was, they responded "mobile phone", I then asked them what operating system it was, the response was "Google" - certainly more accurate as it's an Android.
I originally suspected that 'device' would appeal to a greater audience but it may provide weaker information so let's go with Operating system 👍 
Thanks!
