### ISSUE TITLE
A browser name containing only space characters is validated

### ISSUE THREAD

**Issue by cipriansv** [webcompat/webcompat.com#3042]
*Environment:*
Browser / Version: Firefox Nightly 72.0a1 (2019-10-24)
Operating System: Ubuntu 18.04.3 LTS

*Steps to Reproduce:*
1. Navigate to https://staging.webcompat.com/issues/new
2. Fill in the form and reach the ” What browser were you using when the issue encountered?” section.
3. From the “Browser” input field delete the pre-populated browser name.
4. Type a few space characters and press the keyboard’s tab key.

*Expected Behavior:*
 A browser error message should be displayed.

*Actual Behavior:*
 The browser is validated and the validation icon is displayed.

*Notes:*
1. Screen capture attached.
2. The issue is  also reproducible on Chrome 78.0.3904.70

Watchers:
@softvision-sergiulogigan
@softvision-oana-arbuzov

sv;

![Screenshot from 2019-10-25 14-51-19](https://user-images.githubusercontent.com/45160931/67569404-72a21e80-f737-11e9-8a05-4d80720c8c1b.png)

**Comment by miketaylr** [comment]
Oops. Nice catch.

https://github.com/webcompat/webcompat.com/blob/master/webcompat/static/js/lib/bugform.js#L374-L381 is the place to start looking.
