### ISSUE TITLE
Non http url's are not allowed

### ISSUE THREAD

**Issue by softvision-sergiulogigan** [webcompat/webcompat.com#3045]
**Environment:**
Browser / Version: Firefox Nightly 72.0a1 (2019-10-24)
Operating System: Windows 10

**Steps to Reproduce:**
1. Navigate to https://staging.webcompat.com/issues/new
2. Fill in the URL field with www.pisicamare.com

**Expected Behavior:**
The field is validated.

**Actual Behavior:**
The field is not validated.

**Notes:**
1. Screenshot attached.

Watchers:
@softvision-sergiulogigan
@softvision-oana-arbuzov
@cipriansv

![image](https://user-images.githubusercontent.com/16573771/67571320-581e7400-f73c-11e9-9e9b-60fc555350fb.png)

**Comment by miketaylr** [comment]
@softvision-sergiulogigan are you suggesting we should allow non-HTTP(s) URLs in the form?

I think that was the behavior a few years ago, but we moved to require http/https in https://github.com/webcompat/webcompat.com/issues/1508. I'm not sure I have strong opinions, but I think there are maybe implications on the server side.

**Comment by miketaylr** [comment]
Actually, I see we have a bug here: https://github.com/webcompat/webcompat.com/issues/2889.

Let's close in favor of that.
