### ISSUE TITLE
Multiple confirm clicks log multiple issues

### ISSUE THREAD

**Issue by softvision-sergiulogigan** [webcompat/webcompat.com#3050]
**Environment:**
Browser / Version: Firefox Nightly 72.0a1 (2019-10-24)
Operating System: Windows 10 Pro

**Steps to Reproduce:**
1. Navigate to https://staging.webcompat.com/issues/new
2. Follow the entire report flow.
3. Click multiple times on the "Send Report" button.

**Expected Behavior:**
The report is only sent once.

**Actual Behavior:**
The report is duplicated.

**Notes:**
1. Screenshot attached.
2. I was able to duplicate a report 70 times in 10 seconds (or less) - https://github.com/webcompat/webcompat-tests/issues?utf8=%E2%9C%93&q=www.pisicamare2154.com

Watchers:
@softvision-sergiulogigan
@softvision-oana-arbuzov
@cipriansv

![image](https://user-images.githubusercontent.com/16573771/67573927-21e3f300-f742-11e9-8667-a920d2102d62.png)

**Comment by miketaylr** [comment]
> I was able to duplicate a report 70 times in 10 seconds (or less) - https://github.com/webcompat/webcompat-tests/issues?utf8=%E2%9C%93&q=www.pisicamare2154.com

You are a monster.

**Comment by miketaylr** [comment]
Yikes, what.

**Comment by miketaylr** [comment]
This one seems particularly bad @bacharakis. It does not reproduce in form v1.

**Comment by johngian** [comment]
I managed to reproduce this in form v1 as well. Should we try to fix it for all versions?

![image](https://user-images.githubusercontent.com/835321/67688961-51456a80-f9a3-11e9-8e43-1cb9f05410c0.png)

**Comment by miketaylr** [comment]
> I managed to reproduce this in form v1 as well.

Well, that's cool I guess. Not a new regression. 

The good news is I don't think we've ever really seen this (at least, as a spam tactic). Should probs fix this everywhere (or just fix it once on the backend).
