### ISSUE TITLE
The end of long URLs are overlapped by the checkmark

### ISSUE THREAD

**Issue by softvision-sergiulogigan** [webcompat/webcompat.com#3052]
**Environment:**
Browser / Version: Firefox Nightly 72.0a1 (2019-10-24)
Operating System: Windows 10 Pro

**Steps to Reproduce:**
1. Navigate to https://staging.webcompat.com/issues/new
2. Fill in the URL field with a long URL.

**Expected Behavior:**
The end of the URL is entirely visible.

**Actual Behavior:**
The last character of the URL is not visible.

**Notes:**
1. Screenshot attached.

Watchers:
@softvision-sergiulogigan
@softvision-oana-arbuzov
@cipriansv

![image](https://user-images.githubusercontent.com/16573771/67575628-a4ba7d00-f745-11e9-8158-2f0285fba215.png)

**Comment by miketaylr** [comment]
This does not repro in form v1.

**Comment by veemish** [comment]
could I work on this bug as well?
