### ISSUE TITLE
webcompat.com - site is not usable

### ISSUE THREAD

**Issue by tm45** [webcompat/webcompat.com#3069]
**URL**: https://webcompat.com/issues/new

**Browser / Version**: Firefox 71.0
**Operating System**: Linux
**Tested Another Browser**: Yes

**Problem type**: Site is not usable
**Description**: Two links in the top menu don't work: Search and User. Though the latter works on the homepage.
**Steps to Reproduce**:
The links just don't work: nothing  happens when you click. In Chromium too.

<details>
<summary>Browser Configuration</summary>
<ul>
  <li>None</li>
</ul>

</details>

_From [webcompat.com](https://webcompat.com/) with ❤️_

**Comment by softvision-sergiulogigan** [comment]
This is also broken on Windows.

**Comment by miketaylr** [comment]
The search stuff should be fixed by https://github.com/webcompat/webcompat.com/pull/3064 -- we just need to deploy it. @tm45, what do you mean by "User" link?

**Comment by tm45** [comment]
Hello,

I mean the picture/icon at the top right corner.

**Comment by miketaylr** [comment]
Thanks @tm45 -- can you please verify it's been fixed now? Thanks

**Comment by tm45** [comment]
Hello.

Yes, it works now.

**Comment by miketaylr** [comment]
Thanks!
