### ISSUE TITLE
Selected browser info is not displayed in the final report

### ISSUE THREAD

**Issue by softvision-oana-arbuzov** [webcompat/webcompat.com#3077]
URL: https://webcompat.com/issues/new 
Browser / Version: Firefox Nightly 71.0a1 (2019-11-05)
Operating System: Windows 10 Pro

**Steps to Reproduce:**
    1. Navigate to https://webcompat.com/issues/new 
    2. Fill in the required information until reaching browser selection section.
    3. Click any of the options (e.g “Safari”).
    4. Fill in the rest of the information and report the bug.
    5. Observe available info before the bug description.
       
**Expected Behavior:**
The selected browser info is not available (e.g “**Tested Another Browser:** Yes, on Safari”).  

**Actual Behavior:**
The selected browser info is not available.

**Note**
    1. Screenshot attached.

![NOIndicationOfSelectedBrowser](https://user-images.githubusercontent.com/12184325/68298919-3a89cc80-00a3-11ea-9711-58cd6af32097.jpg)

**Watchers:**
@softvision-sergiulogigan
@softvision-oana-arbuzov
@cipriansv

sv;

**Comment by miketaylr** [comment]
Similar to https://github.com/webcompat/webcompat.com/issues/3025, we can probably fix both at the same time.
