### ISSUE TITLE
Browser detection recognizes Edge as Chrome

### ISSUE THREAD

**Issue by Th3S4mur41** [webcompat/webcompat.com#3085]
In the issue form, the autofilled browser version when using Edge is Chrome.
The same issue is true for both Edge (Canary) on Windows as well as on Android.
While both Browser are based on the same Engine, different settings might lead to different behaviors.
So I think it would make sense to recognize Edge as such.

**Comment by miketaylr** [comment]
Thanks for the report @Th3S4mur41, I agree we should recognize Edge differently from Chrome.

**Comment by miketaylr** [comment]
It looks like a fix is already waiting to be merged at https://github.com/ua-parser/uap-core/pull/401

**Comment by miketaylr** [comment]
So the update is in uap-core 0.6.10, but currently uap-python is using 0.6.9: https://github.com/ua-parser/uap-core/compare/71ec72cd37a940683cd40af3f7ab738ecbdcc45b...286809e09706ea891b9434ed875574d65e0ff6b7

I filed https://github.com/ua-parser/uap-python/issues/78

**Comment by karlcow** [comment]
This should be fixed soon. 
https://github.com/ua-parser/uap-python/pull/79

**Comment by miketaylr** [comment]
This is fixed by https://github.com/webcompat/webcompat.com/pull/3413.
![Screen Shot 2020-07-24 at 10 00 36 AM](https://user-images.githubusercontent.com/67283/88405219-8a750480-cd94-11ea-82b7-b3bad586158c.png)
