### ISSUE TITLE
Form is uploading the Bug report screenshot to github

### ISSUE THREAD

**Issue by karlcow** [webcompat/webcompat.com#3095]
@miketaylr @ksy36 I'm not sure it's a regression, but I'm surprised.
Currently the screenshots are being uploaded on GitHub instead of webcompat.

Was there a constraint? Or something has changed in the code? Or was it always like this and I only noticed now. 🤣

**Comment by karlcow** [comment]
An example https://webcompat.com/issues/44485

```
<!-- @browser: Firefox 72.0 -->
<!-- @ua_header: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:72.0) Gecko/20100101 Firefox/72.0 -->
<!-- @reported_with: desktop-reporter -->
<!-- @extra_labels: form-v2-experiment -->
```

and this is not related to the experiment, it happens in the two cases.

**Comment by karlcow** [comment]
Oh is it the addon, in this case it would be @wisniewskit

**Comment by karlcow** [comment]
ah no no :) definitely a regression.
I uploaded these images this morning through webcompat when commenting
https://github.com/webcompat/web-bugs/issues/44353#issuecomment-555793736

And there are hosted on github. Something is broken.

**Comment by karlcow** [comment]
They create a local copy of all images…

```
http HEAD https://camo.githubusercontent.com/a8759466562a31c4ca3bb35ed287c07832ec2a2f/68747470733a2f2f776562636f6d7061742e636f6d2f75706c6f6164732f323031392f31312f63663764353435652d303263372d346630662d623836322d3032363239316538333639302d7468756d622e6a706567
```

and the response.

```http
HTTP/1.1 200 OK
Accept-Ranges: bytes
Age: 1225
Cache-Control: public, max-age=31536000
Connection: keep-alive
Content-Length: 121873
Content-Security-Policy: default-src 'none'; img-src data:; style-src 'unsafe-inline'
Content-Type: image/jpeg
Date: Wed, 20 Nov 2019 06:35:42 GMT
Last-Modified: Mon, 11 Nov 2019 05:30:09 GMT
Server: github-camo (876de43e)
Strict-Transport-Security: max-age=31536000; includeSubDomains
Timing-Allow-Origin: https://github.com
Vary: Accept-Encoding
Via: 1.1 varnish
X-Cache: HIT
X-Cache-Hits: 1
X-Content-Type-Options: nosniff
X-Fastly-Request-ID: e951f2bf3841b631c3f2cf211f623147ea7d5ec3
X-Frame-Options: deny
X-GitHub-Request-Id: 96A8:60AA:1646AA:177DBE:5DD4D9F4
X-Served-By: cache-tyo19943-TYO
X-Timer: S1574231743.513589,VS0,VE3
X-Xss-Protection: 1; mode=block

```

**Comment by karlcow** [comment]
lol our images are already in the cloud 🤡 
https://github.com/mozilla/webcompat-team-okrs/issues/108

**Comment by karlcow** [comment]
This is a test.

![I'm root](http://www.la-grange.net/2019/01/01/2535-misere)

**Comment by karlcow** [comment]
Bingo. Just checked on my server logs.

```
140.82.115.251 - - [20/Nov/2019:06:44:54 +0000] "GET /2019/01/01/2535-misere HTTP/1.1" 200 62673 "-" "github-camo (876de43e)"
```

This was with this markup.

```
!['m root](http://www.la-grange.net/2019/01/01/2535-misere)
```

Let's check with 

```
<img src="http://www.la-grange.net/2019/01/01/2535-misere" alt="I'm root">
```

<img src="http://www.la-grange.net/2019/01/01/2535-misere" alt="I'm root">

**Comment by karlcow** [comment]
And it came again

```
140.82.115.248 - - [20/Nov/2019:06:47:41 +0000] "GET /2019/01/01/2535-misere HTTP/1.1" 200 62673 "-" "github-camo (876de43e)"
```

Not sure it's good or bad. :/

**Comment by miketaylr** [comment]
> They create a local copy of all images…

When an image is hosted on a non-github server they use this github-camo proxy to route it through a secure context: https://github.com/atmos/camo

**Comment by miketaylr** [comment]
I think it's a non-issue. It's just extra work that GitHub is doing to be safe, maybe creates a bit of latency for the user but I don't think anything is broken.
