### ISSUE TITLE
Selecting "Other" browser does not reveal text field

### ISSUE THREAD

**Issue by mcroud** [webcompat/webcompat.com#3097]
If a user selects "Other" in the Browser testing step, they should be prompted to provide the name of the browser. 
On live, no such text field appears, people selecting this option would have not committed to a browser and also would not have seen the "This is important to webcompat" message.

The design:
<img width="968" alt="Screenshot 2019-11-26 at 11 11 01" src="https://user-images.githubusercontent.com/42435754/69624917-729a8480-103d-11ea-8a25-6345f82b9e0a.png">

**Comment by miketaylr** [comment]
I believe @ksy36 fixed this? Whoever it was, it's working now.
