### ISSUE TITLE
Make homepage bug and light animated

### ISSUE THREAD

**Issue by calexity** [webcompat/webcompat.com#310]
Hover affect or animation that makes the homepage exciting!

**Comment by magsout** [comment]
any news about it @calexity ?

**Comment by calexity** [comment]
No, but I can possibly make a rough gif this weekend.  Courtney was going
to help me, but she's been out of town.  Any interest in helping me
implement it?

**Comment by magsout** [comment]
What idea do you have? it may be possible to do it in css only , although I 've never done animation with svg

**Comment by karlcow** [comment]
I guess a filter applied on the filament and/or the lightbulb glass part a yellow shadow with an opacity variation maybe with a slight random sequence. of variations. FUN. New things to learn/experiment.

**Comment by karlcow** [comment]
A blur filter.

``` xml
<svg version="1.1" xmlns="http://www.w3.org/2000/svg"> 
  <filter id="blur"> 
    <feGaussianBlur stdDeviation="3" /> 
  </filter>
</svg>
```

to apply the blur filter.

``` css
.lightbulb { 
  filter: url(blur.svg#blur); 
  -webkit-filter: blur(3px); 
  filter: blur(3px); 
  }
```
Starting the idea. Then maybe animation with CSS.

**Comment by calexity** [comment]
Here's an idea @magsout - might be too complicated....you tell me

<a href="https://imgflip.com/gif/iknwx"><img src="https://i.imgflip.com/iknwx.gif" title="made at imgflip.com"/></a>

**Comment by calexity** [comment]
PS @miketaylr I made you a new sticker while I did this.  Let me know if you ever reprint those and want a hi-res graphic
![sticker](https://cloud.githubusercontent.com/assets/1103366/6544974/fe0fce9a-c51e-11e4-991c-1ffa73f6ed74.png)

**Comment by magsout** [comment]
heh, I can try :dancer:

**Comment by karlcow** [comment]
@calexity new sticker :heart_eyes:

**Comment by miketaylr** [comment]
@calexity yessss. Can you check the asset into the design repo (unless you already, but I don't see it)?

**Comment by calexity** [comment]
@miketaylr here are those stickers you asked for years ago https://github.com/webcompat/design/tree/master/Stickers

**Comment by miketaylr** [comment]
Awesome thank you @calexity!

**Comment by miketaylr** [comment]
It wouldn't be too much work to animate the existing SVG on hover (or similar).

**Comment by miketaylr** [comment]
We have bigger priorities for now, probably not gonna get to this.

(sorry @calexity 😭)
