### ISSUE TITLE
[formv2] What is step9?

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat.com#3106]
It's in the JS, but there's no associated DOM element:

https://github.com/webcompat/webcompat.com/search?q=step9&unscoped_q=step9

**Comment by miketaylr** [comment]
Maybe this is it... https://github.com/webcompat/webcompat.com/blob/f279404888772e029add202bc6d6e3f86c574fbe/webcompat/templates/issue-wizard-form.html#L254

Given that it appears between Steps 8 and 10, and `data-nextstep="10"`

**Comment by miketaylr** [comment]
No, I'm just confused. Apparently there's 2 classes `step8` and `step-8`. 🤷‍♂

**Comment by ksy36** [comment]
This was addressed in https://github.com/webcompat/webcompat.com/pull/3246
