### ISSUE TITLE
“Continue without” button available even if screenshot is uploaded

### ISSUE THREAD

**Issue by softvision-oana-arbuzov** [webcompat/webcompat.com#3110]
**Environment:**
URL: https://webcompat.com/issues/new 
Browser / Version: Firefox Nightly 73.0a1 (2019-12-15)
Operating System: Windows 10 Pro

**Steps to Reproduce:**
    1. Navigate to https://webcompat.com/issues/new 
    2. Fill in the required information until reaching screenshot section.
    3. Upload a screenshot.
    4. Observe available buttons under the section.
       
**Expected Behavior:**
“Continue” and “Delete this image” buttons are available. (“Continue without” changes to “Continue”)

**Actual Behavior:**
“Continue without” and “Delete this image” buttons are available.

**Note**
    1. Screenshot attached.

Affected area:
```html
<button class="button next-step step-10 issue-btn" data-nextstep="11">Continue without</button>
```

**Watchers:**
@softvision-sergiulogigan
@softvision-oana-arbuzov
@cipriansv

sv; 

![ContinueWithout](https://user-images.githubusercontent.com/12184325/70916573-93df0700-2024-11ea-851c-8a668a749216.jpg)

**Comment by miketaylr** [comment]
This was changed in https://github.com/webcompat/webcompat.com/pull/3107

I guess the desired behavior here is "Continue" when there's a screenshot and "Continue without" when there isn't one?

cc @bacharakis

**Comment by miketaylr** [comment]
(I agree "Continue without" when there is a screenshot looks weird)
