### ISSUE TITLE
improve config/environment.py - avoid import *

### ISSUE THREAD

**Issue by karlcow** [webcompat/webcompat.com#3113]
`import *` is usually not a recommended practice. 
This is not an urgent issue.

In https://github.com/webcompat/webcompat.com/blob/daaaa99fa93f944f39286391b0613526f660e2d2/config/__init__.py
Replace

```python
from config.environment import *  # noqa
```

by 

```python
import config.environment as cfg
```

And fixes the references for the used variables.

for example

```python
if not PRODUCTION:
```

would become

```python
if not cfg.PRODUCTION
```

**Comment by apsychogirl** [comment]
Hi, I would like to take this up.

**Comment by karlcow** [comment]
@apsychogirl would you like to tackle this one? now that you finished #3199

**Comment by karlcow** [comment]
See the comment in https://github.com/webcompat/webcompat.com/pull/3273#issuecomment-628346573
and https://github.com/webcompat/webcompat.com/pull/3273/files#r424834237

> yes the change is a bit bigger in architecture than I was planning for at the beginning of this issue and probably harder to achieve. The project is suffering from his past.
> 
> Probably we should drop this issue #3113 and we could create a new issue with a scarier title 👺 like "Webcompat app configuration architecture overhaul".

**Comment by karlcow** [comment]
I will close this issue and eventually we could create a new one.

Some ideas to explore.

* [How and why have a properly “Configuration Handling File” using Flask?](https://itnext.io/how-and-why-have-a-properly-configuration-handling-file-using-flask-1fd925c88f4c)
* [Configuration Handling](https://flask.palletsprojects.com/en/1.1.x/config/)
* [Flask configuration files | Learning Flask Ep. 12](https://pythonise.com/series/learning-flask/flask-configuration-files)

We would probably benefit of the pattern:


```python
class Config(object):
    DEBUG = False
    TESTING = False

class ProductionConfig(Config):
    pass

class DevelopmentConfig(Config):
    DEBUG = True

class TestingConfig(Config):
    TESTING = True
```
