### ISSUE TITLE
Investigate and fix excessive label assigning

### ISSUE THREAD

**Issue by softvision-sergiulogigan** [webcompat/webcompat.com#3114]
This is related to the plethora of labels applied to:

https://github.com/webcompat/web-bugs/issues/46909
https://github.com/webcompat/web-bugs/issues/46908
https://github.com/webcompat/web-bugs/issues/19195

**Comment by karlcow** [comment]
This is spam by a bot.

**Comment by karlcow** [comment]
Probably we could limit the number of labels assignment as a mitigation of the issue.

**Comment by karlcow** [comment]
Flagging this. Just in case this is related to the series of events in #3118

**Comment by karlcow** [comment]
We found the origin of this and we know how to fix it.
