### ISSUE TITLE
Remove inline screenshot images

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat.com#3122]
Just link to them instead. See #3118

**Comment by miketaylr** [comment]
I'm just gonna remove the inline option and link out to it in this issue, but we should file a follow up to stop generating thumbnail images since we won't need those.

(Or, we could stick it inside a closed details element?)

**Comment by karlcow** [comment]
Are these issues only for anonymous reporting or all report. The rationale for me is that someone reporting an issue directly from GitHub:

1. would be identified as a person and blockable for abuse
2. the image would be an inline image

Do we want to lose the functionality for a couple of (very bad) abuses? Or do we want to mitigate?

in #3124 we plan to switch to a probably moderation-first model, this prevents to have images available directly visible without reviews.

Images with concerns:

* adult websites 
* illegal content of any nature
* private content (private profile on social network, bank information, companies internal pages)

**Comment by karlcow** [comment]
So I created PR #3131 to solve this.
