### ISSUE TITLE
Remove illegal content

### ISSUE THREAD

**Issue by karlcow** [webcompat/webcompat.com#3129]
During #3118 event, we have been banned because of some illegal content being reported on our site. I will use this issue to track the work, before we get the green light again for anonymous reporting and re-instating the legal content issues of webcompat-bot. 

By TRACKING, I meant the work and not any specific details about the resources that will be removed for obvious reasons.

**Comment by karlcow** [comment]
* Images with potential issues have been removed from our servers.

**Comment by miketaylr** [comment]
The problematic issues we have identified (so far) have been deleted.

**Comment by karlcow** [comment]
Maybe we should close this.
We will need later probably to do a second pass but after everything is back to normal in terms of reporting.
