### ISSUE TITLE
Add back inline screenshot hidden inside <details> by default

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat.com#3136]
See #3122 for relevant code to tweak.

**Comment by miketaylr** [comment]
> When an image is hidden in a detail, is it still fetched, or the fetch is happening when the detail is opened?

**Comment by karlcow** [comment]
Do we activate thumbs or do we forget about them?
Note to self: test details and image fetching.

**Comment by karlcow** [comment]
Testing of details and images.

I have tested: 
```html
<details>
    <summary>Expand for the image</summary>
    <p><img src="/2005/12/13-fujiyama.jpg" alt="Mount Fuji in Japan"></p>
</details>
```

In Safari Tech Preview, Chrome Canary, Firefox Nightly, latest versions at this date. All of them are fetching the image right away. So closed and open states are not changing anything on the behavior for images.

**Comment by karlcow** [comment]
As a first step I will just put the full image, we may want to decide to put again the thumbnail later. Less urgent.

**Comment by karlcow** [comment]
See #3127 for the original PR where it was removed.

Some testing here:

https://github.com/webcompat/webcompat-tests-private/issues/21


FAIL

```md
<details>
    <summary>View the screenshot</summary>[![Screenshot Description](http://localhost:5000/uploads/2020/1/93dc9a96-5ce0-4e1b-92c6-de06a959b866.jpeg)](http://localhost:5000/uploads/2020/1/93dc9a96-5ce0-4e1b-92c6-de06a959b866.jpeg)</details>
```

FAIL

```md
<details>
    <summary>View the screenshot</summary>
[![Screenshot Description](http://localhost:5000/uploads/2020/1/93dc9a96-5ce0-4e1b-92c6-de06a959b866.jpeg)](http://localhost:5000/uploads/2020/1/93dc9a96-5ce0-4e1b-92c6-de06a959b866.jpeg)
</details>
```

SUCCESS

```md
<details><summary>View the screenshot</summary><img alt="Screenshot" src="http://localhost:5000/uploads/2020/1/93dc9a96-5ce0-4e1b-92c6-de06a959b866.jpeg"></details>
```
