### ISSUE TITLE
Create copy for 2 moderation scenarios

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat.com#3137]
We need text to cover 2 scenarios:

A pre-moderation message: something like, thanks for reporting an issue you can check back here once it's been moderated and made public. 

A post-moderation rejection message: this report doesn't follow our acceptable use guidelines. 

Note we don't have acceptable use guidelines, so it probably has to be more generic, or we adopt or hack Mozilla's: https://www.mozilla.org/en-US/about/legal/acceptable-use/

**Comment by karlcow** [comment]
## In Quarantine

```html
<p>This issue has been put in quarantine. A human
will review if the message meets our current 
<a href="/acceptable-use">acceptable use</a> guidelines. 
It will probably take a couple of days depending on the backlog.
Once it has been reviewed, the content will be either made public
or deleted.</p>
```

## Rejected Message

```html
<p>The content of this issue doesn't meet our 
<a href="/acceptable-use">acceptable use</a>
guidelines. Its original content has been deleted.</p>
```

## About the thanks.
As this is a generic message, I don't think the thanks should be part of the content.

**Comment by karlcow** [comment]
Dependencies on #3143 and #3138

**Comment by miketaylr** [comment]
I like the proposals, but I think the word quarantine has dramatic semantic connotations. I would recommend we just use "moderation".

**Comment by karlcow** [comment]
s/in quarantine/in the moderation queue./

**Comment by miketaylr** [comment]
(assigning to karl, since he did the work. we can probably just close this when #3150 is merged)
