### ISSUE TITLE
Create terms of acceptable use for site

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat.com#3138]
Relates to https://github.com/webcompat/webcompat.com/issues/3137.

We're moving to a moderation model for anonymous bug reports. We need to be able to link to what the terms are, so we have to create them.

Obviously illegal and abusive things are not acceptable.

Open question: ...what else?

**Comment by miketaylr** [comment]
Useful links here: 

https://www.mozilla.org/en-US/about/legal/acceptable-use/
https://help.github.com/en/github/site-policy/github-terms-of-service#c-acceptable-use

Maybe it's enough to defer to GitHub TOS in the short-term, since we're bound by them.

**Comment by miketaylr** [comment]
There's 2 parts to this. Defining the terms, and then creating a front-end for them. cc @magsout

**Comment by miketaylr** [comment]
A draft of something mostly stolen from bits of Mozilla & GitHub webpages, deferring to the terms on their sites. 

r? @karlcow

----

# WebCompat.com Terms of Service
Effective Date: Jan 14, 2020

Webcompat.com is a service that allows users to report web compatibility issues though a simple web form. Volunteers and employees of Mozilla view the reports, identify solutions, then share the reports and solutions with the website admins, or escalate bugs to browser vendors. For more details see our [About page](https://webcompat.com/about). 

## Acceptable Use

Your use of the Website and Service must not violate any applicable laws, including copyright or trademark laws, export control or sanctions laws, or other laws in your jurisdiction. You are responsible for making sure that your use of the Service is in compliance with laws and any applicable regulations.

Webcompat.com is sponsored and hosted by Mozilla, and as such, users are bound by the general [Mozilla Conditions of Use](https://www.mozilla.org/en-US/about/legal/acceptable-use/) as well as the [Mozilla Websites & Communications Terms of Use](https://www.mozilla.org/en-US/about/legal/terms/mozilla/)

Parts of webcompat.com are hosted on GitHub, and as such, users are bound by [GitHub Acceptable Use Policies](https://help.github.com/en/github/site-policy/github-terms-of-service#c-acceptable-use).

## User Generated Content

You may create or upload User-Generated Content while using the Service, but by doing so, agree to be bound by the [Mozilla Websites & Communications Content Terms](https://www.mozilla.org/en-US/about/legal/terms/mozilla/#446-content-submissions) and [GitHub terms for User-Generated Content](https://help.github.com/en/github/site-policy/github-terms-of-service#d-user-generated-content).

We do not pre-screen User-Generated Content, but we have the right (though not the obligation) to refuse or remove any User-Generated Content that, in our sole discretion, violates any of these terms or policies.

## Community Participation Guidelines

In addition to our own [Code of Conduct](https://github.com/webcompat/webcompat.com/blob/master/CODE_OF_CONDUCT.md), it's useful to model interactions with other users of the Service on the [Mozilla Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/) as well as the [GitHub Community Participation Guidelines](https://help.github.com/en/github/site-policy/github-community-guidelines). Behavior which falls into the areas forbidden by both documents is unwelcome and will result in further escalation.

**Comment by karlcow** [comment]
> # WebCompat.com Terms of Service

nit: Webcommpat is not camel cased elsewhere in the text.

> Webcompat.com is a Service that allows users to report web compatibility issues though a simple 

```diff
- though a simple 
+ through a simple 
```

> web form. Volunteers and employees of Mozilla view the reports, identify solutions, then share 
> the reports and solutions with the website admins, or escalate bugs to browser vendors. For 

```diff
- with the website admins
+ with the website stewards
```

> more details see our [About page](https://webcompat.com/about).

```diff
- details see
+ details, see
```

Maybe? 

> ## Acceptable Use
> 
> Your use of the Website and Service must not violate any applicable laws, including copyright or 

```diff
- Your use of the Website and Service 
+ Your use of the webcompat.com website and service 
```

> trademark laws, export control or sanctions laws, or other laws in your jurisdiction. You are 

**IANAL** 👨‍⚖  I don't think in the case of webcompat.com, "in your jurisdiction" matters. What is happening if someone posts a text where the author died 52 years ago? From Canada, no issue, the text is in the public domain. From USA, the text is still protected. And webcompat-bot is in this case the one posting things on GitHub.

but as I said maybe i'm talking non-sense.

> responsible for making sure that your use of the Service is in compliance with laws and any 
> applicable regulations.
> 
> Webcompat.com is sponsored and hosted by Mozilla, and as such, users are bound by the general [Mozilla Conditions of Use](https://www.mozilla.org/en-US/about/legal/acceptable-use/) as well as the [Mozilla Websites & Communications Terms of Use](https://www.mozilla.org/en-US/about/legal/terms/mozilla/)
> 
> Some parts of webcompat.com are hosted on GitHub, and as such, users are bound by [GitHub Acceptable Use Policies](https://help.github.com/en/github/site-policy/github-terms-of-service#c-acceptable-use).
> ## User Generated Content
> 
> You may create or upload User-Generated Content while using the Service, but by doing so, 

```diff
- while using the Service,
+ while using the webcompat.com service,
```

> agree to be bound by the [Mozilla Websites & Communications Content Submission terms](https://www.mozilla.org/en-US/about/legal/terms/mozilla/#446-content-submissions) and [GitHub terms for User-Generated Content](https://help.github.com/en/github/site-policy/github-terms-of-service#d-user-generated-content).
> 
> We do not pre-screen User-Generated Content, but we have the right (though not the obligation) 

pre-screen is not a term. Maybe something along:

```diff
- We do not pre-screen User-Generated Content,
+ We do not review before publication all User-Generated Content, except for anonymous bug report, 
```

> to refuse or remove any User-Generated Content that, in our sole discretion, violates any of these terms or policies.
> ## Community Participation Guidelines
> 
> In addition to our own [Code of Conduct](https://github.com/webcompat/webcompat.com/blob/master/CODE_OF_CONDUCT.md), it's useful to model interactions with other 
> users of the Service on the 

```diff
- users of the Service on the 
+ users of the webcompat.com service on the 
```


> [Mozilla Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/) as well as the [GitHub Community Participation Guidelines](https://help.github.com/en/github/site-policy/github-community-guidelines). Behavior which falls into the areas forbidden by either document is unwelcome and will result in further escalation.

I did my best with my current set of English skills. 🐨 🍷

**Comment by karlcow** [comment]
@miketaylr also on this previous comment.

is this correct

> Behavior which falls into

I thought you could say:

Behaviors which fall into…
or A behavior which falls into…

**Comment by softvision-sergiulogigan** [comment]
We think we should explicitly specify the content that will lead to an issue being not published.

**Comment by laghee** [comment]
> is this correct
> 
> > Behavior which falls into
> 
> I thought you could say:
> 
> Behaviors which fall into…
> or A behavior which falls into…

"Behavior" without the indefinite article is correct, but technically (or at least traditionally) speaking, it should be "behavior that falls into" in this case because it's a restrictive clause. 🤓

**Comment by miketaylr** [comment]
Thanks for the feedback @karlcow and @laghee!



> We think we should explicitly specify the content that will lead to an issue being not published.

I think we can perhaps get there in the future, but it's probably hard to list everything that violates TOS at first. There will have to be some kind of judgement applied. For now, I think just linking out to stuff that's bad is probably OK (but not perfect).

**Comment by miketaylr** [comment]
@karlcow 

> Behavior which falls into

Yeah, this is correct. Behavior is typically used as an "uncountable" noun, but sometimes the plural can be correct. I think either could probably work, but I'll leave it as is.

**Comment by miketaylr** [comment]
OK! updated version here:

-------

# webcompat.com Terms of Service
Effective Date: Jan 14, 2020

Webcompat.com is a Service that allows users to report web compatibility issues through a simple web form. Volunteers and employees of Mozilla view the reports, identify solutions, then share the reports and solutions with the website stewards, or escalate bugs to browser vendors. For more details, see our [About page](https://webcompat.com/about).

## Acceptable Use

Your use of the webcompat.com website and service must not violate any applicable laws, including copyright or trademark laws, export control or sanctions laws, or other laws. You are responsible for making sure that your use of the Service is in compliance with laws and any applicable regulations.

Webcompat.com is sponsored and hosted by Mozilla, and as such, users are bound by the general [Mozilla Conditions of Use](https://www.mozilla.org/en-US/about/legal/acceptable-use/) as well as the [Mozilla Websites & Communications Terms of Use](https://www.mozilla.org/en-US/about/legal/terms/mozilla/)

Some parts of webcompat.com are hosted on GitHub, and as such, users are bound by [GitHub Acceptable Use Policies](https://help.github.com/en/github/site-policy/github-terms-of-service#c-acceptable-use).

## User Generated Content

You may create or upload User-Generated Content while using the webcompat.com service, but by doing so, you agree to be bound by the [Mozilla Websites & Communications Content Submission terms](https://www.mozilla.org/en-US/about/legal/terms/mozilla/#446-content-submissions) and [GitHub terms for User-Generated Content](https://help.github.com/en/github/site-policy/github-terms-of-service#d-user-generated-content).

We do not review before publication all User-Generated Content, except for anonymous bug reports, but we have the right (though not the obligation) to refuse or remove any User-Generated Content that, in our sole discretion, violates any of these terms or policies.

## Community Participation Guidelines

In addition to our own [Code of Conduct](https://github.com/webcompat/webcompat.com/blob/master/CODE_OF_CONDUCT.md), it's useful to model interactions with other users of the webcompat.com service on the [Mozilla Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/) as well as the [GitHub Community Participation Guidelines](https://help.github.com/en/github/site-policy/github-community-guidelines). Behavior that falls into the areas forbidden by either document is unwelcome and will result in further escalation.

**Comment by miketaylr** [comment]
I'm gonna close this one, and open a new bug for the front-end part.

**Comment by softvision-sergiulogigan** [comment]
Here's a piece of (maybe) valuable information, from the CPG slack channel:

https://github.blog/changelog/2020-01-10-use-duplicate-as-a-reason-for-hiding-comments/
