### ISSUE TITLE
Adds specific identifier for anonymous issues in public repo

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat.com#3145]
Do they stay in "needstriage", or do we change that to "needsmoderation"?

**Comment by softvision-sergiulogigan** [comment]
What if we use "Pending Moderation"?

**Comment by karlcow** [comment]
Is it for triager to have to avoid to go through non-moderated bugs?
It could go to needstriage with a `label: quarantine`

**Comment by miketaylr** [comment]
I like needstriage + label. And yes, the idea is to be able to filter on them, or filter them out for whatever reason.

**Comment by karlcow** [comment]
* The needstriage milestone will already  be assigned automatically by @webcompat-bot 
* So We just need to add the right label by modifying the form. 

label name bikeshed:

`action-needsmoderation` https://github.com/webcompat/web-bugs/labels?utf8=%E2%9C%93&q=action

**Comment by karlcow** [comment]
Created label on 
* https://github.com/webcompat/webcompat-tests/labels?utf8=%E2%9C%93&q=action
* https://github.com/webcompat/web-bugs/labels?utf8=%E2%9C%93&q=action

**Comment by karlcow** [comment]
ok I have a workable solution I think. 
The tests are working. But the webhook is always a bit of a pain to test.

**Comment by karlcow** [comment]
This was closed by #3159 (I had just forgotten the right pound sign in the title.)
