### ISSUE TITLE
anonymous but not anonymous

### ISSUE THREAD

**Issue by karlcow** [webcompat/webcompat.com#3152]
So @miketaylr and I can reproduce this.

1. flask run with anonymous on.
   ANON_REPORTING_ENABLED = True
   in config/environment.py for LOCALHOST
2. login (oauth dance from webcompat)
3. logout (from webcompat too)
4. Go to http://127.0.0.1:5000/issues/new (so not logged)
5. fill the form
6. submit as anonymous
7. it goes at the right places on staging and private tests so that's good.

BUT

I tried and it reported as karlcow instead of anonymousbot. This is not good 🔥

**Comment by miketaylr** [comment]
(this may be a false alarm, but thanks for filing)

**Comment by karlcow** [comment]
🚨 So false alarm indeed.
It's that locally @miketaylr and I are using our personal token for testing things.

**Comment by softvision-sergiulogigan** [comment]
Sounds like something similar to https://github.com/webcompat/webcompat.com/issues/3054
