### ISSUE TITLE
Missing test for report_public_issue 

### ISSUE THREAD

**Issue by karlcow** [webcompat/webcompat.com#3158]
The current method `report_public_issue` doesn't have any tests.

https://github.com/webcompat/webcompat.com/blob/742d7c5a0bc1da562624c53feb282801cf38c29f/webcompat/issues.py#L54-L60

**Comment by karlcow** [comment]
This has been fixed by https://github.com/webcompat/webcompat.com/pull/3159/commits/8c3caa4d3a8e125859549322c35eaa5301682c4a

**Comment by ksy36** [comment]
we should probably test that the content of `post_data` (title and message) are equal to those returned from `test_moderation_template`, what do you think @karlcow ? I can add them :)

**Comment by karlcow** [comment]
@ksy36 We could. Could you open a new issue? Thanks.
