### ISSUE TITLE
Update namespaceRegex to include action

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat.com#3161]
We have some `action-foo` prefixed labels, https://github.com/webcompat/web-bugs/labels?utf8=%E2%9C%93&q=action

We should update the following Regexp to account for that: 
https://github.com/webcompat/webcompat.com/blob/d56cd783366d725bcf2cf560723a590faf41e08f/webcompat/static/js/lib/models/label-list.js#L27

**Comment by karlcow** [comment]
@miketaylr This requires to fix #2830 too.
Because right now we are still not getting the full list of labels.

**Comment by miketaylr** [comment]
Solving #2830 is *not* a good first bug, but agreed.
