### ISSUE TITLE
Investigate why anonymous reporting is enabled on staging

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat.com#3183]
Currently on staging we have the following `STAGING_ANON_REPORTING_ENABLED=False`, yet anonymous reporting is enabled.

I've verified on localhost, changing the value of `ANON_REPORTING_ENABLED` to True/False has the expected behavior.

**Comment by miketaylr** [comment]
Note: it's the same no matter which form version is received.

**Comment by karlcow** [comment]
@miketaylr for me on localhost, the anonymous reporting is set as 

```
        anon_reporting_enabled = app.config['ANON_REPORTING_ENABLED']
        print(anon_reporting_enabled)
```

console sends False

still the form displays the anonymous report button.

ah!

```jinja
        <button
          class="button button-secondary {{ 'js-Button' if anon_reporting_enabled else '' }}"
          id="submitanon"
          type={{ 'submit' if anon_reporting_enabled else 'button' }}
          name="github-proxy-report"
          {{ '' if anon_reporting_enabled else 'disabled' }}
        >
          {{'Report Anonymously' if anon_reporting_enabled else 'Anonymous reports temporarily disabled'}}
        </button>
```

And rendered as 

```html
<div class="button-wrapper js-Button-wrapper">
	<button class="button button-secondary js-Button is-disabled" id="submitanon" type="submit" name="github-proxy-report" disabled="">Report Anonymously</button>
</div>
```

If i test on the IDE

```python
>>> from jinja2 import Template
>>> anon_reporting_enabled = False
>>> tmpl = "{{'Report Anonymously' if anon_reporting_enabled else 'Anonymous reports temporarily disabled'}}"
>>> template = Template(tmpl)
>>> template.render()
'Anonymous reports temporarily disabled'
>>> anon_reporting_enabled = 'False'
>>> template.render()
'Anonymous reports temporarily disabled'
>>> anon_reporting_enabled = 'True'
>>> template.render()
'Anonymous reports temporarily disabled'
>>> anon_reporting_enabled = True
>>> template.render()
'Anonymous reports temporarily disabled'
```

something indeed is not working as expected

**Comment by karlcow** [comment]
So i don't think we are using a boolean value as jinja2 expects it.

**Comment by karlcow** [comment]
Probably we should rely on the `{% if %}  {% else %} {% endif %}` and have two separate strings.

**Comment by miketaylr** [comment]
We discovered that the env var is a string (we probably knew this... and forgot). So `if 'False' will always be truthy. Whoops!

@karlcow suggested we change the env var to have a value of 'on' and 'off'

**Comment by miketaylr** [comment]
And besides the templates, we should be sure to update the following as well: https://github.com/webcompat/webcompat.com/blob/master/webcompat/views.py#L308

**Comment by karlcow** [comment]
https://github.com/webcompat/webcompat.com/blob/acc45c14b08d476154778924f236d53001d75956/webcompat/views.py#L307-L309

This says: that if the config doesn't exist just bails out. which is correct. It will need to be changed if we change the name of the config. I suggest, we do:

`ANONYMOUS_REPORTING = ON/OFF`

it's more readable in code and templates.

**Comment by karlcow** [comment]
Also just for the context on why it was still working in production. It's because we had not yet deployed the environment variable version, so we didn't detect it was not working.

Probably an additional test to create. :)

**Comment by karlcow** [comment]
@miketaylr Just for the record. here… 
to [convert a string to a boolean in python](https://docs.python.org/3/distutils/apiref.html#distutils.util.strtobool). hat tip to @rik

**Comment by rik** [comment]
The implementation is pretty straight forward and would raise for misconfigured values: https://github.com/python/cpython/blob/39afa2d3147e4b05a1161cc90dbf09b95072c2bb/Lib/distutils/util.py#L307-L320
