### ISSUE TITLE
Anonymous reporting works on staging but fails on prod

### ISSUE THREAD

**Issue by karlcow** [webcompat/webcompat.com#3195]
So the issue is created in public but the private issue is not created at all.
We need to figure out why.

**Comment by karlcow** [comment]
@miketaylr fyi
(env) ~/code/webcompatdevops/deployment % fab deploy -b karlcow:3195/1 -t staging

**Comment by karlcow** [comment]
ok so this logging is not breaking staging at least. 

```
Feb 11 03:58:34 staging-server webcompat-staging: [2020-02-11 03:58:34,071] INFO in views: 210.194.53.2 b'http://loganonymous.example.com'

Feb 11 03:58:34 staging-server webcompat-staging: [2020-02-11 03:58:34,679] INFO in issues: anonymous report public status: 201

Feb 11 03:58:34 staging-server webcompat-staging: [2020-02-11 03:58:34,681] INFO in issues: anonymous private form: MultiDict([('url', 'http://loganonymous.example.com'), ('problem_category', 'detection_bug'), ('other_problem', ''), ('browser', 'Firefox 74.0'), ('os', 'Mac OS X 10.15'), ('tested_browsers', 'Safari'), ('browser_test', 'yes'), ('steps_reproduce', 'this will be long very long journey'), ('contact', ''), ('username', ''), ('details', 'null'), ('reported_with', ''), ('ua_header', 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:74.0) Gecko/20100101 Firefox/74.0'), ('submit_type', 'github-proxy-report'), ('extra_labels', ['form-v2-experiment']), ('console_logs_url', ''), ('description', 'Desktop site instead of mobile site'), ('csrf_token', '****')])

Feb 11 03:58:34 staging-server webcompat-staging: [2020-02-11 03:58:34,682] INFO in issues: anonymous private path: repos/webcompat/webcompat-tests-private/issues

Feb 11 03:58:34 staging-server webcompat-staging: [2020-02-11 03:58:34,683] INFO in issues: anonymous private: {'title': 'loganonymous.example.com - desktop site instead of mobile site', 'body': '<!-- @browser: Firefox 74.0 -->\n<!-- @ua_header: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:74.0) Gecko/20100101 Firefox/74.0 -->\n<!-- @reported_with:  -->\n<!-- @public_url: https://github.com/webcompat/webcompat-tests/issues/2395 -->\n<!-- @extra_labels: form-v2-experiment -->\n\n**URL**: http://loganonymous.example.com\n\n**Browser / Version**: Firefox 74.0\n**Operating System**: Mac OS X 10.15\n**Tested Another Browser**: Yes Safari\n\n**Problem type**: Desktop site instead of mobile site\n**Description**: Desktop site instead of mobile site\n**Steps to Reproduce**:\nthis will be long very long journey\n\n<details>\n<summary>Browser Configuration</summary>\n<ul>\n  <li>None</li>\n</ul>\n</details>\n\n_From [webcompat.com](https://webcompat.com/) with ❤️_', 'milestone': 1}

Feb 11 03:58:35 staging-server webcompat-staging: [pid: 10702|app: 0|req: 13/54] 192.30.252.97 () {44 vars in 689 bytes} [Tue Feb 11 03:58:35 2020] POST /webhooks/labeler => generated 23 bytes in 3 msecs (HTTP/1.1 403) 8 headers in 824 bytes (1 switches on core 0)

Feb 11 03:58:35 staging-server webcompat-staging: [2020-02-11 03:58:35,491] INFO in issues: anonymous private status: 201
````

**Comment by karlcow** [comment]
so this is interesting.

instead I changed my local configuration so my local instance would be posting on the live repos.
https://github.com/webcompat/web-bugs/issues/48021
https://github.com/webcompat/web-bugs-private/issues/66

then i closed it from the private repos and everything worked well.

The only difference is that `karlcow`  oauth was used instead of webcompat-bot.

**Comment by karlcow** [comment]
ok I have a theory. Let's try to reactivate the anonymous reporting on production

I unticked this.

<img width="818" alt="Capture d’écran 2020-02-11 à 13 19 57" src="https://user-images.githubusercontent.com/505230/74211077-acd90100-4cd1-11ea-93b2-7ce249331eec.png">

**Comment by karlcow** [comment]
this didn't work. :)

**Comment by karlcow** [comment]
ok I found the issue and I don't know yet why this is happening, but that's an interesting issue. 

I made `webcompat-tests-private` actually private and it **stopped working** as expected. webcompat-bot is unable to create an issue.

1. as karl i can file an issue on a private repo cf https://github.com/webcompat/webcompat.com/issues/3195#issuecomment-584472172
2. as webcompat-bot reporting in private is not working.

**Comment by karlcow** [comment]
<img width="172" alt="Capture d’écran 2020-02-11 à 15 12 59" src="https://user-images.githubusercontent.com/505230/74214518-0e549c00-4ce1-11ea-9ad2-183d42db3e15.png">

is it because webcompat-bot is not 2fa

**Comment by karlcow** [comment]
yeah when I switched webcompat-tests-private to private instead of public, this time webcompat-bot received.

```
Feb 11 06:05:00 staging-server webcompat-staging: [2020-02-11 06:05:00,591] INFO in issues: anonymous private status: 404
```

so we need to do something along this.
https://developer.github.com/v3/auth/#working-with-two-factor-authentication

**Comment by karlcow** [comment]
But the issue with this is that a bot will not be able to do OTP.

**Comment by karlcow** [comment]
ah no maybe just a personal access token would work
https://help.github.com/en/github/authenticating-to-github/accessing-github-using-two-factor-authentication#using-two-factor-authentication-with-the-command-line

**Comment by miketaylr** [comment]
Strange. I just double checked, and we don't require 2FA (but we probably should!)
<img width="674" alt="Screen Shot 2020-02-11 at 8 53 59 AM" src="https://user-images.githubusercontent.com/67283/74259022-11816500-4cac-11ea-8b4f-45c1b62f1f0a.png">

**Comment by miketaylr** [comment]
Ah, I think I understand the issue. I bet a diet coke that the OAuth token we prevously had was restricted to `public_repo` scope. We need full repo scope in order to access private repos. I'll generate a new token and stick it on the server.

**Comment by miketaylr** [comment]
I see that you made the webcompat-tests-private repo actually private, so I'm going to re-deploy master to staging and test with the new token and test.

**Comment by karlcow** [comment]
> Ah, I think I understand the issue. I bet a diet coke that the OAuth token we prevously had was restricted to `public_repo` scope. We need full repo scope in order to access private repos. I'll generate a new token and stick it on the server.

Ah I didn't know/remember that oauth token had scopes. Thanks.

**Comment by karlcow** [comment]
So this was solved by @miketaylr through creating a new token with better scopes.
let's close it here.
