### ISSUE TITLE
Closing a private issue after it's been moved to "accepted" sets the moderation template to rejected

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat.com#3197]
I don't know if this is expected behavior...

STR: 
1. file anon issue
2. moderate as accepted
3. close issue

Expected: nothing changes
Actual: the public issue is set to rejected

It seems useful to be able to close accepted issues, so we don't have to keep looking at them. I guess the workaround is to filter on milestone, but the default view of "is:issue is:open" seems easier to work with.

https://github.com/webcompat/web-bugs/issues/48038 is an example where I accidentally discovered this. The history looks messy :P

**Comment by miketaylr** [comment]
@softvision-sergiulogigan @softvision-oana-arbuzov @cipriansv until this issue is fixed (or closed as WONTFIX?), after moderating an issue please leave the issue open.

**Comment by karlcow** [comment]
interesting.

**Comment by karlcow** [comment]
Ah yes it was part of the logic! So it's normal. I guess i could fence that with if it has the milestone accepted, do not edit the issue in public.
