### ISSUE TITLE
change blacklisted by blocked or denied

### ISSUE THREAD

**Issue by karlcow** [webcompat/webcompat.com#3199]
This is an easy one.
https://github.com/webcompat/webcompat.com/search?q=blacklisted&type=Code

Context: 
https://twitter.com/TheAmyCode/status/1227254024656711680

**Comment by miketaylr** [comment]
+1, I like "blocklist" + "allowlist"

**Comment by apsychogirl** [comment]
HI, Can I take this up?

**Comment by karlcow** [comment]
@apsychogirl Sure.

1. Make sure to read 
  1. https://github.com/webcompat/webcompat.com/blob/master/docs/dev-env-setup.md
  2. https://github.com/webcompat/webcompat.com/blob/master/docs/pr-coding-guidelines.md
2. fork the project
3. clone in on your local computer
4. create a branch with the name `3199/1`
5. code
6. push your branch to your fork
7. create a pull request. 

and ask me as a reviewer. 

Thanks!
