### ISSUE TITLE
flask_github.GitHubError: 401: Bad credentials

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat.com#32]
We can sometimes get into a funky state when flipping between production and dev oauth callback URIs.

If this happens, we should take action on behalf of the user, redirecting to re-login (or whatever).

**Comment by gluons** [comment]
I face this issue.

![screenshot_2018-10-22 issues webcompat com](https://user-images.githubusercontent.com/4688092/47296351-2f046880-d63c-11e8-8842-5c0230983056.png)
