### ISSUE TITLE
Comment with the location of the public bug in the private repo

### ISSUE THREAD

**Issue by karlcow** [webcompat/webcompat.com#3201]
1. anonymous report is being published in private repo
2. moderation template in public
3. Should a comment be made automatically by webcompat-bot into the private repo with the location of the issue to the public repo?

Rationale:
the location is here in the html comment but not visible to the moderators. Does it matter?
Maybe it matters once the issue has been moderated for understanding the context.

@miketaylr @ksy36 @softvision-oana-arbuzov @softvision-sergiulogigan @cipriansv 
Thoughts?

**Comment by softvision-sergiulogigan** [comment]
We think that that would improve our workflow.
Once an issue has been `accepted`, a link with the public issue would help us jump right into triaging, that issue.

**Comment by miketaylr** [comment]
>  Once an issue has been `accepted`, a link with the public issue would help us jump right into triaging, that issue.

This sounds like a good improvement.
