### ISSUE TITLE
Notification message about illegal content should be available on the form

### ISSUE THREAD

**Issue by softvision-oana-arbuzov** [webcompat/webcompat.com#3207]
URL: https://webcompat.com/issues/new

Browser / Version: Firefox Nightly 75.0a1 (2020-02-11), Chrome 80.0.3987.87
Operating System: Windows 10 Pro
Tested Another Browser: Yes

**Steps to Reproduce:**
1. Navigate to https://webcompat.com/issues/new
2. Observe the form and screenshot area.

**Expected result:**
A message is displayed, informing the reporter to avoid reporting and uploading illegal content on the site.

**Actual result:**
There is not message informing the reporter about reporting and uploading illegal content on the site.

**Notes:**
1. Screenshot attached with a relevant message about illegal content and a link to a site where this type of issues can be reported (https://safebrowsing.google.com/safebrowsing/report_badware/).
This should be applicable to both webcompat.com forms.
![Screenshot_3](https://user-images.githubusercontent.com/12184325/74325511-6e0a8000-4d91-11ea-983e-d0630067b454.jpg)

![Screenshot_5](https://user-images.githubusercontent.com/12184325/74325521-72cf3400-4d91-11ea-9bbe-4aa61d6dfd67.jpg)
    
**Watchers:**
@softvision-oana-arbuzov
@softvision-sergiulogigan
@cipriansv

**Comment by miketaylr** [comment]
I would avoid writing "child porn", but something link to the terms would be good.

**Comment by soniasingla** [comment]
Can I take this issue? :)

**Comment by chenjefferson** [comment]
First time contributor. I would like to work on this issue! Is it still open?

**Comment by karlcow** [comment]
Yes! 
There is [documentation](https://github.com/webcompat/webcompat.com/blob/master/.github/CONTRIBUTING.md)  covering all the initial steps for starting with the project and starting with the first pull request. 

If you are stuck somewhere, the document also includes information on how and where to get help!
