### ISSUE TITLE
Missing whitespace in copy on step 7 of new issue wizard

### ISSUE THREAD

**Issue by ecsmyth** [webcompat/webcompat.com#3210]
## STR
1. Start a new webcompat issue report (e.g., action "Report site issue..." from ellipsis menu in Firefox address bar)
2. Fill out report through step 7, "Send report"

## Observed
![image](https://user-images.githubusercontent.com/17688672/74790459-71f44180-526c-11ea-885d-a27ba3e9efea.png)

## Expected
Whitespace between `GitHub` and `or`

**Comment by miketaylr** [comment]
Whoops, thanks :)
