### ISSUE TITLE
Make it possible to navigate to the next step by pressing Enter [New UI]

### ISSUE THREAD

**Issue by ksy36** [webcompat/webcompat.com#3223]
<img width="1089" alt="Screen Shot 2020-02-27 at 11 08 33 AM" src="https://user-images.githubusercontent.com/1303908/75462193-db9ddb00-5951-11ea-9dc7-5287864740a7.png">

After entering url and pressing "Enter" nothing happens (even if "Confirm" button is focused). It would be nice to be able to switch to the next step. This is reproducible with all other buttons in the wizard.

This along with https://github.com/webcompat/webcompat.com/issues/2965 and https://github.com/webcompat/webcompat.com/issues/2970 will allow users to submit an issue without relying on a mouse for navigation

**Comment by miketaylr** [comment]
This would be a nice improvement, yes!

**Comment by ksy36** [comment]
This has been added in the refactored version. Note that Tab navigation will be addressed in https://github.com/webcompat/webcompat.com/issues/3396
