### ISSUE TITLE
Check if screenshot deps are installed from make target

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat.com#323]
If users don't have casperjs, phantomjs and slimerjs when they try to run the screenshot Make target, we should echo for them to install:

```
[sudo] npm install casperjs@1.1.0-beta3 -g
[sudo] npm install phantomjs -g
[sudo] npm install slimerjs -g
```

This is not a high priority, but would be nice.

**Comment by deepthivenkat** [comment]
I should be editing the [Makefile](https://github.com/webcompat/webcompat.com/blob/60637b1b5885869c42a98e7513ddf8821455b9f9/Makefile)

like this?

target:
	@ echo "❯ Installing casperjs@1.1.0-beta3, phantomjs, slimerjs"
        npm install casperjs@1.1.0-beta3 -g
        npm install phantomjs -g
        npm install slimerjs -g

**Comment by miketaylr** [comment]
This makes no sense. If we wanted this, they should just have been devDependencies in package.json. But, I don't think anybody uses this.
