### ISSUE TITLE
Increase default textarea size of detailed steps

### ISSUE THREAD

**Issue by wesinator** [webcompat/webcompat.com#3241]
Firefox 73.0.1 macOS 10.14.6
macbook pro 15-inch retina 

Would you mind increasing the default size of the detailed steps text area ? 
<img width="1305" alt="image" src="https://user-images.githubusercontent.com/5124946/76666117-077aac80-655f-11ea-9507-bb4ead9997b1.png">
the default text area size only shows two lines of text, also there is a lot more available, unused space right under the text area.

Thanks,

**Comment by karlcow** [comment]
This is the old form which is not used anymore. 
So I guess this issue is now moot
The new form is 

<img width="1110" alt="Capture d’écran 2020-05-14 à 14 02 31" src="https://user-images.githubusercontent.com/505230/81894769-95205a00-95eb-11ea-81c7-2a506ea06d4d.png">


Thanks @wesinator
