### ISSUE TITLE
Turn on Form v2 to 100% for a week

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat.com#3243]
In order to judge the impact on report volume (since metrics seem a little broken right now), I think we should go to 100% for 7 days, then we can go back to 50% if we feel the need to.

**Comment by miketaylr** [comment]
Any objections @karlcow, @ksy36?

**Comment by ksy36** [comment]
no objections

**Comment by miketaylr** [comment]
OK, I changed relevant env vars to:

```
env = FORM_V1_VARIATION=0 0
env = FORM_V2_VARIATION=0 100
```

Just now, and restarted the server.

**Comment by karlcow** [comment]
go for it with my objection. Kidding.
