### ISSUE TITLE
Sometimes the ML bot overrides an already closed issue

### ISSUE THREAD

**Issue by cipriansv** [webcompat/webcompat.com#3244]
**Steps to reproduce:**
1. Moderate an issue.
2. Move the issue to needstriage repo.
3. Access immediately the issue in the needstriage repo and triage it accordingly.
4. Observe the ML bot behavior.

**Expected Behavior:**
The ML bot must detect that an issue is already closed and not take any further action upon it.

**Actual Behavior:**
Sometimes the ML bot overrides the already closed issue modifying the milestone to invalid.

**Notes:**
1. See https://github.com/webcompat/web-bugs/issues/49917

**Watchers:**
@softvision-oana-arbuzov
@softvision-sergiulogigan

sv;

**Comment by miketaylr** [comment]
@cipriansv can you file a bug @ https://github.com/mozilla/webcompat-ml please (then this can be closed)

**Comment by karlcow** [comment]
@miketaylr @cipriansv probably this should be on https://github.com/mozilla/webcompat-ml-deploy/

**Comment by cipriansv** [comment]
Thanks, @karlcow.
I filed a new issue in the suggested repo: https://github.com/mozilla/webcompat-ml-deploy/issues/7.
