### ISSUE TITLE
Actually Enable form v2 for 100% of people

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat.com#3250]
We enabled form v2 for 100% of new users... but it's not really enabled, depending on DNT and *possibly* logged in status. 

https://github.com/webcompat/webcompat.com/blob/d1c3b122fac11a2c6cc838c67cc358a23d5df8a6/webcompat/helpers.py#L706-L733

I think we should remove the DNT restriction -- if everyone has it on, it's not tracking. And we're not storing or sharing that info.

**Comment by miketaylr** [comment]
(And we can add @karlcow to `AB_EXEMPT_USERS` to know that that code path actually works. :))

https://github.com/webcompat/webcompat.com/blob/d1c3b122fac11a2c6cc838c67cc358a23d5df8a6/webcompat/helpers.py#L701

**Comment by miketaylr** [comment]
cf https://github.com/webcompat/webcompat.com/issues/3249

**Comment by karlcow** [comment]
> I think we should remove the DNT restriction -- if everyone has it on, it's not tracking. And we're not storing or sharing that info.

Agreed. It's just the new thing. We are recording the info through the label and it's how we detected the issue. BUT the label should probably go away too if it's the new norm.

One thing though… `ab_current_experiments()` is supposed to be a generic function of experimentation, not really tied to the form experiment. If the new form is our new way of doing things, we don't need it to pass it through the ab experiment code.

**Comment by karlcow** [comment]
So the `AB_EXPERIMENTS` is here 
https://github.com/webcompat/webcompat.com/blob/d1c3b122fac11a2c6cc838c67cc358a23d5df8a6/config/__init__.py#L240-L251

Maybe this should be removed.

**Comment by karlcow** [comment]
so maybe the only line to modify is here.

https://github.com/webcompat/webcompat.com/blob/d1c3b122fac11a2c6cc838c67cc358a23d5df8a6/webcompat/views.py#L269-L274
