### ISSUE TITLE
intern.json configuration file.

### ISSUE THREAD

**Issue by karlcow** [webcompat/webcompat.com#3254]
In December, we upgraded intern to 4.7.1 in package.json

```
    "intern": "4.7.1",
```

It seems that the way to [configure intern](https://theintern.io/docs.html#Intern/4/docs/docs%2Fconfiguration.md/config-file) now is through an `intern.json` file.

Should we do that?

**Comment by miketaylr** [comment]
We can try!

I think we might lose out on some of the custom stuff we have in `_intern.js`, like the `grep` stuff, but maybe that can be done via intern.json.

**Comment by miketaylr** [comment]
We also do a custom thing for CircleCI here:

```
// custom Firefox binary location, if specified then the default is ignored.
// ref: https://code.google.com/p/selenium/wiki/DesiredCapabilities#WebDriver
if (args.firefoxBinary) {
  config.capabilities["moz:firefoxOptions"].binary = args.firefoxBinary;
}
```

And

```
node --max-old-space-size=8192 ./tests/functional/_intern.js --reporters="runner" 
--firefoxBinary=`which firefox`
```

But maybe we can pass it a custom config.json or something. LETS FIND OUT.
