### ISSUE TITLE
Running tests with intern locally

### ISSUE THREAD

**Issue by karlcow** [webcompat/webcompat.com#3255]
In our documentation we are telling people that it's possible to run the test locally. I tried a couple of times, without success.

Just me, or the doc is wrong. 
In one window `npm run start:test` 
In another one `npm run test:js`

This is not working. nothing is really starting.

**Comment by ksy36** [comment]
Do you see any errors when running `npm run start:test`?

I have `python` linking to python 2 and `python3` linking to python 3, so I run test server with this command:

`source env/bin/activate && python3 run.py -t`

If I try running the server with python 2 I get this error:

```
dyld: Library not loaded: @executable_path/../.Python
  Referenced from: /Users/ksenia/Documents/projects/webcompat.com/env/bin/python
  Reason: image not found
Abort trap: 6
```

`npm run start:test` still has `python` in it, so I don't use it:

```js
"start:test": "npm run build && source env/bin/activate || . env/bin/activate && python run.py -t",
```

But I'd assume you may have it set up differently @karlcow ?

**Comment by karlcow** [comment]
my python default is linked to python3. The server is starting. with no error messages. 
The `npm run start:test` just does one request on the server, and nothing else is happening. I'm still trying to figure out why. So I assume this is working for you @ksy36. That's good to know. I need to figure out if something is wrong in my own config.

**Comment by karlcow** [comment]
sorry i meant. And i just tried with the current master and no tests is running.

```
(env) ~/code/webcompat.com % npm run test:js

> webcompat@ test:js /Users/karl/code/webcompat.com
> node ./tests/functional/_intern.js

(env) ~/code/webcompat.com % 
```

which triggers in the other terminal window.

```
127.0.0.1 - - [25/Mar/2020 08:32:38] "GET /api/issues/100 HTTP/1.1" 200 -
```

**Comment by karlcow** [comment]
Oh wait I'm dumb… I switch to zsh a couple of weeks ago… and reconfigure from start my profile…

> The firefox binary will also need to be in your PATH. Here's how this can be done on OS X:
>
> `export PATH="/Applications/Firefox.app/Contents/MacOS/:$PATH"`

Let's reconfigure this to see if it changes things. 
So that was missing but it didn't change anything.

```
(env) ~/code/webcompat.com % nvm list
        v6.10.2
->      v9.10.0
       v12.10.0
         system
default -> 9.10.0 (-> v9.10.0)
node -> stable (-> v12.10.0) (default)
stable -> 12.10 (-> v12.10.0) (default)
iojs -> N/A (default)
unstable -> N/A (default)
nvm_list_aliases:36: no matches found: /Users/karl/.nvm/alias/lts/*
```

let's be more modern. `nvm use v12.10.0`
nope still a fail.

**Comment by karlcow** [comment]
* [x] PATH is good.
* [x] npm latest version
* [x] java

```
java -version 
java version "1.7.0_51"
Java(TM) SE Runtime Environment (build 1.7.0_51-b13)
Java HotSpot(TM) 64-Bit Server VM (build 24.51-b03, mixed mode)
```

Though the panel says Java 8.241 (build 1.8.0_241-b07)
Let's reinstall java, just in case.

Let's restart

**Comment by karlcow** [comment]
restarting doesn't give me the good version of java interesting.
I removed java entirely but the system still shows it, which means the update was installing it elsewhere, I'll need to figure out where. 

```
sudo rm -rf /Library/Java/JavaVirtualMachines/jdk1.7.0_51.jdk
(env) ~/code/webcompat.com % java -version                                                             
No Java runtime present, requesting install.
```

and now trying to start the tests it says that java is not installed. Ok so that was my java version which was busted. Now I need to figure out where it installed it instead.

**Comment by karlcow** [comment]
wow…
```
(env) ~/code/webcompat.com % /Library/Internet\ Plug-Ins/JavaAppletPlugin.plugin/Contents/Home/bin/java -version
java version "1.8.0_241"
Java(TM) SE Runtime Environment (build 1.8.0_241-b07)
Java HotSpot(TM) 64-Bit Server VM (build 25.241-b07, mixed mode)
```

This is where it was hidden.
https://community.intersystems.com/post/fixing-java-version-osx

ANd this is a mess. 
https://docs.oracle.com/javase/9/install/installation-jdk-and-jre-macos.htm

**Comment by karlcow** [comment]
Added to my .zshrc these:

```
# * Adding Firefox for webdriver testing *
export PATH=/Applications/Firefox.app/Contents/MacOS/:$PATH

# * Adding JAVA_HOME location *
export JAVA_HOME="/Library/Internet\ Plug-Ins/JavaAppletPlugin.plugin/Contents/Home"
```

and this is now working. Holy Cow 🐄
