### ISSUE TITLE
Using "Report Site Issue" button from Private Mode opens the form in Standard Mode 

### ISSUE THREAD

**Issue by cipriansv** [webcompat/webcompat.com#3261]
As reported in https://github.com/webcompat/web-bugs/issues/50779:

On **Firefox Preview Nightly** in **Private Mode**:
 1. Access any site.
2. Use the "Report site" issue button.
3. Observe the opened window.

**Expected result:**
The window must be opened in Private Mode.

**Actual result:**
The window opens in Standard Mode.

**Watchers:**
@softvision-oana-arbuzov
@softvision-sergiulogigan

sv;

**Comment by miketaylr** [comment]
@cipriansv can you file this bug against the Fenix repo? We can't control it from our end of things.

**Comment by cipriansv** [comment]
@miketaylr, I filed an issue in the Fenix repo: https://github.com/mozilla-mobile/fenix/issues/9536.
