### ISSUE TITLE
When API requests rate limit is reached, use webcompat issues DB for results

### ISSUE THREAD

**Issue by karlcow** [webcompat/webcompat.com#327]
> Another idea (for the future) is we have a local db of all issues title and states and the search is tapping there when we reached the limit of API requests.

This came during a discussion on issue #313 and has a dependency on #165.
We record this for a future feature, but thinking on how it should be working is welcome in the meantime.

**Comment by miketaylr** [comment]
So, this is technically interesting, but we've never come close to needing it. Let's reopen when we need it.
