### ISSUE TITLE
Migrate to dependabot

### ISSUE THREAD

**Issue by magsout** [webcompat/webcompat.com#3272]
![Screen Shot 2020-04-02 at 21 12 01](https://user-images.githubusercontent.com/1997108/78292024-affcaa80-7526-11ea-9afb-3b077ec2d7aa.png)

Dependabot is owned and maintained by GitHub https://github.com/marketplace/dependabot-preview

**Comment by magsout** [comment]
we already us it on metrics client

**Comment by miketaylr** [comment]
SGTM!

**Comment by magsout** [comment]
I removed  greenkeeper  from webcompat repo

**Comment by magsout** [comment]
I added dependabot with this config:

![Screen Shot 2020-04-29 at 21 21 00](https://user-images.githubusercontent.com/1997108/80637498-63da5280-8a5f-11ea-921e-cfb664f18689.png)


Monthly updated should enough, I guess?

**Comment by karlcow** [comment]
This is done! 
and the changelog has been modified too. See #3301
