### ISSUE TITLE
Make issue moderation more efficient

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat.com#3291]
Thinking of ways to optimize issue moderation. Right now the workflow is basically:

1. look at the issue, make sure it's not a violation of our TOS
2. move it to the accepted milestone
3. close the issue
(and then probably go triage the issue)

That's 2 clicks and it gets annoying, because you have to wait on GitHub's UI. Kind of slow sometimes.

Just by moderating some issues, it's obvious that they are acceptable, but invalid. It makes me think we could speed up certain interactions.

A couple of ideas that wouldn't be hard to implement:

1. a browser addon that adds a button somewhere that moves it to "accepted" and closes the issue in one click (via the API in the background). it could even open a new tab with the public issue right after, if that was part of the workflow.

2. a command line tool to do something similar (seems like a not great idea, unless it was connected to your browsing session. having to enter in URLs wouldn't be an improvement)

3. add some common milestones like "accepted: invalid" or "accepted: incomplete". Once you change the milestone, we have the app close the issue, and put in some template comment on the public issue, and close that issue.

I think the 3rd option would be pretty simple.

**Comment by softvision-sergiulogigan** [comment]
> 3\. add some common milestones like "accepted: invalid" or "accepted: incomplete". Once you change the milestone, we have the app close the issue, and put in some template comment on the public issue, and close that issue.

I personally think that this is the more cool thing to do.

**Comment by softvision-sergiulogigan** [comment]
We have 2 similar ways we do Moderation:

1. We open a batch of issues (or maybe even all of them), evaluate them, close the ones that are not fit for the public, and after that, we accept and close the rest in batch (all at once).
*Accept and Close in batch*

2. We open a batch of issues (or maybe even all of them), evaluate them, close the ones that are not fit for the public, accept the rest one by one and after that, we close the rest in batch (all at once).
*Accept each one at a time and Close in batch*

We think that the solution which would satisfy both scenarios, would be to have an `accepted - invalid` milestone that, once selected, triggers a script that closes and moves the public issue into the Invalid milestone, with a predefined message.
