### ISSUE TITLE
changelog.py script unable to handle commit messages from @dependabot

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat.com#3297]
```
Traceback (most recent call last):
  File "tools/changelog.py", line 139, in <module>
    sys.exit(main())
  File "tools/changelog.py", line 119, in main
    loglines = create_changelog(json_response)
  File "tools/changelog.py", line 59, in create_changelog
    title = normalize_title(issue['title'])
  File "tools/changelog.py", line 87, in normalize_title
    title = log_line.format(msg=m.groupdict())
AttributeError: 'NoneType' object has no attribute 'groupdict'
```

Probably from https://github.com/webcompat/webcompat.com/pull/3296 (we switched to a new dependency bot thingy):

`Bump grunt from 1.0.4 to 1.1.0`

**Comment by miketaylr** [comment]
https://github.com/webcompat/webcompat.com/blob/ed96b3d8169babd0d1260a638283b7f4bbee3bb8/tools/changelog.py#L72-L88

And see also the tests:

https://github.com/webcompat/webcompat.com/blob/ed96b3d8169babd0d1260a638283b7f4bbee3bb8/tests/unit/test_tools_changelog.py#L36-L61

**Comment by miketaylr** [comment]
(I'm being lazy, so I will manually fix the PR title, but is maybe a good bug for you to pick up @apsychogirl, if you're interested!)

**Comment by miketaylr** [comment]
Before we relied on `🚀` in the title to know it was an NPM update, so I guess now we need to be a little more clever.

**Comment by apsychogirl** [comment]
I'll definitely give it a try.

**Comment by miketaylr** [comment]
Great! Let me know if you get stuck or need any pointers.

**Comment by apsychogirl** [comment]
Hi, I was trying to rebuild the error, but wasn't able to. How can I proceed further? :(

**Comment by karlcow** [comment]
@apsychogirl always start with a test covering what you want to test, run the test suite and you will see if it fails or not. The test suite is the key. :)

**Comment by apsychogirl** [comment]
Hi, actually I am unable to reciprocate the error on my machine :(

**Comment by karlcow** [comment]
@miketaylr changed the original title to make it pass.

<img width="735" alt="Capture d’écran 2020-05-07 à 21 51 57" src="https://user-images.githubusercontent.com/505230/81296553-04a6be80-90ad-11ea-8b30-204648263e97.png">

The test is probably something along

> Bump grunt from 1.0.4 to 1.1.0

checking on other projects, the message always start with Bump.

**Comment by karlcow** [comment]
This is the test, you need to add,

```
     # dependabot-review title style 
     actual = changelog.normalize_title('Bump grunt from 1.0.4 to 1.1.0') 
     expected = 'NPM update - grunt from 1.0.4 to 1.1.0' 
     assert actual == expected
```

then run pytest, see how it fails, and try to fix the function `changelog.normalize_title`

:)
