### ISSUE TITLE
Remove GA tracking code for steps in form 

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat.com#3305]
No longer needed.
Added in #3100

**Comment by karlcow** [comment]
https://github.com/webcompat/webcompat.com/pull/3101/files

**Comment by miketaylr** [comment]
I guess we could revert that PR, or just have @ksy36 not port it over to her rewrite?

**Comment by ksy36** [comment]
Yeah, I didn't move the tracking code to the refactored version
