### ISSUE TITLE
Create a "model" test file using pytest

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat.com#3310]
@karlcow do you want to port over any unit test file from unittest/nose to pytest? It would be nice to have something to model after, and then we can update docs as well (pointing to the flask + other useful articles).

**Comment by karlcow** [comment]
Good idea.

**Comment by karlcow** [comment]
And indeed this needs a good rewrite.
https://github.com/webcompat/webcompat.com/blob/master/docs/tests.md#writing-tests
