### ISSUE TITLE
label browser-firefox-mobile is added to an issue reported through fenix reporter

### ISSUE THREAD

**Issue by ksy36** [webcompat/webcompat.com#3314]
I've reported this issue in Firefox Preview Nightly 
https://github.com/webcompat/web-bugs/issues/53357

Even though `label=browser-fenix` was in the url from the reporter, the issue ended up having `browser-firefox-mobile` label (Fennec). I would expect it having `browser-fenix` label instead

**Comment by miketaylr** [comment]
@karlcow is this something you could investigate when you have some spare cycles?

**Comment by karlcow** [comment]
@ksy36 @miketaylr 

```
<!-- @browser: Firefox Mobile 78.0 -->
<!-- @ua_header: Mozilla/5.0 (Android 6.0.1; Mobile; rv:78.0) Gecko/78.0 Firefox/78.0 -->
<!-- @reported_with:  -->
<!-- @public_url: https://github.com/webcompat/web-bugs/issues/53357 -->
```

The `reported_with` is blank

so I decided to try on Firefox Preview Nightly and going through the form until the end but submitting. And If we look at the URL at this moment there is no `label=browser-fenix` in the URI.

so I decided to try to open 
  `http://127.0.0.1:5000/issues/new?label=browser-fenix` 
on the desktop to force the extra-label

And this is what I get for `formEl` related to the extra_labels

`<input id="extra_labels" name="extra_labels" type="hidden" value="">`



<img width="539" alt="Capture d’écran 2020-06-15 à 16 31 07" src="https://user-images.githubusercontent.com/505230/84629732-c1e6ca80-af25-11ea-93f3-1dacd3b5a23e.png">

is the extra labels code working at all right now? It seems the URI -> (js) -> HTML input is not doing its job currently.


hmmm…

The code never seems to go through this. It's calling it but never go in. We can see that if we put breakpoints inside. And it's never call elsewhere. The prefillForm function is then never called. 

https://github.com/webcompat/webcompat.com/blob/0d260f567f7f34a938d1edfa9f4224cae2b813c0/webcompat/static/js/lib/issue-wizard-bugform.js#L351-L358

**Comment by ksy36** [comment]
`handleMessage` is only used to handle postMessage from the reporter, so it won't be triggered when we go to this url directly `http://127.0.0.1:5000/issues/new?label=browser-fenix`. postMessage is sent from desktop and fennec reporters only I think.

I think we parse GET request params and save extra_labels to session 

https://github.com/webcompat/webcompat.com/blob/956377ff3d47f335fd8b5d0ec130d677cfc7ffa1/webcompat/views.py#L264

and then retrieve it from the session on submit 
https://github.com/webcompat/webcompat.com/blob/956377ff3d47f335fd8b5d0ec130d677cfc7ffa1/webcompat/views.py#L280

I've tried to file locally on desktop and it adds correct label. I'll try on my phone in a bit

**Comment by ksy36** [comment]
Ah, realized that Dennis did some improvements in https://github.com/mozilla/webcompat-team-okrs/issues/132 and Fenix reporter now also sends a postMessage. 

This is a message I get from it at the moment:

<img width="574" alt="Screen Shot 2020-06-15 at 11 19 11 AM" src="https://user-images.githubusercontent.com/1303908/84676307-5a1b8a00-aefb-11ea-97a2-3b48748fa629.png">

extra_labels is empty and the src is "desktop_reporter". I think if we add `browser-fenix` to extra_labels, we'll get correct label at the webcompat side. Also could perhaps change "src" to be `mobile-reporter`

https://github.com/mozilla-mobile/android-components/blob/3454444a13753e7bf1cb63f7f8f8d406fb8ba2b7/components/feature/webcompat-reporter/src/main/assets/extensions/webcompat-reporter/background.js#L141-L151

This issue is related to the old version of reporter, when it used to open a page with a get param (`?label=browser-fenix`). But since the reporter has changed, it's probably no longer that important

**Comment by ksy36** [comment]
That makes me think, back to the conversation we had about functionality on webcompat.com that is not being used. Maybe we could drop support of param prefilling on the backend since it'll simplify things. I think at the moment we support 3 ways of prefilling the form, GET and POST and postMessage. And probably postMessage will be the main source of prefilling the form now that Firefox Preview has it as well. What do you think? @karlcow @miketaylr

**Comment by miketaylr** [comment]
> What do you think? @karlcow @miketaylr

I'm supportive of the idea, but I think Firefox Reality uses GET params. We could try to get that to use the Android Component version however?

(In theory GET params are nice to allow for HTTP-only interactions, but so far that's remained theoretical)

**Comment by karlcow** [comment]
This is working on my phone when I manually add the label… on staging.

https://staging.webcompat.com/issues/new?label=browser-fenix

see https://github.com/webcompat/webcompat-tests/issues/2495


So this is working. BUT if I do with firefox preview nightly: 3 dots menu -> addons -> report site issue, there is no '?label=browser-firefox' on the uri.

**Comment by miketaylr** [comment]
> BUT if I do with firefox preview nightly: 3 dots menu -> addons -> report site issue, there is no `?label=browser-firefox` on the uri.

Ah, Nightly should be using the new Android component version that @denschub landed. I guess we need to add that label back in, because there's still no way to automatically detect Fenix from Fennec on the backend?

**Comment by karlcow** [comment]
I meant above `browser-fenix`. fixed the comment.

**Comment by ksy36** [comment]
> > BUT if I do with firefox preview nightly: 3 dots menu -> addons -> report site issue, there is no `?label=browser-firefox` on the uri.
> 
> Ah, Nightly should be using the new Android component version that @denschub landed. I guess we need to add that label back in, because there's still no way to automatically detect Fenix from Fennec on the backend?

Yeah, see my comment above :)  https://github.com/webcompat/webcompat.com/issues/3314#issuecomment-644214348

**Comment by karlcow** [comment]
yeeha everything is solved! Thanks @ksy36 !!!

**Comment by denschub** [comment]
Ah, this is my fault! Happy to make sure the correct labels are set within the android-component soon.

However, just adding it to the source is likely not a good idea. The android component can be used in a lot of browsers (even Firefox Reality would be a target), so we should probably expose a product name in the component's `install` method, so this can be set per usage, not once in the component itself. :)
