### ISSUE TITLE
Remove the form building from home page

### ISSUE THREAD

**Issue by karlcow** [webcompat/webcompat.com#3319]
In the spirit of removing unnecessary call to unused functions for this context.

The home page is making a call to `get_form` which is not useful anymore.

https://github.com/webcompat/webcompat.com/blob/b3e5e1ffb58dc4cc372e4dad94eb390675a9c2d3/webcompat/views.py#L180

and communicating the data to a template which does nothing with it.
https://github.com/webcompat/webcompat.com/blob/b3e5e1ffb58dc4cc372e4dad94eb390675a9c2d3/webcompat/views.py#L187

we just need to remove these.

<img width="1434" alt="Capture d’écran 2020-05-28 à 12 16 38" src="https://user-images.githubusercontent.com/505230/83094686-32e05280-a0dd-11ea-9919-d836028a8219.png">

**Comment by karlcow** [comment]
In the past these were useful but we transitioned from a form on the homepage to a link to the issue page. so this is not needed anymore.

**Comment by miketaylr** [comment]
Oh, nice catch. 👍
