### ISSUE TITLE
Test webcompat.com on staging after refactoring

### ISSUE THREAD

**Issue by ksy36** [webcompat/webcompat.com#3333]
Now that the [refactored version of the form and webpack bundling](https://github.com/webcompat/webcompat.com/projects/9) is on staging, it would be nice to do some additional testing. Since the main chunk of work was done on the reporting page, it probably needs more attention and for the rest of the pages I think quick check would be enough.

@softvision-oana-arbuzov @cipriansv would you be able to help with testing? (since I could have missed something).

cc @miketaylr

**Comment by miketaylr** [comment]
Thanks for filing @ksy36. We're looking for *regressions* from current behavior (although new (serious) bugs are interesting!

**Comment by softvision-oana-arbuzov** [comment]
Thanks @ksy36, we will do some testing.

**Comment by softvision-oana-arbuzov** [comment]
@ksy36 and @miketaylr we've performed some exploratory testing on the site and did not find any new major/critical issues.
From our point of view, we consider it to be in good shape for release. 
Great job !

**Comment by miketaylr** [comment]
Thank you for testing! <3

**Comment by ksy36** [comment]
Thanks @softvision-oana-arbuzov and @cipriansv :)
