### ISSUE TITLE
Incorrect image displayed in "Contributors" page 

### ISSUE THREAD

**Issue by softvision-oana-arbuzov** [webcompat/webcompat.com#3344]
**URL**: https://webcompat.com/contributors

**Browser / Version**: Firefox Nightly 200614 (🦎 79.0a1-20200612094620), Chrome 83.0.4103.101, Firefox Nightly 79.0a1 (2020-06-10)
**Operating System**: Samsung Galaxy S6 Edge (Android 7.0) - 1440 x 2560 pixels (~577 ppi pixel density), Windows 10 Pro

**Steps to Reproduce**:
1. Navigate to https://webcompat.com/contributors
2. Scroll down to "Ksenia Berezina" section.
3. Observe the image.

**Expected Behavior:**
The image is of "Ksenia Berezina".

**Actual Behavior:**
The image is of "Karl Dubost".

**Notes:**
1. Screenshot attached.
![image](https://user-images.githubusercontent.com/12184325/84689380-91188c80-af49-11ea-8d1d-1e896e15670c.png)

**Watchers:**
@softvision-oana-arbuzov
@cipriansv

**Comment by miketaylr** [comment]
E_TOO_MUCH_@karlcow

**Comment by miketaylr** [comment]
(this is fixed now)
