### ISSUE TITLE
Remove /activity route and its assets.

### ISSUE THREAD

**Issue by karlcow** [webcompat/webcompat.com#3347]
`activity` route was a good intent but it's practically not that useful in the current shape and form. 
This is accessible only to the logged in individual for its own activity. 

So this issue is both a deprecation notice, and the issue that the route will be gone.

It means removing.

* [ ] Replacing `/activity/<username>`  by 410 Gone  
    https://github.com/webcompat/webcompat.com/blob/d6781a0829ffb68afd7e4286531d505f338cf2eb/webcompat/views.py#L377-L396
* [ ] Remove `/activity/me`
    https://github.com/webcompat/webcompat.com/blob/d6781a0829ffb68afd7e4286531d505f338cf2eb/webcompat/views.py#L368-L374
* [ ] Remove https://github.com/webcompat/webcompat.com/blob/d6781a0829ffb68afd7e4286531d505f338cf2eb/webcompat/templates/user-activity.html
* [ ] Remove https://github.com/webcompat/webcompat.com/tree/d6781a0829ffb68afd7e4286531d505f338cf2eb/webcompat/templates/user-activity
* [ ] Remove the functional tests https://github.com/webcompat/webcompat.com/blob/0d260f567f7f34a938d1edfa9f4224cae2b813c0/tests/functional/user-activity-auth.js and https://github.com/webcompat/webcompat.com/blob/0d260f567f7f34a938d1edfa9f4224cae2b813c0/tests/functional/user-activity-non-auth.js
* [ ] Remove the uglify code  
    https://github.com/webcompat/webcompat.com/blob/0d260f567f7f34a938d1edfa9f4224cae2b813c0/grunt-tasks/uglify.js#L27-L30
* [ ] Remove the grunt code  
    https://github.com/webcompat/webcompat.com/blob/3df0c39a1f01b935279cec1db01c10179f2341ee/grunt-tasks/concat.js#L80-L88
* [ ] Remove the webpack code  
    https://github.com/webcompat/webcompat.com/blob/d6781a0829ffb68afd7e4286531d505f338cf2eb/webpack/entries.js#L32-L37
* [ ] Remove the unit testing code  
    https://github.com/webcompat/webcompat.com/blob/ec9cb3a01f724b8947b59bb4191f9ecb98984053/tests/unit/test_rendering.py#L73-L78
* [ ] Remove the shared nav link  
    https://github.com/webcompat/webcompat.com/blob/d56cd783366d725bcf2cf560723a590faf41e08f/webcompat/templates/nav/shared-nav-links.html#L36-L38

**Comment by apsychogirl** [comment]
I would like to take this up.
