### ISSUE TITLE
"End Google Analytics" comment in wrong place

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat.com#3351]
This is a good first bug, because it does not affect functionality at all - just view source.

```
<!-- Google Analytics -->
<script src="/dist/ga.js"></script>
<script async src='https://www.google-analytics.com/analytics.js'></script>
<script nomodule src="/dist/vendor.es5.js?37c3f356637c7f63a991b6bddeefb3fe"></script>
<script nomodule src="/dist/webcompat.es5.js?5270a9fe17db823cadab89672c2d3dfa"></script>
<!-- End Google Analytics -->
<script type="module" src="/dist/vendor.js?ff6d7fd6b7a5a7bf64b9d7b6c540af79"></script>
<script type="module" src="/dist/webcompat.js?d633938f16ba8e2f9d85e2de85054f4b"></script>
```

To fix this, the comment should be moved up 2 lines just after the Google Analytics script:

https://github.com/webcompat/webcompat.com/blob/6478d111db4dfd8d66202447ff21774fcf922a0d/webcompat/templates/layout.html#L26

(an alternate fix would be to delete the comment in addition to `<!-- Google Analytics -->` lol)

**Comment by apsychogirl** [comment]
Can I take this?
