### ISSUE TITLE
constraints for reported_with are not defined

### ISSUE THREAD

**Issue by karlcow** [webcompat/webcompat.com#3359]
Right now:

`reported_with` is a free form field.

https://github.com/webcompat/webcompat.com/blob/d6781a0829ffb68afd7e4286531d505f338cf2eb/webcompat/form.py#L297

**Comment by karlcow** [comment]
Currently we do not check if the value we receive is an expected one. 

* web (default)
* desktop-reporter
* mobile-reporter
* addon-reporter-chrome
* addon-reporter-firefox
* addon-reporter-firefox-mobile
* addon-reporter-opera

@miketaylr Are there others?

**Comment by miketaylr** [comment]
There's also https://searchfox.org/mozilla-central/source/browser/fxr/content/fxrui.js#13 which expands to https://webcompat.com/issues/new?src=web-fxr

**Comment by miketaylr** [comment]
(I'll file an issue, but it would also be nice if we could somehow expose this data on our metrics server to know where the issues are coming from)

**Comment by karlcow** [comment]
@miketaylr I started to design something for #3360 and #3359 

A question about the results

These are obious:

* `{}` ➜ `web`
* `{'src': 'desktop-reporter'}` ➜ `desktop-reporter`

What about these two cases?

* `{'src': ''}` ➜ `unknown` or `web`
* `{'src': 'punkCat'}` ➜ `unknown` or `web`

Also I think I want to push the value list into an ENV variable style or file independent of the release for flexibility, as we probably should for deny list of domain blocking. aka flexibility and independence of code editing.

**Comment by miketaylr** [comment]
I think `unknown` is a good solution for the weird stuff. In theory we can investigate it, and fix whatever the issue is, rather than skew `web` results.
