### ISSUE TITLE
Some issues don't get a milestone 

### ISSUE THREAD

**Issue by ksy36** [webcompat/webcompat.com#3361]
There are about 15 issues that don't have a milestone right now:
https://github.com/webcompat/web-bugs/issues?q=is%3Aopen+is%3Aissue+no%3Amilestone

In case the above link  doesn't load here is a screenshot:

![no milestone](https://user-images.githubusercontent.com/1303908/85590923-d3f5f680-b612-11ea-94f1-156832518bca.png)

We need to investigate why the needstriage milestone is not added.

As an example, this issue was copied from the private repo to public and no milestone was added:
https://github.com/webcompat/web-bugs/issues/52418

**Comment by miketaylr** [comment]
This one seems like the webhook just did not run (no browser labels, for example): https://github.com/webcompat/web-bugs/issues/47575

**Comment by miketaylr** [comment]
We had 6 of these reports on January 2, 2020 -- but there's no recorded webhook incidents according to GitHub on that day: https://www.githubstatus.com/uptime/4230lsnqdsld?page=2

![Screen Shot 2020-06-24 at 11 29 12 AM](https://user-images.githubusercontent.com/67283/85594876-f46f8200-b60d-11ea-89f9-9e253fd01739.png)

**Comment by karlcow** [comment]
the usernames looks very spammy to me.

**Comment by karlcow** [comment]
So this is happening time to time. I have fixed it in the past manually. Note that the milestone is done through webhooks it means that there's an HTTP request negotiation and so it's not guarantee to work 100% of the time, even if there is no webhook incident. A long HTTP requests, an international routing issue, etc etc. and the HTTP request is dropped and pooof the milestone is lost. 

This is another way to set a milestone.
https://help.github.com/en/github/managing-your-work-on-github/about-automation-for-issues-and-pull-requests-with-query-parameters#supported-query-parameters

**Comment by miketaylr** [comment]
Cool, didn't know about `https://github.com/octo-org/octo-repo/issues/new?milestone=blah`. 

In the meantime, I guess a manual check every few weeks or so to catch the edge case bugs isn't the end of the world (since it seems pretty rare).
