### ISSUE TITLE
[A11Y] URL section becomes truncated after reaching "Report" buttons and using "Tab" key

### ISSUE THREAD

**Issue by softvision-oana-arbuzov** [webcompat/webcompat.com#3420]
**Browser / Version**: Firefox Nightly 81.0a1 (2020-07-27), Chrome 84.0.4147.89 
**Operating System**: Windows 10 Pro

**Steps to Reproduce**:
1. Navigate to https://webcompat.com/issues/new
2. Fill in all required data from the form until reaching "Report anonymously" button. 
3. Use one "Tab" key.
4. Move to the top of the report ("Page up" button).
5. Observe URL section.

**Expected Behavior:**
The section is fully visible. 

**Actual Behavior:**
The section is truncated on the top side. 

**Notes:**
1. Screenshot attached.
![image](https://user-images.githubusercontent.com/12184325/88669837-11a3de80-d0ed-11ea-809a-f6704e3f8593.png)
2. Workaround: Scrolling does not help, but refreshing the page works.

**Watchers:**
@softvision-oana-arbuzov
@cipriansv

**Comment by miketaylr** [comment]
Nice find. :)

The reason this is happening is related to the hidden github username field:

![Screen Shot 2020-08-19 at 2 25 29 PM](https://user-images.githubusercontent.com/67283/90680828-12312000-e228-11ea-8c80-524da3f66f15.png)

**Comment by miketaylr** [comment]
This will get fixed by https://github.com/webcompat/webcompat.com/issues/3458, so let's close it.

**Comment by softvision-oana-arbuzov** [comment]
I can confirm this is fixed.
![image](https://user-images.githubusercontent.com/12184325/93602017-b1ce0380-f9ca-11ea-9829-554cacfa759d.png)

**Tested with:**
Browser / Version: Firefox Nightly 82.0a1 (2020-09-17), Chrome 85.0.4183.102
Operating System: Windows 10 Pro
