### ISSUE TITLE
Speed up pytest command

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat.com#3425]
I'm lazy, so I usually invoke pytest via `pytest` from the project root. This can take forever, likely due to it scanning all directories for tests.

I did some digging and found:

https://docs.pytest.org/en/latest/reference.html#confval-testpaths

So if I do `pytest -o "testpaths=tests"`, the tests start immediately. 

@karlcow do you think we should add a `pytest.ini` to the project root to specify this? Or do you have some other tricks you use?

**Comment by karlcow** [comment]
I most of the time, type `pytest tests/unit/`.

Yeah let's do a [`pytest.ini`](https://docs.pytest.org/en/latest/customize.html#config-file-formats)
