### ISSUE TITLE
Simplify test_webhook.py tests

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat.com#3436]
Right now the mocking is kind of gnarly in some places, and could be greatly simplified.

(Mostly the result of me learning by doing...)

**Comment by karlcow** [comment]
I have the feeling that most of the "gnarly" could be addressed right away without much modifications

see the comments in https://github.com/webcompat/webcompat.com/pull/3415#pullrequestreview-460402924

**Comment by miketaylr** [comment]
Yeah, i think this can be closed now.
