### ISSUE TITLE
Refactor parse_link_header

### ISSUE THREAD

**Issue by karlcow** [webcompat/webcompat.com#3447]
So we currently have `parse_link_header`

https://github.com/webcompat/webcompat.com/blob/b2b68c19881ea98c484a2c66e67db886ca6b02c3/webcompat/helpers.py#L342-L362

which is used at different places in the code, which returns a dictionary of links.

And what did I discovered today… cough cough… 🤦 

```python
>>> links = '<https://api.github.com/repositories/17914657/issues/1470/comments?page=2>; rel="next", <https://api.github.com/repositories/17914657/issues/1470/comments?page=2>; rel="last"' 
>>> import requests
>>> requests.utils.parse_header_links(links)
[{'url': 'https://api.github.com/repositories/17914657/issues/1470/comments?page=2', 'rel': 'next'}, {'url': 'https://api.github.com/repositories/17914657/issues/1470/comments?page=2', 'rel': 'last'}]
```

`parse_header_links` was added in 2012

That means removing also the test
https://github.com/webcompat/webcompat.com/blob/b2b68c19881ea98c484a2c66e67db886ca6b02c3/tests/unit/test_helpers.py#L146-L150

* [x] replace `parse_link_header` by `utils.parse_header_links`
* [x] remove `parse_link_header`
* [x] remove `test_parse_http_link_headers`
* [x] make sure all the tests are passing

**Comment by miketaylr** [comment]
Heh, nice find. :)

**Comment by apsychogirl** [comment]
Can I work on this?

**Comment by karlcow** [comment]
@apsychogirl yes.

**Comment by apsychogirl** [comment]
@karlcow I didn't understand if I need to replace the name of the function or remove it. In the issue, it is mentioned as 

>     * [ ]  replace `parse_link_header` by `utils.parse_header_links`
> 
>     * [ ]  remove `parse_link_header`

**Comment by karlcow** [comment]
We want to use `requests.utils.parse_header_links` instead of the homemade `parse_link_header`. It would mean to 1. replace by the requests function and then to remove the homemade one.

**Comment by apsychogirl** [comment]
There are some errors after I replaced `parse_link_header` by `utils.parse_header_links`
`(env)  ✘ apsychogirl@dell  ~/webcompat.com   3447/1 ●  pytest
========================================================= test session starts =========================================================
platform linux -- Python 3.8.2, pytest-5.4.3, py-1.9.0, pluggy-0.13.1
rootdir: /home/apsychogirl/webcompat.com, inifile: pytest.ini, testpaths: tests/unit
plugins: mock-3.2.0
collected 187 items                                                                                                                   

tests/unit/test_api_helpers.py ..                                                                                               [  1%]
tests/unit/test_api_urls.py F..........                                                                                         [  6%]
tests/unit/test_config.py ..                                                                                                    [  8%]
tests/unit/test_console_logs.py .....                                                                                           [ 10%]
tests/unit/test_form.py .....................                                                                                   [ 21%]
tests/unit/test_helpers.py .........................FFF                                                                         [ 36%]
tests/unit/test_http_caching.py ...                                                                                             [ 38%]
tests/unit/test_issues.py .........                                                                                             [ 43%]
tests/unit/test_rendering.py .....                                                                                              [ 45%]
tests/unit/test_template.py ............                                                                                        [ 52%]
tests/unit/test_tools_archive.py ............s.                                                                                 [ 59%]
tests/unit/test_tools_changelog.py ..                                                                                           [ 60%]
tests/unit/test_topsites.py ...                                                                                                 [ 62%]
tests/unit/test_uploads.py ...                                                                                                  [ 64%]
tests/unit/test_urls.py ................................                                                                        [ 81%]
tests/unit/test_webhook.py ....................                                                                                 [ 91%]
tests/unit/test_webhook_model.py ...............                                                                                [100%]

============================================================== FAILURES ===============================================================
___________________________________________ TestAPIURLs.test_api_comments_link_header_auth ____________________________________________

self = <unit.test_api_urls.TestAPIURLs testMethod=test_api_comments_link_header_auth>

    def test_api_comments_link_header_auth(self):
        """Pagination in comments Link response header.
    
        API access to comments greater than 30 returns HTTP Link
        in the response header.
        """
        with patch('webcompat.helpers.proxy_request') as github_data:
            # Create mock data. One api_response for each call.
            github_data.side_effect = [
                mock_api_response({
                    'status_code': 200,
                    'content': '[]',
                    'headers': {
                        'Link': '<https://api.github.com/repositories/17839063/issues/398/comments?page=2>; rel="next", <https://api.github.com/repositories/17839063/issues/398/comments?page=4>; rel="last"',  # noqa
                    },
                }),
                mock_api_response({'status_code': 200, 'content': '[]'})
            ]
>           rv = self.app.get('/api/issues/398/comments', environ_base=headers)

tests/unit/test_api_urls.py:123: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
env/lib/python3.8/site-packages/werkzeug/test.py:1006: in get
    return self.open(*args, **kw)
env/lib/python3.8/site-packages/flask/testing.py:222: in open
    return Client.open(
env/lib/python3.8/site-packages/werkzeug/test.py:970: in open
    response = self.run_wsgi_app(environ.copy(), buffered=buffered)
env/lib/python3.8/site-packages/werkzeug/test.py:861: in run_wsgi_app
    rv = run_wsgi_app(self.application, environ, buffered=buffered)
env/lib/python3.8/site-packages/werkzeug/test.py:1096: in run_wsgi_app
    app_rv = app(environ, start_response)
env/lib/python3.8/site-packages/flask/app.py:2464: in __call__
    return self.wsgi_app(environ, start_response)
env/lib/python3.8/site-packages/flask/app.py:2450: in wsgi_app
    response = self.handle_exception(e)
env/lib/python3.8/site-packages/flask/app.py:1867: in handle_exception
    reraise(exc_type, exc_value, tb)
env/lib/python3.8/site-packages/flask/_compat.py:39: in reraise
    raise value
env/lib/python3.8/site-packages/flask/app.py:2447: in wsgi_app
    response = self.full_dispatch_request()
env/lib/python3.8/site-packages/flask/app.py:1952: in full_dispatch_request
    rv = self.handle_user_exception(e)
env/lib/python3.8/site-packages/flask/app.py:1821: in handle_user_exception
    reraise(exc_type, exc_value, tb)
env/lib/python3.8/site-packages/flask/_compat.py:39: in reraise
    raise value
env/lib/python3.8/site-packages/flask/app.py:1950: in full_dispatch_request
    rv = self.dispatch_request()
env/lib/python3.8/site-packages/flask/app.py:1936: in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
webcompat/api/endpoints.py:190: in proxy_comments
    comments_data = api_request('get', path, params=params,
webcompat/helpers.py:414: in wrapped_func
    return func(*args, **kwargs)
webcompat/helpers.py:478: in api_request
    get_response_headers(resource))
webcompat/helpers.py:205: in get_response_headers
    new_headers['link'] = rewrite_and_sanitize_link(headers.get('link'))
webcompat/helpers.py:339: in rewrite_and_sanitize_link
    return rewrite_links(sanitize_link(link_header))
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

link_header = '<https://api.github.com/repositories/17839063/issues/398/comments?page=2>; rel="next", <https://api.github.com/repositories/17839063/issues/398/comments?page=4>; rel="last"'

    def sanitize_link(link_header):
        """Remove any oauth tokens from the Link header from GitHub.
    
        see Also rewrite_links.
        """
        header_link_data = requests.utils.parse_header_links(link_header)
        for data in header_link_data:
>           data['link'] = remove_oauth(data['link'])
E           KeyError: 'link'

webcompat/helpers.py:318: KeyError
_____________________________________________ TestHelpers.test_rewrite_and_sanitize_link ______________________________________________

self = <unit.test_helpers.TestHelpers testMethod=test_rewrite_and_sanitize_link>

    def test_rewrite_and_sanitize_link(self):
        """Rewrite and Sanitize Links test."""
        self.assertNotIn('access_token=',
>                        rewrite_and_sanitize_link(ACCESS_TOKEN_LINK))

tests/unit/test_helpers.py:99: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
webcompat/helpers.py:339: in rewrite_and_sanitize_link
    return rewrite_links(sanitize_link(link_header))
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

link_header = '<https://api.github.com/repositories/17839063/issues?per_page=50&page=3&access_token=12345>; rel="next", <https://api...; rel="first", <https://api.github.com/repositories/17839063/issues?per_page=50&page=1&access_token=12345>; rel="prev"'

    def sanitize_link(link_header):
        """Remove any oauth tokens from the Link header from GitHub.
    
        see Also rewrite_links.
        """
        header_link_data = requests.utils.parse_header_links(link_header)
        for data in header_link_data:
>           data['link'] = remove_oauth(data['link'])
E           KeyError: 'link'

webcompat/helpers.py:318: KeyError
____________________________________________________ TestHelpers.test_rewrite_link ____________________________________________________

self = <unit.test_helpers.TestHelpers testMethod=test_rewrite_link>

    def test_rewrite_link(self):
        """Test we're correctly rewriting the passed in link."""
>       self.assertEqual(rewrite_links(GITHUB_ISSUES_LINK_HEADER),
                         REWRITTEN_ISSUES_LINK_HEADER)

tests/unit/test_helpers.py:85: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

link_header = '<https://api.github.com/repositories/17839063/issues?per_page=50&page=3>; rel="next", <https://api.github.com/reposit...per_page=50&page=1>; rel="first", <https://api.github.com/repositories/17839063/issues?per_page=50&page=1>; rel="prev"'

    def rewrite_links(link_header):
        """Rewrite Link header Github API endpoints to our own.
    
        <https://api.github.com/repositories/17839063/iss...&page=2>; rel="next",
        <https://api.github.com/repositories/17839063/iss...&page=4>; rel="last"
    
        is transformed into
    
        </api/issues?per_page=50&page=2>; rel="next",
        </api/issues?per_page=50&page=4>; rel="last" etc.
        """
        header_link_data = requests.utils.parse_header_links(link_header)
        for data in header_link_data:
>           uri = data['link']
E           KeyError: 'link'

webcompat/helpers.py:296: KeyError
___________________________________________________ TestHelpers.test_sanitize_link ____________________________________________________

self = <unit.test_helpers.TestHelpers testMethod=test_sanitize_link>

    def test_sanitize_link(self):
        """Test that we're removing access_token parameters."""
>       self.assertNotIn('access_token=', sanitize_link(ACCESS_TOKEN_LINK))

tests/unit/test_helpers.py:94: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

link_header = '<https://api.github.com/repositories/17839063/issues?per_page=50&page=3&access_token=12345>; rel="next", <https://api...; rel="first", <https://api.github.com/repositories/17839063/issues?per_page=50&page=1&access_token=12345>; rel="prev"'

    def sanitize_link(link_header):
        """Remove any oauth tokens from the Link header from GitHub.
    
        see Also rewrite_links.
        """
        header_link_data = requests.utils.parse_header_links(link_header)
        for data in header_link_data:
>           data['link'] = remove_oauth(data['link'])
E           KeyError: 'link'

webcompat/helpers.py:318: KeyError
======================================================= short test summary info =======================================================
FAILED tests/unit/test_api_urls.py::TestAPIURLs::test_api_comments_link_header_auth - KeyError: 'link'
FAILED tests/unit/test_helpers.py::TestHelpers::test_rewrite_and_sanitize_link - KeyError: 'link'
FAILED tests/unit/test_helpers.py::TestHelpers::test_rewrite_link - KeyError: 'link'
FAILED tests/unit/test_helpers.py::TestHelpers::test_sanitize_link - KeyError: 'link'
============================================== 4 failed, 182 passed, 1 skipped in 2.18s ===============================================
`

**Comment by apsychogirl** [comment]
There are some errors after I replaced `parse_link_header` by `utils.parse_header_links`
```bash
(env)  ✘ apsychogirl@dell  ~/webcompat.com   3447/1 ●  pytest
========================================================= test session starts =========================================================
platform linux -- Python 3.8.2, pytest-5.4.3, py-1.9.0, pluggy-0.13.1
rootdir: /home/apsychogirl/webcompat.com, inifile: pytest.ini, testpaths: tests/unit
plugins: mock-3.2.0
collected 187 items                                                                                                                   

tests/unit/test_api_helpers.py ..                                                                                               [  1%]
tests/unit/test_api_urls.py F..........                                                                                         [  6%]
tests/unit/test_config.py ..                                                                                                    [  8%]
tests/unit/test_console_logs.py .....                                                                                           [ 10%]
tests/unit/test_form.py .....................                                                                                   [ 21%]
tests/unit/test_helpers.py .........................FFF                                                                         [ 36%]
tests/unit/test_http_caching.py ...                                                                                             [ 38%]
tests/unit/test_issues.py .........                                                                                             [ 43%]
tests/unit/test_rendering.py .....                                                                                              [ 45%]
tests/unit/test_template.py ............                                                                                        [ 52%]
tests/unit/test_tools_archive.py ............s.                                                                                 [ 59%]
tests/unit/test_tools_changelog.py ..                                                                                           [ 60%]
tests/unit/test_topsites.py ...                                                                                                 [ 62%]
tests/unit/test_uploads.py ...                                                                                                  [ 64%]
tests/unit/test_urls.py ................................                                                                        [ 81%]
tests/unit/test_webhook.py ....................                                                                                 [ 91%]
tests/unit/test_webhook_model.py ...............                                                                                [100%]

============================================================== FAILURES ===============================================================
___________________________________________ TestAPIURLs.test_api_comments_link_header_auth ____________________________________________

self = <unit.test_api_urls.TestAPIURLs testMethod=test_api_comments_link_header_auth>

    def test_api_comments_link_header_auth(self):
        """Pagination in comments Link response header.
    
        API access to comments greater than 30 returns HTTP Link
        in the response header.
        """
        with patch('webcompat.helpers.proxy_request') as github_data:
            # Create mock data. One api_response for each call.
            github_data.side_effect = [
                mock_api_response({
                    'status_code': 200,
                    'content': '[]',
                    'headers': {
                        'Link': '<https://api.github.com/repositories/17839063/issues/398/comments?page=2>; rel="next", <https://api.github.com/repositories/17839063/issues/398/comments?page=4>; rel="last"',  # noqa
                    },
                }),
                mock_api_response({'status_code': 200, 'content': '[]'})
            ]
>           rv = self.app.get('/api/issues/398/comments', environ_base=headers)

tests/unit/test_api_urls.py:123: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
env/lib/python3.8/site-packages/werkzeug/test.py:1006: in get
    return self.open(*args, **kw)
env/lib/python3.8/site-packages/flask/testing.py:222: in open
    return Client.open(
env/lib/python3.8/site-packages/werkzeug/test.py:970: in open
    response = self.run_wsgi_app(environ.copy(), buffered=buffered)
env/lib/python3.8/site-packages/werkzeug/test.py:861: in run_wsgi_app
    rv = run_wsgi_app(self.application, environ, buffered=buffered)
env/lib/python3.8/site-packages/werkzeug/test.py:1096: in run_wsgi_app
    app_rv = app(environ, start_response)
env/lib/python3.8/site-packages/flask/app.py:2464: in __call__
    return self.wsgi_app(environ, start_response)
env/lib/python3.8/site-packages/flask/app.py:2450: in wsgi_app
    response = self.handle_exception(e)
env/lib/python3.8/site-packages/flask/app.py:1867: in handle_exception
    reraise(exc_type, exc_value, tb)
env/lib/python3.8/site-packages/flask/_compat.py:39: in reraise
    raise value
env/lib/python3.8/site-packages/flask/app.py:2447: in wsgi_app
    response = self.full_dispatch_request()
env/lib/python3.8/site-packages/flask/app.py:1952: in full_dispatch_request
    rv = self.handle_user_exception(e)
env/lib/python3.8/site-packages/flask/app.py:1821: in handle_user_exception
    reraise(exc_type, exc_value, tb)
env/lib/python3.8/site-packages/flask/_compat.py:39: in reraise
    raise value
env/lib/python3.8/site-packages/flask/app.py:1950: in full_dispatch_request
    rv = self.dispatch_request()
env/lib/python3.8/site-packages/flask/app.py:1936: in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
webcompat/api/endpoints.py:190: in proxy_comments
    comments_data = api_request('get', path, params=params,
webcompat/helpers.py:414: in wrapped_func
    return func(*args, **kwargs)
webcompat/helpers.py:478: in api_request
    get_response_headers(resource))
webcompat/helpers.py:205: in get_response_headers
    new_headers['link'] = rewrite_and_sanitize_link(headers.get('link'))
webcompat/helpers.py:339: in rewrite_and_sanitize_link
    return rewrite_links(sanitize_link(link_header))
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

link_header = '<https://api.github.com/repositories/17839063/issues/398/comments?page=2>; rel="next", <https://api.github.com/repositories/17839063/issues/398/comments?page=4>; rel="last"'

    def sanitize_link(link_header):
        """Remove any oauth tokens from the Link header from GitHub.
    
        see Also rewrite_links.
        """
        header_link_data = requests.utils.parse_header_links(link_header)
        for data in header_link_data:
>           data['link'] = remove_oauth(data['link'])
E           KeyError: 'link'

webcompat/helpers.py:318: KeyError
_____________________________________________ TestHelpers.test_rewrite_and_sanitize_link ______________________________________________

self = <unit.test_helpers.TestHelpers testMethod=test_rewrite_and_sanitize_link>

    def test_rewrite_and_sanitize_link(self):
        """Rewrite and Sanitize Links test."""
        self.assertNotIn('access_token=',
>                        rewrite_and_sanitize_link(ACCESS_TOKEN_LINK))

tests/unit/test_helpers.py:99: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
webcompat/helpers.py:339: in rewrite_and_sanitize_link
    return rewrite_links(sanitize_link(link_header))
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

link_header = '<https://api.github.com/repositories/17839063/issues?per_page=50&page=3&access_token=12345>; rel="next", <https://api...; rel="first", <https://api.github.com/repositories/17839063/issues?per_page=50&page=1&access_token=12345>; rel="prev"'

    def sanitize_link(link_header):
        """Remove any oauth tokens from the Link header from GitHub.
    
        see Also rewrite_links.
        """
        header_link_data = requests.utils.parse_header_links(link_header)
        for data in header_link_data:
>           data['link'] = remove_oauth(data['link'])
E           KeyError: 'link'

webcompat/helpers.py:318: KeyError
____________________________________________________ TestHelpers.test_rewrite_link ____________________________________________________

self = <unit.test_helpers.TestHelpers testMethod=test_rewrite_link>

    def test_rewrite_link(self):
        """Test we're correctly rewriting the passed in link."""
>       self.assertEqual(rewrite_links(GITHUB_ISSUES_LINK_HEADER),
                         REWRITTEN_ISSUES_LINK_HEADER)

tests/unit/test_helpers.py:85: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

link_header = '<https://api.github.com/repositories/17839063/issues?per_page=50&page=3>; rel="next", <https://api.github.com/reposit...per_page=50&page=1>; rel="first", <https://api.github.com/repositories/17839063/issues?per_page=50&page=1>; rel="prev"'

    def rewrite_links(link_header):
        """Rewrite Link header Github API endpoints to our own.
    
        <https://api.github.com/repositories/17839063/iss...&page=2>; rel="next",
        <https://api.github.com/repositories/17839063/iss...&page=4>; rel="last"
    
        is transformed into
    
        </api/issues?per_page=50&page=2>; rel="next",
        </api/issues?per_page=50&page=4>; rel="last" etc.
        """
        header_link_data = requests.utils.parse_header_links(link_header)
        for data in header_link_data:
>           uri = data['link']
E           KeyError: 'link'

webcompat/helpers.py:296: KeyError
___________________________________________________ TestHelpers.test_sanitize_link ____________________________________________________

self = <unit.test_helpers.TestHelpers testMethod=test_sanitize_link>

    def test_sanitize_link(self):
        """Test that we're removing access_token parameters."""
>       self.assertNotIn('access_token=', sanitize_link(ACCESS_TOKEN_LINK))

tests/unit/test_helpers.py:94: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

link_header = '<https://api.github.com/repositories/17839063/issues?per_page=50&page=3&access_token=12345>; rel="next", <https://api...; rel="first", <https://api.github.com/repositories/17839063/issues?per_page=50&page=1&access_token=12345>; rel="prev"'

    def sanitize_link(link_header):
        """Remove any oauth tokens from the Link header from GitHub.
    
        see Also rewrite_links.
        """
        header_link_data = requests.utils.parse_header_links(link_header)
        for data in header_link_data:
>           data['link'] = remove_oauth(data['link'])
E           KeyError: 'link'

webcompat/helpers.py:318: KeyError
======================================================= short test summary info =======================================================
FAILED tests/unit/test_api_urls.py::TestAPIURLs::test_api_comments_link_header_auth - KeyError: 'link'
FAILED tests/unit/test_helpers.py::TestHelpers::test_rewrite_and_sanitize_link - KeyError: 'link'
FAILED tests/unit/test_helpers.py::TestHelpers::test_rewrite_link - KeyError: 'link'
FAILED tests/unit/test_helpers.py::TestHelpers::test_sanitize_link - KeyError: 'link'
============================================== 4 failed, 182 passed, 1 skipped in 2.18s ===============================================
(env)  ✘ apsychogirl@dell  ~/webcompat.com   3447/1 ●  


```

**Comment by karlcow** [comment]
@apsychogirl Do you still plan to work on this? Or do you prefer to free the issue for someone else?

**Comment by apsychogirl** [comment]
@karlcow , sorry I'm occupied at the moment and won't be able to work on it.

**Comment by karlcow** [comment]
no issue! Thanks for the quick reply.
