### ISSUE TITLE
Refactor 3 prepare_foo_issue methods into one

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat.com#3463]
There's a lot of repeated code here, so it's probably possible to just do `prepare_issue('invalid', title)`, etc.

https://github.com/webcompat/webcompat.com/blob/dc7f9002e64faa1e8eaedc356e4d63e362d65cc4/webcompat/webhooks/helpers.py#L212-L268

**Comment by apsychogirl** [comment]
Can I take this up?

**Comment by karlcow** [comment]
@apsychogirl you may.

Note that there will be a bit of work to do around testing too.

**Comment by karlcow** [comment]
@apsychogirl I would recommend you take it once you are done with #3447 if someone else wants to tackle this one before. Thanks!

**Comment by apsychogirl** [comment]
@karlcow Sure thing!

**Comment by miketaylr** [comment]
Oops, I forgot that I filed this issue and unintentionally fixed it in https://github.com/webcompat/webcompat.com/commit/180670859258436d80a59780073f45605d82466b. Sorry to steal potential future work @apsychogirl :))
