### ISSUE TITLE
List of labels is fetched from GitHubs API instead of the local list, causing pagination issues

### ISSUE THREAD

**Issue by denschub** [webcompat/webcompat.com#3485]
While setting needsinfo labels via GitHub and someone else editing the issue on webcompat.com, I had a small fight with @webcompat-bot two days ago, where the bot removed `status-needsinfo-ksy36` and `status-needsinfo-wisniewskit`. Trying to set the labels on webcompat.com, I noticed that most `needsinfo-*` labels are actually missing on webcompat.com:

![Screenshot 2020-09-21 at 15 51 31](https://user-images.githubusercontent.com/344777/93775158-5eee8900-fc22-11ea-96f0-448f09e9af34.png)

This is because the frontend pulls the labels from GitHub's API, without being aware that pagination exists. We currently have 261 labels in the web-bugs repo, so that means 161 labels are unknown by the webcompat.com frontend. If one missing label was previously set, opening and closing the labels popup causes those labels to be removed, since the frontend isn't ware of them.

In https://github.com/webcompat/webcompat.com/pull/3171, @laghee created a cronjob that pulls a list of labels from GitHub and stores them in the file system. However, I don't think this data is used anywhere yet. It would probably wise to serve the locally cached json as source for the labels, and only fallback to the API if we have no cached copy yet.

**Comment by laghee** [comment]
You're right, @denschub -- I was about to start addressing this in #3172 after All Hands, but I lost track of it when all the 💩 started to hit the ... well, you know. I will put it on my new to-do list. ![Alt Text](https://media.giphy.com/media/YR6uzVNysDkM8/source.gif)

**Comment by denschub** [comment]
Oh, my search didn't even find your issue. Sorry! :)

Let's just go ahead and close this one as a duplicate of #3172! No reason to have two issues opened for the same thing.
