### ISSUE TITLE
Make contributors page more responsive!

### ISSUE THREAD

**Issue by calexity** [webcompat/webcompat.com#349]
The follow-up story to https://github.com/webcompat/webcompat.com/issues/169#issuecomment-62086954

Make the All Issues page better on all devices from small to large.

Here's a couple ideas.  I wonder how frustrating it might get to have the sort and filter tools load on the top if you are paging back and forth.  Is it possible to stay at the scroll point and load new issues?

![smallish view](https://cloud.githubusercontent.com/assets/1103366/4949648/360fa714-664e-11e4-9d99-5ba14fbdbb49.png)

-------------

![medium view](https://cloud.githubusercontent.com/assets/1103366/4949650/399f08f2-664e-11e4-9728-8cc3080240d8.png)

**Comment by miketaylr** [comment]
There's a lot of good ideas in here, but we think we want to move towards something that @calexity proposed in https://github.com/webcompat/webcompat.com/issues/510#issuecomment-69483924. So let's close this one and pursue the work there. :earth_africa:
