### ISSUE TITLE
A milestone is missing or has been added: ['accepted']

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat.com#3490]
I just did a clean environment setup and get the following message when I boot up:

`A milestone is missing or has been added: ['accepted']`

That comes from:
https://github.com/webcompat/webcompat.com/blob/981e14682a17caba9d3b67f21385fec50c2b7810/config/__init__.py#L30

And indeed, webcompat-tests has an unexpected milestone: https://github.com/webcompat/webcompat-tests/milestones

@karlcow this is pretty old (a few months), but since it's on your issue want to delete it? (maybe you have more context -- one thought i had was it was a misconfigured webhook test related to issue moderation?)

**Comment by karlcow** [comment]
huh. Interesting. When did we add this? in July. 

So ok. It has been removed. :) thanks for the ping. ❤️
