### ISSUE TITLE
More mike to remove

### ISSUE THREAD

**Issue by karlcow** [webcompat/webcompat.com#3494]
As a followup to #3483
@denschub found another trace of @miketaylr in the code.
https://github.com/webcompat/webcompat.com/blob/f0020035e094e0d7ff206db64cab087ab0f7981d/config/environment.py#L107-L114

**Comment by miketaylr** [comment]
This still seems pretty good for abuse:

![image](https://user-images.githubusercontent.com/67283/95922676-6b758580-0d79-11eb-883c-f33839001ecb.png)

**Comment by karlcow** [comment]
@miketaylr perfect! ;)

**Comment by soniasingla** [comment]
@karlcow with whom to replace here? :) I will raise PR for this !

**Comment by karlcow** [comment]
@soniasingla Use `kdubost@mozilla.com` for now. I'll try to get a more generic email for the future.

**Comment by karlcow** [comment]
let's change this I just requested an alias `webcompat@mozilla.com`.
