### ISSUE TITLE
Upgrade Pillow to 8.0.0? (for Python 3.9.0)

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat.com#3518]
If you have Python 3.9 and try to install requirements(-dev).txt, Pillow explodes.

@karlcow told me that 8.0.0 should work, and it solved the issue for me locally. Maybe a good idea to upgrade for everyone?

**Comment by karlcow** [comment]
so right now there is on the server 

```
karl@staging-server-webcompat:~$ python3 -V
Python 3.8.5
```

but we can probably upgrade on the server too. 
Let's first try to see if Pillow 8.0 is working with 3.8.5
At a first step we can upgrade Pillow, then Python

**Comment by karlcow** [comment]
@miketaylr I'm upgrading in #3533

**Comment by miketaylr** [comment]
Perfect, thanks @karlcow
