### ISSUE TITLE
Determine what avenues people are using to report bugs

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat.com#355]
It would be nice to know if people are reportings bugs from the web, our add-ons, or the Fennec "Report Site Issue". It may help us to know where to focus our energy.

Note I didn't use the word "track". :p We just want to know which door people came through, and nothing else.

Karl had a cool idea on how to track issues being reported from addons https://github.com/webcompat/webcompat.com/issues/317#issuecomment-62077881

**Comment by calexity** [comment]
@miketaylr @karlcow Did you guys discuss this in Whistler as part of the A/B testing discussion? It looks like Google Analytics is hooked up. Are you guys reviewing those analytics on a regular basis? If not, we should consider reviewing them to see where people are coming from and where they drop off.

**Comment by karlcow** [comment]
ping @miketaylr

**Comment by miketaylr** [comment]
Funnily enough, @adamopenweb expressed interest in doing some research in this area today.

But no, we're not really looking at analytics right now, or bounce metrics or stuff like that. Definitely looks of room for improvement, and an area worthy of study.

**Comment by miketaylr** [comment]
I thought of a way we can do this...

@karlcow recommended we send an `x-reported-with: Blah` header from the add-on, which is doable. We could then in form.py check for its presence and do a few things:

1) leave a "hidden" github comment `<!-- @reported-with: Blah -->`
2) modify the "reported from webcompat.com with <3" comment to be something like "reported from the webcompat.com reporter with <3"
3) track this in issues DB

1 and 2 are the easiest/fastest and mean we can use GitHub search to track this for now. 3 is a good option, but issues db is under development by @deepthivenkat.

So I think maybe we do either 1 or 2, then move towards 3 at some point.

**Comment by deepthivenkat** [comment]
I can speed up my development for 'extracting data dump from GitHub' and
complete it by weekend - if that helps.

**Comment by deepthivenkat** [comment]
Or I can add an entry to issues.db named 'report from' and then proceed
with the data dump issue

**Comment by miketaylr** [comment]
@deepthivenkat nah, no need to rush. I think I can get 1 or 2 done in the next day or so (given infinite energy and no sleep!). 

> I can add an entry to issues.db named 'report from' and then proceed with the data dump issue

I think this is a good option. 👍

**Comment by deepthivenkat** [comment]
Okay! I will add the new entry soon

**Comment by miketaylr** [comment]
> 1) leave a "hidden" github comment 

The alternative is to use a GitHub label and make sure the webcompat UI doesn't expose it (it shouldn't).

**Comment by miketaylr** [comment]
uhhhhhhhh

**Comment by miketaylr** [comment]
Crap. @karlcow I forgot to make a branch and just pushed this to master.

I can revert, or maybe you can just comment on https://github.com/webcompat/webcompat.com/compare/499614e506ee1f4fcb2054e7152cdb673d8801d9...master ? 😢

**Comment by miketaylr** [comment]
(will not deploy, obviously)

**Comment by miketaylr** [comment]
https://github.com/webcompat/webcompat-tests/issues/461 is an issue I reported locally after these changes (you can see the "metadata" if you click edit).

**Comment by karlcow** [comment]
> Crap. @karlcow I forgot to make a branch and just pushed this to master.

💊 hehe.

**Comment by karlcow** [comment]
not really important but just for info.
https://github.com/webcompat/webcompat.com/compare/499614e506ee1f4fcb2054e7152cdb673d8801d9...master#diff-f1975977b06efb529b8c60f23a7bc4eeR113

```python
for md in metadata:
    result += wrap_metadata(md)
```

can be done with 

```python
>>> metadata
[('beautiful', 'stars'), ('foo', 'bar')]
>>> ''.join([wrap_metadata(md) for md in metadata])
u'<!-- @beautiful: stars -->\n<!-- @foo: bar -->\n'
```

Everything looks fine. Though I remember a github and HTML comments and markdown issue in the past. Need to check that.

**Comment by karlcow** [comment]
On https://github.com/webcompat/webcompat.com/issues/355#issuecomment-250584110 @miketaylr the two issues looks fine in GitHub. What about rendering on webcompat in localhost?

If everything is fine. r+ and deploy.

**Comment by miketaylr** [comment]
> On #355 (comment) @miketaylr the two issues looks fine in GitHub. What about rendering on webcompat in localhost?

Will check on localhost to make double check before deploying.

> >>> ''.join([wrap_metadata(md) for md in metadata])

Awesome.

**Comment by miketaylr** [comment]
Confirming we're not leaking comments w/ this change:

<img width="871" alt="screen shot 2016-09-30 at 4 31 18 pm" src="https://cloud.githubusercontent.com/assets/67283/19007593/63613cf0-872b-11e6-8e97-e0bbb2b5a220.png">

**Comment by miketaylr** [comment]
Let's close and deploy.
