### ISSUE TITLE
Adding Contributors: Raul Bucata

### ISSUE THREAD

**Issue by softvision-oana-arbuzov** [webcompat/webcompat.com#3555]
@softvision-raul-bucata would you like to be on this page? https://webcompat.com/contributors

Could you share with us the same type of details that other people have sent? 
Don't forget a picture.

Note: If anyone wants to jump on this, after details are provided. 
The file to modify is https://github.com/webcompat/webcompat.com/blob/eae44eda6b0e1db226d9c4acaa90839c99199593/webcompat/templates/contributors.html#L47-L66

**Comment by softvision-raul-bucata** [comment]
Raul Bucata
Romania

QC Engineer that enjoys breaking web pages...for the greater good. Loves snowboarding and the fine art on skin.


github@softvision-raul-bucata

![IMG_4175](https://user-images.githubusercontent.com/75027050/125918008-4de44b48-1db1-4996-84fa-52a2e1559d95.JPG)

**Comment by ksy36** [comment]
This is deployed
