### ISSUE TITLE
Incorporate bugbug ml labelling into moderation process 

### ISSUE THREAD

**Issue by ksy36** [webcompat/webcompat.com#3574]
In https://github.com/webcompat/webcompat.com/issues/3571 I've added bugbug classification and issues that are most likely invalid will receive `bugbug-probability-high` label in the private repository. We need to incorporate this into the moderation process to close such issues automatically.

There is a problem with posting issues content to the public repository without human moderation as we may end up submitting abusive content and get banned by GitHub again. So as a solution, we could post a placeholder text to the public issue, instead of its content for these invalid issues. Something like the current bot is posting now [as a comment](https://github.com/webcompat/web-bugs/issues/73946#issuecomment-842043683), but we'll put it in the issue body instead.

`issue is labelled invalid by the bot -> do not post the content to the public repository, post a placeholder text instead and close the issue`

If we decide to go this path, users won't be able to see the content of their report if it was labelled invalid (they will only see the placeholder text). It's not ideal (but acceptable?), and I wonder how important this is given the overwhelming amount of issues we're getting. 

Do you have any thoughts on this? 
@softvision-oana-arbuzov  @softvision-raul-bucata @karlcow

**Comment by ksy36** [comment]
To add to this, we had a discussion with @karlcow about another approach. We could train a second model to detect nsfw sites and label those and make a decision about posting content to public based on this label. 

`issue is labelled invalid and nswf -> do not post the content to public repository, put a placeholder text instead and close the issue`

`issue is labelled invalid by the bot -> post content to public repository and close the issue`

The problem with this approach is that we can't be 100% sure on nsfw prediction. We currently have a good amount of issues that are manually labeled `nsfw`, however there always will be a new domain, an image or something on the page that could be considered abusive content, but will not be categorized by the model as nsfw. In addition, since we delete problematic (teen) issues in both repositories, there is no data for those domains either.

**Comment by softvision-oana-arbuzov** [comment]
@ksy36 I think it is a good approach using the placeholder text, most of those issues have no value (meaning no relevant info is given to work with), and I don't think the users that report these kind of issues, will come back to comment.

**Comment by ksy36** [comment]
Sounds good, I'll go with this approach then, thanks for the feedback :)

**Comment by karlcow** [comment]
Just deployed on staging.

I created a [dumb issue](https://github.com/webcompat/webcompat-tests-private/issues/281) which was identified as invalid and autoclosed and the [original content was updated](https://github.com/webcompat/webcompat-tests/issues/2647)

This bug was [identified as valid](https://github.com/webcompat/webcompat-tests-private/issues/282)
and after switching to accepted the [original content was published](https://github.com/webcompat/webcompat-tests/issues/2648).

This is awesome @ksy36 
This will accelerate the work of @softvision-oana-arbuzov and @softvision-raul-bucata

**Comment by ksy36** [comment]
thanks for testing on staging @karlcow, I'll deploy this on production today

**Comment by ksy36** [comment]
I think @karlcow has deployed it already 😁
