### ISSUE TITLE
safari ipad wrongly identified as firefox ios

### ISSUE THREAD

**Issue by karlcow** [webcompat/webcompat.com#3578]
This type of issues reported from Safari on iPad gets a `browser-firefox-ios` label.

This is wrong and it must be a regression of my previous patch #3570

We need more tests.

```
<!-- @browser: Safari 13.1 -->
<!-- @ua_header: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1 Safari/605.1.15 -->
<!-- @reported_with: mobile-reporter -->
<!-- @public_url: https://github.com/webcompat/web-bugs/issues/75522 -->
<!-- @extra_labels: browser-firefox-ios -->
```

It should be `browser-safari-ios` + `device-tablet`. Let's fix this.

**Comment by karlcow** [comment]
examples:

* https://github.com/webcompat/web-bugs/issues/75511
* https://github.com/webcompat/web-bugs/issues/75522

This issue was found by @softvision-raul-bucata

**Comment by ksy36** [comment]
There is very little difference in UA strings on Safari on iPad and Firefox on iPad.

Safari:
`Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1 Safari/605.1.15`

Firefox
`Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1 Safari/605.1.15`

Pretty much the same, except looks like the versioning is updated in Safari UA and Firefox is hardcoded

**Comment by ksy36** [comment]
Could it be that `browser-firefox-ios` is coming from here? https://github.com/mozilla-mobile/firefox-ios/blob/main/Shared/SupportUtils.swift#L27

**Comment by ksy36** [comment]
@karlcow maybe we could pass another label here https://github.com/mozilla-mobile/firefox-ios/blob/main/Shared/SupportUtils.swift#L27 to identify iPad, something like `browser-firefox-ios` + `device-tablet`? As there is no way to accurately detect an iPad using UA detection at the moment. If we go that way we need to make sure that iPhone doesn't get it, as both seem to be sharing this code

**Comment by karlcow** [comment]
> @karlcow maybe we could pass another label here https://github.com/mozilla-mobile/firefox-ios/blob/main/Shared/SupportUtils.swift#L27 to identify iPad, something like `browser-firefox-ios` + `device-tablet`? 

Yes that would be a good idea.

**Comment by karlcow** [comment]
I opened https://github.com/mozilla-mobile/firefox-ios/issues/8614

**Comment by karlcow** [comment]
OK so https://github.com/mozilla-mobile/firefox-ios/pull/8615 has been merged
And it will be part of v34.1 which will release June 17
So we have 2 weeks to adjust the webcompat.com server side for handling `device-tablet`

* [x] label added to the repo https://github.com/webcompat/web-bugs/labels?q=device
* [ ] create a test case for `device-tablet`
* [ ] add `device-tablet` to the list of accepted extra labels
