### ISSUE TITLE
Add label for Firefox/100

### ISSUE THREAD

**Issue by karlcow** [webcompat/webcompat.com#3612]
There will be a running experiment (driven by the experiment team, piloted by @cpeterso ) very soon for people using Nightly in Firefox we should 

* [x] add label for `version100` in the labels list
* [ ] create tests for `Firefox/100` and `Chrome/100` UA string
* [ ] detect that the reported user agent version is Browser/100 and automatically assign the label

That will help the webcompat team to identify a "potential source" for the issue.

**Comment by karlcow** [comment]
@cpeterso when do we start the experiment?
So we can deploy it on webcompat.com side before it's on.

**Comment by miketaylr** [comment]
Happy to help review this change.

**Comment by cpeterso** [comment]
> @cpeterso when do we start the experiment?
> So we can deploy it on webcompat.com side before it's on.

I don't have an exact date yet. I'm hoping before the end of August, but it won't happen sooner than August 20.

**Comment by karlcow** [comment]
perfect it gives me time to polish the backend and have the approval of @ksy36

**Comment by Mte90** [comment]
maybe can be closed now?

**Comment by ksy36** [comment]
Yeah, let's close this as the experiment is over and we're in 104 now.
