### ISSUE TITLE
GitHub App permission

### ISSUE THREAD

**Issue by Mte90** [webcompat/webcompat.com#3626]
![immagine](https://user-images.githubusercontent.com/403283/139045101-05023320-9b7f-4b99-a034-ad8d334b6a19.png)

This is what GitHub suggest to me for the login.
I don't understand why should be able to write all those information in my repositories.
Should asks just for the user and not also for the various organizations I am part of?
I am not able to login as I don't want to share permission for all of them.

**Comment by ksy36** [comment]
Just an update here, I've converted the Oath app to a Github app, so it will only ask for permissions for `webcompat/web-bugs` from now on.

**Comment by Mte90** [comment]
Thanks!
