### ISSUE TITLE
Have better instructions for dev setup in a windows environment

### ISSUE THREAD

**Issue by karlcow** [webcompat/webcompat.com#364]
> I had loads of trouble getting the environment set up on windows for local testing. >_<
mentioned in #363

**Comment by miketaylr** [comment]
@hallvors said "just throw it over", which means he's going to help with this. Unless he meant throw this issue in the trash.

**Comment by miketaylr** [comment]
TODO: 

@hallvors to write notes of how he got his setup working.
@miketaylr and @haseebgit to test out the instructions and write docs.

**Comment by hallvors** [comment]
Well, since we've fixed #758 it's a lot easier - make sure python and node are on your PATH, ignore all instructions saying "make" or "sudo" and you'll be fine :-p
