### ISSUE TITLE
possible flaky test

### ISSUE THREAD

**Issue by XinyuLiu5566** [webcompat/webcompat.com#3655]
When I run pytest --flake-finder on this project, test_template.py:: test_get_checksum_not_in_cache fails after the first run because it added something into the dictionary and check its emptiness again, so I think it would be better if the added thing is deleted after each run so the test passes every time.

**Comment by ksy36** [comment]
This was addressed in https://github.com/is2ei/webcompat.com/commit/aa149b447c0c707f28f900226e067653fdea7376
