### ISSUE TITLE
Potential regression label

### ISSUE THREAD

**Issue by ksy36** [webcompat/webcompat.com#3671]
We had some webcompat issues recently that were caused by a change in Gecko and we detected/diagnosed them too late, so the regressing change had to be backed out from release. To avoid this in the future, we could, perhaps, add an additional check during triage - if there is an issue in Nightly that is about to be moved to `needsdiagnosis`, checking whether an issue is reproducible in Firefox release as well. If it's not reproducible in release (i.e. Nightly only), then it's likely a regression and `regression` or `potential-regression` label can be added.

Based on this label we can prioritize diagnosis, so those issues won't stay in the pile for too long. We will do bisection during diagnosis if needed, to figure out the regressing bug.

@softvision-oana-arbuzov @softvision-raul-bucata wonder what your thoughts are on this, and whether it's too much extra work?

fyi @denschub @karlcow @wisniewskit

**Comment by softvision-raul-bucata** [comment]
@ksy36 Sounds good on our part. We can apply this method, with no problems. Also, we can help with `mozregression` as well when it's the case, as we perform a `mozregression` when issues like this appear. Please let us know when we are ready to apply the labels.

**Comment by ksy36** [comment]
Thanks, @softvision-raul-bucata. I've created the label (https://github.com/webcompat/web-bugs/labels/regression) and we can start using it.

> Also, we can help with mozregression as well when it's the case, as we perform a mozregression when issues like this appear

That's awesome! Also don't feel pressured to do it, let's share the load :)

**Comment by pascalchevrel** [comment]
I think that we should have both a `regression` and a `regressionwindow-wanted` label as we have on bugzilla so as to be able to filter bugs that need mozregression work.

**Comment by karlcow** [comment]
`regressionwindow-wanted` is understandable.
what `regression` means in the context of bugzilla?

Because when we find this is a real regression, the webcompat team usually open a core bug with a link to the original bug in Regressed_by (or link directly to an already opened bug). 

see https://github.com/webcompat/web-bugs/issues?q=is%3Aissue+mozregression+milestone%3Aduplicate

**Comment by pascalchevrel** [comment]
Bugs with the `regression` keyword are regressions with an identified regressor, indicated in the `Regressed By` field. 

Bugs with both `regression` and `regressionwindow-wanted` keywords are identified regressions for which we haven't identified yet the regressor. QA, devs, community as well as our automated regression finders scripts can query for such bugs and provide a mozregression window. 

It is crucial for relman to identify the bug that introduced the regression as this allows us to escalate rapidly the issue with the dev that caused the regression and also allows us to determine if a backout of the regressing patch before shipping is possible or less risky than a hot fix.

**Comment by ksy36** [comment]
> I think that we should have both a regression and a regressionwindow-wanted label as we have on bugzilla so as to be able to filter bugs that need mozregression work.

I've created `regressionwindow-wanted` [label](https://github.com/webcompat/web-bugs/labels/regressionwindow-wanted) as well for such issues. 

Thanks everyone for the feedback, I think we can close this issue.
