### ISSUE TITLE
"Search privately" option is displayed triple times on "Context" menu

### ISSUE THREAD

**Issue by softvision-oana-arbuzov** [webcompat/webcompat.com#3676]
URL: https://webcompat.com/ and https://staging.webcompat.com 
Browser / Version: Firefox Nightly 99.0a1 (🦎 99.0a1-20220212094743) 
Operating System: Google Pixel 5 (Android 12) - 1080 x 2340 pixels, 19.5:9 ratio (~432 ppi density), Samsung Galaxy S8 (Android 9) - 1440 x 2960 pixels, 18.5:9 ratio (~570 ppi density)

**Steps to Reproduce:**
    1. Navigate to https://webcompat.com/
    2. Press long tap on a text until "Context" menu is displayed.
    3. Tap the "More" button from the "Context" menu.
    4. Scroll down and observe the list of options.
          
**Expected Behavior:**
The "Search privately" options are specific to the redirecting browser. (e.g "Search privately on Opera" / "Search privately on Firefox Focus" / "Search privately on Firefox Focus Nightly").

**Actual Behavior:**
The "Search privately" options is displayed triple times.

**Note**
    1. Screenshot attached.
    2. The issue is not reproducible on Chrome.

![image](https://user-images.githubusercontent.com/12184325/154028178-ad2a949e-a8b5-4bab-b1ec-5194582850d6.png)
       
**Watchers:**
@softvision-oana-arbuzov
@softvision-raul-bucata

sv;

**Comment by ksy36** [comment]
This is not related to webcompat.com as it's reproducible on all websites. While the UI is confusing, I think it's expected as those options are coming from other browsers (I have "Search in Edge" and 2 "Search privately" and in my case, they're Opera and Firefox Focus)

See more:
https://github.com/mozilla-mobile/fenix/issues/10543
https://github.com/mozilla-mobile/fenix/issues/8199
https://github.com/mozilla-mobile/fenix/issues/10466
https://github.com/mozilla-mobile/fenix/issues/13070

**Comment by ksy36** [comment]
To add to my comment, maybe an improvement that can be done here is for Firefox Focus to change how its search text appears in this case, to make it more distinct.

@softvision-oana-arbuzov wonder what is the third browser on "search privately" list?

**Comment by softvision-oana-arbuzov** [comment]
I see, thanks @ksy36 . Yes it would be useful to have more specific name for each. 

The 3rd browser for me is Firefox Focus Nightly (which I have installed on my device).

**Comment by ksy36** [comment]
Thanks! I filed https://github.com/mozilla-mobile/focus-android/issues/6478
