### ISSUE TITLE
Redirect link of "Firefox Nightly" on "TOOLS TO REPORT AN ISSUE" section has an extra character

### ISSUE THREAD

**Issue by sv-calin** [webcompat/webcompat.com#3712]
**Url:** https://webcompat.com/contributors/report-bug#tools

**Environment:**
Operating system: Windows 10
Firefox version: Nightly 104.0a1 (2022-07-13) (64-bit)

**Steps to reproduce:**
1. Go to https://webcompat.com/contributors/report-bug#tools
2. Click on "Firefox Nightly" hyperlink from "In Browser" description.

**Expected Behavior:**
The hyperlink redirects the user to the exact place where Nightly can be downloaded.

**Actual Behavior:**
The hyperlink redirects the user to the download page with all the Firefox versions.

**Notes:**
1. Video provided: https://gifyu.com/image/SKB6K
2. There's an extra ( " ) in the redirect link.

**Watchers:**
@softvision-oana-arbuzov
@softvision-raul-bucata

**Comment by ksy36** [comment]
Thanks for the report :) This will be fixed once https://github.com/webcompat/webcompat.com/pull/3728 is deployed

**Comment by sv-calin** [comment]
The issue no longer reproduces. Closing this as Fixed.

[inv_41/2022]
