### ISSUE TITLE
Dead link in "Organize Webcompat events" article

### ISSUE THREAD

**Issue by LaoshuBaby** [webcompat/webcompat.com#3726]
I click the "Report a bug" button on https://webcompat.com/contributors/organize-webcompat-events , this will lead me to https://webcompat.com/contributors/contributors/report-bug and this page had been deprecated, so I got a 404:

![图片](https://user-images.githubusercontent.com/42690037/183750550-2f25e037-9bcd-4190-b0e9-be372f9854de.png)

![图片](https://user-images.githubusercontent.com/42690037/183750490-3b2941da-dbbe-418a-9ac2-5db74ba5f038.png)

Related code is:

https://github.com/webcompat/webcompat.com/blob/408d8032dcdcdd94893b2ca84e071c9b71ba7926/webcompat/templates/contributors/organize-webcompat-events.html#L29

I guess it should be replaced with https://webcompat.com/issues/new ?

**Comment by ksy36** [comment]
Thanks for the report! Yes, it seems to be linking to https://webcompat.com/contributors/contributors/report-bug, but it should be https://webcompat.com/contributors/report-bug (without second `contributors`)
