### ISSUE TITLE
Honor `prefers-reduced-motion`

### ISSUE THREAD

**Issue by denschub** [webcompat/webcompat.com#3735]
As per [this Reddit post](https://www.reddit.com/r/firefox/comments/xvx3yo/if_animation_gives_you_migraines_you_may_need_to/), we should probably set the animation duration to 0 in [`showContainer`/`hideContainer`](https://github.com/webcompat/webcompat.com/blob/408d8032dcdcdd94893b2ca84e071c9b71ba7926/webcompat/static/js/lib/wizard/ui-utils.js#L33-L72) based on a  `window.matchMedia('(prefers-reduced-motion: reduce)')` media-query check.

**Comment by ksy36** [comment]
Fixed in https://github.com/webcompat/webcompat.com/pull/3747

**Comment by MarjaE2** [comment]
Still broken in Firefox.
