### ISSUE TITLE
Rerolling messages doesn't work on Charstar.ai

### ISSUE THREAD

**Issue by NovadewInTheMorning** [webcompat/webcompat.com#3787]
If I try to reroll a message on a character, it will not generate the next message. It will just infinitely load until you reload the site and it reverts back to the message it was before.

**Comment by ksy36** [comment]
Thank you for the report. This repository contains the sources for webcompat.com. We collect reports about site breakage in a different repository (https://github.com/webcompat/web-bugs/issues). 

Could you please file the report about this issue with charstar.ai on https://webcompat.com/issues/new?

Also could this be similar issue? https://github.com/webcompat/web-bugs/issues/127665

**Comment by NovadewInTheMorning** [comment]
Okay, I'll check that out.
