### ISSUE TITLE
How to report a bug about firefox, but not about specific site?

### ISSUE THREAD

**Issue by FeelUsM** [webcompat/webcompat.com#3825]
page https://bugzilla.mozilla.org/enter_bug.cgi? redirects me to https://webcompat.com/issues/new,  
but there I can create bugreport only about site

**Comment by karlcow** [comment]
https://bugzilla.mozilla.org/enter_bug.cgi doesn't redirect to webcompat. 
There are a lot of choices there for Firefox. 

If it's about Firefox UI
https://bugzilla.mozilla.org/enter_bug.cgi?product=Firefox

If it's about Core features
https://bugzilla.mozilla.org/enter_bug.cgi?product=Core
