### ISSUE TITLE
grunt and updating after a while

### ISSUE THREAD

**Issue by karlcow** [webcompat/webcompat.com#386]
So I was in the process of restesting things. I started 

```
python run.py
```

And obviously I had missing CSS. 
So I go back to the cli, check the manual 
https://github.com/webcompat/webcompat.com/blob/master/CONTRIBUTING.md#installing-grunt

And run the commands:

```
(webcompatcom)14:40:12 ~/code/webcompat.com
→ npm install grunt-cli
npm WARN package.json webcompat@ No repository field.
npm ERR! Error: EACCES, symlink '../grunt-cli/bin/grunt'
npm ERR!  { [Error: EACCES, symlink '../grunt-cli/bin/grunt'] errno: 3, code: 'EACCES', path: '../grunt-cli/bin/grunt' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! System Darwin 14.0.0
npm ERR! command "node" "/usr/local/bin/npm" "install" "grunt-cli"
npm ERR! cwd /Users/karl/code/webcompat.com
npm ERR! node -v v0.10.30
npm ERR! npm -v 1.4.21
npm ERR! path ../grunt-cli/bin/grunt
npm ERR! code EACCES
npm ERR! errno 3
npm ERR! stack Error: EACCES, symlink '../grunt-cli/bin/grunt'
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/karl/code/webcompat.com/npm-debug.log
npm ERR! not ok code 0
```

It fails. 

There is something in our documentation which is missing for having an up-to-date server with all the assets.

@magsout what is the secret sauce?
I don't want to do `make init` which redownload everything all python modules.

**Comment by miketaylr** [comment]
I think this is probably fixed now, with the NPM deps stuff added @ https://github.com/webcompat/webcompat.com/commit/d7345efc52e40dd65296241dc4c6dffebb9a56a1 and the Pip stuff added via https://github.com/webcompat/webcompat.com/issues/583.

The only catch being that you need to `npm install` one last time to get the grunt task to check your npm dependencies. :p
