### ISSUE TITLE
Search URI is not pushed to the address bar

### ISSUE THREAD

**Issue by karlcow** [webcompat/webcompat.com#399]
## Step to reproduce:
1. Go to http://webcompat.com/
2. Log in
3. Click see More
4. Type a search term. for example: "is:issue is:open google in:title"

## Expected:
to have the URI in the address bar to be something along (Not necessary this parameter syntax, just an example)
`https://webcompat.com/issues/search?is=issue&is=open&q=google&in=title`

## Current:
The address is `https://webcompat.com/issues`

## Why it's important. 
It's currently not possible for someone to share a specific search URI on the Web or by mail.

## Possible issues
When someone is not logged in to webcompat.com, the search URI will not be working. We could handled that case through a redirect to github search.

**Comment by miketaylr** [comment]
Making progress on this. Pushing params to the URL is all done--and toggling filter params as well. I just need to hook up reading from the URL in `loadIssues`.

And then we need to tackle #516 (actually having and reacting to a state for the pushState). I don't think it will make much sense to deploy one without the other. Or at least it would feel very broken.

**Comment by hallvors** [comment]
heh, Karl was already on it :)

**Comment by miketaylr** [comment]
OK, I think I've got this one done. But I need to write some tests before sending a PR--there's a billion things to keep track of, which means I'll surely break it in the future. ^_^
