### ISSUE TITLE
wc-Labels component

### ISSUE THREAD

**Issue by magsout** [webcompat/webcompat.com#402]
![capture d ecran 2014-11-15 a 15 18 40](https://cloud.githubusercontent.com/assets/1997108/5057927/b69de138-6cda-11e4-947d-f2e5ce4270f6.png)

I find the idea of @calexity interesting , add borders on labels. I think it would be nice to generalize on the list of issues?

**Comment by karlcow** [comment]
ok so far so good. My local instance behaves normally, aka it fails. 
![labels-renaming](https://cloud.githubusercontent.com/assets/505230/6142510/dafac8a6-b1fa-11e4-8c9b-f5646479ee3e.jpg)

Let's see if I can get the refiltering right.
