### ISSUE TITLE
Retina image support for contributors page

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat.com#428]
The images on /contributors look blurry on retina devices.

**Comment by magsout** [comment]
@miketaylr you have retina device ? If yes, can you make some screenshot to test ?

**Comment by miketaylr** [comment]
Yep, I'll take some screenshots on my rMBP.

**Comment by miketaylr** [comment]
See https://cldup.com/9EM7uge54c-3000x3000.png and https://cldup.com/ai4pDOXye3-3000x3000.png, for example.
