### ISSUE TITLE
Developer documentation for contributing to webcompat.com

### ISSUE THREAD

**Issue by calexity** [webcompat/webcompat.com#429]
(Sphinx-RTD)

**Comment by karlcow** [comment]
Yes I need to do that. I had started and I kind of drop the ball. It's ready I just need to kick my ass.

**Comment by karlcow** [comment]
A good example for new contributor.
https://github.com/github/git-lfs/blob/2cf082fa14a738f73db6d172eba800ca118e6d97/CONTRIBUTING.md#feature-requests

This issue makes sense again after the flow of outreach contributors we had recently.
See also
* https://wiki.mozilla.org/Compatibility/Mobile/2016-03-22
* http://www.otsukare.info/2016/03/17/community-participation

**Comment by karlcow** [comment]
Also related 
https://github.com/blog/2128-creating-a-new-contributor-on-ramp

**Comment by miketaylr** [comment]
I think this is FIXED now -- see https://github.com/webcompat/webcompat.com/issues/429 for possible ways we can improve what we have in CONTRIBUTING.md.
