### ISSUE TITLE
Include screenshot where possible

### ISSUE THREAD

**Issue by calexity** [webcompat/webcompat.com#431]
Make it easier to include a screenshot when reporting a bug (focus on mobile, but extended to all places we can reach)

As a mobile bug reporter
When I report a bug
Then I want it to make it easy to attach a screenshot
So it can be more helpful and get solved faster.

**Comment by miketaylr** [comment]
Cool, I dig it.

**Comment by miketaylr** [comment]
I'm going to close as a dupe of #452 (even though that was opened later).
