### ISSUE TITLE
Make label editor easier to use

### ISSUE THREAD

**Issue by calexity** [webcompat/webcompat.com#433]

**Comment by magsout** [comment]
what's point about label editor ?

**Comment by calexity** [comment]
I think the point was it is sort of a pain to add labels and we should make it easier.  

Also, @karlcow said there are some inaccurate labels coming through.

Question from Karl
- Do we allow contributors to add tags (beyond the webcompat team)?

I propose that Karl and/or Mike curate the labels and we don't allow people to add to them (if possible).

**Comment by miketaylr** [comment]
Yeah, sounds good. Right now only webcompat [collabs](https://github.com/orgs/webcompat/teams/collaborators) + [owners](https://github.com/orgs/webcompat/teams/owners) can add labels. I think it makes sense to keep that group small.

**Comment by miketaylr** [comment]
This seems fixed.
