### ISSUE TITLE
Make "Need Contact" label and reflect in the UI on webcompat.com

### ISSUE THREAD

**Issue by calexity** [webcompat/webcompat.com#434]
Add a "Need Contact" label for sites that someone needs to find a contact for.  In between Needs Diagnosis and Contact Ready.

We need to add a color or way to show this on the homepage and all issues page

**Comment by miketaylr** [comment]
We have the label now. Just not a UI for it.

**Comment by calexity** [comment]
This just needs a color, right?

Here's the color: #b9edce

Here's a couple screenshots of what that looks like. I think we could copy the same filter from the All Issues page and put it on the homepage (maybe add a white background since they're over gray there). I'm not sure why I designed them differently. 

![screen shot 2015-08-13 at 1 13 44 am](https://cloud.githubusercontent.com/assets/1103366/9245506/85e7a656-4159-11e5-9b68-ecce8a55d936.png)
---------------------------------------
![screen shot 2015-08-13 at 1 13 53 am](https://cloud.githubusercontent.com/assets/1103366/9245507/85e821d0-4159-11e5-9138-5be9307d59f0.png)
---------------------------------------
![screen shot 2015-08-13 at 1 18 40 am](https://cloud.githubusercontent.com/assets/1103366/9245509/85e92c9c-4159-11e5-8945-e14864e82207.png)
---------------------------------------
![screen shot 2015-08-13 at 1 18 48 am](https://cloud.githubusercontent.com/assets/1103366/9245508/85e8a5b0-4159-11e5-8e6a-85d4b8b9fa44.png)

**Comment by miketaylr** [comment]
I think the plan was to get rid of everything except for "new" on the homepage, but otherwise this looks good. ^_^

**Comment by calexity** [comment]
Duh. I'm pretty behind. Is this in this issue? https://github.com/webcompat/webcompat.com/issues/571

Here's what that could look like. Or we could go with what I put in that story which is a smaller version of the All Issues page.

![small viewport](https://cloud.githubusercontent.com/assets/1103366/9267100/43e2d5f0-41fe-11e5-9df4-44bf27cd8da7.png)
--------------
![large viewport](https://cloud.githubusercontent.com/assets/1103366/9267101/43e36c18-41fe-11e5-8c63-f02c42a3e7a8.png)

**Comment by karlcow** [comment]
There are a couple of issues to finish this one.

* Implement the design proposed by @calexity in the HTML/CSS by @magsout ?
* Implement the needscontact in the JavaScript code (should we create a separate bug for this?) OK let's do that, opened #680

**Comment by miketaylr** [comment]
I'm gonna do this -- will ping @magsout if I need his help. ^_^
