### ISSUE TITLE
Custom issue dashboard

### ISSUE THREAD

**Issue by calexity** [webcompat/webcompat.com#442]
As a contributor or a site developer
When I login to webcompat.com
Then I want to customize a dashboard of issues I'm interested in
So when it's easier to contribute to the project.

As a site developer
When I login to webcompat.com
Then I want to customize a dashboard of issues I'm interested in
So when it's easier to watch issues and fix my site.

**NOTES**
Person should be able to customize a search or somehow choose bugs they want to watch and then, it automatically populates a page or section of a page.

**Comment by calexity** [comment]
I was thinking about the expand on the left @magsout - are you thinking that would be useful for filters?  I think the filters should work similarly to how they work on the All issues page. Either exactly the same or something like this.

Under that dropdown, we could include "Mentioning me" and "Submitted by me".

Small
![custom dashboard small](https://cloud.githubusercontent.com/assets/1103366/5694568/26bb9410-991d-11e4-958d-8fc41cecb16c.png)

---

Large
![custom dashboard large](https://cloud.githubusercontent.com/assets/1103366/5694569/2ac5bbd0-991d-11e4-9dee-395867ffbbd1.png)

The star is http://fortawesome.github.io/Font-Awesome/icon/star/

**Comment by miketaylr** [comment]
We talked about this in Paris, and the first steps will be to have a "My Activity" drop down when clicking on the avatar. @magsout is building that in #738 (nearly done) after which we can add a page that shows the following two things:

* Issues I reported
* Issues that @ mention me.

And from there start to do the fancy issue starring (or any number of things).

**Comment by adamopenweb** [comment]
I really like the ideas and drawings here. I want to add that I think returning users who are logged in could be directed to the dashboard. This could give us the freedom to tune the webcompat home page even more towards new users / anonymous reporters and improve on the on-boarding process.

**Comment by miketaylr** [comment]
We changed our mind on how we want to do this. @karlcow can you file the bug?

**Comment by karlcow** [comment]
@miketaylr It seemed clear the way we wanted to do this. But now I'm confused re-reading the full bug in details.
During the meeting, we said we wanted to have a tool helping us managing issues such as being able to see how old a bug is etc. ok Let me spin-off this in a different way.

**Comment by miketaylr** [comment]
Uhhhhh, I think I waited too long to respond. My RAM cache got cleared. 🙈
