### ISSUE TITLE
Bug status label should be mutually exclusive

### ISSUE THREAD

**Issue by karlcow** [webcompat/webcompat.com#448]
Currently we have 

1. needdiagnosis
2. (needcontact) See #434 
3. contactready
4. sitewait
5. fixed, duplicate, wontfix, worksforme, ?

It should not be possible to have these mutually selected. The proposal would be that when you select one, you unselect the other(s).

**Comment by hallvors** [comment]
Nobody minds if I take this..?

**Comment by miketaylr** [comment]
Sounds good!

(I would say generally if nobody is assigned, feel free to assign yourself--unless somebody didn't get assigned and it looks like they're committing code, etc).
