### ISSUE TITLE
Add a screenshot to the browser extensions

### ISSUE THREAD

**Issue by calexity** [webcompat/webcompat.com#452]
As a bug reporter
When I'm reporting a bug using the webcompat browser extension
Then I want it to be easy to include a screenshot of what I'm seeing
So that my bug report can be more useful.

- [x] Firefox extension
- [ ] Firefox for Android
- [x] Chrome extension
- [x] Safari extension
- [x] Opera extension

**Comment by miketaylr** [comment]
Depends on #317.

**Comment by miketaylr** [comment]
OK, brainstorming how this should work here.

1. User is on a webpage which has some kind of problem
2. User clicks "Report Site Issue" (or add-on button, depending on the browser)
3. New tab is opened with webcompat form
4. Somewhere on the form, there's a small preview of of the page from 1, with an (unchecked) option to include the screenshot in the report
5. User checks screenshot, fills out form, and reports issue
6. Issue is created (the `POST` data will now have a blob along w/ the rest of the form data)
7. Create image on filesystem from blob (and ideally be able to run it through @karlcow's image validation/optimization stuff he's working on in #710).
8. Have a pointer to the uploaded screenshot image, just like as if the user did a regular image upload.

(At some point between 2 and 3, we've hopefully called some kind of add-on or browser API to get a `blob` (ideally, or base64 image could work) that contains a screenshot of the problematic site from 1.)

**Comment by miketaylr** [comment]
(Reminder to self that @calexity has some design ideas: https://github.com/webcompat/webcompat.com/issues/431#issuecomment-68215120)

**Comment by miketaylr** [comment]
I'm going to prototype this in the Firefox desktop add-on. https://github.com/webcompat/webcompat-reporter-extensions/commit/ef64b88672d013dc239e641bcc09fc8d0ac86b38 makes it so we can build the add-on with `jpm` (I guess `cfx` is dead).

**Comment by miketaylr** [comment]
I should have something functional, at least the backend parts by Monday or so -- this is probably going to add more work for you, sorry @karlcow (or at least more rebasing for #710). But I'd like to not be blocked on the optimization stuff.

**Comment by karlcow** [comment]
no issue.

**Comment by miketaylr** [comment]
Status update:

Chrome, Opera, Firefox Desktop add-ons are updated. I won't submit the updated ones to the official addon sites until #879 is fixed and deployed -- I think that will probably just confuse the addon reviewers.

#882 just landed which added the ability to parse and save screenshot uploads from the addons.

TODO:

- [ ] Build UI (#867)
- [ ] Finish up #879
- [ ] Safari add-on
- [ ] Fennec add-on

**Comment by miketaylr** [comment]
> Depends on #317.

Nah, not really.

**Comment by miketaylr** [comment]
OK, time to pick this up again...

The Fennec add-on will just be a port of the work for the "Report Site Issue" built-in menu in [Fennec Nightly](https://bugzilla.mozilla.org/show_bug.cgi?id=1237087).

**Comment by miketaylr** [comment]
That said, that's tracked in https://github.com/webcompat/webcompat-reporter-extensions/issues/16. So let's close this. \o/
