### ISSUE TITLE
Do performance audit and make recommendations

### ISSUE THREAD

**Issue by calexity** [webcompat/webcompat.com#454]
As a webcompat visitor
When I load the website
Then I want it to be fast
So I can navigate quickly even with a slow internet connection.

**NOTES**
This story is to do a performance assessment/make some recommendations that can be prioritized to improve performance

**Comment by karlcow** [comment]
use pagespeed and evaluate the painful points to open new issues

**Comment by miketaylr** [comment]
@karlcow recently did this work and said we're in a good place. We can make improvements, but nothing on fire.
