### ISSUE TITLE
Document code architecture

### ISSUE THREAD

**Issue by calexity** [webcompat/webcompat.com#456]
@miketaylr to document the code architecture per our retro (https://github.com/webcompat/webcompat.com/wiki/Retro-from-December-2014-work-week/)

**Comment by miketaylr** [comment]
webcompat.com is a hybrid Flask/BackboneJS web app.
Flask powers the API (which is proxied from GitHub's API) and handles traditional MVC stuff. The view, however, is just an html page which contains the bootstrap JS for the Backbone app, and the CSS.

to document: how the form stuff works, how the API proxying happens, how we enable anonymous stuff, how our backbone apps are structured, grunt.

**Comment by miketaylr** [comment]
I'm going to move this into the Backlog. It would be nice to have™, but not something that exists in every open source project, and I think my time would be better spent on other issues.

 If someone wants to ask questions and contribute these kinds of docs I'd be happy to help.

**Comment by miketaylr** [comment]
Note: @karlcow wants to make a graph of the model of how Flask communicates with GitHub. @karlcow can you file an issue? Let's do that this week.

**Comment by karlcow** [comment]
> Note: @karlcow wants to make a graph of the model of how Flask communicates with GitHub. @karlcow can you file an issue? Let's do that this week.

paper trail with regards to the last comment
https://github.com/webcompat/webcompat.com/issues/1640#issuecomment-313618570
