### ISSUE TITLE
Rethink anonymous bug reporting 

### ISSUE THREAD

**Issue by calexity** [webcompat/webcompat.com#457]
We need to rethink how we handle anonymous reporters - How can we make anonymous reports more valuable?

should we make it easier to do it?  should we not allow anonymous reports?  should we require more complete reporting?

**Comment by karlcow** [comment]
@calexity opened this more than 1 year ago. The discussion has been happening in a couple of issues.  Maybe we should list the problems. That could help us identify what we could work on and more than anonymous bug reporting I would like to frame this as incomplete bug reporting more than anonymous. Sometimes we have incomplete reports with users not answering. 

* Incomplete bug report:  no expected/actual information
* Incomplete bug report: no steps to reproduce the bug
* Wrong browser information. The browser used for reporting was not the one used for testing.
* Missing information about the form factor (screen size and/or tablet, mobile, desktop, tv)
* No replies when asking for more information
* Wrong labels

Even when we have someone's name. Some people do create a github account just for webcompat.com (kind of wow if you think about it), but many times, they don't follow-up on questions asking them more details.


There is probably a mix of language, we use iconography and flow of the bugs. Also the form requires a lot of information. I don't remember where I have read this recently but someone was explaining how a multi-steps mono-task form had improved the conversion rate. Too many fields can be intimidated.

@webcompat/collaborators

**Comment by hallvors** [comment]
Perhaps allowing anonymous reports only from the add-on, with screenshot? That way we're guaranteed to have at least some information we might work on..

**Comment by miketaylr** [comment]
> Perhaps allowing anonymous reports only from the add-on, with screenshot? That way we're guaranteed to have at least some information we might work on..

Now that's an interesting idea...

**Comment by karlcow** [comment]
@hallvors About
> Perhaps allowing anonymous reports only from the add-on, with screenshot? That way we're guaranteed to have at least some information we might work on..

Yes. Good idea that would minimize a bit, for at least the framing of the device/browser used, if we collect this information. I think we partly have an issue opened about this.

**Comment by adamopenweb** [comment]
I really like the friction-less reporting of the site currently. It's simple enough for general web users to discover and just report. I know we've talked about leveraging different account systems, it really depends on what that random web user subscribes to. Email is fairly universal though. Have we considered taking the email address and forcing the user to confirm by email link?

**Comment by karlcow** [comment]
@adamopenweb Could you expand a bit more on the steps from bug reporting to the end of what you are suggesting? Thanks. :)

One thing which makes me nervous about email subscription is the consequences of hosting an email DB,  though there is: Email notifications about webcompat project #55

**Comment by adamopenweb** [comment]
There are multiple ways this could be done, I'll try to explain what comes to my mind.
Method 1: 
Fill out bug details > include a properly formatted email address > submit. At this point we can keep the email address for notifications or immediately discard.

Method 2:
Fill out bug details > include a properly formatted email address > submit > confirmation email sent to user > link in email to "activate" bug report. At this point we can keep the email address for notifications or immediately discard.

If we aren't comfortable keeping email addresses right now, we can choose not to. At a later point, if we are ready to keep them, it would be easy to ask the user permission to do so.

If the goal is to reduce spam, Method 1 will not be very effective.

**Comment by hallvors** [comment]
We've learnt that a significant number of reports need more info - when we don't have a way to contact the reporter we can only close them. Also, discussing with reporters might help us expand the community and involve more people? So there are strong reasons for collecting E-mail addresses..

**Comment by karlcow** [comment]
> So there are strong reasons for collecting E-mail addresses.

No doubts. 
The thing which makes me uncomfortable, it's what comes with it. Privacy policy, consequences of being hacked, encryption of the data. The additional layer of responsibility and complexity.

**Comment by miketaylr** [comment]
> The thing which makes me uncomfortable, it's what comes with it. Privacy policy, consequences of being hacked, encryption of the data. The additional layer of responsibility and complexity.

Agree with @karlcow here. 

But I also agree there's value in being able to communicate with anonymous reporters (de-anonymizing them I guess, at some level).

I wonder if we might get traction for some reports if we put in an optional email field when people are reporting anon reports (similar to how the firefox crash reporter works "email in case we need to contact you"). Good topics for London.

**Comment by karlcow** [comment]
What about having a box for contact information, where we basically leave the freedom for the person to choose the way they wish to be contacted. 

We have to make it clear that the information will be public in the bug.

* Some could be github users who don't want to authorize webcompat to access everything
* Some could leave a twitter handle
* Some an email address.

**Comment by miketaylr** [comment]
WFM, @karlcow.
