### ISSUE TITLE
Assess security of tests requiring GitHub credentials

### ISSUE THREAD

**Issue by tagawa** [webcompat/webcompat.com#469]
In the <a href="https://github.com/webcompat/webcompat.com/blob/master/CONTRIBUTING.md#functional-tests">Functional Tests instructions</a> the following command is used, requiring a valid GitHub username and password:

```node_modules/.bin/intern-runner config=tests/functional/intern user=testusername pw=testpassword```

This feels insecure to me &mdash; the credentials could be being sent over HTTP (I guess not but haven't checked) and they're being stored in plain text in bash history.

We should look into whether there's cause for concern. If yes, do something about it, if no, add a note to the instructions to allay fears.

**Comment by miketaylr** [comment]
Doing some more research into this--I think the only risk would be a  MITM attack where someone has control of your localhost and grabs the credentials. When they're sent to GitHub, it's over HTTPS, and we don't hit any other external HTTP resources for tests.

The safest option is to not put in username or pw and enter it manually. But I'm OK with just passing in a bot's info on my local network. 

The other risk is bash history--but @tagawa covered that. Let's close now, but please reopen or add more info if I'm missing something. I'm not exactly a security expert.

**Comment by tagawa** [comment]
Thanks for checking the HTTPS - closing it for now sounds good to me.
