### ISSUE TITLE
About page color contrast errors

### ISSUE THREAD

**Issue by andrewmcgivery** [webcompat/webcompat.com#484]
Each one of the colored boxes in the section on the about page explaining the three part life cycle are causing color contrast errors.

Here's a list of the issues, their current color, and a color that would pass AAA standards.

Text | Current Color | Passing Color (AAA)
-----|-----|-----
Bug Reporting |  #6fc7fa | #437d9e
Bug Analysis | #ff8364 | #b75c46
Getting Contacts and Reaching Out | #a1ebbf | #558066

**Comment by miketaylr** [comment]
:+1: Very nice palette.

**Comment by miketaylr** [comment]
@calexity is there a bug for the new progress design and search stuff in your last comment? (I may have missed it)

**Comment by magsout** [comment]
@miketaylr this https://github.com/webcompat/webcompat.com/issues/510 ?

**Comment by miketaylr** [comment]
thxx!

**Comment by miketaylr** [comment]
I think this is done... can you verify @andrewmcgivery?

**Comment by andrewmcgivery** [comment]
About page looks good to me.

**Comment by miketaylr** [comment]
Cool, let's close. :+1:
