### ISSUE TITLE
Failing issue-list label search test

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat.com#493]
This is weird. It passes locally but fails on Travis. It might be timing related. But the error is weird:

See https://travis-ci.org/webcompat/webcompat.com/builds/44372336
```
Test main - issue-list - clicking on a label performs a label search FAILED on firefox 33.1 on LINUX:

StaleElementReference: [GET http://localhost:4444/wd/hub/session/8f03c094-bcd5-48c2-808f-d7f1a083f910/element/81/text] Element not found in the cache - perhaps the page has changed since it was looked up

For documentation on this error, please visit: http://seleniumhq.org/exceptions/stale_element_reference.html
```

Disabled in https://github.com/webcompat/webcompat.com/commit/f9c02eff90b1879fcd5ed282fc1f687542c18ded until we know what's up.

**Comment by karlcow** [comment]
@miketaylr Do we still have this issue?

**Comment by miketaylr** [comment]
Nope, don't think so!
