### ISSUE TITLE
Issue comment - Parse hashtag on comment

### ISSUE THREAD

**Issue by magsout** [webcompat/webcompat.com#501]
Like 
![capture d ecran 2014-12-20 a 11 06 24](https://cloud.githubusercontent.com/assets/1997108/5514471/4b2a9b52-8838-11e4-8c9c-a6699ec5c5a9.png)

I have to go on Github to see the correct issue.

**Comment by calexity** [comment]
Is this along the lines of what you were thinking @magsout @karlcow @miketaylr?

![commentstatus](https://cloud.githubusercontent.com/assets/1103366/5694487/5145c94e-9913-11e4-8bc8-0b72382f9130.png)

**Comment by karlcow** [comment]
Yes something like this. That's cool.
I would put either icon or text but not both for the status.

**Comment by calexity** [comment]
In that case, I think the text is clearer. I'd drop the icon at least until we've had them for a while.

**Comment by magsout** [comment]
A tooltip or title perhaps? I am concerned if we add the title of issue in the middle of the sentence, becomes difficult to understand, especially if we just add a reference

**Comment by karlcow** [comment]
@magsout yes. good grief, it can be overloaded. Let's imagine how these could be manipulated, changed, etc. The question is more about, how do we want it. :)

Another way of doing it (layout can be changed, just illustrating the concept):

![capture d ecran 2015-01-31 a 09 55 19](https://cloud.githubusercontent.com/assets/505230/5986018/98a4176a-a92f-11e4-8d8f-3a0997b12dc4.png)

Could become something like:

![capture d ecran 2015-01-31 a 09 55 01](https://cloud.githubusercontent.com/assets/505230/5986017/9880a262-a92f-11e4-8482-a0c9c620bd00.png)

**Comment by magsout** [comment]
I like the second :+1:

**Comment by karlcow** [comment]
Note that this is just exploration. I really think we can do better. Any suggestions are welcome. :)

**Comment by calexity** [comment]
I love the tooltip idea! Though it wouldn't work on mobile.

Something like this
http://cssdeck.com/labs/pure-css-tooltip-with-arrow

**Comment by miketaylr** [comment]
- [ ] add marked.js fork to our repo
- [ ] implement issue parsing

**Comment by miketaylr** [comment]
After doing some investigating, it seems Marked.js is very buggy and hacking support for this might be not worth it. Right now emoji and @username stuff only works if it's the *only* item of a block/paragraph. https://github.com/markdown-it/markdown-it looks promising and has a nice plugin architecture, already with emoji plugin and a "hashtag" plugin that could be extended for issue linking.

**Comment by miketaylr** [comment]
Let's take care of #604 then we can properly do this.

**Comment by karlcow** [comment]
#604 is done. Where do we stand on this one for `@usernames` and `#numbers`?

**Comment by miketaylr** [comment]
cc @hallvors who is going to be learning the markdown parser for #716

**Comment by hallvors** [comment]
'k, if you want more fancy stuff here please file new bugs..
