### ISSUE TITLE
Add note about using "[ci skip]" for doc updates, etc.

### ISSUE THREAD

**Issue by karlcow** [webcompat/webcompat.com#509]
When we are pushing commits, travis will repeat its dance for every single one, even when there is nothing to test, such as docs. etc.

There are two possibilities to manage this:

* **[`ci skip`](http://docs.travis-ci.com/user/how-to-skip-a-build/#Not-All-Commits-Need-CI-Builds)**
> Commits that have [ci skip] anywhere in the commit messages will be ignored. [ci skip] does not have to appear on the first line, so it is possible to use it without polluting your project's history.
* **[blacklist some branches](http://docs.travis-ci.com/user/build-configuration/#Specify-branches-to-build)**
We could imagine to have things like:
```
branches:
    except:
        - /^doc.*$/
```
and using always `docIssueNumber` for a branch which is about doc and other type of conventions.

**Comment by miketaylr** [comment]
I went ahead and just pushed this to master.
