### ISSUE TITLE
Closed/Open and bug status - two separate things

### ISSUE THREAD

**Issue by karlcow** [webcompat/webcompat.com#510]
During a test of the UI on ipod touch 3, I noticed something which seems not very logical.
1. Go to http://webcompat.com/
2. Click on the all issues list icon
3. Click on Closed.

The UI displays the list of closed issues, but we still have the "View All Open Issues" dropdown.

![img_1002](https://cloud.githubusercontent.com/assets/505230/5547083/aba2166e-8b52-11e4-938a-79e2c013c80c.PNG)

I think it is related to the questions we have on bug #349

**Comment by magsout** [comment]
@karlcow very interesting analysis, and many good point. I love the idea of the filters.

>Proposal: Should we get rid of the dropdown, and have instead a:
[All] [Open] [Closed]

@karlcow , @calexity  On desktop, maybe add the dropdown with the stats (all, close, open) next to the dropdowns "newest" and "show X" ?

On small devices, we could have in the order of appearance

- As a button (appearance):  `Open`-  `closed` - `filter` 
- SearchBar
- IssueList
- Pagination (only at bottom)

1) click on open: all open issue appear
2) click on closed: all closed issue appear
3) click on filter : all filter (news, need diagnosis, need contact etc..) appear and the two dropdown : Show by and Sort by.

And what about : 
- View Issues Submitted by Me  ?
- View Issues Mentioning Me  ? 

I don't use these `information` on Github, but maybe the other yes, so is it relevant or not ?

**Comment by calexity** [comment]
@magsout @karlcow 

Another option, just adding back Closed. I know there is some complexity to closed but it seems like between search and these filters, you could find the bug you were looking for.

Small
![smallfilter](https://cloud.githubusercontent.com/assets/1103366/5694403/97439716-990c-11e4-82a9-876d310bd236.png)

---

Large
![desktop add filter](https://cloud.githubusercontent.com/assets/1103366/5694405/a1730b54-990c-11e4-9d9c-ef7c22367a63.png)



Re: "issues submitted by me" and "issues mentioning me", I think that's a great idea for the issue dashboard filter (where it says Saved Issues) - https://github.com/webcompat/webcompat.com/issues/442

**Comment by karlcow** [comment]
note that the labels reorg has landed. So that will make a lot things easier, at least for writing code.

**Comment by hallvors** [comment]
@calexity love those small icons on the status labels! :heart:

**Comment by adamopenweb** [comment]
I agree the icons look great! I also like the reduced height of each item in the issue list.

**Comment by miketaylr** [comment]
Note: we like these designs and want to come back to them. But the issue around filtering on closed will be made obsolete by #1527.
