### ISSUE TITLE
Next/Prev Links in issues list are not links

### ISSUE THREAD

**Issue by karlcow** [webcompat/webcompat.com#511]
The next/prev buttons are not real links.

``` html
<div class="r-Grid-cell r-all--1of2 wc-Pagination js-pagination-controls">
            <button class="r-ResetButton wc-Pagination-link js-pagination-previous">previous</button>
            <button class="r-ResetButton wc-Pagination-link js-pagination-next">next</button>
          </div>
```

We can't navigate them.

Suggestion: Replace these by populated `a href`

**Comment by miketaylr** [comment]
Right now the navigation buttons/items/links (whatever we end up with) are rendered on the client. So even if they were links with hrefs, a non-JS client wouldn't see them. I don't know what the actual benefit would be to adding an href that is never navigated by a JS capable client--and we wouldn't want navigation to happen, the endpoint just returns JSON to be consumed by the client.

**Comment by karlcow** [comment]
>and we wouldn't want navigation to happen

I don't understand that. Because we specifically want this. That's an issue currently. see #399 this is basically the same type of things.

**Comment by miketaylr** [comment]
Got it. Once #399 is fixed, we can change it to links but it still won't change the fact that the site is only usable in JS-enabled client. I guess it will be useful is someone wants to open a "next" page in a new tab.

**Comment by magsout** [comment]
@karlcow so link ?

If we add links to the button instead,  "href" will be filled or it will be empty?

**Comment by karlcow** [comment]
@magsout Currently in the way the system is set up (I have to check again), I have the feeling that the JS client (instead of python backend) will add the right links to the href. @miketaylr can confirm.

1. change button to href.
2. Attach the link to the href before the click event.

If the question is in between 
* option A: "href stays empty and we listen click event"
* option B: "href is populated with the link, when the DOM is created/refreshed"

I say option B. Does it answer your question? :)

**Comment by miketaylr** [comment]
Yeah, we need to update the href of the link whenever the URL params are updated.

**Comment by miketaylr** [comment]
I've got a local patch that has this working--will clean it up tonight/tomorrow morning and send a PR.

**Comment by karlcow** [comment]
Yeah! :tada:
