### ISSUE TITLE
Login from the issues list

### ISSUE THREAD

**Issue by karlcow** [webcompat/webcompat.com#512]
1. On a browser not logged to webcompat.com
2. Go to the issues list page
3. Login
4. Github sends back to the homepage, not the issues list.

**Comment by miketaylr** [comment]
Thx, will investigate.

**Comment by miketaylr** [comment]
(oops)

**Comment by karlcow** [comment]
I have put my repo square again. And reconfigured my config.py.
Everything is working on my side, but this new feature. 
I guess we need a test. 

1. With a blank profile on Firefox (be sure to be logged out of Github)
2. Go to http://localhost:5000/issues
3. click on Log in
4. You get the github form
5. Enter your own credentials
6. Back to the home page and not http://localhost:5000/issues

The referer value is good `http://localhost:5000/issues`

``` http
Referer: http://localhost:5000/issues
Content-Length: 
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:34.0) Gecko/20100101 Firefox/34.0
Connection: keep-alive
Host: localhost:5000
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Content-Type: 
Accept-Encoding: gzip, deflate
```

**Comment by karlcow** [comment]
@miketaylr do you get the same thing?

**Comment by miketaylr** [comment]
Hmm, no I don't get the same behavior. After 5 I end up back at /issues. Just tested in a clean test profile and in a Chrome Canary private window. 

@magsout -- can you try to test when you get a chance?

**Comment by miketaylr** [comment]
(I was testing on master after I just pulled)

**Comment by magsout** [comment]
Works for me , just tested with the branch master, and I am redirected to /issues with those steps:

1. Go to http://localhost:5000/issues
2. click on Log in
3. You get the github form
4. Enter your own credentials
5. Back to the home page and not http://localhost:5000/issues
