### ISSUE TITLE
Search results are "below the fold" for small viewports

### ISSUE THREAD

**Issue by karlcow** [webcompat/webcompat.com#513]
0. With a mobile device
1. Go to https://webcompat.com/
2. Log in
3. Go to the issues list page.
4. Enter "Yahoo!" in the search field Press enter.

Nothing changed on the mobile screen.

Suggestion: Scroll to the top of search results. This might be partly solved with proposals made in #510

**Comment by miketaylr** [comment]
I think it makes sense to scroll the search field to the top. Should we do this for all viewport sizes, or just small ones?

**Comment by karlcow** [comment]
all viewports will be easier to maintain.

**Comment by calexity** [comment]
Is it possible to close the keyboard as well upon enter or hitting the magnifying glass?

**Comment by miketaylr** [comment]
Seems like there's got to be some hacks out there to acheive that--maybe just "blur"ing the input would be enough (meaning, make it lose focus).

**Comment by magsout** [comment]
>Is it possible to close the keyboard as well upon enter or hitting the magnifying glass?

even if we lose focus, it's doesn't work on Google chrome

**Comment by calexity** [comment]
@karlcow and I were talking about this bug last week. 

Scrolling to the first result would be great.  If you hit the magnifying glass, it already closes the keyboard.

Also, the designs here would condense the top section on mobile by half.  We could also flip where the search goes
https://github.com/webcompat/webcompat.com/issues/510#issuecomment-68192389
https://github.com/webcompat/webcompat.com/issues/510#issuecomment-69483924

**Comment by miketaylr** [comment]
Let's close this and purse the work in #510. :heart:
