### ISSUE TITLE
webcompat-bot created a internet label instead of IE

### ISSUE THREAD

**Issue by karlcow** [webcompat/webcompat.com#515]
It was in [this bug](https://github.com/webcompat/web-bugs/issues/566)

![webcompat bot label](https://cloud.githubusercontent.com/assets/505230/5549073/4686458c-8b81-11e4-985e-d4b0b315363d.png)

**Comment by miketaylr** [comment]
Thanks. We track issues for that @ https://github.com/webcompat/web-bugs-issue-tagger.
