### ISSUE TITLE
navigation in between issues destroys the list context

### ISSUE THREAD

**Issue by karlcow** [webcompat/webcompat.com#516]
1. Go to https://webcompat.com/issues (being logged)
2. Click Untriaged
3. Select "Oldest"
4. Click on the first issue. Add comments, etc.
5. Click on the back arrow near the issue title.

Expected: return to the previous state

Actual: back to the unfiltered initial issues list.

Maybe will be solved partly by #399.

**Comment by miketaylr** [comment]
Yeah, hopefully we can fix this in #399. Thanks for filing.

**Comment by XavierDelgado** [comment]
Issue seems fixed on Windows 8.1, with FF Nightly 37.0a1 (2015-01-12)

**Comment by miketaylr** [comment]
Fix deployed to master.
