### ISSUE TITLE
Url should open on a new tab in issues page

### ISSUE THREAD

**Issue by swarnava** [webcompat/webcompat.com#526]
As a contributor, when i am trying to visit a site from issue page to reproduce a problem, it should open the website url on a new tab instead of current tab.

**Comment by karlcow** [comment]
@swarnava Not sure about that. There is already Command + Click to open in a new tab. or with contextual menus.  I'm usually annoyed when a site decides for me when opening a new tab. I think there was usability studies about that. People being lost because of this behavior.

**Comment by karlcow** [comment]
Wondering what @calexity is thinking about it.

**Comment by miketaylr** [comment]
I think we should keep the default behavior for now. Thanks for the issue though @swarnava.
