### ISSUE TITLE
Take into account label needscontact in the code for untriaged

### ISSUE THREAD

**Issue by karlcow** [webcompat/webcompat.com#533]
The code to modify is at 
https://github.com/webcompat/webcompat.com/blob/f8d06cd84dea2d3a61b22a69eb2a1c1c06b47871/webcompat/issues.py#L65-L71

**Comment by karlcow** [comment]
``` python
def filter_untriaged(issues):
    '''Return the list of untriaged issues, encoded as JSON.

    "untriaged" means anything that isn't an issue with a "contactready",
    "sitewait", or "needsdiagnosis" label.
    '''
    def is_untriaged(issue):
        '''Filter function.'''
        match = True
        if issue.get('labels') == []:
            match = True
        else:
            for label in issue.get('labels'):
                if  'needsdiagnosis' in label.get('name'):
                    match = False
                elif 'needscontact' in label.get('name'):
                    match = False
                elif 'contactready' in label.get('name'):
                    match = False
                elif 'sitewait' in label.get('name'):
                    match = False
        return match

    return json.dumps([issue for issue in issues if is_untriaged(issue)])
```

Also this can probably be simplified.

**Comment by karlcow** [comment]
also /webcompat/api/endpoints.py in 
```
@api.route('/issues/search/<issue_category>')
def get_category_from_search(issue_category)
```

**Comment by karlcow** [comment]
category_list is defined in `endpoint` (twice) and in `issues` (once), that smells like bad code and prone to error. Maybe we should move this to a config file. 

Or maybe better if we re-categorize the labels with a namespace `wc-*`, we save some out-of-the-band list, and can just check if the label starts with the right namespace such as `label.startswith('wc-')`

**Comment by karlcow** [comment]
This still requires a test before making a pull request.

**Comment by miketaylr** [comment]
Hmm, I think we're going to find ourselves in a bit of a merge conflict with https://github.com/webcompat/webcompat.com/pull/531 (still waiting for merge... *cough* @magsout :p)

"untriaged" is getting renamed "new".
