### ISSUE TITLE
Double requests from the JS client for new issues

### ISSUE THREAD

**Issue by karlcow** [webcompat/webcompat.com#535]
When requesting the following URI: `https://webcompat.com/issues?new=1` **being logged out**, we request twice the JSON file of the issues at this URI `https://webcompat.com/api/issues/search/new?page=1&per_page=50`

![capture d ecran 2015-01-14 a 11 13 19](https://cloud.githubusercontent.com/assets/505230/5732999/2847811c-9bdf-11e4-8e25-ec2239954386.png)

**Comment by miketaylr** [comment]
Bummer, thought #542 would fix this (magically, I didn't try to fix it)--but it still happens on that branch. To investigate.

**Comment by karlcow** [comment]
@miketaylr do you know where it is happening in the code?

**Comment by miketaylr** [comment]
I haven't looked at this yet, will take a closer peek in the next day or so.

**Comment by miketaylr** [comment]
Actually, I think this is fixed now. Here's what I did:

0) open devtools, network panel selected
1) Navigate to localhost:5000/?stage=new
2) Observe requests

![screenshot](https://cldup.com/68_AIN9CI0-3000x3000.png)

Only a single JSON request.

I don't observe any difference for logged in or logged out.

**Comment by karlcow** [comment]
COOL! with the new code?

**Comment by miketaylr** [comment]
Yep. /me waves magic wand and pretends it was intentional.
