### ISSUE TITLE
filter is_new not working for logged-in case

### ISSUE THREAD

**Issue by karlcow** [webcompat/webcompat.com#536]
We have a difference of behavior between two states:
1. Being not logged, the "new" category is working properly.
2. Being logged in, the "new" category is not working and displays all values.

**Comment by miketaylr** [comment]
Can you test if "new/untriaged" was working before you refactored the filter?

**Comment by karlcow** [comment]
hmm wait. It is working now… weird.
Cache issue? ok I will close it.

**Comment by miketaylr** [comment]
That's good. :)

Perhaps time to revisit that cache busting all client-side scripts issue (too sleepy to dig up link now).
