### ISSUE TITLE
500 on filing a bug

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat.com#541]
Reported by @pepelsbey via twitter: https://twitter.com/pepelsbey_/status/555716405874950145

> @miketaylr, it seems there’s something wrong with @webcompat, I get 500 (broken glass sounds) while submitting bug :(

In uwsgi.log I see the following:

```
[pid: 24873|app: 0|req: 1867/1867] 91.203.97.247 () {48 vars in 1179 bytes} [Thu Jan 15 13:18:03 2015] POST / => generated 4900 bytes in 15 msecs (HTTP/1.1 500) 2 headers in 100 bytes (2 switches on core 0)
[pid: 24873|app: 0|req: 1881/1881] 91.203.97.247 () {48 vars in 1179 bytes} [Thu Jan 15 13:19:03 2015] POST / => generated 4900 bytes in 17 msecs (HTTP/1.1 500) 2 headers in 100 bytes (2 switches on core 0)
[pid: 24873|app: 0|req: 1882/1882] 91.203.97.247 () {48 vars in 1179 bytes} [Thu Jan 15 13:19:06 2015] POST / => generated 4900 bytes in 15 msecs (HTTP/1.1 500) 2 headers in 100 bytes (1 switches on core 0)
```

I'm guessing that was him. @pepelsbey - did you try to file the bugs anonymously or with your GitHub account?

I just deployed the latest master to staging and was able to file bugs anonymously and as myself. I can try a test issue on production... I'm not really sure what might have been up. Hopefully just a server hiccup. :confused: :question:

**Comment by pepelsbey** [comment]
I did it while logged in

**Comment by miketaylr** [comment]
Thanks. Will hunt around for a real bug to report as a test--shouldn't be hard. :)

**Comment by miketaylr** [comment]
Hrm... I just filed https://webcompat.com/issues/618 as myself without any issue. Unsure what the original issue was (possibly our Digital Ocean server), but I can't reproduce now.

**Comment by pepelsbey** [comment]
I tried three times with [#617](https://github.com/webcompat/web-bugs/issues/617), but then filed it via GitHub. Maybe I’m just lucky :) Feel free to close it, I’ll reopen it once I see it again.

**Comment by miketaylr** [comment]
OK, let's close. Please let me know if you see anything else fishy!
