### ISSUE TITLE
Issue title Removed text overflow ellipsis

### ISSUE THREAD

**Issue by magsout** [webcompat/webcompat.com#543]
Better to see all title (Two Line or more) than text overflow ellipsis

**Comment by magsout** [comment]
I think mobile, it is interesting to see issues like this (no ellipsis, and multi line if needed)? 
![title](https://cloud.githubusercontent.com/assets/1997108/5983465/eb94a816-a8cd-11e4-95d0-30a473de1a3b.png)


cc @karlcow @miketaylr

**Comment by karlcow** [comment]
Agreed with @magsout it's more readable. 
I would also evolve to something a bit different for the layout, maybe I should open a separate issue.

**Comment by karlcow** [comment]
Created #545 for more general layout comment.

**Comment by miketaylr** [comment]
+1.
