### ISSUE TITLE
Mozilla Websites

### ISSUE THREAD

**Issue by buluma** [webcompat/webcompat.com#544]
Hello

I've noted something with mozilla website. They are not loading stylesheet or more inaccessible 

http://fhr.cdn.mozilla.net/
https://developer.mozilla.org/en-US/
https://support.mozilla.org/en-US/get-involved?fpa=1

**Comment by karlcow** [comment]
@buluma Thanks for reporting.
Are you trying to report a bug about webcompat.com or are you trying to report a bug about Mozilla web sites? if it's about any Web sites, please head to  [Web Compat](https://webcompat.com/?open=1&url=http://example.org)

This repo is for bugs about the development of the webcompat Web site itself.

**Comment by karlcow** [comment]
I will close the bug. If you think it is about webcompat development, please describe the issue again.
