### ISSUE TITLE
Arrow to go back from an issue after navigation

### ISSUE THREAD

**Issue by karlcow** [webcompat/webcompat.com#546]
Steps to reproduce.

1. Go to http://webcompat.com/
2. Click on New issues. We reach [https://webcompat.com/issues?page=1&per_page=50&state=open&stage=new](https://webcompat.com/issues?page=1&per_page=50&state=open&stage=new)
3. Click on an issue. We land to something like this:
![webcompat](https://cloud.githubusercontent.com/assets/505230/6012440/846477b4-ab8b-11e4-9516-0d176aff880e.jpg)

What are your expectations with regards to the back arrow near the title of the issue. For me, it's mostly to come back to the step 2. The code is at:

```html
<a class="Issue-linkBack" href="/issues" title="All issues">
		  <span class="wc-sronly">All Issues</span>
          <span class="Issue-linkBack-icon wc-Icon wc-Icon--arrow-left" aria-hidden="true"></span>
        </a>
```

before we modify anything in the code. I wonder what are the expectations of others?

**Comment by tagawa** [comment]
Good point @karlcow - I'd expect it to go back to the filtered list of issues rather than all issues.

**Comment by magsout** [comment]
>Good point @karlcow - I'd expect it to go back to the filtered list of issues rather than all issues.


Yes, +1

**Comment by miketaylr** [comment]
Yeah, let's see if we can call history.back() and prevent the default action on the link--in theory that should work.
