### ISSUE TITLE
'g' in search string creates redirection

### ISSUE THREAD

**Issue by karlcow** [webcompat/webcompat.com#549]
So this one I'm not entirely sure but it seems I can reproduce.

1. Go to https://webcompat.com/ and login
2. Go to All issues
3. Search a string "ABCDEF", we get no results.
4. Try now "ABCDEFG".

Actual: 
It redirects to Github. Magical "G" :dancers: 
It is working with "ABCGDEF" too. :heart: 

Funny bug.

**Comment by miketaylr** [comment]
Ha, cool.
