### ISSUE TITLE
Email notifications about webcompat project

### ISSUE THREAD

**Issue by sesam** [webcompat/webcompat.com#55]
I'd like a field where I add myself to a mail list to get news about this project. After adding email, why not ask a yes/no question if I want a (persona!) login to simplify further interaction with your site. May fit in well with if you need to handle taking bug reports without requiring github account incl. readwrite access to all my repo:s, which I'd prefer not handing out.

**Comment by adamopenweb** [comment]
I think the experience for anonymous reporters could be improved with options for email notifications. I'm not disputing the privacy challenges @karlcow has mentioned, I agree with them.

I think it's fair to say that anonymous reporters begin their process with a website issue. They are likely at the point of wanting to take action but not sure how exactly. This part is fuzzy, but somehow they come across webcompat.com (possibly through search, [see screenshot](https://github.com/webcompat/web-bugs/issues/2624)). Once the issue has been reported, the process for getting updated is manual. They would need to record the bug link somehow and remember to check on it. 

Sometimes people report good bugs and we begin to work on them very quickly. Except for weekends, our initial triage is pretty quick. This is a good opportunity to let the user know they made a difference and update them along with the process. If they feel rewarded, they might be open to learning what a compatibility bug is and repeat the process. The sooner they see progress, the more likely they will be to stay engaged (I've heard).

**Comment by miketaylr** [comment]
We decided this isn't something we have the bandwidth to take on right now.
