### ISSUE TITLE
Installation script for labels in a test github repo

### ISSUE THREAD

**Issue by karlcow** [webcompat/webcompat.com#557]
This is related to #436 
Currently someone who want to hack on the project would have to create by hand all the labels.
It has a couple of consequences:
* cumbersome
* prone to errors
* not easy for first timers

We may want to create an initialization script for it.

**Comment by miketaylr** [comment]
:100:

**Comment by miketaylr** [comment]
To accomplish this there would probably be a few steps involved:

* Create a script that will add the following labels (via the GitHub API) to an arbitrary repo: https://github.com/webcompat/webcompat-tests/issues/labels

* Add documentation

We have some code at https://github.com/webcompat/issue-importer which adds labels to issues if that's helpful to look at, and these docs cover the issue labels API https://developer.github.com/v3/issues/labels/

**Comment by miketaylr** [comment]
Bonus points for not hard-coding the labels to be added, but fetching them from the webcompat-tests repo via GitHub's API.

**Comment by dshgna** [comment]
@miketaylr I think it may be a good idea if the user had the option to pre-populate the repo with some existing issues. What do you think?

**Comment by karlcow** [comment]
@dshgna Open a new issue about it :)

**Comment by karlcow** [comment]
@dshgna when you have fixed the comments issue I'm giving it a r+
Thanks for the hard work.

Then we need to solve this issue I just created and we can put your script at an appropriate place.
https://github.com/webcompat/webcompat.com/issues/965
