### ISSUE TITLE
Way to browse issues submitted by me

### ISSUE THREAD

**Issue by tagawa** [webcompat/webcompat.com#560]
There's a source code comment that says the "Submitted by Me" section on the front page will be scrollable. Is this the best solution or should we consider making "Submitted by Me" a link to a new page displaying the user's issues? That could then be the foundation for future development into the custom issue dashboard proposed in #442.

**Comment by karlcow** [comment]
Related to  #55 and all things which requires a unique profile system.

**Comment by tagawa** [comment]
I can't see the connection - wrong issue number maybe?

**Comment by karlcow** [comment]
Both are calling for personalization and tracking. 

It's a set of very interesting feature on how one person can track his/her own bugs. Be the one they submitted or the one they chose to follow or be interested by. 

It has also challenges in terms of privacy and state management. The submitted by me is one of the low hanging fruits if we take into account that only "github logins" count as the tracking system. 

@tagawa what would you like to see in that page submitted by me? What would be useful into it?

**Comment by tagawa** [comment]
Ah, I see. That seems like a larger scope than what I was thinking.

My use case is that today I wanted to find a particular bug I filed a few months ago. I couldn't remember the issue name for searching so I tried to browse my old bugs, but the front page only shows a maximum of six. I was going to create a "My Issues" page that is linked from the "Submitted by Me" text, but then saw a comment saying the front page "Submitted by Me" section will be scrollable at some point.

I created this issue to discuss whether we should implement either of these approaches.

**Comment by karlcow** [comment]
heh. It seems we have difficulty to understand each other. I'm failing to explain.
* The scope of your issue seems clear.
* I added a comment to link contexts, dots, in between issues. So when we are discussing the other one, we remember this one.
* You asked more details so I gave input. I'm not saying this issue is not what you are saying it is. :D :) 

You basically want a view with the information [Created by](https://github.com/webcompat/web-bugs/issues/created_by/tagawa).

**Comment by tagawa** [comment]
Thanks - got it now!

Yes, that's exactly the kind of view I was thinking of, but I'm not sure whether it's better as a page on its own or as a scrollable section on the front page (a more powerful version of the current Submitted by Me section).

**Comment by miketaylr** [comment]
@tagawa is this what you're looking for? Note you have to be logged in to get that option.

![](https://cldup.com/nE68qhn0VN-3000x3000.png)

**Comment by miketaylr** [comment]
I just realized that "Submitted by Me" isn't a link, while the rest of the headers on the homepage are. We could fix that easily. Maybe we could make it even more obvious by having a "see more" link floated to the right or something?

**Comment by tagawa** [comment]
@miketaylr, yes, that link in the dropdown menu that already exists is exactly what I wanted. D'oh!

I also expected the "Submitted by Me" to be a link, so glad to see PR #561, but having them underlined would be better IMO to show they're clickable.

**Comment by tagawa** [comment]
Closing this and opening #562 to address the link appearance point.
