### ISSUE TITLE
Make issue heading links on front page more obvious

### ISSUE THREAD

**Issue by tagawa** [webcompat/webcompat.com#562]
It's not very clear that the section headings can be clicked, e.g. "Submitted by Me": 
![68747470733a2f2f636c6475702e636f6d2f734d524d697677374a4f2d3330303078333030302e706e67](https://cloud.githubusercontent.com/assets/94173/6199431/91ebc262-b486-11e4-8860-f00bcf9545d8.png)

Perhaps they should be underlined or have some other indicator (arrow, "see more", etc.).

**Comment by magsout** [comment]
Maybe add a link under list like : `see more`  ?

**Comment by miketaylr** [comment]
Yeah, I like the idea of a "see more" link. There's already so many underlines in this area, a linked header is less obvious. Possibly floated to the right of the header itself? Or maybe under looks better.

**Comment by magsout** [comment]
let's finished that issue https://github.com/webcompat/webcompat.com/issues/571 to see if I'll add link  or not .

**Comment by miketaylr** [comment]
These got removed, so let's close.
