### ISSUE TITLE
the search feature is hidden and not obvious

### ISSUE THREAD

**Issue by globau** [webcompat/webcompat.com#563]
it took me a while to find webcompat's search feature. a less persistent person would have closed the tab.

as i understand it, in order to search you need to be logged in and viewing the "all issues" page.  neither of these actions are discoverable.

i see that searching is limited to authenticated users due to github api rate limiting issues, which sucks but that's i guess the price of sitting atop a system which you don't control :(

i suggest always adding the search widget to the front page, and if you're not logged in displaying instructions which indicate that you need to do so before you can search.

**Comment by karlcow** [comment]
@globau Yes it's a good grief.  I have myself sometimes to remember it… and I'm one of the coder of the site. :black_joker: We need to find a better way.

**Comment by miketaylr** [comment]
Yeah, we could do a better job here for sure.

**Comment by tagawa** [comment]
Agree, and in addition consider making the form a bit more obvious - in particular the text box blends in to the background so well and is so far from the magnifying glass button (on desktop) I occasionally forget it's there.

**Comment by calexity** [comment]
Adding notes from talking with @karlcow 

- Let's always show the search functionality and add some clear messaging that you need to log in

I will work on a design

**Comment by miketaylr** [comment]
Based on the work we did in #639, I think we can do another option:

If the user is not logged in, they can do 10 search queries per minute from the client before running into problems. So, we do this and if they hit the limit, we display message asking them to log in to search more.

This shouldn't be a ton of work.

**Comment by miketaylr** [comment]
To be clear, this is basically the plan of:
>    Let's always show the search functionality and add some clear messaging that you need to log in

With the tweak that search will mostly work unless you're doing a LOT of searches. At that point, we'll show the log in message.

**Comment by miketaylr** [comment]
I started working on this over the weekend and hope to get it finished this week at some point.

As mentioned before, we're going to display search by default (for all users) and if they're logged in, they get a higher rate limit. If not logged in, they send the search request from their machine and get a lower rate limit. 

TODO:

- [ ] display a message prompting people to log in if they hit the limit
- [ ] possibly write the reverse of https://github.com/webcompat/webcompat.com/blob/master/webcompat/static/js/lib/models/issue.js#L231 so we don't push garbage to the URL bar.

**Comment by miketaylr** [comment]
Okey doke, getting closer. Still need error handling message for hitting the limit and tests. But this works now (knock on :christmas_tree: :deciduous_tree: :evergreen_tree:).

**Comment by karlcow** [comment]
Discussed in Paris September 2015. 
* Needs rate limit handling
* Needs tests

Probably finished before the end of this week.
