### ISSUE TITLE
Unable to go back from Issues page

### ISSUE THREAD

**Issue by tagawa** [webcompat/webcompat.com#564]
### Steps to reproduce ###
1. Go to https://webcompat.com
2. Click on "New Issues" to open that page
3. Click the browser's back button

### What should happen ###
The webcompat.com front page should be displayed.

### What actually happens ###
Nothing. The spinner appears briefly but that's it. No error message in the console. Tried in Firefox and Blink/WebKit browsers.

**Comment by miketaylr** [comment]
Oops, will fix!

**Comment by miketaylr** [comment]
I think I thought of a way to (more easily) fix this the other night... it's a bit more complicated than I was hoping. The current problem is basically calling pushState twice on updateURLParams (IIRC, it was last week that I dug in), so when you go back it updates and you've got an extra state ahead of you and then you go back and you've got an extra...

**Comment by miketaylr** [comment]
So I've done a bunch of poking around here and managed to fix the bug as reported--but I maybe broke a few things to ge there. 

I've added the concept of `stage=all`, which lets us simplify things a bit. Also removed a bunch of redundant calls to `updateURLParams` and `updateModelParams`.

Things I want to fix before merging this in:

- [ ] `q` params should be shown in the URL bar when a search is active.
- [ ] going back and forth between a state filter and non-state filter should reliably update results. Right now it's iffy and I don't understand why.

The moral of the story is managing history by yourself sucks. It would be way simpler (for me :smiling_imp: :) to use `replaceState` for everything, but then you couldn't go back from "show newest" to "show oldest" with the back button, for example. It would just kick you to the last page and that would suck.

**Comment by miketaylr** [comment]
OK, I think I have this fixed now.
