### ISSUE TITLE
Report new issue from /issues page?

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat.com#565]
I received an email about someone being confused how to report a bug from /issues. Should we make this possible?

**Comment by karlcow** [comment]
@miketaylr The form is not obvious on the front page and there's no easy way to find out how to report new issues. It is somehow related to #317

**Comment by miketaylr** [comment]
I don't know if I agree with "The form is not obvious on the front page"--we've never received any feedback like that, but I think we could add a Report New Issue to the global header or footer (or wherever it makes sense).

**Comment by tagawa** [comment]
+1 to adding something to the header. We should probably keep the naming consistent with the front page so a "Report bug" item next to "All issues" at the top right, for example.

**Comment by miketaylr** [comment]
The quickest fix would be `<a href="/?open=1">`. The better fix would be fix #317, and then maybe we can get crazy with modals or something (or not :8ball:).

**Comment by tagawa** [comment]
Quick 'n' simple FTW!

**Comment by miketaylr** [comment]
Thanks to @tagawa, this is fixed and deployed now.
