### ISSUE TITLE
Enhancement: Search button on Home page of Webcompat

### ISSUE THREAD

**Issue by girishdakhare** [webcompat/webcompat.com#566]
Is it possible to provide search button/field on Home page of Webcompat?

Search button is required on home page to check whether bug which we are going to add is already present or not.

Please check attachment.

![search button webcompat home page](https://cloud.githubusercontent.com/assets/11094743/6365230/80c8693a-bcd9-11e4-8217-e3acb18dc155.JPG)

**Comment by karlcow** [comment]
@girishdakhare Thanks for the issue report.
This discussion has already started in #563

**Comment by miketaylr** [comment]
Hey @girishdakhare. We do have search, but it's at webcompat.com/issues and only appears if you log in. But this isn't obvious to everyone, so we need to make it better. :)

**Comment by girishdakhare** [comment]
Hi Mike,

Thanks for reply.

How are you?

Thanks & Regards, 
Girish 

-----Original Message-----
