### ISSUE TITLE
Back button doesn't work on the detail of an issue

### ISSUE THREAD

**Issue by magsout** [webcompat/webcompat.com#569]
1) go to https://webcompat.com/issues/734
2) click on back button

-> the back button does not work

**Comment by miketaylr** [comment]
Hmm, I can't reproduce this one. If I go to https://webcompat.com/issues/734 and hit back, I come back here. If I go to https://webcompat.com/issues, and click on an issue both my browser back button and the back arrow work.

But I can reproduce #564.

**Comment by magsout** [comment]
if you go to https://webcompat.com/issues?page=1&per_page=50&state=open, open one issue in new tab and click on back button ?

**Comment by miketaylr** [comment]
Ah. *In a new tab*.

Yeah, can fix that. So the browser back button won't work, but we can make the arrow button work. Is that what you mean?

**Comment by magsout** [comment]
my bad, sorry, I'm talking about our back button 
![capture d ecran 2015-02-26 a 22 12 27](https://cloud.githubusercontent.com/assets/1997108/6402005/986094b0-be04-11e4-88f7-083fc29c7408.png)

**Comment by miketaylr** [comment]
Cool, yeah. This is an easier fix than #564. :p

**Comment by zoepage** [comment]
Not sure, if it's a bug, but it feels like one. 

When I go to "report a bug" and hit the back button, I'll end up on the list of all bugs.
I understand why it is a good thing to push contributors to the list, so they can explore and help out. But this is confusing for new contributors, who are looking around. 

Also, on the "view all" list, it toggles the labels. Not sure, if this is an expected behavior?

**Comment by karlcow** [comment]
@zoepage this seems to be two different bugs. My impression is that you need to open two bugs with the steps to reproduce.

**Comment by zoepage** [comment]
#1287  for back button.

Before I open the one on the toggling labels, is this an expected behavior?
1. Label / filter is activated in "view all" list
2. push back button
3. Label / filter is deactivated
4. push back button
5. Label / filter is activated
...

**Comment by karlcow** [comment]
@zoepage Could you start with a fresh window. And explain by providing the URI and the actions. I'm not sure what you are doing. :) I don't reproduce what you are saying, but I maybe do something wrong.

**Comment by zoepage** [comment]
@karlcow 
1. webcompat.com -> scroll down to "Join The Team".
2. Click on either "diagnose bugs" or "reach out to sites"
3. push back button
4. Label / filter is deactivated
5. push back button
6. Label / filter is activated
7. ...

**Comment by karlcow** [comment]
Ahah! This is a bug. 💯 Thanks @zoepage Open it with the steps to reproduce. 
The back button should come back to the home page.

**Comment by zoepage** [comment]
Will do. Thanks @karlcow :)
