### ISSUE TITLE
"G takes you to github..." on mobile

### ISSUE THREAD

**Issue by calexity** [webcompat/webcompat.com#572]
On the All Issues page -

I think we should link this message to Github rather than confusing people.
Possibly should do the same on Desktop. Either type g or just click the link.

Thoughts @karlcow @miketaylr @magsout

**Comment by tagawa** [comment]
Agree re. the link.

And I notice now we don't have a similar message on individual issue pages but I think we should.

**Comment by calexity** [comment]
Yes, second that. Thanks @tagawa

**Comment by miketaylr** [comment]
Yeah, that's pretty goofy. Thanks for catching that @calexity/@tagawa.

**Comment by miketaylr** [comment]
Ah, forgot about this issue: https://github.com/webcompat/webcompat.com/issues/449#issuecomment-66548365

Looks a little goofy. Should we just left align it and call it a day?

**Comment by tagawa** [comment]
I'll defer to @calexity's design sense.

**Comment by calexity** [comment]
I thought I responded to this, and it looks closed, but I think left-align or center-align should be fine, if it's still an open question.

**Comment by miketaylr** [comment]
You have have @calexity -- sorry if I missed that. I'll pick left or center and we can deploy the fix today.
