### ISSUE TITLE
Drop the original message part when someone is replying through email

### ISSUE THREAD

**Issue by karlcow** [webcompat/webcompat.com#575]
1. Go to https://webcompat.com/issues/751

Notice some of the messages have the full mail attached. This is happening when someone is replying to the bug by mail.

Proposal:

Drop everything after and including `-----Original Message-----`.

**Comment by magsout** [comment]
good idea

**Comment by miketaylr** [comment]
Ew, yes. Looks bad.

**Comment by miketaylr** [comment]
@haseebgit is going to tackle this. Feel free to ask any and all questions in here.

**Comment by tsah20** [comment]
@miketaylr Which file I am supposed to refer for this bug?

**Comment by tsah20** [comment]
Need help  How should I approach this one?

**Comment by miketaylr** [comment]
(unassigning @haseebgit because AFAIK he's not working on this).

**Comment by miketaylr** [comment]
Hmm, there's a few ways you might be able to do this one (probably more!)

One approach would be to write a `md` plugin or extension similar to this `linkify` code: https://github.com/webcompat/webcompat.com/blob/master/webcompat/static/js/lib/issues.js#L16

That would involve getting pretty familiar with the markdown lib we use to parse comment data with: https://github.com/webcompat/webcompat.com/blob/master/webcompat/static/js/vendor/markdown-it.js

The other way would be to do something similar to how we have to hide HTML comments ourselves in the (comment) BodyView render method: https://github.com/webcompat/webcompat.com/blob/master/webcompat/static/js/lib/issues.js#L140. Basically, find everything after the "Original Message" part that @karlcow mentioned in the first comment of this bug.

See https://webcompat.com/issues/751#issuecomment-77093841 for an example.

**Comment by karlcow** [comment]
Note: These messages are not going through webcompat (it's users replying to the github notifications by email). So we can't handle them only after the fact.

@miketaylr gave two suggestions already.

A third approach to have webhook on comments 
https://developer.github.com/webhooks/
https://developer.github.com/v3/activity/events/types/#issuecommentevent

That check if the comment contains the string and when it is detected.
Then send a PATCH on this comment to remove the original message part
https://developer.github.com/v3/issues/comments/#edit-a-comment

**Comment by hallvors** [comment]
There is also the possibility of having a hook for new comments and physically remove the text.. But we'd risk some data loss of course. (Oops - I see Karl already said that).

This isn't hard to do from JS - one suggestion would be to go through all DIV elements with class ``wc-Comment-content js-Comment-content``, check their P children and find the first one, if any, whose text content starts with the ``Original message`` (or similar) string. Bonus points for wrapping that and all subsequent P tags in a DETAILS element :)

One problem though: where does that "Original message" string come from? Is it Karl's mail program (in which case there will be thousands of variations..) or is it GitHub?

**Comment by miketaylr** [comment]
> One problem though: where does that "Original message" string come from? Is it Karl's mail program (in which case there will be thousands of variations..) or is it GitHub?

Hmm, good question. We would probably want to test replying to a GitHub notification from a few different email clients to check. Mail.app, Thunderbird, Gmail, Yahoo, etc.

**Comment by karlcow** [comment]
It's GitHub.

**Comment by karlcow** [comment]
Test from Mail.app

> Le 10 mars 2016 à 00:40, Mike Taylor <notifications@github.com> a écrit :
> 
> One problem though: where does that "Original message" string come from? Is it Karl's mail program (in which case there will be thousands of variations..) or is it GitHub?
> 
> Hmm, good question. We would probably want to test replying to a GitHub notification from a few different email clients to check. Mail.app, Thunderbird, Gmail, Yahoo, etc.
> 
> —
> Reply to this email directly or view it on GitHub.
> 

-- 
Karl Dubost 🐄
http://www.la-grange.net/karl/

**Comment by karlcow** [comment]
ok just replied to github. The Original Message string is gmail :dancer:

**Comment by karlcow** [comment]
Editing the comment. The markup is 

```
Test from Mail.app

> Le 10 mars 2016 à 00:40, Mike Taylor <notifications@github.com> a écrit :
> 
> One problem though: where does that "Original message" string come from? Is it Karl's mail program (in which case there will be thousands of variations..) or is it GitHub?
> 
> Hmm, good question. We would probably want to test replying to a GitHub notification from a few different email clients to check. Mail.app, Thunderbird, Gmail, Yahoo, etc.
> 
> —
> Reply to this email directly or view it on GitHub.
> 

-- 
Karl Dubost 🐄
http://www.la-grange.net/karl/

```

So basically no way to be sure it's a mail or a comment. Except if github knows and tells us in the body. Let's see.

```html
<div class="comment-body markdown-body email-format js-comment-body">
          <div class="email-fragment">Test from Mail.app</div>
<span class="email-hidden-toggle"><a href="#">…</a></span><div class="email-hidden-reply" style="display: block;">
<div class="email-quoted-reply"> Le 10 mars 2016 à 00:40, Mike Taylor &lt;notifications@github.com&gt; a écrit :

 One problem though: where does that "Original message" string come from? Is it Karl's mail program (in which case there will be thousands of variations..) or is it GitHub?

 Hmm, good question. We would probably want to test replying to a GitHub notification from a few different email clients to check. Mail.app, Thunderbird, Gmail, Yahoo, etc.

 —
 Reply to this email directly or view it on GitHub.
</div>
<div class="email-fragment"></div>
<div class="email-signature-reply">-- 
Karl Dubost <g-emoji alias="cow2" fallback-src="https://assets-cdn.github.com/images/icons/emoji/unicode/1f404.png">🐄</g-emoji>
<a href="http://www.la-grange.net/karl/">http://www.la-grange.net/karl/</a>
</div>
</div>
      </div>
```

so github knows this is coming from an email. :) I wonder if this information is given into the json.

**Comment by hallvors** [comment]
It's not in the JSON.. :-/

**Comment by karlcow** [comment]
Let's kill this. We can't do anything with the current way that GitHub sends this data. Too many unknowns.
