### ISSUE TITLE
Bottom links of webcompat home page go to github

### ISSUE THREAD

**Issue by karlcow** [webcompat/webcompat.com#576]
We need to fix these 3 links at the bottom, they go to github instead of webcompat.com :)

![capture d ecran 2015-03-06 a 09 19 29](https://cloud.githubusercontent.com/assets/505230/6517824/458327a6-c3e2-11e4-907f-8b4be013ba63.png)

**Comment by magsout** [comment]
Align middle:

![align-middle](https://cloud.githubusercontent.com/assets/1997108/6545692/338b0966-c594-11e4-8efa-48904691e935.png)


Or align bottom: 

![align-bottom](https://cloud.githubusercontent.com/assets/1997108/6545693/3845cde2-c594-11e4-9509-334d509451a3.png)

**Comment by karlcow** [comment]
@magsout I'm talking about the actual link when we click. ^_^

About the image itself (separate issue) The align middle seems better.

**Comment by magsout** [comment]
Ouch I need to sleep ....

**Comment by miketaylr** [comment]
> Ouch I need to sleep ....

Nah.... :coffee: :p
