### ISSUE TITLE
Check the dependencies before starting the server

### ISSUE THREAD

**Issue by karlcow** [webcompat/webcompat.com#583]
Sometimes we change the modules, etc. For example,

```
-WTForms==1.0.5
+WTForms==2.0.2
```

I wonder if we should add a checker before run. Where we would get a pseudo UI like:

```
python run.py

** You need first to update your python/js before starting webcompat.com
@@Instructions to do so@@
```

On the python side, probably something with `pip install --no-install`
or making a diff in between libraries installed and the ones in requirements.txt

For JavaScript, I don't know how it is checked. 
Also when do you need to run again grunt.

**Comment by karlcow** [comment]
See also in #581
`do not forget to do : npm install cc @karlcow @tagawa @calexity `

**Comment by tagawa** [comment]
+1

**Comment by miketaylr** [comment]
> For JavaScript, I don't know how it is checked. 

I don't think starting the application server should know or care about build-time (which is all we use npm/grunt for) dependencies. If we do anything for that, it should happen at the make/grunt level.

>  Also when do you need to run again grunt.

You could write a grunt task for this, there might even be a module out there already. As for when to run grunt, just run `grunt watch`  or `make watch` while developing. No need to re-run it. 

 e0a4aa6 is a simple take on pip dependencies, using a difference set.

**Comment by miketaylr** [comment]
Here we go: https://www.npmjs.com/package/grunt-check-dependencies. Let's open a new bug for that.

**Comment by miketaylr** [comment]
cf #587.

**Comment by karlcow** [comment]
> I don't think starting the application server should know or care about build-time (which is all we use npm/grunt for) dependencies. 

Note that it is about discovering that there is something missing or that we need to rerun. Think about it as deploying locally for running. So indeed it is possible it's not the right place. No issue with that. It might be good to put it at another place. Maybe I should just create an alias for myself which does it. Or create my own script which doesn't impact the project. 

> `grunt watch`

It doesn't do what I want.

```
(webcompatcom)08:32:03 ~/code/webcompat.com
→ grunt watch
Running "watch" task
Waiting...
```

Still waiting. Not sure what it does. 

It doesn't tell me that something has changed and I should run something. It has happened already more than 3 times, that I just type `make` and it recompiles and installs everything with a nice blank `config.py`. Yes I'm a bit dumb :japanese_ogre: And I'm trying to usually put destroying actions behind flags and have the default being more secure. 

I will find a solution.

**Comment by miketaylr** [comment]
> It doesn't do what I want.

@karlcow what do you want it to do? I think I got confused by your description of having to re-run grunt.

We use grunt to do a few things, the only really useful thing for development/local server is re-compiling the CSS and running jshint. That's what `grunt watch` is for.  When it says "Waiting...", it's watching for local changes to CSS files. As soon as it detects one, it will re-run the cssnext task (which concatenates the development CSS). If there was a change in JS, it runs jshint, etc.

> It doesn't tell me that something has changed and I should run something.

#587 will fix that, I'll take a stab at that today or tomorrow.
