### ISSUE TITLE
Webcompat comments have no styles for list items.

### ISSUE THREAD

**Issue by karlcow** [webcompat/webcompat.com#588]
Lists are difficult to read because they are not styled. 

![capture d ecran 2015-03-10 a 10 35 21](https://cloud.githubusercontent.com/assets/505230/6567813/65d6b586-c711-11e4-891e-c5ff8f312667.png)

**Comment by miketaylr** [comment]
http://staging.webcompat.com/issues/252 is an example of this. We have the correct li structure, just missing a useful style for it.
