### ISSUE TITLE
"Report via GitHub" could display username.

### ISSUE THREAD

**Issue by karlcow** [webcompat/webcompat.com#589]
When opening a new bug: I get two choices whatever my status being logged or not. 

![capture d ecran 2015-03-10 a 09 29 01](https://cloud.githubusercontent.com/assets/505230/6567834/8dfd6f1e-c711-11e4-9304-040593da5549.png)

"Report Anonymously" seems fine. Maybe two choices:
* When logged in: "Report as [username]"
* When not logged: "Report (via login)" or something better.

The goal is to encourage login for being able to have a discussion when information is missing. To keep anonymous is important even when logged in. Some people might not want their name associated with some Web sites. That's a cool feature.

**Comment by miketaylr** [comment]
I like "Report as miketaylr" when we know the username, but if we change `Report via Github` for non-logged in users it should somehow still communicate that GitHub is the service that will be used. Maybe `Report via GitHub (login)`? Or maybe that's even worse.

**Comment by magsout** [comment]
Yes, good idea @karlcow 

- Report as magsout  (logged)
- Report via Github (not logged)

Seems good to me. I agree with @miketaylr , it is necessary to leave written github

**Comment by karlcow** [comment]
Let's do that.
