### ISSUE TITLE
HTTP Caching is broken on webcompat.com

### ISSUE THREAD

**Issue by karlcow** [webcompat/webcompat.com#590]
We must have made a modification at a point which has broken our cache. We need to figure it out :)
So far just a preview. I tried to navigate a bit more and I get only "200" except for github and google which are sending the right things for their own parts independent of webcompat. 

![issues-cache](https://cloud.githubusercontent.com/assets/505230/6570035/116c7762-c737-11e4-9bde-886790beaaa5.jpg)

Let's try with 773
* html `/issues/773` No Etag sent by the server, no caching information.
So the second time we hit it it does the same thing again.

Hmm… I wonder if we butchered all of that when we decided to put under https?

**Comment by miketaylr** [comment]
Yep, only CSS is cached on re-loads for me. That's busted.

![screen shot 2015-03-10 at 09 55 28](https://cloud.githubusercontent.com/assets/67283/6577397/c026b046-c70b-11e4-9cb7-18a9538174f9.png)

**Comment by miketaylr** [comment]
OK, so that's not necessarily true. Re-testing again I get 304s except for 779.json. We should be able to fix that.

![39als3nck3-3000x3000](https://cloud.githubusercontent.com/assets/67283/6582612/6c3b8f30-c72c-11e4-828c-a090063019f8.png)

**Comment by miketaylr** [comment]
It looks like the source of the bug is we only do conditional GET for logged in users. If I log in, I get a 304 on 779.json on the 2nd time.

So the fix would be to incorporate `get_request_headers` into `proxy_request`.

**Comment by miketaylr** [comment]
OK in theory that's supposed to be happening here: https://github.com/webcompat/webcompat.com/blob/master/webcompat/issues.py#L31

**Comment by miketaylr** [comment]
Ah, I think I see the bug. `headers` is not the `headers` we think it is. :)

**Comment by karlcow** [comment]
@miketaylr did a good job for the JSON part. We need to fix the caching story for HTML too. 
I have opened #609
