### ISSUE TITLE
Switch back to Issues API for issue categories

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat.com#592]
https://github.com/webcompat/webcompat.com/blob/master/webcompat/api/endpoints.py#L187-L190

GitHub fixed their bug :balloon::
> Just wanted to let you know that the team finally squashed that bug -- pagination links should now be included as expected when listing issues, even when a labels filter is present.

**Comment by karlcow** [comment]
oh! :joy: :fireworks:

**Comment by miketaylr** [comment]
Once #603 lands, I'll work on this.
