### ISSUE TITLE
tagging an issue from the list should happen once the window is closed

### ISSUE THREAD

**Issue by karlcow** [webcompat/webcompat.com#595]
1. Go to an issue
2. Select one or two tags

Actual: Tagging is happening right away as soon as we click the checkbox in the pop up window
Expected: Tagging should happen once leaving the pop up window.

Why: If we make mistakes in checking the boxes and changes while still in the pop up window, there is a dance of tagging happening in the history of the bug.

**Comment by miketaylr** [comment]
I agree.

**Comment by miketaylr** [comment]
Also a good opportunity to start on #272.

**Comment by miketaylr** [comment]
(just testing how github behaves here)

**Comment by miketaylr** [comment]
@karlcow just so I understand, we shouldn't update the UI with the labels that someone has picked until they Save/close the editor?

Right now we [add/remove a label to the UI as soon as it is checked/unchecked](https://github.com/webcompat/webcompat.com/blob/master/webcompat/static/js/lib/labels.js#L127), but don't send it to GitHub until the [editor is closed](https://github.com/webcompat/webcompat.com/blob/master/webcompat/static/js/lib/labels.js#L145).

I'm not attached to either behavior, so we can change it to only update UI when we send it to GitHub if you think that's a better model.

**Comment by karlcow** [comment]
Ah! I guess I got confused by the UI of webcompat.com.
So I guess it's fine. Maybe yes not showing it in the UI until we close the UI.

**Comment by karlcow** [comment]
Let's close it for now. Other priorities. And I will reopen that bug, when I'm in front of the same pattern which troubled me.

**Comment by miketaylr** [comment]
OK, thanks!
