### ISSUE TITLE
Domain names feed for getting notifications of new issues

### ISSUE THREAD

**Issue by tobiastom** [webcompat/webcompat.com#60]
It would be awesome for site owner if I could register on the project, specify to which sites I'm responsible (including a verification), and then get notified once someone posts an issue about one of the sites.

Currently I have to go back to the project each and every time and check if someone might have created an issue. I don't assume many people will do that…

**Comment by hallvors** [comment]
I think we should have both E-mail subscription ("send me an E-mail if there's an issue for site x") and RSS. Maybe those should be separate bugs.

**Comment by miketaylr** [comment]
cc @deepthivenkat

**Comment by miketaylr** [comment]
We can include a `<link rel=alternate>` in the head of the page that lists the domains, e.g.,`<link rel="alternate" type="application/atom+xml" href="http://www.la-grange.net/feed.atom">` and this will allow feed readers/software to subscribe. See http://microformats.org/wiki/rel-alternate

**Comment by miketaylr** [comment]
We can create a route like `https://webcompat.com/feeds/facebook.com` that shows the list of related issues, etc.

**Comment by tobiastom** [comment]
@miketaylr That would be awesome.

**Comment by miketaylr** [comment]
Let's close this in favor of #132.
