### ISSUE TITLE
return of the wyciwyg

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat.com#600]
Originally was in web-bugs 831 (not linking to create noise) as `wyciwyg://0/http://bbs.csdn.net/topics/20282413`. I just went to the site and it reproduces when I click Report Site Issue: http://bbs.csdn.net/topics/20282413.

**Comment by miketaylr** [comment]
Uh ok, our Regex is looking for wysiwyg instead of wyciwyg.So yeah, I never fixed this. :disappointed:

**Comment by karlcow** [comment]
:heart: at "I never fixed this".
