### ISSUE TITLE
Swap out marked.js for markdown-it

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat.com#604]
See https://github.com/markdown-it/markdown-it. Actively maintained and has a plugin architecture. :+1:

**Comment by miketaylr** [comment]
TODO 

- [ ] configure `langPrefix` so syntax highlighting still works
- [ ] emoji plugin https://www.npmjs.com/package/markdown-it-emoji
- [ ] sanitizer plugin https://www.npmjs.com/package/markdown-it-sanitizer

investigate https://www.npmjs.com/package/markdown-it-hashtag as a hackable replacement for issue linking, or possibly https://www.npmjs.com/package/markdown-it-for-inline.

**Comment by miketaylr** [comment]
Sweet, this markdown parser is already so much nicer.

**Comment by miketaylr** [comment]
So the way this thing deals with emoji is to map to the real unicode emoji codepoint. So that leaves out some older browsers. See https://github.com/webcompat/webcompat.com/issues/260#issuecomment-90267646 for the plan on how I think we should proceed (tl;dr, if someone complains about lack of support in older browsers, we add in support for serving images).

**Comment by karlcow** [comment]
> So the way this thing deals with emoji is to map to the real unicode emoji codepoint.

Instant love. ;) I think it's fine to avoid image overload. 
Talking about feature detections vs user agent sniffing. How do you detect in a code if you can send a unicode point or an image. :hurtrealbad:

**Comment by karlcow** [comment]
Hmm i guess by testing if the value returns the generic character

``` js
String.fromCharCode(0x1F6C8) 
```

will return a generic icon for missing character (maybe different depending on the browsers).
hmmm…

**Comment by karlcow** [comment]
holy :cow: http://stimulus.hk/demos/testFont.html  (Check the source code)

**Comment by miketaylr** [comment]
I wonder if @mathiasbynens hasn't solved this problem before...

**Comment by mathiasbynens** [comment]
Well there’s https://github.com/Modernizr/Modernizr/blob/master/feature-detects/emoji.js which detects if an emoji renders as expected or not. You could do something similar for other characters.

**Comment by mathiasbynens** [comment]
Ah, that’s basically what http://stimulus.hk/demos/testFont.html (which @karlcow already mentioned) does. So there!

**Comment by miketaylr** [comment]
thx!
