### ISSUE TITLE
script loops when trying to render issue 1074

### ISSUE THREAD

**Issue by hallvors** [webcompat/webcompat.com#614]
https://webcompat.com/issues/1074 seems to send some part of our JS (the Prism highlighter/tokenizer?) into a never-ending loop, causing a "slow script" dialog.

If there's a newer version of Prism we can try upgrading - else we need to dig into the tokenizer logic. I'm happy to do that :)

**Comment by karlcow** [comment]
Wondering if it's because of the opening brace which is not closed. That would be a funny bug.

**Comment by hallvors** [comment]
The cause here is actually a regexp used to look for a closing tag. The DIV tag in my comment isn't closed, and processing this regular expression will never finish:
/<\/?[\w:-]+\s*(?:\s+[\w:-]+(?:=(?:("|')(\\?[\w\W])*?\1|[^\s'">=]+))?\s*)*\/?>/gi

**Comment by hallvors** [comment]
(And it's not Firefox's fault - this thing fails in all browsers. Too many lookaheads, I guess..)

**Comment by miketaylr** [comment]
@hallvors can you check to see if the latest has a fix? https://github.com/PrismJS/prism

**Comment by hallvors** [comment]
The problematic regexp is still there:
https://github.com/PrismJS/prism/blob/b1fd5bdcee9c6203748286d13d6299f6ca90d903/components/prism-markup.js#L7
Maybe @LeaVerou and @PrismJS know if it's a known issue..

**Comment by miketaylr** [comment]
Probably worth filing a proper bug upstream then. Or submitting a patch. :)

**Comment by miketaylr** [comment]
(I went ahead and edited your comment to close the div as a workaround).

**Comment by LeaVerou** [comment]
This is very odd. Can you reproduce in [Prism’s test drive page](http://prismjs.com/test.html)? If so, could you file an issue on Prism’s repo? This is serious, and would be very high priority.

**Comment by miketaylr** [comment]
Thanks @LeaVerou -- reported.
