### ISSUE TITLE
Quick guide to markdown format for writing comments

### ISSUE THREAD

**Issue by calexity** [webcompat/webcompat.com#615]
Per the thread on the mailing list - we should create a quick way to show our markdown format.

There's probably the wrong markdown in this example because I don't know all the rules for ours.

@miketaylr I can't find the Twitter overlay example, but I took a guess. Can you send a link or a screenshot?

We could also build this as a page as a first step if that's easier to build or easier to use.
## ![small markdown overlay](https://cloud.githubusercontent.com/assets/1103366/7766328/fde66850-001c-11e5-9e6c-034bd2b72da3.png)

Could we allow it to be a modal that people could drag around next to their comment so it's a live reference guide?
## ![small markdown drag](https://cloud.githubusercontent.com/assets/1103366/7766332/06cc0498-001d-11e5-9ff3-8da4696849f2.png)

**Icons** 
http://fortawesome.github.io/Font-Awesome/icon/question-circle/
http://fortawesome.github.io/Font-Awesome/icon/times/

cc @hallvors @karlcow @magsout

**Comment by miketaylr** [comment]
Hey @calexity thanks for filing!

![](https://cldup.com/EGmrr9Y1ft.thumb.png) is what you see from twitter.com if you type '?'.

**Comment by magsout** [comment]
yeah, good idea :+1:
