### ISSUE TITLE
[bug] ordered list are not styled

### ISSUE THREAD

**Issue by karlcow** [webcompat/webcompat.com#621]
Our css is missing style for ordered lists.
Easy to fix.

**Comment by magsout** [comment]
in comment ?

There is style only for list default not number list 

![capture d ecran 2015-06-09 a 20 24 20](https://cloud.githubusercontent.com/assets/1997108/8066032/93acf38c-0ee5-11e5-89b6-e6e4f582d3a8.png)

**Comment by magsout** [comment]
- remove line height (due to page li)
- add style for list number

**Comment by magsout** [comment]
Ordered list ... Not list number...  So ok , I get it.

**Comment by karlcow** [comment]
Fixed by https://github.com/webcompat/webcompat.com/pull/625
