### ISSUE TITLE
[bug] h2 in comments are not styled

### ISSUE THREAD

**Issue by karlcow** [webcompat/webcompat.com#622]
When using `##` in comments we get a `h2` element in HTML. This is currently not styled.

**Comment by magsout** [comment]
oh yea, we can style h3 I guess, but maybe it's enough, no h4 ?

**Comment by miketaylr** [comment]
# h1
## h2
### h3
#### h4
##### h5
###### h6
####### h7 (lol)

**Comment by miketaylr** [comment]
(just testing, sorry)

**Comment by magsout** [comment]
I added `h1` `h2` `h3` on my PR https://github.com/webcompat/webcompat.com/commit/efa39c46a96c941400aa8adba85e8e1436613ea4

@miketaylr  I should add more ?

**Comment by miketaylr** [comment]
@magsout I'm not really sure. Maybe we wait until someone files a bug. :p

I've never had the need for that many headings in a comment... @karlcow ?

**Comment by karlcow** [comment]
Solved by https://github.com/webcompat/webcompat.com/pull/625
