### ISSUE TITLE
set up youshoulduse service

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat.com#623]
https://youshoulduse.herokuapp.com/

**Comment by magsout** [comment]
interesting, but how it can detect that anything broke css ?

**Comment by miketaylr** [comment]
Supposedly it compares it against MDN's compatibility tables data: https://github.com/mdn/YouShouldUse#how-it-works

I think it's more of a "careful this property only works in X browser" rather than "this property breaks your page in this way" type of thing. But I'm not really sure. :)

**Comment by karlcow** [comment]
We can give it a try so that might help them to detect some bugs. 
Note to self: Not sure it's working for people committing sass type css.

**Comment by miketaylr** [comment]
OK, I set up the webhook. Now I need to push something to trigger it--looking for a typo in the docs. ^_^

**Comment by miketaylr** [comment]
Hmm. Maybe it needs to be a commit with CSS. Oh well, let's see if anything happens in the future.
