### ISSUE TITLE
@webcompat twitter account

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat.com#63]
So. We have twitter.com/webcompat and it's doing nothing.

What's a good use? Tweeting bug reports? Updates? Emoji?

**Comment by miketaylr** [comment]
Karl is going to write a script to collect bugs that were fixed in the past week, and a bot to tweet (some of) those bugs will be cool.

**Comment by hallvors** [comment]
@karlcow is there a bug for "last week's fixes" script?

This feature can be added to the webhooks stuff we've moved to the webcompat.com server now.

**Comment by SemicolonExpected** [comment]
I'm not sure if you are still looking for suggestions, but you could also link to some relevant articles as well. I've seen a lot of "brands" tweet/share/etc articles that are relevant to the industry they're in. In this case you could share articles regarding web compatibility, which doesn't seem too narrow of a scope to focus in on.

**Comment by karlcow** [comment]
@SemicolonExpected We do time to time. But they are not that many ;)

**Comment by miketaylr** [comment]
I'm gonna close this as unactionnable and vague (the reporter is the worst). If anyone has suggestions, let's open specific issues for each type of info we might want to broadcast.
