### ISSUE TITLE
local development setup fails with 'grunt not found' error

### ISSUE THREAD

**Issue by hallvors** [webcompat/webcompat.com#632]
I tried to clone webcompat.com repo and do "make install" on a Ubuntu laptop. After a while it said:

```
intern@2.2.0 node_modules/intern
├── diff@1.1.0
├── charm@0.2.0
├── source-map@0.1.33 (amdefine@0.1.1)
├── chai@1.9.1 (assertion-error@1.0.0, deep-eql@0.1.3)
├── leadfoot@1.2.0 (dojo@2.0.0-alpha3)
├── digdug@1.2.0 (dojo@2.0.0-alpha3, decompress@0.2.3)
├── dojo@2.0.0-dev
└── istanbul@0.2.16 (which@1.0.9, abbrev@1.0.7, nopt@3.0.2, wordwrap@0.0.3, async@0.9.2, mkdirp@0.5.1, resolve@0.7.4, fileset@0.1.7, esprima@1.2.5, handlebars@1.3.0, escodegen@1.3.3, js-yaml@3.3.1)
make: grunt: Command not found
make: *** [install] Error 127
```

**Comment by hallvors** [comment]
Ah, I forgot sudo.. May I remove the brackets from the command in the docs? ;)

**Comment by hallvors** [comment]
(but repeating the command with sudo just fails differently)

**Comment by hallvors** [comment]
make: *** [install] Error 1

**Comment by magsout** [comment]
@hallvors have you install Grunt and  Grunt cli -g ?

**Comment by hallvors** [comment]
Yes. Supposedly. But the weirdest thing is that if I type "grunt" in a terminal, nothing happens..

**Comment by magsout** [comment]
`which grunt` ?

**Comment by magsout** [comment]
@hallvors you can test if cli is installed globally : `which grunt`

```
MacBook-Air:webcompat.com GuillaumeDEMESY$ which grunt
/usr/local/bin/grunt
```

**Comment by hallvors** [comment]
/usr/local/bin/grunt

**Comment by magsout** [comment]
@hallvors `npm install` and `grunt ?

**Comment by hallvors** [comment]
Something is very weird on this system - running ```grunt``` just quits silently every time. No error message, nothing. 
Hm.. this might solve it:
http://stackoverflow.com/questions/19953216/grunt-doesnt-give-any-output-ubuntu

**Comment by hallvors** [comment]
Now it works better :)
No CSS is applied because the /css/webcompat.dev.css file is 404 - but I assume a "make build" will fix this?

**Comment by hallvors** [comment]
All set!

**Comment by magsout** [comment]
👍

**Comment by miketaylr** [comment]
Thanks @magsout --glad you got it sorted @hallvors.
