### ISSUE TITLE
search broken when a status category is selected

### ISSUE THREAD

**Issue by karlcow** [webcompat/webcompat.com#633]
Steps to Reproduce.
1. Login
2. Go the All issues page
3. Select "New issues"
4. Type in the search box "country: jp"
5. Enter key

Expected: get the "search string" combined with the "new issues" only

Actual: nothing is happening. The enter key has no effect.

**Comment by miketaylr** [comment]
> Actual: nothing is happening. The enter key has no effect.

This part I can't reproduce. I get search results. Is the enter key not working for you generally, or just in this scenario?

> Expected: get the "search string" combined with the "new issues" only

So you mean you want the search results but only for new issues? That should be possible. We initially made a decision (I can find the bug later) that doing a search would clear all filters.

**Comment by magsout** [comment]
@karlcow 
>Actual: nothing is happening. The enter key has no effect.

I results related to the search bar but not the selected filter

**Comment by karlcow** [comment]
> We initially made a decision (I can find the bug later) that doing a search would clear all filters.
hmm indeed

What happened to me. I was trying to get "country: jp" which was from a precise category.

To think.

**Comment by magsout** [comment]
But maybe we can if it's possible to think about search Component. Multi filter + query search.

**Comment by karlcow** [comment]
this might be reopened in the future. but we do not really need it now.
