### ISSUE TITLE
[feature] Add QR code to bug URLs

### ISSUE THREAD

**Issue by tagawa** [webcompat/webcompat.com#636]
For checking in mobile browsers it would be helpful to have a QR code (or button to show one) for the URLs of problematic sites.

**Comment by miketaylr** [comment]
I'm not a fan of QR codes, but I see how this could be useful. We could hide it behind a keystroke and fetch the JS on-demand so all users wouldn't have to download it.

@tagawa have you done any client-side generated QR stuff before?

**Comment by tagawa** [comment]
Not a fan? Does not compute - this must be Austin humour.

I've only used PHP QR libraries in the past by there are several JS ones. This one looks good and doesn't require jQuery:
* http://neocotic.com/qr.js/ - 
* https://davidshimjs.github.io/qrcodejs/ - IE6+, no dependencies

I can have a play and make a mock-up.

**Comment by tagawa** [comment]
I'm thinking it would be good to use a font icon for the button. @magsout, do you have a link to the icons available? I know we use Icomoon to package them but I'm not sure what is the source icon set.

**Comment by magsout** [comment]
yes here https://github.com/webcompat/design/tree/master/3_Style%20Guide/icon%20from%20icomoon

Just import selection.json in https://icomoon.io/app/#/select

**Comment by tagawa** [comment]
Thanks for the quick help @magsout. If I update the font file I'll update those style guide files as well.
