### ISSUE TITLE
Better placement for label editor on issues page

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat.com#637]
As suggested by @karlcow in https://github.com/webcompat/webcompat.com/pull/630#issuecomment-112665108.

**Comment by miketaylr** [comment]
@magsout has some good ideas that might make this issue obsolete in #545.

**Comment by miketaylr** [comment]
Action item: implement side label widget thinger, consider ways this makes sense on mobile.

One proposal is to show labels on top and bottom (for mobile viewport).

**Comment by karlcow** [comment]
After discussing with @adamopenweb and @magsout, we decided to use icons at the top for the browsers. And to have actions near the comment box.
The large screen would get label editor on the right side. Small screens at the bottom.

**Comment by miketaylr** [comment]
This is done.
