### ISSUE TITLE
Add example page with one or two success stories

### ISSUE THREAD

**Issue by tagawa** [webcompat/webcompat.com#641]
As motivation to encourage contributions, this page should simply explain an example site problem, how it was fixed and the next step for potential contributors. It could be linked to from a "Why?" button on the front page.

**Comment by miketaylr** [comment]
:100:

**Comment by tagawa** [comment]
Assignment noted. Any suggestions for a good example fix we've had? Ideally something that doesn't show the company/organisation in a bad light.

**Comment by miketaylr** [comment]
I think someone suggested one of the Google Inbox bugs, but it would be good to review the relevant bug--I agree we don't want to link to an issue where people are too grouchy. Maybe @karlcow can suggest something?

**Comment by karlcow** [comment]
We had good contacts with some of the twitter bugs. 
Also this can help too 
https://github.com/webcompat/web-bugs/issues?q=is%3Aissue+is%3Aclosed+sort%3Acomments-desc

For example cookpad helped us find a bug
https://github.com/webcompat/web-bugs/issues/1050

after a long time, we managed to have a good contact on bestbuy
https://github.com/webcompat/web-bugs/issues/664

Medium is another one
https://github.com/webcompat/web-bugs/issues/745

**Comment by hallvors** [comment]
+1 - but it would be good if we could find some before/after screenshots for this.

**Comment by adamopenweb** [comment]
Let's plan to add a link to this from the contributor page. We can put the content on the wiki initially.

**Comment by adamopenweb** [comment]
I'm going to close this for now as duplicate, as we are discussing this in #1309 and will be implementing part of it on the updated contributor page #1149.

Thanks for getting this started @tagawa, if you are still interested your input is always welcome on the other reports. :)
