### ISSUE TITLE
[feature] import other bug trackers

### ISSUE THREAD

**Issue by karlcow** [webcompat/webcompat.com#642]
We proposed to other browsers to participate more. It didn't work as much as expected. 
Maybe we could try to test a couple of other options.

I was wondering if we could have more success if individual browsers bug reporting system could decide to export to webcompat.com on a per bug basis. 

This  needs refinement. Just the beginning of an idea.

**Comment by calexity** [comment]
This sounds like a solid idea @karlcow. Maybe it would help to understand why each browser team wants their own bug system? 

I wonder if it's more helpful for people to report to us and then we make it easy to export from webcompat.com to the browser bug triage system.

**Comment by karlcow** [comment]
> This sounds like a solid idea @karlcow. Maybe it would help to understand why each browser team wants their own bug system? 

To answer this I guess because each Browser have already an individual bug tracker. Some of the reasons

* a well known set of tools in their environment (filtering, notifications, etc.)
* bugs being transferred from a group to another easily. Basically a bug can start with a component parent, then being assigned to let's say "Core" component, then the Core dev realizes that it's not a core bug and move it to a WebCompat component. etc.

**Comment by miketaylr** [comment]
wontfix
