### ISSUE TITLE
Prioritized issue tracker for webcompat website work

### ISSUE THREAD

**Issue by calexity** [webcompat/webcompat.com#644]
I'd like for us to consider creating a single, prioritized list of work for work on the webcompat.com website. We talked about this at one time, I believe. 

It might be easier for people (like me) who intermittently read through the issues to jump in on work than the Github issues. 

I think our tool would be most helpful if it can:
1) Keep priorities clear
2) Make it clear who's working on an issue at any given time
3) Keep a history of the conversation around an issue

For consideration:
[Pivotal Tracker]
(https://www.pivotaltracker.com/faq#istrackerreallyfreeforpublicprojectsindividualusenonprofitsandeducators)
[Trello](https://trello.com/)
Both free for open source projects

Thoughts @miketaylr @karlcow @magsout @tagawa @hallvors ?

**Comment by tagawa** [comment]
Hmm, part of me thinks we could avoid service fragmentation as we already have task handling in GitHub. We could tweak it to suit our needs more if we make best use of issues and especially labels.

But on the other hand I really like using Trello and it's so much more intuitive and easy than GitHub. I haven't tried Pivotal Tracker but I imagine it's similar.

**Comment by karlcow** [comment]
ok let's see. 

Labels gives a type of view but really a status.
https://github.com/webcompat/webcompat.com/labels

Milestones are a bit more helpful. Somehow I often think I should do my home page of webcompat.com project with Milestones. More than the current one which is not helpful. 
https://github.com/webcompat/webcompat.com/milestones

We do not really use assignee. I just assign this one to @calexity as an experiment.

Pulse gives a summary of the activities, but also not useful for project management. 
https://github.com/webcompat/webcompat.com/pulse

I was digging around to see if there were things using github for the backend.
https://waffle.io/webcompat/webcompat.com

What we should try to avoid is to have to manage two places at the same time.

> I think our tool would be most helpful if it can:
> 1) Keep priorities clear

Could you give a bit more background? Do you mean we should really do this before that?

> 2) Make it clear who's working on an issue at any given time

Hehe. That's true we are not very good at that. Or more exactly only @calexity is good at it. :) Compare

https://github.com/webcompat/webcompat.com/issues/assigned/karlcow
https://github.com/webcompat/webcompat.com/issues/assigned/miketaylr
https://github.com/webcompat/webcompat.com/issues/assigned/tagawa
https://github.com/webcompat/webcompat.com/issues/assigned/magsout
with 
https://github.com/webcompat/webcompat.com/issues/assigned/calexity

Maybe it's the source of the issue?

> 3) Keep a history of the conversation around an issue

Is it not what we have currently? This discussion. Or are you thinking about something else?

**Comment by karlcow** [comment]
I was checking what waffle would require. 

Not sure about what it means fully.

![capture d ecran 2015-07-21 a 10 30 15](https://cloud.githubusercontent.com/assets/505230/8791269/8dc533a2-2f93-11e5-959d-5f13a36c636f.png)

**Comment by calexity** [comment]
@tagawa @karlcow I hear your concern. I don't want to add more tools and
Github is certainly the most obvious place to do our work.

Waffle looks like a good compromise because it sits on top of Github
issues. It looks like Trello a bit and it seems we would be able to
prioritize work.

My main concern is not being able to prioritize the work. When I look at
Github now, I'm never sure what other people are working on and what to
pick up.

Can we try setting up Waffle and give it a timebox of a week or so?

**Comment by tagawa** [comment]
>  My main concern is not being able to prioritize the work.

There's also the option of having ```P1```, ```P2```, etc. labels like some bug-tracking systems, but I admit this is very basic.

**Comment by karlcow** [comment]
@calexity I created it. https://waffle.io/webcompat/webcompat.com
Tell me if it's working for you.

**Comment by calexity** [comment]
Wow! Cool! It works and I love it.

Do you @karlcow @miketaylr or @magsout want to drag a couple most important
issues over to the Ready column? I'm planning on working tomorrow night on
Webcompat.

**Comment by magsout** [comment]
woot, waffle seems good.

**Comment by magsout** [comment]
I love Trello, but there is no third party without system to communicate between. Waffle seems like a good solution, because it takes up the issues already in place.

**Comment by karlcow** [comment]
ok. Cool. Let's close that issue as resolved. ^_^ thanks for the patience everyone.
And sorry for being a bit slow.

**Comment by miketaylr** [comment]
:100: this is cool.

**Comment by miketaylr** [comment]
@calexity -- sorry for taking forever as well. I just added about 10 issues to the Ready category.

**Comment by calexity** [comment]
Great @miketaylr! Thanks for setting this up @karlcow. I dig it.
