### ISSUE TITLE
Close QR modal with Esc

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat.com#645]
Right now Esc is bound for the label editor closing--should be possible to refactor that to share a generic "close" method, or to scope the shortcut.

**Comment by hallvors** [comment]
Should also close the search field if it's in the "open" state

**Comment by hallvors** [comment]
* QR modal
* Search field
* Label editor

- Either we let a single "Esc" key close everything at once, or we need a "stack" of "closeables" and let Esc pop off an close one at a time.

**Comment by miketaylr** [comment]
I like the closeable stack idea.

**Comment by miketaylr** [comment]
This feature doesn't exist anymore, closing.
