### ISSUE TITLE
Re-think (or kill?) "Thanks" page

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat.com#646]
I wonder if we should get rid of the /thanks/ page entirely and take reporters directly to their bug.

Looking at https://webcompat.com/thanks/1390, it's kind of bare. We could put the "thx" messaging with a link to Twitter in a Flash message, I think.

**Comment by karlcow** [comment]
Two options:

1. [kill] Redirect directly to the bug page, so the person might continue with the analysis. It can be even educative on the next steps the person could take. A flash message (disappeared after a couple of seconds) is not helpful. It can stays in the redirected page until the next reload. 
2. [rethink] 
  - (if anonymous) Redirect directly to the bug page + next steps
  - (if logged-in) Mini dashboard of how many bugs have been opened, closed, etc. + next steps.

![webcompat-issue-646](https://cloud.githubusercontent.com/assets/505230/8790973/58ebee86-2f8f-11e5-958f-25492b000222.jpg)
 
summary and next steps needs to have a proper design.

**Comment by miketaylr** [comment]
> A flash message (disappeared after a couple of seconds) is not helpful.

We have the ability to persist flash messages until the next reload (that's the default) behavior. For this I agree fading out would be bogus.

**Comment by calexity** [comment]
From my perspective, it makes the most sense to take them to their bug. I think we could consider adding a CTA at the bottom of bugs to get more info on how to help. That's a bit subtle, like this:
![contributorskeyboardshortcut](https://cloud.githubusercontent.com/assets/1103366/9596972/2559974a-5031-11e5-9032-faf93eabe351.png)

---------

Or we could do a notification bar on the top maybe every once in a while or if we could tell you were new:

![contributorsguide](https://cloud.githubusercontent.com/assets/1103366/9596979/49ced266-5031-11e5-9b63-f35f02e21e4e.png)


I like the achievements idea @karlcow. We could tie this into a badges system or profiles that would have that info and prioritize it separately.

**Comment by miketaylr** [comment]
We discussed this in Paris and want to:

* kill the thanks page
* create a hybrid of @karlcow and @calexity's suggestions: have a one-time thanks box on the newly reported issue that suggests next steps (CTA), + twitter, etc.

**Comment by miketaylr** [comment]
Mike promises to fix this this week.

**Comment by miketaylr** [comment]
> Mike promises to fix this this week.
What a liar. 

I'm gonna wait until #1104 is merged, so I don't create more work/conflicts for @magsout.

**Comment by miketaylr** [comment]
OK, blocker is done.
