### ISSUE TITLE
[documentation] Explain how to run intern to execute only one set of files

### ISSUE THREAD

**Issue by karlcow** [webcompat/webcompat.com#647]
When developing tests for interns, it's a bit cumbersome to have to run the full test suite during test development phase. It would be good to have  a way to tests individual set of tests in a file. For example, test only "issue.js" 

Reference
https://github.com/webcompat/webcompat.com/blob/master/CONTRIBUTING.md#functional-tests

**Comment by karlcow** [comment]
Assigning @miketaylr for at least commenting here on how to do that. I volunteer to include it in the documentation.

**Comment by miketaylr** [comment]
See https://github.com/webcompat/webcompat.com/issues/272#issuecomment-130117267. @karlcow figured it out. ^_^
