### ISSUE TITLE
functional tests are dependent of Mike's repo

### ISSUE THREAD

**Issue by karlcow** [webcompat/webcompat.com#648]
Most of the functional tests will fail if not configured properly with Mike repo's. I wonder if we should find a way to make this more resilient. Either by having a setup phase or by making the config always pointing to mike setup.

![capture d ecran 2015-07-21 a 16 21 16](https://cloud.githubusercontent.com/assets/505230/8795087/977b2498-2fc4-11e5-8451-61b38218ecd2.png)

For example, there is a hard dependency on `issue/100`

**Comment by miketaylr** [comment]
Yeah, this is not good. And bad for collaboration, IMO.

A few solutions (ordered from easiest -> hardest):

1) A test repo that is owned by webcompat
2) A script that people can run to populate an arbitrary repo with the types of issues we need to test against.
3) We mock out API requests with fake data

**Comment by karlcow** [comment]
Thinking out loud about potential issues.

1. Seems to be a good solution in any cases. It gives a bit of freedom for testers. Though I wonder if it creates issues in terms of tests which requires login aka ownership of the repo. 
2. Solve the issues of ownership, the issue I can see is that the script has to figure out if the repo has already been created and if it's in the right shape for running the tests.
3. The hardest to start up… but maybe the easier to maintain on a longterm with no dependencies on external infrastructure and ownership. 

## About Mocking with intern
* https://www.sitepen.com/blog/2014/07/14/mocking-data-with-intern/
* https://bocoup.com/weblog/effective-unit-testing-with-amd/
* http://rmurphey.com/blog/2014/07/13/unit-tests/
* http://fredkschott.com/post/2014/05/nodejs-testing-essentials/

I wonder if we could find a progressive way to go about it. For mocking maybe we could try with one simple test and figure out the complexity we have not yet figured out.

**Comment by karlcow** [comment]
in #661 @miketaylr asked about the "issue 100". The intern's tests are all dependent of one canonical issue. see for example https://github.com/webcompat/webcompat.com/blob/master/tests/functional/comments.js#L23

```js
.get(require.toUrl(url(100)))
```
it means that when we setup our own test repos we need to have at least 100 issues. And that this one needs to be configured as the ones of mike's repo. 

1. The easiest solution would be to have the test repo be on webcompat.com and force the configurations for people to use this test repo. 
2. Then in the future, make us less dependent on the repo through mocking some of the tests.

**Comment by karlcow** [comment]
The issue is https://github.com/miketaylr/nobody-look-at-this/issues/100
Mine is https://github.com/karlcow/webcompat-test/issues/100
So they are definitely different.

Another thought I had is that the script could have a setup phase creating the issue it needs, putting in storage the issue number for using after in the rest of the tests, instead of hardcoding it. :)

**Comment by miketaylr** [comment]
Cool, thanks for reminding me the issue. The simplest way to fix this might be for me to just transfer the repo to webcompat (and rename it something less dumb). I like the idea of a populating script--maybe a cool Paris project.

**Comment by miketaylr** [comment]
OK, I just renamed the repo and transferred it to https://github.com/webcompat/webcompat-tests.

So if anyone was using "miketaylr/nobody-look-at-this/issues" in their config.py, they need to change it to 
"webcompat/webcompat-tests/issues". I think maybe just @karlcow, @tagawa  and @magsout were.

This should be fine--but to really pass all tests you need to be a collaborator. So a script to generate a repo with test images is a better solution here.

**Comment by tagawa** [comment]
Thanks for the heads-up @miketaylr - done.

**Comment by miketaylr** [comment]
Phew, Travis didn't explode. Let's close this one and open a new issue for a repo/issues script.

**Comment by karlcow** [comment]
Thanks @miketaylr :fireworks:
