### ISSUE TITLE
QR popup is cropped if bug report is short

### ISSUE THREAD

**Issue by hallvors** [webcompat/webcompat.com#649]
See https://webcompat.com/issues/1425 and open the QR code popup. The bottom part is cropped away because it extends beyond the bug description, and there's an "overflow:hidden" rule or two..

**Comment by miketaylr** [comment]
Ah, yes. @tagawa, will you have time to look at this over the next week or so?

**Comment by tagawa** [comment]
Thanks for spotting this. Dynamically changing the ```overflow:hidden``` rules is a possible fix but prone to messing up the layout, so this workaround just reduces the size and top margin.

**Comment by miketaylr** [comment]
I wonder if scaling down the image based on container size (if there's going to be an overflow) would work. Or if it would just look scaled and crappy.

**Comment by hallvors** [comment]
Could the modal overlay be a sibling rather than a child of those overflow:hidden elements?

**Comment by hallvors** [comment]
(BTW it's a really cool feature @tagawa - I've never really bothered using a QR reader before, but in this case it's a real timesaver!)

**Comment by tagawa** [comment]
Much appreciated @hallvors. I love QR codes &mdash; trying to convert the world one step at a time :-)

**Comment by tagawa** [comment]
@hallvors I think I tried the sibling positioning when I was developing it but don't think I was able to get it to work properly. I can try again.

**Comment by miketaylr** [comment]
This got fixed by #691!
