### ISSUE TITLE
Excessive permissions required to file a bug using Github

### ISSUE THREAD

**Issue by AlfonsoML** [webcompat/webcompat.com#655]
When I tried to file a bug about a website there are two buttons at the bottom "Report via Github" and "Report anonymously", I clicked on Github and then I was prompted to grant too many permissions:

![mezer_08-03_12-15-18](https://cloud.githubusercontent.com/assets/2482331/9035558/5aaf0baa-39d9-11e5-926c-fcb7a7dfab0d.jpg)

I had expected to only allow permissions on the webcompat repository and granting permission to read my identity and file a bug on my behalf seems like should be enough, no need to give full permissions on everything

**Comment by miketaylr** [comment]
Hey @AlfonsoML, thanks for filing. FWIW, I totally agree with you. Unfortunately GitHub doesn't yet [provide an oauth scope](https://developer.github.com/v3/oauth/#scopes) that restricts access to issues. :(

If you'd like to contact GitHub and make that suggestion that might help--we've also asked them to do the same.

**Comment by hallvors** [comment]
Question: if the user is not filing through webcompat.com UI but directly on GitHub, I guess s/he doesn't need to grant any permissions at all? Could we offer that as a third option, for users who know what they are doing?

**Comment by miketaylr** [comment]
Yes, possibly. But GitHub doesn't allow for issue templates so we may find that the quality of the bugs varies wildly. The Webcompat UI at least forces some notion of consistency. Maybe this is just a theoretical concern though. Right now nothing will break (I think).

**Comment by hallvors** [comment]
What if we add in small print underneath the "report" buttons 

"You can also copy the text you entered above and <a href="https://github.com/webcompat/web-bugs/issues/new">click here</a> to add a new bug through GitHub. This lets you report under your user name without having to grant our app access to your GitHub account."

**Comment by hallvors** [comment]
Even better - GitHub supports some query string arguments to /issues/new - I just tested :) So we can update that link in real time and add ?title=foo&body=bar

**Comment by miketaylr** [comment]
Cool. I can work on this tomorrow morning.

**Comment by karlcow** [comment]
Same concerns than @miketaylr 
I would rather have 
* [report via Webcompat] (old report via GitHub)
* [report via GitHub] (new hallvord proposal)
* [report anonymously] 

Issue: Screenshot feature? Maybe not, just something to add to the body.

**Comment by hallvors** [comment]
Hm.. The screenshot feature should "just work" (famous last words) if it submits an image to a GitHub service and gets a magic markdown string back that is added to the body. That magic string is of course passed on to GitHub with the rest of the text with the [Report via GitHub] option..

Is there any functional difference between your [Report via Webcompat] and [Report via GitHub], @karlcow? If we had a [Report via GitHub] button, would be need the webcompat one?

**Comment by karlcow** [comment]
> Is there any functional difference between your [Report via Webcompat] and [Report via GitHub], @karlcow? If we had a [Report via GitHub] button, would be need the webcompat one?

If I understood your proposal is about making an HTTP POST to the Web site (a bit like a selenium test). Not talking to the API of Github directly.

**Comment by miketaylr** [comment]
Let's close until GitHub announces finer grained OAuth scopes.

**Comment by miketaylr** [comment]
It seems like something is coming: https://developer.github.com/early-access/integrations/#granular-permissions

(still not ready for public to use yet tho... but promising!)

**Comment by karlcow** [comment]
Reopening the issue, after a comment by @dbaron on a recent bug. I was wondering if GitHub was now offering finer granularity. I need to dig a bit more the docs. 

https://developer.github.com/apps/building-integrations/setting-up-and-registering-oauth-apps/about-scopes-for-oauth-apps/

**Comment by karlcow** [comment]
To note that the issue is known by GitHub
https://github.com/dear-github/dear-github/issues/113

**Comment by karlcow** [comment]
if I check my current Scopes in my headers, I get 

```
X-OAuth-Scopes: gist, repo, user
X-Accepted-OAuth-Scopes: 
```

**Comment by karlcow** [comment]
In https://developer.github.com/apps/building-integrations/setting-up-and-registering-oauth-apps/about-scopes-for-oauth-apps/
I still don't see a way to make it more granular at the repo level.

**Comment by karlcow** [comment]
ok closing again for now.

**Comment by karlcow** [comment]
This is potentially interesting.
https://developer.github.com/apps/building-github-apps/identifying-and-authorizing-users-for-github-apps/

> Your GitHub App can perform actions on behalf of a user, like creating an issue, creating a deployment, and using other supported endpoints.

and


> The user's access token allows the GitHub App to make requests to the API on behalf of a user.

**Comment by dmose** [comment]
@zoepage It's not obvious to me that this is an enhancement.  Right now, to file through webcompat.com, I'm required to give webcompat.com the ability to write the _code_ in all the public repositories that I have access to, which is a serious overreach and certainly a vector for security breach access to spread, should webcompat.com get breached.

@miketaylr What are your thoughts on converting this to a Github App?  Is that a substantial amount of work?

**Comment by karlcow** [comment]
@dmose 
About 
> which is a serious overreach 

yes and we are not happy about it as you see in this thread. :)

> @miketaylr What are your thoughts on converting this to a Github App? Is that a substantial amount of work?

I guess there's indeed the amount of work that would require, which could be an issue. Maybe we should check/look for a project which went through this type of transition to assess the challenges.

**Comment by karlcow** [comment]
To read https://rhystyers.com/blog/post/github-apps.html

**Comment by miketaylr** [comment]
I don't think there's any harm in re-opening this, since it's something I would love to fix.

> @miketaylr What are your thoughts on converting this to a Github App? Is that a substantial amount of work?

It doesn't look like an impossible amount of work. It looks like it would allow us to kill of @webcompat-bot (sorry, buddy), for anonymous reports, which is nice. I need to investigate if it would still allow us to file issues on behalf of a user, as the user (if they choose the non-anon option).

**Comment by miketaylr** [comment]
Realistically, we don't have bandwidth to work on this in Q2, but it's possible we could make progress in Q3. Thanks for re-raising @dmose.

**Comment by dmose** [comment]
No worries; thanks for the updates!

**Comment by karlcow** [comment]
> I know you might not have a better choice, but the @MozWebCompat permissions are way too broad.. (r/w all repository data, no less) https://twitter.com/kangsterizer/status/1083551261054488577/photo/1
> doing anonymous report but adding your github username seems to work fine though ;-)

— https://twitter.com/kangsterizer/status/1083551575937695744

**Comment by Manishearth** [comment]
A far simpler solution to writing an entire Github App is to use Github's support for [prefilling issues with query parameters](https://help.github.com/en/articles/about-automation-for-issues-and-pull-requests-with-query-parameters). When you click "file", it uploads all images server-side using the API and generates a link, which you are navigated to.

**Comment by miketaylr** [comment]
@Manishearth wow! I didn't know this existed.

**Comment by karlcow** [comment]
Added backlog to reopen when it's time to work on it.

**Comment by karlcow** [comment]
Our low band-aid for this is to report anonymously and leave your github username in the field allowing it. It's not perfect but easier than redeveloping the oauth for Github App in our current resources.

**Comment by karlcow** [comment]
This might become more urgent with the #3118 events.

**Comment by dmose** [comment]
@karlcow isn't the thing described in https://github.com/webcompat/webcompat.com/issues/655#issuecomment-522880568 a way to avoid a big rewrite?

**Comment by karlcow** [comment]
@dmose it seems interesting, but I don't think it will solve our issues. Maybe I'm wrong. 

> You must have the proper permissions for any action to use the equivalent query parameter.

So I interpret this as only people with specific permissions on the repo will be able to file a complete report as we wish it to be.

**Comment by Manishearth** [comment]
> So I interpret this as only people with specific permissions on the repo will be able to file a complete report as we wish it to be.

The only thing you will lose out on is labeling, and you can write a pretty lightweight bot to label issues based on metadata in a comment at the end of it or whatever.

**Comment by Manishearth** [comment]
You can also use this feature in conjunction with issue templates to autoset labels, but y'all have a lot of them and getting the entire set of possible labels into templates would be annoying.

**Comment by karlcow** [comment]
So to be clear, the issue we are talking about here is people reporting issue with https://webcompat.com/issues/new and wants to log in as a GitHub user to have the report made under their name. 

The form is created by webcompat.com and then sent to GitHub. We are not using the GitHub form templates to file issues currently (except for the very rare case where people use directly GitHub).

This for example doesn't solve our issues. :) 
https://github.com/webcompat/webcompat-tests/issues/new?labels=bug&title=New+bug+report

It just creates a prefilled form on **GitHub**, not on **webcompat.com**

**Comment by Manishearth** [comment]
Right, I understand what you want to achieve here. What I'm suggesting is this:

 - User fills in form on webcompat.com, clicks submit
 - webcompat.com generates a GitHub prefilled form link, and redirects to it
 - user just needs to click submit on the GitHub issue

There are two problems here: images, and labels. You can't send images through the query string, and you can't use labels since not everyone has permissions to use labels on the repo. For the former, you can preupload the images server-side and then just insert links. For the latter, you can note the relevant metadata in the issue and have a bot apply the correct labels.

I mentioned templates because templates are one way to get around the label restriction, GitHub allows templates to come with preset labels, and you can use the query string thing with templates. But this workaround requires you create one template for each label combination, and is a big hack, using a bot for labeling seems easier.

**Comment by karlcow** [comment]
@Manishearth Thanks for explaining. I understood you were trying to redirect the users to github. :)
1. For labels we already have a bot. 
2. For the images we are linking to them. ;)

**Comment by Manishearth** [comment]
Ah, so then we should be all set? We just need to replace the server side stuff that the "report via github" button does with a simple link generator thing. This doesn't fix anonymous filling, but it makes the github filling much easier and less permissionsy.

**Comment by karlcow** [comment]
it means we have an option if we accept to get out of the current UX workflow. :)

**Comment by karlcow** [comment]
Someone on matrix made the comment about the excessive permissions required by webcompat.com.

@ksy36 We should at least re-evaluate seriously what needs to be done to change the code. 

Then when we have a better idea of the amount of efforts we could decide what to do about it. Probably we would get more authenticated users if the system was more granular.

**Comment by karlcow** [comment]
Removing @miketaylr who has probably no time or desire to work on that.

**Comment by miketaylr** [comment]
> Removing @miketaylr who has probably no time 

Yeah, realistically no.

> or desire to work on that.

😭
