### ISSUE TITLE
new issues page doesn't receive a JSON response

### ISSUE THREAD

**Issue by karlcow** [webcompat/webcompat.com#656]
1. Go to https://webcompat.com/
2. scroll down and click on [New Issues]

Expected: the list of new issues

Actual: blank list. The New Issues button is not selected.
The API JSON call to 
`https://webcompat.com/api/issues/search/new?page=1&per_page=50&state=open&stage=new&sort=created&direction=desc`
is not made. 

The URI is 
`https://webcompat.com/issues?page=1&per_page=50&state=open&stage=new&sort=created&direction=desc`

If I click the New Issues label then the JSON resource is called.

**Comment by miketaylr** [comment]
From https://github.com/webcompat/webcompat.com/commit/8cfd1fa1906c9fbad99f320ed2d7f8232ee72b44

We don't need "status-" in the filterRegex because they come from URL params which don't have "status-" in them. Looks like I could have done a better job reviewing. ^_^

**Comment by miketaylr** [comment]
Ahh :hankey:. I didn't mean to push to master. :/

**Comment by karlcow** [comment]
Merci!
