### ISSUE TITLE
setUp / tearDown for login and logout on functional tests

### ISSUE THREAD

**Issue by karlcow** [webcompat/webcompat.com#664]
Should this part of the code be in a login feature or a setUp that we activate at least in any tests library we need. Right now, there is a dependency on having index.js for the rest of the tests to be working.

```js
    'my issues (when logged in)': function() {
      return this.remote
        .setFindTimeout(intern.config.wc.pageLoadTimeout)
        .get(require.toUrl(url))
        .findByCssSelector('.js-login-link').click()
        .end()
        .findByCssSelector('#login_field').click()
        .type(intern.config.wc.user)
        .end()
        .findByCssSelector('#password').click()
        .type(intern.config.wc.pw)
        .end()
        .findByCssSelector('input[type=submit]').submit()
        .end()
        .findByCssSelector('button').submit()
        .end()
```

**Comment by karlcow** [comment]
Ah interesting to ease with the login process when testing only the labels.js library I decided to include it.
See https://gist.github.com/karlcow/3a1ed0435ae3b36532c1

The first HTTP request doesn't go to the right place. 
I get an expected failure for the tests.

![capture d ecran 2015-08-06 a 10 36 17](https://cloud.githubusercontent.com/assets/505230/9101867/214d9d72-3c27-11e5-9809-cf68b38857cd.png)

But more interesting was the first test (login one.)

![capture d ecran 2015-08-06 a 10 31 45](https://cloud.githubusercontent.com/assets/505230/9101884/54d4d2c8-3c27-11e5-853b-e7b0956d93dc.png)

it failed with a 404 and the wrong URI which we can find in 
https://github.com/webcompat/webcompat.com/blob/master/tests/intern.js#L22-L27

**Comment by karlcow** [comment]
Also using 

```
→ npm -v intern
1.4.21
```

**Comment by karlcow** [comment]
Checking `packages.json` I see

```
    "intern": "2.2.0",
```

I wonder why there's no warning about it. when I run intern in command line. That might explain some of my issues?

**Comment by miketaylr** [comment]
:+1:, seems good.

**Comment by miketaylr** [comment]
> Right now, there is a dependency on having index.js for the rest of the tests to be working.

This is true for:

* comments.js
* issue-list.js
* reporting JS

Not true for:
* contributors.js
* history-navigations.js
* issues.js

**Comment by miketaylr** [comment]
@karlcow another thing to keep in mind is once you've successfully logged in once, you have a session cookie. So doing the login again won't require typing in username/pw. 

We could use https://theintern.github.io/leadfoot/Command.html#clearCookies between tests, but that's going to make tests take much long (especially in Japan).

It should be possible to write the login test in such a way to handle both conditions though--as is it would wait 10 seconds and timeout after the first successful login.

**Comment by karlcow** [comment]
Another option:
1. We reorganize in a way that all tests which do not require any session are done first
2. Then the tests which requires logins. 
3. When creating additional tests/suites, we can make sure we are in the wanted state before starting the test.
4. I would also put in a separate category the tests which are testing the login and the logout. These are very specific. And Maybe should run before any "logged in required" test suites. If we fail at that stage, there might be an issue with github, network being slow and we should bail out early instead of trying to execute the tests in a state which doesn't work. (That's one of my issues from Japan. The tests are becoming erratic because the machine is not in the supposed state.)

**Comment by miketaylr** [comment]
Seems like a good plan. Until someone does this work another option to alleviate pain from Japan is to do your work in a webcompat/webcompat.com branch and let Travis run tests for you for each commit. It's fast and free. ^_^

**Comment by karlcow** [comment]
> another option to alleviate pain from Japan is to do your work in a webcompat/webcompat.com branch and let Travis run tests for you for each commit. 

hmm intermediate solution indeed, but means to have to commit a lot for changing a comma then waiting for travis to execute everything, when I'm still in the phase where I prototype and develop things on the go. I also comment out the other suites to not be dependent on them. :)

**Comment by karlcow** [comment]
This contains part of our answers. Quite nice.
https://theintern.github.io/intern/#page-objects

**Comment by karlcow** [comment]
@miketaylr Did we deal with that in #711 
Shall we close?

**Comment by karlcow** [comment]
Ok let's close. It's almost done. Follow up in #711
