### ISSUE TITLE
New Issues filter is not working properly

### ISSUE THREAD

**Issue by swarnava** [webcompat/webcompat.com#668]
Go to http://webcompat.com
Browse to New issues only.(https://webcompat.com/issues?page=1&per_page=50&state=open&stage=new&sort=created&direction=desc)

the page is also showing needdiagnosis filter.

**Comment by miketaylr** [comment]
Thanks for reporting @swarnava. We've made a few changes to how we handle labels--so this was probably a regression.

**Comment by magsout** [comment]
Bug seems fixed, right ?

**Comment by miketaylr** [comment]
Ah yes--deployed today. Thanks. :)
