### ISSUE TITLE
[ux] UI improvements around issue image uploads

### ISSUE THREAD

**Issue by karlcow** [webcompat/webcompat.com#681]
Now that we deployed the new feature #24 for uploading images, we can now improve the User experience.

I just tested with https://webcompat.com/issues/1576

I see two issues, here the description of the UX. (other issue at #682 )

1. Once you have selected an image to upload, it's not possible to know if we successfully added the image to the form. 
2. Also maybe the name of the image should be there with a chance to rename it.

**Comment by miketaylr** [comment]
> Maybe the name of the image should be there with a chance to rename it.

Agreed we could do more here. Possibly show a clientside preview. What's the purpose of renaming the image? Right now we obfuscate the filename on upload (that can change of course).

**Comment by karlcow** [comment]
>What's the purpose of renaming the image? Right now we obfuscate the filename on upload (that can change of course).

1. obfuscate the image filename :+1: 
2. rename the image for the alt tag not for the filename. (sorry for not being clear) ^_^

**Comment by calexity** [comment]
I can't figure out how to add an image. Is it in production? 

Here's a shot at this without being able to test the existing functionality. Let me know if we support both drag & drop and click:

![images in comments](https://cloud.githubusercontent.com/assets/1103366/9596803/d1060900-502e-11e5-8d83-b71cda24d38c.png)

Would be nearly the same on Desktop, slightly bigger.

Icon is fa-plus-circle

Colors are same placeholder color, or we could introduce a medium gray, if we haven't already #555555

**Comment by miketaylr** [comment]
> I can't figure out how to add an image. Is it in production? 

Yeah, but for right now it's just for new bug reports (there's a little cloud upload thingy if you look at the bottom of the form at webcompat.com/?open=1. I'm in the middle of getting it to work for issue comments in https://github.com/webcompat/webcompat.com/issues/687.

**Comment by calexity** [comment]
Ah ok. That makes sense.

**Comment by miketaylr** [comment]
These designs look good, @calexity. Two things to think about:

 * we'll need to account for is somewhere to stick a validation error (if someone tries to upload a word document or something). Here's what it looks like on my branch now (just re-using components from the homepage):

![](https://cldup.com/E7-pgkenNl-3000x3000.png)

 * in addition to drag + drop we should do something like GitHub and make it possible to click somewhere to open a file picker. It could be as simple as what they do.

![](https://cldup.com/nY5W1B4jjP-3000x3000.png)

**Comment by miketaylr** [comment]
> Renaming an image would happen in the brackets with the [ImageNameHere]. Is that too subtle?

That's how I've currently implemented the issue image upload -- (just like GitHub) -- when you upload an image, it sends an AJAX POST to the server w/ the file and returns the URL. On success we append something like `![Screenshot of the site issue](https...blahblahblah.png)` to the comment textarea. People can edit the text before making their comment.

**Comment by miketaylr** [comment]
I think this can be closed now that #867 is fixed. See https://github.com/webcompat/webcompat.com/issues/879#issuecomment-169107610 for a gif of what this looks like now -- there is a preview of the image you're about to upload.
