### ISSUE TITLE
[bug] upload images doesn't work /  alt not useful

### ISSUE THREAD

**Issue by karlcow** [webcompat/webcompat.com#682]
This is also related to #681 and #24 for uploading images
I just tested with https://webcompat.com/issues/1576

1. Once the bug has been submitted… the upload didn't happen or something else happened 

``` html
<p>
  <img src="https://webcompat.com/uploads/2015/8/55cbd63b-6e06-498a-9fae-273ffc7edffe.png" 
           alt="2015/8/55cbd63b-6e06-498a-9fae-273ffc7edffe.png">
</p>
```

2. The `alt` is not very useful. :)

**Comment by miketaylr** [comment]
Thanks for reporting -- I'll take a look in the morning. We should probably go with an empty alt.

**Comment by karlcow** [comment]
or the alt could be "Screenshot of the site issue"
