### ISSUE TITLE
Too many 404s on quick reload

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat.com#683]
I don't know if we can blame this on a GitHub DDOS...

If I visit https://webcompat.com/issues/1576, about 50% of the time I get a 404. Even just refreshing a few times...

![](https://cldup.com/tMQOb9CQiC-2000x2000.png)

@karlcow, any ideas? You touched error handling last. :fire_engine: :)

**Comment by miketaylr** [comment]
It seems like if I load an issue, then reload immediately I get a 404. :S

**Comment by karlcow** [comment]
Note that our caching system is busted too for these resources.

**Comment by miketaylr** [comment]
Ah, found the bug, @karlcow.

https://github.com/webcompat/webcompat.com/blame/master/webcompat/api/endpoints.py#L55

That explains the caching as well. The `status_code` is 304 on reload (I just tested locally with a print statement). We probably want to check for 2XX or 3XX before jumping to 404.

**Comment by karlcow** [comment]
I will fix that today with test + code.
Thanks @miketaylr

**Comment by miketaylr** [comment]
Cool, thanks!

**Comment by karlcow** [comment]
hehe… my comment was appropriate

``` python
# we might want to be less tolerant here.
abort(404)
```

I guess I thought about it and then focused on just fixing the JSON errors.
