### ISSUE TITLE
Disable anonymous reports for facebook.com (temporarily).

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat.com#688]
There have been a number (20+) of strange reports for facebook.com. Some request us to ban a user for using bad language or other similar behavior. Since we're *not* the internet police, this is effectively spam. In https://github.com/webcompat/web-bugs/issues/1600 I asked the user to stop, but more messages have come through anonymously. :hankey: :hankey: :police_car: 

So let's turn it off anonymous reporting for facebook.com for the time being. If you reach this bug and have a legitimate web compatibility issue, feel free to email miket@mozilla.com.

**Comment by miketaylr** [comment]
Also disabling for fb.com, because :hankey:

**Comment by miketaylr** [comment]
See https://github.com/webcompat/webcompat.com/commit/eff06cc5859e42a4e1f26e6b3b4fd3778e0f478b.

**Comment by buttercookie42** [comment]
I'm hitting this even though I'm trying to submit via my Github account. If I'm not logged in at webcompat.com, it doesn't even try to log me in via Github, but just redirects me to that error message. If I manually log in, the submit button changes and contains my user name, but I still can't submit the new issue.

**Comment by miketaylr** [comment]
Sorry about that @buttercookie42, I know it's annoying.

If you'd like, you can email me the issue directly miket @ mozilla.com. Maybe we can disable the weak, weird spam control next week--perhaps the strange spammers have forgotten about us.

**Comment by miketaylr** [comment]
I wonder if it's time to remove this now...

**Comment by mathiasbynens** [comment]
FWIW, I’m running into this as well despite being logged in on the webcompat.com through GitHub.

**Comment by miketaylr** [comment]
Thanks @mathiasbynens -- I'll file a bug to remove this (I would be impressed if the previous spammer came back to try again).
