### ISSUE TITLE
Clicking labels on the UI doesn't bring search results.

### ISSUE THREAD

**Issue by karlcow** [webcompat/webcompat.com#693]
Steps to reproduce:

1. Go to https://webcompat.com/issues?page=1&per_page=50&state=open&stage=all&sort=created&direction=desc
2. A list of bugs is displayed, choose to click on 1 label of the right side such  as firefox or needscontact
3. The search returns nothing

Some hints:

* The URL stays https://webcompat.com/issues?page=1&per_page=50&state=open&stage=all&sort=created&direction=desc
* The page shows in the search form "label:firefox". Change it with "label:browser-firefox" and we get the right result and the URL changes to https://webcompat.com/issues?page=1&per_page=50&state=open&stage=all&sort=created&direction=desc&q=label%3Abrowser-firefox

**Comment by miketaylr** [comment]
Yeah, more fallout from label changes. We pass the label directly to GitHub, so we'll have to do some more prefix fiddling before sending off the search.

**Comment by miketaylr** [comment]
Will file a follow up for tests.
