### ISSUE TITLE
[feature] Quick Abuse Control Mechanism

### ISSUE THREAD

**Issue by karlcow** [webcompat/webcompat.com#694]
As any Web sites being open on the interactions with users, we got in the last couple of weeks our first abuses. We don't want to become a fortress there are no interests on that. I'm not sure what triggered the first spams but let's try to build a mechanism where we can be quicker to react.

This is a proposal, open to discussions and suggestions. 
This will require individual issues for specific part of the code, to avoid to make this one a monster.
## Proposal:
- [ ] A list of conditions (see below for the format) at a precise URI
- [ ] A hourly reading of the URI
- [ ] The URI can be updated by a couple of people with editing rights on the project (not too many)
- [ ] The URI is orthogonal to webcompat.com deployment 
- [ ] A record of abuse issues related to each list item at the URI
- [ ] A logging system for recording if the abuse is still attempted 
- [ ] A weekly report on the abuse by mail to the owners of the abuse list
- [ ] Each POST requests is checking that it's not part of the abuse list
- [ ] An error message is sent back to the user with a link to the record of abuse issue.
## Some Process:

We could imagine that there's a hosted file on https://github.com/webcompat/webcompat.com which can be updated through Pull Requests. The site webcompat.com can fetch this file on a hourly basis. Our geographical distribution makes it easier to be able to adjust this file very quickly when we detect an issue. And makes it easy to cancel by someone else. 
## Format

```
user: username issue_number
url: domain_name issue_number
```

where 
- `user` says if we are dealing with blocking a specific `username`. ex: `miketaylr`
- `url` says if we are dealing with a specific `domain_name`. ex: `facebook.com`, `myie9.com`
- `issue_number`: is where we recorded our decision to add/remove to the list of abuse. ex: `https://github.com/webcompat/webcompat.com/issues/688`
## Benefits
- Makes it easier for us to be reactive
- doesn't depend on @miketaylr deploying the full site.
## Drawbacks
- Spending our time on developing something that we would rather not have to develop.

**Comment by tagawa** [comment]
Re. an error message being sent back to the user/abuser, there is some merit in not doing this but instead having it be accepted as normal and then silently fail (/dev/null). This could prevent some kind of argument or retaliation.

**Comment by hallvors** [comment]
What about this:
if anyone attempts to add a new report with the same URL and/or content as a report we've closed during the last month, pretend to accept it as a new report but actually give them the URL to the old one.. ?

**Comment by karlcow** [comment]
@tagawa Yes I thought about that, but then someone who is reporting something legit might not understand why it failed. That's a good point though.

@hallvors Worth exploring. The spam we have received have been made to change. Slight variations in the report.

**Comment by hallvors** [comment]
Perhaps matching on URL hostname+path would be good enough? Although I guess this is a bit slow and cumbersome when we use Github's DB through some web API.. :-/

**Comment by miketaylr** [comment]
A good topic for Paris.

**Comment by miketaylr** [comment]
Moving to backlog until we need it.
