### ISSUE TITLE
Third Party embeddable issue form for webcompat.com

### ISSUE THREAD

**Issue by gxela** [webcompat/webcompat.com#695]
Need to create a embed module to be usable by webmasters to embed a submit issue form into websites. To allow for easier adoption of webcompat on the web, make easier for anyone to add a "submit issue" form to their website. Which in turn submits an issue to the webcompat/webbugs issues

**Comment by gxela** [comment]
This can be a simple javascript embed that submits an issue to github

**Comment by miketaylr** [comment]
Interesting idea, thanks for filing @gxela.
