### ISSUE TITLE
Update privacy policy with regards to logging for security and performance issues

### ISSUE THREAD

**Issue by karlcow** [webcompat/webcompat.com#705]
We landed #245 which adds capabilities for logging, we need to update the privacy policy if we want to log things related to the user such as an ip address.

**Comment by miketaylr** [comment]
Not ready to merge yet, until we have log creation and deletion in place.

**Comment by miketaylr** [comment]
Mike: land ur code

**Comment by karlcow** [comment]
@miketaylr ping. Cleaning  https://github.com/webcompat/webcompat.com/milestone/31 before Taipei.
