### ISSUE TITLE
Add guidelines to contributing.md with regards to logging best practices

### ISSUE THREAD

**Issue by karlcow** [webcompat/webcompat.com#706]
We landed #245 which adds a logging mechanism to the webcompat.com code. 
We need to make sure that we have guidelines for adding logging capabilities and **what to not do**.

**Comment by zoepage** [comment]
@karlcow could you provide more information here? thank you!

**Comment by karlcow** [comment]
@zoepage yes for sure. 

* Pointing at the logging mechanism in python which now exists and is usable.
* Probably a code example on how to instantiate a logger
* Finally be mindful of the people privacy, we can NOT log everything. We can use the logger for certain type of problems in the code, but we can't go further than what is described in the privacy policy.

If you need help, please let me know. :) If you are not comfortable enough with it, just remove it from your list of things to edit, and I'll do it. :) No issue. Happy to help.

**Comment by zoepage** [comment]
@karlcow took a look into it and it would be great, if you could help out with this one. Thank you <3

**Comment by miketaylr** [comment]
We're gonna close this, Flask handles logging in a way that makes it difficult for us to create granular logging  by file.
