### ISSUE TITLE
add label for Edge browser

### ISSUE THREAD

**Issue by karlcow** [webcompat/webcompat.com#707]
We need to add browser-edge as a label.

**Comment by karlcow** [comment]
we need to adjust the bot. See repo for the bot.

**Comment by karlcow** [comment]
https://github.com/webcompat/web-bugs-issue-tagger/issues/9

**Comment by deepthivenkat** [comment]
I should be modifying this [file](https://github.com/webcompat/webcompat.com/blob/60637b1b5885869c42a98e7513ddf8821455b9f9/webcompat/templates/list-issue/issue-list.html)  ?

Any border color preference?

**Comment by deepthivenkat** [comment]
#962 r? @karlcow

**Comment by miketaylr** [comment]
This is fixed.
