### ISSUE TITLE
Mocking the GitHub communications for functional tests

### ISSUE THREAD

**Issue by karlcow** [webcompat/webcompat.com#712]
When we are testing the UI with intern, we want to make sure that the UI reacts accordingly to what we want of the user experience. Right now, the tests are dependent of Github communication but it's not necessary most of the time for the suer experience. Communications issues in between webcompat and github have to be dealt with elsewhere. 

1. Mock all response from Github to WebCompat in intern (when possible)

There is two features which are currently directly talking to Github. 
* search everywhere (in progress)
* load search results from URI bar

decided in Paris september 2015 at webcompat meeting  with @miketaylr

**Comment by karlcow** [comment]
In issue #663 we wanted to make a canonical test repo. But if we mock the correct issues, we kind of make #663 irrelevant. Let's close #663

**Comment by miketaylr** [comment]
I spent a lot of time today looking at mocking modules and servers, and too many of them make the assumption that we want to mock out python unit tests. So instead I came up with the following idea:

We have a `@api_mock('file.json')` decorator for API endpoints that checks if we're in `TESTING` mode, and if so it serves that file instead of requesting it from GitHub. It serves them from `tests/fixtures/`.

Right now this is a READ-only solution, so it won't work for all tests or endpoints. But it's a start.

**Comment by miketaylr** [comment]
Also need to figure out how to mock logins, and how to decide when to send some kind of fixture-auth.js and fixture-non-auth.js, etc.

**Comment by miketaylr** [comment]
Also figure out why this breaks nose:

```
..E......................
======================================================================
ERROR: API access to labels without auth returns JSON 401.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/miket/dev/compat/webcompat.com/tests/test_api_urls.py", line 68, in test_api_labels_without_auth
    json_body = json.loads(rv.data)
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

----------------------------------------------------------------------
Ran 25 tests in 1.128s
```

**Comment by miketaylr** [comment]
> Also need to figure out how... to decide when to send some kind of fixture-auth.js and fixture-non-auth.js, etc.

One ugly idea is to extend the decorator to take 2 args, and then decide which file to serve based on `g.user`:

`@api_mock(auth_fixture='file-auth.json', non_auth_fixture='file-non-auth.json')`

**Comment by miketaylr** [comment]
> Also figure out why this breaks nose

That's likely breaking because we're just serving the same file to authed and non-authed. The suggestion in my previous comment would fix it.

**Comment by miketaylr** [comment]
OK, just updated this so it's like `@api_mock('file-auth.json', 'file-non-auth.json')`. `None` can be used for either value.

**Comment by miketaylr** [comment]
Hmm, not super happy with this. It sort of falls apart with routes like `@api.route('/issues/category/<issue_category>')`. Thinking thinking. :thought_balloon:

**Comment by miketaylr** [comment]
OK, so the way around that is to do something like https://github.com/webcompat/webcompat.com/blob/6dcfa732390685ec27766bfd0d8dc582afeb1d93/webcompat/api/endpoints.py#L141-L144. Let's do a few more endpoints and see how it goes.

**Comment by miketaylr** [comment]
Another way to approach this is instead of passing in a string that refers to a file is to pass in the API route/request URL. That way we can handle fixtures for multiple issues, for example -- the func tests look for 69, 200, 100, 101, etc. We could use a little magick™ to detect auth state, and if not authed look for a `-non-auth.json` resource. 

Everybody loves magical APIs. :sparkles:

**Comment by miketaylr** [comment]
Or maybe I'm overthinking this. endpoints.py needs to worry about auth vs. non-auth. Let's just send a single fixture resource.

**Comment by miketaylr** [comment]
OK, more progress. Renamed `@api_mock` to `@mockable_response` and it will look for a fixture file that matches its `request.path` in the fixture dir.

**Comment by karlcow** [comment]
nice progress. :)

**Comment by miketaylr** [comment]
Thx @karlcow. :)

I think I'll add mocked responses for all the simple read-only GET stuff and then send a PR. And then we can work on mocking logging in and out and handling POST, PATCH, etc.

**Comment by miketaylr** [comment]
Another thought, right now I'm just copying responses by hand from GitHub and putting them in the fixtures folder. That seems prone to breaking in the future.

Ideally we'd have a `record` script or testmode or something that runs through the tests once and writes the GitHub responses to disk. To think about for future improvements.

**Comment by miketaylr** [comment]
Also it's a pain in the butt for stuff with GET args. >:|

**Comment by miketaylr** [comment]
One possible complication:

Our Python unit tests (specifically test_api_urls.py) are expecting specific content types and HTTP response codes. This current approach just sends everything as a 200.

Two "easy" solutions come to mind:

1) Don't run the nosetests in the `TESTING` environment, so they won't get the mocked responses. :cry: 
2) Use the fixture file to send some metadata and send the response according to that, maybe in a `_fixtures` key somewhere.

I'm gonna try 2 and see how it goes.

**Comment by miketaylr** [comment]
OK, I spent a few hours down the rabbit hole and am now opting for #1. ^_^

The tests that fail are the ones testing error situations--they don't even request data from GitHub. So it's a non-issue. If we do `webcompat.app.config['TESTING'] = False` in the test `setUp`, the @mockable_response` decorator won't have any effect.

**Comment by miketaylr** [comment]
I think I'm one final issue away from having something close enough to review:

We need to be able to send the `Link` header so pagination tests work correctly. I suppose doing metadata in a JSON key will work... and now I'm sort of kicking myself for deleting my work from a few hours ago that implemented that. >_< :bomb:

**Comment by miketaylr** [comment]
Currently at `11/61 tests failed` when running Intern w/ `python run.py -t`. Not bad!

**Comment by miketaylr** [comment]
Stashing failures to investigate later: https://gist.github.com/miketaylr/b4d69848da057465ed35

**Comment by miketaylr** [comment]
OK, one more issue to solve before squashing/cleaning up history and sending a PR:

Currently the labels test rely on setting a label, reloading the page, removing a label and then reloading the page. I think I can fake this w/ fixture data by sending a GET param, which won't do anything when connected to the network, but will tell us to load the right file when in test mode.

The other option is remove or rewrite those tests. :confused:

**Comment by miketaylr** [comment]
Hmm, no. The GET trick won't work because we're getting a template route, not an API endpoint. Hmm. :clock1:

**Comment by miketaylr** [comment]
Sigh, labels code is all broken anyways. I'm just going to remove these tests because they didn't catch us breaking what's broken. :( Bug incoming.
