### ISSUE TITLE
Prioritization of Issues at triage time

### ISSUE THREAD

**Issue by karlcow** [webcompat/webcompat.com#715]
See [Meeting](https://github.com/webcompat/webcompat.com/wiki/Paris-Work-Week/)
- lack of priority, severity, site ranking. We like the idea of adding prioritization at the triage level.
  Probably with UI and cute icons. @calexity @magsout 
  Need to work out how it should work.

**Comment by hallvors** [comment]
We were joking about labels 'severity-sucks', 'severity-bad', 'severity-catastrophic' - I think those are pretty good actually, although in the UI we could have icons for them. I think personally it should not be just at "triage time" but also exposed to bug reporters - it would be interesting to see how reporters classify issues.

I also suggest adding a feature that can order a bug list by the Alexa rank (or similar ranking system) of the reported websites.

**Comment by adamopenweb** [comment]
@karlcow After speaking with @miketaylr, he suggested we try to sort this out soon. With the reports coming from SoftVision now, there will be many bugs that should have different priorities. [Here's an example](https://webcompat.com/issues/4979) of a real bug, that probably isn't the highest priority to us.

I'm sure you'll have some suggestions as to how we could do this.

As for the labels themselves, it might make sense to replicate the [scale on Bugzilla](https://wiki.mozilla.org/Bugmasters/Process/Triage#How_Do_You_Triage): P1 to P5. Though I don't think we need to use all 5 groups.

In fact it would be nice if regular priority simply didn't have a label.

**Comment by karlcow** [comment]
and this is very close to what #1413 is aka labels for work status. This one here is another category. I have the feeling we are starting to reach the point of a giant workflow graph to understand better what we need, do and how we solve it. 

Also, maybe we need to think about all this meta-information in terms of work and UI and less in terms of labels.  "when all you have is a hammer everything looks like a nail" and I have the feeling it's what we are doing with our GitHub hammer and our need for UI.

**Comment by karlcow** [comment]
@miketaylr just gave me the https://github.com/servo/servo/labels as a counter-example. Indeed not bad.

**Comment by karlcow** [comment]
Just putting it here for remembering
http://imgur.com/a/ZueSo

![capture d ecran 2017-03-09 a 13 06 22](https://cloud.githubusercontent.com/assets/505230/23735662/501126fc-04ca-11e7-867d-7a7cff7f2899.png)
![capture d ecran 2017-03-09 a 13 12 05](https://cloud.githubusercontent.com/assets/505230/23735661/501073b0-04ca-11e7-9591-12bf6a441332.png)

**Comment by softvision-sergiulogigan** [comment]
I also support the use of Priority and/or Severity codes. We can use either a L-M-H Severity scale (Low-Medium-High), a Severity 1-5 or Priority 1-5 scale.

**Comment by miketaylr** [comment]
@adamopenweb and @karlcow will discuss how to move forward this week.

**Comment by karlcow** [comment]
So during the meeting this week [we discussed about prioritization](https://wiki.mozilla.org/Compatibility/Meetings/2017-05-09#webcompat_Priority_triage_.28miketaylr.29).

The resolution has been to have

1. to have ONE label for priority. 
2. to have the label set during the triage. 

We need to iron some details. See #1554 

I'm closing this.
