### ISSUE TITLE
Add rel=nofollow to URL links

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat.com#716]
This probably needs to happen somewhere in our markdown conversion lib: 

https://github.com/webcompat/webcompat.com/blob/master/webcompat/static/js/vendor/markdown-it.js

**Comment by hallvors** [comment]
I'm proposing a small change to markdown-it that would make this very easy: specify per-tag default attributes in config

https://github.com/hallvors/markdown-it/commit/af7920f619b1d1629efe6b6db352b98687f22789
Let's see if they take it.
