### ISSUE TITLE
Set up service to delete logs older than 14 days

### ISSUE THREAD

**Issue by karlcow** [webcompat/webcompat.com#717]
Once we start to collect we need to rotate and delete logs with a cron on the server side

**Comment by miketaylr** [comment]
We still want to do this, every 2 weeks to begin with.

**Comment by miketaylr** [comment]
ping @karlcow

**Comment by karlcow** [comment]
Requirements:

* `/usr/sbin/logrotate`
* `cron` working, probably in `/etc/crontab` for the handlers
* a directory of your choice on the machine for the logs only accessible to admins. calling it `/tmp/secretlogs/` for the purpose of the demo.
* The file for the logs should be only accessible to admins let's call it `webcompat.log`

Do we have already there this?

```
/etc/cron.daily/logrotate
```

This means that every day logrotate is started and we can create a logrotate conf file for it.

in `/etc/logrotate.conf`, there might be already other configurations, so you can add at the end.

```
/tmp/secretlogs/webcompat.log {
    rotate 14
    daily
    copytruncate
    create 700 webc_user webc_group
    dateext
    compress
}
```

You can test with 
`logrotate -s /var/log/logstatus logrotate.conf`

This should run daily and keep only the last 14 files, compress them, and put a date in the filename.

More options at http://www.linuxcommand.org/man_pages/logrotate8.html

**Comment by karlcow** [comment]
r? @miketaylr 
If you prefer me to do it on the server itself. 
I just need to remember how I setup my access there. :) no issue.

**Comment by miketaylr** [comment]
> Do we have already there this?
> 
> /etc/cron.daily/logrotate

yep! so it looks like we're all set to rotate logs, we just need to log stuff (which is what https://github.com/webcompat/webcompat.com/pull/1125 is for).

I'm happy to set this up on the server -- thanks!

**Comment by miketaylr** [comment]
> I'm happy to set this up on the server -- thanks!

Yeah right.

**Comment by miketaylr** [comment]
OK. This is set up. Thanks again for the guidance @karlcow. 🍰
