### ISSUE TITLE
Add border to "Report Bug" link/button/action

### ISSUE THREAD

**Issue by karlcow** [webcompat/webcompat.com#720]
Ask users if they understand that they need to click on the report bug for opening the form.

**Comment by adamopenweb** [comment]
We received a lot of feedback from Outreachy applicants that the Report Bug link isn't a great call to action.

**Comment by denschub** [comment]
How 'bout that?

![screen shot 2016-12-09 at 15 36 10](https://cloud.githubusercontent.com/assets/344777/21070168/63555148-be25-11e6-940a-73a7107f390e.png)

That's basically a `1px solid #414042` border with a 5px `border-radius`.

**Comment by miketaylr** [comment]
I think it looks good. WDYT @magsout?

**Comment by zoepage** [comment]
Asking myself what @lockettm thinks about that? :)

**Comment by magsout** [comment]
@miketaylr looks good.

**Comment by miketaylr** [comment]
I'd say let's ship it, if someone wants to submit a PR. 

(unless @lockettm objects ^__^)

**Comment by lockettm** [comment]
I like it, helps it stand out more.

**Comment by miketaylr** [comment]
Cool. Let's change the scope of this issue to be about adding the change.

**Comment by zoepage** [comment]
I am against the border. It disrupts the flow of the site. 
I feel, when we add a padding-top to the `report bug` the group of claim and link should be separated. Like in the following screenshot.
<img width="1433" alt="screen shot 2017-02-08 at 11 22 55 pm" src="https://cloud.githubusercontent.com/assets/562354/22760323/4c6373f0-ee56-11e6-9cd1-195fbf7805c1.png">

If this is not enough, we could still consider to turn the link into a button. (This should be considered anyway for mobile, but would also work for desktop.)

Something like this...
<img width="1433" alt="screen shot 2017-02-08 at 11 44 07 pm" src="https://cloud.githubusercontent.com/assets/562354/22760854/9fb5d8fc-ee58-11e6-909f-ba90bb7c1a6c.png">

**Comment by miketaylr** [comment]
I think both options are better than what we currently have, and the dark button is cool. +1

**Comment by karlcow** [comment]
The dark background is a cool option for this link (this is not a button 😛 ). 
Also I laughed at @zoepage's 

> I am against the border. It disrupts the flow of the site.

Agreed. Tell that to 🇺🇸
