### ISSUE TITLE
Have two sizes for one image

### ISSUE THREAD

**Issue by karlcow** [webcompat/webcompat.com#722]
When uploading an image. We can display a smaller version and keep the original which is linked from the smaller one. Depends on #710

**Comment by miketaylr** [comment]
I just saw that PIL has [Image.thumbnail(size, resample=1)](http://pillow.readthedocs.org/en/3.0.x/reference/Image.html#PIL.Image.Image.thumbnail). Very cool module.

**Comment by karlcow** [comment]
yep there are very cool things in pillow.

**Comment by miketaylr** [comment]
#710 dependency is fixed.

**Comment by miketaylr** [comment]
ping @karlcow

**Comment by miketaylr** [comment]
@karlcow what is the status here?
