### ISSUE TITLE
All issues page params should be updated, when reached from homepage search

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat.com#729]
Right now search works, but the model params aren't merged with `q` for some reason.

**Comment by hallvors** [comment]
Just noticed this morning that if I edit the query string to for example request 150 issues, the page still says "Show 50 issues" - is that what this bug is about?

**Comment by miketaylr** [comment]
@hallvors posssssibly. I opened #728 because apparently that exact same test (for the behavior you're describing) is breaking.

**Comment by miketaylr** [comment]
Ah, turns out this only happens if you're logged out. Which means I probably broke something when landing #563.
