### ISSUE TITLE
Write script to prepare changelog

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat.com#740]
Seems silly to do manually (we can tag the "add-to-changelog" manually and let it work from that).

**Comment by magsout** [comment]
Maybe using webhooks ?

**Comment by miketaylr** [comment]
Here's a simple way to do this:

1) script fetches all issues with the "add to changelog" labels: 

* https://api.github.com/repos/webcompat/webcompat.com/issues?labels=status%3A%20add%20to%20changelog

2. grab the PR (issue) URL and dump out some text that looks like the following:

```
X.X.X - YYYY-MM-DD
* PR title [Pull #NNNN](https://example.com/link/to/github/issue)
...
```
The user will have to determine the version number, but the date can be created. 

Bonus points for appending that to CHANGELOG.md, but dumping to console would be an OK first version (for copying and pasting).

3. remove the "add to changelog" label from each issue that was added to CHANGELOG.md

At that point, we could make it even nicer -- but this is the bulk of the manual work. Creating a commit and a tag isn't that much work.

**Comment by miketaylr** [comment]
Looks lie @karlcow is working on this.
