### ISSUE TITLE
Documentation on setting up local test instance should be more helpful

### ISSUE THREAD

**Issue by hallvors** [webcompat/webcompat.com#742]
I find several things about this section confusing (some of this is admittedly nitpicking but I'm trying to think like a newbie):
https://github.com/webcompat/webcompat.com/blob/master/CONTRIBUTING.md#configuring-the-server

> To test issue submission, you need to create a fake repo on github.

What is a "fake repo"? There is no button on Github to create a fake repo. You mean a test repository that can hold data you enter while testing or something like that.

> Let's assume your username is miketaylr.
> Create a new repository called nobody-look-at-this (or the name of your choice).

"For example, my user name is miketaylr and I created a new repository called .." and then link to it.

> You can now edit config.py and
>
>    provide pointers to repo issues URIs. ISSUES_REPO_URI = "&lt;user>/&lt;repo>/issues". 
> With the example, we chose it would be ISSUES_REPO_URI = "miketaylr/nobody-look-at-this/issues"

Rather than "With the example", say "For example, my setup needs to say ...". Also good with a comment in config.py itself explaining "replace &lt;user> with your GitHub user name" etc.
This variable is set two times in config.py and can also be read from environment variables. Where exactly is it best to set it for a local test setup?

> It is mandatory to create your own personal bot for local development. 

What is "your own personal bot"? This sounds rather advanced or scary.

> The instructions for creating a bot token are given on GitHub.

Github's terminology is "access token" or "personal access token" - it's better to be consistent.

> Once you created the token you can add it to the variable BOT_OAUTH_TOKEN = "".

After the os.environ.get() or set up an environment variable - which is recommended?

> This is the oauth token we use to report issues on behalf of people who don't
> want to give GitHub oauth access (or don't have GitHub accounts).
>    get the secrets for config.py

And now you really lost me - what are these secrets? Your Github user name and password - or something else? Why are environment variable names supposed to be FAKE_SECRET and FAKE_ID? In which of the three if/elif clauses should these be set?

**Comment by karlcow** [comment]
Thanks a lot @hallvors this needs to be adjusted. Specifically with the bug triage of Paris.

**Comment by miketaylr** [comment]
Good feedback. I'll update this.

**Comment by miketaylr** [comment]
OK, I pushed some fixes -- would be nice if you could take a look to see if they are less confusing @hallvors.
