### ISSUE TITLE
autofocus input SearchBar

### ISSUE THREAD

**Issue by magsout** [webcompat/webcompat.com#743]
If I open webcompat in webview on iOS:

I guess it's due to the attribute `autocomplete`

![img_3776](https://cloud.githubusercontent.com/assets/1997108/10247737/57367c44-691b-11e5-8596-b466a2949a3d.jpeg)

**Comment by miketaylr** [comment]
Hm, yeah probably `autofocus` attribute. I can take a look on Monday, my iOS devices are all back in Texas.
