### ISSUE TITLE
Split contibuting.md into several *.md

### ISSUE THREAD

**Issue by magsout** [webcompat/webcompat.com#745]
I think the file begins to be too long. Maybe we can split into serveral file like:

- Installation.md
- CodingStyle.md
- Contributing.md
-Test.md

And maybe add let summary in Contributing.md

etc...

**Comment by miketaylr** [comment]
That seems fine to me.  Would it break anything to put those individual files in the `/docs/` folder? (I don't really know much about what's going on there, @karlcow should).

**Comment by karlcow** [comment]
cf #264

**Comment by magsout** [comment]
@karlcow maybe we should closed this issue ? It's a duplicate of yours

**Comment by karlcow** [comment]
Yup. Thanks @magsout
