### ISSUE TITLE
Overlay with loader

### ISSUE THREAD

**Issue by magsout** [webcompat/webcompat.com#746]
I think add an Overlay when loader is launched could be a good idea .

Any thought ?

![capture d ecran 2015-10-05 a 11 16 40](https://cloud.githubusercontent.com/assets/1997108/10276919/c2c02986-6b52-11e5-95e7-6ee6474d9120.png)

**Comment by magsout** [comment]
The point is to show that UI is temporaly blocked.

**Comment by miketaylr** [comment]
@magsout yeah, we should do this if we're blocking on something (which hopefully doesn't happen much!).

I know we do this right now if you're uploading an image, andddd I forget when else. When specifically are you thinking?

**Comment by magsout** [comment]
>I know we do this right now if you're uploading an image, andddd I forget when else. When specifically are you thinking?

As my example, when we upload an image. For now, I see that here

**Comment by miketaylr** [comment]
Ah! I misunderstood. You mean in addition to the spinner, we have an overlay (grayed out or something similar to GitHub). :+1:

**Comment by miketaylr** [comment]
`E_TOO_EARLY`

**Comment by magsout** [comment]
>Ah! I misunderstood. You mean in addition to the spinner, we have an overlay (grayed out or something similar to GitHub). :+1:

Exactly ;)

>`E_TOO_EARLY`

Ah ah jetlag effect ;)

**Comment by karlcow** [comment]
Yup good idea about making it more obvious that something is happening.

**Comment by magsout** [comment]
Multiple option:

- Added a background-color with opacity: rgba(something)
- Added a filter, maybe a blur? (I like blur ;p)
- any other idea ?

**Comment by hallvors** [comment]
What if loading doesn't finish? Users get stuck on a fully blocked page?

**Comment by magsout** [comment]
@hallvors good point. Just add loader and disabled element when needed. Not entire page

**Comment by adamopenweb** [comment]
Was playing around with this a bit. Based on the last comments about blocking the entire page, I tried moving the loader div into form div and using position: relative to keep it there. It doesn't look too bad when large, but on smaller screens the padding on the left looks weird.

Suggestions?

<img width="1337" alt="lg" src="https://cloud.githubusercontent.com/assets/6587558/21165209/ff7a8c84-c16b-11e6-9a13-07e3d7213067.png">

<img width="740" alt="sm" src="https://cloud.githubusercontent.com/assets/6587558/21165210/ff7adf90-c16b-11e6-8516-7784f1e805b5.png">

**Comment by miketaylr** [comment]
Looks good! What about blocking out the entire viewport? I guess something like position fixed w/ height 100%?

**Comment by adamopenweb** [comment]
@miketaylr the div is setup to do that already I think. I changed it as per @hallvors comment if the loading doesn't finish, the navigation is inaccessible to the user. Not sure how often that will happen.

**Comment by miketaylr** [comment]
> Not sure how often that will happen.

I'm not sure if it's possible -- we hide the loader when we get an error.

https://github.com/webcompat/webcompat.com/blob/master/webcompat/static/js/lib/bugform.js#L415

https://github.com/webcompat/webcompat.com/blob/cc7ab4b24fbd6653e647192e0a8c939ecd1fe9a1/webcompat/static/js/lib/issue-list.js#L378

**Comment by magsout** [comment]
IMHO, I think it's not a good thing to block the entire page while loading. If something happens, the user can not click anywhere and must reload the entire page.

**Comment by zoepage** [comment]
As we decided on a solution in #1529, I'll close this one.
