### ISSUE TITLE
Make a "My Activity" page

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat.com#749]
From #442.

This issue is more specific. We want a page that shows:

1) Bugs that @mention you
2) Bugs that you reported.

**Comment by miketaylr** [comment]
@karlcow I forget what we decided exactly for this.

"My Activity" is going to link to `/me` which redirects to `/miketaylr` (in my case)? Is that correct?

**Comment by miketaylr** [comment]
* [ ] Make API endpoints for "mentions" and "reported"
* [ ] Make `/me` route in views.py that redirects to `/<username>`
* [ ] Write Backbone views
* [ ] Some kinda tests

**Comment by magsout** [comment]
>"My Activity" is going to link to `/me` which redirects to `/miketaylr` (in my case)? Is that correct?

@miketaylr yes, correct 👍

**Comment by miketaylr** [comment]
Thanks!

**Comment by miketaylr** [comment]
I think we should probably add pagination for each section, and only display maybe 5 or 10 issues for mentions/reported issues.

**Comment by miketaylr** [comment]
@magsout can you help with the headings? I just stole the markup from the browse-issues.html template, and it looks a little bogus. :p

This is in the `issues/749/1` branch.

**Comment by magsout** [comment]
@miketaylr I cleaned the markup and codebase..

**Comment by magsout** [comment]
It's just a begining

**Comment by miketaylr** [comment]
You're the best, @magsout.

**Comment by miketaylr** [comment]
A few things to tweak:
This seems like it cuts off suddenly. Maybe a little bottom margin on the last issue item?
![](https://cldup.com/Y43Zi9IQzz-2000x2000.png)

And here it looks a little unbalanced. Maybe we can split the bottom margin/padding of "miketaylr's activity" and the top margin/padding of "Issues reported by miketaylr"?
![](https://cldup.com/dlmeg3mHLw-2000x2000.png)

**Comment by magsout** [comment]
@miketaylr you renamed `mentionned-user.html`, but not in `user-activity.html` , right ?? I had an error when I pulled

**Comment by miketaylr** [comment]
Ugh, yes. Sorry about that. I can get to it in about an hour or so, orrrrr you can fix it now. ^_^

**Comment by magsout** [comment]
@miketaylr 

![capture d ecran 2015-10-06 a 20 18 25](https://cloud.githubusercontent.com/assets/1997108/10317998/7e81bdaa-6c67-11e5-913f-8cdb74e7ccca.png)
![capture d ecran 2015-10-06 a 20 18 51](https://cloud.githubusercontent.com/assets/1997108/10317999/7e83e8fa-6c67-11e5-8ad0-b6c9ea384450.png)

Seems different from you. I had some news utils class. Did you build css ? Or maybe some cache ?

**Comment by magsout** [comment]
>Ugh, yes. Sorry about that. I can get to it in about an hour or so, orrrrr you can fix it now. ^_^

:shipit:

**Comment by miketaylr** [comment]
:heart:

**Comment by miketaylr** [comment]
> Seems different from you. I had some news utils class. Did you build css ? Or maybe some cache ?

My bad. Forgot to re-build CSS. Sorry!

**Comment by miketaylr** [comment]
Things left to do: 

* [ ] Add pagination controls
* [ ] Possibly add "Show N" dropdown as well?
* [ ] Get visual feedback from @calexity

**Comment by miketaylr** [comment]
(I deployed this branch just now to staging if that makes it easier to take a look at). `http://staging.webcompat.com/me` is the link -- but apparently logging in is busted. Will take a look).

**Comment by miketaylr** [comment]
OK, broken login fixed.

**Comment by magsout** [comment]
@miketaylr 

There are views that are beginning to share. For example I just created a `IssueItem` view because it is used on the home page, on the list of issues, and now on the Activity view.

On the activity you want to add filters (`Pagination`,`Sorting`, `Dropdown`) when I look `models` they are all in the same file, and are based on IssueList logic. I think it would be better to create a model and therefore logical for each items, dropdown, sorting, pagination.

what do you think about it ? We could use them anywhere in the application more easily.

**Comment by magsout** [comment]
Just pushed on branch what I started about `IssueItem`

**Comment by miketaylr** [comment]
@magsout yeah, I agree. I think I even had a "TODO make this model its own file" comment somewhere in the dropdown code. +1 for making this stuff more modular.

**Comment by miketaylr** [comment]
Right now @magsout is in the process of splitting up the components (HOOOORAY), so let's wait on that getting down before wiring up the pagination/display N components. We're still waiting on @calexity's feedback, so we have time (I spoke with her and she's got some time on her calendar soon).

**Comment by magsout** [comment]
@miketaylr @karlcow 

there is a way to do this in pyhton :

php example
```
<?= $this->partial('Dropdoown.phtml', array(
 'size'		=> 'medium'
)) ?>
```

Passed logic in partial view ?


We have 4 Dropdown. Same base, but we passed logic inside (size, js-*). So I don't want to duplicate code and just passed with include some logic.

**Comment by miketaylr** [comment]
We should be able to, yeah. We have access to a few variables in the template by default: http://flask.pocoo.org/docs/0.10/templating/#standard-context

We can also pass in data from the view function, like in https://github.com/webcompat/webcompat.com/blob/master/webcompat/views.py#L136. So we could create a variable like "size" and pass that into whatever template is including the dropdown. Then from the template itself:

```
return render_template('index.html', form=bug_form,
                               browser=browser_name, dropdown_size='medium')
```

````
{% if dropdown_size  == 'medium' %}
  etc
{% elif dropdown_size  == 'FRIGGIN HUGE' %}
```

Etc.

**Comment by magsout** [comment]
ah hum, so its' depend about controller and not view itself ?

There is no way to send an array or an object directly with include directive ?

**Comment by magsout** [comment]
Something like `{% include "web_modules/pagination.html" Object({size=> "medium"}) %}`

**Comment by magsout** [comment]
Ok, ok, I understand the logic. `view.py` is a rooter ? It's not exactly what I thiught, but seems good.

**Comment by magsout** [comment]
@miketaylr `/issue` page have 3 `Dropdown`, so add variable in `view.py` is not usefull because it works for each file incude. How I can make the difference between each Dropdown ?

**Comment by magsout** [comment]
Ok so, I just pushed what I did @miketaylr 

I used macro for Pagination, I thought it would be a good idea (or not) so tell me what do you think.

cc @karlcow 

https://github.com/webcompat/webcompat.com/commit/7e0305e93c4dc3710b356f70f8f554fbf390c5d3

If all is good, next step, JavaScript

**Comment by miketaylr** [comment]
Awesome, will check it out today (was on PTO on Friday, sorry for the delay).

**Comment by miketaylr** [comment]
This looks good to me, and all our tests pass. So if you broke something, we don't know about it yet. ^_^

Let me get started on the JS to hook up the dropdown and pagination components for the activity page (probably tomorrow).

**Comment by magsout** [comment]
>This looks good to me, and all our tests pass. So if you broke something, we don't know about it yet. ^_^

Just move the markup so I think it's normal that Travis are happy :)


>Let me get started on the JS to hook up the dropdown and pagination components for the activity page (probably tomorrow).

Cooool. I think after that we could make a PR, because there is lot of commit on this banch and the review will be hard..

**Comment by miketaylr** [comment]
Yeah. I see you're working on some issues with @karlcow on the python bits, so I'll hold off on the JS until you give me the thumbs up.

**Comment by magsout** [comment]
@miketaylr If you want you can start to work on JS. The part I'm doing with @karlcow is about `FIlter`, so not depend for activty page.  

:heart:

**Comment by miketaylr** [comment]
Ah cool. Will start today.

**Comment by magsout** [comment]
awesome ;) I'm very curious how you'll do that.

**Comment by miketaylr** [comment]
> awesome ;) I'm very curious how you'll do that.

Yeah, me too...

**Comment by magsout** [comment]
Ah ah don't worry, I know that you're a rock star

![rock_star_2](https://cloud.githubusercontent.com/assets/1997108/10467572/e3343d20-71fa-11e5-9501-6a18b46613c1.gif)

**Comment by miketaylr** [comment]
OK, I'll start with just the pagination stuff. It looks like that's pretty tightly coupled with the issue-list code, so I need to see how to split that up.

**Comment by miketaylr** [comment]
- [ ] Make sure we're serving `creator`, `mentioned` w/ appropriate pagination/`Link` header
- [ ] Move pagination methods from issue-list.js into the `IssueCollection` Collection.

**Comment by miketaylr** [comment]
Reminding myself, Github will only send a Link header if there are more than 30 items, unless you request a different number via `per_page=N` (and have more than that).

**Comment by miketaylr** [comment]
For now I'm gonna hard-code this to `per_page=10`, and we can change that once we have the dropdowns set up.

**Comment by miketaylr** [comment]
- [ ] Move `PaginationMixin` into own file
- [ ] Implement `fetchAndRenderIssues` and `updateModelParams` in `MyIssuesView` (or re-think how to approach this) and `IssueMentionsView`
- [ ] Add `PaginationMixing` to `MyIssuesView` and `IssueMentionsView`

**Comment by miketaylr** [comment]
Oops, looks like we need to update the tests @magsout.

```
FAIL: main - Issue-list - FilterView renders (10612ms)
AssertionError: All filter buttons are displayed: expected 0 to equal 6
```
A lot of the other failures look "filter"-related: https://travis-ci.org/webcompat/webcompat.com/builds/85965196

**Comment by magsout** [comment]
Actually, there is no filter displayed https://github.com/webcompat/webcompat.com/commit/432ba9ee22ef0a49198cc97507262c0510973a78#commitcomment-13759514


I think that's why travis returns errors. We try to find a solution with @karlcow  to outsource categories to avoid redefine everywhere. but when I do my foreach, the variables seem not to exist

**Comment by miketaylr** [comment]
Ah, OK. Gotcha. Thx @magsout . 

I'm not really worried about those tests right now. Something we'll fix before we land.

**Comment by magsout** [comment]
@miketaylr ok, Categories (Filters) are working now. Thanks @karlcow for you awesome help. There is a good start about our `web`module`  Just wait to see if Travis is happy with that

**Comment by magsout** [comment]
Arg failed of cours, `config.py` is not updated...

**Comment by miketaylr** [comment]
I think I just need to implement `fetchAndRenderIssues` for the two my activity issues views and then we're good for a PR.

**Comment by miketaylr** [comment]
And tests. :)

**Comment by magsout** [comment]
@miketaylr Why did you include the IssueList view of pagination ? listhttps://github.com/webcompat/webcompat.com/blob/issues/749/1/webcompat/templates/user-activity/user-mentions.html#L5

or maybe it's me, don't remember...

**Comment by miketaylr** [comment]
Looks like it was me! https://github.com/webcompat/webcompat.com/commit/8ab52f67aa984c5efc73ad1ee7d53e217b7902bc

@magsout should I be using something else? My idea was to reuse the existing templates, but I might have grabbed the wrong thing.

**Comment by magsout** [comment]
In fact we have to import only these view https://github.com/webcompat/webcompat.com/tree/issues/749/1/webcompat/templates/web_modules

But maybe these view are incomplete ? Maybe I missed something in this view https://github.com/webcompat/webcompat.com/blob/issues/749/1/webcompat/templates/user-activity/reported-by-user.html ?

**Comment by miketaylr** [comment]
OK, so close!

One final bug (before looking at failing tests + writing tests) to fix: `PaginationMixin` needs to be smarter such that having more than one instance of the `_nextButton` and `_prevButton` doesn't affect the other pagination controls on a page. (right now they're just doing a silly `  _nextButton: $('.js-pagination-next'),
`, etc.

I can get a reference to the parent view and scope the jQuery find off of that, I think.

**Comment by miketaylr** [comment]
So my tiny bug revealed a larger flaw in my plan. Hope to get some time to hack on it this weekend. For now I need to work on some spec stuff. :crying_cat_face:

**Comment by miketaylr** [comment]
OK! Just need to write some tests and we're good for a review. ^_^

**Comment by miketaylr** [comment]
@magsout was it intentional to leave out "contactready" from config.py? 

https://github.com/webcompat/webcompat.com/commit/6dae47b26bb73a82f3a95f4655c9c1a167b8dded

**Comment by karlcow** [comment]
@miketaylr Probably a mistake from me.

**Comment by miketaylr** [comment]
No worries @karlcow -- just wanted to be sure I didn't miss a decision to rip out that category. :)
