### ISSUE TITLE
Error setting up webcompat locally  

### ISSUE THREAD

**Issue by haseebgit** [webcompat/webcompat.com#750]
npm ERR! System Linux 3.19.0-28-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /home/haseeb/webcomp/webcompat.com
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.4.21
npm ERR! path /home/haseeb/webcomp/webcompat.com/node_modules/grunt-cssnext/node_modules/cssnext/node_modules/postcss-url/node_modules/directory-encoder/node_modules/img-stats/node_modules/xmldom/test/test.xml
npm ERR! fstream_path /home/haseeb/webcomp/webcompat.com/node_modules/grunt-cssnext/node_modules/cssnext/node_modules/postcss-url/node_modules/directory-encoder/node_modules/img-stats/node_modules/xmldom/test/test.xml
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack /usr/lib/nodejs/fstream/lib/writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (evalmachine.<anonymous>:107:15)
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/haseeb/webcomp/webcompat.com/npm-debug.log
npm ERR! not ok code 0
Makefile:2: recipe for target 'install' failed
make: *** [install] Error 34

**Comment by miketaylr** [comment]
It looks like you have Node installed. Can you paste the contents of npm-debug.log in a comment or a gist?

**Comment by miketaylr** [comment]
Also, your exact setup details some steps to reproduce would be helpful.

**Comment by miketaylr** [comment]
A few things to try, `npm cache clean` and then try again, or updating npm. This sort of looks like https://github.com/npm/npm/issues/6043, but I can't tell w/o the npm-debug.log.

**Comment by haseebgit** [comment]
i am running sudo make install
[npm-debug.txt](https://github.com/webcompat/webcompat.com/files/8551/npm-debug.txt)

**Comment by haseebgit** [comment]
I installed npm globally and it worked

`npm install -g npm`

`npm install -g grunt-cli`

**Comment by miketaylr** [comment]
I wonder if re-installing npm worked because it updated it? Anyways, glad it's working now!
