### ISSUE TITLE
Navbar Small Device

### ISSUE THREAD

**Issue by magsout** [webcompat/webcompat.com#753]
![capture d ecran 2015-10-07 a 07 52 40](https://cloud.githubusercontent.com/assets/1997108/10330027/6eeffdc8-6cc8-11e5-9f96-085b9a791c64.png)

Maybe replace download label by an icon

**Comment by miketaylr** [comment]
Maybe we should consider being smarter with the "Download our Add-on" link, moving it, only showing it some times? To think about...

**Comment by karlcow** [comment]
Should it be moved to the user profile?
As in someone who download the addon is ready to invest more time into webcompat.com and so download an add-on?

**Comment by miketaylr** [comment]
Hmm, maybe we do something sneaky like have the addon inject a DOM element like `<div style="display: none"class=addon-installed></div> (obviously only for webcompat.com host). It is silly to display that message if you already installed it.

**Comment by magsout** [comment]
@miketaylr it's possible to detecte if the addon is already installed ?

**Comment by magsout** [comment]
hum, ah yes, of course, this is not the site that will detect it, but the addon that will be injected into the DOM
