### ISSUE TITLE
Configure web-bugs repo to use self-hosted hook endpoints

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat.com#755]

**Comment by karlcow** [comment]
@miketaylr Explanation? :)

**Comment by miketaylr** [comment]
Basically this just means update the GitHub repo settings to point to the correct endpoint.

**Comment by miketaylr** [comment]
(there won't be any review because no code is involved)

**Comment by miketaylr** [comment]
Also, this needs to be done post-deploy, not before. ^_^

**Comment by hallvors** [comment]
Per the repo settings it seems this is still an issue - not sure if the relevant bits are deployed
