### ISSUE TITLE
run.py depends on cat, why?

### ISSUE THREAD

**Issue by hallvors** [webcompat/webcompat.com#758]
Trying to run run.py on Windows fails because it tries to call the cat command on line 63:

    req = subprocess.check_output(["cat", "requirements.txt"]).splitlines()

The easiest workaround is to do ```run.py -t``` to launch "test mode", and I guess we'll never ever run this on a system where 'cat' is not available for production. But why depend on cat in the first place?

    for req in open("requirements.txt"):
        pkg_resources.require(req)

should do, I think.

**Comment by karlcow** [comment]
@hallvors is talking about https://github.com/webcompat/webcompat.com/blob/2936db395e918ecb1036c2f9e5d9046073688d70/run.py#L57-L71

**Comment by karlcow** [comment]
That was my commit https://github.com/webcompat/webcompat.com/commit/725289180b4cf3603c9dc345d555ecc04f7b0e89

And yes good comment. Your proposal is a good one.  Also possible.

```python
try:
   pkg_resources.require([req for req in open("requirements.txt")])
```

**Comment by hallvors** [comment]
Wow, even more brief :)

**Comment by miketaylr** [comment]
Cool, learned some more Python today. ^_^
