### ISSUE TITLE
The image is not displayed in the comment

### ISSUE THREAD

**Issue by magsout** [webcompat/webcompat.com#764]
See https://webcompat.com/issues/1806

![capture d ecran 2015-10-13 a 22 19 14](https://cloud.githubusercontent.com/assets/1997108/10467151/73f781a8-71f8-11e5-8f41-44df5578a08c.png)

**Comment by miketaylr** [comment]
Hmm, I wonder if this is related to the Markdown changes that @hallvors introduced.

**Comment by hallvors** [comment]
Hm.. strange. Nothing I added or changed seems relevant - our markdownit options have html:true set and I didn't change that..

**Comment by hallvors** [comment]
(I made a first attempt at debugging but was inconvenienced by discovering https://bugzilla.mozilla.org/show_bug.cgi?id=1214524 - I still think it's not related to my changes but since I have done some work with MarkdownIt I might as well try to understand this)

**Comment by magsout** [comment]
thanks @hallvors

**Comment by miketaylr** [comment]
Hmm, I just noticed that sometimes I get the following when uploading an image:

```
![screen shot 2015-10-15 at 11 29 23 pm](https://cloud.githubusercontent.com/assets/67283/10544316/446094e2-73e8-11e5-8cc5-3634ec782174.png)
```

But sometimes I get `<img src....` from GitHub issues. Odd.

I wonder if we can whitelist `<img>` elements in our markdown lib? I wonder if it's escaping the HTML to protect us.

**Comment by hallvors** [comment]
The IMG element HTML is encoded to HTML entities by the markdownitSanitizer. It has some regular expression-based processing of IMG here:
https://github.com/webcompat/webcompat.com/blob/master/webcompat/static/js/vendor/markdown-it-sanitizer-0.3.0.js#L112
The problem is as far as I can tell that their regexp expects a certain order of attributes. Unless the *first* attribute of the IMG tag is ```src```, it won't be recognised as an IMG tag by this regexp:
https://github.com/webcompat/webcompat.com/blob/master/webcompat/static/js/vendor/markdown-it-sanitizer-0.3.0.js#L97

That's not exactly elegant..? :-/

**Comment by hallvors** [comment]
Watch this: https://github.com/svbergerem/markdown-it-sanitizer/issues/4

**Comment by miketaylr** [comment]
> Unless the first attribute of the IMG tag is src, it won't be recognised as an IMG

:/

**Comment by hallvors** [comment]
@miketaylr how important is the markdown-it-sanitizer? Is it our main anti-XSS defence? Do you know of any alternatives?

**Comment by miketaylr** [comment]
> how important is the markdown-it-sanitizer? Is it our main anti-XSS defence? 

For markdown, yeah. We could always switch to another JS markdown parsing lib, as long as it meets our needs. Or we could just fix the bug ourselves and send a PR. Is it enough to just make all the img attribute expressions optional?

> Do you know of any alternatives?

Not really. But I'm sure there's more than one out there.

**Comment by miketaylr** [comment]
To explore: https://github.com/wooorm/mdast

**Comment by Mte90** [comment]
This problem exist also here https://webcompat.com/issues/1945

**Comment by hallvors** [comment]
There is a new version of the MD sanitizer: https://github.com/svbergerem/markdown-it-sanitizer/issues/4#issuecomment-152451423 - I have an update patch.

**Comment by hallvors** [comment]
(For the record, more regular expressions are still around - as far as I can tell ``<a href="" title="">`` will be recognised OK but not ``<a title="" href="">`` .. https://github.com/webcompat/webcompat.com/blob/master/webcompat/static/js/vendor/markdown-it-sanitizer-0.4.1.js#L40 )
