### ISSUE TITLE
Label in webcompat.com repo

### ISSUE THREAD

**Issue by magsout** [webcompat/webcompat.com#765]
What do you think about use these labels in webcompat.com repo https://github.com/putaindecode/putaindecode.fr/labels ?

**Comment by miketaylr** [comment]
Seems good to me. @karlcow?

**Comment by karlcow** [comment]
sounds good to me @magsout except for the rockstar and the fuck off. ;) And some of them seem out of topic for webcompat.com, could you explain a bit more what they mean and in which circumstances, we use them.

**Comment by miketaylr** [comment]
FWIW, I assume @magsout meant the style of labels and not the exact labels. I also agree w/ @karlcow we wouldn't want... certain ones. :)

**Comment by magsout** [comment]
Yes of course it's for `PR, status, type, level` labels I propose that list. The rest has no interest in webcompat. The label AutoMerge and fuck off either, I know this is not the kind of webcompat ;)I want to clarify labels and have a better reading (from my point of view) of the labels in the repo
