### ISSUE TITLE
Contributing guide: npm install

### ISSUE THREAD

**Issue by haseebgit** [webcompat/webcompat.com#766]
1) npm should be stable version, webcompat.com doesn't work with latest version
2)  If `sudo make install` then `sudo python run.py`

**Comment by miketaylr** [comment]
@hallvors how do we determine what's "stable"? Did you install npm from GitHub to get a non-stable version?

**Comment by karlcow** [comment]
s/ @hallvors / @haseebgit / above ;)

**Comment by miketaylr** [comment]
Oops, thanks @karlcow.

**Comment by haseebgit** [comment]
Updating npm leads to beta version i think, so therefore if ran 
`sudo npm install -g n`
`sudo n stable` 
and it worked

**Comment by miketaylr** [comment]
Hang on, `n` is a [NodeJS version manager](https://www.npmjs.com/package/n). Is this bug actually about which version of Node.JS works w/ webcompat, rather than npm? (That would be less surprising than npm).

**Comment by miketaylr** [comment]
@haseebgit can you paste the actual error you ran into?

**Comment by haseebgit** [comment]
I have a screenshot of the error
http://www.awesomescreenshot.com/image/666327/ee348609612a2318fd44c76faec81504

**Comment by miketaylr** [comment]
Hm. That error is about something not working with Intern 2.2.0. Does npm-debug.log give any clues?

**Comment by vladikoff** [comment]
@haseebgit here's my output on os x with node 4 and latest npm3:
```
➜  pj2  nvm use 4
Now using node v4.0.0 (npm v2.14.2)
➜  pj2  sudo npm i -g npm@3
Password:
/Users/vladikoff/npmlocal/bin/npm -> /Users/vladikoff/npmlocal/lib/node_modules/npm/bin/npm-cli.js
npm@3.3.8 /Users/vladikoff/npmlocal/lib/node_modules/npm
➜  pj2  npm i intern@2
npm WARN package.json pj2@1.0.0 No description
npm WARN package.json pj2@1.0.0 No repository field.
npm WARN package.json pj2@1.0.0 No README data
npm WARN excluding symbolic link query -> vendors/jquery/src/
npm WARN excluding symbolic link query -> vendors/jquery/src/
|
> intern@2.2.2 install /Users/vladikoff/tmp/pj2/node_modules/intern
> node support/fixdeps.js

intern@2.2.2 node_modules/intern
├── diff@1.1.0
├── charm@0.2.0
├── source-map@0.1.33 (amdefine@1.0.0)
├── chai@1.9.1 (assertion-error@1.0.0, deep-eql@0.1.3)
├── leadfoot@1.2.1 (dojo@2.0.0-alpha4)
├── digdug@1.2.1 (dojo@2.0.0-alpha4, decompress@0.2.3)
├── istanbul@0.2.16 (which@1.0.9, abbrev@1.0.7, nopt@3.0.4, wordwrap@0.0.3, async@0.9.2, mkdirp@0.5.1, resolve@0.7.4, fileset@0.1.8, esprima@1.2.5, escodegen@1.3.3, handlebars@1.3.0, js-yaml@3.4.3)
└── dojo@2.0.0-dev
➜  pj2  
```

Try downgrading to old npm 2 or reinstalling... it MAY BE an ubuntu issue, but I hope not.

**Comment by karlcow** [comment]
@haseebgit is it still an issue?
Or did the project move so much that it is not a valid issue anymore?

**Comment by haseebgit** [comment]
@karlcow safe to close the issue :)

**Comment by zoepage** [comment]
@haseebgit thank you :)
