### ISSUE TITLE
Integrate travis ci with webcompat IRC for notifications

### ISSUE THREAD

**Issue by haseebgit** [webcompat/webcompat.com#768]

**Comment by haseebgit** [comment]
More about the notifications docs http://docs.travis-ci.com/user/notifications/

**Comment by magsout** [comment]
yeah good idea. And maybe integrate issue and PR (on irc) ?

**Comment by miketaylr** [comment]
I'm afraid this might get noisy for people who aren't working on the site. Maybe we could make a new channel (maybe #webcompat-dev?) and dump all the notifications there. ^_^

**Comment by haseebgit** [comment]
it might get little noisy but it will show others that we are active, btw i am thinking of only PR merged notifications

**Comment by miketaylr** [comment]
> it will show others that we are active

Is there a perception that we aren't active in the IRC channel?

**Comment by hallvors** [comment]
If anything, IMHO the IRC channel is often too quiet.. I'd support small pings for new PRs and merged PRs. Not sure about Travis though..

**Comment by miketaylr** [comment]
Let's not do this.
