### ISSUE TITLE
Write script to generate fixture files

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat.com#777]
Ideally we could run the app in "record" mode, and all API responses it got back from GitHub it would save to the `tests/fixtures` folder. And then we could nuke the old fixtures from time to time and get "fresh" ones.

cf. #712.

**Comment by marimeireles** [comment]
Hm... That's what my get fixtures mode did. Isn't it?

**Comment by karlcow** [comment]
@marimeireles yes. and that was October 17, **2015**. Many things happened since which is the sense of #2756 issue. Let's close this one. Thanks @miketaylr for unearthing that dinosaurs skeleton! 😆 🦎

**Comment by marimeireles** [comment]
hahaha
it's okay :p

**Comment by karlcow** [comment]
Also just for the record. There is a [vcrpy module](https://vcrpy.readthedocs.io/en/latest/) which has some of these capabilities that @miketaylr was talking about (when we were still painting on cave walls with our hands).
