### ISSUE TITLE
Figure out how to mock POST/PUT/PATCH 

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat.com#778]
Right now we just mock GET.

cf. #712.

**Comment by karlcow** [comment]
food for thougts https://www.appneta.com/blog/python-unit-test-mock/

**Comment by karlcow** [comment]
@brizental we are probably done! :) Thanks a lot.

**Comment by miketaylr** [comment]
Yeah, what @karlcow said. Thanks!
