### ISSUE TITLE
Labels editor forgets selected labels when you've made changes once

### ISSUE THREAD

**Issue by hallvors** [webcompat/webcompat.com#784]
1) Go to issue, for example https://webcompat.com/issues/1
The issue should have two labels: "firefox" and "sitewait"

2) Open label editor and apply another label, for example "windows". Click "Save and close"

3) Open label editor again

Bug: no labels are selected. If you close the editor unaware of this state, it will remove all labels from the issue.

**Comment by magsout** [comment]
Hum yes confirmed... 

But if you refresh page and open Editor labels are selected.

**Comment by miketaylr** [comment]
Yeah, this is likely some kind of regression. It's worked in the past.

**Comment by hallvors** [comment]
The code just throws the response model at the issue. I'm not sure if that ever worked? Anyway, I have a fix.

**Comment by hallvors** [comment]
(Bug is here: https://github.com/webcompat/webcompat.com/blob/master/webcompat/static/js/lib/models/issue.js#L219 - not sure what exactly the response object is, but it takes a little more work to get the labels array..)

**Comment by karlcow** [comment]
What I see myself.

1. Go to a bug with already a label
2. Click on label widget
3. Select an additional label
4. The previous ones disappear from the list
5. clicking out of the box, only the one you have selected is saved, the old one has disappeared.

This doesn't always happen. I haven't identified if it's a specific label or if it's an HTTP issue.

**Comment by hallvors** [comment]
The specific label firefox-mobile will always disappear because we don't have it in the current set of labels. What probably happens here is that it's the only legacy label with a hyphen in it, and since we use hyphens as a "namespace" separator, the code will handle "firefix-mobile" as a label called "mobile" in the namespace "firefox". Since we AFAIK also have a label called just "mobile", we most likely end up applying that label instead.

I think we should kill the firefox-mobile label. It's going to be very confusing to have some labels with hyphens that are *not* intended to be namespaced, although if we move to a hard-coded set of labels it won't be impossible to do so.

**Comment by karlcow** [comment]
all new bugs are written with `firefox-mobile` so webcompat-bot is setting the firefox-mobile maybe we need to change that.

**Comment by karlcow** [comment]
See https://github.com/webcompat/web-bugs/labels/browser-firefox-mobile

**Comment by hallvors** [comment]
hm.. that's browser-firefox-mobile. OK, I need to debug this.. #798 is probably invalid.
