### ISSUE TITLE
Clicking label to filter list does not work on the front page

### ISSUE THREAD

**Issue by hallvors** [webcompat/webcompat.com#787]
Like #693 on the issues list, clicking a label to see only issues with that label does not do anything on the webcompat.com front page.

The underlying reason is that this functionality is in issues-list.js, and the front page does not include issues-list.js yet uses the same (or similar) markup and UI.

Options:
* Make the labels unclickable (IMHO it's not a great loss of functionality)
* Make the label links go to the /issues/ page with a suitable query string and don't use JS click handlers
* Include issues-list.js on front page

Opinions?
@miketaylr , @karlcow , @magsout , @calexity ?

**Comment by miketaylr** [comment]
Oops, that's an oversight.

I think the first two options are fine, originally we didn't show labels on the homepage but I think they snuck in when we were doing some consolidation of templates/styles. (Because I'm lazy I would probably just remove the hyperlinks).
