### ISSUE TITLE
[Discussion] clicking several labels on issues list should accumulate, not replace them

### ISSUE THREAD

**Issue by hallvors** [webcompat/webcompat.com#795]
When you load a list of issues you may want to easily see all "Needs contact" for "IE", or all "Needs diagnosis" for "firefox". You can click labels for various workflow steps (like "Needs contact") at the top, and you can click labels like "firefox" next to the bug summary. However, if you click first "Needs contact", then "firefox", the latter action will cancel out the first one.

The way the UI is organised indicates strongly that it should be possible to combine at least one of the top-level workflow statuses with some other tag or search. It would be useful to make that work.

Personally I'd suggest that clicking other labels _always_ should accumulate them, and I'd also like to see a small UI where selected labels appear and can be "deleted" again with a little x - this is a common UI idiom when searching by labels or keywords now.

So @webcompat/owners and @webcompat/collaborators - please discuss :)

**Comment by magsout** [comment]
:+1: 

I agree with you. 

Already as we discussed in Paris, we must reorganize general UI because there are inconsistencies between the `closed` Filter and `open all issue` dropdown. 

Then we could add the ability to accumulate labels. 

To be sure we are talking about the same thing. `labels` are the links (firefox, chrome, android, mobile) in Issue item?

**Comment by hallvors** [comment]
>  labels are the links (firefox, chrome, android, mobile) in Issue item?

Exactly.

**Comment by hallvors** [comment]
The labels across the top are *status* labels. Other labels are mostly browser/platform stuff. It should not be too hard to change the relevant code so that clicking a status label removes any other status labels from the search, but leaves any other labels alone..

**Comment by hallvors** [comment]
Should we replace the word "Open" in the drop-down with [status] while we're at it?
I think I'll just write some code here and see if it makes sense, so I'll take this bug :)

**Comment by hallvors** [comment]
Here's how my UI change looks at the moment:

![wcnewsearch](https://cloud.githubusercontent.com/assets/120136/11514899/3d2da23e-987b-11e5-9b36-8ccab54368ab.png)

Note how the top category "Needs Diagnosis" is active *and* labels I've clicked in the main list are added with Xes to remove them again underneath the search field.

**Comment by miketaylr** [comment]
Ah, interesting. In general I like the idea, but we should refine the design a bit. Not crazy about the gradients and the big red X (sorry to bikeshed :bike: :house:, will go look at the code now).

**Comment by hallvors** [comment]
No problem, just used some existing file that happened to have gradient and red X :) 
This is obviously a topic we'd love @magsout  and @calexity to chime in on..

**Comment by hallvors** [comment]
The new PR: https://github.com/webcompat/webcompat.com/pull/846
(Seems GitHub doesn't automatically link to a PR from an issue even when the PR claims to fix that issue..?)

**Comment by hallvors** [comment]
I've listed some issues for discussion / explanation when we look at this together:
https://public.etherpad-mozilla.org/p/webcompat-site-search
@magsout sorry you can't be here, if you have questions based on that etherpad please ask them :)

**Comment by hallvors** [comment]
(I wonder why normalizeAPIParams() exists here: https://github.com/webcompat/webcompat.com/blob/master/webcompat/static/js/lib/models/issue.js#L190 - might be or at least should be obsolete with the new QueryParams model)

**Comment by miketaylr** [comment]
> I wonder why normalizeAPIParams() exists here

Was added in https://github.com/webcompat/webcompat.com/commit/142b30fbe48f28c7e7ff05456de352f02eab6083#diff-d8615cb1f2c6198fdc8508e11290b0bb to support un-authenticated search. Not sure if QueryParams can handle that, but we need to keep the feature.
