### ISSUE TITLE
The browser-firefox-mobile label is always removed when editing labels

### ISSUE THREAD

**Issue by hallvors** [webcompat/webcompat.com#799]
See https://github.com/webcompat/webcompat.com/issues/784#issuecomment-151056209

**Comment by hallvors** [comment]
It will work with the #796 code

**Comment by miketaylr** [comment]
Fixed by https://github.com/webcompat/webcompat.com/commit/d6b97ead05d0433d77e6c620d95632f18fb61002.

**Comment by miketaylr** [comment]
@hallvors I just deployed the new code and it seems this bug isn't fixed.

See https://webcompat.com/issues/1840, for example.

**Comment by miketaylr** [comment]
Oops, accidentally just nuked the label. `firefox-mobile` also doesn't appear in the label editor. Wild guess: could the `-` be causing trouble?

**Comment by miketaylr** [comment]
I just created a `browser-firefox-mobile` label for the webcompat-tests repo (if you use that for local testing): https://github.com/webcompat/webcompat-tests/issues/291

**Comment by hallvors** [comment]
@miketaylr The reason it gets accidentally nuked is that it is missing in the official list of "all labels" - https://webcompat.com/api/issues/labels data lacks browser-firefox-mobile . I don't see browser-chrome-mobile either and I think it exists. Why? You ask for 'n' labels from Github and we have more than 'n' total or something? Nope, I don't see it if I do GET https://api.github.com/repos/webcompat/web-bugs/labels either.

Maybe we should just move to a config solution..? Or can you have a look at GitHub API docs to see if you figure out this?

**Comment by miketaylr** [comment]
Oh, that's goofy. Let me just add a label to the repo manually. And then let's move to a config solution at some point in the future.

**Comment by miketaylr** [comment]
...except I see both `browser-chrome-mobile` and `browser-firefox-mobile` at https://github.com/webcompat/web-bugs/labels :ghost:

**Comment by miketaylr** [comment]
This might be "file a bug with GitHub support" territory.

**Comment by hallvors** [comment]
Agree. There is something odd about the GitHub backend here.

**Comment by miketaylr** [comment]
I emailed GitHub support.

**Comment by miketaylr** [comment]
Oh, how silly.

https://developer.github.com/v3/issues/labels/ shows (in the sample response) that labels are *paginated*. 

A few options:

1) Add a `per_page=100` param to the model URL. We probably won't have more than that for a while. :smile: 
2) Parse and traverse link headers (we have some code here that does this already: https://github.com/webcompat/webcompat.com/blob/master/webcompat/static/js/lib/models/issue.js#L214-L256)
3) Make a config-based API endpoint to serve our own list of labels.

I would say, we do a quick fix with 1, then work on 3.

**Comment by miketaylr** [comment]
I've got a quick fix ready. Gonna take this one.

**Comment by hallvors** [comment]
Regarding that proposed fix: I'd suggest doing it all at the backend, to change less code.. In any case I'm also proposing a competing fix that closes #781, so take whichever you want :)

**Comment by miketaylr** [comment]
@hallvors can you r- the PR and close it then? The idea was to have a working fix in a few days before #781 is done, but those few days are over now. :p
