### ISSUE TITLE
Image uploading rejects uppercase file extensions

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat.com#802]
`.PNG` and `.JPEG` etc.

**Comment by miketaylr** [comment]
Just need to `toLowerCase` `ext` here: https://github.com/webcompat/webcompat.com/blob/master/webcompat/static/js/lib/bugform.js#L96

(and then double check that the python side doesn't care)

**Comment by karlcow** [comment]
Regression.
<img width="746" alt="Capture d’écran 2019-04-08 à 08 24 44" src="https://user-images.githubusercontent.com/505230/55691319-e9fca480-59d7-11e9-913a-42a220b8d0a8.png">

I'm opening a new issue.
