### ISSUE TITLE
[ux] being able to see what you really need to focus on

### ISSUE THREAD

**Issue by karlcow** [webcompat/webcompat.com#805]
Just leaving this as a point of discussion and not necessary as something to code. I guess MyActivity page and/or feeds will help partly solving this. 
1. When looking for issues to work on I often check this list which is basically the list of all bugs, with least recently updated classification. So to work partly on things which are the oldest.
   https://webcompat.com/issues?page=1&per_page=50&state=open&stage=all&sort=updated&direction=asc
2. Being paid by Mozilla, I try to focus on the bugs about Firefox. There are a couple of IE bugs which are older and not really maintained, so I have to scroll down. 

It's slightly cumbersome. Realizing that I can imagine how boring it must be for other browser vendors to have to deal with the massive amount of Firefox issues to just see what they need. :)

**Comment by hallvors** [comment]
I think #795 would go a long way towards solving this

**Comment by miketaylr** [comment]
Agreed that it's something we should try to solve.
