### ISSUE TITLE
CONTRIBUTING.md: explain what "build" does and when you might need to build the project

### ISSUE THREAD

**Issue by hallvors** [webcompat/webcompat.com#811]
I have the impression that changing certain HTML files requires "build"ing before you test the changes locally, but I have actually no clear picture of what building does and when one might need to use the build command. More details would be nice.

**Comment by miketaylr** [comment]
(i don't ever use the make commands--I assume this issue refers to `make build`, which just calls `grunt`.)

Changing HTML templates shouldn't require any special commands, the server is smart enough to detect a change and restarts itself. When you do want to use `make build` or `grunt` locally is when you want a quick jshint check (before pushing a commit, for example) or want to rebuild CSS. This is obvious when you switch between branches at times (and there are significant CSS changes between them). Re-run `grunt` and refresh and it'll look "normal".

**Comment by hallvors** [comment]
So, that's the sort of explanation I want here:
https://github.com/webcompat/webcompat.com/blob/master/CONTRIBUTING.md#building-project
:)
Also, it does restart if I change .py files but I don't see it restart if I change .html files. Perhaps double-check this before you document it ;)

**Comment by miketaylr** [comment]
http://stackoverflow.com/questions/9508667/reload-flask-app-when-template-file-changes/9511655#9511655 suggests it's possible to have the flask app restart itself when arbitrary files are changed, but templates served via render_template should just work™.

Just tested on the index and contributors templates that the app doesn't restart, but the changes are served from disk.
