### ISSUE TITLE
JS style guide enforcement

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat.com#813]
We don't really have a style guide, and writing one seems like a lot of work.

It would be cool to hook up some tooling to do the checks for us:

http://eslint.org/docs/rules/ (eslint can also replace jshint)

OR

http://jscs.info/ (to be used in conjunction with jshint).

Mainly I'd like us to have consistent use of quoting and whitespace, and not have to think about these boring things during code review.

Thoughts? @magsout @hallvors

**Comment by miketaylr** [comment]
Whichever one we pick, we can agree on a set of a few common rules and go from there (and then perhaps send a single fixup PR to catch existing violations)

**Comment by hallvors** [comment]
jshint is already enforcing some rules, no?

**Comment by miketaylr** [comment]
Yeah, it does "these things will probably be bugs" rules. I'm also interested in having a consistent codebase in terms of style.

**Comment by hallvors** [comment]
It's nagging me about "un-necessary semicolon"s now and then. Sounds like a style issue ;)
Anyway, I suggest you just run jscs with a few presets and figure out which of them gives fewer errors with the existing code base.. Then we take it from there, perhaps relaxing some of the rules if we don't like the preset we end up with.

**Comment by miketaylr** [comment]
> It's nagging me about "un-necessary semicolon"s now and then. Sounds like a style issue ;)

OK. But it doesn't do the other interesting things that this issue is about.

I'll mess with jscs or eslint in the coming days and send a PR.

**Comment by magsout** [comment]
eslint is a good choise, I use it on a lot of project. Plus I made this https://github.com/stylelint/stylelint-config-cssrecipes for css, so maybe wen can use it too.

But yeah, it's a good idea to have a consistant code base..

**Comment by miketaylr** [comment]
+1

**Comment by magsout** [comment]
@miketaylr if you want we can create a new branch and try to add those linter ?

**Comment by miketaylr** [comment]
@magsout let's go ahead and open a new issue for CSS linting, I don't think they need to be done in the same branch.
