### ISSUE TITLE
Tablet/Android identification issues

### ISSUE THREAD

**Issue by karlcow** [webcompat/webcompat.com#819]
So it seems we had a couple of bugs with `Firefox 45` on `Android 6.0` which are not identified as such.

```
<!-- @browser: Android 6.0 -->
<!-- @ua_header: Mozilla/5.0 (Android 6.0; Tablet; rv:45.0) Gecko/45.0 Firefox/45.0 -->
```

We might to fix that. https://github.com/webcompat/web-bugs/issues/1885

**Comment by miketaylr** [comment]
Yeah, we need to fix this. Possibly file a bug upstream on the ua parsing lib we use (might be a good time to update it...).

**Comment by miketaylr** [comment]
We're currently on 0.3.5, let's update to 0.5.0.

**Comment by miketaylr** [comment]
Here's the before and after after the upgrade:

![](https://cldup.com/SwPe_-63_r-3000x3000.png)

**Comment by miketaylr** [comment]
@karlcow does it seem OK that it's identified as Firefox Mobile? We could report a bug upstream, but I'm not sure how important it is.

**Comment by karlcow** [comment]
hmm not bad
I wonder if we want to have the tablet thingy or not. 
It gives good info on the screen size. Or maybe more relevant for us would be the screen size. 

I guess Firefox Mobile seems ok.

**Comment by miketaylr** [comment]
It probably isn't a bad idea to report a bug upstream and update in the future. I'll do that.

**Comment by miketaylr** [comment]
It looks like they do parse it as a tablet, but we're just passing through family. See https://github.com/ua-parser/uap-core/issues/111#issuecomment-151463331.

Maybe we could do something like, `Firefox Mobile (Tablet)` just for tablets?
