### ISSUE TITLE
Add Tablet info to browser name

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat.com#821]
See https://github.com/webcompat/webcompat.com/issues/819#issuecomment-153974462.

The idea would be if we have `device.model == 'Tablet'`, we add a `(Tablet)` after the browser name. Just need to investigate how other tablet browsers are currently displayed so we don't do something silly like `Chrome Tablet (Tablet)`.

**Comment by miketaylr** [comment]
To fix this bug, you'll probably want to add some logic to `get_labels` (label is a weird choice here, it's really more of hidden metadata we wrap in an HTML comment) to figure out if the UA is a tablet. That might involve re-parsing the UA string (or not, it's been a while since I've looked at this code).

https://github.com/webcompat/webcompat.com/blob/master/webcompat/form.py#L106

Code that sets a label on an issue:
https://github.com/webcompat/webcompat.com/blob/master/webcompat/webhooks/__init__.py &
https://github.com/webcompat/webcompat.com/blob/master/webcompat/webhooks/helpers.py#L27 

`get_browser_name` and `get_browser`:
https://github.com/webcompat/webcompat.com/blob/master/webcompat/helpers.py#L102

(But it occurs to me that might be theoretical, I'm not sure I changed the endpoints in GitHub yet :ghost:)

**Comment by miketaylr** [comment]
And for it to work at that point, we need to add a label to the web-bugs repo "firefox-mobile-tablet" (or similar, just has to match what we send to GitHub).

**Comment by miketaylr** [comment]
@dshgna want to take a look at this bug?

**Comment by dshgna** [comment]
@miketaylr working on it! Made an initial commit to check if I'm going in the right direction. #941
