### ISSUE TITLE
Ensure the UI makes sense without Gravatar images

### ISSUE THREAD

**Issue by hallvors** [webcompat/webcompat.com#822]
If you block tracking stuff, you may want to block Gravatar images.  We should make sure the UI still makes sense if there are no images. 

This was brought up on Twitter: https://twitter.com/oncletom/status/661587848315949056

**Comment by magsout** [comment]
Ah yes good catch. We need default a FlexEmbed block to avoid break UI.

**Comment by hallvors** [comment]
Our Avatars are served from githubusercontent.com, maybe not a typical server to block - but if you worry about privacy, why not?

    <img alt="" src="https://avatars.githubusercontent.com/u/1162991?v=3">

A simple fix might be setting alt tags:

    <img alt="@swarnava" src="https://avatars.githubusercontent.com/u/1162991?v=3">

This is pretty much what GitHub itself does.

**Comment by miketaylr** [comment]
Alt text is more useful than something empty, but it would be nice to have a background image of an empty avatar (or even just a grey box -- which would have less overhead).

**Comment by hallvors** [comment]
Easy to style div.wc-Comment-avatar with width/height and background, I guess. Goes in ```static/css/development/components/comment.css```. That plus an alt text should fix this. The alt text should go in ```webcompat/templates/issue.html``` with ```reporter``` for the reporterAvatar and ```commenter``` for the avatarUrl references.

**Comment by hallvors** [comment]
I'm not sure about the grey background - what if someone has a Github avatar image with transparency in it?

**Comment by miketaylr** [comment]
> what if someone has a Github avatar image with transparency in it?

Dunno, pick a white bg?

**Comment by hallvors** [comment]
Done - r?@miketaylr
