### ISSUE TITLE
Addon install on Nightly

### ISSUE THREAD

**Issue by karlcow** [webcompat/webcompat.com#825]
If we install the addon on Nightly we get twice the same menu on Report Site Issue.
And we still keep the message about downloading it. ^_^

**Comment by miketaylr** [comment]
Yeah, that's not great. We can open a bug for the addon in the addon repo: https://github.com/webcompat/webcompat-reporter-extensions

And possibly we can solve the "don't prompt to download" problem as well, but it will take some hacks.
