### ISSUE TITLE
When "fixed" label is applied, "state" label still says "new"

### ISSUE THREAD

**Issue by hallvors** [webcompat/webcompat.com#832]
This is very, very minor since usually fixed bugs are immediately closed. However, here goes: If you apply a "fixed" label to an issue, you'll still have the big orange patch saying "New issue" at the top. This is inconsistent with how other status labels behave.

**Comment by hallvors** [comment]
I guess all it takes to fix this is to add one more case here:
https://github.com/webcompat/webcompat.com/blob/master/webcompat/static/js/lib/models/issue.js#L34

**Comment by dshgna** [comment]
@hallvors I'm stuck trying to reproduce this bug because "fixed" does not show up under the Labels dropdown. Has the codebase changed since? 
Thanks.

**Comment by hallvors** [comment]
Hi @dshgna, welcome :) 
You're right the "fixed" label doesn't appear in the list of possible labels now - I don't know, maybe @miketaylr can tell us if this is a bug or was done on purpose. There are bugs around that are labelled fixed such as:
https://webcompat.com/issues/2151

This bug is basically easy to reproduce by 
1) Create a bug in your test repo on GitHub.
2) Assign the label status-fixed or status-worksforme but *do not close it*.
3) Load that bug in the webcompat page and observe that while many other "status" labels (such as contactready, sitewait) *are* reflected at the top, "fixed" and "worksforme" are not - the label says "New issue". We'd probably like it to say "Fixed" and "Appears to work" respectively. It's minor because these labels typically apply to closed bugs, in which case the "Closed" status wins and gets shown at the top. It's still inconsistent - hence a bug :)

**Comment by miketaylr** [comment]
> You're right the "fixed" label doesn't appear in the list of possible labels now - I don't know why, maybe @miketaylr can tell us if this is a bug or was done on purpose.

Hmm, I don't know if this was intentional or not. ^_^ Will have to take a look at the label code to see where we control what gets allowed in the dropdown.

**Comment by dshgna** [comment]
@hallvors Thank you for the welcome and guidance :)

I created a pull request. Attached are the screenshots for each case. 

![Fixed](http://i.imgur.com/DkiILl4.png)

![AppearsToWork](http://i.imgur.com/1cpnnto.png)

![IssueList](http://i.imgur.com/Q9f0dN6.png)

**Comment by hallvors** [comment]
:+1: :)
