### ISSUE TITLE
Issues JS generates self-contradicting backend URLs

### ISSUE THREAD

**Issue by hallvors** [webcompat/webcompat.com#834]
Initial URL is fine:
https://webcompat.com/api/issues?page=1&per_page=50&state=open&stage=all&sort=created&direction=desc
The one you get by clicking "new" has a "stage=all" in it:
https://webcompat.com/api/issues/search/new?page=1&per_page=50&state=open&stage=all&sort=created&direction=desc&q=netflix
and if you keep clicking those labels, you'll see that "stage" keeps lagging one step behind and contradicting the path:

https://webcompat.com/api/issues/category/needsdiagnosis?page=1&per_page=50&state=open&stage=new&sort=created&direction=desc

https://webcompat.com/api/issues/category/needscontact?page=1&per_page=50&state=open&stage=needsdiagnosis&sort=created&direction=desc

Hmm.. :-/

**Comment by hallvors** [comment]
I note that in endpoints.py, api/issues/search has no support for transforming category (or a ?stage=statuslabel) queries to labels, while api/issues/search/<category> will drop any non-category query input on the floor.

**Comment by hallvors** [comment]
@karlcow @miketaylr @magsout  @alex-mayorga  I think I'll sort this out in #835 - however, it's a bit of work to change because changing backend URLs require changing fixture file names etc. So I'd rather check if you all approve of these changes first..

1) I think we should aim to simplify this by generating the same URL query string for the "frontend" (shown in URL bar) and the backend. Preferably pathname too (sans the string "api" for frontend of course).

2) I'd simplify by sending ?order=desc instead of ?direction=desc to avoid changing the name on the backend, as order is what GitHub uses.

3) I'd drop ?state= and ?stage= parameters completely from the backend API URL, and rely on the keyword in the pathname (with an exception for when we create direct-to-github query URLs). So rather than odd URLs like 
```/category/needsdiagnosis?stage=new&state=open``` we get just ```/category/needsdiagnosis``` or ```/category/new```. The backend knows that "new" and "closed" are special, all others are translated to ```label:status-foo state:open```.

4) I think webcompat.com/issues/new and webcompat.com/issues/needsdiagnosis etc for public URLs looks neat. (Although /issues/new means something entirely different at GitHub so perhaps it should be /issues/incoming or something like that?`)

So we end up with these query string params:

* q=search
* page=pagination index
* per_page=number of issues per page
* order=asc or desc
* sort=what aspect list is sorted by

And these pathname fragments:

* /new (or /incoming)
* /needsdiagnosis
* /needscontact
* /contactready
* /sitewait
* /closed

**Comment by hallvors** [comment]
(queries like creator: and mentioned: also have some UI, these actually end up in q=key:value)

**Comment by miketaylr** [comment]
I think we should discuss this in Orlando -- I still need to finish review of #835.

**Comment by hallvors** [comment]
We can't land #835 as-is anyway without changing some fixture file names because the URLs have changed somewhat. On the other hand, it's fine to leave the rest of the "public URLs" proposals here for later and just tinker with the backend URLs right now. Mike also mentioned that one of the GitHub APIs uses direction and one order (huh..?) so I've possibly already caused some bugs here - I'll have to investigate that.

**Comment by karlcow** [comment]
hmmm… this looks like a lot of changes. Not sure I understand everything. And we have a very good opportunity to discuss this face to face before jumping to big decisions. 

And specifically when it's about the URI space ;) I would love to have time to understand. 

small steps :footprints:

**Comment by miketaylr** [comment]
> Mike also mentioned that one of the GitHub APIs uses direction and one order (huh..?) so I've possibly already caused some bugs here - I'll have to investigate that.

Here's a good place to see an overview of the tricks we have to do to talk to both the Issues and the Search APIs: https://github.com/webcompat/webcompat.com/blob/master/webcompat/helpers.py#L205-L232

**Comment by hallvors** [comment]
Do we need the ability to list for example "closed issues that are SITEWAIT" - ever? The current UI assumes that "Closed" is a separate category of its own that can not be combined with the other statuses. The *backend* does not make any such assumption, since we have separate state= and stage= params, but since the UI *does* I was tempted to suggest simplifying the URLs.. Thoughts?

**Comment by miketaylr** [comment]
Revisit after #886.

**Comment by karlcow** [comment]
I think this is fixed.
