### ISSUE TITLE
Set up dist folders and serve static assets from there

### ISSUE THREAD

**Issue by hallvors** [webcompat/webcompat.com#839]
The build process job for optimizing jpg and png images overwrites the originals. It's odd to run the optimizations again and again on those same files, and it's annoying that Git actually thinks some of them have changes that should be checked in.

**Comment by miketaylr** [comment]
> It's odd to run the optimizations again and again on those same files

Yeah, there should be a better way to do this (I hope).

> it's annoying that Git actually thinks some of them have changes that should be checked in

That's news to me. I assume this is on Windows for you? Could it be that the Windows and Mac optimizations are not binary-equivalent?

**Comment by miketaylr** [comment]
Any ideas on how we could improve this, @magsout? 

One idea is we could just make this grunt task a non-default task (that *is* run when building for a deploy).

**Comment by hallvors** [comment]
Why not send all output from the build process into ./dist or ./built_site or some such?

Would it be hard to only optimize images that are newer than already optimized file inside ./dist ?

**Comment by hallvors** [comment]
> Could it be that the Windows and Mac optimizations are not binary-equivalent?

Most likely. I guess if I *did* check them in you'd end up seeing this issue on your side. git ping pong? :)

**Comment by miketaylr** [comment]
> Would it be hard to only optimize images that are newer than already optimized file inside ./dist ?

Hm, probably not. We could have the task move them to `webcompat/static/img/dist/` (which should be .gitignore'd) and check the last-modified date on those before running the task. 

One minor wrinkle is this would allow us to check in large unoptimized files into the repo. I don't know if that will be an real issue in practice though.

**Comment by hallvors** [comment]
/me thinks that's a feature :-p

Another thing: I'm quite often using "Search in files" to get an overview of the code, and the way our build process keeps built files and source files pretty close in the tree is annoying. It's hard - especially while being newbie - to tell which files are the output of a build process and which aren't. Making sure all output goes to ./dist would be a great improvement.

**Comment by miketaylr** [comment]
I'm gonna take this and do the following:

- [ ] make a /dist folder and make all processed files go there
- [ ] update templates to look there

And then I'll see if my "check the last-modified date on those before running the task" plan is annoying to implement or not.

**Comment by miketaylr** [comment]
> The build process job for optimizing jpg and png images overwrites the originals. It's odd to run the optimizations again and again on those same files,

I just checked, and imagemin doesn't actually overwrite them or optimize them if there's no gains to be made. But it still spends time attempting to optimize them.

**Comment by hallvors** [comment]
imagemin takes a while to run on Windows and outputs a message saying "n images optimized, 0 bytes saved". Afterwards Git thinks those files were modified. So it's weird :-p

**Comment by miketaylr** [comment]
The joys of cross-OS tooling. :hammer:

**Comment by miketaylr** [comment]
So, thinking more about this it's gonna be a number of hours to make a fix that saves about a minute per build. I guess that adds up, but I propose the following simpler approach: make imagemin non-default but always included for deploys.

We can re-visit a `/dist` folder later, but there's a lot more important things to get done right now. I'll leave this open if someone wants to work on this -- perhaps a good chance to get familiar with the codebase.

**Comment by magsout** [comment]
To avoid these issues, I always avoid touching the original file. I have a build directory with css, js, img, svg etc ..  This directory is of course not track by git.

**Comment by magsout** [comment]
Maybe we can thinking about migrate to webpack (a good solid webstack) with lot of loader (svg, img, js, css) ..

**Comment by miketaylr** [comment]
I agree with @magsout, but it might be a while before we get to webpack. If someone wants to tackle this as an opportunity to mess with grunt and some templates, I think the plan from https://github.com/webcompat/webcompat.com/issues/839#issuecomment-163712423 would still work.

You would need to create a `/dist` folder in `/webcompat/static/` and make sure all the grunt tasks put built assets there: https://github.com/webcompat/webcompat.com/tree/master/grunt-tasks (pretty much anything that has a destination or output).

We probably want to add dist to gitignore too.

**Comment by zoepage** [comment]
Related to #909

**Comment by miketaylr** [comment]
I think we don't want to do this anymore.
