### ISSUE TITLE
matching URL with .* less correct than with .+

### ISSUE THREAD

**Issue by hallvors** [webcompat/webcompat.com#854]
In this regular expression:
https://github.com/webcompat/webcompat.com/blob/master/webcompat/helpers.py#L368
when we do ```(.*)``` we do not *actually* intend to look for "0 or more characters" - a 0 characters long URL isn't a URL. We should use + instead of *.

**Comment by miketaylr** [comment]
Is a 1 character long URL a valid URL? If not, I'm not sure it makes much of a difference, but a good first patch indeed. :stuck_out_tongue_winking_eye:

**Comment by hallvors** [comment]
Well, there's code elsewhere to handle URLs without a http(s):// prefix I think - certainly at Opera "t" was a URL and a pretty important one ;)
We can always do ```{3,}``` or something like that to require three or more characters but who knows what will be a minimum valid URL length down the road? I'm however pretty sure that a 0 character long string is going to remain invalid. It's good with some certainties in life :D
