### ISSUE TITLE
Some browsers start inline find on keypress, cancel default action on [g]

### ISSUE THREAD

**Issue by hallvors** [webcompat/webcompat.com#857]
Minor annoyance: we have a ```[g]``` shortcut key to take you to GitHub. However, if the browser is configured to start inline find on a keypress it will do so when the user hits G, and start highlighting various letters in the text while navigation is happening. 

The simple fix is to add 
```
e.preventDefault();
```
here: https://github.com/webcompat/webcompat.com/blob/master/webcompat/static/js/lib/issue-list.js#L544

**Comment by miketaylr** [comment]
@hallvors which platform does this happen on (just curious)? On mac it's `/`

**Comment by deepthivenkat** [comment]
#938
