### ISSUE TITLE
Enable linting via Travis

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat.com#860]
eslint + pep8 for now.

**Comment by miketaylr** [comment]
Probably want to add an `.eslintignore` file so we're not failing on minified libs and the like.

**Comment by miketaylr** [comment]
> Probably want to add an .eslintignore file so we're not failing on minified libs and the like.

Eh, it's only a few more lines to add what we want for JS. So I did that instead.

**Comment by miketaylr** [comment]
I'm gonna go with the following pep8 magical incantation to give to travis:

`pep8 --ignore=E402 webcompat/ tests/ config.py.example`

E402 complains about non-top-level imports, but in certain places we have to wait on the app to be initialized before importing junk.

**Comment by karlcow** [comment]
yeah \o/
