### ISSUE TITLE
Create UI for filtering on several labels / search strings

### ISSUE THREAD

**Issue by hallvors** [webcompat/webcompat.com#863]
If you load https://www.webcompat.com/issues you have various options for searching and filtering:
- Drop down for open/all and if logged in own/mentioned issues
- Filter by status (New, Needs diagnosis etc..)
- Free text search
- Labels that show up in the list of bugs can be clicked to filter on this label

While the UI might make you think that you can filter in a very granular way (show only bugs reported by me that need diagnosis and are labelled 'firefox') this isn't actually the case. Each filter, when set, will currently cancel out all the others.

We want to change this, but haven't quite reached consensus on a good UX / UI design. Some requirements:
- There needs to be a way to remove labels if they are added to the filters by clicking a label in the issue list
- The URL must always reflect the state of the filtering so that it can be bookmarked or sent by E-mail

It's not _necessarily_ a requirement to keep the drop-downs if there is a better way to present shortcuts to those same options. In particular, the main "Open issues / all issues / my issues" dropdown contributes to a confusing UI in certain states, as described in #510 

See also: #795 for coding

One attempt at creating a UI is here:
https://cloud.githubusercontent.com/assets/120136/11514899/3d2da23e-987b-11e5-9b36-8ccab54368ab.png

**Comment by miketaylr** [comment]
We don't want to do this right now.
