### ISSUE TITLE
Client-side implementation of "detect bugs with similar domain names"

### ISSUE THREAD

**Issue by hallvors** [webcompat/webcompat.com#864]
This is a bug for coding an implementation of the feature described in #307 
It depends on #307 and can only start when we have some solid UI suggestions.

**Comment by dshgna** [comment]
@hallvors Created a basic prototype.
[Imgur](http://i.imgur.com/zqxBzZF.png)

**Comment by magsout** [comment]
Sounds good @dshgna . Maybe removed a little bit offset between input and List

**Comment by hallvors** [comment]
Looks great!
I would like to add something like:

> You may want to comment on an existing issue instead of reporting a new one.

but then, we'd have to explain that a GitHub account is needed to log in and how they need to authorize our app etc.. I guess it gets too complicated.

**Comment by dshgna** [comment]
@hallvors Thinking over it, the prompt to comment actually adds a lot to the user experience. Perhaps go on with it?

**Comment by hallvors** [comment]
Maybe.. 
> You may want to comment on an existing issue instead of reporting a new one. Log in via GitHub to do so.
(And then we could make sure the "Log in" text only appears if not logged in, and linking to https://webcompat.com/login ..? Not sure how that login works, maybe it is done with JS. It's a bit tricky to make sure they don't loose their context and the list of bugs they are interested in if we do this link though..)

**Comment by dshgna** [comment]
@hallvors I think we can give a try to implement it :) 

This is how it looks like with the whole form. There will be quite a large whitespace when the suggestions are not being displayed. 

![Imgur](http://i.imgur.com/aiRZYSD.png)

An alternative I thought of is to display the possible duplicates above the form. 

![Imgur](http://i.imgur.com/6NVImTe.png)

@hallvors @magsout  What do you think? :)

**Comment by magsout** [comment]
We can use `position: absolute` for this new element ?

**Comment by dshgna** [comment]
@magsout Sorry didn't quite get you :) I didn't try this out on the code yet, just design mocks.

**Comment by magsout** [comment]
@dshgna ah yes, I know, just said that new element is displayed only if there is a result and like a dropdown above other element.

**Comment by dshgna** [comment]
@magsout yes

**Comment by miketaylr** [comment]
Before anyone does any more work on this, this issue is intended to be worked on by the Outreachy intern as part of the "Design and build a user interface that allows bug reporters to identify possible duplicate problems" project. 

Thanks for the ideas so far @dshgna!

(If they don't choose that project, no worries).

**Comment by miketaylr** [comment]
Closing for now, see https://github.com/webcompat/webcompat.com/issues/307#issuecomment-281479941.
