### ISSUE TITLE
Create UI design for E-mail subscription form and workflow

### ISSUE THREAD

**Issue by hallvors** [webcompat/webcompat.com#866]
Per #723 we want to let users subscribe to notifications of new issues for specific websites. We need design for a subscription form and a confirmation screen for this feature.

**Comment by magsout** [comment]
Maybe @Raphseck, can help ?

**Comment by Raphseck** [comment]
Hey guys,
Yes i can help!
I need some visual references.

**Comment by dshgna** [comment]
@magsout I'd be interested in working on this. Could you give me some pointers on where to start?

**Comment by miketaylr** [comment]
Hang off on this one just yet @dshgna. ^_^

This will likely be part of the Outreachy project. And needs some more info that I need to write up.

**Comment by miketaylr** [comment]
@Raphseck sorry for not responding! Let me write something up in the next day or two to give more context to this issue.

**Comment by Raphseck** [comment]
@miketaylr no problem!! ok!! :)

**Comment by dshgna** [comment]
@miketaylr  sure :)

**Comment by miketaylr** [comment]
We're not gonna do email subscription for now.
