### ISSUE TITLE
Create UI for including screenshot in bug report

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat.com#867]
Issue #452 tracks adding the ability to grab screenshots of a problematic tab, via browser add-ons (and built into Fennec, eventually). I hope to make good progress the implementation details of that this week (knock on :deciduous_tree:).

We need a UI to possible show a small preview of the screenshot and an unchecked-by-default checkbox that the user can check if they want to include it. This is to prevent us from automatically submitting images that might contain sensitive information (or maybe NSFW stuff or whatever).

Here's one take from @calexity: https://github.com/webcompat/webcompat.com/issues/431#issuecomment-68215120

**Comment by miketaylr** [comment]
I want to ship a minimal/kinda-crappy-but-not-super-terrible version of this so we can have the feature before we have the perfect UI. I think a minimum requirement is that we show a preview of the image, so the user can see what's about to be sent. 

One thing to keep in mind is this UI will only be shown if a user sends a postMessage'd base64 image from the "https://webcompat.com" origin -- which means they have our new add-on versions installed. Otherwise, the UI stays the same.

Mobile seems like a pretty easy leap from @calexity's design. Desktop is trickier...

Some ideas:

@magsout @karlcow @calexity  (+anybody else) thoughts? In the interest of shipping v1 sooner than later, minimal tweaks (or alternative mockups welcome!) would be awesome. Anything more complex would be OK for v2 wish-list (like a lightbox w/ highlight/blackout capability).

![](https://cldup.com/ne823xTcbU-3000x3000.png)
![](https://cldup.com/gqXTd99NDl-3000x3000.png)

**Comment by miketaylr** [comment]
Also cc @Raphseck, if you have any ideas. It might be helpful to go to "https://webcoompat.com/?open=1" to see what this currently looks like (basically the same w/o the inline screenshot and the "give more details" bit extends the entire width of the viewport for the desktop version".

**Comment by miketaylr** [comment]
I'm going to take silence as consent here, and probably start building this out tomorrow. We can iterate on better designs if we ever come up with them. :p

**Comment by Raphseck** [comment]
@miketaylr and guys!
Sorry about the late and sorry about my english!
I like this layout and had some ideas about the screenshot part.
Maybe some more intuitive here.
Hope you like!
![file_1](https://cloud.githubusercontent.com/assets/14264676/12027189/cb316ad2-ada9-11e5-88ab-32173fc35725.jpg)
![file_2](https://cloud.githubusercontent.com/assets/14264676/12027190/cb5c67aa-ada9-11e5-80d9-ca30f783fe31.jpg)

cheers! : )

**Comment by miketaylr** [comment]
Hey @Raphseck, não se preocupe, seu inglês é melhor que nosso português. :p

I actually really like the idea of a large drop-target, since it means we don't have to special-case the UI depending on the presence of an add-on or not. We have an issue (will find and link) for adding drag & drop support as well.

**Comment by magsout** [comment]
oh yeah, @Raphseck nice proposal.  I really like

**Comment by miketaylr** [comment]
@magsout how hard do you think it would be to build this version? https://cloudup.com/cSxDmqHwMUN

**Comment by miketaylr** [comment]
I think for the addon screenshot, it might be cool to have a small overlay like this: https://cloudup.com/cXAGKmlRYYT, but with an unchecked checkbox that says "Upload screenshot image?" -- we want to make sure that users are opting in explicitly.

**Comment by magsout** [comment]
@miketaylr I try to do this today or tomorrow .

**Comment by miketaylr** [comment]
@magsout :tada: you rock!

**Comment by hallvors** [comment]
Perhaps it's better to not show the preview until the "Upload screenshot" box is ticked - people may miss the checkbox and just assume the image will be added..?

**Comment by miketaylr** [comment]
Fixed, thank you @magsout and @Raphseck!!! :heart:

**Comment by magsout** [comment]
Good proposal @Raphseck 👍

**Comment by miketaylr** [comment]
> Perhaps it's better to not show the preview until the "Upload screenshot" box is ticked - people may miss the checkbox and just assume the image will be added..?

@hallvors I sort of changed the interaction a bit -- check out https://github.com/webcompat/webcompat.com/issues/879#issuecomment-169107610 (and comment there with feedback)

**Comment by Raphseck** [comment]
great guys! : )
