### ISSUE TITLE
[ux] My Activity page when not logged and when logged

### ISSUE THREAD

**Issue by karlcow** [webcompat/webcompat.com#877]
For the following list, **open specific bugs** for each of those depending on the decisions we make. I will update this with the bug numbers.

When a user is not logged and is reaching a https://webcompat.com/activity/me or https://webcompat.com/activity/karlcow, he/she gets a blank page and an API call not found.

Different options possible:
## `/activity/me` (NOT logged)
- `/activity/me` sends a [403](http://tools.ietf.org/html/rfc7235#section-3.1) and invites in the body people to login to see their own activity page.
- `/activity/me` sends a [403](http://tools.ietf.org/html/rfc7231#section-6.5.3) and a message about what is the purpose of this page.

![capture d ecran 2015-12-17 a 12 07 05](https://cloud.githubusercontent.com/assets/505230/11860635/21be4c1a-a4ba-11e5-88a4-a1c476266d98.png)
## `/activity/me` (logged)
- `/activity/me` sends a [301](http://tools.ietf.org/html/rfc7231#section-6.4.2) (permanent redirect) to the user's page. For example `/activity/karlcow`. Right now it stays on `/activity/me` Open a specific bug for this if we decide this is the option we want.
## `/activity/karlcow` (aka username) (NOT logged)
- `/activity/karlcow` sends a [403](http://tools.ietf.org/html/rfc7235#section-3.1) and invites in the body people to login to see their own activity page.
- `/activity/karlcow` sends a [200](http://tools.ietf.org/html/rfc7235#section-3.1) and shows the activity of this person.
## `/activity/karlcow` (aka username) (logged)
- `/activity/karlcow` shows the activity of the person be yours or not. A logged user has access to both `/activity/karlcow` and `/activity/miketaylr`. BUT there is a **bug**. Currently being karlcow if I request miketaylr, I get the same results than my page.

![capture d ecran 2015-12-17 a 12 30 55](https://cloud.githubusercontent.com/assets/505230/11860642/32bce9c2-a4ba-11e5-956c-4d2ad2d20405.png)
## Question Bonus
- `/activity/dbaron` is a commenter but has never reported a bug on webcompat. What do we do? What do we show?
- `/activity/mnot` is neither a commenter or issue reporter, but a github user. We probably wants to send a 404.

**Comment by karlcow** [comment]
@calexity @miketaylr @hallvors @magsout @tagawa You are welcome to chime in

**Comment by miketaylr** [comment]
> When a user is not logged and is reaching a https://webcompat.com/activity/me or https://webcompat.com/activity/karlcow, he/she gets a blank page and an API call not found.

So this is a bug. The code claims to do what we discussed in Paris:

```
@app.route('/me')
def me_redirect():
    '''This route redirects to /activity/<username>, for logged in users.'''
    if not g.user:
        return redirect(url_for('login'))
    get_user_info()
    return redirect(url_for('show_user_page', username=session['username']))


@app.route('/activity/<username>')
def show_user_page(username):
    return render_template('user-activity.html', user=username)
```

If you're not logged in, redirect to login, then redirect to `/activity/username`. We should fix that, I can open a bug.

As for looking at other people's activity, I don't have any strong opinions.

**Comment by magsout** [comment]
> /activity/me (NOT logged)

:+1:  /activity/me sends a 403 and invites in the body people to login to see their own activity page.

> /activity/me (logged)

I think redirect /me to /magsout is pretty good, plus there is a bug right now  about query param
![capture d ecran 2015-12-19 a 09 04 21](https://cloud.githubusercontent.com/assets/1997108/11912133/82eb7118-a62f-11e5-96e3-fb86ce31b92a.png)

> /activity/karlcow (aka username) (NOT logged)

:+1:  > /activity/karlcow sends a 200 and shows the activity of this person.

>/activity/mnot is neither a commenter or issue reporter, but a github user. We probably wants to send a 404. 

Yes, seems good for me

**Comment by miketaylr** [comment]
Oh wait. I was confused.

`/activity/me` is not a route that we support. We support `/me` which is supposed to redirect to `/activity/<username>`. There's a bug in the redirection if you're not already logged in, but that's covered in #878.

**Comment by miketaylr** [comment]
I guess the real bug/feature here is giving people the ability to check out other people's activity?

**Comment by karlcow** [comment]
@miketaylr once logged try https://webcompat.com/activity/me

And yes this is the question to the other comment about 
> I guess the real bug/feature here is giving people the ability to check out other people's activity?

**Comment by miketaylr** [comment]
> @miketaylr once logged try https://webcompat.com/activity/me

Yep, that's trying to view the activity of a user called "me", which we don't allow currently (hence the API whatever not allowed error message).

**Comment by miketaylr** [comment]
To fix:

* [ ] remove the session username check in the `show_user_page` view method in views.py
* [ ] make sure tests still work, or are updated

(I think that's it?)

**Comment by karlcow** [comment]
The session check will not solve it. :) Probably. I need to test a bit more.

**Comment by karlcow** [comment]
Let's close this.
