### ISSUE TITLE
/me doesn't redirect to login then /activity/username for logged-out users

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat.com#878]
cf. #877 

Code is here: https://github.com/webcompat/webcompat.com/blob/master/webcompat/views.py#L209-L215, for whatever reason it's not prompting the user to login.

**Comment by miketaylr** [comment]
Right now the current behavior if you're logged out is to get a token from GitHub, and then it takes you back to the homepage. That's the bug -- it should take you back to /me (or /activity/<username>)

**Comment by miketaylr** [comment]
If you haven't authorized the GitHub app, the following happens:

1) user goes to /me 
2) GitHub prompts you to authorize app
3) end up logged in at homepage

**Comment by miketaylr** [comment]
So this is a funny issue.

The /me redirect works when you're logged in and click on the /me link, because at that point you have a `request.referrer` to follow back. The only way to have a /me link to click is to be logged in (you then have the link in the avatar drop-down).

If you're *not* logged in, you must have followed that from a bookmark maybe or entered it into the URL bar so there is no `request.referrer` and the redirect just goes to index (which is the fallback behavior).

@karlcow what do you think? Should we special case the redirect here? I don't have any great solutions, and I think this is probably a very low priority issue to fix.

**Comment by karlcow** [comment]
https://github.com/webcompat/webcompat.com/blob/master/webcompat/views.py#L209

The current code is:

```python
@app.route('/me')
def me_redirect():
    '''This route redirects to /activity/<username>, for logged in users.'''
    if not g.user:
        return redirect(url_for('login'))
    get_user_info()
    return redirect(url_for('show_user_page', username=session['username']))
```

Probably which should return a [401 non-authorized](http://tools.ietf.org/html/rfc7235#section-3.1) instead of a redirection.

```
    if not g.user:
        abort(401)
```

**Comment by miketaylr** [comment]
That sounds fine.
