### ISSUE TITLE
React to add-on opening new issue with screenshot

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat.com#879]
cf. #452.

I'm thinking we'll have the add-on do a postMessage w/ the screenshot image as an argument to the home page. Once it receives that, we construct an img element and put it on the page, and then we'll put it in the `FormData` object that we POST to the server. :rainbow: :racehorse:

**Comment by miketaylr** [comment]
Possibly need to add base64 image support in the image uploading backend. Not sure right now.

**Comment by miketaylr** [comment]
OK, with #867 done, this should be pretty simple. :tada:

**Comment by miketaylr** [comment]
![](https://cldup.com/c8gAJ1JHeU.gif)

Looks cool!

**Comment by magsout** [comment]
Oh yeaah 💯

**Comment by hallvors** [comment]
Excellent!

**Comment by karlcow** [comment]
nicely done! :cake:
