### ISSUE TITLE
Error when log in at /activity/magsout and no data provide

### ISSUE THREAD

**Issue by magsout** [webcompat/webcompat.com#880]
Not logged, go to https://webcompat.com/activity/magsout, log in.  There is a flash message about `API CALL NOT FOUND`   Label in dropdown is wrong (avatar user)

![capture d ecran 2015-12-19 a 09 09 10](https://cloud.githubusercontent.com/assets/1997108/11912150/2fe55d52-a630-11e5-9fa5-789f5be92607.png)

Plus, I cant's see my activity, but If I go to Homepage et back to the previous url, it's ok.

**Comment by miketaylr** [comment]
I think this might be the same bug as https://github.com/webcompat/webcompat.com/issues/878, or it's at least related. Will try to fix soon!

**Comment by miketaylr** [comment]
s/soon/in two months/
