### ISSUE TITLE
Remove Flask-Upload and implement our own upload backend

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat.com#882]
Splitting #879 into two bugs here to make it easier to review.

The new backend should be able to handle regular file uploads, as well as incoming screenshots from the add-ons, do image format validation, and save them to the filesystem.

**Comment by miketaylr** [comment]
I think this will actually make #710 a lot easier. @karlcow and I talked about doing this in Orlando as part of that, so hopefully I beat him to it and haven't duplicated his efforts here.

**Comment by miketaylr** [comment]
Note: I need to test this stuff in the context of filing issues, locally I was just making sure the upload stuff worked/was saved to file.

**Comment by miketaylr** [comment]
Locally, "regular" file upload images is working but the screenshot stuff isn't when filing a new issue.

To investigate.

**Comment by karlcow** [comment]
👏😂🙇🏼. Time for 🍔
