### ISSUE TITLE
[meta] Use Milestones for status

### ISSUE THREAD

**Issue by karlcow** [webcompat/webcompat.com#886]
I put it here more as a reminder and space for discussions. We can safely close it.

Today I just realized that we didn't use at all the notion of Milestones for managing the status.
It's a bit unfortunate, specifically with all the hard work that @hallvors and @miketaylr  put into it, for revising the data-model for labels. If we have to touch again that code. We might want to think twice about using Milestones for the status.

The why is expressed here:  https://github.com/karlcow/webcompat-test/milestones
It creates bucket where an issue can be only in one specific milestones. So it isolates itself from the rest of the bucket on github itself. So if someone changes the milestones on Github it is consistent on webcompat.com while now if someone puts two labels for status on github, it requires management from webcompat.com, more complicated.

[update september 5, 2017]:

Places we need to modify:

* Tests (Py + JS)
* API Backend (Py)
* Webhooks (Py)
* Backbone Junk (JS)
* Templates (CSS + HTML)

**Comment by karlcow** [comment]
The API for Milestones
https://developer.github.com/v3/issues/milestones/

**Comment by miketaylr** [comment]
This is definitely interesting...

**Comment by karlcow** [comment]
A couple of thoughts about that:

* Makes it easier to track the number in each bucket. A [single milestone](https://developer.github.com/v3/issues/milestones/#get-a-single-milestone) returns `open_issues` and `closed_issues` count. so we can have a status about the workload for each status. aka issue #291
* Free the labels space from workflow and makes it more a useful label space such as `serversniff`, `webkitcss`, etc.
* Simplify a lot the JS code on managing states, etc, through webcompat.com and also makes it easier to have the same state on both side.

@magsout @hallvors

**Comment by hallvors** [comment]
:up:
Sounds good to me. I volunteer for changing the label code again ;)

**Comment by karlcow** [comment]
Discussed in London. 
https://wiki.mozilla.org/Compatibility/Meetings/2016-06-work-week#.F0.9F.9B.A0_Moving_bug_stage_labels_to_milestones_for_webcompat.com

```
🛠 Moving bug stage labels to milestones for webcompat.com

Issue 886 on moving the status of issues from label to Milestones in Github.

Mike explains how labels and milestones are working on Github. Milestones prevent to be in two states. So we are thinking of getting rid of status-* to move milestones. To change a milestone, the issue API has a PATCH method.

We moved issues 886 to London Milestones.

    RESOLUTION: We ditch the label status-* in favor of milestones.
    ACTION: deepthi to fix 975, before moving to milestones.
    ACTION: miketaylr to erase the status-* labels on the repo.
    ACTION: miketaylr to fix functional tests for labels->milestones.
```

**Comment by miketaylr** [comment]
Writing some notes here for myself:

To list issues by milestone: https://developer.github.com/v3/issues/, there's a `milestone` param for the `GET /repos/:owner/:repo/issues` endpoint:

> if an integer is passed, it should refer to a milestone by its number field. If the string * is passed, issues with any milestone are accepted. If the string none is passed, issues without milestones are returned.

When creating issues with the `POST /repos/:owner/:repo/issues` endpoint, there's a `milestone` param that takes an integer:

> The number of the milestone to associate this issue with. NOTE: Only users with push access can set the milestone for new issues. The milestone is silently dropped otherwise.

Same goes for editing issues, we use a `milestone` param with an integer and use `PATCH /repos/:owner/:repo/issues/:number`.

**Comment by miketaylr** [comment]
I wonder if we don't want a seperate Milestone picker widget for webcompat, just like GitHub now. 

<img width="273" alt="screen shot 2016-07-12 at 2 28 18 pm" src="https://cloud.githubusercontent.com/assets/67283/16778650/e7bcf45e-483c-11e6-8fc9-9ef0a42abe8d.png">

(we wouldn't call it "Milestone", but maybe something like "Bug Status" or "Bug State"?)

Just trying to think through picking and setting of a milestone in addition to setting labels and not sure what the best way to do it is.

**Comment by karlcow** [comment]
> I wonder if we don't want a seperate Milestone picker widget for webcompat, just like GitHub now. 

Yes and if well done it could clarify a lot of things. The only issue would be the last Milestone(s): 

* One big bag for fixed, invalid, etc.
* Different bags for fixed, invalid, etc.

Another issue to test. How many issues can a milestone contains? :)

**Comment by MDTsai** [comment]
Read through this, so milestone will be used for status only, we need to remove current non-compat (or keep it as status-noncompat).

**Comment by karlcow** [comment]
Some thoughts around that. A quick search for status in the code. This is missing probably the CSS.
With @magsout we discussed options during our long walk to the closing event in San Francisco for the html/css part.

```
webcompat/api/endpoints.py
63:        return (edit.content, edit.status_code, {'content-type': JSON_MIME})
127:        # add "status-" before the filter param to match the naming scheme
129:        params.add('labels', 'status-' + issue_category)
196:        # add "status-" before the issue_category to match
198:        query_string += 'label:{0}'.format('status-' + issue_category)
240:        return (labels.content, labels.status_code,

webcompat/error_handlers/__init__.py
32:        resp = jsonify({'status': code, 'message': ERROR_DICT[code]})
33:        resp.status_code = code
68:def too_many_requests_status(err):
82:    resp.status_code = err.code

webcompat/helpers.py
458:    (content, status_code, response_headers) into a Response object.
467:    if resource.status_code != 404:
468:        return (resource.content, resource.status_code,

webcompat/static/js/lib/bugform.js
527:        if (response && response.status === 415) {
534:        if (response && response.status === 413) {

webcompat/static/js/lib/issue-list.js
267:    // NOTE: these filters don't need "status-" prefixes because appear in URL params

webcompat/static/js/lib/labels.js
158:    // We try to make sure only one "status" or "priority"-type label is set
159:    // If the change event comes from a "status" or "priority"-type label,
160:    // enumerate all checked "status" or "priority"-type labels and uncheck
164:    if (remotename.match(/^(status|priority)/) && evt.target.checked) {

webcompat/static/js/lib/models/issue.js
23:  _namespaceRegex: /(browser|closed|os|status)-/i,
111:        var msg = "There was an error editing this issues's status.";

webcompat/static/js/lib/models/label-list.js
17:* new issues.LabelList({labels: [{name:'status-worksforme', url:'...',
27:    this.set("namespaceRegex", /(browser|closed|os|priority|status)-(.+)/i);

webcompat/templates/contributors/site-outreach.html
14:    <li class="contributors__list__item contributors__list__item--lvl_down"><span><strong>Share with consideration</strong> Share any contact you attempted or made in the issue comments section.  It helps everyone to know the status so they can pitch in or not repeat work. That said -  be careful to not disclose private information such as names and emails. You may simply say: "I contacted someone at $COMPANY", "Someone from $COMPANY said this..."</span></li>

webcompat/templates/layout.html
11:  <meta name="apple-mobile-web-app-status-bar-style" content="black">

webcompat/webhooks/__init__.py
46:                labels = ['status-needstriage']
54:                if response.status_code == 200:
```

For example looking at the needstriage, we can see the extent 

```
webcompat/api/endpoints.py
114:    * needstriage
122:                     'needsdiagnosis', 'needstriage', 'sitewait']
137:    # Note that 'needstriage' here is primarily used on the homepage.
139:    # see /issues/search/needstriage.
141:    # been replaced with needstriage.
191:                     'needsdiagnosis', 'needstriage', 'sitewait']
204:    # been replaced with needstriage.

webcompat/static/css/development/components/box.css
15:  border-color: var(--base-stateNeedsTriage);

webcompat/static/css/development/components/issue-list.css
15:  --Issue-stateNeedsTriage: var(--base-stateNeedsTriage);
37:.wc-IssueList--needstriage {
38:  border-left: 5px solid var(--Issue-stateNeedsTriage);

webcompat/static/css/development/components/issue.css
24:.wc-Issue-information-header--needstriage {
25:  background-color: var(--base-stateNeedsTriage);

webcompat/static/css/development/components/style-variable.css
16:  --base-stateNeedsTriage: #f90; /* orange */

webcompat/static/css/development/components/tag.css
37:.wc-Tag--needstriage {
38:  border-color: var(--base-stateNeedsTriage);
42:.wc-Tag--needstriage.wc-Tag--filter:hover,
43:.wc-Tag--needstriage.wc-Tag--filter:focus,
44:.wc-Tag--needstriage.is-active,
45:.wc-Tag--needstriage.wc-Tag--label {
46:  background-color: var(--base-stateNeedsTriage);

webcompat/static/js/lib/diagnose.js
8:diagnose.NeedsTriageCollection = Backbone.Collection.extend({
10:  url: "/api/issues/category/needstriage"
13:diagnose.NeedsTriageView = Backbone.View.extend({
18:    this.issues = new diagnose.NeedsTriageCollection();
26:  template: _.template($("#needstriage-tmpl").html()),
39:  new diagnose.NeedsTriageView();

webcompat/static/js/lib/issue-list.js
268:    _filterRegex: /&*stage=(closed|contactready|needscontact|needsdiagnosis|needstriage|sitewait)&*/i,
432:        "needstriage",

webcompat/static/js/lib/models/issue.js
78:    this.set("stateClass", "needstriage");

webcompat/templates/contributors/diagnose-bug.html
2:  <li class="contributors__list__item"><span>Find a bug that "<a href="https://webcompat.com/issues?page=1&per_page=50&state=open&stage=needsdiagnosis&sort=created&direction=desc">Needs Diagnosis</a> or <a href="https://webcompat.com/issues?page=1&per_page=50&state=open&stage=needstriage&sort=created&direction=desc">Needs Triage"</a></span>

webcompat/templates/home-page/browse-issues.html
5:      <script type="text/template" id="needstriage-tmpl">

webcompat/webhooks/__init__.py
32:    - Add label needstriage to the issue
46:                labels = ['status-needstriage']
```

## Status 

1. needstriage
2. needsdiagnosis
3. needscontact
4. contactready
5. sitewait

## Closing an issue 

Then there is the special case for closing an issue. What do we do? There are different options:

* A milestone "closed" and an associated label for the reason 
* a milestone for each type of closed, aka a `closed-invalid` milestone, a `closed-incomplete` milestone, etc.

**Comment by karlcow** [comment]
The [API for milestones](https://developer.github.com/v3/issues/milestones/)

The way to set or remove a milestone on an issue.
https://developer.github.com/v3/issues/#edit-an-issue

> milestone | integer | The **number** of the milestone to associate this issue with or **null** to remove current. NOTE: Only users with push access can set the milestone for issues. The milestone is silently dropped otherwise.

**Comment by karlcow** [comment]
So I did a bit of testing on creation and deletion of milestones. The milestones id get incremented by one  (sequentially) as long as there is at least one milestone. On the other hand, it restarts at 1 after deletions of all milestones.

**Comment by karlcow** [comment]
This bug is ready to land. :) Thanks a lot to @MDTsai and @miketaylr for the work done in Taipei around developing the main structure.

Next steps. Staging for some tests.
Then deploy on the real site.

**Comment by karlcow** [comment]
Milestones have been created on the webcompat.com project.
https://github.com/webcompat/web-bugs/milestones

They are **not used yet**.

Next steps: 
1. Move the bugs to their own milestones without deleting the labels  (needs a script. I'm checking that today)
Special care needs to be done for `status-invalid` and not in milestones `non-compat`
2. Check if we have orphaned issues
3. Deploy the new code (not on Friday)
4. Let it "rest" for 24h
5. Remove the `status-*` labels, except for `status-needinfo`

**Comment by karlcow** [comment]
The script is done. Just waiting for @miketaylr review. And then we are due for a long run.

**Comment by miketaylr** [comment]
Thanks. Will review today.

**Comment by miketaylr** [comment]
Fixed by https://github.com/webcompat/webcompat.com/pull/1841. Thanks everyone. 💟

**Comment by karlcow** [comment]
Party time!
