### ISSUE TITLE
Crazy feature request: url shortener

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat.com#898]
Often times I'm dumping links into goo.gl so it's not so painful to type them into my phone. It wouldn't be much work to make our own URL shortener (just a simple db mapping from short-hyperlink to long-hyperlink), and then we could append the short URL to the bug report.

Maybe it's a bad idea, I dunno.

**Comment by miketaylr** [comment]
(Note, this would be in addition to the original URL -- we wouldn't touch that)

**Comment by magsout** [comment]
I don't understand the point ?

**Comment by miketaylr** [comment]
The point being, you're looking at an issue on your laptop -- and want to visit the site on your phone to see the problem.

The URL is http://blah.com/dlkfjldjf/dfkdjflkdjfl/lskdfjl/222___aspx.com/kill/me/now

The proposal would be to have the bug report say:

**URL**: http://blah.com/dlkfjldjf/dfkdjflkdjfl/lskdfjl/222___aspx.com/kill/me/now
**short url**: http://webcompat.com/a1

Or something like that. So then you just have to type the short one, and it will redirect to the original, long one.

**Comment by magsout** [comment]
Ah yes 💯💯💯💯👍

**Comment by karlcow** [comment]
## What I usually do.

I connect the phone with the WebIDE through USB or wifi. And I have the Web Console opened. I then type on the laptop in the console: `window.location = 'http://example.com/somewhere/with/a/very/long/funky/path'. Benefits: I'm already setup for the analysis.

## If we go the shortener way.

Let's at least make the shortener longer (hehe) `http://webcompat.com/l/a1` (aka a `L` to not clutter the top space of URLs and risk collisions in the future.) Note that I'm not a big fan of shortener. 

## QR code

It seems to be a redundancy with the QR code thingy? @tagawa

## More natural shortener.

The code for the link will be another character strings with a combination of chars disconnected from the bug. What about doing something like `https://webcompat.com/l/1234` with 1234 being the issue number. On desktop there is the notion of smart keywords. I wonder if it exists on Android. It would be then easy to program your own word redirection in the URL bar. something like `w 1234`. Also, the `http://webcompat.com/l/` can become a home page with a very simple form to enter the issue number redirecting to the right link. So You can bookmark this page on your device.

## nitpicking (me being me. yes you can make fun of me ;) ) 
When giving example of domains `s/blah.com/example.com/` ;)

**Comment by miketaylr** [comment]
> It seems to be a redundancy with the QR code thingy? @tagawa

Oh! I forgot about this. >_<

Let's just close this issue and I'll remember to use QR codes. Less work. :sleeping:

**Comment by miketaylr** [comment]
Some context to expand on Karl's "More natural shortener." idea:

```
[4:51 PM] <karlcow> note the webcompat.com/l/ proposal too. :)
[4:56 PM] <miketaylr> karlcow: also point taken about example.com :)
[4:57 PM] <miketaylr> karlcow: https://webcompat.com/l/1234 would map to https://webcompat.com/issues/1234?
[4:57 PM] <miketaylr> or the URL in that issue?
[4:57 PM] <miketaylr> that's an interesting idea
[5:02 PM] <karlcow> the URL in the issue
[5:03 PM] <karlcow> another possibility is to do w3c way
[5:03 PM] <karlcow> aka a comma tool
[5:03 PM] <karlcow> webcompat.com/issues/1234,l  <- comma + l  for links
[5:04 PM] <miketaylr> cool
```

**Comment by tagawa** [comment]
You can't resist the pull of QR codes. Welcome to the dark side :sunglasses:
