### ISSUE TITLE
inline-svg instead of icon-font

### ISSUE THREAD

**Issue by magsout** [webcompat/webcompat.com#899]
http://www.sitepoint.com/icon-fonts-vs-svg-debate/

### Header
- [ ] Search
- [ ] Contribute
- [ ]  Issues
- [ ] Log in
- [ ] Home
- [ ] Caret down

### Submit form

- [ ] Cloud upload

### Threesteps

- [ ] Bug reporting
- [ ]  Bug diagnosis  
- [ ]  Site outreach

###  Thanks 

- [ ]  Browser stack

### Footer 

- [ ] Twitter
- [ ] Github 

### Search

- [ ] Caret down
- [ ] Search
- [ ]  Github

### Issue
- [ ] cog

**Comment by miketaylr** [comment]
Yeah, seems like icon fonts aren't cool anymore. +1 for inline svg at some point.

**Comment by magsout** [comment]
Just re up this issue.

What do you think @zoepage  ?

**Comment by zoepage** [comment]
@magsout I agree on SVG. Could be a great issue for our all-hands list? :)

**Comment by magsout** [comment]
@zoepage added on my all hands SF todolist ;)

**Comment by zoepage** [comment]
This will be fully solved by the refactor in 2 weeks. Already implemented in http://webcompat.github.io/design/
