### ISSUE TITLE
Update Python deps

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat.com#902]
Just discovered https://requires.io/github/webcompat/webcompat.com/requirements/?branch=master, and we could update some stuff. (After testing).

**Comment by karlcow** [comment]
Creating a visual bookmark.

![capture d ecran 2016-02-09 a 17 24 39](https://cloud.githubusercontent.com/assets/505230/12910931/168f94d0-cf52-11e5-8373-801940006bf2.png)

Github-Flask from 0.3.4 to 3.1.1 ouch. indeed. :)
Too bad that's the only one who would prevent us from moving to python3. hmm wait on the project page they say:

> GitHub-Flask is an extension for authenticating Flask applications with GitHub. It also provides support for various other requests to the GitHub API. Compatible with Python 2.7 and 3.4.

https://github.com/cenkalti/github-flask

So I guess indeed we could.

**Comment by karlcow** [comment]
Pillow and requests should be updated at least in priority.

**Comment by karlcow** [comment]
```
→ git checkout -b 902/1
Switched to a new branch '902/1'

→ subl requirements.txt 

→ git commit -m 'updating requests and pillow for security reasons' requirements.txt 
[902/1 b6ce3ed] updating requests and pillow for security reasons
 1 file changed, 3 insertions(+), 3 deletions(-)

→ pip install -r requirements.txt
…
Successfully installed Pillow requests
Cleaning up...

→ nosetests
...................................
----------------------------------------------------------------------
Ran 35 tests in 4.241s

OK

→ python run.py
secrets /Users/karl/code/webcompat.com
 * Running on http://localhost:5000/ (Press CTRL+C to quit)
 * Restarting with stat
secrets /Users/karl/code/webcompat.com

127.0.0.1 - - [09/Feb/2016 17:35:42] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [09/Feb/2016 17:35:43] "GET /api/issues/labels?per_page=100 HTTP/1.1" 304 -
127.0.0.1 - - [09/Feb/2016 17:35:48] "GET /api/issues/category/new HTTP/1.1" 304 -
127.0.0.1 - - [09/Feb/2016 17:36:32] "GET /issues/324 HTTP/1.1" 200 -
127.0.0.1 - - [09/Feb/2016 17:36:34] "GET /api/issues/324 HTTP/1.1" 304 -
127.0.0.1 - - [09/Feb/2016 17:36:39] "GET /api/issues/324/comments HTTP/1.1" 304 -
127.0.0.1 - - [09/Feb/2016 17:36:39] "GET /?open=1 HTTP/1.1" 200 -
127.0.0.1 - - [09/Feb/2016 17:36:47] "GET /img/valid.svg HTTP/1.1" 200 -
127.0.0.1 - - [09/Feb/2016 17:36:48] "GET /img/invalid.svg HTTP/1.1" 200 -
127.0.0.1 - - [09/Feb/2016 17:37:04] "GET /img/loader.gif HTTP/1.1" 200 -
127.0.0.1 - - [09/Feb/2016 17:37:09] "POST /issues/new HTTP/1.1" 302 -
127.0.0.1 - - [09/Feb/2016 17:37:09] "GET /thanks/325 HTTP/1.1" 200 -
```

ok so far so good.
http://localhost:5000/issues/325


I still have an issue with
`https://github.com/login/oauth/authorize?scope=public_repo&redirect_uri=http%3A%2F%2Flocalhost%3A5000%2Fcallback&client_id=`

but that's unrelated.

**Comment by karlcow** [comment]
ok fixed my login issues, I'll go hide under a rock for the reason ;)

**Comment by magsout** [comment]
ah ah, what is the reason ?

**Comment by karlcow** [comment]
ok. upgraded the Github-Flask and the universe didn't collapse. 

@magsout secrets.py missing my keys ;)

**Comment by karlcow** [comment]
I propose we remove Flask-Limiter. We are not using it.

**Comment by karlcow** [comment]
Ah no we do. in the API. Wrong string search.

**Comment by karlcow** [comment]
We use babel. for this part only it seems (if I'm not mistaken)
https://github.com/webcompat/webcompat.com/blob/master/webcompat/helpers.py#L42

```python
@app.template_filter('format_delta')
def format_delta_filter(timestamp):
    '''Jinja2 fiter to format a unix timestamp to a time delta string.'''
    delta = datetime.now() - datetime.fromtimestamp(timestamp)
    return format_timedelta(delta, locale='en_US')
```

Which in return seems to be used at 
https://github.com/webcompat/webcompat.com/blob/master/webcompat/templates/ratelimit.txt

I wonder if we might want in the future to get rid of this module for just this use.

**Comment by karlcow** [comment]
Thinking out loud.

About the babel package the feature we are using in this package is:
https://github.com/python-babel/babel/blob/dd467ca2224cb6e2eba570c647b3843affe396da/babel/dates.py#L820

```python
def format_timedelta(delta, granularity='second', threshold=.85,
                     add_direction=False, format='long',
                     locale=LC_TIME):
```

which means we call it like this 

```python
format_timedelta(delta, granularity='second', threshold=.85, add_direction=False, format='long', locale='en_US')
```

It's cool to use timedelta when there is a lot of variations from days to seconds. It gives a human date. Not so sure in our case, which is also on the order of minutes or seconds.

**Comment by karlcow** [comment]
OK I didn't have any issue with nosetests.
and monkey testing.
I was unable to run the functional tests. The browser starts and then the intern tests do not start.

@miketaylr Has something changed with the instructions there:
https://github.com/webcompat/webcompat.com/blob/master/CONTRIBUTING.md#functional-tests

Also webcompat.sh is not very useful in its current state. Either we should kill it or make it more useful :)

I will try a pull request and we could put that into staging. So we can see if it's behaving well.
