### ISSUE TITLE
style selection for CSSFixme (for Windows)

### ISSUE THREAD

**Issue by hallvors** [webcompat/webcompat.com#905]
Selection looks a bit weird if you select code with highlighted fixes.

For example, try to go to https://webcompat.com/tools/cssfixme and fix `p{display:-webkit-flex}` and select the output. It looks as if the extra highlighted part wasn't selected..

![oddity](https://cloud.githubusercontent.com/assets/120136/12372982/42ade4f4-bc6a-11e5-9f6f-4ea9fb380caa.png)

I suggest we add some styling for `pre strong::selection` to undo this weird effect.
https://developer.mozilla.org/en-US/docs/Web/CSS/::selection
@magsout ?

**Comment by magsout** [comment]
@hallvors seems good. Let me finished with my current PR, and next I'll do it  (same as your old email that you sent me)

**Comment by magsout** [comment]
@hallvors still an issue? I can't reproduced

**Comment by hallvors** [comment]
So, turns out this is a Windows-specific issue :-o
(Well, Firefox on Mac is different - so I assume it's Win, haven't tested on *nix but @deepthivenkat can perhaps help with that?)

What do we do? Add CSS that only is applied on Windows, by some mechanism?

**Comment by magsout** [comment]
@hallvors 

>What do we do? Add CSS that only is applied on Windows, by some mechanism?

nah, we can add some styling for all browser... using your idea

**Comment by bijiezhu** [comment]
When I tested the issue on Linux Mint and Chrome browser, something different happens
![screenshot from 2017-03-27 22-53-52](https://cloud.githubusercontent.com/assets/11596921/24388397/5173d80a-1348-11e7-8089-03b9cc3c6cc5.png)

**Comment by bijiezhu** [comment]
@hallvors  Something weird happens on my Linux when using chrome browser 
![screenshot from 2017-03-27 22-53-52](https://cloud.githubusercontent.com/assets/11596921/24411108/04ac81ba-13a3-11e7-92db-529f200cb961.png)

**Comment by bijiezhu** [comment]
And I would like to try this

**Comment by zoepage** [comment]
@bijiezhu Have fun and let us know, if you have any questions! :)

**Comment by zoepage** [comment]
As we removed CSSFIX from the repo for now, I'm closing.
