### ISSUE TITLE
[ui] upload image in comment

### ISSUE THREAD

**Issue by magsout** [webcompat/webcompat.com#906]
We have this 
![capture d ecran 2016-01-26 a 09 51 04](https://cloud.githubusercontent.com/assets/1997108/12576209/577f2564-c412-11e5-9882-4a376e5573d8.png)

But the inital design of @calexity is better IMHO.

https://github.com/webcompat/design/blob/master/2_Current%20Designs/Issues/Sketch%20and%20PSDs/IssuesStyle.psd

Any thought? @karlcow @hallvors @miketaylr @Raphseck

**Comment by miketaylr** [comment]
@magsout agreed. Right now we only support file selection (I plan on adding DnD support this quarter), so we could just say "<a>Select an image</a> to attach." or keep it as "Attach a screenshot image" but use that style.

**Comment by cch5ng** [comment]
hi, I'm interested in applying to the upcoming outreachy internship. I'd like to work on this issue as part of my application.

**Comment by cch5ng** [comment]
@magsout do you want this change to apply to only new comments for existing issues?
(i.e. like http://localhost:5000/issues/252)

should this also apply to the form for new issues?
(i.e. like http://localhost:5000/?open=1)

![screen shot 2016-03-11 at 3 32 11 pm](https://cloud.githubusercontent.com/assets/4755432/13718455/e9e7eada-e79e-11e5-8ceb-6e93aca9e03c.png)

**Comment by magsout** [comment]
Hello @cch5ng , thanks for your help. 

Yes,  it is to improve the uploader only in a new comment for existing issue.

For now we just keep the ability to sent an image after a click on a input. Drag and drop Will be add later.

**Comment by miketaylr** [comment]
Thanks again @cch5ng -- this looks so much better.

<img width="838" alt="screen shot 2016-03-25 at 6 31 49 pm" src="https://cloud.githubusercontent.com/assets/67283/14056270/deca4976-f2b7-11e5-8874-f363b373ceef.png">
