### ISSUE TITLE
Keyboard navigation and focus

### ISSUE THREAD

**Issue by karlcow** [webcompat/webcompat.com#907]
I was working on this [webcompat issue](https://webcompat.com/issues/141) when I tried to navigate the webcompat page with tab. And I have the feeling we do a poor job at it too.

**Comment by magsout** [comment]
you are absolutely right.

**Comment by magsout** [comment]
what I suggest is to double in 90% of the case :hover with :focus.

**Comment by magsout** [comment]
10% is special cas where hover and focus have no sense

**Comment by magsout** [comment]
@karlcow you think we need something more for Keyboard navigation and focus ?

**Comment by karlcow** [comment]
@magsout do a pull request on this one. And if other issues surface in the future, will create another issues. Small steps. :)

**Comment by magsout** [comment]
@karlcow yes, I did it https://github.com/webcompat/webcompat.com/commit/5af80fc5c56ced775838520f5dd494d146646fba and already merged

**Comment by miketaylr** [comment]
Seems like this one is fixed?
