### ISSUE TITLE
Add Brave browser support on webcompat

### ISSUE THREAD

**Issue by swarnava** [webcompat/webcompat.com#908]
currently webcompat detecting Brave browser as Chrome. 

Sample Useragent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_2) AppleWebKit/537.36 (KHTML, like Gecko) brave/0.7.11 Chrome/47.0.2526.110 Brave/0.36.5 Safari/537.36

website: https://brave.com

**Comment by magsout** [comment]
Thanks @swarnava

**Comment by miketaylr** [comment]
We use https://github.com/ua-parser/uap-python for UA string parsing -- @swarnava can you file a bug upstream (if there isn't already one)? When it gets fixed, we can update.

**Comment by swarnava** [comment]
I just did here: https://github.com/ua-parser/uap-python/issues/44

**Comment by swarnava** [comment]
https://github.com/ua-parser/uap-core/issues/128

**Comment by swarnava** [comment]
can we start working here?

**Comment by karlcow** [comment]
@swarnava what do you mean? :)

**Comment by karlcow** [comment]
Ah I see there is a PR for Brave 
https://github.com/ua-parser/uap-core/pull/129

So I guess @swarnava is asking us to update the lib?

**Comment by miketaylr** [comment]
As soon as it's available in a stable version of https://github.com/ua-parser/uap-python -- looks like they haven't updated in 2 months there.

**Comment by miketaylr** [comment]
For future reference, we currently use `0.6.1` on the site --- I suppose anything higher than that will contain the Brave code that got merged in. As of today, the published version of  https://github.com/ua-parser/uap-python is still 0.6.1.

**Comment by miketaylr** [comment]
To fix this, once uap-python is updated, we just need to bump in requirements.txt.

**Comment by adamopenweb** [comment]
Looks like the latest is now 0.7.1.

**Comment by miketaylr** [comment]
This should be fixed in #1304. Let's close here since @karlcow has an active branch.
