### ISSUE TITLE
m.facebook.com: <link rel=manifest> not sent to Opera

### ISSUE THREAD

**Issue by mathiasbynens** [webcompat/webcompat.com#911]
Browser/system info:

* Opera 35.0.2066
* OS X 10.11.3
* UA string: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.82 Safari/537.36 OPR/35.0.2066.37`

#### Reproduction steps

1. Navigate to: https://m.facebook.com/

#### Expected Behavior

Source code contains `<link rel="manifest" href="/data/manifest" />` just like when viewed in Chrome.

#### Actual Behavior

Source code does not contain `<link rel="manifest" href="/data/manifest" />` unlike Chrome.

Facebook seems to base this on the UA HTTP header. Opera for Android supports manifests just like Chrome for Android does, so please send the manifest to Opera as well.

FTR, Chrome’s UA string (for which the manifest is referenced correctly) looks like this:

```
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.103 Safari/537.36
```

**Comment by mathiasbynens** [comment]
cc @hdragomir

**Comment by hallvors** [comment]
(Just for the record: it's better to report web site bugs here: https://github.com/webcompat/web-bugs/issues :) )

**Comment by mathiasbynens** [comment]
Whoops, sorry! #facepalm

**Comment by mathiasbynens** [comment]
Closing in favor of https://github.com/webcompat/web-bugs/issues/2232.
