### ISSUE TITLE
[layout] wrapping of long code lines

### ISSUE THREAD

**Issue by karlcow** [webcompat/webcompat.com#913]
This morning, webcompat.com seems to be broken.

The long lines of codes are not being wrapped anymore.
![broken-webcompat](https://cloud.githubusercontent.com/assets/505230/12876693/948213fa-ce48-11e5-9b42-a9caad371d9d.png)

**Comment by miketaylr** [comment]
Probably related to the refactor we deployed on Friday.

**Comment by magsout** [comment]
Ooops I'm on it. My bad
