### ISSUE TITLE
[layout] small images are pixelated

### ISSUE THREAD

**Issue by karlcow** [webcompat/webcompat.com#914]
Since this morning the images which are smaller than the comment box are being displayed as 100% of the width of the comment box. It makes them pixelated.

![broken-webcompat](https://cloud.githubusercontent.com/assets/505230/12876693/948213fa-ce48-11e5-9b42-a9caad371d9d.png)

**Comment by miketaylr** [comment]
Probably related to the refactor we deployed on Friday.
