### ISSUE TITLE
[functional] Upload link in comments doesn't work anymore

### ISSUE THREAD

**Issue by karlcow** [webcompat/webcompat.com#915]
Since this morning, it seems the upload link for images is not working.

**Comment by miketaylr** [comment]
Interesting, probably related to the deploy I did on Friday -- https://github.com/webcompat/webcompat.com/releases/tag/v2.3.1.

I can take a closer look in the morning.

**Comment by magsout** [comment]
@karlcow you mean here ?

![capture d ecran 2016-02-08 a 12 21 45](https://cloud.githubusercontent.com/assets/1997108/12884441/8c9be22c-ce5e-11e5-9d68-54fdc990957a.png)

**Comment by karlcow** [comment]
yes!
