### ISSUE TITLE
Improvement Comment issue

### ISSUE THREAD

**Issue by magsout** [webcompat/webcompat.com#922]
- better line-height
- highlight link 

https://webcompat.com/issues/1930

![capture d ecran 2016-02-15 a 21 55 42](https://cloud.githubusercontent.com/assets/1997108/13060066/08e78450-d42f-11e5-9c3d-06fe73f9ccb7.png)

**Comment by miketaylr** [comment]
:+1: 

Also the padding could use a bit more balance.

**Comment by miketaylr** [comment]
to compare:

![](https://cldup.com/nDDPvDnFIh-2000x2000.png)

**Comment by magsout** [comment]
ah yes, @miketaylr Header and Content have same padding.

**Comment by magsout** [comment]
Let's close
