### ISSUE TITLE
[bug] fixed issues are not closed

### ISSUE THREAD

**Issue by karlcow** [webcompat/webcompat.com#923]
We have an issue currently in the UI.

![capture d ecran 2016-02-17 a 10 22 25](https://cloud.githubusercontent.com/assets/505230/13096935/84fc6808-d560-11e5-825f-7681657af8b9.png)

This is a fixed issue. So it should be labeled as closed, but it says: "New issue"

**Comment by miketaylr** [comment]
cc @hallvors - I think he did something related-ish not too long ago. 

(but this would be a good first bug for anyone else)

**Comment by hallvors** [comment]
This is #832

**Comment by hallvors** [comment]
(And it is indeed a good-first-patch - the master bug is labelled correctly as such :))
