### ISSUE TITLE
Syntax higlighter falls apart when meeting strange encoding

### ISSUE THREAD

**Issue by karlcow** [webcompat/webcompat.com#924]
Probably not really a bug for us but more for the library which we are using on webcompat.com
See https://webcompat.com/issues/1072#issuecomment-186973303

**Comment by miketaylr** [comment]
Hm, yes. Probably worth filing against https://github.com/PrismJS/prism.

**Comment by miketaylr** [comment]
Seems like it's fixed. Let's close.
