### ISSUE TITLE
Add an Issue template

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat.com#925]
We take care of this on the front-end, but if someone reports an issue directly via the GitHub interface we miss out on some stuff. 

This issue is about copying the template we use on webcompat.com into an issue template that will be used by the web-bugs repo.

See https://help.github.com/articles/creating-an-issue-template-for-your-repository/ for how to make that work. 

(In theory, this shouldn't affect the webcompat.com front-end)

**Comment by dshgna** [comment]
Created pull request in the web-bugs repo. (https://github.com/webcompat/web-bugs/pull/2325)

**Comment by miketaylr** [comment]
Yesssss

**Comment by miketaylr** [comment]
![](https://cldup.com/haozzbCkp_-3000x3000.png)
