### ISSUE TITLE
CSS fixme highligh is suddenly dark-on-dark :-o

### ISSUE THREAD

**Issue by hallvors** [webcompat/webcompat.com#926]
Caused by https://github.com/webcompat/webcompat.com/commit/c4b52e63695c01acf71141ba72dbcf3fe1541684#diff-d78febd34e89b24b3552d063128eb28aR6

```
.wc-CSSFixme-resultat strong {
    background-color: #404040;
}
```
This regression needs fixing.
(To kill two birds with one stone maybe you could close #905 while you're at it)

**Comment by hallvors** [comment]
Ping @magsout

**Comment by miketaylr** [comment]
@hallvors can you give some STR or a screenshot?

**Comment by hallvors** [comment]
STR: go to https://webcompat.com/tools/cssfixme and try to fix ```p{display:-webkit-flex}```

**Comment by hallvors** [comment]
![foo](https://cloud.githubusercontent.com/assets/120136/13410221/cd819fb4-df36-11e5-96b0-c7a5da089757.png)

**Comment by miketaylr** [comment]
Yep, seems trivial to fix. I can write a patch.
