### ISSUE TITLE
Visual style regressions for QR code stuff

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat.com#930]
STR:

Go to any issue page, click on QR code.

The qr icon itself should should be in the little gray bar, and should be bigger when clicked.

![](https://cldup.com/Y_l4SPJCj7-2000x2000.png)

**Comment by dshgna** [comment]
Hi @miketaylr 

Could you clarify if the following visual style meets the requirement, please?

(https://rawgit.com/dshgna/dshgna.github.io/master/images/930.PNG)

**Comment by magsout** [comment]
@dshgna I think that's what @miketaylr meant . IMO, I find the position much better

**Comment by dshgna** [comment]
@magsout Thanks for the feedback! I'll commit and make the pull request then.

**Comment by magsout** [comment]
@dshgna :+1:

**Comment by miketaylr** [comment]
Yes, thanks! :balloon:
