### ISSUE TITLE
Add travis lint task (grunt, webpack?)

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat.com#945]
So I don't break the stupid thing again. :sob: :person_frowning: 

https://www.npmjs.com/package/grunt-travis-lint

**Comment by magsout** [comment]
Or maybe https://github.com/webcompat/webcompat.com/pull/909

**Comment by miketaylr** [comment]
Yeah, you're right. Not much point investing time in grunt when webpack should be the way forward.

**Comment by zoepage** [comment]
As the webpack refactor will not land soon (I guess) and this seems pretty straight forward, shall we add the pkg @miketaylr ?
