### ISSUE TITLE
CSS Fix me is not submitting the form

### ISSUE THREAD

**Issue by karlcow** [webcompat/webcompat.com#947]
We broke https://webcompat.com/tools/cssfixme
Enter a CSS
Click on Fix it!

Nothing is happening.

In the console:

```
mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create cssfixme.min.js:6:16186
TypeError: declarations[i].property is undefined cssfixme.min.js:6:308
```

**Comment by magsout** [comment]
Strange, it works for me

![capture d ecran 2016-03-07 a 06 19 40](https://cloud.githubusercontent.com/assets/1997108/13561375/a61f6b36-e42c-11e5-8250-62d5fb4f0e92.png)

**Comment by karlcow** [comment]
And it's working for me too now. Grmph!
Thanks @magsout
