### ISSUE TITLE
Documentation:Scopes required for Personal access token generation

### ISSUE THREAD

**Issue by tsah20** [webcompat/webcompat.com#948]
While creating the personal access token which scopes access is  required for the project?

**Comment by miketaylr** [comment]
Oops, what a silly oversight.

@tsah20 it should be `public_repo`.

**Comment by miketaylr** [comment]
To fix this docs bug, we would need to add the scope in the relevant part of https://github.com/webcompat/webcompat.com/blob/master/CONTRIBUTING.md#configuring-the-server.
