### ISSUE TITLE
Management/Admin scripts for the project

### ISSUE THREAD

**Issue by karlcow** [webcompat/webcompat.com#965]
We start to have a couple of scripts and management tasks that we need to straighten a bit. 
@miketaylr @magsout feedback?
- `Makefile`
- `Gruntfile.js`
- `webcompat.sh`
- `labels.py` The recent script created by @dshgna https://github.com/webcompat/webcompat.com/issues/557 for labeling initialization
- `run.py`

It's piling up at the root and starts to be a bit esoteric. The deployment scripts of @miketaylr are not there either. 

What about creating a directory `utilities` or `commands` or `admin`, where the scripts are kept and having a single script in the root directory from where they are call. It can be the Makefile or a bash script or a python script, but just one calling the others. :)

**Comment by magsout** [comment]
Yeah good idea. I used to see a _scripts_ directory. 

Maybe we can add eslint directly in `package.json` @miketaylr

**Comment by karlcow** [comment]
Who is using `webcompat.sh` as-is in the root directory? @miketaylr @magsout @hallvors

**Comment by magsout** [comment]
@karlcow hum not me even if  I created the recipes.

**Comment by karlcow** [comment]
So maybe `webcompat.sh` could be deleted. :joy: and if we need it again, we could improve something through a python script testing that the right components and paths are here. Right now starting the functional tests are a bit cumbersome and I guess it makes it more unlikely that people will run them.

**Comment by magsout** [comment]
>So maybe webcompat.sh could be deleted

yes agreed

**Comment by miketaylr** [comment]
> Who is using webcompat.sh as-is in the root directory? @miketaylr @magsout @hallvors

Late reply, but no - I don't.

**Comment by miketaylr** [comment]
> The deployment scripts of @miketaylr are not there either.

We probably won't include the deployment scripts in the public repo, FWIW.

**Comment by karlcow** [comment]
> We probably won't include the deployment scripts in the public repo, FWIW.

Added to London Agenda for discussions https://wiki.mozilla.org/Compatibility/Mobile/2016-06-work-week#Deployment_scripts_for_webcompat.com

**Comment by miketaylr** [comment]
I wonder if there's anything actionable left in this issue. Adding "needs-decision".

**Comment by karlcow** [comment]
Let's close it. I think we reached a stable position. We could improve with specific install scripts. but that would be a different type of scripts and stories.
