### ISSUE TITLE
[ux] Time of a comment should appear under post

### ISSUE THREAD

**Issue by swarnava** [webcompat/webcompat.com#966]
On mobile, the timeline is messing with reporter's name, can we make it under issue's comment?

![Screenshot of the site issue](https://webcompat.com/uploads/2016/3/e648b56d-b0b5-42b5-b6d0-4ababd6494f9.png)

**Comment by magsout** [comment]
There is patch waiting production. Thanks for the report

**Comment by magsout** [comment]
Here https://github.com/webcompat/webcompat.com/commit/fa1750ee0a30703e977a074d7af75f848c2450a0, it was fixed with new position of QRCode

**Comment by magsout** [comment]
I forgot to close since it is fixed
