### ISSUE TITLE
The attached image is not disaplyed when commenting to close an issue on Webcompat.com

### ISSUE THREAD

**Issue by DiveshRoopowa** [webcompat/webcompat.com#976]
URL: https://webcompat.com/issues/2359
Browser / Version: Firefox 45.0.1
Operating System: Windows 10
Problem type: With regards to Webcompat.com when commenting to close an issue together with an image. The image is not displayed after the comments are posted   

Steps to Reproduce:
    Navigate to: https://webcompat.com/issues/2359
    …
Expected Behavior: The comments are posted and the attached image is displayed.

Actual Behavior: The comments are posted but without the attached image.
@miketaylr

**Comment by miketaylr** [comment]
This doesn't reproduce anymore.
