### ISSUE TITLE
Add a license field to package.json

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat.com#977]
`npm WARN package.json webcompat@ No license field.`

We use MPL 2: https://github.com/webcompat/webcompat.com/#license

**Comment by karlcow** [comment]
@deepthivenkat It's usually better if you ask for review on the Pull Request itself.
https://github.com/webcompat/webcompat.com/pull/1019

**Comment by miketaylr** [comment]
Yep, just ping me for review on the PR when it's ready. 👍

**Comment by deepthivenkat** [comment]
#1034

**Comment by deepthivenkat** [comment]
#1034

**Comment by deepthivenkat** [comment]
#1038
