### ISSUE TITLE
Determine minimum supported Node version and update docs

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat.com#979]
(Also it would be good to see if everything worked on a modern version, like v4 or v5)

**Comment by magsout** [comment]
see https://docs.npmjs.com/files/package.json#engines

>(Also it would be good to see if everything worked on a modern version, like v4 or v5)

it's working on node v4 et V5

**Comment by miketaylr** [comment]
Ohhhhhhhh, which version are you running @magsout?

**Comment by magsout** [comment]
```
MacBook-Air:~ GuillaumeDEMESY$ node --version
v5.7.0
MacBook-Air:~ GuillaumeDEMESY$ npm -v
3.6.0
MacBook-Air:~ GuillaumeDEMESY$ 
```

**Comment by magsout** [comment]
I updated recently, before I had node v4

**Comment by miketaylr** [comment]
Fancy. I guess I should update then...

**Comment by miketaylr** [comment]
I think we should probably stick with 4.4.x, which is the LTS version: https://nodejs.org/en/download/releases/

**Comment by magsout** [comment]
We can only determine minimum { "engines" : { "node" : ">=***" } } not maximum ? so why 4.4 ?

**Comment by miketaylr** [comment]
@magsout I don't even think we should check this in code, just recommend people use the current LTS version of Node (which happens to be 4.4.x right now).

**Comment by miketaylr** [comment]
I suppose we could check for Node >= 4 in package.json, if someone is looking for that information. Turns out npm won't actually enforce that: https://docs.npmjs.com/files/package.json#engines (which is OK, I think).
