### ISSUE TITLE
move functional tests to BrowserStack (+ Chrome testing)

### ISSUE THREAD

**Issue by cch5ng** [webcompat/webcompat.com#980]
(update 02.18.17) checklist for this isssue
* [ ] 1 either clean up current intern tests which are failing (or at least know clearly which tests are currently failing as expected, locally and on travis)
* [ ] 2 update travis and intern.js configurations to run automated browser tests on BrowserStack.com (as of 07.2016 configurations were working for firefox, chrome on BrowserStack but was having some challenge configuring separate scripts to run different configurations)
* [ ] 3 make better sense of current failing tests resulting on BrowserStack (step 1 should greatly help with this)
* [ ] 4troubleshooting 2 functional authenticated search tests (one is done)
* [x] 5 add a thank you to BrowserStack to the webcompat.com site (and README), per their request from sales rep for giving free test accounts to webcompat
  * my main contacts from 07.2016 were Ady (Adithya Chadalawada) I believe in sales/marketing role and Ashwin from support side
* [x] 6 move the BrowserStack account from my personal email to a general webcompat email account (so I don't become a bottleneck in the future)

(updated 06.13) this issue/automated test enhancement requires
- updating travis and intern.js configurations to run automated browser tests on BrowserStack.com
- troubleshooting 2 functional authenticated search tests (one is done)
- adding a thank you to BrowserStack to the webcompat.com site (and README), per their request from sales rep for giving free test accounts to webcompat

some of the discussion of requirements is in [this old PR](https://github.com/webcompat/webcompat.com/pull/1026)

(old March 2016) hi (I'm one of the outreachy applicants). while I was testing css changes for a PR, I decided to check with Browser Stack whether they would offer a free testing account for this project. one of their sales reps replied yes as long as there would be a mention of Browser Stack on the project github page and website.

I was thinking there would be impacts to these files: about page/view, README.md, and CONTRIBUTING.md. I think other people who need to test the UI would be able to request an account for testing in the future. it seems handiest for IE testing (older versions). 

does this sound OK? hope this is the right place to ask.

for ref: http://www.browserstack.com/
https://www.browserstack.com/pricing  (scroll to free for open source)

**Comment by miketaylr** [comment]
Hi @cch5ng! 

This would be cool. Currently we run our Intern tests on a Firefox instance via Travis CI (which has a built-in Firefox plugin). But more browser coverage would be awesome.

(It would also require figuring out how to get the Intern tests to run there, and how that interacts with Travis).

**Comment by magsout** [comment]
woot sounds good.

**Comment by cch5ng** [comment]
hi @miketaylr sorry for the delay. I just sent their sales rep a message to see if they are ok with adding the automated tests through TravisCI. looking at their docs, I see there is support for TravisCI from BrowserStack but I am just wondering if they might have limits in terms of throughput or browsers/versions they'd be willing to support. I'll probably just forward her response to you.

**Comment by cch5ng** [comment]
@miketaylr I got a BrowserStack account and started looking at the docs. a few questions (thanks in advance):

* is there a generic webcompat test email I should use for the BrowserStack account? TravisCI's .yml file would need to be updated with the BrowserStack username + auth key. I can use mine for now.
* is there some base list of environments which should be tested (OS, browser, version)?
* there was a recommendation about encrypting the BrowserStack account login info but in the Travis docs there seems to be some caveat where encrypted environment variables will result in the travis tests only being run for project participants (https://docs.travis-ci.com/user/pull-requests#sts=Security Restrictions when testing Pull Requests). is this ok?
* is there any recommended way I should test my changes to .travis.yml without making a bunch of dummy PR's to the repo? I saw a stackoverflow topic about running travis locally using a docker container, is that better?

**Comment by miketaylr** [comment]
Hey @cch5ng!

I have a generic webcompat@gmail.com test account that I've used to set up some throwaway test accounts. If you shoot me an email at (miket@mozilla.com) I can give you access to that email account as a delegate (assuming you have a Google Account).

As for base environments, we can start simple, like Mac/Windows and latest browsers. Once we get it running we can tweak our support matrix.

(I suppose we also need to set up the intern tests to run on BrowserStack as well: https://theintern.github.io/intern/#hosted-selenium)

I think having encrypted env vars is OK. We already do that for the GitHub username/login (of a bot) used for the functional tests. I think if I add you to the webcompat org, you should have access to the repo's settings on Travis. I'll do that now and ping me if it gives you any trouble.

Thanks for working on this!

**Comment by cch5ng** [comment]
I opened an issue with intern (https://github.com/theintern/intern/issues/622) but will look more at the intern config docs. maybe I didn't change enough.

right now I am testing this by committing changes to my forked repo (synced with travisci). should this be sufficient to test or would I have to commit changes to the main repo?

**Comment by cch5ng** [comment]
@miketaylr I'm seeing BrowserStack running tests. but most are failing. I'm not sure what to enter for the github user credentials (without using my own login)

`node_modules/.bin/intern-runner config=tests/intern user=testusername pw=testpassword`

**Comment by miketaylr** [comment]
@cch5ng yeah, the login and pw are set as Travis encrypted env vars. You should have access to the main webcompat repo now, so one option is to make a branch to test with -- it should run tests from your commits on that branch.

**Comment by miketaylr** [comment]
(if you don't have push access, let me know)

Just be sure to send a PR from a branch when you're ready for review, thanks!

**Comment by cch5ng** [comment]
@miketaylr do you mind if I add a couple environment vars to Travis for browserstack authentication?

**Comment by miketaylr** [comment]
Nope, go for it.

**Comment by cch5ng** [comment]
@miketaylr when I try to run the browser tests locally, I have about half passing and I think the failing ones may be due to my setup for github access. but when I try to run the browser tests on browserstack, it seems as though most of the tests are failing. would this be due to the config of the intern proxy? should I need to change that?

**Comment by cch5ng** [comment]
looks like the issue is the intern.js siteRoot value. right now BrowserStack is giving a lot of cannot find element errors and it's looking for a local web application instance. is there some qa instance I should repoint to?

**Comment by cch5ng** [comment]
I will break this out into a few separate issues.

1. changes to existing tests to make them ready for testing on multiple browsers
2. config changes for travis, intern. this also includes npm scripts for running tests in different environments.
3. docs and content changes. for contributors and also recognition of browserstack free account.

**Comment by miketaylr** [comment]
Seems like a good plan!

**Comment by cch5ng** [comment]
@miketaylr (apologize in advance that I will probably post a bunch of notes/questions but will try to break them as different comments)

in order to address [checkbox 1 (understand which intern tests are failing locally/travis)](https://github.com/webcompat/webcompat.com/issues/980#issue-143386485), I updated my repo and was getting an error about missing dojo/loader in response to trying to run intern tests locally.

this appeared to be resolved by upgrading the intern version (3.4.0 => 3.4.2), which then seemed to upgrade dojo (2.0.0-dev to 2.0.0-alpha.7). I was wondering if other people have run into this error recently as well (is irc the best place to ask now?).

**Comment by cch5ng** [comment]
@miketaylr these are notes and questions re CONTRIBUTING.md for testing setup.

```
Add the client id and client secret to secrets.py. If you're part of the webcompat GitHub organization, you can get the client id and client secret from GitHub. Otherwise, create your own test and production applications (instructions here) — when prompted for a "Authorization callback URL", use http://localhost:5000/callback,(Cloud 9 users should use http://yourapp.c9users.io:8000/callbackinstead) and take note of the client id and client secret GitHub gives you.
```

I'm not positive I did this correctly. I tried to click the link to get client id/secret, it gives a 404 error on github (is that due to not having access rights?). I created a dummy application on github to get client id and secret and put those into secrets.py.

**Comment by cch5ng** [comment]
@miketaylr these are local intern tests that are failing for me currently. a few are failing b/c I just was not fast enough to enter the github 2fa auth code in the UI. but are any of the auth tests expected to fail currently? also would it would be nice to push all tests requiring authentication to a separate file and to default those test to run at the very beginning?

![1webcompat_local_test_fail2017-02-18](https://cloud.githubusercontent.com/assets/4755432/23099637/b9ef6b8c-f620-11e6-8c89-1e1934aecdb1.png)

**Comment by cch5ng** [comment]
@miketaylr after running intern tests locally, from the terminal running the server, there are errors related to missing fixture files. but I can see these files in the local repo, so I am wondering if there may be something wrong with my configuration...

```
127.0.0.1 - - [17/Feb/2017 18:14:38] "GET /issues?page=1&per_page=50&state=open&stage=needstriage&sort=created&direction=desc HTTP/1.1" 200 -
Expected fixture file: /webcompat.com/tests/fixtures/api/issues/labels.6665c4820456e6a813dcbbdddd690ffc.json
127.0.0.1 - - [17/Feb/2017 18:14:38] "GET /api/issues/labels?per_page=100 HTTP/1.1" 200 -
Expected fixture file: /webcompat.com/tests/fixtures/api/issues/category/needstriage.cf431ca7f9fa9e70723c39e7d4d2725f.json
127.0.0.1 - - [17/Feb/2017 18:14:38] "GET /api/issues/category/needstriage?page=1&per_page=50&state=open&stage=needstriage&sort=created&direction=desc HTTP/1.1" 200 -
Expected fixture file: /programming/web/mozilla_webcompat/fix071216/webcompat.com/tests/fixtures/api/issues/category/needstriage.json
127.0.0.1 - - [17/Feb/2017 18:14:40] "GET /api/issues/category/needstriage HTTP/1.1" 200 -
```

**Comment by miketaylr** [comment]
> his appeared to be resolved by upgrading the intern version (3.4.0 => 3.4.2), which then seemed to upgrade dojo (2.0.0-dev to 2.0.0-alpha.7). I was wondering if other people have run into this error recently as well (is irc the best place to ask now?).

It's possible, I think I even ran into that issue. I tend to just `rm -rf node_modules` before doing any upgrade, because I expect everything to fail. if you think a note in CONTRIBUTING.md would be useful, please file an issue or send in a PR. :)

**Comment by miketaylr** [comment]
> I tried to click the link to get client id/secret, it gives a 404 error on github (is that due to not having access rights?). I created a dummy application on github to get client id and secret and put those into secrets.py.

@zoepage is this link 404 for you as well? You both are part of the "core devs" group, in theory it should work: https://github.com/organizations/webcompat/settings/applications/

**Comment by miketaylr** [comment]
> after running intern tests locally, from the terminal running the server, there are errors related to missing fixture files. but I can see these files in the local repo, so I am wondering if there may be something wrong with my configuration...

@cch5ng Did you start the local server with the `-t` flag, e.g., `python run.py -t`?

**Comment by miketaylr** [comment]
> (edit) I feel like the test failures might be due to something wrong with my config b/c it seems they are mostly the ones requiring authentication.

@cch5ng are you using the test bot's credentials? Or your own?

**Comment by zoepage** [comment]
@miketaylr 

> @zoepage is this link 404 for you as well? You both are part of the "core devs" group, in theory it should work: https://github.com/organizations/webcompat/settings/applications/

its a 404. Got mine through ->https://github.com/settings/applications/new

(Yes, we need to update that info in CONTRIBUTE.md. Will add to #1314 )

**Comment by miketaylr** [comment]
Ah, bad URL. Thanks!

**Comment by miketaylr** [comment]
@cch5ng Ah.....I removed the code you had added for the 2FA delay when I did the Intern 3 upgrade. I had intended to file a bug to add it back... but forgot. :(

Sorry about that. 😢 

https://github.com/webcompat/webcompat.com/pull/1277/files#diff-6a3371457528722a734f3c51d9238c13L463

> also would it would be nice to push all tests requiring authentication to a separate file and to default those tests to run at the very beginning?

We can change the order of those here: https://github.com/webcompat/webcompat.com/blob/master/tests/functional-all.js

I had split out https://github.com/webcompat/webcompat.com/blob/master/tests/functional-nonauth.js to run for fork PRs since they don't have auth credentials, but they end up failing because the non-auth tests run out of GitHub API requests coming from Travis IPs (IIRC).

**Comment by cch5ng** [comment]
@miketaylr re
> Did you start the local server with the -t flag, e.g., python run.py -t?

I ran the tests with the -t flag (the missing fixture errors were seen with the -t flag)

**Comment by cch5ng** [comment]
follow up to [checkbox 1](https://github.com/webcompat/webcompat.com/issues/980#issue-143386485) for failing nonauth tests, there is one currently known failing test:
issue #1368. 

decided to separate the list of known failing tests by nonauth and auth groupings for this time and focus on the nonauth tests group for now. should probably also follow up with documenting the auth tests that are currently failing locally.

**Comment by cch5ng** [comment]
revisiting checkbox 1 (resolve currently failing intern tests)

observed that it should probably just be a requirement when running local tests to always use server with fixture files
```
python run.py -t
```

then running only non auth tests locally => all tests pass consistently (2x, 3rd time, one timeout issue but could be my isp b/c see hangtime with dns lookups)

* CONTRIBUTING.md should be updated accordingly; I'm not quite sure when is a good scenario you'd want to run test w/o fixture files b/c there is at least one test that is dependent on having the fixture file(s) served (issues-non-auth.js => Issue comments load)

**Comment by brizental** [comment]
Closing this off so we can start fresh at #1666

**Comment by brizental** [comment]
Closing this off so we can start fresh at #1666 :)
