### ISSUE TITLE
[bug] non clickable labels

### ISSUE THREAD

**Issue by karlcow** [webcompat/webcompat.com#981]
![capture d ecran 2016-03-25 a 13 49 32](https://cloud.githubusercontent.com/assets/505230/14038198/bd969bc8-f290-11e5-9f44-59121f065049.png)

On issue individual pages, the labels are non clickable 

1. Go to https://webcompat.com/issues/707
2. Click on ie

Nothing happens. All the ie issues should pop up.

**Comment by miketaylr** [comment]
Yeah, that's what I would expect too.
