### ISSUE TITLE
New issues aren't getting browser labels applied to them.

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat.com#983]
New issues aren't getting the browser labels applied to them.

For example, https://github.com/webcompat/web-bugs/issues/2394 -- that should have a "browser-firefox-mobile" label.

**Comment by miketaylr** [comment]
I wonder if the changes in https://github.com/webcompat/webcompat.com/commit/871a4b7fec0a670dadd89ab9c3fb682cf053b0de are related?

Want to investigate @dshgna?

**Comment by dshgna** [comment]
@miketaylr Really sorry about this. Figured it out and it now works fine locally. However, I think we will need to add a separate label for Tablet....
