### ISSUE TITLE
Report Site Issue failed with Firefox Nightly

### ISSUE THREAD

**Issue by karlcow** [webcompat/webcompat.com#985]
It seems that at least @lissyx has issues with Report a Site issues on Firefox Nightly when reporting bug to webcompat. It would be good to know a bit more the circumstances. He tried for example yesterday to fill a bug for ryanair Web site and it failed. 

I wonder if the sequence is 
1. "report a site issue", then login dance to github
2. or already logged in and report a site issue.

cc @miketaylr who made the feature in Firefox Android.

**Comment by karlcow** [comment]
It could be our side, it could be the side of Firefox.

**Comment by lissyx** [comment]
I used the "anonymous" reporting feature. I got the spinner after tapping on it. Then it stays like this until this morning (yes, the whole night).

Circumstances were that I wanted to report broken Ryanair website on Nightly/Android

**Comment by miketaylr** [comment]
It sounds like the same thing as #986. Possibly we broke something -- going to take a look with @adamopenweb shortly.

**Comment by miketaylr** [comment]
Adam posted a stacktrace from the error that's throwing in https://github.com/webcompat/webcompat.com/issues/986#issue-144337969.

**Comment by miketaylr** [comment]
@lissyx by chance were you using the Webcompat Reporter add-on?

https://addons.mozilla.org/en-US/firefox/addon/webcompatcom-reporter/

**Comment by miketaylr** [comment]
Actually, it sounds like @lissyx was using the built-in "Report Site Issue" menu from Firefox for Androd. Can you confirm?

**Comment by lissyx** [comment]
Yes, I was using the built-in report site issue.

**Comment by miketaylr** [comment]
Thanks this should be fixed now. Let me know if you run into any other issue.
