### ISSUE TITLE
Make a nicer looking error message for "image is too big" error

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat.com#995]
Right now it looks hilariously bad, but it's still an improvement over a nginx 413 page.

![](https://cldup.com/8Y6MXypyYa-2000x2000.png)

@magsout, would it be possible to make a red banner with white text similar to the "Remove Image Upload" banner we have? 

![](https://cldup.com/6fzIepWFt6-3000x3000.png)

(It wouldn't need to be a button, just plain text should be OK i think?)

**Comment by karlcow** [comment]
Heh. Hilariously bad could be moved to hilariously funny. :question: 
Like the fly from the lightbulb who would have eaten too much. 
But as a first step. The submit button should be blocked and maybe the message should be inside the yellow area.

**Comment by miketaylr** [comment]
Hehe, I like the idea of using a stuffed fly. :pizza: :bee: 


> But as a first step. The submit button should be blocked and maybe the message should be inside the yellow area.

Agreed. #996 makes the submits disabled. I was also thinking we could maybe change the yellow area to be red, with white text containing the error message.

**Comment by magsout** [comment]
Message error in red at the bottom.
Close button on top/right


![capture d ecran 2016-04-08 a 09 03 31](https://cloud.githubusercontent.com/assets/1997108/14376421/b50f0178-fd69-11e5-880b-b4c7268d6182.png)

**Comment by miketaylr** [comment]
Looks nice! I wonder if we can remove the close image, or at least make "choose an image" a hyperlink (or something that looks like a hyperlink, could be a button) that opens the image picker.

Or maybe the close image button also opens the file picker too?

**Comment by magsout** [comment]
>Looks nice! I wonder if we can remove the close image, or at least make "choose an image" a hyperlink (or something that looks like a hyperlink, could be a button) that opens the image picker.

Ah yes, good point. Hum So icon is not enough and revelant..
