### ISSUE TITLE
better labeling for the project

### ISSUE THREAD

**Issue by karlcow** [webcompat/webcompat.com#997]
Discussion/Brainstorming for London probably.

We do have some labeling which is pretty decent, but sometimes confusing. 
The more details we try to be and the more difficult it will be to get it right.

`browser-firefox` we know we are talking about a brand, but then if you start thinking **for this label** about `ios`, `desktop`, `android`, `mobile`, `firefox os`, `iot-lol`, etc. it starts to become very muddy.
#886 will help with status. I was wondering if we should have a very limited strict category of namespaces and one which is free. When we refactored the labels, in the initial proposal, we had things such as `os-` etc.

`browser-firefox-mobile` is firefox on firefox os? on ios? on android? Maybe it would be better to have: `browser-firefox` and `os-firefox`.

The same way we could have labels for actions such as `to-karlcow` as the notifications system is really not that good on GitHub in terms of longterm.

**Comment by karlcow** [comment]
it's a follow-up on  Organize labels #436

**Comment by miketaylr** [comment]
So the proposal is to have a "browser" and an "os" label for each report? That sounds good to me.

@karlcow can you explain "to-karlcow"?

**Comment by karlcow** [comment]
So there are categories of information around bugs.

* [x] issues-status which is a kind of action-status
* [x] browser-brand
* [ ] os-brand
* [ ] form-factor
* [ ] issues-dependency (intertwined issues through duplicate, bugs family (same company, same library), etc. )
* [ ] call-to-action in between humans

Right now github offers a notification system based on @miketaylr if the person has not deactivated the notifications. Can become very noisy. The other issue is that it is a one time notification, but not a reminder of action.  It means that people forget to answer/take action. Bugzilla has needinfo which is a reminder of actions. It creates an icon signal in the WebUI until the person decided to take an action about it, or someone else replied for the request.

a `to-karlcow` whatever the namespace could be a system either through tagging or prose in the comment such as `@karlcow ni` that would record the date and the comment of the question and probably displays it in your personal activity page and would stay there until you ack on it.

Is it clearer?

**Comment by miketaylr** [comment]
Ah yes. So using a label as a persistent reminder for an individual (that can be removed). 

I think it's a good idea.

**Comment by adamopenweb** [comment]
From discussion on IRC, it might be helpful to have a label for bugs that are "moved to browser vendor". If a bug is moved it could be for different reasons. Should we just mark as an "invalid" web compatibility bug? Or should these be called out explicitly with a label?

**Comment by miketaylr** [comment]
> it might be helpful to have a label for bugs that are "moved to browser vendor"

I think "invalid" doesn't really convey the idea that it's a real bug -- but it's due to the browser being buggy. Not sure the best terms to describe... "upstreamed", "moved", "lol sorry".

**Comment by karlcow** [comment]
> From discussion on IRC, it might be helpful to have a label for bugs that are "moved to browser vendor". I

Usually in the past, we often used "duplicate" + closed. But indeed a label could be something dup-bugnumber over there and when such label is detected, the UI could give a link to say that go look over there.

**Comment by karlcow** [comment]
Example: https://webcompat.com/issues/1416#issuecomment-184450841
Though maybe I'm the only one to do that. I noticed mike just close without changing labels.

**Comment by karlcow** [comment]
Now that milestones are out of the way, we can probably think about this one a bit more.

**Comment by karlcow** [comment]
Followup on #2531

**Comment by karlcow** [comment]
A resolution has been reached in https://github.com/webcompat/webcompat.com/issues/2372#issuecomment-400903755
