### ISSUE TITLE
[feature] domain name search for webcompat.com

### ISSUE THREAD

**Issue by karlcow** [webcompat/webcompat.com#999]
Probably related to #865
But could work on his own.

if we had a keyword `domain` or `site`, we could interesting stuff in terms of search

`site:google.com` will pull out all the bugs about google.com. How to make it work right now?

using Github's `is:issue google.com in:title` 

Example: https://github.com/webcompat/web-bugs/issues?utf8=%E2%9C%93&q=is%3Aissue+google.com+in%3Atitle

**Comment by MDTsai** [comment]
Simple idea: if search keyword contains **site:google.com**, then transform to **google.com in:title**
Guess I can do something in updateIssues, issue-list.js to make this happen? still trace source code
